### ISSUE TITLE
Extending the Helm chart configuration

### ISSUE THREAD

**Issue by morarucostel** [oauth2-proxy/oauth2-proxy#1005]
Creating a new item to track the differences between our [chart](https://github.com/boomerang-io/charts/tree/main/bmrg-auth-proxy) and this one and hopefully incorporate them here.

## Expected Behavior

I believe there are 3 main differences which can be added in this one:
**1. We can set the 'authenticatedEmailsFile' as a secret or configmap, depending on what mechanism is wanted.**
```
  allowEmailList:
    enabled: false
    # How the email-list file will be projected, via a configmap or secret
    persistence: configmap
    # Name of the external secret/configmap to use as allow email-list
    # If not provided it will generate the file based on the provided values
    name:
    # List of allowed email addresses
    emailList:
    - test@ibm.com
    - sample@sample.com
```

**2. Redis is an embedded subchart from "https://charts.bitnami.com/bitnami"**
We decided to use a:
```
redis:
  enabled: false
```
We wanted to use a slim version of redis, thus we defined these values by default in the values, but I guess we can leave them out in this repo (and introduce only the redis.enabled flag):
```
redis:
  enabled: false
  redisPort: 6379
  cluster:
    enabled: false
    slaveCount: 1
  usePassword: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false
```

**3. Default value of "--cookie-name=" in the helm chart should be linked with the release name**
Typically someone has multiple oauth2-proxy releases in their k8s cluster (installed in different namespaces) and they want to avoid that all of them to have the same cookie name. Thus, my suggestion is to expose the name of the cookie in the deployment and default it to {{ .Release.Name | replace "-" "_"}} . 
It might be easy to forget for an end-user to add it in the `configFile` value or extraArgs and then it goes to the default value `_oauth2_proxy`. I don't think is that relevant to exposed it as a stand alone config in the values.

## Possible Solution

Addapt the k8s resources to incorporate the requested changes.

## Steps to Reproduce (for bugs)

NA

## Context

Extending the configuration options for the helm chart

## Your Environment

Any k8s environment.

- Version used:

@tlawrie , @erkannt, @JoelSpeed
