### ISSUE TITLE
Problems with redirect when running behind a reverse proxy that rewrites the basepath

### ISSUE THREAD

**Issue by fmotrifork** [oauth2-proxy/oauth2-proxy#1008]
I am running the oauth2-proxy in kubernetes with a nginx ingress controller.
Here i do load balancing based on the request host and path.

https://my-domain.com/my-service/$2 is rewritten and forwarded to http://my-service/$2

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: my-service
spec:
  rules:
  - host: my-domain.com
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
        path: /my-service(/|$)(.*)
```

In this service I am running the oauth2-proxy as a sidecar to handle that all requests to the service is authenticated.
Both internally in the cluster and from the outside.

To get the redirect from the external OIDC provider to work correctly i have my redirect url set like this:
```env
OAUTH2_PROXY_REDIRECT_URL: "https://my-domain.com/my-service/oauth2/callback"
# Listen externally
OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
# Forward to local, main container
OAUTH2_PROXY_UPSTREAMS: "http://127.0.0.1:8080"
```
On first login i get redirected to the external oidc provider and back to my own domain, as expected, but I loos the `/my-service` part of the path.

## Expected Behavior

 - User visits https://my-domain.com/my-service/page?test=123
 - Redirected to https://idp.example.com/...
 - User logs in
 - Redirected back to https://my-domain.com/my-service/oauth2/callback
 - Finally ends up on https://my-domain.com/my-service/page?test=123

I cannot find a way to configure the oauth2-proxy with a basepath that are prefixed the request path it can see in the request.

The problem is that the oauth2-proxy does not know about the path part that is removed by nginx in the ingress controller step. 

## Current Behavior

 - User visits https://my-domain.com/my-service/page?test=123
 - Redirected to https://idp.example.com/...
 - User logs in
 - Redirected back to https://my-domain.com/my-service/oauth2/callback
 - Finally ends up on https://my-domain.com/page?test=123 # Missing the `/my-service/` path part.

## Possible Solution

Implement a `basepath` config to be used when running behind a reverse proxy using path load balancing.

## Your Environment

Oauth2-proxy config:

```bash
OAUTH2_PROXY_PROVIDER=oidc
OAUTH2_PROXY_REDIRECT_URL=https://my-domain.com/my-service/oauth2/callback
OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
OAUTH2_PROXY_EMAIL_DOMAINS=*
OAUTH2_PROXY_UPSTREAMS=http://127.0.0.1:8080
OAUTH2_PROXY_EXTRA_JWT_ISSUERS=https://idp.example.com/ 
OAUTH2_PROXY_COOKIE_SECRET= < redacted >
OAUTH2_PROXY_COOKIE_SECURE=false
OAUTH2_PROXY_CLIENT_ID= < redacted >
OAUTH2_PROXY_CLIENT_SECRET= < redacted >
OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
OAUTH2_PROXY_OIDC_ISSUER_URL=https://idp.example.com/
OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS=true
```

- Version used: `quay.io/oauth2-proxy/oauth2-proxy:v6.1.1`

**Comment by JoelSpeed** [comment]
There are solutions already available to resolve your issue, they do however require you to pass information to OAuth2 Proxy at the start of the authentication call.

Based on the fact you have the OAuth2 Proxy as a sidecar, you can add `X-Auth-Request-Redirect` as a header for requests to your upstream and point this to the original URI of the request. This will tell OAuth2 Proxy where to send the request post authentication.

As of v7.0.0 (imminent release), you will also be able to supply `X-Forwarded-URI` as an alternative to the above header, but it will still want the same value

**Comment by fmotrifork** [comment]
I am not sure I understand your proposal.

I am using OAuth2 Proxy as a sidecar to filter all traffic before it hits my actual applications. That means that I don't actually start the authentication call explicitly myself. And as the clients that uses the redirect flow is browsers, I cannot expect them clients to send a `X-Auth-Request-Redirect` header along.

Are you proposing that I make nginx ingress send the `X-Auth-Request-Redirect` along with all requests coming to the cluster?

**Comment by JoelSpeed** [comment]
> Are you proposing that I make nginx ingress send the X-Auth-Request-Redirect along with all requests coming to the cluster?

Yes, you could add this at your ingress layer so that OAuth2 Proxy knows where to send the user should it need to log them in/perform the redirect. It could be under `X-Auth-Request-Redirect` or under `X-Forwarded-URI` post v7 release

**Comment by fmotrifork** [comment]
Thanks @JoelSpeed 
I solved the redirect problem with the `X-Auth-Request-Redirect` in the nginx ingress.

Final ingress ended up looking like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: 'proxy_set_header X-Auth-Request-Redirect  $request_uri;'
  name: my-service
spec:
  rules:
  - host: my-domain.com
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
        path: /my-service(/|$)(.*)
```
