### ISSUE TITLE
Redirect loop with Traefik forward auth

### ISSUE THREAD

**Issue by FlomoN** [oauth2-proxy/oauth2-proxy#1019]
Hi guys,
I'm trying to use this behind Traefik 2.3 on Kubernetes (k3s), therefore I followed the instructions that were given in the docs, as closely as I could. I'm serving the oauth2-proxy on a different domain than the application Im trying to protect. The problem that occurs is that when I try to access my application (`x.otherdomain.de`) it gets 401 and serves the login prompt page (for some reason the URL doesn't change it is still `x.otherdomain.de` and not `auth.domain.de`). When I click on "Sign-In with GitHub" now, I get 401 again and it serves the same page again, but now from `https://x.otherdomain.de/oauth2/start?rd=https%3A%2F%2Fx.otherdomain.de%2F`. From there on the loop continues. No Cookies get set or anything.

The logs from oauth2-proxy always show:

```
[2021/02/03 23:59:29] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.42.0.1 - - [2021/02/03 23:59:29] auth.domain.de GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" 401 13 0.000
10.42.0.1 - - [2021/02/03 23:59:29] x.otherdomain.de GET - "/oauth2/sign_in" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36" 200 2645 0.
```

I also don't really understand which configurations are necessary, so maybe I'm just missing something super obvious.

## Expected Behavior

Working login.

## Current Behavior

See above

## Possible Solution

-

## Steps to Reproduce (for bugs)

My Configuration for oauth2proxy looks as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.0.0
          ports:
            - containerPort: 4180
          args:
            - "--reverse-proxy=true"
            - "--cookie-domain=.domain.de,.otherdomain.de"
            - "--whitelist-domain=.domain.de,.otherdomain.de"
            - "--provider=github"
            - "--github-org=domain-de"
            - "--client-id=xxxxxxxx"
            - "--client-secret=xxxxxxx"
            - "--cookie-secret=xxxxxxxxxx"
            - "--email-domain=*"
            - "--http-address=0.0.0.0:4180"
            - "--real-client-ip-header=X-Forwarded-For"
---
#
# Auth Service
#
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: auth
  labels:
    app: oauth2-proxy
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy
  ports:
    - name: auth-http
      port: 4180
      targetPort: 4180
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: oauth2-proxy
  namespace: auth
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth-auth-headers@kubernetescrd
spec:
  rules:
    - host: auth.domain.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180
---
#
# Auth Middleware
#
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: auth
  name: fwauth
spec:
  forwardAuth:
    #    address: https://oauth2-proxy.auth.svc.cluster.local:4180/oauth2/auth
    address: https://auth.domain.de/oauth2/auth
    trustForwardHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: auth
  name: fwauth-errors
spec:
  errors:
    status:
      - "401-403"
    query: "/oauth2/sign_in"
    service:
      name: oauth2-proxy
      port: 4180
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: auth
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: domain.de
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure-chain
  namespace: auth
spec:
  chain:
    middlewares:
      - name: redirect-ssl
        namespace: traefik
      - name: fwauth-errors
      - name: fwauth


```

The Ingress the app is served with over `x.otherdomain.de` uses the secure-chain middleware.

## Your Environment

- k3s v1.20
- Traefik 2.3.6

- Version used: 7.0.0
