### ISSUE TITLE
Authorization Bearer header does not get passed

### ISSUE THREAD

**Issue by jonkerj** [oauth2-proxy/oauth2-proxy#1034]
Following up on #773, which is closed, I am trying to get oauth2-proxy to pass the `Authorization: Bearer` header upstream, but I cannot seem to get it to work. I am using `--pass-authorization-header true` and `pass-basic-auth false` (amonst other flags). This might be a bug.

## Expected/Current Behavior

I would expect the header to get passed upstream, but it doesn't. Upstream is a HTTP echo server, showing me the request headers, which do not contain `Authorization`.

## Steps to Reproduce (for bugs)

This is my setup:
1. Setup Keycloak, create a client
2. Install oauth2 using Helm (from https://charts.helm.sh/stable, v3.2.5) with the values as below
3. Install echo server using Helm (https://ealenn.github.io/charts, v0.3.0) with default values
4. Visit the HTTP endpoint of oauth2, authenticate

Values:
```yaml
image:
   repository: quay.io/oauth2-proxy/oauth2-proxy
   tag: v7.0.0
configFile: |
  email_domain = "REDACTED"
  provider = "keycloak"
  login_url = "https://REDACTED/auth/realms/REDACTED/protocol/openid-connect/auth"
  redeem_url = "https://REDACTED/auth/realms/REDACTED/protocol/openid-connect/token"
  validate_url = "https://REDACTED/auth/realms/REDACTED/protocol/openid-connect/userinfo"
  upstream = "http://echo-server/"
  scope = "email"
  skip_provider_button = true
  skip_jwt_bearer_tokens = true
  pass_basic_auth = false
  pass_authorization_header = true
config:
  existingSecret: oauth2-secret
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts: ['REDACTED']
  tls:
  - hosts: ['REDACTED']
    secretName: oauth2-tls
```

## Context

This feature is needed to use oauth2-proxy in front of Kubernetes dashboard, which is blocking my/our transition from the retired keycloak-gatekeeper to oauth2-proxy. This was supposed to be fixed in issue #773/#869, but that does not seem to work for me (header does not get passed).

## Your Environment

I am using the Docker image v7.0.0 on Kubernetes with the settings per above

**Comment by NickMeves** [comment]
So what I think is happening is the `--pass-authorization-header` injects the ID Token to the upstream (for providers that provide it -- meaning OIDC capable and not barebones OAuth2).

The `keycloak` provider is barebones OAuth2 (even though Keycloak is OIDC capable).  This is something we intend to overhaul with the Keycloak provider.

So my guess is you don't have an ID Token, so nothing gets passed. I recommend you use your Keycloak instance with the OIDC provider until we overhaul the Keycloak provider and make it use OIDC (which apparently we need to do if the latest Keycloak doesn't support our legacy Keycloak provider: https://github.com/oauth2-proxy/oauth2-proxy/issues/1033)

**Comment by jonkerj** [comment]
Hi, really appreciate your help! I thought tested that before, with the same result, but to be sure, I switched from `keycloak` to `oidc` by changing the provider, removing all `_url` parameters, adding the `oidc_issuer_url` and changing the scope to `email openid` (it was complaining about not getting an `id_token`). Now I am facing different issues

When I sign in on my IDP (keycloak, backed by Google), I get a 502 from oauth2-proxy. Its logs tell me:
```
[stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
```

At the same time, keycloak is not very happy too:

```
WARN  [org.keycloak.protocol.oidc.utils.OAuth2CodeParser] (default task-23) Code '55f5ccbc-de35-49f0-9a26-f50ef130135a' already used for userSession 'a0e43393-699d-4d77-8162-807061b620e9' and client '1500e6c5-18a1-4b3a-8279-7dd4b312653f'.
WARN  [org.keycloak.events] (default task-23) type=CODE_TO_TOKEN_ERROR, realmId=9ka, clientId=kubernetes, userId=null, ipAddress=172.21.46.13, error=invalid_code, grant_type=authorization_code, code_id=a0e43393-699d-4d77-8162-807061b620e9, client_auth_method=client-secret
```

I did some googling and reading, and found #941, but I am not sure if this is the same issue, as my call to `/oauth2/callback` throws 502s and does not get to the point where it is setting cookies.

**Comment by JoelSpeed** [comment]
There should be additional logs for the 502 that tell you why the 502 occurred. If you can't find that you could also try using the master branch which has updated error page rendering which should give you more information about this particular failure.

If you are using the OIDC provider, please try removing the scope flag and use the default (`openid profile email`) to eliminate scope issues (IIRC technically `openid` is supposed to come first)

**Comment by jonkerj** [comment]
This is all the logging I get around the 502:
```
[2021/02/15 10:28:00] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.233.125.16:39774 - - [2021/02/15 10:28:00] echo.9ka.nl GET - "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36" 302 291 0.000
10.233.125.16:39774 - jorik@kippendief.biz [2021/02/15 10:28:00] [AuthSuccess] Authenticated via OAuth2: Session{email:jorik@kippendief.biz user:3278e5da-ba7e-4979-ae46-690c50b461f5 PreferredUsername:jorik@kippendief.biz token:true id_token:true created:2021-02-15 10:28:00.769078258 +0000 UTC m=+108.816160018 expires:2021-02-15 10:33:00.768547971 +0000 UTC m=+408.815629724 refresh_token:true groups:[argocd k8s-admin offline_access uma_authorization Admin]}
10.233.125.16:39774 - - [2021/02/15 10:28:00] echo.9ka.nl GET - "/oauth2/callback?state=ce4182cdcc0fb06164829ca95fd0497d%3A%2F&session_state=121f8428-b455-4c0c-a9a7-e4b459aa4e76&code=b8b11a07-8b3e-489a-b71e-e3a8f4212a4d.121f8428-b455-4c0c-a9a7-e4b459aa4e76.1500e6c5-18a1-4b3a-8279-7dd4b312653f" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36" 302 24 0.020
[2021/02/15 10:28:00] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.233.125.16:39776 - - [2021/02/15 10:28:00] REDACTED GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36" 302 302 0.000
10.233.125.16:39776 - jorik@kippendief.biz [2021/02/15 10:28:00] [AuthSuccess] Authenticated via OAuth2: Session{email:REDACTED user:REDACTED PreferredUsername:REDACTED token:true id_token:true created:2021-02-15 10:28:00.938583236 +0000 UTC m=+108.985665018 expires:2021-02-15 10:33:00.938006655 +0000 UTC m=+408.985088420 refresh_token:true groups:[REDACTED offline_access uma_authorization Admin]}
10.233.125.16:39776 - - [2021/02/15 10:28:00] REDACTED GET - "/oauth2/callback?state=983316d634e6103eb659635abd52f586%3A%2Ffavicon.ico&session_state=121f8428-b455-4c0c-a9a7-e4b459aa4e76&code=691e6911-1018-4a48-96dc-242f69fdb3f2.121f8428-b455-4c0c-a9a7-e4b459aa4e76.1500e6c5-18a1-4b3a-8279-7dd4b312653f" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36" 302 35 0.022
```

I have built and deployed master, still gives me a 502 (bad gateway), which is getting served by nginx (my ingress controller). Nginx does not log anything special. When I reload the 502'ing page, it does give a nice page. When I click "more info", it tells me "Oops! Something went wrong. For more information contact your server administrator."

I tried removing the scope flag (I like the suggestion, don't know why I did not stick with the default), it does not affect above errors.

**Comment by JoelSpeed** [comment]
There's nothing in the log there that implies that OAuth2 Proxy is the one responding with the 502 error, so not sure why Nginx would report that.

There's a couple of things you could try, `--show-debug-on-error` should show more details errors than the oops something went wrong message, and also you could try `--session-cookie-minimal` to determine if it's some problem with the response from OAuth2 Proxy being too large

**Comment by jonkerj** [comment]
Took me a while to test this, sorry for that, really appreciate the help. The cluster I was debugging this issue on has gotten some serious refactoring in the meanwhile (new CD system, switch to Talos). I am not able to reproduce the 502 anymore, I might have made a typo in the flag providing the upstream earlier (https instead of http). But, the authorization header is not getting passed either. 

I am running a git build from commit ce29b16. My current config, to recap:

```
--http-address=0.0.0.0:4180
--email-domain=REDACTED
--oidc-issuer-url=https://REDACTED/auth/realms/REDACTED
--pass-authorization-header=true
--pass-basic-auth=false
--provider=oidc
--show-debug-on-error=true
--skip-jwt-bearer-tokens=true
--skip-provider-button=true
--ssl-upstream-insecure-skip-verify=true
--upstream=http://kubernetes-dashboard-echo-server
--config=/etc/oauth2_proxy/oauth2_proxy.cfg
```
That particular config holds:

```
email_domains = [ "*" ]
upstreams = [ "file:///dev/null" ]
```
This configfile was templated by Helm, but as the correct upstream is found, I don't think its messing things up.

I tried the setting `session-cookie-minimal`; it does not work when forwarding authorization header (but I don't need it since its not 502'ing anymore):
```
[2021/02/23 12:23:52] [main.go:58] invalid configuration:
  id_token claim for header "Authorization" requires oauth tokens in sessions. session_cookie_minimal cannot be set
```

To quickly check if the header is getting passed, I'm using [echo-server](https://github.com/Ealenn/Echo-Server), which does not show me the header.

So, anything else I can try?

**Comment by fabbarix** [comment]
@jonkerj I currenlty have OAUth2 Proxy in front of Kubernetes Dashboard - my OAuth2 Proxy configuration, for ingress-nginx - looks like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
     k8s-app: oauth2-proxy
   name: oauth2-proxy
   namespace: ingress-nginx
spec:
   replicas: 1
   selector:
     matchLabels:
       k8s-app: oauth2-proxy
   template:
     metadata:
       labels:
         k8s-app: oauth2-proxy
     spec:
       containers:
         - args:
             - --provider=oidc
             - --oidc-issuer-url=https://xxxxx/auth/realms/yyyyyy
             - --skip-provider-button=true
             - --email-domain=*
             - --scope=openid
             - --set-authorization-header=true
             - --login-url=https://xxxxxx/auth/realms/kubernetes/protocol/openid-connect/auth
             - --redeem-url=https://xxxxxx/auth/realms/kubernetes/protocol/openid-connect/token
             - --profile-url=https://xxxxx/auth/realms/kubernetes/protocol/openid-connect/userinfo
             - --validate-url=https://xxxxx/auth/realms/kubernetes/protocol/openid-connect/userinfo
             - --upstream=file:///dev/null
             - --http-address=0.0.0.0:4180
           envFrom:
             - secretRef:
                 name: oauth2-proxy-info
           image: quay.io/oauth2-proxy/oauth2-proxy:v7.0.1
           imagePullPolicy: Always
           name: oauth2-dash-proxy
           ports:
             - containerPort: 4180
               protocol: TCP
```
*Note the `--set-authorization-header=true`*

The `oauth2-proxy-info` points to a secret that looks like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-info
  namespace: ingress-nginx
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: xxxxxxxxxxxxxxxxxxxx
  OAUTH2_PROXY_CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  OAUTH2_PROXY_COOKIE_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxxx
```

The service I created for it:

```yaml
apiVersion: v1
kind: Service
metadata:
   labels:
     k8s-app: oauth2-proxy
   name: oauth2-proxy
   namespace: ingress-nginx
spec:
   ports:
     - name: http
       port: 4180
       protocol: TCP
       targetPort: 4180
   selector:
       k8s-app: oauth2-proxy
```

My dashboard ingress looks a bit like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   annotations:
     cert-manager.io/cluster-issuer: letsencrypt
     nginx.ingress.kubernetes.io/auth-response-headers: authorization
     nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
     nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
     nginx.ingress.kubernetes.io/backend-protocol: HTTPS
   name: kubernetes-dashboard
   namespace: kubernetes-dashboard
spec:
   tls:
     - secretName: dash-web-cert
       hosts:
         - xxxx.xxxx.xxxx
   rules:
     - host: xxxx.xxxx.xxxx
       http:
         paths:
           - path: /
             pathType: ImplementationSpecific
             backend:
               service:
                 name: kubernetes-dashboard
                 port:
                   number: 443
---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: oauth2-dashboard-proxy
   namespace: ingress-nginx
   annotations:
     cert-manager.io/cluster-issuer: "letsencrypt"
     nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
spec:
   tls:
     - secretName: dash-web-cert
       hosts:
         - xxxx.xxxx.xxxx
   rules:
     - host: xxxx.xxxx.xxxx
       http:
         paths:
           - path: /oauth2
             pathType: ImplementationSpecific
             backend:
               service:
                 name: oauth2-proxy
                 port:
                   number: 4180
```
Make sure `cert-manager.io/cluster-issuer` points to the cert manager issuer you want to use.

The `nginx.ingress.kubernetes.io/proxy-buffer-size: 64k` is there to resolve some `502` errors due to the size of some of the
cookies flying around.

The only issue with this current setup is that the `access_token` expires in 5 minutes by default - you can change that in the keycloak settings for the client - and I can't figure out how to make it use the refresh token.

**Comment by jonkerj** [comment]
Hi there,

I implemented all of your suggestions:
- External authentication through ingress (instead of proxy-ing everything)
- `set-authorization-header` (instead of `pass-`)
- increase proxy buffer size for large cookies

And it all works. I do not fully get which of these three modifications made it working, but after having spent many hours debugging this issue I'm glad to have a working setup and am nog going to look back 😄 

Thanks!

**Comment by hkiang01** [comment]
@jonkerj
 
> And it all works. I do not fully get which of these three modifications made it working, but after having spent many hours debugging this issue I'm glad to have a working setup and am nog going to look back 

Can you paste what your final config ended up looking like?

**Comment by jonkerj** [comment]
Sure. I'm using oauth2 in auth forward mode: the ingress resources carry the annotations per my previous comment. The oauth2-proxy has these arguments/env:
```
args:
- --http-address=0.0.0.0:4180
--- email-domain=REDACTED
- --oidc-issuer-url=REDACTED
- --provider=oidc
- --set-authorization-header=true
- --show-debug-on-error=true
- --skip-provider-button=true
- --whitelist-domain=REDACTED
- --config=/etc/oauth2_proxy/oauth2_proxy.cfg
env:
- name: OAUTH2_PROXY_CLIENT_ID
  valueFrom:
    secretKeyRef:
      key: client-id
      name: oauth2-secret
- name: OAUTH2_PROXY_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      key: client-secret
      name: oauth2-secret
- name: OAUTH2_PROXY_COOKIE_SECRET
  valueFrom:
    secretKeyRef:
      key: cookie-secret
      name: oauth2-secret
```

I'm using a docker image which is based on a fairly recent post v7.0.1 master checkout. 7.0.1 contains a bug regarding the order of argument overrides.
