### ISSUE TITLE
Azure returns int "expires_on" value as number instead of expected string value for code redemption

### ISSUE THREAD

**Issue by lenalebt** [oauth2-proxy/oauth2-proxy#1048]
I was trying to integrate oauth2-proxy (v7.0.1) with the "azure" provider. When trying to redeem the authorization code, it logs an error:
```
[2021/02/15 15:17:46] [oauthproxy.go:753] Error redeeming code during OAuth2 callback: error unmarshalling body: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into int64
```
I manually tried to redeem the code it was getting (using curl), and that was azures response:
```json
{
  //...
  "expires_on":1613405888,
  //...
}
```

I wonder to some extent whether one can misconfigure azure to return the expires_on as a number, or whether something changed on azure side (we're using the "v2.0" apis on azure side, unsure whether that has an impact).

## Expected Behavior

The code should be able to parse the `expires_on` as a number when it's being returned as a number.

## Current Behavior

Referring to this code:
https://github.com/oauth2-proxy/oauth2-proxy/blob/v7.0.1/providers/azure.go#L189

It expects the `expires_on` to be returned as a string, which apparently is not what is being returned. The tests in `azure_test.go` expect the values to be returned as a string.

## Possible Solution

I'm not deep into golang, but if possible I'd want to allow it to parse both a string and a number (as apparently azure seems to be sending it as a number).

## Steps to Reproduce (for bugs)

I'm sorry, I am not entirely sure how to reproduce it, but see "context".

## Context

I was trying to use the oauth2 proxy to add authentication to a bunch of static webpages (a documentation portal; built with https://antora.org/). We're having a `OAUTH2_PROXY_REDEEM_URL` and a `OAUTH2_PROXY_REDIRECT_URL` set as our login URLs seem to differ from what the defaults are. This is how I start the application currently:

```
podman run -p 8080:8080
 -e OAUTH2_PROXY_REDIRECT_URL=http://localhost:8080/oauth2/callback
 -e OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:8080
 -e OAUTH2_PROXY_PROVIDER=azure
 -e OAUTH2_PROXY_COOKIE_SECRET=<omitted>
 -e OAUTH2_PROXY_EMAIL_DOMAINS='*'
 -e OAUTH2_PROXY_CLIENT_ID=<omitted>
 -e OAUTH2_PROXY_CLIENT_SECRET=<omitted>
 -e OAUTH2_PROXY_AZURE_TENANT=<omitted>
 -e OAUTH2_PROXY_LOGIN_URL=<omitted>
 -e OAUTH2_PROXY_REDEEM_URL=<omitted> -it quay.io/oauth2-proxy/oauth2-proxy:v7.0.1 --scope "openid offline_access <omitted_client_id>"
```
according to azure docs, you need to specify the client id as a scope to get an access token returned when redeeming a code.

## Your Environment

Running in docker / podman.

- Version used: v7.0.1

**Comment by JoelSpeed** [comment]
The code to unmarshal this hasn't changed in over 2 years. Out of interest, if you were to try the OIDC provider with Azure instead, does that work at all? Azure v2 is OIDC compatible and the OIDC provider is better maintained so you might find it works just as well

**Comment by lenalebt** [comment]
Hey, I also wondered about the stable code. It naturally makes me expect that I must be doing something wrong, but on the other hand I could not find a better explanation. Maybe other people are not using it with a private tenant :woman_shrugging: .

I'll try it with the OIDC option some time tomorrow, when I can get access to the azure stuff again (I need help from a colleague for that). Thanks for that suggestion already :).

**Comment by lenalebt** [comment]
Hey, just a short note now - I'll update with some details tomorrow so others can find this more easily. I got it to work using the OIDC provider, but it took me some time to get the URLs right to make it work.

I still wonder why I had problems with the azure provider though. Microsoft did a "v2.0" implementation some time ago (unsure how old that is); maybe that "azure" provider is for the "v1.0" version? If so, it would help to get a few lines in the docs about that, but I may be totally wrong here.

**Comment by lenalebt** [comment]
Sorry for taking so long to add this info. This is what I needed to configure to get everything working (all UUIDs and paths replaced with something random):

```
env:
  - name: OAUTH2_PROXY_PROXY_PREFIX
    value: /foobar
  - name: OAUTH2_PROXY_REVERSE_PROXY
    value: "true"
  - name: OAUTH2_PROXY_SKIP_OIDC_DISCOVERY
    value: "true"
  - name: OAUTH2_PROXY_PROVIDER
    value: oidc
  - name: OAUTH2_PROXY_OIDC_EMAIL_CLAIM
    value: "emails" #took me a while to find out about this
  - name: OAUTH2_PROXY_SCOPE
    value: "openid offline_access e8a829c7-d6fc-4477-ad0f-a9de13487abd"  #yes, this needs to repeat the client id
  - name: OAUTH2_PROXY_CLIENT_ID
    value: "e8a829c7-d6fc-4477-ad0f-a9de13487abd"
  - name: OAUTH2_PROXY_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: oauth2-secrets
        key: CLIENT_SECRET
  - name: OAUTH2_PROXY_LOGIN_URL
    value: "https://barbaz.b2clogin.com/barbaz.onmicrosoft.com/oauth2/v2.0/authorize?p=NAME_OF_FLOW"
  - name: OAUTH2_PROXY_REDEEM_URL
    value: "https://barbaz.b2clogin.com/barbaz.onmicrosoft.com/NAME_OF_FLOW/oauth2/v2.0/token"
  - name: OAUTH2_PROXY_OIDC_ISSUER_URL
    value: "https://barbaz.b2clogin.com/a9bc421d-027f-4703-9c28-8343b30e7a4e/v2.0/" #this UUID is your tenant id
  - name: OAUTH2_PROXY_OIDC_JWKS_URL
    value: "https://login.microsoftonline.com/barbaz.onmicrosoft.com/discovery/v2.0/keys?p=NAME_OF_FLOW"
  - name: OAUTH2_PROXY_REDIRECT_URL
    value: "https://some-external-service/foobar/callback"
```

Hope it will help someone else in the future.
