### ISSUE TITLE
Add support for structured logging (at least JSON)

### ISSUE THREAD

**Issue by Ghazgkull** [oauth2-proxy/oauth2-proxy#1057]
oauth2-proxy should support structured logging. Either in a generic, flexible way or at least by adding support for JSON, which is the most popular structured logging format across a range of ecosystems.

## Expected Behavior

Ideally, it would be possible to tell oauth2-proxy to log in either "json" or "text" format with a simple option.

## Current Behavior

Currently, oauth2-proxy allows clients to pass formatters for Auth, Standard, and Request logging, but these formats are all limited to plain text because messages are not escaped before being passed to the logging template.

Since the strings aren't escaped, they can contain tokens which break the structured log parsing. For example:
```{ "message": "These nested "quotes" are unescaped JSON tokens." }```

## Possible Solution

An example of how Istio (built on envoy) exposes this to clients is with a few flags. For example, here's how I tell Istio's access log to use JSON with my own custom format:

```
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  accessLogFormat: |
    {
      "traceId": "%REQ(x-b3-traceid)%",
      "protocol": "%PROTOCOL%",
      "upstream_service_time": "%RESP(x-envoy-upstream-service-time)%",
      "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
      "duration": "%DURATION%",
      "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
      "route_name": "%ROUTE_NAME%",
      "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
      "user_agent": "%REQ(USER-AGENT)%",
      "response_code": "%RESPONSE_CODE%",
      "response_flags": "%RESPONSE_FLAGS%",
      "start_time": "%START_TIME%",
      "method": "%REQ(:METHOD)%",
      "request_id": "%REQ(X-REQUEST-ID)%",
      "upstream_host": "%UPSTREAM_HOST%",
      "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
      "requested_server_name": "%REQUESTED_SERVER_NAME%",
      "bytes_received": "%BYTES_RECEIVED%",
      "istio_policy_status": "-",
      "bytes_sent": "%BYTES_SENT%",
      "upstream_cluster": "%UPSTREAM_CLUSTER%",
      "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
      "authority": "%REQ(:AUTHORITY)%",
      "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
    }
```

## Steps to Reproduce (for bugs)

1.  Configure oauth2-proxy with --standard-logging-format="{\"message\":\"{{.Message}} ({{.File}})\"}"
  1a. I am actually using the Helm chart, so my config looks like:
  ```
  standard-logging-format: >-
    {
    "message":"{{.Message}} ({{.File}})"
    }
  ```
2.  Start oauth2-proxy
3.  Look at the output. It includes nested double-quotes which break JSON parsing. For example, the very first line of output will be:
```{ "message":"mapping path "/dev/null" => file system "/dev/null" (oauthproxy.go:233)" }```

## Your Environment

- Version used: 5.1.0 consumed through version 3.2.6 of the helm chart

**Comment by JoelSpeed** [comment]
So the solution of having a `logging-format=plain|json` seems like it would be relatively easy to implement within the logger, it would just be a case of marshalling every string to JSON before we pass it in as a template variable.

Would we want to have the ability to specify different formats per our 3 logging types though? :thinking: If so, we would need three different flags

**Comment by terala** [comment]
Proper structured logging is the way to go for JSON logging. Formatting tricks can only go far.

**Comment by JoelSpeed** [comment]
I still think it's good to have the ability for users to format the output even with structured isn't it?

**Comment by terala** [comment]
Absolutely... if the users want to format to suit their needs, they should be given that option. However, when it comes to json, being structured is the best way to achieve it. The `zap` framework that I've used allows manual formatting too.

**Comment by JoelSpeed** [comment]
IMO, the issue with introducing Zap here would be that we would have to ensure our logging and their logging follow a common interface, which I don't think we presently do. If we do, this could be easier to implement than I had thought, otherwise my suggestion is that we add an option to encode the messages in JSON before passing to the template

**Comment by terala** [comment]
I've already implemented zap support earlier. It would be like switching over to zap and then add support for user formatting for non-json. Regardless, having a structured logging is very very helpful for splunk and other logging tools. Text parsing is prone for errors and is a major headache trying to get fields out of the log lines.

**Comment by JoelSpeed** [comment]
Ack! Definitely think we want to support structured logging, but I'm also keen to be flexible and not break existing users who are using the existing formatting options

**Comment by lathspell** [comment]
don't close this, bot!

**Comment by frittentheke** [comment]
> don't close this, bot!

**Comment by lathspell** [comment]
don't close this, bot!

**Comment by frittentheke** [comment]
Please keep this active.

**Comment by lathspell** [comment]
don't close this, bot! (this is getting silly, can't you just disable the bot for this issue?)

**Comment by frittentheke** [comment]
> don't close this, bot! (this is getting silly, can't you just disable the bot for this issue?)

**Comment by frittentheke** [comment]
> don't close this, bot! (this is getting silly, can't you just disable the bot for this issue?)

**Comment by frittentheke** [comment]
> don't close this, bot! (this is getting silly, can't you just disable the bot for this issue?)

+1

**Comment by JoelSpeed** [comment]
This is something I'm planning to look into soon

**Comment by lathspell** [comment]
don't close this, bot!

**Comment by indranilr** [comment]
Facing similar issues in my project (K8 based deployment) where we have been experimenting keycloak oidc. 

We need the capability to produce JSON formatted messages for each log types which would include below information. 

- timestamp ( should be able to format the timestamp as needed)
- severity (Info/error/debug/warn) 
- message (The actual log message)
- Custom key value pairs ( Should be able to additional tags and values, example . "service_id" : "my-app-oauth-proxy" , values could be hard coded , use pre-defined variables or environment variable reference)

**Comment by frittentheke** [comment]
unstale

**Comment by wthrbtn** [comment]
# Fixing JSON logging (while hoping for a native JSON logging feature...)


I ***really*** like oauth2-proxy and I ***really*** needed JSON logging for our current projects.

So like everyone else here I tried everything and I got all the problems with un-escaped characters and so on.

But a few sleepless nights later I have a solution that seems to work so far with everything I have thrown at it...

Please test and see if there is anything that can be improved.

Thanks to @Ghazgkull @JoelSpeed @NickMeves for the inspiration!

Sorry if I have abused something with below template functions. I had Go training some five years ago but I have not used it since. :disappointed:

Kubernetes and Helm charts are my normal comfort zone :smile:

Cheers!

/Jörgen

PS. Redis client errors seems to log to stdout without any formatting. Should they be in the "standard" log?

## Using Go template functions

I have used some [predefined global functions:](https://pkg.go.dev/text/template#hdr-Functions)

```text
js
    Returns the escaped JavaScript equivalent of the textual
    representation of its arguments.
```

```text
slice
    slice returns the result of slicing its first argument by the
    remaining arguments. Thus "slice x 1 2" is, in Go syntax, x[1:2],
    while "slice x" is x[:], "slice x 1" is x[1:], and "slice x 1 2 3"
    is x[1:2:3]. The first argument must be a string, slice, or array.
```

```text
len
    Returns the integer length of its argument.
```

## Examples

### Converting current timestamp to ISO 8601 format "2022-09-29T17:11:34Z"

```go
"timestamp": "{{slice .Timestamp 0 4}}-{{slice .Timestamp 5 7}}-{{slice .Timestamp 8 10}}T{{slice .Timestamp 11 19}}Z"
```

### Escaping message with inline double quotes in the standard log

```go
"message": "{{js .Message}}"
```

So this:

```text
mapping path "/" => upstream "http://postgres-operator-ui.postgres-operator.svc.cluster.local"
```

Would turn into this (there are of course extra fields below):

```json
{
    "file": "proxy.go:89",
    "message": "mapping path \"/\" => upstream \"http://postgres-operator-ui.postgres-operator.svc.cluster.local\"",
    "oauth2_proxy_log_type": "standard",
    "timestamp": "2022-09-29T18:54:07Z"
}
```

### Fixing something that is not broken??

I am not sure I understand fully if the currently already quoted .RequestURI and .UserAgent needed further processing.

But just to be safe I sliced off the double quotes in both ends and ran js and added the quotes again:

```go
"user_agent": "{{slice .UserAgent 1 (len (slice .UserAgent 1)) | js}}"
```

## Sample from my current oauth2-proxy Helm chart values.yaml file with oauth2-proxy JSON logging enabled

### Please note the curly brackets with a backtick to make sure Helm processes the template as a raw string

```yaml
{{`
```

and

```yaml
`}}
```

```yaml
extraEnv:
  - name: OAUTH2_PROXY_AUTH_LOGGING_FORMAT
    value: >-
      {{`{
      "timestamp": "{{slice .Timestamp 0 4}}-{{slice .Timestamp 5 7}}-{{slice .Timestamp 8 10}}T{{slice .Timestamp 11 19}}Z",
      "oauth2_proxy_log_type": "auth",
      "client": "{{.Client}}",
      "username": "{{js .Username}}",
      "request_id": "{{js .RequestID}}",
      "host": "{{.Host}}",
      "request_method": "{{.RequestMethod}}",
      "protocol": "{{.Protocol}}",
      "user_agent": "{{slice .UserAgent 1 (len (slice .UserAgent 1)) | js}}",
      "status": "{{.Status}}",
      "message": "{{js .Message}}"
      }`}}
  - name: OAUTH2_PROXY_REQUEST_LOGGING_FORMAT
    value: >-
      {{`{
      "timestamp": "{{slice .Timestamp 0 4}}-{{slice .Timestamp 5 7}}-{{slice .Timestamp 8 10}}T{{slice .Timestamp 11 19}}Z",
      "oauth2_proxy_log_type": "request",
      "client": "{{.Client}}",
      "username": "{{js .Username}}",
      "request_id": "{{js .RequestID}}",
      "host": "{{.Host}}",
      "request_method": "{{.RequestMethod}}",
      "upstream": "{{js .Upstream}}",
      "request_uri": "{{slice .RequestURI 1 (len (slice .RequestURI 1)) | js}}",
      "protocol": "{{.Protocol}}",
      "user_agent": "{{slice .UserAgent 1 (len (slice .UserAgent 1)) | js}}",
      "status_code": {{ .StatusCode }},
      "response_size": {{ .ResponseSize }},
      "request_duration": {{ .RequestDuration }}
      }`}}
  - name: OAUTH2_PROXY_STANDARD_LOGGING_FORMAT
    value: >-
      {{`{
      "timestamp": "{{slice .Timestamp 0 4}}-{{slice .Timestamp 5 7}}-{{slice .Timestamp 8 10}}T{{slice .Timestamp 11 19}}Z",
      "oauth2_proxy_log_type": "standard",
      "file": "{{js .File}}",
      "message": "{{js .Message}}"
      }`}}
```
