### ISSUE TITLE
502 bad gateway on Azure AD login success, Error loading cookied session: cookie "_oauth2_proxy" not present, removing session

### ISSUE THREAD

**Issue by nirupbbnk** [oauth2-proxy/oauth2-proxy#1071]
After  Azure AD successful login , when page is redirected it is giving 502 bad gateway.  

## Expected Behavior
It should have redirected to upstream after success login

## Current Behavior
Throws 502 bad gateway error page instead of going to upstream

##Errors logs found on oauth2 pod

**`Error loading cookied session: cookie "_oauth2_proxy" not present, removing session`
`WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.`
`[AuthSuccess] Authenticated via OAuth2: Session`
**

#Chrome console log

`Warning Cross-Origin Read Blocking (CORB) blocked cross-origin response https://login.microsoftonline.com/ds32540f-d60a-45ad-86a9-e2222ee6669/oauth2/authorize?approval_prompt=force&client_id=d3cca683-0236-4226-9833-7237c94d20db&redirect_uri=https%3A%2F%2Fabc.cloud%2Foauth2%2Fcallback&response_type=code&scope=openid&state=b53b5c69cbd8df92ea3dfd4a3719ff02%3A%2Ffavicon.ico with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

## Steps to Reproduce (for bugs)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - env:
          - name: OAUTH2_PROXY_PROVIDER
            value: azure
          - name: OAUTH2_PROXY_AZURE_TENANT
            value: <Replace with yours>
          - name: OAUTH2_PROXY_CLIENT_ID
            value: <replace>
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                    name: <Replace>
                    key: <Replace>
          - name: OAUTH2_PROXY_HTTP_ADDRESS
            value: "0.0.0.0:4180"
          - name: OAUTH2_PROXY_UPSTREAM
            value: "http://portalservice"
        args:
        - --email-domain=*
        - --cookie-secret=<Repalce>
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: IfNotPresent
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy   

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: default  
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
spec:
  rules:
    - host: <replace your host>
      http:
        paths:
          - path: /oauth2
            backend:
              serviceName: oauth2-proxy
              servicePort: 4180
  tls:
  - hosts:
    - <Repalce your domain>
    secretName: <replace your secret>
```

Annotation on portal service(upstream)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    meta.helm.sh/release-name: adminportal
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
```

## Context
After success login it should redirect to upstream  

## Your Environment

- Version used:
Image: quay.io/oauth2-proxy/oauth2-proxy:latest (Latest as of 26-Feb-2021)
Kubernets provider: AKS 1.18
ingress-nginx controller : k8s.gcr.io/ingress-nginx/controller:v0.44.0

**Comment by nirupbbnk** [comment]
@NickMeves @JoelSpeed @steakunderscore could you please help with this

**Comment by NickMeves** [comment]
Azure is notorious for having super large OIDC tokens. Even after we refactored our cookie session encoding scheme to use lz4 compression & message pack binary encoding to trim the size by 50%, some azure environments still have session cookies that are too large.

There is a 8KB header max, if you session cookie + other headers are too big, you will hit that.

We recommend Azure users use the Redis session store for sessions.

(I'm honing in on the bad gateway + multiple cookies warning you have for the theory that you are hitting the 8KB header max since you are using cookie session store instead of a persistent redis session store).

**Comment by nirupbbnk** [comment]
@NickMeves my requirement is peculiar , I need Azure AD integration just to check user is from my organization , after successful login from azure AD , user will be redirected to a one more custom login page of application. 
I was following this article  
https://msazure.club/protect-kubernetes-webapps-with-azure-active-directory-aad-authentication/

Here they are using machinedata/oauth2_proxy:latest with this azure ad is working fine I am able to successfully redirect to upstream .
My concern with this image is, this is  not under active development they have archived . 
I am surprised how  it's working with that image .

**Comment by shmolyneaux** [comment]
I believe I have a similar issue to the OP. Using Azure I have a session which exceeds the 4kb cookie limit.

Based on the logging output, it seems like this is due to the large number of groups stored in the session. Since I don't need the groups, it would be simpler to not include them in the session. That way I wouldn't need to set up a redis db. Is this an option that would be reasonable to add to oauth2-proxy?

**Comment by Mistuke** [comment]
> Azure is notorious for having super large OIDC tokens. Even after we refactored our cookie session encoding scheme to use lz4 compression & message pack binary encoding to trim the size by 50%, some azure environments still have session cookies that are too large.
> 
> There is a 8KB header max, if your session cookie + other headers are too big, you will hit that.
> 
> We recommend Azure users use the Redis session store for sessions.

Hmm I've tried using Redis and I no longer get the 502 but now get stuck in an endless login loop.  But not sure what I am missing.

My docker compose config looks like
```
    environment:
      - VIRTUAL_HOST=my.domain.com
      - VIRTUAL_PORT=80
      - DEFAULT_HOST=my.domain.com
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_AZURE_TENANT=<removed>
      - OAUTH2_PROXY_CLIENT_ID=<removed>
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/<removed>/v2.0
      - OAUTH2_PROXY_COOKIE_SECRET=<removed>
      - OAUTH2_PROXY_CLIENT_SECRET=<removed>
      - OAUTH2_PROXY_EMAIL_DOMAIN=my.domain.com
      - OAUTH2_PROXY_COOKIE_DOMAIN=my.domain.com
      - OAUTH2_PROXY_WHITELIST_DOMAIN=my.domain.com
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_COOKIE_NAME=_custom_name
      - OAUTH2_PROXY_COOKIE_SAMESITE=lax
      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true # Injects a bunch of user profile info.
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://redis_cache:6379
      - OAUTH2_PROXY_REDIS_PASSWORD=secretKey
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
      # - OAUTH2_PROXY_ALLOWED_GROUP=
    tty: true
    depends_on:
      - redis_cache

  redis_cache:
    image: redis:7.0-alpine3.17
    container_name: redis-server
    deploy:
      restart_policy:
        condition: any
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass secretKey
    volumes:
      - session_cache:/data

volumes:
  session_cache:
    driver: local
```
and my nginx config
```
server {
  #listen 443 ssl;
  server_name ${DEFAULT_HOST};
  #include ssl/ssl.conf;
  large_client_header_buffers  4 32k;
  proxy_buffer_size  32k;

  location /oauth2/ {
    proxy_pass       http://127.0.0.1:4180;
    proxy_set_header Host                    $host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Scheme                $scheme;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
    # or, if you are handling multiple domains:
    # proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
  }

  location = /oauth2/auth {
    # proxy_pass       http://127.0.0.1:4180/oauth2/auth?allowed_groups=xxx;
    proxy_pass       http://127.0.0.1:4180;
    proxy_set_header Host             $host;
    proxy_set_header X-Real-IP        $remote_addr;
    proxy_set_header X-Scheme         $scheme;
    # nginx auth_request includes headers but not body
    proxy_set_header Content-Length   "";
    proxy_pass_request_body           off;
  }

  location / {
    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in;

    # pass information via X-User and X-Email headers to backend,
    # requires running with --set-xauthrequest flag
    auth_request_set $user   $upstream_http_x_auth_request_user;
    auth_request_set $email  $upstream_http_x_auth_request_email;
    proxy_set_header X-User  $user;
    proxy_set_header X-Email $email;

    # if you enabled --pass-access-token, this will pass the token to the backend
    auth_request_set $token  $upstream_http_x_auth_request_access_token;
    proxy_set_header X-Access-Token $token;

    # if you enabled --cookie-refresh, this is needed for it to work with auth_request
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $auth_cookie;

    # When using the --set-authorization-header flag, some provider's cookies can exceed the 4kb
    # limit and so the OAuth2 Proxy splits these into multiple parts.
    # Nginx normally only copies the first `Set-Cookie` header from the auth_request to the response,
    # so if your cookies are larger than 4kb, you will need to extract additional cookies manually.
    auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;

    # Extract the Cookie attributes from the first Set-Cookie header and append them
    # to the second part ($upstream_cookie_* variables only contain the raw cookie content)
    if ($auth_cookie ~* "(; .*)") {
        set $auth_cookie_name_0 $auth_cookie;
        set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
    }

    # Send both Set-Cookie headers now if there was a second part
    if ($auth_cookie_name_upstream_1) {
        add_header Set-Cookie $auth_cookie_name_0;
        add_header Set-Cookie $auth_cookie_name_1;
    }

    proxy_pass http://${DEFAULT_HOST}/;
    # or "root /path/to/site;" or "fastcgi_pass ..." etc
  }
}
```
but I can't figure out what I'm missing...
