### ISSUE TITLE
oauth2-proxy 7.0.1 fails when mixing Oauth2 users and htaccess users

### ISSUE THREAD

**Issue by Spindel** [oauth2-proxy/oauth2-proxy#1079]
## Expected Behavior

For various reasons we have authentication using oauth2-proxy that mixes htaccess logins and oauth2 logins. 

In 6.1.1  and before the proxy would generate an Authorization Basic header with either the htaccess username, or the oauth2 username (or email claim), both with the same defaulted password from the setting.

This means that no matter which access method was used to get a claim, the Authorization header passed to the  web application would match with a username  and static password.

## Current Behavior

The current behaviour instead ONLY generates the Authorization: Basic  header for oauth2 logins, and simply doesn't pass the  oauth2-enabled htaccess login names at all to the backend.  This also seems to be the case for the HTTP headers when using side-by-side authentication.

## Possible Solution

Consider adding the oauth2 managed htaccess usernames and treating them as usernames.

## Steps to Reproduce (for bugs)

Simply upgrading to version 7.x  was enough to change this behaviour and break our monitoring and authentication flow. It should be noted that the /oauth2/userinfo  endpoint actually returns the correct username.

1. Set up oauth2-proxy with a htaccess file with a single user in it
2. Set up login with an oauth2 provider
2. turn on --pass-basic-auth
3. Login as oauth2  user and and check header
4.  Login as htaccess user and check header

## Context

Broke all our robot users that use htaccess for authentication after upgrading to 7.x series. 

## Your Environment

OAUTH2_PROXY_REVERSE_PROXY: "true"
OAUTH2_PROXY_PROVIDER: google
OAUTH2_PROXY_SCOPE: email
OAUTH2_PROXY_EMAIL_DOMAINS: example.com
OAUTH2_PROXY_UPSTREAMS: http://127.0.0.1:8080
OAUTH2_PROXY_HTTP_ADDRESS: ":4180"
OAUTH2_PROXY_HTPASSWD_FILE: /etc/secret/htaccess
OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
OAUTH2_PROXY_PASS_BASIC_AUTH: "true"
OAUTH2_PROXY_PREFER_EMAIL_TO_USER: "true"

- Version used:  
- 6.1.1  works
- 7.0.1  fails

**Comment by JoelSpeed** [comment]
This was not an intentional break, but I suspect the problem is around `PREFER_EMAIL_TO_USER`, IIRC we don't set emails for the basic auth and now, because we check the field is not empty, we need to somehow copy the basic auth username to the email field in the session when the prefer email to user option is being used.

To test this theory, do you have a chance to disable this option and see if the headers are being passed in this case?

**Comment by Spindel** [comment]
It seems to work that way, although that's a mode of operating that we cannot use to authenticate with, as google user id's are very large integers. :/

**Comment by JoelSpeed** [comment]
Ok, I appreciate that, but it confirms to me what the bug actually is here, so now we can go ahead and create a fix

**Comment by Spindel** [comment]
Is there a way to replicate this kind of configuration in the new config
format?   I've read the documentation,  but so far I couldn't actually
grasp how to use it for this setup.

**Comment by JoelSpeed** [comment]
We wanted to remove the idea of indeterminate fallbacks such as those implemented in the prefer email option, so, not 100% no. You can however do two things that may or may not work with your particular use case

Either create a header with two values, so to the upstream it would look like `Authorization: Basic blah, Basic blah` for a normal user and `Authorization: Basic blah`, your application may be able to handle this by only accepting the first value:
```
injectRequestHeaders:
- name: Authorization
  values:
   - claim: email
     prefix: "Basic "
     basicAuthPassword:
       fromValue: <Base64 string>
   - claim: user
     prefix: "Bearer "
     basicAuthPassword:
       fromValue: <Base64 string>
```

Or set two different headers and have your application read from one and then the other if the first solution doesn't work:
```
injectRequestHeaders:
- name: Authorization
  values:
   - claim: email
     prefix: "Basic "
     basicAuthPassword:
       fromValue: <Base64 string>
- name: AuthorizationUser
  values:
   - claim: user
     prefix: "Bearer "
     basicAuthPassword:
       fromValue: <Base64 string>
```

You can also load the password `fromEnv` or `fromFile` if you don't want to put it into your configuration file directly
