### ISSUE TITLE
alpha configs not getting values from claims

### ISSUE THREAD

**Issue by dhananjay-bahal** [oauth2-proxy/oauth2-proxy#1083]
Here is my alphaConfig.yaml file
```
upstreams:
  - id: <unique id>
    uri: file:///dev/null
    path: file:///dev/null
injectResponseHeaders:
  - name: X-Auth-Request-Roles
    values:
    - claim: roles
  - name: X-Auth-Request-Email
    values:
    - claim: upn
```

and I use it in my oauth2_proxy.yaml file as below:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - args:
        - --email-domain=<domain>
        - --http-address=<some ip>
        - --provider=azure
        - --session-store-type=redis
        - --redis-connection-url=<redis url>
        - --redis-password=<redis password>
        - --scope=<scope>
        - --oidc-groups-claim=<group claim>
        - --alpha-config=./alphaConfig.yaml
        env:
          - name: OAUTH2_PROXY_PROVIDER
            value: azure
          - name: OAUTH2_PROXY_AZURE_TENANT
            value: <azure tenant id>
          - name: OAUTH2_PROXY_CLIENT_ID
            value: <client id>
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: <client secret>
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: <cookie secret>
          - name: OAUTH2_PROXY_HTTP_ADDRESS
            value: <ip address>
          - name: OAUTH2_PROXY_UPSTREAM
            value: <upstream url>
          - name: OAUTH2_PROXY_EMAIL_DOMAIN
            value: <email domain>
        image: <docker image built on top of quay.io/oauth2-proxy/oauth2-proxy:latest>
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: <port number>
          protocol: TCP
```

When I try to verify the header values in my access_by_lua_block in my nginx ingress, they are not getting set.  In the alpha config file, if I change the values from claim to a fixed value (base64 encoded as mentioned in the docs) the headers work. Is there something I am missing out here in my config files?

updated alpha config without claims:
```
upstreams:
  - id: upstream_redash
    uri: file:///dev/null
    path: file:///dev/null
injectResponseHeaders:
  - name: X-Auth-Request-Roles
    values:
    - value: <base64 encoded string>
  - name: X-Auth-Request-Email
    values:
    - value: <base64 encoded string>
```
