### ISSUE TITLE
Describe ingress setup for dynamic callback urls

### ISSUE THREAD

**Issue by elsesiy** [oauth2-proxy/oauth2-proxy#109]
Hi @JoelSpeed,

I'm facing the same issue described in #12 and have been trying to get the described setup working but the redirect to the downstream ingress doesn't work. Do you have some more documentation on how this exactly should look like?

Here's what I did:

1. Install the chart
```
helm install stable/oauth2-proxy --name login-oauth2-proxy \
    --namespace xyz \
    --set config.clientID="clientId" \
    --set config.clientSecret="clientSecret" \
    --set config.cookieSecret="cookieSecret" \
    --set extraArgs.provider="azure" \
    --set extraArgs.azure-tenant="tenantId" \
    --set extraArgs.whitelist-domain=".mydomain.com" \
    --tls
```

2. Create the ingress for oauth2_proxy:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: login-ingress-oauth2
  namespace: xyz
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: login.mydomain.com
    http:
      paths:
      - backend:
          serviceName: login-oauth2-proxy
          servicePort: 80
        path: /oauth2
  tls:
  - hosts:
    - login.mydomain.com
```

By now browsing `https://login.mydomain.com/oauth2/sign_in` works as expected.

3. Configure downstream ingress to use the oauth2_proxy:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myservice-ingress
  namespace: xyz
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://login.mydomain.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.mydomain.com/oauth2/start?rd=service.cdhamap.com"
spec:
  rules:
  - host: service.cdhamap.com
    http:
      paths:
      - backend:
          serviceName: service-backend
          servicePort: 1337
        path: /
  tls:
  - hosts:
    - service.cdhamap.com
```

Browsing `https://service.mydomain.com` now correctly redirects me to the Microsoft Login but still shows `https://login.mydomain.com/oauth2/callback` as the redirect_uri which then after successful authentication falls back to `default-backend`.

What am I missing?

Thanks a lot!!

**Comment by r0fls** [comment]
I'm encountering the same problem, after successful oauth2 workflow the final URL is the oauth2-proxy URL, not the kubernetes dashboard ingress (trying to follow: https://thenewstack.io/single-sign-on-for-kubernetes-dashboard-experience/)

**Comment by r0fls** [comment]
For me, the issue turned out to be that I was missing the following oauth2 proxy flags:

```
domain=.kube.example.com# Cookie needs to cover all whitelisted domains--cookie-domain=.kube.example.com
```

**Comment by maxh8086** [comment]
you need to publish dashboard service on http not on https, this is how it worked for me.. after going through lot of blogs and forum, what i understood is.. oauth2 proxy do not understand how to pass token via header when dashboard is using selfsign certificate... your upstream will be dashboard service url http://kubernetes-dashboard.kube-system.svc.cluster.local.. if you still wish to ssl your dashboard.. you may use san certificate for oauth2 and set them up on ingress level to handle it properly.

**Comment by okgolove** [comment]
Hello everyone! Have the same idea. I want to have domain like oauth.example.com, not specified path (/oauth2) for every Ingress I want to auth using oauth.
A scheme is: Kibana (for example) ingress -> Oauth-proxy -> keycloak, successful auth -> oauth-proxy /oauth2/callback and in the end it redirects me to oauth.example.com with 404.

Tried to explore something about X-Auth-Request-Redirect, but it didn't helped. The main idea to set up the final redirect to the service requested OAuth in the start (for my case this is Kibana).

**Comment by JoelSpeed** [comment]
Hi @elsesiy, I've had a look through your config and have two suggestions that might help,

First off, make sure to set your cookie domain, it should be the parent domain off all subdomains you are protecting and I think it needs to include the OAuth2_Proxy as well, are your Authentication and protected service on the same parent domain? (eg `foo.bar.example.com` and `baz.example.com` share `example.com` as a parent so the `cookie-domain=.example.com` to allow the cookie to be read by them all)

Secondly, in your redirect, try adding the scheme to the beginning of the request, if you are `https` only then `rd=https://$host$request_uri` should suffice, else you can try `rd=$scheme://$host$request_uri` for mixed `http`/`https` (I haven't tested the latter btw)

Let me know how you get on! 😄

**Comment by elsesiy** [comment]
@JoelSpeed Works flawlessly now, thanks. The missing piece was the `cookie-domain` 👍 Do you think it makes sense to create a dedicated section in the docs on how to set this up?

**Comment by JoelSpeed** [comment]
> Do you think it makes sense to create a dedicated section in the docs on how to set this up?

It *really really* does, but sadly no one has had time to do so yet

**Comment by okgolove** [comment]
@elsesiy it would be great, if you were able to describe it!

**Comment by maxh8086** [comment]
i am also facing same challange, please let me know if there is any way available to add if(condition to ensure authentication is done) { rewrite URL}  with below example to solve this

https://kubernetes.github.io/ingress-nginx/examples/rewrite/#examples

rather than nginx sidecar - 

https://www.callumpember.com/Kubernetes-A-Single-OAuth2-Proxy-For-Multiple-Ingresses/

**Comment by elsesiy** [comment]
@JoelSpeed @okgolove OK, I can create a PR. Shall I just add to the README or create a dedicated directory for guides & how-tos?

**Comment by elsesiy** [comment]
Until @JoelSpeed decides where to contribute, I published a [blog post](https://elsesiy.com/blog/oauth2-proxy-dynamic-callback-urls) for now.

**Comment by samvdb** [comment]
@JoelSpeed comment should work for most people. setting cookie-domain does the trick.
One other thing that might be needed (like in my use-case) is the whitelist-domain setting.

eg : whitelist-domain: .example.com

This fixes the invalid redirects after the first login.
example without whitelist-domain:

scenario 1: go to app.example.com without cookies => you will need to login
                   after login you will be redirected to auth.example.com/callback (or whatever your proxy domain is)
                  You will get a 404 here.

scenario 2: go to app.example.com with cookies ( you already logged in before )
                  everything works...

> Hi @elsesiy, I've had a look through your config and have two suggestions that might help,
> 
> First off, make sure to set your cookie domain, it should be the parent domain off all subdomains you are protecting and I think it needs to include the OAuth2_Proxy as well, are your Authentication and protected service on the same parent domain? (eg `foo.bar.example.com` and `baz.example.com` share `example.com` as a parent so the `cookie-domain=.example.com` to allow the cookie to be read by them all)
> 
> Secondly, in your redirect, try adding the scheme to the beginning of the request, if you are `https` only then `rd=https://$host$request_uri` should suffice, else you can try `rd=$scheme://$host$request_uri` for mixed `http`/`https` (I haven't tested the latter btw)
> 
> Let me know how you get on!

**Comment by beebird** [comment]
I added ```whitelist-domain``` parameter and everything works as expected!!!  I'm so happy:)

**Comment by agolomoodysaada** [comment]
The suggested solution `https://oauth.mywebsite.com/oauth2/start?rd=$scheme://$host$request_uri` almost worked for me. The `$host` resolved to my oauth host instead of the original target host. To make nginx-ingress redirect correctly, I had to use the forwarded host using the `$best_http_host` variable. For example: `rd=$scheme://$best_http_host$request_uri`.
The `$scheme` worked like a charm!

**Comment by okgolove** [comment]
Did someone try this scheme with Keycloak?

**Comment by sc250024** [comment]
Also curious if anyone got this working for GitLab? In my case, the redirect to GitLab works fine, but GitLab redirects to the bsae oauth2 proxy (https://oauth2.mycompany.com/) instead of following the `rd=https://$host$request_uri` part.

Any ideas?

**Comment by sc250024** [comment]
Nevermind, solved it. It was the `whitelist-domain` feature :D

**Comment by transient1** [comment]
I think I've done what was suggested here but am still having issues with the redirect. I have an oauth proxy with this config:

`spec:
      containers:
      - args:
        - --provider=google
        - --email-domain=mycompany.com
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --cookie-domain=mycompany.engineering
        - --whitelist-domain=".mycompany.engineering" (added after reading the above posts)
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: <redacted>
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: <redacted>
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: <redacted>
        image: quay.io/pusher/oauth2_proxy:v3.2.0`

My ingress for oauth 
`spec:
  rules:
  - host: stage.internal.mycompany.engineering
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 80
        path: /oauth2/`

So then I add a backend service with ingress
`ingress.kubernetes.io/auth-signin: https://stage.internal.mycompany.engineering/oauth2/start?rd=https://$best_http_host$request_uri
    ingress.kubernetes.io/auth-url: https://stage.internal.mycompany.engineering/oauth2/auth
    kubernetes.io/ingress.class: oauth
......
spec:
  rules:
  - host: grafana.stage.internal.mycompany.engineering
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80`

When I try to hit that url I get the oauth sign-in, but the redirect goes back to the original oauth url and I get the default backend 404 message. 

1. Do I need to change the cookie domain to ".mycompany.engineering"?
2. Is my subdomain nesting the issue? Does the whitelist need to be internal.mycompany.engineering, or even stage.internal.mycompany.engineering?

**Comment by Swetad90** [comment]
Does anyone know how to redirect it to a host:port?
For me the redirect is happening only to the host (ie metrics.staging.com) and I want to redirect to metrics.staging.com:9099 ?

My prometheus ingress:
`  nginx.ingress.kubernetes.io/auth-signin: https://oauth2-qa.staging.com:9043/oauth2/start?rd=https://$host$request_uri$is_args$args
           
nginx.ingress.kubernetes.io/auth-url: https://oauth2-qa.staging.com:9043/oauth2/auth
nginx.ingress.kubernetes.io/backend-protocol: HTTPS
`

My `whitlist-domain` and `cookie-domain` are both set to `.staging.com`

**Comment by JoelSpeed** [comment]
@Swetad90 As far as I'm aware, the code that deals with the whitelists doesn't account for ports, maybe you could submit a PR to add it?

https://github.com/pusher/oauth2_proxy/blob/62bf233682372266e515fa477031c2aba5ff1512/oauthproxy.go#L497-L516

**Comment by icelynjennings** [comment]
@JoelSpeed thank you king

**Comment by aseemmishra25** [comment]
@JoelSpeed I need a help please.. my oauth2 proxy config looks good, I get the login page , when I try to login it lets me in to the landing page as that is  the flow for it but with access request module. My issue is the username I used it comes back appended like this "{Email:username@abc.com}" so my username looks like as if it has "email:" added to it.

**Comment by JoelSpeed** [comment]
> I used it comes back appended like this 

How are you retrieving this email from the proxy? There are various ways you can get the information like this out. Also, could you please open a new issue so we don't pollute this one, this seems like a separate problem

**Comment by aseemmishra25** [comment]
@JoelSpeed  I will do the needful, in the mean time is there any best practices I can follow please let me know. We are on a critical path so was asking.. can you please point out what you meant "There are various ways you can get the information like this out".
Please help.

**Comment by JoelSpeed** [comment]
@aseemmishra25 I was referring more to this comment from yourself

> My issue is the username I used it comes back appended like this "{Email:username@abc.com}" so my username looks like as if it has "email:" added to it.

How did you read that value? Was it set in a header? If so which header? Also, does your OAuth2 Proxy directly proxy requests to upstream services or do you use it in the Nginx auth request style deployment?

**Comment by messiahUA** [comment]
I'm banging my head on this and I can't make redirect work. I have:

Service: svc.sub.domain.com

auth-signin: https://oauth2-proxy.services.sub.domain.com/oauth2/start?rd=https://$host$request_uri
auth-url: https://oauth2-proxy.services.sub.domain.com/oauth2/auth

cookie_domain = ".domain.com"

I've also tried different combinations for whitelist_domain:
".domain.com"
".sub.domain.com"
"svc.sub.domain.com"

Even tried to provide a list as:
whitelist_domain = [ ".domain.com", ".sub.domain.com", "svc.sub.domain.com" ]

But nothing works and I'm still redirected to https://oauth2-proxy.services.sub.domain.com/

Can anyone suggest any ideas where I'm wrong?

**Comment by messiahUA** [comment]
Figured out that the problem is the wrong parameter name.
It is an inconsistency in:
https://github.com/pusher/oauth2_proxy/blob/10adb5c516b5a15756a7baa50aa2d8551a6655b8/options.go#L51

"whitelist_domains" in config and "whitelist-domain" as a flag. The documentation states only about cli options.

**Comment by nonylene** [comment]
> The documentation states only about cli options.

This behavior is documented...

> Environment variables
> Every command line argument can be specified as an environment variable by prefixing it with OAUTH2_PROXY_, capitalising it, and replacing hypens (-) with underscores (_). **If the argument can be specified multiple times, the environment variable should be plural (trailing S).**
>
> https://pusher.github.io/oauth2_proxy/configuration

PS. I've also set with the wrong variable name and reached this issue :)

**Comment by nonylene** [comment]
Oops, you were talking about config file, not environment variables.

**Comment by xUnholy** [comment]
This thread has been closed for a while but I'm experiencing a 404 on my redirect.

Here is my HelmRelease

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: network
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: oauth2-proxy
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: oauth2-proxy
    version: 3.1.0
  values:
    image:
      repository: 'quay.io/pusher/oauth2_proxy'
      tag: v5.1.1-arm64
    config:
      existingSecret: oauth2-proxy
    extraArgs:
      provider: github
      github-org: raspbernetes
      email-domain: '*'
      cookie-domain: .raspbernetes.com
      whitelist-domain:
        - raspbernetes.com
        - .raspbernetes.com
      cookie-samesite: none
    ingress:
      enabled: true
      path: /oauth2
      hosts:
        - auth.raspbernetes.com
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: 'letsencrypt-staging'
      tls:
        - secretName: auth.raspbernetes.com-tls
          hosts:
            - auth.raspbernetes.com
```

I have my ingress with the following annotations:

```
nginx.ingress.kubernetes.io/auth-url: 'https://auth.raspbernetes.com/oauth2/auth'
nginx.ingress.kubernetes.io/auth-signin: 'https://auth.raspbernetes.com/oauth2/start?rd=$escaped_request_uri'
```

I login to Github as expected, but the redirect just 404's

I've done the recommendations as mentioned above but to no avail, would love any thoughts on what I might be missing?
