### ISSUE TITLE
Keycloak as provider - Got error: Error redeeming code during OAuth2 callback: no access token found <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden

### ISSUE THREAD

**Issue by susana-garcia** [oauth2-proxy/oauth2-proxy#1124]
Deploy on Kubernetes cluster:
- keycloak 
- oauth2-proxy (with setup to work with Keycloak)

Our Kubernetes cluster uses istio.

## Expected Behavior

Expect to be redirected to upstream.

## Current Behavior

When trying to access the app, I got to the keycloak login, then add the credentials (username/password), but after being authenticated I got this in the browser (500 Internal Server Error):

<img width="280" alt="Screenshot 2021-03-24 at 11 09 06" src="https://user-images.githubusercontent.com/10615081/112292425-5cccbc00-8c91-11eb-9dcd-b84bf53a4b84.png">

Checking the oauth2-proxy logs:
```
127.0.0.1 - - [2021/03/23 15:24:34] 127.0.0.1:8080 GET - "/oauth2/callback?state=b6b3b3c7a726d766d22c1444eccf8f60%3A%2Ffavicon.ico&session_state=8c5d68f3-e797-45d0-8496-c173d1acdba0&code=3dfe278e-0c06-4550-8b20-cd0f719e5b00.8c5d68f3-e797-45d0-8496-c173d1acdba0.f4e938c6-73fa-4df7-ae51-dbf7d4caa7ef" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" 500 345 0.104
[2021/03/23 15:24:35] [oauthproxy.go:762] Error redeeming code during OAuth2 callback: no access token found <!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
```
I took the liberty to print some information out in oauth2-proxy and show that when calling the Redeem URL`https://login.helio.dev/auth/realms/helio/protocol/openid-connect/token` with params `client_id=helio-proxy&client_secret=8d5514bc-0f3c-4f15-bfeb-5a3e9fd83f2a&code=3dfe278e-0c06-4550-8b20-cd0f719e5b00.8c5d68f3-e797-45d0-8496-c173d1acdba0.f4e938c6-73fa-4df7-ae51-dbf7d4caa7ef&grant_type=authorization_code&redirect_uri=http%3A%2F%2F127.0.0.1%3A8080%2Foauth2%2Fcallback` I get that `403` (html) response:

```
<!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
```

The interesting part is that when I run oauth2-proxy locally (without port-forward, etc), with what I think it's the same setup: 

```
go run . --provider=keycloak --cookie-secret="lMdndiCCF9Mc6Mf4qByRMQ==" --client-secret="8d5514bc-0f3c-4f15-bfeb-5a3e9fd83f2a" --client-id="helio-proxy" --email-domain="*" --login-url="https://login.helio.dev/auth/realms/helio/protocol/openid-connect/auth" --redeem-url="https://login.helio.dev/auth/realms/helio/protocol/openid-connect/token" --profile-url="https://login.helio.dev/auth/realms/helio/protocol/openid-connect/userinf"o --validate-url="https://login.helio.dev/auth/realms/helio/protocol/openid-connect/userinfo" http-address="http://127.0.0.1:4180" --cookie-secure="false" --pass-authorization-header="true" --set-authorization-header="true" --pass-access-token="true" --set-xauthrequest="true" --redirect-url="http://127.0.0.1:4180/oauth2/callback" --upstream="http://0.0.0.0:80"
``` 
It works like charm. I actually get the access token in the answer, when calling the Redeem URL`https://login.helio.dev/auth/realms/helio/protocol/openid-connect/token` with params `client_id=helio-proxy&client_secret=8d5514bc-0f3c-4f15-bfeb-5a3e9fd83f2a&code=91b22600-0178-4cb9-86f2-876762a42ac6.3444141b-35e2-4202-80a5-2d3a582fc09b.f4e938c6-73fa-4df7-ae51-dbf7d4caa7ef&grant_type=authorization_code&redirect_uri=http%3A%2F%2F127.0.0.1%3A4180%2Foauth2%2Fcallback`:

```
{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJvemY2LUF1RTZ5a0d5TGJrOGR1OUJSeXhSMEJPMWlONTBZS3dONmkxaklzIn0.eyJleHAiOjE2MTY0OTczNzYsImlhdCI6MTYxNjQ5NzA3NiwiYXV0aF90aW1lIjoxNjE2NDk3MDc2LCJqdGkiOiJiNWUwMGI2YS02NGNjLTQ3YzItODI5Zi1kMjFjMWM5YzY2ZTMiLCJpc3MiOiJodHRwczovL2xvZ2luLmhlbGlvLmRldi9hdXRoL3JlYWxtcy9oZWxpbyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJlOGYyMjkwNi0xMzliLTRiNGUtOWEwNS1kZWQyMzE5NDZkYTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJoZWxpby1wcm94eSIsInNlc3Npb25fc3RhdGUiOiIzNDQ0MTQxYi0zNWUyLTQyMDItODBhNS0yZDNhNTgyZmMwOWIiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiYWRtaW4iLCJ1bWFfYXV0aG9yaXphdGlvbiIsInVzZXIiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwgYXBpIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJTdXNhbmEgR2FyY2lhIiwiZ3JvdXBzIjpbIi9IZWxpbyJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzdXNhbmEiLCJnaXZlbl9uYW1lIjoiU3VzYW5hIiwiZmFtaWx5X25hbWUiOiJHYXJjaWEiLCJlbWFpbCI6InN1c2FuYUBoZWxpby5leGNoYW5nZSJ9.drf41qUb2cZeKzGK3jZUg7GPBEmI-6q2-Q9nnoKGecJWovlV-1wwCHMUsVjXT5BG_JgIk1MAa_g5DNw2zi8YpV5OMLKJpfwZhnR-EXbv8og-OV7DixtrhnDJoe-WLkcJOX3kMT5aA2PuApP18D1K9vH6gWHILqUIMgdYZbKRYEcqSteR7yQOHJoENjSB5yWk9igazICCogXzh8urto4j2ZDeB7hPfl8qzm-fhrc_jhqqYMBwUiJE1mSEDihhVZHtk-4385sq-pq89NwBPIvFfZY0AuOVfR4YvYZI1OjvCmfRvehHs3jt1gvNYg7buEgDuBo7V5numGJkxIx3XcUdew","expires_in":300,"refresh_expires_in":1800,"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2YWVlMTYwYi0zNDAxLTQ4ZWUtOTk2Zi00MDk0OTQ1ZGI1NWIifQ.eyJleHAiOjE2MTY0OTg4NzYsImlhdCI6MTYxNjQ5NzA3NiwianRpIjoiYmI1YzE0OWItODY2ZS00MTU1LTlkNmEtNTNhNzIyM2YyNmFiIiwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5oZWxpby5kZXYvYXV0aC9yZWFsbXMvaGVsaW8iLCJhdWQiOiJodHRwczovL2xvZ2luLmhlbGlvLmRldi9hdXRoL3JlYWxtcy9oZWxpbyIsInN1YiI6ImU4ZjIyOTA2LTEzOWItNGI0ZS05YTA1LWRlZDIzMTk0NmRhMyIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJoZWxpby1wcm94eSIsInNlc3Npb25fc3RhdGUiOiIzNDQ0MTQxYi0zNWUyLTQyMDItODBhNS0yZDNhNTgyZmMwOWIiLCJzY29wZSI6InByb2ZpbGUgZW1haWwgYXBpIn0.YsCQJQRnkkaitHsAgxnxCnj7Y26toN-GFZSA7n3_QfE","token_type":"Bearer","not-before-policy":0,"session_state":"3444141b-35e2-4202-80a5-2d3a582fc09b","scope":"profile email api"}
```

## Steps to Reproduce

1.  Deploy keycloak
2.  Deploy oauth2-proxy in Kubernetes and customize it using: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#keycloak-auth-provider

## Your Environment

Kubernetes 1.19.7, Istio 1.3.6, Keycloak 12.0.4 and oauth2-proxy 7.0.1 (build with go1.15.3)

Here is the yaml to deploy outh2-proxy:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: keycloak-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=keycloak
            - --login-url=https://login.helio.dev/auth/realms/helio/protocol/openid-connect/auth
            - --redeem-url=https://login.helio.dev/auth/realms/helio/protocol/openid-connect/token
            - --profile-url=https://login.helio.dev/auth/realms/helio/protocol/openid-connect/userinfo
            - --validate-url=https://login.helio.dev/auth/realms/helio/protocol/openid-connect/userinfo
            - --email-domain=*
            - --upstream=http://0.0.0.0:80/
            - --http-address=http://127.0.0.1:4180
            - --cookie-secure=false
            - --pass-authorization-header=true
            - --set-authorization-header=true
            - --pass-access-token=true
            - --set-xauthrequest=true
            - --redirect-url=http://127.0.0.1:8080/oauth2/callback
            - --client-secret=8d5514bc-0f3c-4f15-bfeb-5a3e9fd83f2a
            - --client-id=helio-proxy
            - --cookie-secret=lMdndiCCF9Mc6Mf4qByRMQ==
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy-service
  namespace: keycloak-sample-app
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy

```
