### ISSUE TITLE
When rewriting the URI in an Istio VirtualService, all endpoints are blocked

### ISSUE THREAD

**Issue by ericmeadows** [oauth2-proxy/oauth2-proxy#1137]
## Expected Behavior

Whether an Istio `VirtualService` has a rewrite or not, it should be authenticated if authentication has been validated, and the authentication cookie is set.

## Current Behavior

When the request is made, using `Google` as the OAuth2 provider, the following networking requests are made:
* 302 - (No Auth Headers) - `https://my.dns/eat/hello`
* 302 - (No Auth Headers) - `https://accounts.google.com/o/oauth2/v2/auth?...`
* 302 - (CSRF Sent) - `https://my.dns/oauth2/callback?...`
* 403 - (cookie, `_oauth2_proxy` Sent) `https://my.dns/eat/hello`

## Possible Solution

No clue.

## Steps to Reproduce (for bugs)

* Setup Istio's [helloworld sample](https://github.com/istio/istio/tree/master/samples/helloworld)
* Create the following `VirtualService`, then navigate to `https://my.dns/hello` -> **Success**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
spec:
  hosts:
  - "my.dns"
  gateways:
  - istio-autogenerated-k8s-ingress
  http:
  - name: test
    match:
    - uri:
        prefix: "/hello"
    rewrite:
      uri: "/hello"
    route:
    - destination:
        host: helloworld.default.svc.cluster.local
        port:
          number: 5000
```
* Create the following `VirtualService`, then navigate to `https://my.dns/hello` -> **Failure**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-prefixing
spec:
  hosts:
  - "my.dns"
  gateways:
  - istio-autogenerated-k8s-ingress
  http:
  - name: test
    headers:
      request:
        add:
          x-auth-request-redirect: "/eat/hello"
    match:
    - uri:
        prefix: "/eat/hello"
    rewrite:
      uri: "/hello"
    route:
    - destination:
        host: helloworld.default.svc.cluster.local
        port:
          number: 5000
```

## Context

```sh
OIDC_DISCOVERY_URL="https://accounts.google.com/.well-known/openid-configuration"
OIDC_DISCOVERY_URL_RESPONSE=$(curl $OIDC_DISCOVERY_URL)
OIDC_ISSUER_URL=$(echo $OIDC_DISCOVERY_URL_RESPONSE | jq -r .issuer)
OIDC_JWKS_URI=$(echo $OIDC_DISCOVERY_URL_RESPONSE | jq -r .jwks_uri)

# Set your client ID and secret from your OIDC provider setup
CLIENT_ID="*******.apps.googleusercontent.com"
CLIENT_SECRET="***********"
COOKIE_SECRET=$(openssl rand -hex 16)

echo ""
echo "------------------"
echo "CONFIGS"
echo "------------------"
echo "$OIDC_DISCOVERY_URL"
echo "$OIDC_ISSUER_URL"
echo "$OIDC_JWKS_URI"
echo "$CLIENT_SECRET"
echo "$COOKIE_SECRET"
echo "------------------"
echo ""

OIDC_DISCOVERY_URL="https://accounts.google.com/.well-known/openid-configuration"
OIDC_DISCOVERY_URL_RESPONSE=$(curl $OIDC_DISCOVERY_URL)
OIDC_ISSUER_URL=$(echo $OIDC_DISCOVERY_URL_RESPONSE | jq -r .issuer)
OIDC_JWKS_URI=$(echo $OIDC_DISCOVERY_URL_RESPONSE | jq -r .jwks_uri)
kubectl $action -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  jwtRules:
  - issuer: $OIDC_ISSUER_URL
    jwksUri: $OIDC_JWKS_URI
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
stringData:
  OAUTH2_PROXY_CLIENT_ID: $CLIENT_ID
  OAUTH2_PROXY_CLIENT_SECRET: $CLIENT_SECRET
  OAUTH2_PROXY_COOKIE_SECRET: $COOKIE_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
  - name: http
    port: 4180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.0
        args:
        - --provider=oidc
        - --email-domain=*
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --set-authorization-header=true
        - --oidc-issuer-url=$OIDC_ISSUER_URL
        - --http-address=0.0.0.0:4180
        - --cookie-expire=4h
        - --whitelist-domain=.$DOMAIN
        - --cookie-domain=.$DOMAIN
        - --standard-logging=true
        - --auth-logging=true
        - --request-logging=true
        - --skip-provider-button=true
        - --upstream=static://
        - --reverse-proxy
        - --show-debug-on-error
        - --silence-ping-logging
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: OAUTH2_PROXY_CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: OAUTH2_PROXY_COOKIE_SECRET
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        ports:
        - containerPort: 4180
          protocol: TCP
        readinessProbe:
          periodSeconds: 3
          httpGet:
            path: /ping
            port: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.filters.http.jwt_authn
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.ext_authz
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          http_service:
            authorizationRequest:
              allowedHeaders:
                patterns:
                - exact: accept
                - exact: authorization
                - exact: cookie
                - exact: from
                - exact: proxy-authorization
                - exact: user-agent
                - exact: x-forwarded-access-token
                - exact: x-forwarded-email
                - exact: x-forwarded-for
                - exact: x-forwarded-host
                - exact: x-forwarded-proto
                - exact: x-forwarded-user
                - prefix: x-auth-request
                - prefix: x-forwarded
              headers_to_add:
              - key: x-auth-request-redirect
                value: "https://%REQ(:AUTHORITY)%%REQ(:PATH)%"
            authorizationResponse:
              allowedClientHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
              allowedUpstreamHeaders:
                patterns:
                - exact: authorization
                - exact: location
                - exact: proxy-authenticate
                - exact: set-cookie
                - exact: www-authenticate
                - prefix: x-auth-request
                - prefix: x-forwarded
            server_uri:
              # URIs here should be to the oauth2-proxy service inside your
              # cluster, in the namespace where it was deployed. The port
              # in that 'cluster' line should also match up.
              cluster: outbound|4180||oauth2-proxy.oauth2-proxy.svc.cluster.local
              timeout: 1.5s
              uri: http://oauth2-proxy.oauth2-proxy.svc.cluster.local:4180
EOF
```

## Your Environment

- Version used: `7.0.0`
- Istio version: `1.9.2`
- Kubernetes version: `1.18.9-eks-d1db3c`
