### ISSUE TITLE
OIDC provider does not recognize array of "emails" in token

### ISSUE THREAD

**Issue by gregmuellegger** [oauth2-proxy/oauth2-proxy#1165]
## Expected Behavior

I try to integrate oauth2-proxy with Azure AD B2C. [This Stackoverflow Question](https://stackoverflow.com/questions/61148502/how-can-i-debug-oauth2-proxy-when-connecting-to-azure-b2c) was super helpful in that regard.

However I reached the point where I get back the following contents from the token:

```
{
  "exp": 1619079153,
  "nbf": 1619075553,
  "ver": "1.0",
  "iss": "https://<mynamespace>.b2clogin.com/567d511c-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0/",
  "sub": "9376b413-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "aud": "c453389d-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "nonce": "defaultNonce",
  "iat": 1619075553,
  "auth_time": 1619075553,
  "given_name": "Gregor",
  "family_name": "Müllegger",
  "emails": [
    "myemail@example.com"
  ],
  "tfp": "B2C_1_signup_signin",
  "at_hash": "N5xKcwiozOO-lx4Lwh86Rg"
}
```
(decoded with https://jwt.ms/)

But oauth2-proxy logs:

```
[oauthproxy.go:794] Error creating session during OAuth2 callback: id_token did not contain an email and profileURL is not defined
```

So the expected behaviour is that oauth2-proxy should recognize multiple emails configured in an array instead of just looking for a single `email` attribute.

## Possible Solution

1. Possible solution is to either auto-detect the `emails` array
2. Alternatively provide a way to configure how to read the email from the token, e.g. by providing a json path to the attribute like `--oidc-token-email-attr=emails.0`.

## Steps to Reproduce (for bugs)

I guess this requires an Azure Subscription to fully reproduce, however I'm happy to provide tokens/codes privately if necessary.

## Your Environment

Version: 7.1.2
Docker Image used: `quay.io/oauth2-proxy/oauth2-proxy:latest`

Tested locally with redis as session storage. This is the `docker-compose.yml` used:

```yaml
version: "3.7"
services:
  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: >
      --provider=oidc
      --email-domain=*
      --upstream=http://localhost:8000
      --http-address=0.0.0.0:9000
      --redirect-url=http://localhost:9000
      --scope="https://<mynamespace>.onmicrosoft.com/c453389d-xxxx-xxxx-xxxx-xxxxxxxxxxxx/read openid"
      --reverse-proxy=true
      --skip-provider-button=true
      --session-store-type=redis
      --redis-connection-url=redis://redis:6379
      --skip-oidc-discovery=true
      --oidc-issuer-url=https://<mynamespace>.b2clogin.com/567d511c-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0/
      --login-url=https://<mynamespace>.b2clogin.com/<mynamespace>.onmicrosoft.com/b2c_1_signup_signin/oauth2/v2.0/authorize
      --redeem-url=https://<mynamespace>.b2clogin.com/<mynamespace>.onmicrosoft.com/b2c_1_signup_signin/oauth2/v2.0/token
      --oidc-jwks-url=https://<mynamespace>.b2clogin.com/<mynamespace>.onmicrosoft.com/b2c_1_signup_signin/discovery/v2.0/keys
    environment:
      OAUTH2_PROXY_CLIENT_ID: "XXX"
      OAUTH2_PROXY_CLIENT_SECRET: "XXX"
      OAUTH2_PROXY_COOKIE_SECRET: "XXX"
    ports:
      - "9000:9000"
  web:
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
  redis:
    image: redis:latest
```
