### ISSUE TITLE
Add support for subpath/subfolder in RedirectUrl

### ISSUE THREAD

**Issue by iTaybb** [oauth2-proxy/oauth2-proxy#1177]
oauth2-proxy should support cases where a website that is secured by oauth2-proxy is being served from a subpath (e.g. domain.com/subpath/).

## Expected Behavior

oauth2-proxy should be able to authenticate.

## Current Behavior

The endpoint "/oauth2/callback" will not work with subpaths, as path "/subpath/oauth2/callback" is not recognized by oauth2-proxy, causing an authentication failure.

## Possible Solution

1. Register the oauth2 callback function to `RedirectUrl`'s path.

## Workaround
Currently as a workaround, I'm rewriting the path with a middleware to delete the subpath in Traefik v2:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-for-oauth2
spec:
  replacePathRegex:
    regex: ^\/(?:\w+\/(oauth2\/.+)|(.+))$
    replacement: /$1$2
```

## Your Environment
- Version used:
7.1.3
