### ISSUE TITLE
Oauth2-Proxy Helm and Okta config setup

### ISSUE THREAD

**Issue by 5w0ng** [oauth2-proxy/oauth2-proxy#1180]
Whilst I have followed the guidance in the docs it somewhat feels incorrect but I can't say where for sure.  For context, I have installed oauth2-proxy via helm/terraform on aws eks.  I would like to leverage Okta's authentication in the first instance and leverage both okta and oauth2-proxy for authorization.

## Expected Behavior

I would like to configure the helm values to redirect an internal app to Okta login but I can't seem to set this up correctly.  

## Current Behavior

I can't see in the helm values file where to change provider from defaulting to google.  I've tried adding additional config to the values for example

```
config:
  # -- OAuth client ID
  clientID: "******"
  # -- OAuth client secret
  clientSecret: "*"
  # -- server specific cookie for the secret; create a new one with `openssl rand -base64 32 | head -c 32 | base64`
  cookieSecret: "*="

  # -- custom [oauth2_proxy.cfg](https://github.com/pusher/oauth2_proxy/blob/master/contrib/oauth2_proxy.cfg.example) contents for settings not overridable via environment nor command line
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]
    #  - '--provider=oidc'
    #  provider= "oidc"
  # Custom configuration file: oauth2_proxy.cfg
  # configFile: |-
  #   pass_basic_auth = false
  #   pass_access_token = true
  # -- (string)existing Kubernetes configmap to use for the configuration file. See [config template](https://github.com/helm/charts/blob/master/stable/oauth2-proxy/templates/configmap.yaml) for the required values
  existingConfig:
    # provider: "oidc"
```

As you can see, there's different areas config can be added and I've tried different combinations but I now feel I am blocked in attempting to get this to work.  

The type of error I get is this - `MountVolume.SetUp failed for volume "configmain" : configmap "oauth2-proxy" not found`

- Version used: latest

Any help would be greatly appreciated.  Thanks!
