### ISSUE TITLE
How to configure correctly with helm/nginx?

### ISSUE THREAD

**Issue by 5w0ng** [oauth2-proxy/oauth2-proxy#1183]
I've manage to install and configure Oauth2-Proxy on Kubernetes using Helm/Terraform, Nginx and trying to get authentication using Okta for Kubernetes-Dashboard.  Pretty bog standard deployment but for some reason I can't seem to rack my brains around the config!  

## Expected Behavior

Navigate to kubernetes-dashboard url and for it to re-direct to our Okta login window, once authenticated be redirected back to kuberntes-dashboard. 

## Steps to Reproduce (for bugs)

No redirect occurs and I am hit with a 500 Internal Server Error.  

I've tried so many different configs I've found online but with no avail.  Here is the values.yaml being installed via Helm.
```
configFile: |-
    provider = "oidc"
    client_id = "[hidden]"
    client_secret = "hidden]"
    login_url = "https://mycompany-co.okta.com/oauth2/default/v1/auth"
    redeem_url = "https://mycompany-co.okta.com/oauth2/default/v1/token"
    redirect_url = "https://oauth2.my-domain.com/oauth2/callback"
    oidc_issuer_url = "https://mycompany-co.okta.com/oauth2/default"
    profile_url = "https://mycompany-co.okta.com/oauth2/default/v1/userinfo"
    validate_url = "https://mycompany-co.okta.com/oauth2/default/v1/validate"
    email_domains = [ "*" ]
    upstreams = [ "http://127.0.0.1:8080/" ]

    pass_access_token = true
    cookie_secret = "[hidden]"
    skip_provider_button = true
```

Here is the kubernetes-dashboard ingress.  The lines highlighted in bold are the lines that I added, if I remove them I can access kubernetes-dashboard gui without any problem. 
```
ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/alias: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    **nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local:4180/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.my-domain.com/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"**
  paths:
    - /
  hosts:
    - kdashboard.my-domain.com
  tls:
    - secretName: tls-kubernetes-dashboard-token
      hosts:
        - kdashboard.my-domain.com
```

## Errors

```
2021/05/04 18:07:47 [error] 2434#2434: *10266987 upstream timed out (110: Operation timed out) while connecting to upstream, client: 10.252.248.141, server: kdashboard.my-domain.com, request: "GET /favicon.ico HTTP/2.0", subrequest: "/_external-auth-Lw", upstream: "http://172.20.46.112:4180/oauth2/auth", host: "kdashboard.my-domain.com", referrer: "https://kdashboard.my-domain.com/"

2021/05/04 18:07:47 [error] 2434#2434: *10266987 auth request unexpected status: 504 while sending to client, client: 10.252.248.141, server: kdashboard.my-domain.com, request: "GET /favicon.ico HTTP/2.0", host: "kdashboard.my-domain.com", referrer: "https://kdashboard.my-domain.com/"
```

Any help as to how I can configure this would be greatly appreciated!  Thanks!
