### ISSUE TITLE
Feature request - Path rewrite

### ISSUE THREAD

**Issue by bechhansen** [oauth2-proxy/oauth2-proxy#1186]
Hi

Has it ever been discussed to make it possible to to do path rewrite as part of the alpha configuration?
To be able to do routing only one place I would like to be able to do something like this:

```
upstreams:
    - id: route1
      path: /
      uri: http://service1.default.svc.cluster.local:80

    - id: route2
      path: /external
      pathRewrite: /internal
      uri: http://service2.default.svc.cluster.local:80
```
So the idea is that I would like to access a service on the path /external, but then route the request to the endpoint /internal of service 2. Then path external should not be part of the request to the internal service.
