### ISSUE TITLE
Nginx ingress and oauth2_proxy set for OIDC (IdentityServer4)

### ISSUE THREAD

**Issue by Peperud** [oauth2-proxy/oauth2-proxy#1194]
Is there a a complete example?

I'm trying to secure an app with IdentityServer4. 
Nginx Ingress controller in front.

Here's my setup:

oauth2_proxy
```yaml
# oauth2-proxy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4180
          protocol: TCP
        args:
        - --provider=oidc
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --cookie-secure=false
        - --redirect-url=https://[redacted]/oauth2/callback
        - --skip-provider-button=true
        - --set-xauthrequest=true
        - --skip-auth-preflight=false
#        - --skip-oidc-discovery
        - --oidc-issuer-url=https://[redacted]
        - --login-url=https://[redacted]/connect/authorize
        - --redeem-url=https://redacted/connect/token
        - --oidc-jwks-url=https://[redacted]/.well-known/openid-configuration/jwks
        - --email-domain=*
        - --client-id=[redacted]
        - --client-secret=[redacted]
        - --cookie-secret=[redacted]
        - --reverse-proxy=true
        - --scope=openid profile
        - --oidc-email-claim=[redacted]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy
```

Ingress
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization 
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.default.svc.cluster.local:4180/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_name_1;
      
      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }    
spec:
  tls:
  - hosts:
    - "redacted.mydomain.com"
  rules:
  - host: "redacted.mydomain.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elk-kib-service
            port: 
              number: 5601
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-oauth2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /oauth2
    kubernetes.io/ingress.class: "nginx"    
spec:
  tls:
  - hosts:
    - redacted.mydomain.com
  rules:
  - host: redacted.mydomain.com
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180 
```

## Expected Behavior
Non authenticated requests to be redirected to oauth2_proxy and upon successful authentication to continue into the application.

## Current Behavior
With the setup above:
1. Non authenticated request are sent to **oauth2_proxy**
2. **oauth2_proxy** redirects to my OIDC server for authentication
3. I'm authenticated by the OIDC server and it redirects back to **/oauth2/callback** with authorization **code**
4. oauth2_proxy does **again** a 302 redirect to to OIDC server
5. Steps 3 & 4 repeat until Nginx decides that it has seen too many redirects.

Looking at oauth2_proxy container logs I see 
```
Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
```
I do **not** see **_oauth2_proxy** cookie being set at any time in my browser. There's **_oauth2_proxy_csrf** cookie, but not  **_oauth2_proxy**. 

- Version used:
7.1.3

**Comment by Peperud** [comment]
Slight progress. 
After adding a **Redis** node and setting **oauth2-proxy** to use it, I see a **_oauth2_proxy** cookie in the browser albeit with no value (?!).
**oauth2-proxy** error changed slightly
```
[2021/05/12 18:42:58] [oauthproxy.go:149] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
[2021/05/12 18:44:39] [stored_session.go:76] Error loading cookied session: http: named cookie not present, removing session
```
Auth code is being sent via (the browser).  The cycle of steps 3 & 4 from above remains. 

In my experience with oidc clients, this often indicates a missing claim (or wrongly mapped) etc. that makes the handler want to auth again (and again, and again...). 

I do see in the **nginx** logs a call to ```/oauth2/callback``` , but I don't see a corresponding entry in the **oatuth2-proxy** logs. Instead it is always to ```/oauth2?code=<some-auth-code here>&other...```. 

If I have to guess, I'd say on the call to ```/oauth2/callback```, instead of using the auth code to get tokens from the oidc authority, the proxy decides that id doesn't like something and goes off to get yet another auth code.

Is there a more detailed logging for **oauth2-proxy** (```--show-debug-on-error``` is already on )?

**Comment by Peperud** [comment]
After two days of experimentation, turned out ```oauth2-proxy``` errors were (more or less) a red herring. 
Bottom line - wrong ingress configuration -  ```pathType: Prefix``` above should be ```pathType: ImplementationSpecific```. 
Here's the working setup in case it might help someone else:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
  name: my-ingress
spec:
  tls:
  - hosts:
    - redacted.mydomain.com
  rules:
  - host: redacted.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: elk-kib-service
            port:
              number: 5601
        path: /
        pathType: ImplementationSpecific

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-oauth2
spec:
  tls:
  - hosts:
    - redacted.mydomain.com
  rules:
  - host: redacted.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
        path: /oauth2
        pathType: ImplementationSpecific

```
