### ISSUE TITLE
upstream timeout on ingress-controller nginx-0.43.0

### ISSUE THREAD

**Issue by eumel8** [oauth2-proxy/oauth2-proxy#1203]
I had a running configuration with Keycloak, based on [External OAuth Example of Nginx-Ingress-Controller](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/)

## Expected Behavior

**ingress-controller: nginx-0.35.0/Kubernetes 1.19**

There are two Ingress rules, the first rule had this annotations:

```
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
```
The second rule provides the oauth-proxy services behind `/oauth2` uri

```
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
```

## Current Behavior

**ingress-controller: nginx-0.43.0/Kubernetes 1.20**

60 seconds after the request timeout occured with Error 504:

```
2021/05/17 21:52:19 [error] 1308#1308: *370278 upstream timed out (110: Operation timed out) while reading response header from upstream, client: xx.xx.xx.xx, server: xxxx.xxxxx.xxxx, request: "GET / HTTP/2.0", subrequest: "/_external-auth-Lw-Prefix", upstream: "https://xx.xx.xx.xx:443/oauth2/auth", host: "xxxx.xxxxx.xxxxxx.xx"
2021/05/17 21:52:19 [error] 1308#1308: *370278 auth request unexpected status: 504 while sending to client, client: xx.xx.xx.xx, server: xxxxx.xxxxx.xxx.xx, request: "GET / HTTP/2.0", host: "xxxxx.xxxxx.xxxx.xx"
```
## Possible Solution

downgrade ingress-controller will work
couldn't catch the right issue on [ingress-nginx changelog](https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md) which cause this behavior.

## Steps to Reproduce (for bugs)

Update nginx-ingress-controller from 0.35.0 to 0.43.0

## Context

Ingress-Controller is installed and running by Rancher with HostNetwork.

## Your Environment

External Keycloak Service, Kubernetes Ingress Service, installed oauth2-proxy with protected app in the same namespace.

- Version used: v5.1.1 (tested with latest tag as well)
