### ISSUE TITLE
SSO feature of oauth2proxy returning on same url or oauthproxy

### ISSUE THREAD

**Issue by sharmavijay86** [oauth2-proxy/oauth2-proxy#1208]
## Configuration
oauth2-proxy helm chart values.yaml
```
config:
  clientID: "b730xxxxxxxxxx"
  clientSecret: "8f34e20110xxxxxxxxxxxxxxxc93a91"
  cookieSecret: "R0tuUlJCN1ZyL2lPaGhmSUpzUHVPVmZqbjFZd0JIQzM="
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]
  existingConfig:

extraArgs:
  provider: "github"
  github-org: "myorg"
  github-team: "dashboarduser"
ingress:
  enabled: true
  path: /oauth2
  hosts:
    - login.devk8s.mylab.local
  extraPaths: []
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
     cert-manager.io/cluster-issuer: mylab
  tls:
     - secretName: login-tls
       hosts:
         - login.devk8s.mylab.local
```
Ingress.yaml for k8s-dashboard

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: mylab
    meta.helm.sh/release-name: dashboard
    meta.helm.sh/release-namespace: kubernetes-dashboard
    nginx.ingress.kubernetes.io/auth-signin: https://login.devk8s.mylab.local/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://login.devk8s.mylab.local/oauth2/auth
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
  creationTimestamp: "2021-05-19T15:55:38Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-dashboard
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: kubernetes-dashboard-4.1.0
  name: dashboard-kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: dashboard.devk8s.mylab.local
    http:
      paths:
      - backend:
          serviceName: dashboard-kubernetes-dashboard
          servicePort: 443
        path: /
        pathType: ImplementationSpecific
  tls:
  - secretName: dashboard-tls

```
## Expected Behavior

oauth2-proxy url is   : login.devk8s.mylab.local
app dashboard url is : dashboard.devk8s.mylab.local

I want when a user access dashboard url, it should get authentication from auth url (i.e. oauth2proxy ingress url+github user), and should be back on my dashboard url after authentication process finish ( kind of redirection after auth - usual )

## Current Behavior
dashboard.devk8s.mylab.local  url, redirecting to login.devk8s.mylab.local for authentication, after github authentication process done, it returns to login.devk8s.mylab.local instead of dashboard.devk8s.mylab.local

## Possible Solution

may be some config miss in ingress annotation. or perhaps bug in version.

## Your Environment

- Version used:
- ingress-nginx : 0.45.0
- oauth2-proxy helm chart: oauth2-proxy-5.0.5
- pauth2-proxy  app version: 7.0.1
- kubernetes : 1.19
- cert-manager:  1.3.1
