### ISSUE TITLE
Keycloak question

### ISSUE THREAD

**Issue by breedjaram** [oauth2-proxy/oauth2-proxy#1223]
Hi
we would like to operate oauth2-proxy with Keycloak. 
For Keycloak we can using ,,provider oidc,, or ,,provider keycloak,, in oauth2-proxy.

We are using Nginx with Oauth2-proxy with allowed_groups
```
annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.example.com/oauth2/auth?allowed_groups=security3"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.example.com/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
```

What are the differences in functionality between oidc and Keycloak provider in oauth2-proxy conf?
What will be better to use in the future?

Thank you for the experience
Breed
