### ISSUE TITLE
Keycloak 13 via OIDC returns invalid_scope

### ISSUE THREAD

**Issue by patrickleet** [oauth2-proxy/oauth2-proxy#1241]
I used oauth2proxy for a long time with Keycloak 12. 

Unfortunately, my Keycloak upgraded itself to Keycloak 13 cause operatorhub...

Anyway, the same config that worked with keycloak 12 now results in an "invalid_scope" error. Viewing the keycloak logs is quite useless as it just says:

```
21:33:23,732 ERROR [org.keycloak.services] (default task-1) KC-SERVICES0093: Invalid parameter value for: scope
```

Not what about what parameter is invalid - just no.

Here is the oauth2proxy config which used to work:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2proxy
  name: oauth2proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2proxy
    spec:
      containers:
        - image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
          - containerPort: 4180
            protocol: TCP
          env:
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: keycloak-client-secret-dev
                key: CLIENT_ID
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-client-secret-dev
                key: CLIENT_SECRET
          - name: COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2proxy
                key: cookieSecret
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-redis
                key: redis-password
          args:
          - --provider=oidc
          - --provider-display-name="Keycloak"
          - --client-id=$(KEYCLOAK_CLIENT_ID)
          - --client-secret=$(KEYCLOAK_CLIENT_SECRET)
          - --email-domain="*"
          - --pass-access-token=true
          - --pass-authorization-header=true
          - --set-authorization-header=true
          - --oidc-issuer-url=https://auth.example.com/auth/realms/dev
          - --login-url=https://auth.example.com/auth/realms/dev/protocol/openid-connect/auth
          - --redeem-url=https://auth.example.com/auth/realms/dev/protocol/openid-connect/token
          - --validate-url=https://auth.example.com/auth/realms/dev/protocol/openid-connect/userinfo
          - --http-address=http://:4180
          - --scope=openid profile email roles
          - --cookie-refresh=4m0s
          - --cookie-expire=4h0m0s
          - --cookie-secure=true
          - --cookie-secret=$(COOKIE_SECRET)
          - --whitelist-domain=".example.com"
          - --cookie-domain=.example.com
          - --standard-logging=true
          - --auth-logging=true
          - --request-logging=true
          - --skip-provider-button=true
          - --upstream=static://
          - --redis-connection-url=redis://auth-redis-master.auth.svc.cluster.local:6379
          - --redis-password=$(REDIS_PASSWORD)
          - --session-store-type=redis
```

In attempting to get it working again I tried setting scope to the default `openid profile email`, `api` as was suggested elsewhere, just `email` as someone else suggested, and none of those combinations caused any difference.

I also upgraded to `v7.1.3` with the same results.

## Expected Behavior

Able to login via keycloak configured via oidc provider

## Current Behavior

invalid_scope

## Possible Solution

🤷‍♂️

## Steps to Reproduce (for bugs)

1.  Use Keycloak 13 and oauth2proxy with above oidc configuration

## Context

No one can log into anything anymore. Not sure why scope would be invalid now when it used to be valid.

## Your Environment

- Version used: 6.1.1 and 7.1.3, Keycloak 13
