### ISSUE TITLE
Traefik Forward and OAuth2-Proxy with `skip-provider-button=true` do not redirect to initial page

### ISSUE THREAD

**Issue by DanielHabenicht** [oauth2-proxy/oauth2-proxy#1255]
## Expected Behavior

On Navigating directly to `a-service.example.com` I am redirected to the OIDC Login page and after successful login I should be redirected to `a-service.example.com`. 

## Current Behavior

On Navigating directly to `a-service.example.com` I am redirected to the OIDC Login page and after successful login I am redirected to `auth.example.com` instead of the initial url.

## Possible Solution

With `skip-provider-button=false` I get the OAuth2-Proxy page, when I click on Authenticate everything works as expected. 

## Steps to Reproduce (for bugs)

Using the configuration from: 
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#forwardauth-with-static-upstreams-configuration (adopted to Kubernetes, I am currently writing on Blog Post with the source code, will update accordingly. Somewhere it was mentioned that you might want to update your Documentation with more specific examples. I would be happy to contribute one for Kubernetes/Traefik)

with the oauth2-proxy configuration like: 

```
 containers:
        - args:
            - '--upstream=static://202'
            - '--http-address=0.0.0.0:4180'
            - '--reverse-proxy'
            - '--email-domain=*'
            - '--skip-provider-button=true'
            - '--cookie-domain=.example.com'
            - '--real-client-ip-header=X-Forwarded-For'
            - '--oidc-issuer-url=https://keycloak.example.com/auth/realms/master'
          env:
            - name: OAUTH2_PROXY_WHITELIST_DOMAIN
              value: .example.com
            - name: OAUTH2_PROXY_PROVIDER
              value: oidc
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: 'true'
            - name: OAUTH2_PROXY_SET_XAUTHREQUEST
              value: 'true'
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: clientid
                  name: oauth2-proxy-config
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: clientsecret
                  name: oauth2-proxy-config
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwtsecret
                  name: oauth2-proxy-config
          image: 'bitnami/oauth2-proxy:7'
          imagePullPolicy: IfNotPresent
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
```

The Following the bug steps. 

## Context

I am trying to authenticate multiple services (Domains) all behind a Traefik v2 instance. 
I wrote almost all issues matching search queries related to this use case, for this context https://github.com/oauth2-proxy/oauth2-proxy/pull/1023 should have fixed this (raised in https://github.com/oauth2-proxy/oauth2-proxy/issues/1015), but only updated the docs? 
https://github.com/oauth2-proxy/oauth2-proxy/pull/762#issuecomment-768360213 was the initial request 

(https://github.com/traefik/traefik/issues/5036 still not resolved so this seems to be an traefik specific issue)

## Your Environment

Traefik/Helm Chart: 2.4.8/9.18.2
Keycloak: quay.io/keycloak/keycloak:14.0.0
OAuth2-Proxy: bitnami/oauth2-proxy:7
Cluster: v1.17.9-r0-CCE20.8.1.3.B001-17.36.5
