### ISSUE TITLE
Unable to bypass Keycloak login page when authenticating M2M

### ISSUE THREAD

**Issue by tmurphy5** [oauth2-proxy/oauth2-proxy#1266]
I can't identify the proper configuration settings to allow any non-browser interaction through OAuth2 Proxy. Each request results in the Keycloak login page HTML being returned, rather than the requested resource

## Expected Behavior

The requested resource should be returned from a script that has set the appropriate authentication header

## Current Behavior

The Keycloak login page is always returned

## Context

Browser-based configuration works well for our use case, but Postman scripts, shell scripts, etc, can no longer be executed against protected services.

We can obtain a valid JWT token, parse out the auth-token and set it's value as "Authorization: Bearer $token" header in the request.

## Your Environment

* Kubernetes
* Nginx - auth_request configuration
* Keycloak
* OAuth2 Proxy
 
- Version used: 7.1.3

relevant nginx configuration:
```yaml
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/auth-response-headers: authorization, x-auth-request-user, x-auth-request-email, x-auth-request-access-token
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_origin ~* "^https://.*\.SUBDOMAIN\.DOMAIN\.TLD$") {
          set $cors "true";
      }

      if ($request_method = 'OPTIONS') {
          set $cors "${cors}options";
      }

      if ($cors = "true") {
          more_set_headers "Access-Control-Allow-Origin: $http_origin";
          more_set_headers "Access-Control-Allow-Credentials: true";
      }

      if ($cors = "trueoptions") {
          add_header 'Access-Control-Allow-Origin' "$http_origin";
          add_header 'Access-Control-Allow-Credentials' 'true';
          add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,DELETE,OPTIONS';
          add_header 'Access-Control-Allow-Headers' 'DNT,Authorization,X-Auth-Token,X-CustomHeader,X-Forwarded-User,X-Forwarded-Email,X-Forwarded-Preferred-Username,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
          add_header 'Access-Control-Max-Age' 1728000;
          add_header 'Content-Length' 0;
          add_header 'Content-Type' 'text/plain charset=UTF-8';
          return 204;
      }

      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
```

relevant oauth2-proxy configuration:
```yaml
  extraArgs:
    cookie-domain: .DOMAIN.TLD
    cookie-httponly: "true"
    cookie-samesite: "lax"
    email-domain: "*"
    http-address: "0.0.0.0:4180"
    insecure-oidc-allow-unverified-email: "true"
    oidc-issuer-url: "https://keycloak.SUBDOMAIN.DOMAIN.TLD/auth/realms/master"
    pass-access-token: "true"
    pass-authorization-header: "true"
    pass-host-header: "true"
    provider-display-name: "Keycloak"
    provider: "oidc"
    reverse-proxy: "true"
    scope: "openid offline_access"
    set-authorization-header: "true"
    set-xauthrequest: "true"
    skip-jwt-bearer-tokens: "true"
    upstream: "file:///dev/null"
    whitelist-domain: ".DOMAIN.TLD"
```

What am I missing?
