### ISSUE TITLE
OIDC + DEX: failed to verify id token signature

### ISSUE THREAD

**Issue by pburgisser** [oauth2-proxy/oauth2-proxy#1338]
In incognito mode (chrome), after clicking on login, sometimes I get an error 500 with the following message on the logs:
`Error redeeming code during OAuth2 callback: could not verify id_token: failed to verify signature: failed to verify id token signature
`

## Steps to Reproduce (for bugs)

```
DEX config:
  issuer: https://auth.shto.zz
  storage:
    type: memory
  enablePasswordDB: false
  logger:
    level: "debug"
  connectors:
    - type: ldap
      id: ldap
      name: ldap
      config:
        host: ldap.shto.zz:636
        insecureSkipVerify: true
        insecureNoSSL: false
        usernamePrompt: Username
        userSearzz:
          baseDN: o=shto,c=zz
          filter: "(objectClass=posixAccount)"
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: sn
        groupSearzz:
          baseDN: ou=groups,o=shto,c=zz
          filter: "(objectClass=EPFLGroupOfPersons)"
          userAttr: uid
          groupAttr: memberUid
          nameAttr: cn

  staticClients:
  - id: oauth2-proxy
    secret: proxy
    name: OAuth2 Proxy
    redirectURIs:
    - https://client-demo.shto.zz/oauth2/callback
```

```
oAuth2 config:
    provider = "oidc"
    upstreams = [
      "http://localhost:8888"
    ]
    https_address = ":9117"
    http_address = ":9116"
    client_id = "oauth2-proxy"
    client_secret = "proxy"
    redirect_url = "https://client-demo.shto.zz/oauth2/callback"
    oidc_issuer_url = "https://auth.shto.zz"
    cookie_secure = false
    cookie_secret = "secretsssecretss"
    cookie_domains = ".shto.zz"
    email_domains = [
      "*"
    ]
    htpasswd_file = "/etc/oauth/htpasswd"
    custom_templates_dir = "/etc/oauth/templates"
    ssl_insecure_skip_verify = true
```

## workaround

Restarting oauth proxy helps

- Version used: 7.1.3
