### ISSUE TITLE
Documentation with Traefik and Kubernetes

### ISSUE THREAD

**Issue by MatteoGioioso** [oauth2-proxy/oauth2-proxy#1355]
I have been trying for days and countless hours to make this thing work with Traefik, however not matter what I have tried nothing has been working so far.

I have tried first with Nginx ingress controller and managed to make it work, so I am sure that my provider (Cognito) and the oauth2-proxy pod is working correctly.

I am trying to configure Oauth-proxy with Traefik and Linkerd dashboard, however the documentation on Kubernetes specific is missing and the example provided does not work for me: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#forwardauth-with-401-errors-middleware

So, I am using an EKS 1.20 cluster and we have Traefik installed via helm chart

```
replicas: 1

rbac:
  enabled: true

accessLogs:
  enabled: false

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "my-certs"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

externalTrafficPolicy: Local

ssl:
  enabled: true
  enforced: true
  upstream: true
```

```
helm upgrade -i traefik traefik/traefik -f traefik-values.yaml
```

This is the config of my oauth proxy, which works with Nginx. 
In the Oauth-proxy there is no mention about Traefik so I guess this should work as well:

```
config:
  clientID: "xxxxx"
  clientSecret: "xxxxxx"
  cookieSecret: "xxxx"
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]

extraArgs:
  oidc-issuer-url: "https://cognito-idp.<region>.amazonaws.com/<pool_id>"
  oidc-jwks-url: "https://cognito-idp.<region>.amazonaws.com/<pool_id>/.well-known/jwks.json"
  provider: oidc
  provider-display-name: "Cognito SSO"
  cookie-secure: false
  cookie-name: "_oauth2_proxy"
  skip-provider-button: true
  scope: openid
  
```

This is the configuration adapted from the example for Kubernetes:

<details>

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: linkerd-viz
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth
  namespace: linkerd-viz
spec:
  forwardAuth:
    address: https://mycompany.com/oauth2/auth
    trustForwardHeader: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors
  namespace: linkerd-viz
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      port: 80
    query: "/oauth2/sign_in"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: linkerd-viz
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host=(`mycompany.com`) && PathPrefix(`/oauth2/`)"
      kind: Rule
      services:
        - kind: Service
          name: oauth2-proxy
          port: 80
      middlewares:
        - name: auth-headers

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: linkerd-dashboard-ingress-v2
  namespace: linkerd-viz
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: traefik-issuer
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host=(`mycompany.com`)"
      kind: Rule
      services:
        - name: web
          namespace: linkerd-viz
          kind: Service
          port: 8084
      priority: 1
      middlewares:
        - name: oauth-errors
        - name: oauth-auth
  tls:
    secretName: linkerd-dashboard-ssl-cert

```

</details>

I have also tried some of the "workaround" proposed in this issue: https://github.com/oauth2-proxy/oauth2-proxy/issues/46#issuecomment-502144577

<details>

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-oauth2-proxy-signin
spec:
  errors:
    query: /oauth2/sign_in
    service:
      name: oauth2-proxy
      port: 80
    status:
      - "401"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-oauth2-proxy-verify
spec:
  forwardAuth:
    address: http://oauth2-proxy:80/oauth2/auth
    trustForwardHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: alertmanager-redirect-header-middleware
spec:
  headers:
    customRequestHeaders:
      X-Auth-Request-Redirect: https://mycompany.com/
    customResponseHeaders:
      X-Auth-Request-Redirect: https://mycompany.com/
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkerd-dashboard-ingress
  namespace: linkerd-viz
  annotations:
    kubernetes.io/ingress.class: traefik-ingress
    traefik.ingress.kubernetes.io/router.middlewares: alertmanager-redirect-header-middleware@kubernetescrd,traefik-oauth2-proxy-signin@kubernetescrd,traefik-oauth2-proxy-verify@kubernetescrd
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8084
```

</details>

When I go and hit example.com it will just say 404. 
Honestly I am on a dead end, but the devils is in the details and I am quite sure I am missing that little detail =)

Any help is appreciate if you need I can even make a PR to add more docs for Kubernetes specific configuration.

Thanks

PS: 
- So far I have posted on Stackoverflow and The traefik forum, but I have received no answer
- This link on your docs is broken: https://doc.traefik.io/traefik/middlewares/forwardauth/

**Comment by MatteoGioioso** [comment]
I have cleaned up a bit and tried to make it more simple using, this time I am not using Linkerd dashboard, which seems that is not even working with Traefik at all. But I am using a working route which I know I can access:

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth
spec:
  forwardAuth:
    address: https://mycompany.com/oauth2/auth
    trustForwardHeader: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      port: 80
    query: "/oauth2/sign_in"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`mycompany.com`) && PathPrefix(`/oauth2/`)"
      kind: Rule
      services:
        - kind: Service
          name: oauth2-proxy
          port: 80
      middlewares:
        - name: auth-headers

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: linkerd-dashboard-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`mycompany.com`)"
      kind: Rule
      services:
        - name: nginx-service
          kind: Service
          port: 8080
      priority: 1
      middlewares:
        - name: oauth-auth
        - name: oauth-errors

```

With this configuration now it will get redirected, however it goes in loop and I have `ERR_TOO_MANY_REDIRECTS`

**Comment by akosveres** [comment]
Here's our deployment of oauth proxy with traefik that works:

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  routes:
    - match: "Host(`oauth2.<domain.tld>`)"
      kind: Rule
      middlewares:
        - name: oauth2-proxy-headers
      services:
        - name: oauth2-proxy
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-headers
  namespace: oauth2-proxy
spec:
  headers:
    sslRedirect: false
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---
# Source: oauth2-proxy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  stringDataFrom:
    secretsManagerSecretRef: 
      secretId: ops/k8s/oauth2_proxy
---
# Source: oauth2-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 44180
      protocol: TCP
      targetPort: metrics
      name: metrics
  selector:
    app: oauth2-proxy
---
# Source: oauth2-proxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "44180"
      labels:
        app: oauth2-proxy
    spec:
      serviceAccountName: oauth2-proxy
      containers:
      - name: oauth2-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.1.3"
        imagePullPolicy: Always
        args:
          - --http-address=0.0.0.0:4180
          - --metrics-address=0.0.0.0:44180
          - --reverse-proxy=true
          - --upstream=static://202
          - --silence-ping-logging
          - --cookie-domain=".<domain.tld>"
          - --whitelist-domain=".<domain.tld>"
          - --provider=oidc
          - --redirect-url=https://oauth2.<domain.tld>/oauth2/callback
          - --oidc-issuer-url=https://<company>.okta.com
          - --email-domain=<domain.tld>
          - --pass-access-token=true
          - --footer=Internal Tool - Access restricted to employees only.
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy
              key: client_id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy
              key: client_secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth2-proxy
              key: cookie_secret
        ports:
          - containerPort: 4180
            name: http
            protocol: TCP
          - containerPort: 44180
            protocol: TCP
            name: metrics
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
          successThreshold: 1
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext:
          allowPrivilegeEscalation : false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
```

And here's the traefik admin endpoint that's using oauth2-proxy:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-admin
  namespace: kube-system
spec:
  routes:
    - match: Host(`traefik.<domain.tld>`)
      kind: Rule
      middlewares:
        - name: traefik-forward
      services:
        - name: traefik-ingress-lb
          port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-sso-oauth2
  namespace: oauth2-proxy
spec:
  routes:
    - match: "Host(`traefik.<domain.tld>`) && PathPrefix(`/oauth2/`)"
      kind: Rule
      middlewares:
        - name: oauth2-proxy-headers
      services:
        - name: oauth2-proxy
          namespace: oauth2-proxy
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward
  namespace: kube-system
spec:
  forwardAuth:
    address: https://oauth2.<domain.tld>
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
```

Traefik is just a simple kubernetes deployment, TLS termination is on the ALB via ACM in front of Traefik.

**Comment by vangahari** [comment]
Hey @MatteoGioioso seems with nginx ingress controller works for you. I am not sure how you are tried and did setup. Here's my entire Configuration https://github.com/oauth2-proxy/oauth2-proxy/issues/1367, for me its redirecting to service but not working due to some Cookie issue. If you have any thoughts around this please help us.

**Comment by MatteoGioioso** [comment]
For all other passing by, I have solved by using (traefik-auth-forward](https://github.com/thomseddon/traefik-forward-auth) instead of Oauth2-proxy

**Comment by vangahari** [comment]
@MatteoGioioso Thanks for the reply. 
Yes. I am not terminating SSL at ELB level, I dont think so its SSL issue. Its redirecting to application. Only with with some cookies it seems. 
Yes, I am specifying right callback otherwise it would not even redirected. I will try with Configuration as you mentioned above. And you mentioned some NLB configuration right, I am using classic load balancer. I dont get where you used the above NLB configuration. Is that nginx-ingress controller service..?

**Comment by MatteoGioioso** [comment]
@vangahari the annotations comes from the nginx ingress controller chart: https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx#aws-l7-elb-with-ssl-termination

I have just changed to use the NLB, I would start by fixing the SSL just to rule it out

**Comment by yongzhang** [comment]
@akosveres Could you share why we need those headers here?

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-headers
  namespace: oauth2-proxy
spec:
  headers:
    sslRedirect: false
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
```

**Comment by thatInfrastructureGuy** [comment]
Here is what worked for me. 

I have same situation as @akosveres.
> Traefik is just a simple kubernetes deployment, TLS termination is on the ALB via ACM in front of Traefik.

Assuming:
* oauth2-proxy is deployed in oauth2-proxy namespace
* kubernetes-dashboard is deployed in kubernetes-dashboard namespace


*OAuth2-Proxy settings*
```yaml
          - --http-address=0.0.0.0:4180
          - --metrics-address=0.0.0.0:44180
          - --provider=oidc
          - --provider-display-name="Dex"
          - --client-id=xxxx
          - --client-secret=xxxx
          - --redirect-url=http://oauth2-proxy.internal.company.com/oauth2/callback
          - --oidc-issuer-url=https://dex.internal.company.com/dex
          - --cookie-secure=false
          - --cookie-secret=xxxx
          - --cookie-domain=.internal.company.com
          - --whitelist-domain=.internal.company.com
          - --cookie-samesite=lax
          - --session-store-type=redis
          - --redis-connection-url=redis://redis:6379
          - --email-domain=*
          - --upstream="static://202"
          - --oidc-groups-claim=groups
          - --oidc-email-claim=email
          - --scope=openid profile email groups #depends on your provider
          - --pass-authorization-header=true
          - --set-authorization-header=true
          - --set-xauthrequest=true
          - --pass-access-token=true
          - --pass-host-header=true
          - --skip-provider-button=true
          - --skip-jwt-bearer-tokens=true
          - --insecure-oidc-allow-unverified-email=false
          - --insecure-oidc-skip-issuer-verification=true
          - --show-debug-on-error=false
          - --silence-ping-logging=true
          - --ssl-insecure-skip-verify=true
          - --ssl-upstream-insecure-skip-verify=true
          - --reverse-proxy=true
          - --force-https=false

```
*Traefik for kubernetes-dashboard*
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: kubernetes-dashboard
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`kubernetes-dashboard.internal.company.com`)
    kind: Rule
    services:
    - name: kubernetes-dashboard
      port: 8080
    middlewares:
    - name: auth
```

*Traefik for OAuth2-proxy*
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`oauth2-proxy.internal.company.com`)
    kind: Rule
    services:
    - name: oauth2-proxy
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wildcard-auth
  namespace: oauth2-proxy
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`*.internal.company.com`) && PathPrefix(`/oauth2/`)
    kind: Rule
    services:
    - name: oauth2-proxy
      port: 80
---
```
