### ISSUE TITLE
Limiting Resource access based on claims or groups

### ISSUE THREAD

**Issue by ReignbowRoad** [oauth2-proxy/oauth2-proxy#1360]
## Expected Behavior

We're considering migrating away from the Louketo Proxy to OAuth2-Proxy which we're using KeyCloak. In Louketo, we have some configuration that we can't seem to replicate in OAuth2-Proxy. The documentation doesn't make it clear if this is possible.

First is limiting access to uri's via group:

````yaml
resources:
- uri: /api/v1/servicea
  methods:
  - GET
  groups:
  - group-a
  - group-b
- uri: /api/v1/serviceb
  methods:
  - POST 
  groups:
  - group-c
````

The second is using the `match-claims` property to restrict access to a resource based on values held in one or more claims:

````yaml
match-claims:
   preferred_username: usera
````

Is this kind of configuration supported by OAuth2-Proxy. If yes, can someone provide me with more information on how to achieve this?

## Current Behavior

N/a

## Possible Solution

N/a

## Steps to Reproduce (for bugs)

N/a

## Context

N/a

## Your Environment

N/a

- Version used: latest
