### ISSUE TITLE
Oauth Cookie Issue

### ISSUE THREAD

**Issue by vangahari** [oauth2-proxy/oauth2-proxy#1367]
Hello Team, 

We have deployed Jeager in the Kubernetes cluster with ClusterIP, Jeager doesn't have the support of authentication. So we wanted to put the Authentication mechanism using the Oauth2-proxy using Gitlab OpenID. To communicate the Jeager in the K8s we have Nginx-ingress controller. When I hit the domain for Jeager, its redirected to Gitlab, So authentication is happening there and it is redirecting to Jeager application, But the Problem is that, Oauth2 is not sending the cookie to Jeager.

Please verify my Configuration.
Nginx-ingress installation: 
https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-manifests

Gitlab OpenID Application
I gave redirect URI: **http://jeager.example.com/oauth2/callback**

<img width="1437" alt="Screenshot 2021-09-15 at 3 23 59 PM" src="https://user-images.githubusercontent.com/45491142/133412619-8be0a07d-5955-46ce-a43f-707fe8c13c6d.png">

**Oauth2 kubernetes manifest file**: 

``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 4180
          protocol: TCP
        args:
        - --provider=gitlab
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --cookie-secure=false
        - --redirect-url=http://jeager.example.com/oauth2/callback
        - --skip-provider-button=false
        - --set-xauthrequest=true
        - --skip-auth-preflight=false
        - --skip-oidc-discovery
        - --oidc-issuer-url=https://gitlab.com
        - --login-url=https://gitlab.com/oauth/authorize
        - --redeem-url=https://gitlab.com/oauth/token
        - --oidc-jwks-url=https://gitlab.com/oauth/discovery/keys
        - --email-domain=*
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: <GITLAB_APP_ID>
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: <GITLAB_APP_SECRET>
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: "COOKIE"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy
```

I have Generated cookie by using the below command 
```$ python -c 'import os,base64; print(base64.b64encode(os.urandom(16)).decode("ascii"))'```

I used the cookie here
```
- name: OAUTH2_PROXY_COOKIE_SECRET
          value: "COOKIE"
``` 
          
**Nginx-rules  kuberntes manifest file for forwarding the traffic here:**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micro-ingress
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-url: "http://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  rules:
    - host: "jeager.example.com"
      http:
        paths:
          - backend:
              serviceName: tracing
              servicePort: 80
            path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micro-ingress-oauth
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /oauth2

spec:
  rules:
    - host: "oauth2.example.com"
      http:
        paths:
          - backend:
              serviceName: oauth2-proxy
              servicePort: 4180
            path: /oauth2
```

I have configured the Nginx-ingress with load balancer type service in the AWS. It has been launched the AWS classic load balancer. 
 The Domain which I mentioned in the Gitlab application and for Jeager applications, created in Route53 records which are mapped to load balancer which was created by Ingress controller 

when I hit the **oauth2.example.com** its opening Oauth page

<img width="986" alt="Screenshot 2021-09-15 at 3 35 57 PM" src="https://user-images.githubusercontent.com/45491142/133414323-5574b58d-15bf-448e-8706-c1b2ad7c88d0.png">

Then its authenticating with Gitlab,
<img width="634" alt="Screenshot 2021-09-15 at 3 36 46 PM" src="https://user-images.githubusercontent.com/45491142/133414470-0a8aee4c-2b50-4a7c-b840-b46308e9d47b.png">

Then its redirecting to Jeager **jeager.example.com**, but due to Cookie issue its not sending the traffic properly
<img width="1439" alt="Screenshot 2021-09-15 at 3 38 03 PM" src="https://user-images.githubusercontent.com/45491142/133414697-889a7efb-6f2d-4066-8b82-89fc997c22f4.png">

It is the response URL when it is redirecting to Jeager Dashboard
``` http://jeager.example.com/oauth2/callback?code=6710988c56ece8d75a7386d4d1f55361fadf80c065fb86bacfc51adebf3dd40c&state=17dade19ba05bd26569df7b2e3d84b13:/```

Please help us to resolve this issue. Any information would be appreciated.
Thanks.
