### ISSUE TITLE
injectRequestHeaders for cognito:groups

### ISSUE THREAD

**Issue by fkarakas** [oauth2-proxy/oauth2-proxy#1370]
Hello,
I am trying to inject the cognito:groups in `X-Forwarded-Groups` : 
```
injectRequestHeaders:
- name: X-Forwarded-Groups
  values:
  - claim: groups
 ```
Got only, no group : 
```
X-Forwarded-Email: fkarakas@xxx.yyy
X-Forwarded-For: 192.168.96.1
X-Forwarded-User: <som uuid>
```
i tried to set : 
```
injectRequestHeaders:
- name: X-Forwarded-Groups
  values:
  - claim: cognito:groups
 ```
The authorization header jwt has a field:
```
  "cognito:groups": [
    "ua:admin",
    "rc:user",
    "pa:access",
    "ua:manager"
  ],
```
if you have any idea.

using latest version of the proxy:

```
  oauth2-proxy:
    image:  quay.io/oauth2-proxy/oauth2-proxy
    hostname: oauth2-proxy
    command: --alpha-config=/oauth2-proxy.yaml --config=/oauth2-proxy-alpha.cfg
```
BTW nice project 👍
