### ISSUE TITLE
Unable to Authenticate K8 Nginx Ingress using Keycloak, OAuth2-Proxy

### ISSUE THREAD

**Issue by rahgadda** [oauth2-proxy/oauth2-proxy#1373]
I wanted to authenticate deployment based on image `docker.io/threecomma/helloworld` using `oauth2-proxy` & `keycloak`

## Expected Behavior
- System should not allow accessing ingress URL of helloworld without getting authenticating using keycloak

## Current Behavior
- System is redirecting to keycloak for authentication. Once authenticated, it is pointing to helloworld - `Working as Expected`
- When tried to access the helloworld URL, it's not getting authenticating but displaying helloworld  - `System should not allow this. Sidecar should authenticate`

## Steps to Reproduce (for bugs)
- Created keycloak client based on  details provided [here](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-auth-provider)
- Deployed below

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 4180
          protocol: TCP
        args:
        - --provider=keycloak
        - --client-id=kubectl
        - --client-secret=<ttttt>
        - --login-url=https://rahulkirangaddam.hopto.org/auth/realms/kubernetes/protocol/openid-connect/auth
        - --redeem-url=https://rahulkirangaddam.hopto.org/auth/realms/kubernetes/protocol/openid-connect/token
        - --profile-url=https://rahulkirangaddam.hopto.org/auth/realms/kubernetes/protocol/openid-connect/userinfo
        - --validate-url=https://rahulkirangaddam.hopto.org/auth/realms/kubernetes/protocol/openid-connect/userinfo
        - --keycloak-group=/admin
        - --keycloak-group=/basic_user
        - --allowed-group=/basic_user
        - --allowed-group=/admin
        - --cookie-secret=PP1XU50W4ieZyYCZkufD3A==
        - --email-domain=*
        - --oidc-issuer-url=https://rahulkirangaddam.hopto.org/auth/realms/kubernetes
        env:
        - name: OAUTH2_PROXY_COOKIE_DOMAIN
          value: oauth2-domain
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: "PP1XU50W4ieZyYCZkufD3A=="
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
        - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
          value: "true"
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: 0.0.0.0:4180
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "*"
        - name: OAUTH2_PROXY_PROVIDER
          value: keycloak
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: https://rahulkirangaddam.hopto.org/auth/realms/kubernetes
        - name: OAUTH2_PROXY_CLIENT_ID
          value: kubectl
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: <ttt>
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: https://rahulkirangaddam.hopto.org/oauth2/callback 
        - name: OAUTH2_PROXY_UPSTREAMS
          value: https://rahulkirangaddam.hopto.org/oauth2/callback
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: docker.io/threecomma/helloworld
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: my-nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-nginx-prod
spec:
  acme:
    email: gaddam.rahul@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-prod
spec:
  secretName: certificate-prod-nginx
  dnsNames:
  - rahulkirangaddam.hopto.org
  issuerRef:
    name: letsencrypt-nginx-prod
    kind: ClusterIssuer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /oauth2
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    cert-manager.io/issuer: "letsencrypt-nginx-prod"

  name: oauth2-ingress
spec:
  tls:
  - hosts:
    - rahulkirangaddam.hopto.org
    secretName: certificate-prod-nginx
  rules:
  - host: rahulkirangaddam.hopto.org
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
    cert-manager.io/issuer: "letsencrypt-nginx-prod"
    ingress.kubernetes.io/auth-url: https://rahulkirangaddam.hopto.org/oauth2/auth
    ingress.kubernetes.io/auth-signin: https://rahulkirangaddam.hopto.org/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  name: nginx-ingress
spec:
  tls:
  - hosts:
    - rahulkirangaddam.hopto.org
    secretName: certificate-prod-nginx
  rules: 
    - host: rahulkirangaddam.hopto.org
      http:
        paths:
          - path: /oauth2/callback
            pathType: Prefix
            backend:
              service:
                name: my-nginx
                port:
                  number: 8080
```

- On accessing https://rahulkirangaddam.hopto.org/oauth2 it's routing to keycloak login but on https://rahulkirangaddam.hopto.org/oauth2/callback system is not routing to  keycloak login

## Your Environment
This cluster is based on Oracle OCI Arm64. Installation details are available [here](https://dev.to/rahgadda/installing-k8-on-arm64-4-cpu-24gb-ram-648)

- Version used:
`quay.io/oauth2-proxy/oauth2-proxy               latest-arm64 `
