### ISSUE TITLE
Traefik and OIDC-Provider with Keycloak: [AuthFailure] Invalid authentication via Oauth2: unauthorized

### ISSUE THREAD

**Issue by Raskosk** [oauth2-proxy/oauth2-proxy#1378]
I'm running a little Testlab for learning purpose.
1 Master + 2 Node-VMs
OS: Debian
Container-Engine: containerd

## Expected Behavior

Secure several Web-Apps (e.g. whoami-Website) with a centralized Identity Management (Keycloak).

Example:
By calling whoami.example.com (or whoami.example.com/oauth2) I want to redirect to oauth2-proxy.example.com for Authentication, formally Keycloak.
After Authentications, the logged in User should be redirected to whoami.example.com

## Current Behavior

- [x] ForwardAuthentication works; oauth2_proxy shows up.

- [x] Check Auth/Login works, by clicking "Login"-Button keycloak-Login-Form shows up

- [x] Redirect works, after submitting credentials, the redirect to whoami.example.com starts loading

- [ ] ReCheck Auth doesn't work, getting this

![image](https://user-images.githubusercontent.com/75483160/134706348-6d53b37d-47b4-4e2f-af67-de265fbe33b6.png)
Log:

> [2021/09/24 12:34:53] [stored_session.go:76] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session
10.10.10.1 - cec2dc7b-34f8-4cc3-8351-1784f13e7410 - - [2021/09/24 12:34:53] whoami.example.com GET - "/" HTTP/1.1 "Go-http-client/1.1" 403 8121 0.001
10.10.10.10 - 1b06bd72-4e20-4ea0-b6ab-9e5fbc44cb1b - - [2021/09/24 12:34:57] whoami.example.com GET - "/oauth2/start?rd=http%3A%2F%2Fwhoami.example.com%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52" 302 381 0.000
10.10.10.10 - 1ffc1c10-9866-487a-9fbc-afe5b7f3e571 - demo.user@example.com [2021/09/24 12:34:57] [AuthFailure] Invalid authentication via OAuth2: unauthorized
10.10.10.10 - 1ffc1c10-9866-487a-9fbc-afe5b7f3e571 - - [2021/09/24 12:34:57] whoami.example.com GET - "/oauth2/callback?state=BfcE2RTAA0iOJhz6c9TxlfLEajKm1nEdRE49dledS0A%3Ahttp%3A%2F%2Fwhoami.example.com%2F&session_state=a3cf1c64-8c4b-49fe-919f-64ac48d26567&code=c10513ac-86b0-49af-bc7b-57c04930ff70.a3cf1c64-8c4b-49fe-919f-64ac48d26567.b65b94df-4932-473b-8ce2-41842489294c" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52" 403 2703 0.023

When I call oauth2-proxy.example.com, I'm getting exactly the same error.

## Steps to Reproduce (for bugs)

<ol>
<li>Deploy Traefik (e.g. using official helm chart)</li>
<li>Deploy Keycloak /e.g. using official helm chart</li>
<li>Deploy Oauth2_proxy
<details>
<summary>Show YAML</summary>

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: customadmin
spec:
  routes:
    - match: "Host(`oauth2-proxy.example.com`)"
      kind: Rule
      middlewares:
        - name: oauth2-proxy-headers
      services:
        - name: oauth2-proxy
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-headers
  namespace: customadmin
spec:
  headers:
    sslRedirect: false
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---
# Source: oauth2-proxy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: customadmin
---
# Source: oauth2-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: customadmin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 44180
      protocol: TCP
      targetPort: metrics
      name: metrics
  selector:
    app: oauth2-proxy
---
# Source: oauth2-proxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: customadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      serviceAccountName: oauth2-proxy
      containers:
      - name: oauth2-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.1.3"
        imagePullPolicy: Always
        args:
          - --http-address=0.0.0.0:4180
          - --metrics-address=0.0.0.0:44180
          - --reverse-proxy=true
          - --upstream=static://202
          - --silence-ping-logging
          - --cookie-domain=".example.com"
          - --whitelist-domain=".example.com"
          - --provider=oidc
          - --redirect-url=http://whoami.example.com/oauth2/callback
          - --oidc-issuer-url=http://keycloak.example.com/auth/realms/TEST
          - --email-domain=.example.com
          - --pass-access-token=true
          - --cookie-secure=false
          - --footer=Internal Tool - Access restricted to employees only.
        env:
        - name: http_proxy
          value: "http://proxy:3128"
        - name: https_proxy
          value: "http://proxy:3128"
        - name: no_proxy
          value: ".example.com"
        - name: OAUTH2_PROXY_LOGIN_URL
          value: "https://keycloak.example.com/auth/realms/TEST/protocol/openid-connect/auth"
        - name: OAUTH2_PROXY_REDEEM_URL
          value: "https://keycloak.example.com/auth/realms/TEST/protocol/openid-connect/token"
        - name: OAUTH2_PROXY_PROFILE_URL
          value: "https://keycloak.example.com/auth/realms/TEST/protocol/openid-connect/userinfo"
        - name: OAUTH2_PROXY_VALIDATE_URL
          value: "https://keycloak.example.com/auth/realms/TEST/protocol/openid-connect/userinfo"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: "oauth2-proxy"
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: "secret99-1207-4e96-8f4e-bananad92d8"
        - name: OAUTH2_PROXY_COOKIE_SECRET
	  value: "test1234567890ab"
        ports:
          - containerPort: 4180
            name: http
            protocol: TCP
          - containerPort: 44180
            protocol: TCP
            name: metrics
        livenessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          timeoutSeconds: 1
          successThreshold: 1
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        securityContext:
          allowPrivilegeEscalation : false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-admin
  namespace: kube-system
spec:
  routes:
    - match: Host(`traefik.example.com`)
      kind: Rule
      middlewares:
        - name: auth-forward
      services:
        - name: traefik
          port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-sso-oauth2
  namespace: customadmin
spec:
  routes:
    - match: "Host(`whoami.example.com`) && PathPrefix(`/oauth2/`)"
      kind: Rule
      middlewares:
        - name: oauth2-proxy-headers
      services:
        - name: oauth2-proxy
          namespace: customadmin
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-forward
  namespace: kube-system
spec:
  forwardAuth:
    address: https://oauth2-proxy.example.com
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
```
</details>

</li>
<li>Deploy whoami-Example
<details>
<summary>Show YAML</summary>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
  - name: http
    port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-auth
spec:
  forwardAuth:
    address: http://oauth2.example.com
    trustForwardHeader: true
    authResponseHeaders:
      - "X-Auth-Request-User"
      - "X-Auth-Request-Email"
      - "Authorization"
      - "Set-Cookie"
    authRequestHeaders:
      - "Accept"
      - "X-CustomHeader"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:                     
    - web
  routes:                           
  - kind: Rule
    match: Host(`whoami.example.com`)
    priority: 10                   
    middlewares:                   
    - name: test-auth              
      namespace: default
    services:                      
    - kind: Service
      name: whoami-service
      namespace: customadmin
      passHostHeader: true
      port: 80                     
      responseForwarding:
        flushInterval: 1ms
      sticky:
        cookie:
          httpOnly: true
          name: cookie
          secure: true
          sameSite: none
      strategy: RoundRobin
      weight: 10
```
</details>

</li>
</ol>

## Context

At first, I tried around with the keycloak provider, but couldn't get it running.
So I switch to the OIDC-provider so I get at least some progress.

What am I missing in my example?

Would be nice if somebody could share a working example.

## Your Environment

K8s on 3 vSphereVMs
1 Master
2 Worker
OS: Debian 10
Container-Runtime: containerd

- Version used:
- Kubernetes: v1.22.2
- Web-Routing/ReverseProxying: Traefik v 2.5.1
- Keycloak: v15.0.0
- Oauth2_proxy: v7.1.3
