### ISSUE TITLE
Error after keycloak update: "Invalid client secret"

### ISSUE THREAD

**Issue by rparree** [oauth2-proxy/oauth2-proxy#1382]
## Expected Behavior

This week i had to setup a new keycloak. The previous one had a corrupted database.  This is the only component that has changed. I set-up the realm and client as before. 

However the The `oauth2-proxy/oauth2-proxy` logs:

```
[logger.go:508] Error redeeming code during OAuth2 callback: no access token found {"error":"unauthorized_client","error_description":"Invalid client secret"}
```

I checked the source code in keycloak, and the conditions under which keycloak throws this error is when the send secret does not match (https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/services/src/main/java/org/keycloak/authentication/authenticators/client/ClientIdAndSecretAuthenticator.java#L135). (There's a second case, when the client does not have a secret, but it has)

The oauth2-proxy (inside k8s) process use an environment variable:

```
/bin/oauth2-proxy --provider=keycloak --client-id=totoclient --oidc-issuer-url=https://…//auth/realms/toto --client-secret=$KEYCLOAK_CLIENT_SECRET" --login-url=https://…/auth/
realms/toto/protocol/openid-connect/auth --redeem-url=https://…/auth/realms/toto/
protocol/openid-connect/token --validate-url=https://…/auth/realms/toto/protocol/openid-conn
ect/userinfo --cookie-secret=abc--skip-provider-button=true --cookie-expire=10m --cookie-refresh=4m --r
edis-connection-url=redis://redis-oauth-headless:6379 --email-domain=* --http-address=:4180 --pass-access-token=true --set-xa
uthrequest=true --pass-authorization-header=true --set-authorization-header=true --skip-jwt-bearer-tokens=true --upstream=sta
tic:// --skip-auth-regex=^\/$ --skip-auth-regex=^\/index.html --skip-auth-regex=^\/help --skip-auth-regex=^\/setup --skip-aut
h-regex=^\/sass --skip-auth-regex=\/images --skip-auth-regex=^\/\d{3}\.html --skip-auth-regex=^\/\.well-known/.*
```

Checking the environment of the container confirms the value of `KEYCLOAK_CLIENT_SECRET` is set correctly

## Your Environment

- Version used: `v6.1.1` (also tried `v7.1.3`, same results)
- k8s (on prem, version `1.20.11`)
- keycloak version `11.0.3` (also tried `15.0.2`, same results)

I am able to get the code and token going through the OAuth "Authorisation code" flow manually.  

Keycloak is the only changed component, so i realise the problem should lie there, but i am however able to get the code and token using curl (using the same parameters as is in the `Redeem` function (https://github.com/oauth2-proxy/oauth2-proxy/blob/a87c27b6bf05f9a9373c1e8c1320bab3fb378e77/providers/provider_default.go#L52)

Thanks for any insight into solving this problem

**Comment by JoelSpeed** [comment]
Can you share the deployment manifest that you have deployed via K8s? I'm wondering if there's an issue with the environment substitution, I know in the past this has caused issues for people

**Comment by rparree** [comment]
Thanks for you reply.

Please find the `container` part below:

```yaml
containers:
  - name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    env:
      - name: KEYCLOAK_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: keycloak-toto
            key: toto-client-secret
    args:
      - '--provider=keycloak'
      - '--client-id=toto'
      - '--oidc-issuer-url=https://sso.toto.com/auth/realms/toto'
      - '--client-secret=$KEYCLOAK_CLIENT_SECRET'
      - '--login-url=https://sso.toto.com/auth/realms/toto/protocol/openid-connect/auth'
      - '--redeem-url=https://sso.toto.com/auth/realms/toto/protocol/openid-connect/token'
      - '--validate-url=https://sso.toto.com/auth/realms/toto/protocol/openid-connect/userinfo'
      - '--cookie-secret=abc' # python -c 'import secrets,base64; print(base64.b64encode(secrets.token_bytes(16)));'
      - '--skip-provider-button=true'
      - '--cookie-expire=10m'
      - '--cookie-refresh=4m'
      #            - '--cookie-httponly=true'
      #            - '--cookie-secure=true'
      - '--redis-connection-url=redis://redis-oauth-headless:6379'
      - '--email-domain=*'
      - '--http-address=:4180'
      - '--pass-access-token=true'    
      - '--set-xauthrequest=true'
      - '--pass-authorization-header=true' 
      - '--set-authorization-header=true'
      - '--skip-jwt-bearer-tokens=true' 
      - '--upstream=static://'
      - '--skip-auth-regex=^\/$'
      - '--skip-auth-regex=^\/index.html'
      - '--skip-auth-regex=^\/help'
      - '--skip-auth-regex=^\/setup'
      - '--skip-auth-regex=^\/sass'
      - '--skip-auth-regex=\/images'
      - '--skip-auth-regex=^\/\d{3}\.html'
      - '--skip-auth-regex=^\/\.well-known/.*'

```

I tried `"${KEYCLOAK_CLIENT_SECRET}"` in an attempt to find a solution. Note that this code has been unchanged and worked with my previous installation of keycloak.

Thanks
