### ISSUE TITLE
User session should be removed during refresh when the user has been disabled by the IDP

### ISSUE THREAD

**Issue by breedjaram32** [oauth2-proxy/oauth2-proxy#1420]
Hi,
i have testing a new keycloak-oidc provider on v7.2.0. Works fine but I have a problem with refresh session.
I am solving the situation of how to log off a user remotelly if his account is compromised or if he no longer has access.

## Current Behavior

My actual configuration oaut2-proxy
````yaml
        - --provider=keycloak-oidc
        - --client-id=kcclient
        - --client-secret=XXXXXXX
        - --cookie-secret=XXXXXXXXX
        - --oidc-issuer-url=https://URL/auth/realms/local
        - --email-domain=*
        - --scope=openid profile email users
        - --cookie-domain=.domain.com
        - --whitelist-domain=.domain.com
        - --cookie-refresh=5m
        - --cookie-expire=168h
        - --http-address=0.0.0.0:8091
        - --cookie-name=_oauth2_proxy_kctest
        - --reverse-proxy=true
        - --session-store-type=redis
        - --redis-connection-url=redis://URL:6379
        - --redis-password=PW
        - --set-xauthrequest=true
        - --set-authorization-header=true
        - --show-debug-on-error=true
        - --silence-ping-logging=true
````
My actual kubernetes ingress annotation
````
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User, X-Auth-Request-Email, X-Auth-Request-Preferred-Username, X-Auth-Request-Groups"
    nginx.ingress.kubernetes.io/auth-url: "https://URL/oauth2/auth?allowed_groups=group1,group2"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/auth-signin: "https://URL/oauth2/start?rd=https://$host$request_uri"
````

## Steps to Reproduce (for bugs)

Login via keycloak to destination site. everything will be fine. 

1. When user is disabled in keycloak so after cookie-refresh 5m I will see error
`[2021/10/25 15:01:56] [stored_session.go:124] Unable to refresh session: error refreshing tokens: unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"User disabled"}
10.30.21.14 - 3a6255a88cdbf9e40b9d8072ba8b0482 - email@XX.cz [2021/10/25 15:03:39] URL_OF_SITE GET - "/oauth2/auth?allowed_groups=group1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15" 202 0 0.006`

**_But I have a still 202 access to site! This is a problem. User is logged out after cookie expire 1 hour_**

2. When I kill user session manually in Keycloak - after cookie-refresh 5m I will see error
 `[2021/10/25 14:50:21] [stored_session.go:119] Refreshing session - User: c6a948e8-2792-4401-8206-ecd9534ba500; SessionAge: 6m8.379203922s
[2021/10/25 14:50:21] [stored_session.go:124] Unable to refresh session: error refreshing tokens: unable to redeem refresh token: failed to get token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Session not active"}`
`10.30.21.15 - 7c4508d0c1ba1970a057985be8f918e9 - email@XX.cz  URL_OF_SITE GET - "/oauth2/auth?allowed_groups=group2" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15" 202 0 0.023`

**_But I have a still 202 access to site! This is a problem. User is logged out after cookie expire 1 hour_**

3. So far, the only functional option to prevent access
- Simply remove a all groups from user in Keycloak
`[2021/10/25 15:05:31] [stored_session.go:119] Refreshing session - User: c6a948e8-2792-4401-8206-ecd9534ba500; SessionAge: 8m58.47999412s
10.30.20.202 - 8a0d8ed227824a34af752f583faeb9fb - email@XX.cz [2021/10/25 15:05:31] URL_OF_SITE GET - "/oauth2/auth?allowed_groups=group2" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15" 403 10 0.037`

**_I have a 403 now! Perfect. User is logged out after cookie-refresh 5 minute_**

## Expected Behavior

I believe that access (get 403) should be blocked even when manual remove a user session or user is disabled.
I tested in one windows on browser (without more panels... without windows close...)

- Version used: v7.2.0
