### ISSUE TITLE
Problems connecting to oauth2-proxy pod

### ISSUE THREAD

**Issue by stumueller** [oauth2-proxy/oauth2-proxy#1428]
I am trying to run an oauth2-proxy pod on my kubernetes cluster. Should I be able to wget -qO- http://podsipaddress:4180/oauth2 and get a response back?

All I am getting is connection refused. when I try externally from a browser to go to https://url.mydomain.com/oauth2 I get the error: "upstream connect error or disconnect/reset before headers. reset reason: connection failure"

my deployment yaml files read as follows:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth2
  labels:
    app: oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
        - name: oauth2
          image: quay.io/oauth2-proxy/oauth2-proxy
          imagePullPolicy: "IfNotPresent"
          args:
          - --email-domain=*
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          ports:
            - name: http
              containerPort: 4180
              protocol: TCP
          env:
            - name: OAUTH2_PROXY_REVERSE_PROXY
              valueFrom:
                configMapKeyRef:
                  name: oauth2-config
                  key: OAUTH2_PROXY_REVERSE_PROXY
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: oauth2-config
                  key: OAUTH2_PROXY_CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: oauth2-config
                  key: OAUTH2_PROXY_CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                configMapKeyRef:
                  name: oauth2-config
                  key: OAUTH2_PROXY_COOKIE_SECRET
            - name: OAUTH2_PROXY_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: oauth2-config
                  key: OAUTH2_PROXY_PROVIDER
```
```
kind: Service
apiVersion: v1
metadata:
  name: oauth2
spec:
  selector:
    app: oauth2
  ports:
    - name: http
      port: 80
      targetPort: http
```

My pod is running ok, its not errored or crashed - I just cant make a connection to it. Can anyone shed any light onto why that might be?

Thanks
