### ISSUE TITLE
Forward on localhost HTTP results in Connection Refused [Potential Question]

### ISSUE THREAD

**Issue by MarianZoll** [oauth2-proxy/oauth2-proxy#1436]
I am trying to configure an oauth2-proxy sidecar in the front of a pre-built community project that does not provide proper authentication/ authorization. In order to set things up on K8s, I started to set things up locally (+ Keycloak Provider already configured) and ran into the following pretty weird behavior. If this is not a bug and I am just getting something wrong, I'd like to add something to the docs or an external blog post to help people not hitting the same issues.

## Expected Behavior

- Traffic is proxied correctly to the respective application on local networks.

## Current Behavior

- Authentication on the IdP works fine so most likely, if you provide support, you can exchange Keycloak for any other IdP,
- The connection is refused locally when the oauth2-proxy container tries to forward traffic to the upstream. 

```
[+] Running 2/2
 ⠿ Container oauth2-proxy_whoami_1        Recreated                                                                                                                                                                                                                                                                                                                    0.1s
 ⠿ Container oauth2-proxy_oauth2-proxy_1  Recreated                                                                                                                                                                                                                                                                                                                    0.1s
Attaching to oauth2-proxy_1, whoami_1
oauth2-proxy_1  | [2021/11/02 14:07:37] [proxy.go:89] mapping path "/" => upstream "http://localhost:4440/"
oauth2-proxy_1  | [2021/11/02 14:07:37] [oauthproxy.go:148] OAuthProxy configured for Keycloak OIDC Client ID: changeme
oauth2-proxy_1  | [2021/11/02 14:07:37] [oauthproxy.go:154] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
whoami_1        | Starting up on port 80
oauth2-proxy_1  | [2021/11/02 14:07:41] [error_page.go:93] Error proxying to upstream server: dial tcp 127.0.0.1:4440: connect: connection refused
oauth2-proxy_1  | 172.22.0.1:57866 - 3b7c9751-1f59-486e-a2a7-b298a41ef831 - usermail@test.com [2021/11/02 14:07:41] localhost:4180 GET / "/maintenance" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36" 502 2303 0.002
```

## Possible Solution

Sorry - I am happy to discuss about solutions and working on the resolution if necessary.

## Steps to Reproduce (for bugs)

- Configure an auth provider of your choice (and change the config below accordingly),
- Start `docker compose up` 
```
version: "3.7"
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
    ports:
      - 4180:4180
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_CLIENT_ID: changeme
      OAUTH2_PROXY_CLIENT_SECRET: changeme
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://<keycloak-host>/auth/realms/<realm>
      OAUTH2_PROXY_UPSTREAMS: "http://localhost:4440/"
      OAUTH2_PROXY_COOKIE_SECRET: changeme
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_ERRORS_TO_INFO_LOG: "true"
      OAUTH2_PROXY_HTTP_ADDRESS: http://:4180
  whoami:
    image: containous/whoami
    ports:
      - 4440:80
```
- Access http://localhost:4440 or http://localhost:4440/maintenance to verify the application container works fine, 
- Acess http://localhost:4180/ to use the proxy, 
- Authenticate at the auth provider, 
- Experience a 502 Bad Gateway.

## Context

- oauth2-proxy should be used as a sidecar to authenticate users to access the application container on a Kubernetes pod,
- Keycloak provider is used for authentication,
- Istio is installed as ingress gateway. 

-> To ease debugging I created the local docker compose environment. Moving this to a proper Helm chart in the described context should not be a lot of effort:

![image](https://user-images.githubusercontent.com/14123913/139861824-54af3dc0-5573-4572-ae6c-61f8de9376b4.png)

## Your Environment

- Docker Compose environment running two containers, 
    - oauth2-proxy is running on localhost:4180
    - containous/whoami is running on localhost:4440 and returns a couply of dummy endpoints such as `/` and `/maintenance`
- Keycloak 15.x running on AKS and already used across multiple apps - a separate realm and client is used.
- Version used: 7.2.0
