### ISSUE TITLE
User headers not sent to upstream with ADFS and Traefik

### ISSUE THREAD

**Issue by cstisa** [oauth2-proxy/oauth2-proxy#1441]
## Expected Behavior

After successful authentication on the IdP and then redirected back to the Ingress resource, the user headers (X-Forwarded-User, X-Forwarded-Groups, X-Forwarded-Email and X-Forwarded-Preferred-Username) should be set by OAuth2 Proxy and sent to the upstream servers.

## Current Behavior

Access to upstream servers is allowed by OAuth2 Proxy (we are successfully redirected), but no user header is present in the request header. A call to `/oauth2/userinfo` successfully returns `email` and `user` values.

## Context

We are trying to set up OAuth2 Proxy on Kubernetes with Traefik as Ingress Controller and ADFS as Identity Provider.

OAuth2 Proxy config :
```
email_domains = [ "*" ]
oidc_issuer_url = "https://adfs.example.com/adfs"
provider = "adfs"
reverse_proxy = true
whitelist_domains = [ "upstream.example.com" ]
pass_basic_auth = true
pass_user_headers = true
silence_ping_logging = true
```

Traefik config :
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors
spec:
  errors:
    query: /oauth2/sign_in
    service:
      name: <upstream_service>
      port: http
    status:
    - 401-403
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth
spec:
  forwardAuth:
    address: http://<upstream_service>/oauth2/auth
    trustForwardHeader: true
```

Annotation on upstream Ingress : `traefik.ingress.kubernetes.io/router.middlewares: oauth-errors@kubernetescrd,oauth-auth@kubernetescrd`

OAuth2 Proxy Ingress :
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: upstream-oauth2-proxy
spec:
  rules:
  - host: upstream.example.com
    http:
      paths:
      - backend:
          service:
            name: upstream-oauth2-proxy
            port:
              name: http
        path: /oauth2/
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - upstream.example.com
    secretName: upstream.example.com-tls
```

We also tried the [second example](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#forwardauth-with-static-upstreams-configuration) for Traefik in your documentation but the result is the same.

## Your Environment

- OAuth2 Proxy version : 7.2.0
- Traefik version : 2.5.3
- Kubernetes version : 1.21
- ADFS role installed on Windows Server 2019

**Comment by cstisa** [comment]
Update : I tested with the GitLab provider and our instance of GitLab, and there's still no header received by the upstream service

**Comment by cstisa** [comment]
I finally solved my issue. I've added the following lines to OAuth2 Proxy config :
```
pass_access_token = true
set_xauthrequest = true
```
And changed the `oauth-auth` Middleware to :
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-auth
spec:
  forwardAuth:
    address: http://<upstream_service>/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
    - X-Auth-Request-User
    - X-Auth-Request-Email
    - X-Auth-Request-Groups
    - X-Auth-Request-Preferred-Username
```
P.S. : Even if I add X-Forwarded-Email and other X-Forwarded-* headers to `authResponseHeaders`, they are not set by OAuth2 Proxy. It seems that only X-Auth-Request-* headers are being set. It could be nice to add this to the documentation because it is not clear (including the difference between the options `--set-xauthrequest` and `--pass-user-headers`).
