### ISSUE TITLE
Invalid Scopes with keycloak provider

### ISSUE THREAD

**Issue by cclloyd** [oauth2-proxy/oauth2-proxy#1448]
## Expected Behavior

It should redirect to login page then back to specified url after authenticating.

## Current Behavior

I get an error (firefox) "The page isn't redirecting properly", and it suggests I disable cookies.

Logs from the oauth sidecar container

    [2021/11/16 02:53:54] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - 11a1cec8ad469a10f530cba529d97cf4 - - [2021/11/16 02:53:54] k8.example.com GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 397 0.001
    [2021/11/16 02:53:54] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - ae1a12c3f8d436fbc2d17deeedee1de5 - - [2021/11/16 02:53:54] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=TlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 572 0.001
    [2021/11/16 02:53:54] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - 16cc6281c9cb4c5d593b0e9375a8a303 - - [2021/11/16 02:53:54] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=cwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%253A%252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 775 0.001
    [2021/11/16 02:53:55] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - 917f93466e10d000bcc17576c3463557 - - [2021/11/16 02:53:55] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=ZadZUSvTw10pEQ3gAmRTMtKNgZTK_CdhzOlaumda6IQ%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3DcwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%253A%252Foauth%252Fcallback?error%253Dinvalid_scope%2526error_description%253DInvalid%252Bscopes%25253A%252B%252522email%252Bgroups%252522%2526state%253DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%25253A%25252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 1006 0.001
    [2021/11/16 02:53:55] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - a73a05a53150ce6f8ee12288113f5799 - - [2021/11/16 02:53:55] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=ncFcfUqh9pFRpAKN8HwNQYDjB8lsC8urBFay9sF64LM%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3DZadZUSvTw10pEQ3gAmRTMtKNgZTK_CdhzOlaumda6IQ%253A%252Foauth%252Fcallback?error%253Dinvalid_scope%2526error_description%253DInvalid%252Bscopes%25253A%252B%252522email%252Bgroups%252522%2526state%253DcwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%25253A%25252Foauth%25252Fcallback?error%25253Dinvalid_scope%252526error_description%25253DInvalid%25252Bscopes%2525253A%25252B%25252522email%25252Bgroups%25252522%252526state%25253DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%2525253A%2525252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 1265 0.001
    [2021/11/16 02:53:55] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - 3af4429401948f7767ae5f9d6035b96e - - [2021/11/16 02:53:55] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=HObZdaUsNDy8s3qXaWKx2e0Odtd7j9mUy1Y5C7Uz_8E%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3DncFcfUqh9pFRpAKN8HwNQYDjB8lsC8urBFay9sF64LM%253A%252Foauth%252Fcallback?error%253Dinvalid_scope%2526error_description%253DInvalid%252Bscopes%25253A%252B%252522email%252Bgroups%252522%2526state%253DZadZUSvTw10pEQ3gAmRTMtKNgZTK_CdhzOlaumda6IQ%25253A%25252Foauth%25252Fcallback?error%25253Dinvalid_scope%252526error_description%25253DInvalid%25252Bscopes%2525253A%25252B%25252522email%25252Bgroups%25252522%252526state%25253DcwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%2525253A%2525252Foauth%2525252Fcallback?error%2525253Dinvalid_scope%25252526error_description%2525253DInvalid%2525252Bscopes%252525253A%2525252B%2525252522email%2525252Bgroups%2525252522%25252526state%2525253DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%252525253A%252525252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 1552 0.001
    [2021/11/16 02:53:55] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - 81ffece29426198a56ebe00890ffd27b - - [2021/11/16 02:53:55] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=w5RlVXc0525T4eOi1sOdWTgScyPQwtGDi8MMpxiy1fo%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3DHObZdaUsNDy8s3qXaWKx2e0Odtd7j9mUy1Y5C7Uz_8E%253A%252Foauth%252Fcallback?error%253Dinvalid_scope%2526error_description%253DInvalid%252Bscopes%25253A%252B%252522email%252Bgroups%252522%2526state%253DncFcfUqh9pFRpAKN8HwNQYDjB8lsC8urBFay9sF64LM%25253A%25252Foauth%25252Fcallback?error%25253Dinvalid_scope%252526error_description%25253DInvalid%25252Bscopes%2525253A%25252B%25252522email%25252Bgroups%25252522%252526state%25253DZadZUSvTw10pEQ3gAmRTMtKNgZTK_CdhzOlaumda6IQ%2525253A%2525252Foauth%2525252Fcallback?error%2525253Dinvalid_scope%25252526error_description%2525253DInvalid%2525252Bscopes%252525253A%2525252B%2525252522email%2525252Bgroups%2525252522%25252526state%2525253DcwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%252525253A%252525252Foauth%252525252Fcallback?error%252525253Dinvalid_scope%2525252526error_description%252525253DInvalid%252525252Bscopes%25252525253A%252525252B%252525252522email%252525252Bgroups%252525252522%2525252526state%252525253DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%25252525253A%25252525252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 1867 0.002
    [2021/11/16 02:53:55] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - 5f0cf43dbe391d0868cfa67aafb56cea - - [2021/11/16 02:53:55] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=KlvtOXkBYOoysgcL5isJUDMgy42fNnNSR4MRBdq9ias%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3Dw5RlVXc0525T4eOi1sOdWTgScyPQwtGDi8MMpxiy1fo%253A%252Foauth%252Fcallback?error%253Dinvalid_scope%2526error_description%253DInvalid%252Bscopes%25253A%252B%252522email%252Bgroups%252522%2526state%253DHObZdaUsNDy8s3qXaWKx2e0Odtd7j9mUy1Y5C7Uz_8E%25253A%25252Foauth%25252Fcallback?error%25253Dinvalid_scope%252526error_description%25253DInvalid%25252Bscopes%2525253A%25252B%25252522email%25252Bgroups%25252522%252526state%25253DncFcfUqh9pFRpAKN8HwNQYDjB8lsC8urBFay9sF64LM%2525253A%2525252Foauth%2525252Fcallback?error%2525253Dinvalid_scope%25252526error_description%2525253DInvalid%2525252Bscopes%252525253A%2525252B%2525252522email%2525252Bgroups%2525252522%25252526state%2525253DZadZUSvTw10pEQ3gAmRTMtKNgZTK_CdhzOlaumda6IQ%252525253A%252525252Foauth%252525252Fcallback?error%252525253Dinvalid_scope%2525252526error_description%252525253DInvalid%252525252Bscopes%25252525253A%252525252B%252525252522email%252525252Bgroups%252525252522%2525252526state%252525253DcwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%25252525253A%25252525252Foauth%25252525252Fcallback?error%25252525253Dinvalid_scope%252525252526error_description%25252525253DInvalid%25252525252Bscopes%2525252525253A%25252525252B%25252525252522email%25252525252Bgroups%25252525252522%252525252526state%25252525253DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%2525252525253A%2525252525252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 2210 0.002
    [2021/11/16 02:53:55] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - 8092bd22a05bc8befedd1567e30b2901 - - [2021/11/16 02:53:55] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=S0UFH0TSQzAS8FMjBQGyKD9h6ZY7BvEIBTv8qHerpXI%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3DKlvtOXkBYOoysgcL5isJUDMgy42fNnNSR4MRBdq9ias%253A%252Foauth%252Fcallback?error%253Dinvalid_scope%2526error_description%253DInvalid%252Bscopes%25253A%252B%252522email%252Bgroups%252522%2526state%253Dw5RlVXc0525T4eOi1sOdWTgScyPQwtGDi8MMpxiy1fo%25253A%25252Foauth%25252Fcallback?error%25253Dinvalid_scope%252526error_description%25253DInvalid%25252Bscopes%2525253A%25252B%25252522email%25252Bgroups%25252522%252526state%25253DHObZdaUsNDy8s3qXaWKx2e0Odtd7j9mUy1Y5C7Uz_8E%2525253A%2525252Foauth%2525252Fcallback?error%2525253Dinvalid_scope%25252526error_description%2525253DInvalid%2525252Bscopes%252525253A%2525252B%2525252522email%2525252Bgroups%2525252522%25252526state%2525253DncFcfUqh9pFRpAKN8HwNQYDjB8lsC8urBFay9sF64LM%252525253A%252525252Foauth%252525252Fcallback?error%252525253Dinvalid_scope%2525252526error_description%252525253DInvalid%252525252Bscopes%25252525253A%252525252B%252525252522email%252525252Bgroups%252525252522%2525252526state%252525253DZadZUSvTw10pEQ3gAmRTMtKNgZTK_CdhzOlaumda6IQ%25252525253A%25252525252Foauth%25252525252Fcallback?error%25252525253Dinvalid_scope%252525252526error_description%25252525253DInvalid%25252525252Bscopes%2525252525253A%25252525252B%25252525252522email%25252525252Bgroups%25252525252522%252525252526state%25252525253DcwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%2525252525253A%2525252525252Foauth%2525252525252Fcallback?error%2525252525253Dinvalid_scope%25252525252526error_description%2525252525253DInvalid%2525252525252Bscopes%252525252525253A%2525252525252B%2525252525252522email%2525252525252Bgroups%2525252525252522%25252525252526state%2525252525253DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%252525252525253A%252525252525252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 2581 0.002
    [2021/11/16 02:53:55] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - f83b01b314579b615985651034608d42 - - [2021/11/16 02:53:55] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=apMU5q0aaBfdHS5QZzGS1AHJphhH2hpkTv0l6sts1_o%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3DS0UFH0TSQzAS8FMjBQGyKD9h6ZY7BvEIBTv8qHerpXI%253A%252Foauth%252Fcallback?error%253Dinvalid_scope%2526error_description%253DInvalid%252Bscopes%25253A%252B%252522email%252Bgroups%252522%2526state%253DKlvtOXkBYOoysgcL5isJUDMgy42fNnNSR4MRBdq9ias%25253A%25252Foauth%25252Fcallback?error%25253Dinvalid_scope%252526error_description%25253DInvalid%25252Bscopes%2525253A%25252B%25252522email%25252Bgroups%25252522%252526state%25253Dw5RlVXc0525T4eOi1sOdWTgScyPQwtGDi8MMpxiy1fo%2525253A%2525252Foauth%2525252Fcallback?error%2525253Dinvalid_scope%25252526error_description%2525253DInvalid%2525252Bscopes%252525253A%2525252B%2525252522email%2525252Bgroups%2525252522%25252526state%2525253DHObZdaUsNDy8s3qXaWKx2e0Odtd7j9mUy1Y5C7Uz_8E%252525253A%252525252Foauth%252525252Fcallback?error%252525253Dinvalid_scope%2525252526error_description%252525253DInvalid%252525252Bscopes%25252525253A%252525252B%252525252522email%252525252Bgroups%252525252522%2525252526state%252525253DncFcfUqh9pFRpAKN8HwNQYDjB8lsC8urBFay9sF64LM%25252525253A%25252525252Foauth%25252525252Fcallback?error%25252525253Dinvalid_scope%252525252526error_description%25252525253DInvalid%25252525252Bscopes%2525252525253A%25252525252B%25252525252522email%25252525252Bgroups%25252525252522%252525252526state%25252525253DZadZUSvTw10pEQ3gAmRTMtKNgZTK_CdhzOlaumda6IQ%2525252525253A%2525252525252Foauth%2525252525252Fcallback?error%2525252525253Dinvalid_scope%25252525252526error_description%2525252525253DInvalid%2525252525252Bscopes%252525252525253A%2525252525252B%2525252525252522email%2525252525252Bgroups%2525252525252522%25252525252526state%2525252525253DcwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%252525252525253A%252525252525252Foauth%252525252525252Fcallback?error%252525252525253Dinvalid_scope%2525252525252526error_description%252525252525253DInvalid%252525252525252Bscopes%25252525252525253A%252525252525252B%252525252525252522email%252525252525252Bgroups%252525252525252522%2525252525252526state%252525252525253DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%25252525252525253A%25252525252525252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 2980 0.001
    [2021/11/16 02:53:55] [oauthproxy.go:862] No valid authentication in request. Initiating login.
    10.0.0.1 - 40f121ff1e51223cfc0d91f65ec6a6a8 - - [2021/11/16 02:53:55] k8.example.com GET - "/oauth/callback?error=invalid_scope&error_description=Invalid+scopes%3A+%22email+groups%22&state=IyMJFswhvyxVmK4jV82dlyckqzjIj1TLBc4Rslnc6vc%3A%2Foauth%2Fcallback?error%3Dinvalid_scope%26error_description%3DInvalid%2Bscopes%253A%2B%2522email%2Bgroups%2522%26state%3DapMU5q0aaBfdHS5QZzGS1AHJphhH2hpkTv0l6sts1_o%253A%252Foauth%252Fcallback?error%253Dinvalid_scope%2526error_description%253DInvalid%252Bscopes%25253A%252B%252522email%252Bgroups%252522%2526state%253DS0UFH0TSQzAS8FMjBQGyKD9h6ZY7BvEIBTv8qHerpXI%25253A%25252Foauth%25252Fcallback?error%25253Dinvalid_scope%252526error_description%25253DInvalid%25252Bscopes%2525253A%25252B%25252522email%25252Bgroups%25252522%252526state%25253DKlvtOXkBYOoysgcL5isJUDMgy42fNnNSR4MRBdq9ias%2525253A%2525252Foauth%2525252Fcallback?error%2525253Dinvalid_scope%25252526error_description%2525253DInvalid%2525252Bscopes%252525253A%2525252B%2525252522email%2525252Bgroups%2525252522%25252526state%2525253Dw5RlVXc0525T4eOi1sOdWTgScyPQwtGDi8MMpxiy1fo%252525253A%252525252Foauth%252525252Fcallback?error%252525253Dinvalid_scope%2525252526error_description%252525253DInvalid%252525252Bscopes%25252525253A%252525252B%252525252522email%252525252Bgroups%252525252522%2525252526state%252525253DHObZdaUsNDy8s3qXaWKx2e0Odtd7j9mUy1Y5C7Uz_8E%25252525253A%25252525252Foauth%25252525252Fcallback?error%25252525253Dinvalid_scope%252525252526error_description%25252525253DInvalid%25252525252Bscopes%2525252525253A%25252525252B%25252525252522email%25252525252Bgroups%25252525252522%252525252526state%25252525253DncFcfUqh9pFRpAKN8HwNQYDjB8lsC8urBFay9sF64LM%2525252525253A%2525252525252Foauth%2525252525252Fcallback?error%2525252525253Dinvalid_scope%25252525252526error_description%2525252525253DInvalid%2525252525252Bscopes%252525252525253A%2525252525252B%2525252525252522email%2525252525252Bgroups%2525252525252522%25252525252526state%2525252525253DZadZUSvTw10pEQ3gAmRTMtKNgZTK_CdhzOlaumda6IQ%252525252525253A%252525252525252Foauth%252525252525252Fcallback?error%252525252525253Dinvalid_scope%2525252525252526error_description%252525252525253DInvalid%252525252525252Bscopes%25252525252525253A%252525252525252B%252525252525252522email%252525252525252Bgroups%252525252525252522%2525252525252526state%252525252525253DcwSGFo9Iko9bXwB-YLG3hM4SGXPbeMDEOUZ_P1sBYT4%25252525252525253A%25252525252525252Foauth%25252525252525252Fcallback?error%25252525252525253Dinvalid_scope%252525252525252526error_description%25252525252525253DInvalid%25252525252525252Bscopes%2525252525252525253A%25252525252525252B%25252525252525252522email%25252525252525252Bgroups%25252525252525252522%252525252525252526state%25252525252525253DTlwRV_ERBTZTsNZu_TANFeHFuDnowgezwBKUIf6nITE%2525252525252525253A%2525252525252525252F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" 302 3407 0.001

## Steps to Reproduce (for bugs)

Manifests provided below:

**Deployment:**
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
    spec:
      containers:
        - name: oauth-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
          ports:
            - containerPort: 3000
              name: auth
              protocol: TCP
          args:
            - --http-address=:3000
            - --upstream="https://127.0.0.1:8443/"
            - --ssl-upstream-insecure-skip-verify=true

            - --allowed-group="kubernetes-admins"
            - --skip-auth-route="/health.*"
            - --skip-provider-button=true
            - --reverse-proxy=true
            - --email-domain="*"
            - --cookie-domain=".example.com"
            - --whitelist-domain="*"
            - --scope="email groups"

            - --pass-authorization-header=true
            - --pass-access-token=true

            - --provider=keycloak-oidc
            - --provider-display-name="My Keycloak"
            - --redirect-url=https://k8.example.com/oauth/callback
            - --oidc-issuer-url=https://keycloak.example.com/auth/realms/master

            - --client-id=oauthproxy
            - --client-secret=REDACTED
            - --cookie-secret=REDACTED
            - --cookie-secure=false
          env:
            - name: AUTH_SERVER_URL
              value: https://keycloak.example.com/auth/
          volumeMounts:
           - name: oauth-config
             mountPath: /etc/oauth2-proxy.cfg
             subPath: oauth2-proxy.cfg
           - name: templates
             mountPath: /templates
             subPath: html
             readOnly: true


        - name: kubernetes-dashboard
          image: kubernetesui/dashboard:v2.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              protocol: TCP
              name: http
          args:
            - --auto-generate-certificates
            - --namespace=kubernetes-dashboard
            - --token-ttl=86400
            - --enable-insecure-login
            # Uncomment the following line to manually specify Kubernetes API server Host
            # If not specified, Dashboard will attempt to auto discover the API server and connect
            # to it. Uncomment only if the default does not work.
            # - --apiserver-host=http://my-address:port
          volumeMounts:
            - name: kubernetes-dashboard-certs
              mountPath: /certs
              # Create on-disk volume to store exec logs
            - mountPath: /tmp
              name: tmp-volume
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 2001


      volumes:
        - name: kubernetes-dashboard-certs
          secret:
            secretName: kubernetes-dashboard-certs
        - name: tmp-volume
          emptyDir: {}
        - name: oauth-config
          configMap:
            name: oauth
        - name: templates
          nfs:
            server: singularity
            path: /srv/Web
      serviceAccountName: kubernetes-dashboard
      nodeSelector:
        "kubernetes.io/os": linux
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
```
**Ingress:**
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard-auth
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/16"
spec:
  rules:
    - host: k8.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  name: auth
```
**Service:**
```yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  ports:
    - port: 443
      targetPort: auth
      name: auth
    - port: 8443
      targetPort: http
      name: http
  selector:
    k8s-app: kubernetes-dashboard
  type: LoadBalancer
```

## Context

The goal here was to stick oauth2-proxy in front of kubernetes-dashboard.  In case kubernets-dashboard has a weird authentication messing with it, I also tried this with an app in my cluster that has no auth at all, which I normally secure with keycloak-gatekeeper.

Of note is that this worked before with keycloak-gatekeeper.  I'll provide that manifest too for reference.

```yaml
annotations:
  authproxy.stakater.com/enabled: "true"
  authproxy.stakater.com/gatekeeper-image: "keycloak/keycloak-gatekeeper:6.0.1"
  authproxy.stakater.com/listen: "0.0.0.0:3000"
  authproxy.stakater.com/upstream-url: "https://127.0.0.1:8443"
  authproxy.stakater.com/discovery-url: "https://keycloak.example.com/auth/realms/master"
  authproxy.stakater.com/redirection-url: "https://k8.example.com"
  authproxy.stakater.com/client-id: "kubernetes-dashboard"
  authproxy.stakater.com/client-secret: "REDACTED"
  authproxy.stakater.com/source-service-name: "kubernetes-dashboard"
  authproxy.stakater.com/target-port: "3000"
  authproxy.stakater.com/resources: "uri=/*|roles=Kubernetes User"
```

## Your Environment

- **Kubernetes:** Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
- **oauth2-proxy:** 7.2.0
- **Ingress controller:** helm chart: bitnami/nginx-ingress-controller-7.6.12
