### ISSUE TITLE
getting the access/id token from the cookie

### ISSUE THREAD

**Issue by nbraun-wolf** [oauth2-proxy/oauth2-proxy#1452]
Hi, I am trying out the proxy. We have used a client-side library before to authenticate against azure AD. The problem I have now is that I want to get the access token or ID token on the frontend to pass the API requests to a backend.

Is  there a way to get this token? It must be part of the cookie, but I am unsure how to extract it.

**Comment by r-kotagudem** [comment]
@nbraun-wolf 
Please check below
https://github.com/oauth2-proxy/oauth2-proxy/issues/1277

If your app can make a request to /oauth2/auth, that should also be able to return things like the tokens as separate headers, which you can then copy to the request to the backend application if you need to send the token specifically

**Comment by nbraun-wolf** [comment]
The proxy is returning 401 on /oauth2/auth and /oauth2/userinfo, for some reason. I have it deployed via helm chart. Am I missing something? 

```yaml
extraArgs:
  provider: azure
  oidc-issuer-url: https://sts.windows.net/<tenant-id>/
  whitelist-domain: .my.domain.com
  cookie-domain: .my.domain.com

config:
  clientID: <client-id>
  clientSecret: <client-secret>
  cookieSecret: <cookie-secret>

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://frontend.my.domain.com"
  path: /
  pathType: Prefix
  hosts:
    - &host oauth.my.domain.com
  tls:
    - hosts:
        - *host
      secretName: oauth2-proxy-tls
```
