### ISSUE TITLE
Support for per-route/method role/group authZ

### ISSUE THREAD

**Issue by justjanne** [oauth2-proxy/oauth2-proxy#1459]
The louketo-proxy/keycloak-proxy/keycloak-gatekeeper project used to allow specifying multiple resources, with multiple matchers, with multiple requirements that needed to be fulfilled to allow authorization.

To provide an example from the documentation:

```yaml
resources:
- uri: /admin/test
  # the methods on this URL that should be protected, if missing, we assuming all
  methods:
  - GET
  # a list of roles the user must have in order to access URLs under the above
  # If all you want is authentication ONLY, simply remove the roles array - the user must be authenticated but
  # no roles are required
  roles:
  - openvpn:vpn-user
  - openvpn:prod-vpn
  - test
- uri: /admin/*
  methods:
  - GET
  roles:
  - openvpn:vpn-user
  - openvpn:commons-prod-vpn
```

What would be the equivalent configuration for this project, to obtain the same functionality?

In our case, we’d like to require for some routes (e.g. all paths matching `/i/*` or `/self/` with method `GET`) the role/group `foo:bar:read`, for other routes (e.g. all paths matching `/i/*` with method `PUT`, `PATCH`, `POST`, `DELETE`) the role/group `foo:bar:write``, and for a third endpoint (e.g. all paths matching `/admin/*` and all methods) the role/group `foo:bar:admin`.

Additionally, we’d like to configure some endpoints to allow anonymous access, but pass through user/role information, if the token exists (e.g. and endpoint that allows anonymous access, but returns more metadata if the user is logged in). (e.g. the endpoint `/i/*`)

Is this functionality – which previously was available in keycloak-proxy – currently implemented in this project, if yes, how could we configure it, and if no, is it on the roadmap?
