### ISSUE TITLE
Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 

### ISSUE THREAD

**Issue by zvazquez** [oauth2-proxy/oauth2-proxy#1461]
## Expected Behavior
Use of Oauth2Proxy to initiate and finalize OpenID Authentication flow to access Web resources within Kubernetes using NGINX Ingress Controller.

## Current Behavior
Authentication flow fails during callback call with error:
```
[oauthproxy.go:723] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 
```

The following is observed in the browser:

![image](https://user-images.githubusercontent.com/54040436/144322800-bf70e524-ad66-472e-9bac-1c4a37747c8a.png)

As mentioned Oauth2 Proxy is giving us the error:

![image](https://user-images.githubusercontent.com/54040436/144322919-6f1c2f55-3102-4aa8-9ec0-0dc6524d293f.png)

## Steps to Reproduce (for bugs)

Using multiple versions of Oauth2Proxy, but the lates tested was 7.2.0, runing on Kubernetes 1.19.13 with the ingress nginx controller 1.1.0. I have the following deployment configuration for Oauth2 Proxy:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: admin2
  labels:
    app.kubernetes.io/name: cxm-dex-oauth
    cxm.iac: admin
    k8s-app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        cxm.iac: admin
        k8s-app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: 'quay.io/oauth2-proxy/oauth2-proxy:v7.2.0'
          args:
            - '--cookie-domain=".domain.com"'
            - '--whitelist-domain=".domain.com"'
            - '--provider=oidc'
            - '--provider-display-name=''oauth2-proxy'''
            - '--email-domain=*'
            - '--client-id=clientid'
            - '--client-secret=''secret'''
            - '--errors-to-info-log=true'
            - '--http-address=0.0.0.0:4180'
            - '--standard-logging=true'
            - '--auth-logging=true'
            - '--request-logging=true'
            - '--upstream=static://'
            - '--redirect-url=https://prometheus.domain.com/oauth2/callback'
            - '--oidc-issuer-url=https://idp.com'
            - '--cookie-secret=secret'
          ports:
            - containerPort: 4180
              protocol: TCP          
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry      
```

The ingress artifacts are defined as follow:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-oauth2
  namespace: admin2
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod     
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.domain.com"
      secretName: tls
  rules:
  - host: prometheus.domain.com
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauthproxy-service
            port:
              number: 4180
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: observability
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod  
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"    
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.domain.com"
      secretName: tls
  rules:
    - host: prometheus.domain.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: prometheus-k8s
              servicePort: 9090

```

We are using SAP IaS to provide the OpenID services, more information about it [here](https://help.sap.com/viewer/6d6d63354d1242d185ab4830fc04feb1/Cloud/en-US/c135fc48135f4960bea34ac38ebc49a4.html)

- Version used:

Oauth2Proxy 7.2.0
Kubernetes 1.19.13 
Nginx controller 1.1.0

Thanks,

Zareh

**Comment by gowrisankar22** [comment]
@zvazquez Thanks for reporting much earlier. Today we also ran into the same problem in our setup with nginx ingress `1.1.0`. This working with nginx-ingress < `1.1.0`

```
100.96.5.39:37776 - 47521fc5d1d35c0e76400d16b564224b - - [2021/12/10 04:18:22] xxxxx GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36" 401 13 0.000
10.250.0.8:47422 - 931f44f6-d542-4710-a944-f14c96c27202 - - [2021/12/10 04:18:22] 100.96.1.58:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.20" 200 2 0.000

100.96.1.56:59414 - 000b7b0d4e178864dae5f4dc3ef42d99 - - [2021/12/10 04:18:22] xxxxxx GET - "/oauth2/start?rd=https%3A%2F%2Falertmanager.svc.xxxx%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36" 302 426 0.000
[2021/12/10 04:18:23] [oauthproxy.go:723] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401

Response: <html><head><title>Exception Report</title></head><body><br>HTTP Status 401 – </br></body></html>
100.96.1.56:59414 - 3a75e83862366a280e464c8a29785754 - - [2021/12/10 04:18:23] xxx GET - "/oauth2/callback?
[2021/12/10 04:18:23] [oauthproxy.go:862] No valid authentication in request. Initiating login.

```

**Comment by JoelSpeed** [comment]
The 401 is coming from the identity provider, you will need to work out why your identity provider is returning a 401.

There's no information in the logs right now which can tell us what is going on. 

What is the actual identity provider you are using, is it some online hosted IDP or are you using something in house, can you check the access logs to see what the issue is?

**Comment by pbdco** [comment]
For anyone out there coming from google with the related issue:

```
Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Code not valid"}
```

If you are using Keycloak, try disabling the "Use Refresh Token" in your client configuration. This has solved the issue in my case.

**Comment by aug70** [comment]
Still running into the same issue with github. Successful auth still causes error.

```
[2022/08/23 13:06:36] [oauthproxy.go:768] Error redeeming code during OAuth2 callback: error performing request: Post "https://github.com/login/oauth/access_token": dial tcp: i/o timeout
10.244.4.173:40858 - [redacted] - - [2022/08/23 13:06:06] [redacted] GET - "/oauth2/callback?code=[redacted]&state=[redacted]is%3A%2F" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" 500 2837 30.001
10.244.4.173:40858 - [redacted] - - [2022/08/23 13:06:36] [redacted] GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" 401 13 0.000
```
From the browser console a code has been returned to OAuth2 with any error. 401 doesn't come from the identity provider.

**Comment by jarosenthal** [comment]
I am having this issue too, successful login but no token. I turned off `Use Refresh Tokens` .. this has been driving me crazy for days. Anyone have a solution yet?

**Comment by maradwan** [comment]
same issue

**Comment by fjrial** [comment]
I have a similar configuration (keycloak (bug using oidc provider), ingress),  but the error I'm getting is 
`Error redeeming code during OAuth2 callback: token exchange failed: Post "https://<publicdns>/realms/<my_realm>/protocol/openid-connect/token": EOF`

I mean, I can usually login correctly, but sometimes, I'm getting a 500 error in oauth2 proxy, and that error in the log

My problems is in fact similar or the same as this one https://github.com/oauth2-proxy/oauth2-proxy/issues/2167

**Comment by fjrial** [comment]
I've fixed my problem by setting these parameters in oauth
--cookie-csrf-per-request=true
--cookie-csrf-expire=5m

**Comment by hmshashank** [comment]
Hi I am seeing similar error :

Error redeeming code during OAuth2 callback: error performing request: Post "https://<ip>.ip.linodeusercontent.com/realms/OAuth2-demo/protocol/openid-connect/token": x509: certificate is valid for ingress.local, not <ip>.ip.linodeusercontent.com

**Comment by Sumon01829** [comment]
> ## Expected Behavior
> Use of Oauth2Proxy to initiate and finalize OpenID Authentication flow to access Web resources within Kubernetes using NGINX Ingress Controller.
> 
> ## Current Behavior
> Authentication flow fails during callback call with error:
> 
> ```
> [oauthproxy.go:723] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 
> ```
> 
> The following is observed in the browser:
> 
> ![image](https://user-images.githubusercontent.com/54040436/144322800-bf70e524-ad66-472e-9bac-1c4a37747c8a.png)
> 
> As mentioned Oauth2 Proxy is giving us the error:
> 
> ![image](https://user-images.githubusercontent.com/54040436/144322919-6f1c2f55-3102-4aa8-9ec0-0dc6524d293f.png)
> 
> ## Steps to Reproduce (for bugs)
> Using multiple versions of Oauth2Proxy, but the lates tested was 7.2.0, runing on Kubernetes 1.19.13 with the ingress nginx controller 1.1.0. I have the following deployment configuration for Oauth2 Proxy:
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: oauth2-proxy
>   namespace: admin2
>   labels:
>     app.kubernetes.io/name: cxm-dex-oauth
>     cxm.iac: admin
>     k8s-app: oauth2-proxy
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       k8s-app: oauth2-proxy
>   template:
>     metadata:
>       labels:
>         cxm.iac: admin
>         k8s-app: oauth2-proxy
>     spec:
>       containers:
>         - name: oauth2-proxy
>           image: 'quay.io/oauth2-proxy/oauth2-proxy:v7.2.0'
>           args:
>             - '--cookie-domain=".domain.com"'
>             - '--whitelist-domain=".domain.com"'
>             - '--provider=oidc'
>             - '--provider-display-name=''oauth2-proxy'''
>             - '--email-domain=*'
>             - '--client-id=clientid'
>             - '--client-secret=''secret'''
>             - '--errors-to-info-log=true'
>             - '--http-address=0.0.0.0:4180'
>             - '--standard-logging=true'
>             - '--auth-logging=true'
>             - '--request-logging=true'
>             - '--upstream=static://'
>             - '--redirect-url=https://prometheus.domain.com/oauth2/callback'
>             - '--oidc-issuer-url=https://idp.com'
>             - '--cookie-secret=secret'
>           ports:
>             - containerPort: 4180
>               protocol: TCP          
>           imagePullPolicy: IfNotPresent
>       restartPolicy: Always
>       imagePullSecrets:
>         - name: docker-registry      
> ```
> 
> The ingress artifacts are defined as follow:
> 
> ```
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: prometheus-oauth2
>   namespace: admin2
>   annotations:
>     cert-manager.io/cluster-issuer: letsencrypt-prod     
> spec:
>   ingressClassName: nginx
>   tls:
>     - hosts:
>         - "*.domain.com"
>       secretName: tls
>   rules:
>   - host: prometheus.domain.com
>     http:
>       paths:
>       - path: /oauth2
>         pathType: Prefix
>         backend:
>           service:
>             name: oauthproxy-service
>             port:
>               number: 4180
> ---
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: prometheus
>   namespace: observability
>   annotations:
>     cert-manager.io/cluster-issuer: letsencrypt-prod  
>     nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
>     nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"    
>     nginx.ingress.kubernetes.io/auth-response-headers: Authorization
>     nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
>     nginx.ingress.kubernetes.io/configuration-snippet: |
>       auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
>       access_by_lua_block {
>         if ngx.var.name_upstream_1 ~= "" then
>           ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
>         end
>       }
> spec:
>   ingressClassName: nginx
>   tls:
>     - hosts:
>         - "*.domain.com"
>       secretName: tls
>   rules:
>     - host: prometheus.domain.com
>       http:
>         paths:
>           - path: /
>             pathType: ImplementationSpecific
>             backend:
>               serviceName: prometheus-k8s
>               servicePort: 9090
> ```
> 
> We are using SAP IaS to provide the OpenID services, more information about it [here](https://help.sap.com/viewer/6d6d63354d1242d185ab4830fc04feb1/Cloud/en-US/c135fc48135f4960bea34ac38ebc49a4.html)
> 
> * Version used:
> 
> Oauth2Proxy 7.2.0 Kubernetes 1.19.13 Nginx controller 1.1.0
> 
> Thanks,
> 
> Zareh

**Comment by Sumon01829** [comment]
> ## Expected Behavior
> Use of Oauth2Proxy to initiate and finalize OpenID Authentication flow to access Web resources within Kubernetes using NGINX Ingress Controller.
> 
> ## Current Behavior
> Authentication flow fails during callback call with error:
> 
> ```
> [oauthproxy.go:723] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 
> ```
> 
> The following is observed in the browser:
> 
> ![image](https://user-images.githubusercontent.com/54040436/144322800-bf70e524-ad66-472e-9bac-1c4a37747c8a.png)
> 
> As mentioned Oauth2 Proxy is giving us the error:
> 
> ![image](https://user-images.githubusercontent.com/54040436/144322919-6f1c2f55-3102-4aa8-9ec0-0dc6524d293f.png)
> 
> ## Steps to Reproduce (for bugs)
> Using multiple versions of Oauth2Proxy, but the lates tested was 7.2.0, runing on Kubernetes 1.19.13 with the ingress nginx controller 1.1.0. I have the following deployment configuration for Oauth2 Proxy:
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: oauth2-proxy
>   namespace: admin2
>   labels:
>     app.kubernetes.io/name: cxm-dex-oauth
>     cxm.iac: admin
>     k8s-app: oauth2-proxy
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       k8s-app: oauth2-proxy
>   template:
>     metadata:
>       labels:
>         cxm.iac: admin
>         k8s-app: oauth2-proxy
>     spec:
>       containers:
>         - name: oauth2-proxy
>           image: 'quay.io/oauth2-proxy/oauth2-proxy:v7.2.0'
>           args:
>             - '--cookie-domain=".domain.com"'
>             - '--whitelist-domain=".domain.com"'
>             - '--provider=oidc'
>             - '--provider-display-name=''oauth2-proxy'''
>             - '--email-domain=*'
>             - '--client-id=clientid'
>             - '--client-secret=''secret'''
>             - '--errors-to-info-log=true'
>             - '--http-address=0.0.0.0:4180'
>             - '--standard-logging=true'
>             - '--auth-logging=true'
>             - '--request-logging=true'
>             - '--upstream=static://'
>             - '--redirect-url=https://prometheus.domain.com/oauth2/callback'
>             - '--oidc-issuer-url=https://idp.com'
>             - '--cookie-secret=secret'
>           ports:
>             - containerPort: 4180
>               protocol: TCP          
>           imagePullPolicy: IfNotPresent
>       restartPolicy: Always
>       imagePullSecrets:
>         - name: docker-registry      
> ```
> 
> The ingress artifacts are defined as follow:
> 
> ```
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: prometheus-oauth2
>   namespace: admin2
>   annotations:
>     cert-manager.io/cluster-issuer: letsencrypt-prod     
> spec:
>   ingressClassName: nginx
>   tls:
>     - hosts:
>         - "*.domain.com"
>       secretName: tls
>   rules:
>   - host: prometheus.domain.com
>     http:
>       paths:
>       - path: /oauth2
>         pathType: Prefix
>         backend:
>           service:
>             name: oauthproxy-service
>             port:
>               number: 4180
> ---
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: prometheus
>   namespace: observability
>   annotations:
>     cert-manager.io/cluster-issuer: letsencrypt-prod  
>     nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
>     nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"    
>     nginx.ingress.kubernetes.io/auth-response-headers: Authorization
>     nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
>     nginx.ingress.kubernetes.io/configuration-snippet: |
>       auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
>       access_by_lua_block {
>         if ngx.var.name_upstream_1 ~= "" then
>           ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
>         end
>       }
> spec:
>   ingressClassName: nginx
>   tls:
>     - hosts:
>         - "*.domain.com"
>       secretName: tls
>   rules:
>     - host: prometheus.domain.com
>       http:
>         paths:
>           - path: /
>             pathType: ImplementationSpecific
>             backend:
>               serviceName: prometheus-k8s
>               servicePort: 9090
> ```
> 
> We are using SAP IaS to provide the OpenID services, more information about it [here](https://help.sap.com/viewer/6d6d63354d1242d185ab4830fc04feb1/Cloud/en-US/c135fc48135f4960bea34ac38ebc49a4.html)
> 
> * Version used:
> 
> Oauth2Proxy 7.2.0 Kubernetes 1.19.13 Nginx controller 1.1.0
> 
> Thanks,
> 
> Zareh

2167

**Comment by Sumon01829** [comment]
quay.io/oauth2-proxy/oauth2-proxy:v7.2.0

**Comment by Sumon01829** [comment]
![Uploading Screenshot_20241119-202245.jpg…]()

**Comment by Sumon01829** [comment]
Anar dipojit simosha

**Comment by nicolay-r** [comment]
I was running into exact the same problem as one below but in a context of `OAUTH2` + locally hosted `Keycloak` service via docker container.
```
Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 401 
```
Contributing to @pbdco  and [this solution](https://github.com/oauth2-proxy/oauth2-proxy/issues/1461#issuecomment-1204715804), **I would categorize this issue as misaligned of the security related data between services.**

In my case I changed settings for the `client_secret` that were made in KC configuration file (json). 
This client secret both utilized in *KC configuration file* and *OAUTH2 config*.
 
The *KC configuration file* file passed to the docker volume as follows at `docker-compose.yml`:
```
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: 'start-dev --import-realm'
    hostname: keycloak
    container_name: keycloak
    volumes:
     # Using custom realm settings for passing into KC
      - ./config/myrealm-keycloak-realm.json:/opt/keycloak/data/import/myrealm-keycloak-realm.json
```

So my further actions were to make sure that `client_secret` is up to date.
For that I went to the realm to `myrealm` -> `client` -> `Client Details`.

![Image](https://github.com/user-attachments/assets/6b081773-8fba-4e9f-ab50-b2c16c7fbb15)

And it was outdated.
It turns out, Keycloak fetched `client_secret` from the **volume** (outdated secret) rather config (new secret).

# Solution

**The solution**: wipe all the container data with dependent volumes:
```
docker rmi quay.io/keycloak/keycloak:24.0.5
docker volume prune -a
```

That made sure that all the secrets are synchonized in between OAUTH2 and KC.
