### ISSUE TITLE
Gitlab token refresh request does not include all required params

### ISSUE THREAD

**Issue by shawnhwei** [oauth2-proxy/oauth2-proxy#1473]
## Expected Behavior

Gitlab access token is able to be refreshed at the /oauth/token endpoint using the stored refresh_token.

## Current Behavior

The token is not refreshed successfully due to 400 response and session is invalidated.

## Possible Solution

I have captured the outgoing request to mygitlab.com/oauth/token and it seems there are required params that are not included.

At my Gitlab's nginx this is the request received:

```
POST /oauth/token
grant_type=refresh_token&refresh_token=TOKEN HERE
```

However the [Gitlab docs](https://docs.gitlab.com/ee/api/oauth2.html) mention also including client_id, client_secret, and redirect_uri during access_token refresh.

Indeed if I do the oauth flow through postman and exclude those params to /oauth/token (only grant_type=refresh and refresh_token), I get the same result as oauth2-proxy:
```json
{
    "error": "invalid_grant",
    "error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
}
```
But once I include them a successful response is returned.

Now if I try to use the refresh token logged from oauth2-proxy in postman it does not work even with the params, but I'm not sure if that refresh_token was already invalidated by Gitlab from the failed request. Unfortunately I don't know if I can log the whole oauth2-proxy session data to test before oauth2-proxy tries to refresh.

## Steps to Reproduce (for bugs)

1.  Setup Gitlab provider integration using OIDC.
2.  Open oauth2-proxy site.
3.  Wait around 2 mins.
4.  Refresh and observe reauthentication is required.

## Context

Need to reauthenticate every 2 minutes for Gitlab provider.

## Your Environment

My Gitlab is a self-hosted CE 14.5.2, and my upstream is the current Kubernetes dashboard v2.4.0. Oauth2-proxy is proxied by nginx-ingress without any options except TLS.

Using latest docker image quay.io/oauth2-proxy/oauth2-proxy:latest@sha256:21efe7d87bbfde86a2929bc26f5ea2929a3ad263276941bd867b6633c9ca427c.

Ingress manifest:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: REDACTED
    kubernetes.io/ingress.class: nginx
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  rules:
  - host: REDACTED
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - REDACTED
    secretName: REDACTED
```

Oauth2-proxy config:
```
      --session-store-type=redis
      --redis-connection-url=redis://redis:6379
      --http-address=0.0.0.0:4180
      --email-domain=*
      --provider=gitlab
      --redirect-url=https://REDACTED/oauth2/callback
      --client-id=REDACTED
      --client-secret=REDACTED
      --scope=openid email profile
      --cookie-secret=REDACTED
      --cookie-refresh=1m
      --oidc-issuer-url=REDACTED
      --upstream=https://kubernetes-dashboard
      --ssl-upstream-insecure-skip-verify
      --insecure-oidc-skip-nonce
      --pass-authorization-header
      --skip-provider-button
      --auth-logging
```

Gitlab application:
```
Callback URL | 
https://REDACTED/oauth2/callback   
Trusted | Yes
Confidential | Yes
Scopes | 
openid (Authenticate using OpenID Connect)   
profile (Allows read-only access to the user's personal information using OpenID Connect)   
email (Allows read-only access to the user's primary email address using OpenID Connect)
```
