### ISSUE TITLE
Configuring Istio enabled K8S cluster with Cognito user pool 

### ISSUE THREAD

**Issue by PrettySolution** [oauth2-proxy/oauth2-proxy#1491]
Hello,
I have set up oauth2-proxy to work with AWS Cognito user pool according to [docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider#openid-connect-provider). 
Everything seems to be working well. When I navigate at [prod.pretty-solution.com](https://prod.pretty-solution.com/api) it redirects me to a login page hosted at amazoncognito.com where I can sign in/up and then be redirected to my service that sits behind the proxy. 

My goal is to provide users with a sort of seamless experience. They should be redirected to login.pretty-solution.com where is served a stylish login page instead of ugly amazoncognito.com.

_How would I achieve that?_ 

I see there is an `--upstream` argument to serve static files. What if It served a SPA app that would handle a nice login page like here at [pretty-solution.com](https://pretty-solution.com/)? (this is an example I did years ago with AWS Amplify)

I am looking for a robust/best practice solution for an Istio enabled k8s cluster.

_Is oauth2-proxy the right choice for this? I want to escape a path with developing my own custom solution? I believe I am not the very first one. Need your help_

Appreciate any help on this.
Thanks!

Here is my config.
Please, let me know if it's not enough.
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
          args:
            - --provider=oidc
            - --cookie-secure=true
            - --cookie-samesite=lax
            - --cookie-refresh=1h
            - --cookie-expire=4h
            - --cookie-name=_oauth2_proxy_istio_ingressgateway
            - --set-authorization-header=true
            - --email-domain=*
            - --http-address=0.0.0.0:4180
            - --upstream=static://200
            - --skip-provider-button=true
            - --whitelist-domain=.pretty-solution.com  # $NGINX_DOMAIN
            - --oidc-issuer-url=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Bb7Xtr6Hp  # $OIDC_ISSUER_URL
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_COOKIE_SECRET
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          ports:
            - containerPort: 4180
              protocol: TCP
          readinessProbe:
            periodSeconds: 3
            httpGet:
              path: /ping
              port: 4180
```
Istio 1.12
kube 1.22
oauth2-proxy 7.2.0
