### ISSUE TITLE
OKTA Auth on EKS does not work

### ISSUE THREAD

**Issue by jin-ahn** [oauth2-proxy/oauth2-proxy#1496]
I have a cluster hosted on EKS and trying to use oauth-proxy as a way to authenticate my k8s dashboard
I have a DNS setup so that that eks.example.com points to the my ingress on EKS. ingress is configured so that eks.example.com has an auth url that will route to oauth-proxy and every other path routes to dashboard

## Expected Behavior
Going to eks.example.com will redirect me to example.okta.com so I can SSO login, which will then pass in a Auth token back to eks.example.com so I can access my k8s dashboard

## Current Behavior

Going to eks.example.com gives me a 403 access forbidden - and no logs are showing up in the proxy which leads me to believe its not getting routed to properly for someone reason.
 
If I change my ingress so that eks.example.com routes directly to oauth-proxy instead of dashboard, then I get redirect to okta, can login, and then get sents to dashboard. However even though I am in the dashboard console, its says 401 unauthorized as show in the screen shot. Logs show auth is successful and Im getting 200 on my request
![image](https://user-images.githubusercontent.com/66384196/147618078-85b63295-76af-4cf3-a19c-972ea9745fac.png)

## Possible Solution
I think a part of has my issue has to do with EKS and the eks apiserver not accepting or having access to the token, but I am not sure how to resolve that. 

## Your Environment

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/callback"
  name: external-auth-oauth2
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: eks.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 80
  tls:
  - hosts:
    - eks.example.com
    secretName: example-com-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: dashboard-proxy
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: eks.example.com
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: dashboard-proxy
            port:
              number: 4180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: dashboard-proxy
  name: dashboard-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dashboard-proxy
  template:
    metadata:
      labels:
        k8s-app: dashboard-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --provider-display-name="Okta"
        - --http-address=0.0.0.0:4180
        - --email-domain=*
        - --redirect-url=https://eks.example.com/oauth2/callback
        - --oidc-issuer-url=https://example.okta.com
        - --upstream=http://kubernetes-dashboard.kube-system.svc.cluster.local
        - --cookie-secure=true
        - --pass-user-headers=true
        - --pass-access-token=true
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --skip-provider-button=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: ZZZZZZZZZZZ
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: XXXXXXXXXX
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: ZZZZZZ
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: dashboard-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: dashboard-proxy
  name: dashboard-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: dashboard-proxy
```

- Version used:
EKS 1.21

**Comment by ianroberts** [comment]
That looks to me like oauth2-proxy has done its job authenticating you against okta before letting you see the dashboard, but then the 401 is the _apiserver_ telling the dashboard it hasn't supplied valid authentication to access k8s APIs.

You're using `auth-url` mode, so what happens is

- user hits `https://eks.example.com` without a valid session
- nginx hits oauth2-proxy `/oauth2/auth` URL passing through the request headers from the original request
- oauth2-proxy responds with a 401 indicating the request is not authenticated
- nginx responds to _this_ by redirecting to the `nginx.ingress.kubernetes.io/auth-signin` URL (which shouldn't be `/oauth2/callback`, it should be `/oauth2/start`)
- `/oauth2/start` triggers the auth code flow, redirects you to Okta, you log in, redirects back to the callback URL, etc.
- eventually you get redirected back to the original `https://eks.example.com`
- nginx again hits oauth2-proxy `/oauth2/auth`, but this time you have a valid cookie
- oauth2-proxy responds with a 202, and sets a variety of headers on its _response_ to nginx, most notably `Authorization` (due to your `--set-authorization-header=true` configuration)
- nginx finally proxies through to the dashboard

The main problem is at this final step: just because `/oauth2/auth` added the `Authorization` header to its _response_ doesn't automatically mean that nginx will copy that header over to the final upstream _request_ to the dashboard - you have to configure that in the ingress.

So at minimum you need to adjust the first ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    # this needs to point to the "start" URL, not the callback
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    # this is what tells nginx to copy the Authorization header from the auth
    # response to the upstream request
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
  name: external-auth-oauth2
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: eks.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 80
  tls:
  - hosts:
    - eks.example.com
    secretName: example-com-tls
```

You can also simplify the container args in the deployment section:

```
        - --provider=oidc
        - --provider-display-name="Okta"
        - --http-address=0.0.0.0:4180
        - --email-domain=*
        - --redirect-url=https://eks.example.com/oauth2/callback
        - --oidc-issuer-url=https://example.okta.com
        - --upstream=static://202
        - --cookie-secure=true
        - --set-authorization-header=true
        - --skip-provider-button=true
```

(I've taken out the "pass" options since they're irrelevant in auth-url mode, and set a static upstream).  This should get the Authorization header passed through to the dashboard, which will then in turn pass it on to the apiserver, so of course your apiserver then needs to be configured with all the appropriate `--oidc-*` options to make it trust the same Okta JWT tokens as oauth2-proxy (I don't know EKS so no idea how to do this or if it's even possible).
