### ISSUE TITLE
--skip-auth-route doesn't work

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [oauth2-proxy/oauth2-proxy#1498]
`--skip-auth-route` seems to be ignored or I don't know how to provide it correctly.

## Expected Behavior

When providing a regex like `--skip-auth-route=^\/api\/.*` endpoint `/api/asd` should be reachable without the auth cookie.

## Current Behavior

I'm still being asked to sign in. Tried with the deprecated `--skip-auth-regex` but is still the same.
Logs show:
```
[2021/12/30 19:23:13] [validator.go:28] using authenticated emails file /var/authorized-emails
[2021/12/30 19:23:13] [watcher.go:80] watching /var/authorized-emails for updates
[2021/12/30 19:23:13] [oauthproxy.go:148] OAuthProxy configured for Google Client ID: xx
[2021/12/30 19:23:13] [oauthproxy.go:154] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:672h0m0s domains:xx.yy path:/ samesite: refresh:after 1h0m0s
[2021/12/30 19:23:13] [oauthproxy.go:455] Skipping auth - Method:  | Path: ^\/api\/.*
```

## Steps to Reproduce (for bugs)

```
  authproxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    container_name: "authproxy"
    restart: always
    command:
      - --http-address=0.0.0.0:4180
      - --provider=google
      - --client-id=${OAUTH2_CLIENT_ID}
      - --client-secret=${OAUTH2_CLIENT_SECRET}
      - --cookie-secret=${OAUTH2_COOKIE_SECRET}
      - --authenticated-emails-file=/var/authorized-emails
      - --skip-auth-route=^\/api\/.*
      - --set-xauthrequest
      - --cookie-expire=672h
      - --cookie-refresh=1h
      - --cookie-secure=true
      - --cookie-httponly=true
      - --request-logging=false
      - --cookie-domain=${EMBY_HOST}
      - --redirect-url=https://${AUTH_HOST}
      - --set-authorization-header
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authproxy_https.rule=Host(`${AUTH_HOST}`) || PathPrefix(`/oauth2`)"
      - "traefik.http.routers.authproxy_https.entrypoints=websecure"
      - "traefik.http.routers.authproxy_https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authproxy_https.middlewares=traefik-real-ip"
      - "traefik.http.services.authproxy.loadbalancer.server.port=4180"
      - "traefik.http.middlewares.authproxy_verify.forwardAuth.address=https://${AUTH_HOST}/oauth2/auth"
      - "traefik.http.middlewares.authproxy_verify.forwardAuth.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Email"
      - "traefik.http.middlewares.authproxy_signin.errors.status=401"
      - "traefik.http.middlewares.authproxy_signin.errors.service=authproxy@docker"
      - "traefik.http.middlewares.authproxy_signin.errors.query=/oauth2/sign_in"
    volumes:
      - ./authorized-emails:/var/authorized-emails
```

## Context

I need access to the /api endpoint where authorization happens via API key yet for some reason I can't seem to get this thing to work, am I understanding this wrong? The only way it works is with this regex: `.*` but that is of limited usefulness.

## Your Environment

Docker-compose + Traefik

- Version used: 7.2.1

**Comment by JoelSpeed** [comment]
You may want to have a play around with the go playground, we use the standard regexp package, potentially it uses a different format for the path.

Alternatively, you could add some logging in https://github.com/oauth2-proxy/oauth2-proxy/blob/dede6fd531659007410c0c316b51a4dcc42d0f6d/oauthproxy.go#L514 to debug what exactly is being passed into the regex, this may help you to understand it

I put together a quick playground, wondering if it could be an escaping issue? https://go.dev/play/p/Q8wl0MxZ2GO

**Comment by mateuszkozakiewicz** [comment]
I solved my issue using traefik configuration, not sure if this parameter does what I need, perhaps it was a misunderstanding on my part, here is a working config that does what I need:
```
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
      - "traefik.http.routers.whoami.middlewares=authproxy_verify,authproxy_signin"
      - "traefik.http.routers.whoami-no-auth.rule=Host(`${WHOAMI_HOST}`)  && PathPrefix(`/api`)"
      - "traefik.http.routers.whoami-no-auth.entrypoints=websecure"
      - "traefik.http.routers.whoami-no-auth.tls.certresolver=letsencrypt"
```
I was never able to make it work using `--skip-auth-route`
