### ISSUE TITLE
id_token nor the profileURL set an email while using a alpha config

### ISSUE THREAD

**Issue by pfragoso** [oauth2-proxy/oauth2-proxy#1503]
Currently, I have a working instance of oauth2-proxy that I would like to change to the Alpha config to take advantage of the injectResponseHeaders option.

I don't rely on a cfg file, most of the stuff is configured through cmd arguments or env variables.

### normal config
 ```
   containers:
      - env:
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: REDACTED
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: REDACTED
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: REDACTED
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: REDACTED
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: REDACTED
        args:
        - --provider=oidc
        - --http-address=0.0.0.0:4180
        - --reverse-proxy=true
        - --whitelist-domain=.REDACTED
        - --upstream=static://202
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --set-authorization-header=true
        - --set-xauthrequest=true
        - --silence-ping-logging=true
        - --skip-auth-preflight
        - --show-debug-on-error=true
        - --cookie-domain=.REDACTED
        - --email-domain=*
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
```
### alpha config (not working)
```
     containers:
      - env:
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: REDACTED 
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: REDACTED
        args:
        - --reverse-proxy=true
        - --whitelist-domain=.REDACTED
        - --silence-ping-logging=true
        - --skip-auth-preflight
        - --show-debug-on-error=true
        - --cookie-domain=.REDACTED
        - --email-domain=*
        - --alpha-config=/etc/oauth2_proxy/oauth2_proxy_new.cfg
        image: quay.io/oauth2-proxy/oauth2-proxy:latest

/etc/oauth2_proxy/oauth2_proxy_new.cfg

    providers:
    - provider: oidc
      clientID: REDACTED
      clientSecret: REDACTED
      oidcConfig:
        issuerURL: REDACTED
      id: oidc
    server:
      BindAddress: "0.0.0.0:4180"
    upstreamConfig:
      upstreams:
      - id: root
        path: /
        static: true
        staticCode: 202
```

Getting the last id_token nor the profileURL set an email after doing the login into the provider.
Tried adding the profileURL, and adding manually the scopes without any result.

Am I missing something?

## Context

Having this solved would help us move to oauth2-proxy as we need injectResponseHeaders to inject the access_token as an Authorization header. 

## Your Environment

Currently running version v7.2.1 in Kubernetes.

**Comment by JoelSpeed** [comment]
What did you try to add the scope, something like `scope: "openid email profile"`?
Have you tried using the internal conversion of starting the proxy with your old config and adding `--convert-config-to-alpha`? This should dump out a full config that matches the old one

**Comment by pf-rvvup** [comment]
I've tried with the scopes and same issue.

Running the convert and using the new cfg seems to at least make it work but seems I'm missing some claims.

generate config
```
  oauth2_proxy_new.cfg: |
    injectRequestHeaders:
    - name: X-Forwarded-Groups
      values:
      - claim: groups
    - name: X-Forwarded-User
      values:
      - claim: user
    - name: X-Forwarded-Email
      values:
      - claim: email
    - name: X-Forwarded-Preferred-Username
      values:
      - claim: preferred_username
    - name: X-Forwarded-Access-Token
      values:
      - claim: access_token
    - name: Authorization
      values:
      - claim: id_token
        prefix: 'Bearer '
    injectResponseHeaders:
    - name: X-Auth-Request-User
      values:
      - claim: user
    - name: X-Auth-Request-Email
      values:
      - claim: email
    - name: X-Auth-Request-Preferred-Username
      values:
      - claim: preferred_username
    - name: X-Auth-Request-Groups
      values:
      - claim: groups
    - name: X-Auth-Request-Access-Token
      values:
      - claim: access_token
    - name: Authorization
      values:
      - claim: id_token
        prefix: 'Bearer '
    metricsServer:
      BindAddress: ""
      SecureBindAddress: ""
      TLS: null
    providers:
    - ADFSConfig: {}
      approvalPrompt: force
      clientID: REDACTED
      clientSecret: REDACTED
      id: oidc=REDACTED
      oidcConfig:
        emailClaim: email
        groupsClaim: groups
        insecureSkipNonce: true
        issuerURL: REDACTED
        userIDClaim: email
      provider: oidc
      scope: "openid email profile"
    server:
      BindAddress: 0.0.0.0:4180
      SecureBindAddress: ""
      TLS: null
    upstreamConfig:
      upstreams:
      - id: static://202
        path: /
        static: true
        staticCode: 202
```

I now get the proper headers for id_token and access_token (yay!) but seems I'm not getting the ones from email.

**Comment by JoelSpeed** [comment]
If possible, can you inspect the response from a call to `/OAuth2/start`, would be good to see the URL it's creating to see what it's sending to your OIDC provider as URL params (secret bits redacted)

**Comment by pfragoso** [comment]
Working config
```
 oauth2_proxy_new.cfg: |
    injectRequestHeaders:
    - name: X-Forwarded-Groups
      values:
      - claim: groups
    - name: X-Forwarded-User
      values:
      - claim: user
    - name: X-Forwarded-Email
      values:
      - claim: email
    - name: X-Forwarded-Preferred-Username
      values:
      - claim: preferred_username
    - name: X-Forwarded-Access-Token
      values:
      - claim: access_token
    - name: Authorization
      values:
      - claim: id_token
        prefix: 'Bearer '
    injectResponseHeaders:
    - name: X-Auth-Request-User
      values:
      - claim: user
    - name: X-Auth-Request-Email
      values:
      - claim: email
    - name: X-Auth-Request-Preferred-Username
      values:
      - claim: preferred_username
    - name: X-Auth-Request-Groups
      values:
      - claim: groups
    - name: X-Auth-Request-Access-Token
      values:
      - claim: access_token
    - name: Authorization
      values:
      - claim: id_token
        prefix: 'Bearer '
    metricsServer:
      BindAddress: ""
      SecureBindAddress: ""
      TLS: null
    providers:
    - ADFSConfig: {}
      approvalPrompt: force
      clientID: REDACTED
      clientSecret: REDACTED
      id: oidc=REDACTED
      oidcConfig:
        emailClaim: email
        groupsClaim: groups
        insecureSkipNonce: true
        issuerURL: REDACTED
        userIDClaim: email
      provider: oidc
      scope: "openid email profile"
    server:
      BindAddress: 0.0.0.0:4180
      SecureBindAddress: ""
      TLS: null
    upstreamConfig:
      upstreams:
      - id: static://202
        path: /
        static: true
        staticCode: 202
 ````
 
 initially, i was missing some headers due to traefik middleware.
 
 ```
 apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-gateway-proxy
spec:
  forwardAuth:
    address: http://auth-proxy-oauth2-proxy.default.svc.cluster.local
    authResponseHeaders:
    - X-Auth-Request-Access-Token
    - Authorization
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
    - X-Auth-Request-Groups
  ```
  
 This solves the issue. Thanks for the help @JoelSpeed 
 Closing this one.
