### ISSUE TITLE
X-Forwarded-URI not being used for redirects after authentication

### ISSUE THREAD

**Issue by devster31** [oauth2-proxy/oauth2-proxy#1538]
## Expected Behavior

Requesting a specific URI which requires authentication will be respected and included in the redirection.

## Current Behavior

It seems currently `oauth2-proxy` ignores the `X-Forwarded-URI` header when redirecting after authentication.

## Steps to Reproduce (for bugs)

Current setup with `Traefik` and `docker-compose.yml`:

```yaml
services:
  whoami:
    image: traefik/whoami
    labels:
      traefik.http.routers.whoami.rule:
        Host(`whoami.${DOMAIN}`)
      traefik.http.routers.whoami.tls: "true"
      traefik.http.routers.whoami.tls.certresolver: ovh
      traefik.http.middlewares.auth-httpbin.forwardAuth.address: <any request bin to record it>
      traefik.http.middlewares.anything-path.stripprefix.prefixes: /anything
      traefik.http.middlewares.anything-path.stripprefix.forceSlash: "true"
      traefik.http.routers.whoami.middlewares:
        auth-httpbin,anything-path
    networks:
      - backend
    restart: unless-stopped

  oauth2-proxy:
    command: >-
      --client-id=traefik
      --cookie-domain=.${DOMAIN}
      --client-secret=${CLIENT_SECRET}
      --cookie-secret=${COOKIE_SECRET}
      --email-domain=*
      --http-address=0.0.0.0:4180
      --metrics-address=0.0.0.0:80
      --oidc-issuer-url=https://${KEYCLOAK_URL}/auth/realms/<myrealm>
      --pass-access-token
      --provider=keycloak-oidc
      --redirect-url=https://oauth.${DOMAIN}/oauth2/callback
      --set-authorization-header
      --set-xauthrequest
      --whitelist-domain=.${DOMAIN}:*
      --reverse-proxy=true
      --redis-connection-url=redis://${REDISLABS_URL_PORT}
      --redis-password=${REDISLABS_PASSWORD}
      --session-store-type=redis
    environment: {}
    image: quay.io/oauth2-proxy/oauth2-proxy
    labels:
      traefik.http.routers.oauth2-proxy.rule:
        Host(`oauth.${DOMAIN}`) || PathPrefix(`/oauth2/`)
      traefik.http.routers.oauth2-proxy.service: oauth2-proxy@docker
      traefik.http.routers.oauth2-proxy.tls: "true"
      traefik.http.routers.oauth2-proxy.tls.certresolver: ovh
      traefik.http.middlewares.oauth2-verify.forwardAuth.address: https://oauth.${DOMAIN}/oauth2/auth
      traefik.http.middlewares.oauth2-verify.forwardAuth.trustForwardHeader: "true"
      traefik.http.middlewares.oauth2-signin.errors.status: 401-403
      traefik.http.middlewares.oauth2-signin.errors.service: oauth2-proxy@docker
      traefik.http.middlewares.oauth2-signin.errors.query: /oauth2/sign_in
      traefik.http.services.oauth2-proxy.loadbalancer.server.port: 4180
    networks:
      - backend
    restart: unless-stopped

  traefik:
    command:
      - --accesslog=true
      - --providers.docker=true
      - --certificatesresolvers.ovh=true
      - --certificatesresolvers.ovh.acme.email=${EMAIL}
      - --certificatesresolvers.ovh.acme.storage=/etc/traefik/acme.json
      - --certificatesresolvers.ovh.acme.dnschallenge=true
      - --certificatesresolvers.ovh.acme.dnschallenge.provider=ovh
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=ovh
      - --entryPoints.websecure.forwardedHeaders.insecure
      - --entryPoints.websecure.proxyProtocol.trustedIPs=127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - --log.level=INFO
    image: traefik:livarot
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

1. request `whoami.${DOMAIN}/anything`
2. `traefik` correctly makes an auth request
3. this is the `ForwardAuth` request sent:
```
X-Forwarded-For: 188.218.255.81
Host: ena7qm8s013g.x.pipedream.net
X-Amzn-Trace-Id: Root=1-61ffe458-07be078c4348d7fa0e875f91
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
accept-encoding: gzip, deflate, br
x-forwarded-host: whoami.${DOMAIN}
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
accept-language: it-IT,it;q=0.9
x-forwarded-server: 2de267270a2d
x-forwarded-method: GET
x-real-ip: 188.218.255.81
x-domain-trace: 15f0239f246750331b007071b762cbbe:1b007071b762cbbe:0000000000000000:1
x-forwarded-uri: /anything
```
4.  the authentication steps occur (this bit works as expected)
5. `oauth2-proxy` is supposed to redirect to the original URL, however the response is the following:
```
oauth2-proxy_1          | 188.218.255.81 - ab1ee9ee-6c66-4c6e-b5cc-8c01f5d89286 - - [2022/02/06 11:19:39] oauth.${DOMAIN} GET - "/oauth2/callback?state=<state>%3Ahttps%3A%2F%2Fwhoami.${DOMAIN}%2F&session_state=<session_state>&code=<code.code>
```
and the final `whoami.${DOMAIN}` captured doesn't show the `X-Forwarded-Prefix` which should be present.
```
Hostname: 7d763b50f28e
IP: 127.0.0.1
IP: 172.18.0.28
RemoteAddr: 172.18.0.25:60928
GET / HTTP/1.1
Host: whoami.${DOMAIN}
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: it-IT,it;q=0.9
X-Domain-Trace: 09fc0517c59b4b0c1e490ae3cb8fa696:09b878f10596d7ef:2a1b2b92928b0876:1
X-Forwarded-For: 188.218.255.81
X-Forwarded-Host: whoami.${DOMAIN}
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: 2de267270a2d
X-Real-Ip: 188.218.255.81
```

## Your Environment

- Version used: oauth2-proxy v7.2.1 (built with go1.17.5)
