### ISSUE TITLE
[question] How to configure oAuth2-proxy group information?

### ISSUE THREAD

**Issue by hiseth** [oauth2-proxy/oauth2-proxy#1553]
## Expected Behavior
How to configure oAuth2-proxy group information?
I am trying to use oAuth2-proxy to manage K8S dashboard. Now I have logged in but I cannot authorize by group. I see groups: [] is empty from dex log.

## Current Behavior
oauth2 > dex > ldap > k8s dashboard

dashboard-and-oauth2-ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$my_domain/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$my_domain/oauth2/start?rd=https://$host$request_uri$is_args$args"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
spec:
  ingressClassName: nginx
  rules:
  - host: $my_domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: oauth-proxy
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - $my_domain
    secretName: kubernetes-dashboard-external-tls
  rules:
  - host: $my_domain
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 8080
```

oauth2-proxy-deployment.yaml
```yaml
      containers:
      - args:
        - --cookie-secure=false
        - --ssl-insecure-skip-verify
        - --provider=oidc
        - --client-id=login
        - --client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
        - --oidc-issuer-url=https://<ip>:32000
        - --http-address=0.0.0.0:8080
        - --upstream=file:///dev/null
        - --email-domain=*
        - --set-authorization-header=true
        - --whitelist-domain=$my_domain
        - --cookie-domain=$my_domain
        - --set-xauthrequest=true
image: quay.io/oauth2-proxy/oauth2-proxy
```

kubectl logs dex-jshfahsdaksdj  output:
```yaml
time="2022-02-14T07:17:47Z" level=info msg="performing ldap search cn=users,cn=accounts,dc=xxxx,dc=org sub (mail=xxxxx@xxxxx.com)"
time="2022-02-14T07:17:47Z" level=info msg="username \"xxxxxxxx@xxxxxxx.com\" mapped to entry uid=xxxxxxx,cn=users,cn=accounts,dc=xxxxxxx,dc=org"
time="2022-02-14T07:17:47Z" level=info msg="login successful: connector \"ldap\", username=\"xxxxxxx\", preferred_username=\"xxxxxxx\", email=\"xxxxxxx@xxxxxxx.com\", groups=[]"
```
You can see that groups:[] is empty
