### ISSUE TITLE
Users are redirected to the oauth app hostname and not the URL from which they came to sign in

### ISSUE THREAD

**Issue by nivimorbgp** [oauth2-proxy/oauth2-proxy#1558]
## Expected Behavior

After sign in, users should be redirected back to the where they came from.

## Current Behavior

Users are able to sign in but are redirected to subdomain of oauth2 app.
oauthproxy.dev.internal.company.io

## Steps to Reproduce (for bugs)

Manifests used
```
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
spec:
  type: ClusterIP
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: web
  selector:
    app: "oauth-proxy"
---
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oauth-proxy"
  template:
    metadata:
      labels:
        app: oauth-proxy
    spec:
      containers:
      - name: oauth-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.2.0"
        env:
          # OIDC Config
          - name: "OAUTH2_PROXY_PROVIDER"
            value: "oidc"
          - name: "OAUTH2_PROXY_OIDC_ISSUER_URL"
            value: "https://company.okta.com"
          - name: "OAUTH2_PROXY_CLIENT_ID"
            value: "*********************"
          - name: "OAUTH2_PROXY_CLIENT_SECRET"
            value: "*************************"

          
          # Cookie Config
          - name: "OAUTH2_PROXY_COOKIE_SECRET"
            value: "***********************************"
          - name: "OAUTH2_PROXY_COOKIE_DOMAINS"
            value: ".company.io"

          # Proxy config
          - name: "OAUTH2_PROXY_EMAIL_DOMAINS"
            value: "company.io"
          - name: "OAUTH2_PROXY_WHITELIST_DOMAINS"
            value: ".company.io"
          - name: "OAUTH2_PROXY_HTTP_ADDRESS"
            value: "0.0.0.0:4180"
          - name: "OAUTH2_PROXY_SET_XAUTHREQUEST"
            value: "true"
          - name: "OAUTH2_PROXY_UPSTREAMS"
            value: "file:///dev/null"
---
# ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
spec:
  rules:
    - host: oauthproxy.dev.internal.company.io
      http:
        paths:
          - path: /oauth2
            backend:
              serviceName: oauth-proxy
              servicePort: 4180
---
```
1. Create an oidc app in OKTA 
2. Apply the manifests above using the details from the okta app
2.  Add the following annotations to the K8S ingress ```
annotations:
  nginx.ingress.kubernetes.io/auth-signin: http://oauthproxy.mydomain.com/oauth2/start
  nginx.ingress.kubernetes.io/auth-url: http://oauthproxy.mydomain.com/oauth2/auth
  nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
```
3.  Go to the service whose ingress has these annotations and try to sign in.

## Context
We are trying to put some services in EKS behind a sign in wall. 
The sign in succeeds but the user has to then go back to the URL from which they came from by themselves.

## Your Environment

EKS 1.20

- Version used:
7.2.0
