### ISSUE TITLE
Cannot get any upstream Authorization information on Rancher RKE rancher/nginx-ingress-controller

### ISSUE THREAD

**Issue by appcoders** [oauth2-proxy/oauth2-proxy#1573]
First everything works regarding oauth2 - but I cannot get any authorization cookies set for consumption on the target service.
oauth2-proxy deployed with helm chart 6.1.2

Config oauth2:
  ```
annotations: {}
  clientID: oauth2proxy
  clientSecret: redacted
  configFile: |-
    email_domains = [ "*" ]
    upstreams = [ "file:///dev/null" ]
    redirect_url = "redacted"
    oidc_issuer_url = "redacted"
    provider = "keycloak-oidc"
  cookieName: license_manager
  cookieSecret: redacted
  google: {}
customLabels: {}
deploymentAnnotations: {}
extraArgs:
  cookie-samesite: lax
  cookie-secure: 'false'
  pass-access-token: 'true'
  pass-authorization-header: 'true'
  pass-user-headers: 'true'
  scope: 'openid profile email'
  set-xauthrequest: 'true'
```

Ingress target service annotations:
```
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $license_manager_upstream_1 $upstream_cookie_license_manager_1;

      access_by_lua_block {
        if ngx.var.license_manager_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "license_manager_1=" .. ngx.var.license_manager_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }   
```
or
```
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_name_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
```

## Expected Behavior

Getting Authorization Cookie set for consumption by target service.

## Current Behavior

Both lead to the same result - no upstream cookies with Authorization infos:
RAW Response from /oauth2/callback 
```
HTTP/1.1 302 Found
Date: Tue, 22 Feb 2022 18:19:32 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 24
Connection: keep-alive
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Location: /
Set-Cookie: license_manager_csrf=; Path=/; Expires=Tue, 22 Feb 2022 17:19:32 GMT; HttpOnly; SameSite=Lax
Set-Cookie: license_manager=redacted-base64|1645553972|e-redacted-base64; Path=/; Expires=Tue, 01 Mar 2022 18:19:32 GMT; HttpOnly; SameSite=Lax
Strict-Transport-Security: max-age=15724800; includeSubDomains

<a href="/">Found</a>.
```

## Context

I also tried a different access_by_lua_block (logging an error) which is working fine - so this is not the root cause.

## Your Environment
Rancher 2.6

- Version used:
 oauth2-proxy helm chart 6.1.2
