### ISSUE TITLE
Issue with oauth2-proxy and okta interconnection

### ISSUE THREAD

**Issue by NikitaIvankov1992** [oauth2-proxy/oauth2-proxy#1582]
Hello team,
we have very specific problem trying to set up oauth2-proxy to proxy identity requests to our OKTA identity provider.
The problem is that OKTA uses something called `Thin tokens`, [according the docs](https://support.okta.com/help/s/article/Okta-Groups-or-Attribute-Missing-from-Id-Token?language=en_US)

> Id token when returned along with access token, is considered Thin Token. Thin id token only carries base claims and some scope dependent claims. Profile attributes (even if profile scope is passed) and groups are skipped (even if groups scope is passed in authorize request). Examples, of when id token and access token are returned together. 
> Implicit flow, where response_type=id_token+token
> Authorization code flow, where openid scope is passed in authorize request
> Resource owner password flow, where openid scope is passed in token request

We need our profile claims to make a decision whether to authorize request or not. Since identity token doesn't contain these claims we could use `profileUrl` and make some extra calls to get these claims. When the claims are gotten from the `user-info` endpoint, we can set only one of them via `-oidc-groups-claim` and `X-Auth-Request-Groups` header. 

To overcome this problem I followed the instruction, I tried to set up oauth2-proxy with `alpha-configuration`(to be capable to inject claims into headers and use its for authorization)

My alpha-config looks like the following
```
    UpstreamConfig:
      upstreams:
      - id: oauth2-proxy
        static: true
        path: /
    Server:
      BindAddress: 0.0.0.0:8080
    Providers:
    - provider: oidc
      id: oauth2-proxy
      clientID: ***
      clientSecret: ***
      profileURL: https://***.okta-emea.com/oauth2/v1/userinfo
      scope: "openid email groups profile"
      oidcConfig:
        groupsClaim: NameOfTheCustomClaim
        issuerURL: https://***.okta-emea.com
        insecureSkipNonce: true
```
general config contains only the following
```
    email_domains = [
      "***.com"
    ]
```
the idea is to set required headers after(when the basic config is working fine).

Currently, 
-I'm getting redirected to okta, 
```
https://***.okta-emea.com/oauth2/v1/authorize?approval_prompt=&client_id=***&redirect_uri=https%3A%2F%2Fnginx-echo-headers.*********%2Foauth2%2Fcallback&response_type=code&scope=openid+email+groups+profile&state=lt-cVediWHF_4PF-t4ATz845grw5gKi1Nfji3OpKC5g%3A%2F
```
-going through authentication procedure 
-getting callback
```
https://nginx-echo-headers.*********/oauth2/callback?code=*****&state=lt-cVediWHF_4PF-t4ATz845grw5gKi1Nfji3OpKC5g%3A%2F
```
and then getting the 403 error...
In the proxy logs I can see the following 
```
[2022/03/03 15:21:54] [oauthproxy.go:730] Error creating session during OAuth2 callback: neither the id_token nor the profileURL set an email
6.193.3.223:55046 - f88a5d8d-faf9-4619-b9ea-fb059c7caf18 - - [2022/03/03 15:21:54] nginx-echo-headers.********** GET - "/oauth2/callback?code=*****&state=lt-cVediWHF_4PF-t4ATz845grw5gKi1Nfji3OpKC5g%3A%2F" HTTP/1.1 "" 500 2810 0.141
```
and have no idea how to solve it...

This set up worked before when I used general config which means okta application set up correctly

Could you please let me know:
1)Is there any way how to push claims gotten from the user-info endpoint to the upstream?
2)Maybe you can see some obvious errors in my config which is preventing me from getting email in the ID token?

Thanks a million in advance and sorry for nube question I'm still very new in it

**Comment by NikitaIvankov1992** [comment]
Finally got it working :) 
I had to add 
```
      oidcConfig:
        emailClaim: email
```
so the final alpha config looks like the following

```
    injectRequestHeaders:
    - name: x-forwarded-Groups
      values:
      - claim: groups
    - name: x-forwarded-user
      values:
      - claim: user
    - name: x-forwarded-email
      values:
      - claim: email
    - name: x-forwarded-preferred-username
      values:
      - claim: preferred_username
    - name: x-forwarded-access-token
      values:
      - claim: access_token
    - name: authorization
      values:
      - claim: id_token
        prefix: 'Bearer '
    injectResponseHeaders:
    - name: x-auth-request-user
      values:
      - claim: user
    - name: x-auth-request-email
      values:
      - claim: email
    - name: x-auth-request-preferred-username
      values:
      - claim: x-auth-request-preferred-username
    - name: x-auth-request-groups
      values:
      - claim: groups
    - name: x-auth-request-access-token
      values:
      - claim: access_token
    - name: authorization
      values:
      - claim: id_token
        prefix: 'Bearer '
    UpstreamConfig:
      upstreams:
      - id: oauth2-proxy
        static: true
        path: /
    Server:
      BindAddress: 0.0.0.0:8080
    Providers:
    - provider: oidc
      id: oauth2-proxy
      clientID: ***
      clientSecret: ***
      profileURL: https://***.okta-emea.com/oauth2/v1/userinfo
      scope: "openid email groups profile"
      oidcConfig:
        emailClaim: email
        groupsClaim: NameOfTheCustomClaim
        issuerURL: https://***.okta-emea.com
```
but the problem is still there - I can't access any custom claims until I "map" it to groupClaim `groupsClaim: NameOfTheCustomClaim`. So my understanding was that after reaching up the `userinfo` endpoint and enriching the session we can use any custom claims and set it as `x-auth-***` headers...but looks like only small set of claims are supported including `user`, `group`, `email` and `preferred-username`. 

Please let me know whether my understanding is correct?
