### ISSUE TITLE
OIDC Connector Dex - LDAP - Returns empty group if allowed group is not specified / allow all groups / validates group when all groups is specified

### ISSUE THREAD

**Issue by CAR6807** [oauth2-proxy/oauth2-proxy#1588]
## Expected Behavior

When connecting to an OIDC provider (dex) - which is configured with AD/LDAP connector - I want to authenticate the users and return the JWT with all the groups associated with the user. I then pass this the upstream - Kubernetes Dashboard - which will use group membership to determine the right level of access via the API Server

## Current Behavior

If ALLOW_GROUPS / --allow-groups is not specified the groups claim is empty []  and the ldap search is different than what is configured in dex. 
```
msg="performing ldap search dc=domain,dc=subdomain,dc=com sub (&(objectClass=person)(sAMAccountName=USERID))"
level=info msg="login successful: connector \"ad\", username=\"USERID\", preferred_username=\"\", email=\"user@domain.com\", groups=[]"

```
If ALLOW_GROUPS / --allow-groups is specified then the proper ldap search is perform and the groups claim returns as expected
```
time="2022-03-14T12:42:28Z" level=info msg="performing ldap search dc=domain,dc=subdomain,dc=com sub (&(objectClass=group)(member=CN=USERID,OU=DIV40,OU=DPT25,OU=HO,OU=Internal,OU=Personal Accounts,DC=domain,DC=subdomain,DC=com))"
time="2022-03-14T12:42:28Z" level=info msg="login successful: connector \"ad\", username=\"USERID\", preferred_username=\"\", email=\"user@domain.com\", groups=[\"GROUP1\" \"GROUP2\"....... ] 
```
However then the OAuth Proxy will only allow access to the upstream if the user is a member of the group specified in ALLOW_GROUPS. Otherwise there is an unauthorized error in the OAuth proxy

Even though the upstream kubernetes dashboard / kube apiserver will validate access based on all group membership, the user will need to be part of whatever group is specified in the ALLOW_GROUP even if the upstream doesn't use it. 

## Possible Solution

Specify a dummy group or common group  in ALLOW_GROUPS that a user will be a part in order for the proper groups membership to be passed to the upstream. 

## Steps to Reproduce (for bugs)

```
          - --email-domain=*
          - --upstream=https://localhost:8443/
          - --provider=oidc
          - --skip-provider-button=true
          - --pass-authorization-header=true
          - --set-authorization-header=true
          - --redirect-url=https://url.domain.com/callback
          - --oidc-issuer-url=https://oidcprovider.domain.com
          - --set-xauthrequest=true
         env:
        - name: OAUTH2_PROXY_OIDC_EMAIL_CLAIM
          value: email
        - name: OAUTH2_PROXY_GROUPS_CLAIM
          value: groups
# Works with Dummy group , without groups claim is []
        - name: OAUTH2_PROXY_ALLOWED_GROUPS
          value: "DUMMY_GROUP"
```

## Context

Usecase is the upstream will handle authorization and access based on JWT being sent through as is, OAuth Proxy shouldn't validate access to the upstream based on ALLOW_GROUPS or it can but the not specify It should allow all groups to sent to the upstream

Is there a way to whitelist all groups so the groups claim is left as is when sent to the upstream

## Your Environment

quay.io/oauth2-proxy/oauth2-proxy:v7.2.0

dex v2.30.0
