### ISSUE TITLE
oauth2 proxy seems to be requesting /oauth2 after successfull authentication

### ISSUE THREAD

**Issue by schoeppi5** [oauth2-proxy/oauth2-proxy#1589]
## Expected Behavior

1. go to dashboard.domain.com/oauth2
2. redirected to keycloak
3. callback to dashboard.domain.com/oauth2/callback
4. redirect (if authorized) to upstream

## Current Behavior

The last step isn't really working:
It maps the upstream to "/" on startup

> mapping path "/" => upstream "https://kubernetes-dashboard/"

but when it redirects from the callback:

> dashboard.domain.com GET - "/oauth2/callback?state=..." HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" 302 30 0.024

it tries to request "/oauth2" on the upstream (which results in a 404):

> dashboard.domain.com GET / "/oauth2" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" 404 43 0.383

## Steps to Reproduce (for bugs)

1. Deploy latest oauth2-proxy helm chart with these values:
```yaml
extraArgs:
  oidc-issuer-url: https://keycloak.domain.com/auth/realms/master
  allowed-group: "kubernetes:admin"
  upstream: https://kubernetes-dashboard/
  provider: oidc
  email-domain: "*"
  skip-provider-button: "true"
  pass-authorization-header: "true"
  ssl-upstream-insecure-skip-verify: "true"
config:
  clientID: kubernetes
  clientSecret: "<client secret>"
  cookieSecret: "<cookie secret>"
```
2. Set up ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: external-auth-oauth2
  namespace: kubernetes-dashboard
spec:
  ingressClassName: nginx
  rules:
  - host: dashboard.domain.com
    http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - dashboard.domain.com
    secretName: <secret name>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: kubernetes-dashboard
spec:
  ingressClassName: nginx
  rules:
  - host: dashboard.domain.com
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              number: 80
        path: /oauth2
        pathType: Prefix
  tls:
  - hosts:
    - dashboard.domain.com
    secretName: <secret name>
```

## Your Environment

K8s: 1.20.7
oauth2-proxy: latest (I have tried it with K8s manifests and the helm chart -> same result)
I am currently using a host entry for dashboard.domain.com, but can verify, that this is not the issue. I have tried it on a prod cluster with working DNS and got the same result. I just think I am overlooking a config here or something.

- Version used:
