### ISSUE TITLE
rewriteTarget not working for websocket connections

### ISSUE THREAD

**Issue by rekup** [oauth2-proxy/oauth2-proxy#1601]
## Expected Behavior

`rewriteTarget` should work identical for websocket connections and none websocket connections

## Current Behavior

For websocket connections, oauth2proxy does not seem to rewrite the request path before sending it to the upstream server.

Example:

```
...
server:
  BindAddress: 0.0.0.0:8081
  SecureBindAddress: ""
  TLS: null
upstreamConfig:
  upstreams:
  - flushInterval: 1s
    id: prod
    passHostHeader: true
    path: ^/prod/(.*)$
    rewriteTarget: /$1
    proxyWebSockets: true
    uri: http://localhost:8080/
```

The configuration snippet above works fine for none websocket connections. Requests to `http://localhost:8081/prod/foo` will be proxied to `http://localhost:8080/foo`

Websocket connections however, will be proxied as follows: `http://localhost:8081/prod/foo` to `http://localhost:8080/prod/foo`.

## Steps to Reproduce

1.  create an oauth2proxy config with the following `upstreamConfig`
      ```
      upstreamConfig:
        upstreams:
        - flushInterval: 1s
          id: prod
          passHostHeader: true
          path: ^/prod/(.*)$
          rewriteTarget: /$1
          proxyWebSockets: true
          uri: http://localhost:8080/
      ```
2. create the required upstream services e.g. by using `jmalloc/echo-server`: `podman run -d -p 8080:8080 jmalloc/echo-server`
3. test none websocket request using curl:
      ```
      curl -H @/tmp/headers localhost:8081/prod/foo
      ```
      the echo server logs the following line
      ```
      e003ff297dd5 10.0.2.100:48740 | GET /foo
      ```
   This is working as expected
4. test websocket request using curl:
      ```
      curl --header "Connection: Upgrade" --header "Upgrade: websocket" -H @/tmp/headers localhost:8081/prod/foo
      ```
      the echo server logs the following line
      ```
      e003ff297dd5 10.0.2.100:48742 | GET /prod/foo
      ```
      I would have expected that the request is identical to the none websocket request **(`GET /foo` instead of `GET /prod/foo`)**

## Your Environment

`oauth2-proxy v7.2.1 (built with go1.16)`
