### ISSUE TITLE
Istio AuthorizationPolicy with oauth2-proxy block authentik/keycloak's Gateway too. How do I make oauth2-proxy bypass authentication for authentik/keycloak's domain.

### ISSUE THREAD

**Issue by iavinas** [oauth2-proxy/oauth2-proxy#1606]
## Expected Behavior
OpenID Configuration URL should be accessible publically without any authentication. 

## Current Behavior
model	Failed to GET from "https://authdomain.com/application/o/app/jwks/": status 403, RBAC: access denied. Retry in 1s
2022-03-30T06:10:45.742915Z	error	model	Failed to refresh JWT public key from

## Steps to Reproduce (for bugs)

1.  Use istio's Gateway and virtualservice for setting up a domain for auth service like authentik and use its OAuth2/OpenID Provider
## Context

oauth-proxy pod crashes because domain https://<domain//application/o/provider/.well-known/openid-configuration is not accessible without authentication.

I am applying these to my gke cluster.
```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
```

```
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
      # component: predictor
      # Istio: ingressgateway
  jwtRules:
  - issuer: $OIDC_ISSUER_URL
    jwksUri: $OIDC_JWKS_URI
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
      # component: predictor
      # Istio: ingressgateway
  action: CUSTOM
  provider:
    # Extension provider configured when we installed Istio
    name: oauth2-proxy
  rules:
  - {}
```

## Your Environment

- Version used:
- oauth2-proxy=V7.2.1
- ISTIO_VERSION=1.9.0
- authentik=2022.3.1
