### ISSUE TITLE
Oauth2-Proxy behind Nginx reverse proxy redirects to its own URL instead of "original" URL

### ISSUE THREAD

**Issue by e36Alex** [oauth2-proxy/oauth2-proxy#1607]
After successful login at keycloak as IDP, i get redirected to the domain of oauth2-proxy instead of the "original" URL.
When i call again test.home.domain.de i get "proxy_passed" to the right service.

## Expected Behavior

1. Call URL test.home.domain.de. 
2. Get redirected to oauth2-proxy (oauth2.home.domain.de) by nginx reverse proxy (auth_request)3. 
3. Get redirected to keycloak for login.
4. Get redirected to **test.home.domain.de** after successful login.

## Current Behavior

1. Call URL test.home.domain.de. 
2. Get redirected to oauth2-proxy (oauth2.home.domain.de) by nginx reverse proxy (auth_request)3. 
3. Get redirected to keycloak for login.
4. Get redirected to **oauth2.home.domain.de** after successful login.

## Your Environment

<img width="963" alt="Bildschirmfoto 2022-04-01 um 12 32 39" src="https://user-images.githubusercontent.com/26880334/161333364-3df72a61-419b-4f9d-99e0-cd42762c01cb.png">

nginx.conf of oauth2.home.domain.de:

```
server {
    # Server config
    listen 443 ssl http2;
    server_name oauth2.home.domain.de;

    # SSL Certs
    ssl_certificate /etc/letsencrypt/live/keycloak.home.domain.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/keycloak.home.domain.de/privkey.pem;

    set $oauth_proxy_hostname 10.0.0.6; # Adjust as needed
    set $oauth_proxy_port 1080;
    set $oauth_proxy_proto http;

    location /oauth2/ {
        #include /config/nginx/resolver.conf;

        proxy_pass $oauth_proxy_proto://$oauth_proxy_hostname:$oauth_proxy_port;
        proxy_set_header Host                    $host;
        proxy_set_header X-Real-IP               $remote_addr;
        proxy_set_header X-Scheme                $scheme;
        proxy_set_header X-Auth-Request-Redirect $request_uri;
    }
    location /oauth2/auth {
        #include /config/nginx/resolver.conf;

        proxy_pass $oauth_proxy_proto://$oauth_proxy_hostname:$oauth_proxy_port;
        proxy_set_header Host             $host;
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Scheme         $scheme;
        # nginx auth_request includes headers but not body
        proxy_set_header Content-Length   "";
        proxy_pass_request_body           off;
    }
}
```

nginx.conf of test.home.domain.de:

```
server {
  listen 443 ssl;
  server_name test.home.domain.de;
  #include ssl/ssl.conf;

  location /oauth2/ {
    proxy_pass       http://10.0.0.6:1080;
    proxy_set_header Host                    $host;
    proxy_set_header X-Real-IP               $remote_addr;
    proxy_set_header X-Scheme                $scheme;
    # proxy_set_header X-Auth-Request-Redirect $request_uri;
    # or, if you are handling multiple domains:
    proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;

  }
  location = /oauth2/auth {
    proxy_pass       http://10.0.0.6:1080;
    proxy_set_header Host             $host;
    proxy_set_header X-Real-IP        $remote_addr;
    proxy_set_header X-Scheme         $scheme;
    # nginx auth_request includes headers but not body
    proxy_set_header Content-Length   "";
    proxy_pass_request_body           off;
  }

  location / {
    proxy_pass http://192.168.10.14:2080;

    auth_request /oauth2/auth;
    error_page 401 = /oauth2/sign_in;
    #error_page 401 = /oauth2/start;

    # pass information via X-User and X-Email headers to backend,
    # requires running with --set-xauthrequest flag
    auth_request_set $user   $upstream_http_x_auth_request_user;
    auth_request_set $email  $upstream_http_x_auth_request_email;
    proxy_set_header X-User  $user;
    proxy_set_header X-Email $email;

    # if you enabled --pass-access-token, this will pass the token to the backend
    auth_request_set $token  $upstream_http_x_auth_request_access_token;
    proxy_set_header X-Access-Token $token;

    # if you enabled --cookie-refresh, this is needed for it to work with auth_request
    auth_request_set $auth_cookie $upstream_http_set_cookie;
    add_header Set-Cookie $auth_cookie;

    # When using the --set-authorization-header flag, some provider's cookies can exceed the 4kb
    # limit and so the OAuth2 Proxy splits these into multiple parts.
    # Nginx normally only copies the first `Set-Cookie` header from the auth_request to the response,
    # so if your cookies are larger than 4kb, you will need to extract additional cookies manually.
    auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;

    # Extract the Cookie attributes from the first Set-Cookie header and append them
    # to the second part ($upstream_cookie_* variables only contain the raw cookie content)
    if ($auth_cookie ~* "(; .*)") {
        set $auth_cookie_name_0 $auth_cookie;
        set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
    }

    # Send both Set-Cookie headers now if there was a second part
    if ($auth_cookie_name_upstream_1) {
        add_header Set-Cookie $auth_cookie_name_0;
        add_header Set-Cookie $auth_cookie_name_1;
    }

  }
}
```

docker-compose.yml of oauth2-proxy:

```
version: '3'

services:
  oauth2-proxy:
      container_name: oauth2-proxy
      image: quay.io/oauth2-proxy/oauth2-proxy:latest
      ports:
      - "1080:1080"
      - "1443:1443"
      volumes:
      - /srv/docker/oauth2-proxy/config/:/etc/oauth2-proxy/config
      environment:
        OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
        OAUTH2_PROXY_EMAIL_DOMAINS: "*"
        OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
        OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
        OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
        OAUTH2_PROXY_OIDC_ISSUER_URL: "https://keycloak.home.domain.de:8443/realms/private"
        OAUTH2_PROXY_COOKIE_DOMAINS: "home.domain.de"
        OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:1080" # This assumes you're running in docker and public listening is OK. Adjust as needed
        OAUTH2_PROXY_HTTPs_ADDRESS: "0.0.0.0:1443" # This assumes you're running in docker and public listening is OK. Adjust as needed
        OAUTH2_PROXY_REVERSE_PROXY: "true"
        OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"
        OAUTH2_PROXY_LOGGING_FILENAME: "/dev/stdout"
        OAUTH2_PROXY_STANDARD_LOGGING: "true"
        OAUTH2_PROXY_STANDARD_LOGGING_FORMAT: "[{{.Timestamp}}] [{{.File}}] {{.Message}}"
        OAUTH2_PROXY_REQUEST_LOGGING: "true"
        OAUTH2_PROXY_REQUEST_LOGGING_FORMAT: "{{.Client}} - {{.Username}} [{{.Timestamp}}] {{.Host}} {{.RequestMethod}} {{.Upstream}} {{.RequestURI}} {{.Protocol}} {{.UserAgent}} {{.StatusCode}} {{.ResponseSize}} {{.RequestDuration}}"
        OAUTH2_PROXY_AUTH_LOGGING: "true"
        OAUTH2_PROXY_AUTH_LOGGING_FORMAT: "{{.Client}} - {{.Username}} [{{.Timestamp}}] [{{.Status}}] {{.Message}}"
        OAUTH2_PROXY_PASS_HOST_HEADER: "false"
        OAUTH2_PROXY_SET_XAUTHREQUEST: "true" # Injects a bunch of user profile info. See link at top for more details.
        OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true" # Injects a signed token.
        OAUTH2_PROXY_WHITELIST_DOMAINS: "home.domain.de"
        OAUTH2_PROXY_COOKIE_EXPIRE: "168h"
        OAUTH2_PROXY_COOKIE_SECURE: "true"
        OAUTH2_PROXY_COOKIE_HTTPONLY: "false"
        OAUTH2_PROXY_SESSION_STORE_TYPE: "redis"
        OAUTH2_PROXY_REDIS_CONNECTION_URL: "redis://10.0.0.6:6379"
        OAUTH2_PROXY_REDIS_PASSWORD: "secretkey"
        OAUTH2_PROXY_REDIRECT_URL: https://oauth2.home.domain.de/oauth2/callback
        OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
        OAUTH2_PROXY_CONFIG: /etc/oauth2-proxy/config/oauth2-proxy.cfg
        
        OAUTH2_PROXY_UPSTREAM: "static://200"
        OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      restart: unless-stopped

  redis-cache:
      container_name: oauth2-cache
      image: redis:latest
      ports:
        - '6379:6379'
      command: redis-server --save 60 1 --loglevel warning --requirepass secretkey
      volumes: 
        - cache:/data
      restart: unless-stopped
      
volumes:
  cache:
    driver: local
```

- Version used: latest
