### ISSUE TITLE
404 when going to the auth URL directly after being authenticated

### ISSUE THREAD

**Issue by politician** [oauth2-proxy/oauth2-proxy#1608]
## Expected Behavior

Opening directly oAuth2 Proxy URL while being authenticated should return a page saying I am already authenticated

## Current Behavior

Let's say app.example.com is behind oAuth2 Proxy:
1. I open `app.example.com`
2. I am redirected to `auth.example.com`
3. I login to my provider
4. I am now authenticated and redirected back to `app.example.com` 🎉
5. If I open directly `auth.example.com` I get a **404 error** 😱

Is this the expected behavior or did I miss something in the config?

## Possible Solution

Create a page that says the user is authenticated

## Steps to Reproduce (for bugs)

My current config (in Kubernetes) if this has any impact

```toml
cookie_domains = [ ".example.com" ]
whitelist_domains = [ ".example.com" ]
email_domains = [ "*" ]
upstreams = [ "file:///dev/null" ]
set_xauthrequest = true
silence_ping_logging = true
```

## Your Environment

- Kubernetes
- oAuth2 Proxy version used: 7.2.1
