### ISSUE TITLE
Using --allowed-role behind nginx reverse proxy to restrict access per site?

### ISSUE THREAD

**Issue by e36Alex** [oauth2-proxy/oauth2-proxy#1614]
I am running oauth2-proxy behind a nginx reverse proxy and use keycloak (oidc) as IDP.
Several sites / subdomains can be reached through nginx reverse proxy (proxy_pass) and i would like to restrict the access per site depending on user groups in keycloak.

## Expected Behavior

Definition per site in nginx which user groups can access the site.

## Current Behavior

Dont know if it is possible and if it is, its not clear for me how to do it.

## Your Environment

Nginx reverse proxy (proxy_pass)
Oauth2-Proxy
Keycloak

- Version used:
latest stable

**Comment by e36Alex** [comment]
Thanks for your post - wasnt sure, if i just didnt see that options. But it seems like i am not the only one missing that feature.
I think running multiple oauth2-proxy containers wouldnt be the best practice.

**Comment by JoelSpeed** [comment]
You should be able to use https://github.com/oauth2-proxy/oauth2-proxy/pull/849 to achieve what you're looking for

**Comment by e36Alex** [comment]
Thanks for your comment. But i am still not sure how to solve it. Are there any config examples, how to use it?

**Comment by JoelSpeed** [comment]
I believe when you configure nginx, the error directive (or signin-url if using nginx-ingress) should have a query string added to the end, `/oauth2/start?allowed_groups=role:<role-name>`, something like this might work

**Comment by e36Alex** [comment]
Thank you, thats pretty cool. I could solve it by adding the following line:
`set $args $args&allowed_groups=/ldap/gitlab;`

Even great, that it works with groups instead of roles, also.

Thank you very much!

**Comment by yongzhang** [comment]
Anyone knows how to archive this in traefik? Seems I can't make it work like this:

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-auth
spec:
  forwardAuth:
    address: "https://auth-proxy.mydomain.com/oauth2/auth?allowed_groups=Everyone"
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Preferred-Username
      - X-Auth-Request-Groups
      - Authorization
```
