### ISSUE TITLE
Alpha config: OIDC profile does not pull the email from the profileURL

### ISSUE THREAD

**Issue by przemub** [oauth2-proxy/oauth2-proxy#1623]
## Expected Behavior

I converted my working config to the alpha one, so I can inject extra headers. The old one is specified as environment variables:
```bash
      - "OAUTH2_PROXY_CLIENT_ID=XXX"
      - "OAUTH2_PROXY_CLIENT_SECRET=XXX"
      - "OAUTH2_PROXY_REDIRECT_URL=http://localhost:8010/oauth2/callback"
      - "OAUTH2_PROXY_PROVIDER=oidc"
      - "OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=XXX"
      - "OAUTH2_PROXY_PASS_USER_GROUPS=true"
      - "OAUTH2_PROXY_OIDC_ISSUER_URL=https://XXX/idp/oidc"
      - "OAUTH2_PROXY_SKIP_OIDC_DISCOVERY=false"
      - "OAUTH2_PROXY_SCOPE=openid profile email address phone xxx"
      - "OAUTH2_PROXY_PROFILE_URL=https://XXX/idp/oidc/userinfo"
      - "OAUTH2_PROXY_OIDC_EMAIL_CLAIM=email"
      - "OAUTH2_PROXY_OIDC_GROUPS_CLAIM=roles"
```

The new one looks as follows:
```yaml
injectRequestHeaders:
- name: X-Forwarded-Groups
  values:
  - claim: roles
- name: X-Forwarded-User
  values:
  - claim: user
- name: X-Forwarded-Email
  values:
  - claim: email
- name: X-Forwarded-Given-Name
  values:
  - claim: given_name
- name: X-Forwarded-Family-Name
  values:
  - claim: family_name
providers:
- approvalPrompt: force
  clientID: XXX
  clientSecret: XXX
  id: XXX
  name: XXX
  oidcConfig:
    emailClaim: email
    groupsClaim: roles
    insecureSkipNonce: false
    issuerURL: https://XXX/idp/oidc
    userIDClaim: user
  profileURL: https://XXX/idp/oidc/userinfo
  provider: oidc
  scope: openid profile email address phone xxx
server:
  BindAddress: 0.0.0.0:80
upstreamConfig:
  upstreams:
  - flushInterval: 1s
    id: /
    passHostHeader: true
    path: /
    proxyWebSockets: true
    uri: http://wagtail:8000
```

The login should work and pass the expected headers.

## Current Behavior

I cannot login anymore due to the following error:
```
oauth_proxy_1      | [2022/04/19 11:07:18] [oauthproxy.go:730] Error creating session during OAuth2 callback: neither the id_token nor the profileURL set an email
```

It looks as if it weren't able to process the profileURL response properly. I intercepted the communication and a request is made to the profileURL endpoint. The email is properly set in the response, under the "email" claim.

## Possible Solution

No idea, unfortunately.

## Steps to Reproduce (for bugs)

1. Configure your OIDC provider to pass the email claim only in the userinfo endpoint.
2. Configure oauth2-proxy using the alpha config to pull the email from the profileURL.
3. Try logging in.

## Context

I tried to convert my working config to the alpha one. Without it working, I won't be able to upgrade when it stops being alpha.

## Your Environment

Official Docker image running under Docker for Mac.

- Version used: v7.2.1

Thanks for your work!
