### ISSUE TITLE
Okta Auth uses wrong user for k8s dashboard

### ISSUE THREAD

**Issue by jin-ahn** [oauth2-proxy/oauth2-proxy#1625]
I have a cluster hosted on EKS and trying to use oauth-proxy as a way to authenticate my k8s dashboard
I have a DNS setup so that that eks.example.com points to the my ingress on EKS. ingress is configured so that eks.example.com has an auth url that will route to oauth-proxy and every other path routes to dashboard

## Expected Behavior
Going to eks.example.com will redirect me to example.okta.com so I can SSO login, which will then pass in a Auth token back to eks.example.com so I can access my k8s dashboard

## Current Behavior

Going to eks.example.com redirects me to okta sso login. I login in successful and get redirected to eks.example.com. At this point the k8s dashboard loads properly, however I do not have access to view anything. I get the following error in the notifications
`cronjobs.batch is forbidden: User "https://***.okta.com#00u1qb618pyrozyIl5d7" cannot list resource "cronjobs" in API group "batch" in the namespace "default"`
![Screenshot_2022-04-21 16 39 41_oU4LGp](https://user-images.githubusercontent.com/66384196/164568607-067fd81e-6652-4d13-ae02-5bf4ba9b1f31.png)

## Possible Solution
I think the issue is because I am accessing the dashboard as "https://***oktas.com#11111".

I have a role on my cluster already that has full access to dashboard, **how do I make oauth-proxy2 utilize that role once I have authenticated OR how do I add my okta groups to k8s configmap?**

## Your Environment

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://dashboard-proxy.kube-system.svc.cluster.local:4180/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
  name: external-auth-oauth2
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: eks.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 80
  tls:
  - hosts:
    - eks.example.com
    secretName: example-com-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: dashboard-proxy
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: eks.example.com
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: dashboard-proxy
            port:
              number: 4180
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: dashboard-proxy
  name: dashboard-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dashboard-proxy
  template:
    metadata:
      labels:
        k8s-app: dashboard-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --provider-display-name="Okta"
        - --http-address=0.0.0.0:4180
        - --email-domain=*
        - --redirect-url=https://eks.****.com/oauth2/callback
        - --oidc-issuer-url=https://****.okta.com
        - --upstream=http://kubernetes-dashboard.kube-system.svc.cluster.local
        - --cookie-secure=true
        - --set-authorization-header=true
        - --skip-provider-button=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: ZZZZZZZZZZZ
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: XXXXXXXXXX
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: ZZZZZZ
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: dashboard-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: dashboard-proxy
  name: dashboard-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: dashboard-proxy
```

- Version used:
EKS 1.21
