### ISSUE TITLE
Not routing back to original URL (if not previously logged-in)

### ISSUE THREAD

**Issue by copolycube** [oauth2-proxy/oauth2-proxy#1639]
## Expected Behavior
I would expect the oauth2-proxy to re-route to the original url when no cookie is set

```mermaid
graph LR;
Z(clear cookies) --> A(original url) --> B{sign_in prompt} --> C(original url) ;
```

## Current Behavior

If I'm not already authenticated:
* access to `whoami.${DOMAIN}` -> sign_in prompt at `oauth.${DOMAIN}/oauth2/sign_in` -> `oauth.${DOMAIN}/`

```mermaid
graph LR;
 Z(clear cookies) --> A(original url) --> B{sign_in prompt} --> C(Oauth2 root path url) ;
```

Note that if the oauth sign-in process has already succeeded, then it behaves correctly (cf. next scheme), so you need to make sure to NOT be logged-in before testing / reproducing : 
```mermaid
graph LR;
A(original url) --> B{transparent sign_in} --> C(original url) ;
```

## Possible Solution

fix in my configuration ? (cf. below) 

## Steps to Reproduce (for bugs)

1.   create a gitlab.com account and the corresponding oauth application (cf. https://docs.gitlab.com/ce/integration/oauth_provider.html ) and make sure docker-compose and docker are installed
2.   copy locally the full `docker-compose.yml` (`traefik` configuration below at the end of the description + add the first extract with whoami service and `oauth` service at the end of the file) and fill in the appropriate values (you can also place them in a `.env` file at the same level than the `docker-compose.yml` file.
3.   `sudo docker-compose up `
4.   clear your cookies 
5. go to `whoami.${DOMAIN}` 

## Context

Installing `oauth2-proxy` as a forwardauth traefik middleware.

## Your Environment

- Version used: v7.2.1

Hello, 
I was able to make the oauth2 proxy work with gitlab.com SAAS version as of today with the following `docker-compose.yml` extract :

```
  oauth2:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    container_name: "oauth"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://oauth:4180/ping"]
      interval: 60s
      timeout: 10s
    labels:
      ai.ix.expose: 'true'
      traefik.enable: 'true'
      traefik.http.middlewares.oauth-verify.forwardAuth.address: http://oauth:4180/oauth2/auth
      traefik.http.middlewares.oauth-verify.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.oauth-verify.forwardAuth.authResponseHeaders: X-Auth-Request-User,X-Auth-Request-Email,Set-Cookie,X-Auth-User,X-Secret
      traefik.http.middlewares.oauth-signin.errors.service: oauth@docker
      traefik.http.middlewares.oauth-signin.errors.status: '401'
      traefik.http.middlewares.oauth-signin.errors.query: /oauth2/sign_in
      traefik.http.routers.oauth.entrypoints: websecure
      traefik.http.routers.oauth.rule: Host(`oauth.${DOMAIN?err}`) || PathPrefix(`/oauth2`)
      traefik.http.routers.oauth.tls.certResolver: myresolver
      traefik.http.routers.oauth.service: oauth@docker
      traefik.http.services.oauth.loadbalancer.server.port: '4180'
    environment:
            # https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#environment-variables
      OAUTH2_PROXY_PROVIDER: gitlab
      OAUTH2_PROXY_GITLAB_GROUP: ${OAUTH2_PROXY_GITLAB_GROUP}
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID?err}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET?err}
      OAUTH2_PROXY_COOKIE_DOMAINS: ${DOMAIN?err}
      OAUTH2_PROXY_COOKIE_REFRESH: '1h'
      OAUTH2_PROXY_COOKIE_SECURE: 'false'
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET?err}
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_FOOTER: '-'
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      OAUTH2_PROXY_PASS_BASIC_AUTH: 'false'
      OAUTH2_PROXY_PASS_USER_HEADERS: 'true'
      OAUTH2_PROXY_REVERSE_PROXY: 'true'
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: 'true'
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_WHITELIST_DOMAIN: '.${DOMAIN?err}'
      OAUTH2_PROXY_REDIRECT_URL: "https://oauth.${DOMAIN}/oauth2/callback"
    networks:
      - internal
      - docker-proxy-internal

```
this is currently the configuration of a POC service :
```
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    networks:
      - internal
      - docker-proxy-internal
    labels:
            traefik.enable: true
            traefik.docker.network: traefik-proxy
            traefik.http.routers.whoami-monitoring.rule: Host(`whoami.${DOMAIN?err}`)
            traefik.http.routers.whoami-monitoring.middlewares: oauth-signin,oauth-verify,default-https
            traefik.http.routers.whoami-monitoring.entrypoints: websecure
            traefik.http.services.whoami-monitoring.loadbalancer.server.port: 80

```

If needed, here is also my traefik configuration

```
version: '3.6'

networks:
  docker-proxy-internal:
  internal:
    external:
      name: traefik-proxy

volumes:
   traefik-letsencrypt:
   traefik-logs:

services:
  traefik:
    image: traefik:latest
    container_name: "traefik"
    command:
      - --log.level=DEBUG
      - --api.dashboard=true
      - --api.insecure=true
       # Do not expose all Docker services by default
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      #- "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - --providers.docker.endpoint=tcp://proxy:2375
      - --providers.docker.network=traefik-proxy

        # DNS Challenge (domain.tld and *.domain.tld DNS zones are defined there) : hetzner
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - --certificatesresolvers.myresolver.acme.email=postmaster@${SERVER_HOSTNAME}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=hetzner
      - --certificatesresolvers.myresolver.acme.dnschallenge.resolvers=helium.ns.hetzner.de,hydrogen.ns.hetzner.com,oxygen.ns.hetzner.com

        # HTTPS : port 443, with letsencrypt certificates provided by myresolver
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=myresolver
      - --entrypoints.websecure.http.tls.domains[0].main=${CERT_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${CERT_DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].main=${SERVER_HOSTNAME}
      - --entrypoints.websecure.http.tls.domains[1].sans=*.${SERVER_HOSTNAME}
        # staging letsencrypt (no quotas, but self signed certificates), comment to move to prod
      #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      #- "--providers.docker.defaultRule=Host(`{{ .Name }}.{{ index .Labels \"customLabel\"}}`)"

        # Redirect HTTP (web) to HTTPS (websecure)
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true

        # Expose prometheus metrics on port 8082 (rerouted by labels)
      - --metrics.prometheus=true
      - '--metrics.prometheus.buckets=0.1,0.3,1.2,5.0'
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --entryPoints.metrics.address=:8082
      - --metrics.prometheus.entryPoint=metrics
      - --metrics.prometheus.manualrouting=true
      - --accesslog=true

      - --entryPoints.mainnet-mezos-lb.address=:39090
      - --entryPoints.mainnet-mezos-lb.proxyProtocol.trustedIPs=${trustedIPs}
      - --entryPoints.mainnet-mezos-lb.http.tls=false
      - --entryPoints.mainnet-graphic-proxy-lb.address=:49090
      - --entryPoints.mainnet-graphic-proxy-lb.proxyProtocol.trustedIPs=${trustedIPs}
      - --entryPoints.mainnet-graphic-proxy-lb.http.tls=false
    environment:
      - HETZNER_API_KEY=${traefik_DNS_cert_Hetzner_API_Key:-notset}
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "39090:39090"
      - "49090:49090"
    volumes:
      - traefik-letsencrypt:/letsencrypt
      - traefik-logs:/logs
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - internal
      - docker-proxy-internal
    labels:
      #"traefik.frontend.rule: HostRegexp(`{catchall:.*}`)"
      traefik.enable: true
      # prometheus exporter
      traefik.http.routers.traefikmetrics.rule: Host(`traefik-metrics.${SERVER_HOSTNAME}`)
      traefik.http.routers.traefikmetrics.entrypoints: websecure
      traefik.http.routers.traefikmetrics.service: prometheus@internal
      traefik.http.services.traefikmetrics.loadbalancer.server.port: 8082
      traefik.http.routers.traefikmetrics.tls.certresolver: myresolver
      # traefik dasboard
      traefik.http.routers.api.rule: Host(`traefik.${SERVER_HOSTNAME}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.api.entrypoints: websecure
      traefik.http.routers.api.service: api@internal
      traefik.http.services.api.loadbalancer.server.port: 8080
      traefik.http.routers.api.tls.certresolver: myresolver
      traefik.http.middlewares.default-compress.compress: 'true'
      traefik.http.middlewares.default-http.redirectScheme.scheme: https
      traefik.http.middlewares.default-http.redirectScheme.permanent: 'true'
      traefik.http.middlewares.default-https.chain.middlewares: default-compress
```

Any suggestion is how to fix this or how to better enhance the oauth2-proxy configuration would be really welcomed !

Thanks in advance for your help !

**Comment by copolycube** [comment]
the logs I got from oauth2-proxy is the following, if it may help :

```
oauth                | [2022/05/11 17:51:31] [oauthproxy.go:148] OAuthProxy configured for GitLab Client ID: <redacted>
oauth                | [2022/05/11 17:51:31] [oauthproxy.go:154] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains:<DOMAIN> path:/ samesite: refresh:after 1h0m0s
oauth                | 172.21.0.3 - 7ec84a40-e256-4d23-8330-3a4189256f72 - - [2022/05/11 17:52:31] oauth:4180 GET - "/ping" HTTP/1.1 "Wget" 200 2 0.000
```

**Comment by JoelSpeed** [comment]
Do you see any logs about the redirect being invalid?

I would recommend reviewing other issues on this project about Traefik, there are lots of users who've been through this same setup. I am not a Traefik user myself so I can only be of limited help

**Comment by copolycube** [comment]
From what I understood it's redirecting to the content of this variable at OAuth2 level, or am I wrong ?

```
       OAUTH2_PROXY_REDIRECT_URL: "https://oauth.${DOMAIN}/oauth2/callback"
```

**Comment by copolycube** [comment]
This seems related  to (if not a duplicate of) : #1297 (with the start of a workaround : https://github.com/oauth2-proxy/oauth2-proxy/issues/1297#issuecomment-1143233276 )

**Comment by JoelSpeed** [comment]
> From what I understood it's redirecting to the content of this variable at OAuth2 level, or am I wrong ?

There are two different redirects. There is the redirect for the identity provider (the REDIRECT_URL) which is what we tell the identity provider to redirect to. Then there's the application redirect which is sourced from either an `rd` parameter or some headers in the case of Traefik.

**Comment by mariaWitch** [comment]
> 

> from either an `rd` parameter or some headers in the case of Traefik.
@JoelSpeed 
Taking a look at the traefik debug logs, it seems as if oauth2-proxy is pulling the X-Forwarded-Host header much too early. As the X-Fowarded-Host header that gets forwarded to oauth2-proxy is correct, however that is forwarded AFTER the rd parameter has already been applied to the url, thereby breaking redirection. I have included the debug logs from traefik which show what I mean. 

```
traefik               | time="2022-08-22T14:53:46-04:00" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/oauth2/auth/\",\"RawPath\":\"\",\"OmitHost\":false,\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip\"],\"Accept-Language\":[\"en-US,en;q=0.9\"],\"Cdn-Loop\":[\"cloudflare; loops=1\"],\"Cf-Connecting-Ip\":[\"<REDACTED>\"],\"Cf-Ipcountry\":[\"US\"],\"Cf-Ray\":[\"<REDACTED>"],\"Cf-Visitor\":[\"{\\\"scheme\\\":\\\"https\\\"}\"],\"Cookie\":[\"<REDACTED>"],\"Sec-Ch-Ua\":[\"\\\"Chromium\\\";v=\\\"104\\\", \\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Microsoft Edge\\\";v=\\\"104\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Ch-Ua-Platform\":[\"\\\"Windows\\\"\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47\"],\"X-Forwarded-Host\":[\"oauth.<REDACTED>.org\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"<REDACTED>"],\"X-Real-Ip\":[\"<REDACTED>"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"oauth.<REDACTED>.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REDACTED>:62252\",\"RequestURI\":\"/oauth2/auth/\",\"TLS\":null}"
traefik               | time="2022-08-22T14:53:46-04:00" level=debug msg="Remote error https://oauth.<REDACTED>.org/oauth2/auth/. StatusCode: 403" middlewareName=oauth-auth@file middlewareType=ForwardedAuthType
traefik               | time="2022-08-22T14:53:48-04:00" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://172.18.0.4:4180" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/oauth2/start\",\"RawPath\":\"\",\"OmitHost\":false,\"ForceQuery\":false,\"RawQuery\":\"rd=https%3A%2F%2Foauth.<REDACTED>.org%2F\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip\"],\"Accept-Language\":[\"en-US,en;q=0.9\"],\"Cdn-Loop\":[\"cloudflare\"],\"Cf-Connecting-Ip\":[\"<REDACTED>\"],\"Cf-Ipcountry\":[\"US\"],\"Cf-Ray\":[\"7<REDACTED>\"],\"Cf-Visitor\":[\"{\\\"scheme\\\":\\\"https\\\"}\"],\"Cookie\":[\"_oauth2_proxy_csrf=<REDACTED>\"],\"Referer\":[\"https://whoami.<REDACTED>.org/\"],\"Sec-Ch-Ua\":[\"\\\"Chromium\\\";v=\\\"104\\\", \\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Microsoft Edge\\\";v=\\\"104\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Ch-Ua-Platform\":[\"\\\"Windows\\\"\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"same-origin\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47\"],\"X-Forwarded-Host\":[\"**whoami.<REDACTED>.org**\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"<REDACTED>\"],\"X-Real-Ip\":[\"<REDACTED>\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"whoami.<REDACTED>.org\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"<REDACTED>:53834\",\"RequestURI\":\"/oauth2/start?rd=https%3A%2F%2Foauth.<REDACTED>.org%2F\",\"TLS\":null}"
oauth-forwardauth     | <REDACTED> - d2107b65-d30b-4b5b-86f6-30262e75800e - - [2022/08/22 18:53:48] whoami.<REDACTED>.org GET - "/oauth2/start?rd=https%3A%2F%2Foauth.<REDACTED>.org%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47" 302 493 0.000
```
The first row shows the last request traefik does before getting the 403 status code (row 2) and then throwing it over to oauth2-proxy for forward auth. My guess is that oauth2 is pulling the X-Forwarded-Host header from this request, not the following request which includes the actual url.
The third row is the exact request that Traefik is sending to oauth2-proxy. As you can see, the forwarded host header on this request is set to whoami.<REDACTED>.org rather than oauth.<REDACTED>.org. This request however already contains the improper redirection url and therefore will never redirect properly.
The forth line shows how oauth2-proxy is receiving the url as formed, which shows that the redirection url is not being set properly.

**Comment by mariaWitch** [comment]
I think I have narrowed it down. I will be making an entirely separate issue for it given the current workaround I have found is an inherent security risk and should not be used.

**Comment by michaelkoetter** [comment]
To add to @mariaWitch's findings, I think the `errors` middleware might be problematic here. It will request `/oauth2/sign_in` through Traefiks `oauth@docker` service, thus the X-Fowarded-* headers for this request will be for `oauth.DOMAIN` and not `whoami.DOMAIN`. This then gets rendered in the HTML form's `rd` parameter, and subsequent redirection is broken.

I got it to work with the following config. The important bit seems to be that `forwardAuth.address` points directly to `http://oauth2-proxy:4180/`. This means the auth request does not get routed through a Traefik service, so the X-Forwarded-* headers are preserved. 
Also note I'm not using the `/oauth2/auth` endpoint, but a static upstream with 202 status instead. 
When there is an unauthenticated request, oauth2-proxy will render the sign-in page and reply with 403, which the `forwardAuth` middleware will just pass to the client. As the X-Forwarded-* headers are now correct when the sign-in page is rendered, subsequent redirection should work.

```yaml
version: '3'

services:
  traefik:
    image: traefik:v2.8
    restart: unless-stopped
    command: 
      - "--accesslog=true"
      - "--providers.docker"
      - "--api.dashboard=true"
      - "--experimental.http3=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http3.advertisedPort=443"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"

    labels:
      traefik.http.routers.traefik.rule: Host(`traefik.fsn1.<REDACTED>`)
      traefik.http.routers.traefik.middlewares: github-auth
      traefik.http.routers.traefik.service: api@internal

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_data:/data"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    restart: unless-stopped
    command:
      - "--client-id=${OAUTH_CLIENT_ID}"
      - "--client-secret=${OAUTH_CLIENT_SECRET}"
      - "--cookie-domain=.<REDACTED>"
      - "--cookie-name=_auth_9668c2cf"
      - "--cookie-secret=${OAUTH_COOKIE_SECRET}"
      - "--email-domain=<REDACTED>"
      - "--github-org=kttr-io"
      - "--http-address=http://[::]:4180"
      - "--provider=github"
      - "--reverse-proxy=true"
      - "--redirect-url=https://auth.fsn1.<REDACTED>/oauth2/callback"
      - "--scope=user:email"
      - "--set-xauthrequest=true"
      - "--upstream=static://202"
      - "--whitelist-domain=.<REDACTED>"
      - "--whitelist-domain=.fsn1.<REDACTED>"
    
    expose:
      - '4180'

    labels:
      traefik.http.routers.oauth2-proxy.rule: Host(`auth.fsn1.<REDACTED>`) || PathPrefix(`/oauth2`)
      traefik.http.routers.oauth2-proxy.middlewares: auth-headers
      traefik.http.routers.oauth2-proxy.tls: 'true'
      traefik.http.routers.oauth2-proxy.tls.certresolver: letsencrypt
      
      traefik.http.middlewares.auth-headers.headers.sslRedirect: 'true'
      traefik.http.middlewares.auth-headers.headers.stsSeconds: '315360000'
      traefik.http.middlewares.auth-headers.headers.browserXssFilter: 'true'
      traefik.http.middlewares.auth-headers.headers.contentTypeNosniff: 'true'
      traefik.http.middlewares.auth-headers.headers.forceSTSHeader: 'true'
      traefik.http.middlewares.auth-headers.headers.sslHost: auth.fsn1.<REDACTED>
      traefik.http.middlewares.auth-headers.headers.stsIncludeSubdomains: 'true'
      traefik.http.middlewares.auth-headers.headers.stsPreload: 'true'
      traefik.http.middlewares.auth-headers.headers.frameDeny: 'true'
      
      traefik.http.middlewares.github-auth.forwardAuth.address: http://oauth2-proxy:4180/
      traefik.http.middlewares.github-auth.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.github-auth.forwardAuth.authResponseHeaders: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token,Authorization

  httpbin:
    image: kennethreitz/httpbin
    restart: unless-stopped
    labels:
      traefik.http.routers.httpbin.rule: Host(`httpbin.fsn1.<REDACTED>`)
      traefik.http.routers.httpbin.middlewares: github-auth

volumes:
  traefik_data:

```

**Comment by mariaWitch** [comment]
Please see: #1768

**Comment by Scrumplex** [comment]
bump

**Comment by vvarga007** [comment]
I have the same issue, but I cant get this working. :/

**Comment by copolycube** [comment]
From what I understood, this is related to https://github.com/traefik/traefik/issues/6814 ( #6814 )

@vvarga007 , have you tried the workaround hack mentioned here ? https://community.traefik.io/t/traefik-oauth2-proxy-forwardauth-middleware-forgets-url/14443/3

**Comment by copolycube** [comment]
workaround still required

**Comment by hegerdes** [comment]
Issue still persists. Not stale

**Comment by mcs** [comment]
Not stale. But idk if the solution lies in https://github.com/traefik/traefik/issues/6814 or here...

**Comment by croneter** [comment]
## Working ForwardAuth and redirect, no hack required, no provider button necessary
To hopefully help others not waste X hours on this: this configuration worked for me like a charm.

Replace the `${PLACEHOLDER}`s accordingly 😉. The oauth2-service listens Kubernetes-**internally** on `[oauth](http://oauth2-proxy.oauth2-proxy)` port 80 (see https://github.com/oauth2-proxy/oauth2-proxy/issues/1639#issuecomment-1224763241, thanks @michaelkoetter !!) Took some inspiration from here as well: https://github.com/oauth2-proxy/oauth2-proxy/issues/1297

Helm release oauth2-proxy and its configuration
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: 6.x
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
  interval: 15m
  timeout: 5m
  values:
    config:
      existingSecret: oauth2-proxy
      configFile: |
        reverse_proxy = true
        redirect_url = "https://oauth2.${hostname}/oauth2/callback"
        provider = "oidc"
        provider_display_name = "Keycloak"
        upstreams = [ "static://202" ]

        # OAuth2 Proxy will request a scope called api which does not exist in
        # Keycloak which will result in a 403 Invalid Scopes error
        scope = "openid profile email"
        oidc_issuer_url = "https://keycloak.${hostname}/realms/${keycloak_realm}"
        email_domains = [ "*" ]
        cookie_domains = [ "${hostname}", "*.${hostname}" ]
        whitelist_domains = [ "${hostname}", "*.${hostname}" ]

        pass_basic_auth = true
        pass_user_headers = true
        prefer_email_to_user = true
        set_authorization_header = true
        set_xauthrequest = true

        skip_provider_button = true

        silence_ping_logging = true
```

Traefik Middleware - note the forwardAuth pointing to the INTERNAL address!
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-forwardauth
  namespace: traefik
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy
    trustForwardHeader: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: traefik
spec:
  headers:
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
```

Ingressroute for oauth2-proxy
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: traefik
spec:
  routes:
  - kind: Rule
    match: Host(`oauth2.${hostname}`)
    middlewares:
    - name: auth-headers
      namespace: traefik
    services:
    - name: oauth2-proxy
      namespace: oauth2-proxy
      port: 80
  tls:
    secretName: ssl-cert
```

Traefik Ingressroute for a specific service you want to protect
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myservice
  namespace: traefik
spec:
  routes:
  - kind: Rule
    match: Host(`myservice.${hostname}`)
    middlewares:
    - name: oauth-forwardauth
      namespace: traefik
    services:
    - name: myservice
      namespace: myservice
      port: 80
  tls:
    secretName: ssl-cert
```

**Comment by lukasmrtvy** [comment]
@croneter OP is using `/oauth2/auth` endpoint not `/` , that's a major difference.

One can use `spec.forwardAuth.address=/oauth2/auth?allowed_groups=admins` for conditional access per service for  example.

**Comment by croneter** [comment]
Thanks @lukasmrtvy, updated my post accordingly - I'm actually chaining two Middlewares to take care of the endpoint. This happens if you try to simplify yamls before posting 🙈

**Comment by tuunit** [comment]
Hi @croneter thank you for the effort you put into your post!

I'll try to get it working on my local environment. We definitely need an actual kubernetes section in the documentation and update traefik and istio examples.

**Comment by eloo** [comment]
hi @croneter ,

thanks for this example.. but sadly i was not able to set this up in my environment.. 
i get a endless loop in the "sign in with... " screen of oauth2 proxy

when i click the sign in button i get a 403 from oauth proxy which looks like this in the logs

```
[2023/09/22 16:29:33] [oauthproxy.go:970] No valid authentication in request. Initiating login.
10.42.0.1 - 2c9441d1-6423-4b80-8966-be8986f80b4a - - [2023/09/22 16:29:33] dashboard.<external-domain> GET - "/" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" 403 8532 0.001
```

it looks like the middleware

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth-forwardauth
  namespace: traefik
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy
    trustForwardHeader: true
```
is directly blocking the request with 403 without allowing a call to my OIDC

Maybe there is a small bug in your example here?

**Comment by JoelSpeed** [comment]
Anyone who has got this working, are you able to write up some documentation explaining how? OAuth2 Proxy behaves correctly when you give it the right input, the missing part in the docs is how to get Traefik to pass the correct input when used in this forward auth mode

**Comment by i5Js** [comment]
+1 I'm completely lost....

**Comment by chriszuercher** [comment]
+1 I'm completely lost....

**Comment by pitkes22** [comment]
For anyone struggling with this, my issue was that in my middleware definition, I used the `/oauth2/auth` path instead of just `/` for the middleware address. I had copied the wrong value from this [Medium article](https://joeeey.com/blog/selfhosting-sso-with-traefik-oauth2-proxy-part-2/) and only realized the mistake after reading @michaelkoetter's comment. :heart:

Would not work (`rd=/`)
```
traefik.http.middlewares.oauth-verify.forwardAuth.address: http://oauth2-proxy:4180/oauth2/auth
```
Redirects correctly (`rd=<url>`)
```
traefik.http.middlewares.oauth-verify.forwardAuth.address: http://oauth2-proxy:4180/
```

**Comment by Juganooo** [comment]
For anyone using the documentation on [oauth2-docs](https://oauth2-proxy.github.io/oauth2-proxy/configuration/integration#forwardauth-with-static-upstreams-configuration) :

for the middlewares part that is : 
```
oauth-auth-redirect:
  forwardAuth:
    address: https://oauth.example.com/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
oauth-auth-wo-redirect:
  forwardAuth:
    address: https://oauth.example.com/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
```

for both middlewares ensure the oauth-proxy container is in same docker network than traefik and replace
`oauth.example.com` by `<oauth2-proxy-container-name>:4180`

so for oauth2-proxy as container name it would be : 
```
oauth2-auth-redirect:
  forwardAuth:
    address: "http://oauth2-proxy:4180/"
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization

oauth2-auth-wo-redirect:
  forwardAuth:
    address: "https://oauth2-proxy:4180/oauth2/auth"
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
```
