### ISSUE TITLE
Question: Can we remove header from the response?

### ISSUE THREAD

**Issue by newhorizs** [oauth2-proxy/oauth2-proxy#1648]
Because there are some header which I don't want to show in the response header.
-> Is it possible to remove header from response header?

I'm finding a way to remove 2 header below:
**Gap-Auth: myuser@email.com
Server: nginx**

Thanks!

**Comment by JoelSpeed** [comment]
Which header is it that you don't want to see in the response? If it's one that OAuth2 Proxy is adding, then changing your settings should prevent it from setting that header

**Comment by newhorizs** [comment]
Hi @JoelSpeed, I'm sorry that I didn't provide enough information. my question is updated.

I want to remove 2 header Gap-Auth & Server because it show user and system information, I think it comes from Oauth2 proxy. I search a lot but can not find any way to remove it.

**Comment by JoelSpeed** [comment]
Could you have a look to see if you have `--signature-key` set in your configuration, I think that's responsible for the Gap-Auth header at least. Server, not sure that is OAuth2 Proxy based, that could be coming from Nginx itself

If you haven't got that flag set, please share your config with all of the personal information redacted and any other relevant details that will help us to understand your particular set up

**Comment by newhorizs** [comment]
I haven't set --signature-key in my config file.

This is my config file:
`
    cookie_name = "xxx"
    cookie_samesite = "xxx"
    reverse_proxy = true
    real_client_ip_header = "X-Forwarded-For"
    proxy_prefix = "/mysite"
    email_domains = [ "email.com" ]
    skip_jwt_bearer_tokens = true
    skip_provider_button = true
`

and alpha config file:

````yaml
injectResponseHeaders:
      - name: xxx
        values:
          - value: xxx
    providers:
      - id: Keycloak
        name: Keycloak
        clientID: ""
        clientSecret: ""
        oidcConfig:
          emailClaim: email
          groupsClaim: groups
          insecureSkipNonce: true
          userIDClaim: email
          issuerURL:
        provider: keycloak-oidc
    upstreamConfig:
      upstreams:
        - flushInterval: 1s
          id: /
          passHostHeader: true
          path: /
          proxyWebSockets: true
          uri: http://backend:80
````

I'm using docker image version `v7.2.1`
