### ISSUE TITLE
Github Auth return 404 after auth with 7.3.0. 7.2.0 no issues

### ISSUE THREAD

**Issue by frederiksf** [oauth2-proxy/oauth2-proxy#1669]
## Expected Behavior
Athenticate and forward to backend app

## Current Behavior

Return 500 image from proxy. Get 404 Error in proxy log

```AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" 302 315 0.000
[2022/05/31 12:26:17] [github.go:280] Found Github Organization:"XXX_BV" Team:"k8s-log-XXX" (Name:"k8s-log-XXX")
[2022/05/31 12:26:17] [oauthproxy.go:775] Error creating session during OAuth2 callback: unexpected status "404": {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/users#list-email-addresses-for-the-authenticated-user"}
```

## Your Environment
Docker (bitnami build)
used env:
```
    spec:
      containers:
        - args:
            - '--provider=github'
            - '--github-org=XXX_BV'
            - '--github-team=k8s-log-XXX'
            - '--email-domain=*'
            - '--redirect-url=https://kibana.XXX.net/oauth2/callback'
            - '--upstream=file:///dev/null'
            - '--http-address=0.0.0.0:4180'
            - '--custom-sign-in-logo=/mnt/logo.png'
            - '--footer=-'
 ```

- Version used:
- 7.3.0 (broken)
- 7.2.0 (working)
