### ISSUE TITLE
GitHub auth using access token not working. 

### ISSUE THREAD

**Issue by rpeets** [oauth2-proxy/oauth2-proxy#1688]
I believe, might have miss something, Same time I'm not 100% sure, what I'm trying to do really work or not. 
So I thought I'll double check here, because currently accessing to REST API with GitHub Access Token is not working for me. 

## Expected Behavior

I have a REST API configured with oauth2-proxy,  provider=github
Currently authentication using web browser work and I can access the API endpoints (using username and password)

However, I'm unable to access the same API using Github Access Token. using curl command. 
Assuming this will make it easier to create command line tools to call the API endpoints. 
if I disable the oauth2-proxy, my REST-API works fine (without auth)

## Current Behavior

Unable to authenticate using GitHub access token
Authentication works while using the web browser (with username and password)

## Your Environment
<img width="1284" alt="Screen Shot 2022-06-13 at 11 38 45 PM" src="https://user-images.githubusercontent.com/94394229/173512918-f3ca8848-9ee4-4b14-b1d5-3515ea4137d9.png">

deployment yaml. 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: myname/webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1-amd64
        imagePullPolicy: Always
        args:
        - --provider=github
        - --github-org=MyOrg
        - --github-team=MyTeam
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --pass-access-token=true
        - --set-xauthrequest=true
        - --cookie-domain=example.com
        - --cookie-secure=true
        - --cookie-httponly=false
        - --cookie-expire=12h0m0s
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: bb####################94
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: 2d####################################58
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: DCgNjGGm+IiqVoh2uJGomg==
        ports:
        - containerPort: 4180
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: proxy
    port: 4180
    protocol: TCP
    targetPort: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: webapp
  labels:
    name: webapp
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx-ingress-external
  rules:
  - host: webapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: webapp
spec:
  ingressClassName: nginx-ingress-external
  rules:
  - host: webapp.example.com
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 4180
```

- Version used:
  oauth2-proxy:v7.2.1-amd64
