### ISSUE TITLE
proxy-prefix doesn't wrap upstream in http calls

### ISSUE THREAD

**Issue by japrogramer** [oauth2-proxy/oauth2-proxy#1689]
## Expected Behavior

I want to have oauth2-proxy run under a path in my website. 
http://localhost:/secret/manager/
and when a successful oa500uth2 login happens I want to serve the upstream site 
my_webservice:80 which runs in a docker container. under the same prefix.
  
## Current Behavior
however after a successful oauth2 login, the website redirects me to the base url of
http://localhost:5000/ and not back to http://localhost:5000/secret/manager/ 

where I would I expect the app to be loaded.

I see from the browser title that the app is running but none of the resources load correctly,
because the are all being requested from http://localhost:5000/ and not http://localhost:5000/secret/manager

## Possible Solution & Context

It only works if I serve the oauth2proxy under a subdomain and a root base path
like http://hidden.localhost:5000/  but than what is the point of --proxy-prefix ?
I don't want to have a subdomain.

I don't know what I am doing wrong.

## Steps to Reproduce (for bugs)
CADDYFILE
```
http://localhost:5000 {
    @oauth {
        path /secret/manager/*
    }

    @basepath {
        path /*
    }

    handle @oauth {
        reverse_proxy oauth2proxy:4180 {
            header_up X-Forwarded-Proto {scheme}
            header_up X-Forwarded-For {remote_host}
            header_up X-Forwarded-Method {method}
            header_up X-Forwarded-Uri {uri}
            header_up Host {host}
            header_up X-Real-IP {rempote_host}
            header_down Server
        }
    }

    handle @basepath {
        respond "Hello World"
    }

    log {
        output stdout
    }
}
```

```
version: '3.6'
services:
  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2proxy
    ports:
    - "4180:4180"
    command: [
      "--provider=generic",
      "--reverse-proxy",
      "--proxy-prefix=/secret/manager",
      "--scope=openid profile email",
      "--cookie-secure=false",
      "--cookie-secret=${COOKIESECRET}",
      "--upstream=http://webapp:80/",
      "--provider-display-name=${PROVIDER_NAME}",
      "--client-id=${OAUTHCLIENTID}",
      "--client-secret=${OAUTHCLIENTSECRET}",
      "--redirect-url=http://localhost:5000/secret/manager/callback",
      "--oidc-issuer-url=https://${OAUTHSOURCE}",
      "--insecure-oidc-skip-nonce",
      "--skip-oidc-discovery",
      "--oidc-jwks-url=https://${OAUTHKEYS}",
      "--login-url=https://${OAUTHAUTHORIZE}",
      "--redeem-url=https://${OAUTHTOKEN}",
      "--profile-url=https://${OAUTHPROFILE}",
      "--email-domain=*",
      "--http-address=0.0.0.0:4180",
    ]
    env_file:
      - .oauth2_env

networks:
  default:
    name: endoplasmic-reticulum
```
```
version: '3.6'
services:
  caddy:
    image: caddy:2.0.0-alpine
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./caddyfiles/local-Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    name: endoplasmic-reticulum
```

## Your Environment
- Version used:
latest  docker build

**Comment by JoelSpeed** [comment]
Have you tried accessing the path `/secret/manager` once you have authenticated? What does it do? When you do this, what path does the upstream server observe?

Have you tried adding a path to the upstream address? Eg have you tried `http://webapp:80/secret/manager`? This should mean that the upstream application is only served from OAuth2 Proxy at `/secret/manager`

The proxy prefix is meant to just be a prefix of the paths related to the proxy itself, normally it's `oauth2/`, so I would recommend if you want the OAuth2 Proxy and your entire upstream application behind `/secret/manager` to set the proxy prefix to `/secret/manager/oauth2`

**Comment by japrogramer** [comment]
adding a path to the upstream address, seems to affect the way upstream urls are routed.
that severely effects the upstream and breaks many upstream apps.
for example if I have the following upstreams 

  1       "--upstream=http://webapp:80/test",
16        "--upstream=https://google.com/search",

I can only reach google if search trails the path used to reach the oauth2-proxy server but after that every single request needs to have /search in its path otherwise it isn't served correctly.

I read that there was another way to route through the upstreams by giving them an id but there where no examples on how to do this.
I think I would like to try using the id approach because the path breaks most upstream apps.

**Comment by japrogramer** [comment]
it seems that upstream apps only work when they are on the root path / otherwise they can't find resources and break.

**Comment by japrogramer** [comment]
@JoelSpeed  I have now tried the alpha config with and I still can't get google to work well.
thats just an example, webapp works but only when the path is / 

```
upstreamConfig:
  upstreams:
  - flushInterval: 1s
    id: webapp
    passHostHeader: true
    path: /
    proxyWebSockets: true
    timeout: 30s
    uri: http://webapp:80/
  - flushInterval: 1s
    id: google
    passHostHeader: true
    path: /google/
    proxyWebSockets: true
    timeout: 30s
    uri: https://google.com/
```
