### ISSUE TITLE
Invalid JWT Signature using DEX

### ISSUE THREAD

**Issue by nicolasmanic** [oauth2-proxy/oauth2-proxy#1693]
I have the oauth2-proxy in front of my backend service, the setup same to the provided example: https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/docker-compose.yaml.

I'm able to get the jwt token from `X-Forwarded-Access-Token` but the signature of the JWT is not valid:
https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjlkMGVlZGZhMzczMWYxZjU5MWZlNTVlOTEzN2YzM2I0YmEwMmM1NjkifQ.eyJpc3MiOiJodHRwOi8vZGV4LmxvY2FsaG9zdDo0MTkwL2RleCIsInN1YiI6IkNpUXdPR0U0TmpnMFlpMWtZamc0TFRSaU56TXRPVEJoT1MwelkyUXhOall4WmpVME5qWVNCV3h2WTJGcyIsImF1ZCI6Im9hdXRoMi1wcm94eSIsImV4cCI6MTY1NTM4OTI2MiwiaWF0IjoxNjU1Mzg1NjYyLCJhdF9oYXNoIjoiM3Ntc25ET2FMLXB0bmVIc0JVYVJvZyIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6ImFkbWluIn0.VkVqiQu2Zd-gT7Zcb9_aqPS_eiZHdSdeqbBWxgdy_LwZoxIEivBrIzIcuGTsKmxKbaeV20RYHLGf7jagvl1RrjCtZXtr5EMvqzP3kgIJvlG_8ek6T1jpTrF15LYKl-BtNOJ-KUOVTUR0fqJ-o1VV32j2S5I2X-QGlPTfu0XqNQ31UGy4vdnzPGSMeiY9kGQCm3z7mVpCz6W_FqBT2tkOeGhK_XlY8KoHfyoaZ5HGFj39UEob__ycTR12wVfoifzELP3fXMls5D9prUB5OmwrOOH93Sux5UrHaPwpZLO6ZvZIJ8i1r1QSYp17BDMRDm-AQPByc7srHsfh6fPOAG4anw

## Steps to Reproduce (for bugs)

1. `docker-compose -f docker-compose.yaml up` for https://github.com/oauth2-proxy/oauth2-proxy/blob/master/contrib/local-environment/docker-compose.yaml

2. Inspect the headers

## Your Environment

Running locally using docker compose 

Oauth2 proxy config:
```
http_address="0.0.0.0:4180"
cookie_secret="OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
provider="oidc"
email_domains="example.com"
oidc_issuer_url="http://dex.localhost:4190/dex"
client_secret="b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK"
client_id="oauth2-proxy"
cookie_secure="false"
pass_access_token="true"

redirect_url="http://localhost:4180/oauth2/callback"
upstreams="http://httpbin"


```

dex config:

```
issuer: http://dex.localhost:4190/dex
storage:
  type: etcd
  config:
    endpoints:
      - http://etcd:2379
    namespace: dex/
web:
  http: 0.0.0.0:4190
oauth2:
  skipApprovalScreen: true
expiry:
  signingKeys: "12h"
  idTokens: "10h"
staticClients:
  - id: oauth2-proxy
    redirectURIs:
      # These redirect URIs point to the `--redirect-url` for OAuth2 proxy.
      - 'http://localhost:4180/oauth2/callback' # For basic proxy example.
      - 'http://oauth2-proxy.oauth2-proxy.localhost/oauth2/callback' # For nginx and traefik example.
    name: 'OAuth2 Proxy'
    secret: b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK
enablePasswordDB: true
staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
```

- Version used:
v7.3.0
