### ISSUE TITLE
How to redirect after login successfully if I'm set application in the subpath

### ISSUE THREAD

**Issue by krittidet** [oauth2-proxy/oauth2-proxy#1694]
- microk8s
- Ingress
- keycloak
- oauth2-proxy 7.2.1
- sample application

Reproduce step
1. go to the website `test.mywebsite.com/test`
2. Everything look working the browser redirect to the KeyCloak auth page
3. type with the right credentials
4. success
5. after login success the system redirects to test.mywebsite.com, It should be redirecte to test.mywebsite.com/test

How am I'm missing some settings?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: test-oauth2-proxy
  name: test-oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: test-oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: test-oauth2-proxy
    spec:
      containers:
      - args:
        - --oidc-issuer-url=https://auth.mywebsite.com/auth/realms/master
        - --client-id=oauth2-proxy
        - --client-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        - --provider=oidc
        - --email-domain=*
        - --upstream=http://html-app-test
        - --redirect-url=https://test.mywebsite.com/test/oauth2/callback
        - --http-address=0.0.0.0:4180
        - --cookie-domain=.mywebsite.com
        - --whitelist-domain=.mywebsite.com
        - --cookie-secret=xxxxxxxxxxxxxxxxxxxxxxxxx
        - --set-authorization-header=true
        - --set-xauthrequest=true
        - --cookie-secure=false
        - --ssl-insecure-skip-verify=true
        - --ssl-upstream-insecure-skip-verify=true
        - --skip-provider-button=true
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
        imagePullPolicy: Always
        name: test-oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: test-oauth2-proxy
  name: test-oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: test-oauth2-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test-mywebsite-oauth2-proxy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$4
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: public
  rules:
  - host: test.mywebsite.com
    http:
      paths:
      - path: /()(test)(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: test-oauth2-proxy
            port:
              number: 4180
```

**Comment by JoelSpeed** [comment]
If you are using skip-provider-button, you need to somehow inject the `rd` parameter or appropriate headers to tell OAuth2 Proxy where it should redirect to after login.

However, in your case, as you are using nginx ingress, I would suggest checking our docs for how to use this with `auth_request` mode, it makes things a little easier and means that only the authentication is handled by OAuth2 Proxy and then requests are proxied by nginx directly to the upstream once authenticated

**Comment by krittidet** [comment]
> 

Thank you I'm already fixed. It working now.

**Comment by saqlain24** [comment]
Hi @krittidet , How you fixed?

**Comment by fishfree** [comment]
Hi @krittidet , How you fixed?

**Comment by krittidet** [comment]
> Hi @krittidet , How you fixed?

@saqlain24 @fishfree I'm just add `rd` parameter 

like this 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://test.mywebsite.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://test.mywebsite.com/oauth2/start?rd=$scheme://$host$request_uri"
    nginx.ingress.kubernetes.io/rewrite-target: /$4
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
spec:
  rules:
  - host: "test.mywebsite.com"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /()(test)(/|$)(.*)
        backend:
          service:
            name: html-app-test
            port:
              number: 80
```
