### ISSUE TITLE
How to get Authorization header without upstream

### ISSUE THREAD

**Issue by krittidet** [oauth2-proxy/oauth2-proxy#1695]
- microk8s
- Ingress
- keycloak
- oauth2-proxy 7.2.1
- sample application

Reproduce step
1. go to the website `subd.mywebsite.com`
2. Everything look working the browser redirect to KeyCloak auth page
3. type with the right credentials
4. success
5. after login try to inspect in google chrome
6. The result in the response header does not have an authorization bearer token

How am I'm missing some settings?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test-mywebsite
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: public
  rules:
  - host: subd.mywebsite.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: html-app-test
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test-mywebsite-oauth2-proxy
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: public
  rules:
  - host: subd.mywebsite.com
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy-test
            port:
              number: 4180
  tls:
  - hosts:
    - subd.mywebsite.com
    secretName: auth-tls-secret-test-mywebsite-dev-com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy-test
  name: oauth2-proxy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy-test
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy-test
    spec:
      containers:
      - args:

        - --redeem-url=https://auth.mywebsite.com/auth/realms/master/protocol/openid-connect/token
        - --oidc-issuer-url=https://auth.mywebsite.com/auth/realms/master
        - --client-id=oauth2-proxy
        - --client-secret=7bc1c7ff-9820-4b42-bb55-8f81d208060b

        - --provider=keycloak-oidc
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --cookie-domain=.mywebsite.com
        - --whitelist-domain=.mywebsite.com
        - --cookie-secret=Z2lCUXFYNVVGYVAya1QzWU1ja2J0aFBsbVNkU2trVm0=
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --set-xauthrequest=true
        - --cookie-secure=false
        - --ssl-insecure-skip-verify=true
        - --ssl-upstream-insecure-skip-verify=true
        - --pass-user-headers
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy-test
  name: oauth2-proxy-test
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy-test
```
