### ISSUE TITLE
[Question] How to get the id token from the oauth2 proxy

### ISSUE THREAD

**Issue by StrongSteve** [oauth2-proxy/oauth2-proxy#1706]
With the changes introduced in keycloak 18 in regards to logout, redirect and the need for an id_token_hint (https://www.keycloak.org/2022/04/keycloak-1800-released -> OpenId Connect Logout) I am really struggling on how to get the id_token_hint from the oauth2 proxy.

We have a frontend angular application, so I would need the URL in the frontend.
Any advice, hints?

One solution may be to write a logout endpoint in the backend but...

I already tried inspecting the cookie or the oauth2/auth endpoint but sadly without luck.

**Comment by hevans-dglcom** [comment]
You can pass the id_token as a header.

Alpha config:
```
injectResponseHeaders:
    - name: Identity   (this is what you want the name of the header to be that contains your token)
    values:
    - claim: id_token
```
