### ISSUE TITLE
Client secret is not required for OIDC with PKCE enabled

### ISSUE THREAD

**Issue by jamesalucas** [oauth2-proxy/oauth2-proxy#1714]
First off, thanks for the great project!

## Expected Behavior

I have configured oauth2-proxy with Okta and configured the Okta app to be a public client using PKCE and in this case there is no client secret provided by Okta. It would be great to be able to start oauth2-proxy without a client secret because it works perfectly with PKCE if you are able to work around not supplying the client secret.

## Current Behavior

The startup validation checks that client secret is provided unless the provider is login.gov:

https://github.com/oauth2-proxy/oauth2-proxy/blob/f6aa7600ea867ec069f86990501c0629aa4b5064/pkg/validation/providers.go#L51-L61

However, I've found that it's possible to work around this by supplying an empty client secret file via the client-secret-file argument.

## Possible Solution

Perhaps a special value of 'none' would skip validation - or maybe tie it to the code challenge type parameter being set (although presumably some OIDC providers do provide a client secret when using pkce?)

## Steps to Reproduce (for bugs)

Start oauth2 proxy without a client secret supplied, startup will error.

1.  Set client secret to an empty string
2.  Set other params to use Okta OIDC with PKCE enabled

```
      image:
        tag: v7.3.0
      config:
        clientID: blahblahblah
        clientSecret: ""
        cookieSecret: blahblahblahblahblah
      extraArgs:
        provider: oidc
        redirect-url: /oauth2/callback
        oidc-issuer-url: https://somedomain.oktapreview.com/oauth2/default
        code-challenge-method: S256
        email-domain: "*"
        skip-provider-button: true
        set-authorization-header: true
        set-xauthrequest: true
        scope: openid profile email groups
```

4.  Start oauth2-proxy

## Context

Trying to use oauth2-proxy with Okta PKCE as per (this)[https://developer.okta.com/blog/2019/08/22/okta-authjs-pkce] article.

## Your Environment

- Version used:

7.3.0
