### ISSUE TITLE
Access token validation failure. Invalid audience. Using 7.3.0 and azure AD

### ISSUE THREAD

**Issue by bluebrown** [oauth2-proxy/oauth2-proxy#1715]
Hi, I noticed an 500 error after the auth flow. After some troubleshooting I found out that this happens with 7.3 but not with 7.2.1.

Image deployed: `quay.io/oauth2-proxy/oauth2-proxy:v7.3.0`

I am not able to pinpoint the specific reason for this. The error message is this:

```
[2022/07/04 21:05:52] [oauthproxy.go:768] Error redeeming code during OAuth2 callback: could not get claim "groups": 
failed to fetch claims from profile URL: error making request to profile URL: unexpected status "401": 
{"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience."
```

The config, I am using looks like this:

```yaml
# pod spec
args:
  - --http-address=0.0.0.0:4180
  - --cookie-domain=.my.domain
  - --cookie-refresh=1h
  - --oidc-issuer-url=https://login.microsoftonline.com/<redacted>/v2.0
  - --pass-access-token=true
  - --provider=oidc
  - --scope=openid email api://<redacted>/User.Read
  - --set-xauthrequest=true
  - --whitelist-domain=.my.domain
  - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
env:
  - name: OAUTH2_PROXY_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: oauth2-proxy-int
        key: client-id
  - name: OAUTH2_PROXY_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: oauth2-proxy-int
        key: client-secret
  - name: OAUTH2_PROXY_COOKIE_SECRET
    valueFrom:
      secretKeyRef:
        name: oauth2-proxy-int
        key: cookie-secret
  - name: OAUTH2_PROXY_SESSION_STORE_TYPE
    value: "redis"
  - name: OAUTH2_PROXY_REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis
        key: redis-password
  - name: OAUTH2_PROXY_REDIS_CONNECTION_URL
    value: redis://redis:6379/3

# configmap
 oauth2_proxy.cfg: "email_domains = [ \"*\" ]\nupstreams = [ \"file:///dev/null\" ]"
```

The proxy is configured to work with azure AD. 

As mentioned, the same config works fine with 7.2.1.

**Comment by JoelSpeed** [comment]
There are some bugs at the moment with the scope parameter for Azure, could you see if you can verify that the scope parameter is being sent correctly with the initiation of the authentication flow

**Comment by Rojax** [comment]
I'm also getting an error using 7.3.0 which was not present in 7.2.1. I'm using nginx as proxy. Do you think this is related to this issue or should I open a new one?

OAuth2-Proxy config itself is pretty default and following the docs.

compose file
```
version: "3.8"
services:
  proxy:
    build: 
      context: .
      args: 
        - BUILDKIT_INLINE_CACHE=1
    init: true
    depends_on: 
      - auth
      - redis
    env_file: 
      - ./conf/vars.env
    volumes:
      - /etc/hosts:/etc/hosts:ro
    restart: always
  
  redis:
    image: bitnami/redis:6.2.7@sha256:f84f2c8afa1c9053606a3dca096c323b02cb15c41b0e1eadaba1f916eb33c9a3
    volumes:
      - /etc/hosts:/etc/hosts:ro
    env_file: 
      - ./conf/vars.env
    restart: always
  
  auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    volumes:
      - /etc/hosts:/etc/hosts:ro
    env_file: 
      - ./conf/vars.env
    depends_on:
      - redis
    restart: always
```

proxy config for OAuth
```
# See: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-nginx-auth_request-directive
# pass information via X-User and X-Email headers to backend,
# requires running with --set-xauthrequest flag
auth_request_set $user   $upstream_http_x_auth_request_user;
auth_request_set $email  $upstream_http_x_auth_request_email;
proxy_set_header X-User  $user;
proxy_set_header X-Email $email;

# if you enabled --cookie-refresh, this is needed for it to work with auth_request
auth_request_set $auth_cookie $upstream_http_set_cookie;
add_header Set-Cookie $auth_cookie;
```

logs (redacted)
```
auth_1   | 10.0.2.2 - bca02d67-f26f-4a84-a5c5-c1da122b3657 - - [2022/07/08 12:07:29] localhost GET - "/oauth2/start?rd=%2Fevaluate%2F" HTTP/1.0 302 415 0.000
proxy_1  | 10.0.2.2 - - [08/Jul/2022:12:07:29 +0000] "GET /oauth2/start?rd=%2Fevaluate%2F HTTP/1.1" 302 415 "https://localhost:9443/evaluate/"
auth_1   | [2022/07/08 12:07:33] [azure.go:227] unable to get claims from token: could not get claim "email": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "400": 
auth_1   | [2022/07/08 12:07:33] [azure.go:157] unable to get email claim from id_token: <nil>
auth_1   | [2022/07/08 12:07:33] [azure.go:230] unable to verify token: failed to verify token: failed to verify signature: failed to verify id token signature
auth_1   | [2022/07/08 12:07:33] [azure.go:165] unable to get email claim from access token: <nil>
auth_1   | [2022/07/08 12:07:33] [oauthproxy.go:775] Error creating session during OAuth2 callback: unable to get email address: unexpected status "400": 
auth_1   | 10.0.2.2 - 800450b9-4399-4a80-a6b2-25a8e019488b - - [2022/07/08 12:07:32] localhost GET - "/oauth2/callback?code=..."
proxy_1  | 10.0.2.2 - - [08/Jul/2022:12:07:33 +0000] "GET /oauth2/callback?code=..."
auth_1   | 10.0.2.2 - f16bb49f-9f4c-4a6b-a48a-b367d783cfcd - - [2022/07/08 12:07:34] localhost GET - "/oauth2/auth" HTTP/1.0 401 13 0.000
auth_1   | 10.0.2.2 - b8cfea70-4c08-4d96-a513-8b379782713d - - [2022/07/08 12:07:34] localhost GET - "/oauth2/sign_in" HTTP/1.0 200 8035 0.001
proxy_1  | 10.0.2.2 - - [08/Jul/2022:12:07:34 +0000] "GET /favicon.ico HTTP/1.1" 200 8061 "https://localhost:9443/oauth2/callback?code=..."
```
