### ISSUE TITLE
failed to redirect to app callback url

### ISSUE THREAD

**Issue by prakashmirji** [oauth2-proxy/oauth2-proxy#1728]
I am trying to integrate with okta for external authorization for our web-app

## Expected Behavior

After the successful login to okta, the request should be directed back to web-app home page. 
( configured the app callback URL in the okta applications section)

## Current Behavior
I get the okta login page, I enter the credentials, i see the redirect callback calls in the browser and then it goes back to okta domain. It tries this continuous redirect for few times. I am not seeing my app home page ( callback URL)

## Steps to Reproduce (for bugs)

here is the istio mesh config:

```
istioctl manifest install -y -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: "[%START_TIME%] %REQ(Authorization)% %REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%
%RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% %REQ(X-FORWARDED-FOR)% %REQ(USER-AGENT)%
%REQ(X-REQUEST-ID)% %REQ(:AUTHORITY)% %UPSTREAM_HOST%\n"
    extensionProviders:
    - name: oauth2-proxy
      envoyExtAuthzHttp:
        service: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port: 4180
        headersToUpstreamOnAllow:
        - authorization
        - cookie
        - set-cookie
        - x-auth-request-user
        - x-auth-request-access-token
        - x-auth-request-email
        - path
        - x-forwarded-access-token
        headersToDownstreamOnDeny:
        - set-cookie
        - content-type
        includeRequestHeadersInCheck:
        - authorization
        - cookie
        - set-cookie
        - x-forwarded-access-token
        - x-fowarded-host
EOF
```

Here is the oauth2-proxy setup details

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
        args:
        - --provider=oidc
        - --cookie-secure=false
        - --cookie-samesite=lax
        - --cookie-path=/
        - --cookie-refresh=1h
        - --cookie-expire=4h
        - --cookie-name=SESSION
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --set-xauthrequest=true
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --upstream=static://200
        - --skip-provider-button=true
        - --whitelist-domain=.xxx-yyy.com
        - --whitelist-domain=.okta.com
        - --cookie-domain=.xxx-yyy.com
        - --cookie-domain=.okta.com
        - --oidc-issuer-url=$OIDC_ISSUER_URL
        - --pass-access-token=true
        - --pass-host-header=true
        - --redirect-url=http://home.xxx-yyy.com/authorization-code/callback
        - --reverse-proxy=true
        - --standard-logging=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: OAUTH2_PROXY_CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy
              key: OAUTH2_PROXY_COOKIE_SECRET
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        ports:
        - containerPort: 4180
          protocol: TCP
        readinessProbe:
          periodSeconds: 3
          httpGet:
            path: /ping
            port: 4180
EOF
```

here is the istio AuthorizationPolicy

```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        paths: ["*"]
  selector:
    matchLabels:
      app: istio-ingressgateway
```

Here is the istio Gateway and VirtualService

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-vs
spec:
  hosts:
  - "home.xxx-yyy.com"
  - "dev-37110063.okta.com"
  gateways:
  - default/my-gateway
  http:
  - route:
    - destination:
        host: app-ui.ui.svc.cluster.local
        port:
          number: 3000
      headers:
        request:
          set:
            Authorization: 'Bearer %REQ(x-auth-request-access-token)%'
```

here are some of the log message from oauth2-proxy pod ( istio-proxy container )

```
{"route_name":"default","upstream_service_time":"0","requested_server_name":"outbound_.4180_._.oauth2-proxy.oauth2-proxy.svc.cluster.local","path":"/authorization-code/callback?code=00mBVPcGEoTsSnKEOfATymvUDLGtyqD9dD3zry2I9jQ&state=nbC_n3ZfKIu2lP7nEuMbRkJ96OTrdknQUBZRjPjAmsU%3A%2Fauthorization-code%2Fcallback%3Fcode%3DQQsezdZQQIapSi1ijW-U08AwbPfajtHNtILBORs7SXM%26state%3DFojmd2qqhAxkihKRou7Al1Zos_O7wnDyTldqH6dCpxA%253A%252Fauthorization-code%252Fcallback%253Fcode%253DCluAs1Sknx5Aaplk_f7Wg7xQE77ikIGi0cofb7wpOp8%2526state%253Dxz8ZVzeIPdbhMb4zQ6dfrzik45jBH6GWC8t4O4EHR3w%25253A%25252Fauthorization-code%25252Fcallback%25253Fcode%25253DBIgmiwFrr3hrdrGt6iaYFmkPMzmbNoJMv7vjf-vNiRw%252526state%25253D3qtAHzxOxDOC2IkWe1WIKJ2T7N7nTUMrGRmGXqyhA1g%2525253A%2525252Fauthorization-code%2525252Fcallback%2525253Fcode%2525253DCn89754MmowAx2N5rCXq9n4rgVuniMgHSawGdJLQGQs%25252526state%2525253D1RRWolW4pLFsouB_pPPU2mxAemh3FwRRDZN6tZclyx4%252525253A%252525252Fauthorization-code%252525252Fcallback%252525253Fcode%252525253DOvT6jQNFV8obygZxwqM2-bEa9VQphPdDlfWxTvN_4DU%2525252526state%252525253DIX5I12vcLweLS4tdyW0GII50MfgETC24s84sHE9PwCA%25252525253A%25252525252Fauthorization-code%25252525252Fcallback%25252525253Fcode%25252525253D5m510mptPDd2_kZMkLroIpJeRSNULPDSURGgt0onpuQ%252525252526state%25252525253DRSZ006S832hKrYYTUjXIgbIklgza4jWpoo1oYx7K9IE%2525252525253A%2525252525252Fauthorization-code%2525252525252Fcallback%2525252525253Fcode%2525252525253DMV0Spb7eT_IS_nDCzp4FvMxZn316MdFu-c0Z17s0Tek%25252525252526state%2525252525253DY_Ib-faiu1h_LYYbDviM2XBW-tuWhRlej_FvhTbeutg%252525252525253A%252525252525252Fauthorization-code%252525252525252Fcallback%252525252525253Fcode%252525252525253DBQxOQmSQLoVR9nzqTG0R_mfuFgG3e--p9ANgtTxHxgA%2525252525252526state%252525252525253DoArzQg10yioAH_bQuZa8j1phmbefQqnFmduwfoIXu1E%25252525252525253A%25252525252525252F","start_time":"2022-07-14T21:24:00.945Z","protocol":"HTTP/1.1","upstream_transport_failure_reason":null,"x_forwarded_for":"10.244.3.104","downstream_local_address":"10.244.3.112:4180","upstream_cluster":"inbound|4180||","bytes_sent":2141,"upstream_host":"10.244.3.112:4180","response_flags":"-","authority":"home.xxx-yyy.com","upstream_local_address":"127.0.0.6:51339","request_id":"d2d7154e-1e33-40e4-9b06-2099420c200f","duration":0,"response_code":302,"user_agent":null,"response_code_details":"via_upstream","method":"GET","downstream_remote_address":"10.244.3.104:0","bytes_received":0,"connection_termination_details":null}
{"upstream_local_address":"127.0.0.6:51339","upstream_service_time":"0","protocol":"HTTP/1.1","route_name":"default","path":"/authorization-code/callback?code=wZ_DjrshIgxskDeKFdzrohHPxjAko4PrnWvcx4emMNc&state=7Ij7ZUdxUB7QVvvOU3MR0umjXIpgs1wlMFX-hHnVmBs%3A%2Fauthorization-code%2Fcallback%3Fcode%3D00mBVPcGEoTsSnKEOfATymvUDLGtyqD9dD3zry2I9jQ%26state%3DnbC_n3ZfKIu2lP7nEuMbRkJ96OTrdknQUBZRjPjAmsU%253A%252Fauthorization-code%252Fcallback%253Fcode%253DQQsezdZQQIapSi1ijW-U08AwbPfajtHNtILBORs7SXM%2526state%253DFojmd2qqhAxkihKRou7Al1Zos_O7wnDyTldqH6dCpxA%25253A%25252Fauthorization-code%25252Fcallback%25253Fcode%25253DCluAs1Sknx5Aaplk_f7Wg7xQE77ikIGi0cofb7wpOp8%252526state%25253Dxz8ZVzeIPdbhMb4zQ6dfrzik45jBH6GWC8t4O4EHR3w%2525253A%2525252Fauthorization-code%2525252Fcallback%2525253Fcode%2525253DBIgmiwFrr3hrdrGt6iaYFmkPMzmbNoJMv7vjf-vNiRw%25252526state%2525253D3qtAHzxOxDOC2IkWe1WIKJ2T7N7nTUMrGRmGXqyhA1g%252525253A%252525252Fauthorization-code%252525252Fcallback%252525253Fcode%252525253DCn89754MmowAx2N5rCXq9n4rgVuniMgHSawGdJLQGQs%2525252526state%252525253D1RRWolW4pLFsouB_pPPU2mxAemh3FwRRDZN6tZclyx4%25252525253A%25252525252Fauthorization-code%25252525252Fcallback%25252525253Fcode%25252525253DOvT6jQNFV8obygZxwqM2-bEa9VQphPdDlfWxTvN_4DU%252525252526state%25252525253DIX5I12vcLweLS4tdyW0GII50MfgETC24s84sHE9PwCA%2525252525253A%2525252525252Fauthorization-code%2525252525252Fcallback%2525252525253Fcode%2525252525253D5m510mptPDd2_kZMkLroIpJeRSNULPDSURGgt0onpuQ%25252525252526state%2525252525253DRSZ006S832hKrYYTUjXIgbIklgza4jWpoo1oYx7K9IE%252525252525253A%252525252525252Fauthorization-code%252525252525252Fcallback%252525252525253Fcode%252525252525253DMV0Spb7eT_IS_nDCzp4FvMxZn316MdFu-c0Z17s0Tek%2525252525252526state%252525252525253DY_Ib-faiu1h_LYYbDviM2XBW-tuWhRlej_FvhTbeutg%25252525252525253A%25252525252525252Fauthorization-code%25252525252525252Fcallback%25252525252525253Fcode%25252525252525253DBQxOQmSQLoVR9nzqTG0R_mfuFgG3e--p9ANgtTxHxgA%252525252525252526state%25252525252525253DoArzQg10yioAH_bQuZa8j1phmbefQqnFmduwfoIXu1E%2525252525252525253A%2525252525252525252F","method":"GET","downstream_remote_address":"10.244.3.104:0","bytes_received":0,"request_id":"c244e5d0-8327-423f-857b-e9b3213bda38","duration":0,"requested_server_name":"outbound_.4180_._.oauth2-proxy.oauth2-proxy.svc.cluster.local","upstream_transport_failure_reason":null,"connection_termination_details":null,"x_forwarded_for":"10.244.3.104","start_time":"2022-07-14T21:24:01.615Z","bytes_sent":2413,"response_code_details":"via_upstream","authority":"home.xxx-yyy.com","downstream_local_address":"10.244.3.112:4180","response_flags":"-","response_code":302,"upstream_cluster":"inbound|4180||","user_agent":null,"upstream_host":"10.244.3.112:4180"}
{"upstream_host":"10.244.3.112:4180","x_forwarded_for":"10.244.3.104","bytes_sent":2413,"upstream_local_address":"127.0.0.6:51339","upstream_service_time":"0","response_flags":"-","downstream_remote_address":"10.244.3.104:0","path":"/authorization-code/callback?code=wZ_DjrshIgxskDeKFdzrohHPxjAko4PrnWvcx4emMNc&state=7Ij7ZUdxUB7QVvvOU3MR0umjXIpgs1wlMFX-hHnVmBs%3A%2Fauthorization-code%2Fcallback%3Fcode%3D00mBVPcGEoTsSnKEOfATymvUDLGtyqD9dD3zry2I9jQ%26state%3DnbC_n3ZfKIu2lP7nEuMbRkJ96OTrdknQUBZRjPjAmsU%253A%252Fauthorization-code%252Fcallback%253Fcode%253DQQsezdZQQIapSi1ijW-U08AwbPfajtHNtILBORs7SXM%2526state%253DFojmd2qqhAxkihKRou7Al1Zos_O7wnDyTldqH6dCpxA%25253A%25252Fauthorization-code%25252Fcallback%25253Fcode%25253DCluAs1Sknx5Aaplk_f7Wg7xQE77ikIGi0cofb7wpOp8%252526state%25253Dxz8ZVzeIPdbhMb4zQ6dfrzik45jBH6GWC8t4O4EHR3w%2525253A%2525252Fauthorization-code%2525252Fcallback%2525253Fcode%2525253DBIgmiwFrr3hrdrGt6iaYFmkPMzmbNoJMv7vjf-vNiRw%25252526state%2525253D3qtAHzxOxDOC2IkWe1WIKJ2T7N7nTUMrGRmGXqyhA1g%252525253A%252525252Fauthorization-code%252525252Fcallback%252525253Fcode%252525253DCn89754MmowAx2N5rCXq9n4rgVuniMgHSawGdJLQGQs%2525252526state%252525253D1RRWolW4pLFsouB_pPPU2mxAemh3FwRRDZN6tZclyx4%25252525253A%25252525252Fauthorization-code%25252525252Fcallback%25252525253Fcode%25252525253DOvT6jQNFV8obygZxwqM2-bEa9VQphPdDlfWxTvN_4DU%252525252526state%25252525253DIX5I12vcLweLS4tdyW0GII50MfgETC24s84sHE9PwCA%2525252525253A%2525252525252Fauthorization-code%2525252525252Fcallback%2525252525253Fcode%2525252525253D5m510mptPDd2_kZMkLroIpJeRSNULPDSURGgt0onpuQ%25252525252526state%2525252525253DRSZ006S832hKrYYTUjXIgbIklgza4jWpoo1oYx7K9IE%252525252525253A%252525252525252Fauthorization-code%252525252525252Fcallback%252525252525253Fcode%252525252525253DMV0Spb7eT_IS_nDCzp4FvMxZn316MdFu-c0Z17s0Tek%2525252525252526state%252525252525253DY_Ib-faiu1h_LYYbDviM2XBW-tuWhRlej_FvhTbeutg%25252525252525253A%25252525252525252Fauthorization-code%25252525252525252Fcallback%25252525252525253Fcode%25252525252525253DBQxOQmSQLoVR9nzqTG0R_mfuFgG3e--p9ANgtTxHxgA%252525252525252526state%25252525252525253DoArzQg10yioAH_bQuZa8j1phmbefQqnFmduwfoIXu1E%2525252525252525253A%2525252525252525252F","user_agent":null,"start_time":"2022-07-14T21:24:02.821Z","response_code":302,"upstream_cluster":"inbound|4180||","method":"GET","requested_server_name":"outbound_.4180_._.oauth2-proxy.oauth2-proxy.svc.cluster.local","route_name":"default","duration":0,"request_id":"5754e227-9261-4513-bd19-25ab780593b4","authority":"home.xxx-yyy.com","upstream_transport_failure_reason":null,"response_code_details":"via_upstream","downstream_local_address":"10.244.3.112:4180","protocol":"HTTP/1.1","bytes_received":0,"connection_termination_details":null}
{"upstream_local_address":"127.0.0.6:51339","protocol":"HTTP/1.1","bytes_received":0,"response_code_details":"via_upstream","bytes_sent":2699,"method":"GET","authority":"home.xxx-yyy.com","upstream_host":"10.244.3.112:4180","connection_termination_details":null,"x_forwarded_for":"10.244.3.104","duration":0,"downstream_local_address":"10.244.3.112:4180","request_id":"ebc8f929-34bc-4807-b01e-aad5fb334476","user_agent":null,"route_name":"default","downstream_remote_address":"10.244.3.104:0","upstream_service_time":"0","start_time":"2022-07-14T21:24:03.499Z","requested_server_name":"outbound_.4180_._.oauth2-proxy.oauth2-proxy.svc.cluster.local","path":"/authorization-code/callback?code=TGavX0lPiMcRhjXc93HvQbqnJany8-lqJwGQW5mYl1g&state=mAtnpgTM6DG3obhwDWu9zqA2n4hY5WDCrcAa5D9pQkk%3A%2Fauthorization-code%2Fcallback%3Fcode%3DwZ_DjrshIgxskDeKFdzrohHPxjAko4PrnWvcx4emMNc%26state%3D7Ij7ZUdxUB7QVvvOU3MR0umjXIpgs1wlMFX-hHnVmBs%253A%252Fauthorization-code%252Fcallback%253Fcode%253D00mBVPcGEoTsSnKEOfATymvUDLGtyqD9dD3zry2I9jQ%2526state%253DnbC_n3ZfKIu2lP7nEuMbRkJ96OTrdknQUBZRjPjAmsU%25253A%25252Fauthorization-code%25252Fcallback%25253Fcode%25253DQQsezdZQQIapSi1ijW-U08AwbPfajtHNtILBORs7SXM%252526state%25253DFojmd2qqhAxkihKRou7Al1Zos_O7wnDyTldqH6dCpxA%2525253A%2525252Fauthorization-code%2525252Fcallback%2525253Fcode%2525253DCluAs1Sknx5Aaplk_f7Wg7xQE77ikIGi0cofb7wpOp8%25252526state%2525253Dxz8ZVzeIPdbhMb4zQ6dfrzik45jBH6GWC8t4O4EHR3w%252525253A%252525252Fauthorization-code%252525252Fcallback%252525253Fcode%252525253DBIgmiwFrr3hrdrGt6iaYFmkPMzmbNoJMv7vjf-vNiRw%2525252526state%252525253D3qtAHzxOxDOC2IkWe1WIKJ2T7N7nTUMrGRmGXqyhA1g%25252525253A%25252525252Fauthorization-code%25252525252Fcallback%25252525253Fcode%25252525253DCn89754MmowAx2N5rCXq9n4rgVuniMgHSawGdJLQGQs%252525252526state%25252525253D1RRWolW4pLFsouB_pPPU2mxAemh3FwRRDZN6tZclyx4%2525252525253A%2525252525252Fauthorization-code%2525252525252Fcallback%2525252525253Fcode%2525252525253DOvT6jQNFV8obygZxwqM2-bEa9VQphPdDlfWxTvN_4DU%25252525252526state%2525252525253DIX5I12vcLweLS4tdyW0GII50MfgETC24s84sHE9PwCA%252525252525253A%252525252525252Fauthorization-code%252525252525252Fcallback%252525252525253Fcode%252525252525253D5m510mptPDd2_kZMkLroIpJeRSNULPDSURGgt0onpuQ%2525252525252526state%252525252525253DRSZ006S832hKrYYTUjXIgbIklgza4jWpoo1oYx7K9IE%25252525252525253A%25252525252525252Fauthorization-code%25252525252525252Fcallback%25252525252525253Fcode%25252525252525253DMV0Spb7eT_IS_nDCzp4FvMxZn316MdFu-c0Z17s0Tek%252525252525252526state%25252525252525253DY_Ib-faiu1h_LYYbDviM2XBW-tuWhRlej_FvhTbeutg%2525252525252525253A%2525252525252525252Fauthorization-code%2525252525252525252Fcallback%2525252525252525253Fcode%2525252525252525253DBQxOQmSQLoVR9nzqTG0R_mfuFgG3e--p9ANgtTxHxgA%25252525252525252526state%2525252525252525253DoArzQg10yioAH_bQuZa8j1phmbefQqnFmduwfoIXu1E%252525252525252525253A%252525252525252525252F","upstream_transport_failure_reason":null,"response_flags":"-","response_code":302,"upstream_cluster":"inbound|4180||"}
{"protocol":"HTTP/1.1","connection_termination_details":null,"route_name":"default","bytes_sent":2999,"upstream_service_time":"0","path":"/authorization-code/callback?code=TrreRXF0zsQWJLcIfXsV719hkVHijPoS2cGOWkvyPpM&state=7ht9gCTj6WuFgVHyY_yIMBTt54QcBzZGU02Rl1AU2Z8%3A%2Fauthorization-code%2Fcallback%3Fcode%3DTGavX0lPiMcRhjXc93HvQbqnJany8-lqJwGQW5mYl1g%26state%3DmAtnpgTM6DG3obhwDWu9zqA2n4hY5WDCrcAa5D9pQkk%253A%252Fauthorization-code%252Fcallback%253Fcode%253DwZ_DjrshIgxskDeKFdzrohHPxjAko4PrnWvcx4emMNc%2526state%253D7Ij7ZUdxUB7QVvvOU3MR0umjXIpgs1wlMFX-hHnVmBs%25253A%25252Fauthorization-code%25252Fcallback%25253Fcode%25253D00mBVPcGEoTsSnKEOfATymvUDLGtyqD9dD3zry2I9jQ%252526state%25253DnbC_n3ZfKIu2lP7nEuMbRkJ96OTrdknQUBZRjPjAmsU%2525253A%2525252Fauthorization-code%2525252Fcallback%2525253Fcode%2525253DQQsezdZQQIapSi1ijW-U08AwbPfajtHNtILBORs7SXM%25252526state%2525253DFojmd2qqhAxkihKRou7Al1Zos_O7wnDyTldqH6dCpxA%252525253A%252525252Fauthorization-code%252525252Fcallback%252525253Fcode%252525253DCluAs1Sknx5Aaplk_f7Wg7xQE77ikIGi0cofb7wpOp8%2525252526state%252525253Dxz8ZVzeIPdbhMb4zQ6dfrzik45jBH6GWC8t4O4EHR3w%25252525253A%25252525252Fauthorization-code%25252525252Fcallback%25252525253Fcode%25252525253DBIgmiwFrr3hrdrGt6iaYFmkPMzmbNoJMv7vjf-vNiRw%252525252526state%25252525253D3qtAHzxOxDOC2IkWe1WIKJ2T7N7nTUMrGRmGXqyhA1g%2525252525253A%2525252525252Fauthorization-code%2525252525252Fcallback%2525252525253Fcode%2525252525253DCn89754MmowAx2N5rCXq9n4rgVuniMgHSawGdJLQGQs%25252525252526state%2525252525253D1RRWolW4pLFsouB_pPPU2mxAemh3FwRRDZN6tZclyx4%252525252525253A%252525252525252Fauthorization-code%252525252525252Fcallback%252525252525253Fcode%252525252525253DOvT6jQNFV8obygZxwqM2-bEa9VQphPdDlfWxTvN_4DU%2525252525252526state%252525252525253DIX5I12vcLweLS4tdyW0GII50MfgETC24s84sHE9PwCA%25252525252525253A%25252525252525252Fauthorization-code%25252525252525252Fcallback%25252525252525253Fcode%25252525252525253D5m510mptPDd2_kZMkLroIpJeRSNULPDSURGgt0onpuQ%252525252525252526state%25252525252525253DRSZ006S832hKrYYTUjXIgbIklgza4jWpoo1oYx7K9IE%2525252525252525253A%2525252525252525252Fauthorization-code%2525252525252525252Fcallback%2525252525252525253Fcode%2525252525252525253DMV0Spb7eT_IS_nDCzp4FvMxZn316MdFu-c0Z17s0Tek%25252525252525252526state%2525252525252525253DY_Ib-faiu1h_LYYbDviM2XBW-tuWhRlej_FvhTbeutg%252525252525252525253A%252525252525252525252Fauthorization-code%252525252525252525252Fcallback%252525252525252525253Fcode%252525252525252525253DBQxOQmSQLoVR9nzqTG0R_mfuFgG3e--p9ANgtTxHxgA%2525252525252525252526state%252525252525252525253DoArzQg10yioAH_bQuZa8j1phmbefQqnFmduwfoIXu1E%25252525252525252525253A%25252525252525252525252F","duration":0,"request_id":"45396947-2e9a-45da-882e-46bf07ee610c","bytes_received":0,"downstream_remote_address":"10.244.3.104:0","authority":"home.xxx-yyy.com","upstream_cluster":"inbound|4180||","response_code_details":"via_upstream","user_agent":null,"requested_server_name":"outbound_.4180_._.oauth2-proxy.oauth2-proxy.svc.cluster.local","x_forwarded_for":"10.244.3.104","downstream_local_address":"10.244.3.112:4180","response_flags":"-","upstream_host":"10.244.3.112:4180","upstream_local_address":"127.0.0.6:51339","start_time":"2022-07-14T21:24:04.176Z","upstream_transport_failure_reason":null,"response_code":302,"method":"GET"}
```

here are log messages from oauth2-proxy container

```
2022/07/14 22:03:07] [oauthproxy.go:862] No valid authentication in request. Initiating login.
127.0.0.6 - dc3db0ca-4bc5-4d15-9516-b3a2ed84fb39 - - [2022/07/14 22:03:07] home.xxx-yyy.com GET - "/" HTTP/1.1 "" 302 323 0.000
127.0.0.6 - 4d79b084-fdc6-479c-b09b-5f53ad8dd260 - - [2022/07/14 22:03:09] 10.244.3.112:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.21+" 200 2 0.000
[2022/07/14 22:03:11] [oauthproxy.go:862] No valid authentication in request. Initiating login.
127.0.0.6 - 953b119d-079f-4ef9-a373-908f9a912ebf - - [2022/07/14 22:03:11] home.xxx-yyy.com GET - "/authorization-code/callback?code=ZO0J3W2XvThVGQD0PXIblQoWyjFyBKdveU54KtHWHGQ&state=c966ZEqB71_E9Xwj-XUCp1elcy_OLt-jpfpMM2dN0b4%3A%2F" HTTP/1.1 "" 302 469 0.000
[2022/07/14 22:03:12] [oauthproxy.go:862] No valid authentication in request. Initiating login.
127.0.0.6 - 28d02bb6-4654-4f5f-9dc1-3bb1bd93fb3e - - [2022/07/14 22:03:12] home.xxx-yyy.com GET - "/authorization-code/callback?code=rvIvYvdhcUaSadprLGTH47OB9ty0tsXascUdyy2p5c4&state=TgOI4C3TAV0Tq3G-0YQSQQ3e3erjfm_DIdpESlYmTZg%3A%2Fauthorization-code%2Fcallback%3Fcode%3DZO0J3W2XvThVGQD0PXIblQoWyjFyBKdveU54KtHWHGQ%26state%3Dc966ZEqB71_E9Xwj-XUCp1elcy_OLt-jpfpMM2dN0b4%253A%252F" HTTP/1.1 "" 302 629 0.000
127.0.0.6 - 7145e04a-150e-4149-8103-af47de1d786a - - [2022/07/14 22:03:12] 10.244.3.112:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.21+" 200 2 0.000
[2022/07/14 22:03:12] [oauthproxy.go:862] No valid authentication in request. Initiating login.
127.0.0.6 - ad9f7f85-7599-4daa-9fbb-3017493a2e2f - - [2022/07/14 22:03:12] home.xxx-yyy.com GET - "/authorization-code/callback?code=2EKLoyJsPt2zmOR7DTBBM4FnC-qiQsEesSLC1ThjKy8&state=cRX_9y4nEzIr_uGW78fc4PCvZo43SVyLLOnrkJxgP6A%3A%2Fauthorization-code%2Fcallback%3Fcode%3DrvIvYvdhcUaSadprLGTH47OB9ty0tsXascUdyy2p5c4%26state%3DTgOI4C3TAV0Tq3G-0YQSQQ3e3erjfm_DIdpESlYmTZg%253A%252Fauthorization-code%252Fcallback%253Fcode%253DZO0J3W2XvThVGQD0PXIblQoWyjFyBKdveU54KtHWHGQ%2526state%253Dc966ZEqB71_E9Xwj-XUCp1elcy_OLt-jpfpMM2dN0b4%25253A%25252F" HTTP/1.1 "" 302 803 0.000
[2022/07/14 22:03:13] [oauthproxy.go:862] No valid authentication in request. Initiating login.
127.0.0.6 - bc83a292-17e2-4510-be0e-3ade2788d3df - - [2022/07/14 22:03:13] home.xxx-yyy.com GET - "/authorization-code/callback?code=bihE9jnY994iLXhWwCnTHIuzk0yo59MJWt4MRwaasmY&state=H2b06H33TZ-UlABeNVpjtjxbdqMqA8n0SbdwllVqnoY%3A%2Fauthorization-code%2Fcallback%3Fcode%3D2EKLoyJsPt2zmOR7DTBBM4FnC-qiQsEesSLC1ThjKy8%26state%3DcRX_9y4nEzIr_uGW78fc4PCvZo43SVyLLOnrkJxgP6A%253A%252Fauthorization-code%252Fcallback%253Fcode%253DrvIvYvdhcUaSadprLGTH47OB9ty0tsXascUdyy2p5c4%2526state%253DTgOI4C3TAV0Tq3G-0YQSQQ3e3erjfm_DIdpESlYmTZg%25253A%25252Fauthorization-code%25252Fcallback%25253Fcode%25253DZO0J3W2XvThVGQD0PXIblQoWyjFyBKdveU54KtHWHGQ%252526state%25253Dc966ZEqB71_E9Xwj-XUCp1elcy_OLt-jpfpMM2dN0b4%2525253A%2525252F" HTTP/1.1 "" 302 991 0.000
```
## Context

We are trying to integrate with okta for external authorization for our web-apps. We want to use tokens in our downstream apps.

## Your Environment

k8s: 1.21 ( on-prem)
Istio: 1.14.1
oauth2-proxy container image: v7.2.0
os: centos7.9

- Version used: 7.2.0

Any help to troubleshoot this would be appreciated.
