### ISSUE TITLE
BUILDPLATFORM ARG empty for image build with docker-compose

### ISSUE THREAD

**Issue by fuchst** [oauth2-proxy/oauth2-proxy#1729]
Building an image with docker-compose fails because the **BUILDPLATFORM** ARG is empry for the call `FROM --platform=${BUILDPLATFORM} golang:1.17-buster AS builder` in the *Dockerfile* although it is specified in the *docker-compose.yml*.

```
ERROR: Service 'oauth2-proxy' failed to build: failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument
```

## Expected Behavior

An image of oauth2-proxy should be build.

## Current Behavior

It fails because **BUILDPLATFORM** is empty ("").

## Possible Solution

Move `ARG BUILDPLATFORM` to the top of the *Dockerfile*.

## Steps to Reproduce (for bugs)

1.  Checkout the git repository to *./oauth2-proxy*
2.  Create the docker-compose.yml
  ```
  version: "3"
  services:
    oauth2-proxy:
      build:
        context: ./oauth2-proxy
        dockerfile: Dockerfile
        args:
          VERSION: lucid_heisenberg
          TARGETPLATFORM: linux/amd64
          BUILDPLATFORM: linux/amd64
  ```
3. Build
  ```
  docker-compose build
  ``` 

## Your Environment

Ubuntu 20.04
Docker 20.10.7
Docker-Compose 1.25.0

- Version used: 7a784a460dbccad2fff4837cdad5a9fb414f971c
