### ISSUE TITLE
[Bug] OIDCOptions defaults not used

### ISSUE THREAD

**Issue by saswatac** [oauth2-proxy/oauth2-proxy#1732]
## Expected Behavior

Default values described in AlphaConfig documentation is used.

## Current Behavior

It appears that the default values described in  https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config#oidcoptions  are not used. I see the following error in the logs -

```
Error redeeming code during OAuth2 callback: could not verify id_token: audience claims [] do not exist in claims
```

To get the authorization working correctly, I had to explicitly specify the values of emailClaim, userIDClaim and audienceClaims to email, email and aud respectively

## Steps to Reproduce (for bugs)

Used the following alpha config - 

```
providers:
  - provider: oidc
    clientID: 
    clientSecret: 
    scope: openid profile email offline_access
    id: default
    oidcConfig:
      issuerURL: 
      extraAudiences:
        - test
      groupsClaim: org_id
    loginURLParameters:
      - name: organization
        default:
          - test
    allowedGroups:
      - test
server:
  BindAddress: 0.0.0.0:4180
```

## Context

I am migrating my deployment to use alpha configs in order to use the loginURLParameters feature.

## Your Environment

deployed in kubernetes. 

- Version used: latest docker image quay.io/oauth2-proxy/oauth2-proxy:latest

**Comment by JoelSpeed** [comment]
I think this is a known bug There's some issue with the way we are defaulting the alpha options and the passing that through to the providers. I believe the issue is in the provider code but haven't had a chance to investigate further

**Comment by newhorizs** [comment]
Hi @saswatac ,
I got the same issue when I tried to upgrade from version 7.2.1 to 7.3.0.
You said that you can make the authorization working correctly by specifying the values of emailClaim, userIDClaim and audienceClaims to email, email and aud.
But when I try to add **audienceClaims: aud** into alpha config, I still got that issue.
How could you make it works? Thanks !!

**Comment by dbg-raghulkrishna** [comment]
Hi  i am also having the same issue any fix on this?

**Comment by JoelSpeed** [comment]
No fix yet that I know of, if anyone has time to debug this and work out a fix I can try to find the time to review

**Comment by ataraxus** [comment]
Hey folks, had this issue just right now. I figured out what to do to get it working. It seems there are many default options missing. After setting these one can get it running: 

```
server:
  BindAddress: 0.0.0.0:4180
upstreamConfig:
  upstreams:
    - id: CLIENT
      uri: http://CLIENT:8000
      path: /

providers:
  - provider: keycloak-oidc
    id: keycloak
    clientSecret: REDACTED
    clientID: CLIENT
    oidcConfig:
      issuerURL: https://REDACTED/auth/realms/REDACTED
      extraAudiences: 
        - CLIENT
      audienceClaims:
        - aud
      emailClaim: email
      userIDClaim: email
    keycloakConfig:
      roles:
        - CLIENT:ROLE
    scope: "openid profile email"
injectRequestHeaders:
  - name: Remote-User
    values: 
      - claim: email
```

**Comment by JoelSpeed** [comment]
This hasn't been resolved yet, we need to find some time to resolve this, anyone got time to work up a PR?

**Comment by ataraxus** [comment]
Was this issue tackled, should i test the New Version? @JoelSpeed

**Comment by JoelSpeed** [comment]
I don't believe this has been fixed no, does anyone have the time to investigate this further and raise a PR?

**Comment by albert0815** [comment]
I think this is still an issue.

**Comment by JoelSpeed** [comment]
I believe this has been fixed in the latest release, have you tried v7.5.0 or v7.5.1?

**Comment by ivangonzalezacuna** [comment]
In our config we are currently adding the `audienceClaims` to be sure it works. We tested removing it again in the latest v7.5.1, but it doesn't work unfortunately.

**Comment by tuunit** [comment]
@ivangonzalezacuna can you share your latest config and envs you used to deploy v7.5.1?

**Comment by ivangonzalezacuna** [comment]
Sure @tuunit . We are currently using both the config and alpha config, because we needed an special header required by Backstage. This is the config we use:

```yaml
# oauth2-proxy.cfg

force_https = false

redirect_url = "http://localhost:3000/oauth2/callback"

email_domains = ["*"]

skip_provider_button = true

skip_auth_routes = [

  "^/ready",
  "^/metrics",

]

cookie_secret = <COOKIE_SECRET>
cookie_domains = "localhost"
cookie_expire = "1h"
cookie_secure = "true"
cookie_httponly = true
```

```yaml
# oauth2-proxy.yaml

# values for claim sources from here https://github.com/oauth2-proxy/oauth2-proxy/blob/433b93d08a3d4f87950b5d21b4cd0e8ae95c1a97/pkg/apis/options/legacy_options.go#L348 (there doesn't seem to be an official list)
injectRequestHeaders:
- name: X-Forwarded-Groups
  values:
  - claim: groups
- name: X-Forwarded-User
  values:
  - claim: user
- name: X-Forwarded-Email
  values:
  - claim: email
- name: X-Forwarded-Preferred-Username
  values:
  - claim: preferred_username
- name: X-Oauth2-Proxy-Id-Token
  values:
  - claim: access_token
    prefix: "Bearer "
metricsServer:
  BindAddress: ""
  SecureBindAddress: ""
  TLS: null
providers:
- clientID: backstage
  clientSecret: <CLIENT_SECRET>
  id: oidc=backstage
  oidcConfig:
    emailClaim: email
    groupsClaim: groups
    audienceClaims:
      - aud # should be the default, workaround for https://github.com/oauth2-proxy/oauth2-proxy/issues/1732
    insecureAllowUnverifiedEmail: true
    insecureSkipNonce: true
    issuerURL: <ISSUER_URL>
    userIDClaim: email
  allowedGroups:
  - "backstage-group"
  provider: oidc
  scope: openid
  caFiles:
  - <CRT_FILE>
  code_challenge_method: 'S256'
server:
  BindAddress: 0.0.0.0:3000
  SecureBindAddress: ""
  TLS: null
upstreamConfig:
  upstreams:
  - flushInterval: 1s
    id: /
    passHostHeader: true
    path: /
    proxyWebSockets: true
    uri: http://localhost:7007

```

And it's executed with docker compose:

```
  oauth2-proxy:
    image: oauth2-proxy/oauth2-proxy:v7.5.1-amd64
    command: "oauth2-proxy --alpha-config /app/oauth2-proxy.yaml --config /app/oauth2-proxy.cfg"
    volumes:
      - "./dev/oauth2-proxy.cfg:/app/oauth2-proxy.cfg"
      - "./dev/oauth2-proxy.yaml:/app/oauth2-proxy.yaml"
      - <OUR_CERT_FILE>
    # oauth2-proxy needs to use the host network to be able to proxy to the
    # local backstage instance running outside of docker
    network_mode: host

```
