### ISSUE TITLE
No valid authentication in callback, stuck in auth loop

### ISSUE THREAD

**Issue by LP0101** [oauth2-proxy/oauth2-proxy#1733]
## Expected Behavior

1. Ambassador (my ingress) redirects me to the oauth2-proxy service
2. Oauth flow happens, I get a callback from Azure
3. Ambassador redirects the callback to oauth2-proxy
4. Oauth2-proxy lets me into my app

## Current Behavior

1. Ambassador redirects me to the oauth2-proxy service
2. Oauth flow happens, I get a callback URL
3. Ambassador redirects the callback URL to oauth2 proxy
4. Oauth2 proxy takes the full callback URL and initiates a new oauth flow with azure, using the full callback URL as the state
5. Repeat steps 3 and 4 until the loop breaks due to the query string being too long

Logs:

Example of the login loop in Chrome dev tools: 
![image](https://user-images.githubusercontent.com/16864921/179606692-90d767b3-4fe4-4c6b-b7b1-7884c7a2bf3c.png)

Ambassador output:
https://gist.github.com/LP0101/91abebf218c6ccecbcffd5fea689ceaa

oauth2-proxy output:
https://gist.github.com/LP0101/b1771c8b78bcd873dc95bbd427c97d38

## Possible Solution

It seems the issue might be caused by oauth2-proxy failing to set a cookie to maintain the session. I'm not sure if that's it, but the only cookie stored by the time it breaks is the csrf cookie.

## Steps to Reproduce (for bugs)

Ambassador mapping:
```
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: oauth2_mapping_ingress-controllers
      ambassador_id: ambassador-internal
      prefix: /oauth2/
      service: oauth2-proxy.ingress-controllers
      timeout_ms: 60000
      bypass_auth: true
    meta.helm.sh/release-name: oauth2-proxy
    meta.helm.sh/release-namespace: ingress-controllers
```

Ambassador authservice:
```
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
  namespace: ingress-controllers
spec:
  ambassador_id:
  - ambassador-internal
  auth_service: oauth2-proxy.ingress-controllers
  path_prefix: ""
  proto: http
  tls: false
```

oauth2-proxy args:
```
  - args:
    - --http-address=0.0.0.0:4180
    - --metrics-address=0.0.0.0:44180
    - --auth-logging=true
    - --email-domain=*
    - --oidc-issuer-url=https://sts.windows.net/<TENET_ID>/
    - --pass-access-token=true
    - --pass-authorization-header=true
    - --provider=azure
    - --proxy-prefix=/oauth2
    - --request-logging=true
    - --reverse-proxy=true
    - --scope=openid
    - --set-authorization-header=true
    - --show-debug-on-error=true
    - --silence-ping-logging=true
    - --skip-provider-button=true
    - --ssl-upstream-insecure-skip-verify
    - --standard-logging=true
    - --upstream=static://200
 ```

## Your Environment

- Version used: 7.2, 7.3, 5.1, all run through the helm chart

Environment is Kubernetes on AKS, running Ambassador 1.4.4 for ingress

**Comment by LP0101** [comment]
Looks like this issue was resolved by fixing the ambassador mapping. It was stripping out the `/oauth2` from the path that was sent to the `oauth2-proxy` service

**Comment by jonathandavis805** [comment]
Could you help explain how this was resolved? We're running into the same issue with an Nginx ingress controller where it continuously calls to oauth/start until it says too many redirects

**Comment by woohgit** [comment]
@jonathandavis805 It happens to me as well, any updates on your side?

**Comment by jonathandavis805** [comment]
Yes, we ended up with this config.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=google
            - --tls-cert-file=/etc/nginx/ssl/tls.crt
            - --tls-key-file=/etc/nginx/ssl/tls.key
            - --cookie-secure=false
            - --upstream=https://ingress-nginx-controller.ingress-nginx.svc.cluster.local:443/
            - --redirect-url=https://example.domain.com/oauth2/callback
            - --scope=openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
            - --reverse-proxy=true
            - --force-https=true
            - --cookie-refresh=120m
            - --oidc-issuer-url=https://accounts.google.com
            - --skip-jwt-bearer-tokens=true
            - --pass-access-token=true
            - --set-authorization-header=true
            - --set-xauthrequest=true
            - --cookie-domain=example.domain.com
            - --cookie-samesite=lax
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: google-app
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: google-app
            # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value:A_Random_Base64_String
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: tls-files
              mountPath: /etc/nginx/ssl
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: tls-files
          secret:
            secretName: example-app-tls
---

apiVersion: v1
kind: Service
metadata:
  labels:
  name: oauth2-proxy
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    k8s-app: oauth2-proxy
```
and Nginx ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - example.domain.com
    secretName: example-app-tls
  rules:
    - host: example.domain.com
      http:
        paths:
        - path: /endpoint
          pathType: Prefix
          backend:
            service:
              name: web-service
              port:
                number: 443
        - path: /another-endpoint
          pathType: Prefix
          backend:
            service:
              name: another-web-service
              port:
                number: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - example.domain.com
      secretName: example-app-tls
  rules:
    - host: example.domain.com
      http:
        paths:
          - path: /oauth2
            pathType: ImplementationSpecific
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 443
```
We're running AWS EKS 1.21 with Cert-Manager creating the https certs so everything's over 443
