### ISSUE TITLE
CSRF validation fails (missing cookie) when user has bookmarked Keycloak login page

### ISSUE THREAD

**Issue by johnswarbrick** [oauth2-proxy/oauth2-proxy#1736]
We have successfully integrated oauth2_proxy with Keycloak using the keycloak-oidc provider. Users visiting our application are redirected to Keycloak for authentication and after being redirected back to our application they have access.

The problem is when a user bookmarks the Keycloak login page and then subsequently uses that bookmark they receive a "403 Forbidden - Login Failed: Unable to find a valid CSRF token. Please try again." message from oauth2_proxy.

This is because the previous CSRF cookie has been expired and no new CSRF cookie was set therefore authentication fails. But I don't know how to avoid this situation.

The successful authentication browser flow looks like this:

1. GET / on our application which determines no valid session
2. Our application 302 redirects to /oauth2/start 
3. GET /oauth2/start on oauth2_proxy which determines no valid session
4. _oauth2_proxy sets CSRF cookie with 7 day expiry_ and 302 redirects to Keycloak /auth/realms/<realm>/protocol...
5. Keycloak present the login page **and the user bookmarks this page**
6. After successful authentication Keycloak 302 redirects to /oauth2/callback
7. oauth2_proxy validates the session and the CSRF cookie
8. _oauth2_proxy updates the CSRF cookie to an immediate expiry_
9. oauth2_proxy 302 redirects back to our application /
10. GET / on our application determines valid session and grants access

The failure scenario with the bookmarked Keycloak login page looks like this:

1. User selects the bookmarked Keycloak login page from step (5) above
2. _No old CSRF cookie is present because it was previously expired in step (8) above_
3. _No new CSRF cookie is set because they have not visited /oauth2/start first_
4. After successful authentication Keycloak 302 redirects to /oauth2/callback
5. oauth2_proxy validates the session and the CSRF cookie which fails because the CSRF cookie is not set
6. "403 Forbidden - Login Failed: Unable to find a valid CSRF token" error message is displayed

I don't know how to avoid users bookmarking the Keycloak login page because whenever they visit the application domain they are always redirected to Keycloak.

As far as I know there is no way of configuring Keycloak to redirect to /oauth2/start if the oauth2_proxy CSRF cookie is not present.

And I don't know if it's possible to disable the CSRF check in oauth2_proxy?

Version: 7.2.0

```
extraArgs:
  reverse-proxy: false
  provider: keycloak-oidc
  cookie-name: oauth2-proxy
  request-logging: true
  pass-access-token: true
  set-xauthrequest: true
  skip-jwt-bearer-tokens: true
  skip-auth-route: .*/api/token
  insecure-oidc-allow-unverified-email: true

extraEnv:
- name: OAUTH2_PROXY_REDIRECT_URL
  value: https://<our_domain>/oauth2/callback
- name: OAUTH2_PROXY_OIDC_ISSUER_URL
  value: https://<our_domain>/auth/realms/<our_realm>
```
