### ISSUE TITLE
Activating cookie-secure leads to 404 error on subdomain redirect

### ISSUE THREAD

**Issue by karlschriek** [oauth2-proxy/oauth2-proxy#1754]
## Expected Behavior

I would expect that with the following setup, redirects to a the root domain https://mydomain.com/oauth2/callback, as well as to a subdomain  https://foo.mydomain.com/oauth2/callback would both work:

```yaml
  OAUTH2_PROXY_COOKIE_DOMAINS: .mydomain.com,mydomain.com
  OAUTH2_PROXY_WHITELIST_DOMAINS: .mydomain.com,mydomain.com
  OAUTH2_PROXY_COOKIE_SECURE: 'true'
```

## Current Behavior

Instead, it works for https://mydomain.com/oauth2/callback, but for https://foo.mydomain.com/oauth2/callback I get a 404 error.

The following is my oauth2-proxy configuration:

```yaml
  OAUTH2_PROXY_COOKIE_DOMAINS: .mydomain.com,mydomain.com
  OAUTH2_PROXY_COOKIE_SECURE: 'true'
  OAUTH2_PROXY_EMAIL_DOMAINS: '*'
  OAUTH2_PROXY_ERRORS_TO_INFO_LOG: 'true'
  OAUTH2_PROXY_FORCE_HTTPS: 'false'
  OAUTH2_PROXY_HTTP_ADDRESS: http://:4180
  OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: 'true'
  OAUTH2_PROXY_OIDC_ISSUER_URL: https://login.mydomain.com
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
  OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: 'true'
  OAUTH2_PROXY_PASS_HOST_HEADER: 'true'
  OAUTH2_PROXY_PASS_USER_HEADERS: 'true'
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_SCOPE: email profile openid
  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: 'true'
  OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
  OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: 'false'
  OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY: 'false'
  OAUTH2_PROXY_UPSTREAMS: static://200
  OAUTH2_PROXY_WHITELIST_DOMAINS: .mydomain.com,mydomain.com
```

I am using this in conjunction with Istio, with the `envoyExtAuthzHttp` extension provider that kicks off an authentication flow via oauth2-proxy. With the includeAdditionalHeadersInCheck parameter we are passing the original HOST/PATH to redirect back to.
```
envoyExtAuthzHttp:
    ...
    includeAdditionalHeadersInCheck:
      X-Auth-Request-Redirect: https://%REQ(Host)%%REQ(:PATH)%
```

As identity provider we run Identity Server on the same cluster, under https://login.mydomain.com.

The setup as above yields the following:

**_this works_** (i.e. on mydomain.com)

`https://mydomain.com/oauth2/callback?code=9E8..1&scope=email profile openid&state=xM..o:https://mydomain.com/foobar&session_state=of..E&iss=https://login.mydomain.com`

**_this fails_** (i.e. on foo.mydomain.com), i.e. it thows a 404 on the following request:

`https://foo.mydomain.com/oauth2/callback?code=BB...04BA-1&scope=email profile openid&state=M2..BY:https://foo.mydomain.com/foobaz&session_state=Kb...BA&iss=https://login.mydomain.com`

If I set `OAUTH2_PROXY_COOKIE_SECURE: 'false'`, both of them work

- Version used: `v7.2.0`

**Comment by karlschriek** [comment]
As a bit more context, we have the following TLS certificates, i.e. mydomain.com and login.mydomain.com are on the same cert. But foo.mydomain.com is on a separate cert. This is the only reason I can think of why callbacks to mydomain.com work while ones to foo.mydomain.com do not.


```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway
spec:
  commonName: mydomain.com
  dnsNames:
    - mydomain.com
    - login.mydomain.com
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: istio-gateway-cert
```
  
  
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-foo  
spec:
  commonName: foo.mydomain.com
  dnsNames:
    - foo.mydomain.com
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: istio-gateway-foo-cert
```
