### ISSUE TITLE
oauth2-proxy with Keycloak

### ISSUE THREAD

**Issue by allanian** [oauth2-proxy/oauth2-proxy#1756]
Hello, can you help me to understand how its should working,

i done with that steps:
1) Keycloak:
Configure the client
| Option | Value |
| ------ | ------ | 
| Client ID | oauth2-proxy 
| Client Protocol | openid-connect |
| Access type | confidential | 
| Valid Redirect URIs | http://10.3.3.182:4180/oauth2/callback |

Mappers:
| Option | Value | 
| ------ | ------ | 
| Protocol| openid-connect | 
| Name | groups |  
| Mapper Type | Group Membership | 
| Token Claim Name | groups | 
| Full group path | OFF |  

| Option | Value | 
| ------ | ------ | 
| Name | Audience |
| Mapper type  | Audience | 
| Included Client Audience  | oauth2-proxy | 
| Included Custom Audience  | oauth2-proxy | 
| Add to access token | true | 

2) k8s dashboard with ingress config:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-dashboard-kubernetes-dashboard
  namespace: infra-k8s-dashboard
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: http://10.3.3.182:4180/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://10.3.3.182:4180/auth
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
spec:
  ingressClassName: nginx
  rules:
    - host: k8s-dash-prod.sheon.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: k8s-dashboard-kubernetes-dashboard
                port:
                  number: 443
```

3) OAUTH-PROXY
```
/tmp/oauth2-proxy-v7.3.0.linux-amd64/oauth2-proxy \
    --http-address=0.0.0.0:4180 \
    --provider=keycloak-oidc \
    --client-id=oauth2-proxy \
    --client-secret=7aacad18-d003-4439-a5f5-0bec7bc4a90d \
    --cookie-secret=ZUNoRTFGZE1BdmVtR3hCWkY5ZFAxZklsZ2tlL2pmTmg= \
	--redirect-url=http://10.3.3.182:4180/oauth2/callback \
	--upstream=https://k8s-dash-prod.sheon.com \
	--oidc-issuer-url=https://keycloak.sheon.com/auth/realms/sheon \
	--ssl-insecure-skip-verify=true \
    --set-authorization-header=true \
	--scope=openid profile email  \
	--allowed-group=kubernetes-admin \
	--oidc-groups-claim=groups \
	--oidc-email-claim=email \
	--email-domain=* \
    --insecure-oidc-allow-unverified-email=true \
	--cookie-secure=false
```
4) go to the url of oauth2-proxy and click to auth with keycloak, its revert with 403
http://10.3.3.182:4180

```
and i getting
404 Not Found
nginx

logs:
172.16.20.49:65436 - 069954a3-8d34-4ec9-8608-14adb857f761 - testk8suser@sheon.com [2022/08/12 12:20:18] [AuthSuccess] Authenticated via OAuth2: Session{email:testk8suser@sheon.com user: PreferredUsername:46653 token:true id_token:true created:2022-08-12 12:20:18.624909826 +0300 MSK m=+7.569053215 expires:2022-08-12 12:25:18.6228797 +0300 MSK m=+307.567022521 refresh_token:true groups:[JunyperUsers awx_admin_users Vault_Group kubernetes-admin AIRFLOW awx_users syspass_users jira_users_group role:offline_access role:uma_authorization role:default-roles-sheon role:account:manage-account role:account:manage-account-links role:account:view-profile]}
[2022/08/12 12:20:18] [session_store.go:163] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.
172.16.20.49:65436 - 069954a3-8d34-4ec9-8608-14adb857f761 - - [2022/08/12 12:20:18] 10.3.3.182:4180 GET - "/oauth2/callback?state=7RKdgwX0Sb2mAtc6VOiKewqy1Ek2SurGnXAcXThOW_I%3A%2F&session_state=8086877b-7407-4ef9-b304-48edd52b3e4a&code=c7ce66b6-745a-4853-94c7-4501baefc3b0.8086877b-7407-4ef9-b304-48edd52b3e4a.5e83da57-382e-46bb-94ff-dd3cd2f5671c" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" 302 24 0.009
172.16.20.49:65436 - 255cb0f1-6357-4325-92f3-b43178fa7aee - testk8suser@sheon.com [2022/08/12 12:20:18] 10.3.3.182:4180 GET / "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" 404 548 0.002
```
