### ISSUE TITLE
oauth2-proxy + Azure AD - headers not passed to app

### ISSUE THREAD

**Issue by rickrain** [oauth2-proxy/oauth2-proxy#1767]
Authenticated user headers are not flowing through to my web application running in AKS. The authentication is working perfectly, however, no response headers are reaching my application. I've tried using Edge, Chrome, and Firefox developer tools to view the headers and the only response headers I see are `content-type`, `date`, and `strict-transport-security`.

Azure AD App Registration is configured for ID tokens and optional claims `email`, `given_name`, and `family_name`.

I have tried several configurations based on posts from other users but just cannot find the right combination of switches and annotations to get what I'm after.

## Ingress - Web Application

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Forwarded-Access-Token
spec:
  rules:
    - host: webapp.xx.xx.xx.xx.sslip.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 80
  tls:
  - hosts:
    - webapp.xx.xx.xx.xx.sslip.io
    secretName: webapp-tls-secret
```

## Ingress - oauth2-proxy
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  rules:
  - host: webapp.xx.xx.xx.xx.sslip.io
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
  tls:
  - hosts:
    - webapp.xx.xx.xx.xx.sslip.io
    secretName: webapp-tls-secret
```

## oauth2-proxy deployment & service
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=https://webapp.xx.xx.xx.xx.sslip.io
        - --http-address=0.0.0.0:4180
        - --pass-access-token=true
        - --skip-provider-button=false
        - --session-store-type=redis
        - --set-xauthrequest=true
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --redis-connection-url=redis://redis-master.default.svc.cluster.local:6379
        - --redirect-url=https://webapp.xx.xx.xx.xx.sslip.io/oauth2/callback
        - --login-url=https://login.microsoftonline.com/__TENANT_ID__/oauth2/v2.0/authorize
        - --redeem-url=https://login.microsoftonline.com/__TENANT_ID__/oauth2/v2.0/token
        - --oidc-issuer-url=https://login.microsoftonline.com/__TENANT_ID__/v2.0
        - --oidc-jwks-url=https://login.microsoftonline.com/__TENANT_ID__/discovery/v2.0/keys
        - --scope=openid profile email
        - --pass-user-headers=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: xxxxxxxxxxxxxxxxxxxxxxxxxx
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: xxxxxxxxxxxxxxxxxxxxxxxxxx
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: xxxxxxxxxxxxxxxxxxxxxxxxxx
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
```

**Comment by rickrain** [comment]
Came back to this after a few days and managed to get this working.  Below is the complete configuration.  Hope it can be helpful to others.

## Ingress - Web Application

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Authorization $token;
        auth_request_set $token $upstream_http_authorization;
        add_header Authorization $token;
spec:
  rules:
    - host: webapp.xx.xx.xx.xx.sslip.io
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 80
  tls:
  - hosts:
    - webapp.xx.xx.xx.xx.sslip.io
    secretName: webapp-tls-secret
```

## Ingress - oauth2-proxy
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  rules:
  - host: webapp.xx.xx.xx.xx.sslip.io
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
  tls:
  - hosts:
    - webapp.xx.xx.xx.xx.sslip.io
    secretName: webapp-tls-secret
```

## oauth2-proxy deployment & service
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=https://webapp.xx.xx.xx.xx.sslip.io
        - --http-address=0.0.0.0:4180
        - --pass-access-token=true
        - --skip-provider-button=false
        - --session-store-type=redis
        - --set-xauthrequest=true
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --redis-connection-url=redis://redis-master.default.svc.cluster.local:6379/0
        - --redirect-url=https://webapp.xx.xx.xx.xx.sslip.io/oauth2/callback
        - --login-url=https://login.microsoftonline.com/__TENANT_ID__/oauth2/v2.0/authorize
        - --redeem-url=https://login.microsoftonline.com/__TENANT_ID__/oauth2/v2.0/token
        - --oidc-issuer-url=https://login.microsoftonline.com/__TENANT_ID__/v2.0
        - --oidc-jwks-url=https://login.microsoftonline.com/__TENANT_ID__/discovery/v2.0/keys
        - --scope=openid profile email
        - --pass-user-headers=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: xxxxxxxxxxxxxxxxxxxxxxxxxx
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: xxxxxxxxxxxxxxxxxxxxxxxxxx
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: xxxxxxxxxxxxxxxxxxxxxxxxxx
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
```
