### ISSUE TITLE
diffrent domain can not get the right url

### ISSUE THREAD

**Issue by easayliu** [oauth2-proxy/oauth2-proxy#1777]
## Possible Solution

it`s like a csrf.
`oauth2-proxy.example.com`
```
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.example.comt/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.example.com/oauth2/auth
```
ingress host is `app.example.net`

the log 
```
172.22.105.118:52008 - 0e2d8bd37a752af06510a3a241f042f6 - - [2022/09/01 02:18:06] oauth2-proxy.example.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" 401 13 0.000

<br class="Apple-interchange-newline">
```

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Context
any solution here?
looked all the closed issues, all of thme did not help me solution this.

## Your Environment

- Version used: v7.3.0

**Comment by lknite** [comment]
did it prompt you to log in?  what are you using as your identity provider?  dex?  keycloak?  azure?  oidc?

**Comment by easayliu** [comment]
> did it prompt you to log in? what are you using as your identity provider? dex? keycloak? azure? oidc?

keycloak.
use samesite ,it is worked.
diff side,return 401 code.

**Comment by lknite** [comment]
there is an oauth2-proxy provider 'keycloak-oidc' and also 'oidc'.  If you are using 'keycloak-oidc' try using 'oidc' instead.
```
      # in this case oauth2-proxy is going to visit
      oidc_issuer_url="https://keycloak.vc-prod.k.home.net/auth/realms/home"
      provider="oidc"
      provider_display_name="Keycloak"

      #
      insecure_oidc_allow_unverified_email="true"

      #
      set_authorization_header="true"
```

**Comment by lknite** [comment]
an older example:
https://github.com/oauth2-proxy/oauth2-proxy/issues/1617

**Comment by easayliu** [comment]
> there is an oauth2-proxy provider 'keycloak-oidc' and also 'oidc'. If you are using 'keycloak-oidc' try using 'oidc' instead.
> 
> ```
>       # in this case oauth2-proxy is going to visit
>       oidc_issuer_url="https://keycloak.vc-prod.k.home.net/auth/realms/home"
>       provider="oidc"
>       provider_display_name="Keycloak"
> 
>       #
>       insecure_oidc_allow_unverified_email="true"
> 
>       #
>       set_authorization_header="true"
> ```

it not works...
and the samesite has been same problem.
```
email_domains = [ "*" ]

upstreams = [ "file:///dev/null" ]

# provider = "keycloak-oidc"

oidc_issuer_url = "https://keycloak.xx.com/auth/realms/xx"

insecure_oidc_allow_unverified_email = true

whitelist_domains = [ "xx.com" ]

cookie_domains = [ ".xx.com" ]

silence_ping_logging = true

redirect_url = "https://oauth2-proxy.xx.com/oauth2/callback"

provider="oidc"

provider_display_name="Keycloak"

set_authorization_header="true"
```

**Comment by easayliu** [comment]
> there is an oauth2-proxy provider 'keycloak-oidc' and also 'oidc'. If you are using 'keycloak-oidc' try using 'oidc' instead.
> 
> ```
>       # in this case oauth2-proxy is going to visit
>       oidc_issuer_url="https://keycloak.vc-prod.k.home.net/auth/realms/home"
>       provider="oidc"
>       provider_display_name="Keycloak"
> 
>       #
>       insecure_oidc_allow_unverified_email="true"
> 
>       #
>       set_authorization_header="true"
> ```

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
  name: external-auth-oauth2
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: __INGRESS_HOST__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 80
---
this is ingress example.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - host: __INGRESS_HOST__
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
  tls:
  - hosts:
    - __INGRESS_HOST__
    secretName: __INGRESS_SECRET__
```
my example
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://__OAUTH_HOST__/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://__OAUTH_HOST__/oauth2/start?rd=$escaped_request_uri"
  name: external-auth-oauth2
  namespace: example
spec:
  ingressClassName: nginx
  rules:
  - host: __INGRESS_HOST__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 80
  tls:
  - hosts:
    -  __INGRESS_HOST__
    secretName: __INGRESS_SECRET__              
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  ingressClassName: nginx
  rules:
  - host: __OAUTH_HOST__
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
  tls:
  - hosts:
    - __OAUTH_HOST__
    secretName: __OAUTH_SECRET__
```

when i auth success, it rewrite to __OAUTH_HOST__ which means `upstreams = [ "file:///dev/null" ]`
if i used auth ,it works on right way, or it will rewrite to oauth_proxy_host upstreams.
