### ISSUE TITLE
[AuthFailure] with JWT when using a non-default OIDC groups claim

### ISSUE THREAD

**Issue by Hellzed** [oauth2-proxy/oauth2-proxy#1779]
## Context

I am using [GitLab SaaS](https://gitlab.com/) as an OIDC provider with OAuth2-Proxy.
Login is restricted to members of GitLab groups.

**Update:**
I originally forgot to mention the JWT are generated by a different "application" on GitLab, and I use `--extra-jwt-issuers https://gitlab.com=<application ID>` to allow using these ID tokens.

**Update:**
I'm actually hit by this issue as discussed by @NickMeves and the pull request author: https://github.com/oauth2-proxy/oauth2-proxy/pull/1242/files#r654730753 
Also why does this work when using alpha configuration ? Is the middleware chain handling JWTs built differently?

## Expected Behavior

For reference, with the same provider configuration, JWTs work for `--provider gitlab` and `--provider oidc` *when no group restrictions are set*.
I exepect to be able to generate JWT ID tokens (with a custom groups claim) and use them as `Bearer` tokens accepted by OAuth2-Prox to access the upstream service (when groups match).

## Current Behavior

In-browser sessions work just fine, but access is denied with `HTTP 403` code when using a JWT as `Bearer` token with a custom groups claim.

I have tried the following OAuth2-Proxy settings, with the same result:
- `--provider gitlab` with `--gitlab-group my-group`
- `--provider oidc` with `--allowed-group my-group` and `--oidc-groups-claim groups_direct` (as GitLab sets this specific group claim)

In OAuth2-Proxy logs, I find the following: `[AuthFailure] Invalid authorization via session: removing session {info, no groups...}`

**Update:**
I found a workaround: when using `--alpha-config`, omitting `--extra-jwt-issuers https://gitlab.com=<application ID>`, but using the alpha configuration key `alphaConfig.configData.providers[0].oidcConfig.extraAudiences: [<application ID>]`, OAuth2 Proxy behaves as expected and JWT from this app are accepted (groups are applied to the session even if not in a "groups" claim).

## Possible Solution

This [commit](https://github.com/oauth2-proxy/oauth2-proxy/commit/a392cc109880758c97fd899ad453b4ff7ea91026) adds groups to a session created from a JWT token.
Unfortunately, the "groups" key is hardcoded.
Instead, `CreateTokenToSessionFunc` should use the provider config to parse the ID token and extract groups from the appropriate claim.

I'm not familiar with go, but I'm willing to give this a try. Would it be considered better practice to add pass provider config to `CreateTokenToSessionFunc`, or create a different implementation within the OIDC provider?

## Steps to Reproduce (for bugs)

Use an OIDC provider with a groups claim that is not "groups", and try to use JWT to access the upstream of an OAuth2-Proxy instance.

## Your Environment

- Version used: 7.3.0

**Comment by JoelSpeed** [comment]
You seem to have self helped a lot here. I think the extra audiences workaround you've found is what I'd recommend. We intend going forward to drop the extra jwt issuers options in favour of just using multiple providers. In that world, the extra audiences is the option you need

**Comment by Hellzed** [comment]
Thank you for conforming this. Should this issue remain open until OAuth2 Proxy v8 is released?

I'm also still curious as to why, when using alpha config, the JWT middleware behaves differently.

**Comment by JoelSpeed** [comment]
> I'm also still curious as to why, when using alpha config, the JWT middleware behaves differently.

Does it? In theory the conversion from the old to alpha config should preserve the behaviour so perhaps there's a bug in it.

**Comment by Hellzed** [comment]
With the old config, the OIDC groups seems to [always be from the JWT "groups" claim](https://github.com/oauth2-proxy/oauth2-proxy/pull/1242/files#diff-84dc7de2b2111fe29c5f145a3396d0e26874cdd70872131494b7e783389e4d4eR29).

**Comment by eloo** [comment]
@Hellzed can you maybe share the config you are now using? 

for me its still not working with the alpha config :( 

currently my config looks like this 
```
    providers:
    - clientId: CLIENTID
      clientSecretFile: /etc/oidc/clientSecret
      id: default
      allowedGroups:
        - my-group
      oidcConfig:
        groupsClaim: https://****/groups
        issuerURL: https://****/
        audienceClaims:
          - aud
        extraAudiences: 
          - CLIENTID
        emailClaim: email
        userIDClaim: email
      provider: oidc
      profileUrl: https://****/userinfo
      scope: openid profile email offline_access groups
```

but with the allowedGroups its still not working and i get 403..
without allowedGroups its workings.. 

so the same as with the old config style
