### ISSUE TITLE
BUG: Error while loading cookied session from redis

### ISSUE THREAD

**Issue by EinavDanielDX** [oauth2-proxy/oauth2-proxy#1784]
## Current Behavior
Oauth2 Proxy fails to load the redis session with the following error, after few minutes idle:
`[2022/09/04 10:11:42] [stored_session.go:94] Error loading cookied session: failed to load the session state with the ticket: error loading redis session: redis: nil, removing session`

When it happens, oauth2 proxy acts as if the user is not logged on and initiates another `/oauth2/start` cycle.
The main issue here is it may happen while triggering a POST/UPDATE http request by clicking a button - then the request is being redirected (multiple times) to finish the log-in process, by doing that it loses its request body, and the method is being changed to GET.

## Expected Behavior
oauth2 session should live for as long as indicated in "--cookie-expire" flag, and not initiate new /oauth2/start unless cookie is deleted or expired.
oauht2 proxy session should always be found on its paired redis.

## Steps to Reproduce (for bugs)
It happens in any of our environments

### Components versions
Whole stack (web-app, ouath2-proxy and redis) are deployed using kubernetes:
Kubernetes -  v1.21
Redis - v6.2.6
Oauth2-Proxy - v7.3.0
Oauth provider - keycloak v18.0.1
helm-chart - [v6.2.2](https://github.com/oauth2-proxy/manifests/tree/main/helm/oauth2-proxy)

### Configuration
oauth2 configmap:
```
cookie_secure = true
cookie_samesite = "lax"
cookie_expire = "2160h0m0s"
cookie_refresh = "0h10m0s"
cookie_name = "myapp-dev_session"
cookie_domains = "my.dev.domain,dashboards-my.dev.domain"
```

oauth2 chart settings:
```
oauth2:
  redis:
    enabled: true
    fullnameOverride: my-env-redis
    replica:
      replicaCount: 0
    auth:
      enabled: false
    cluster:
      enabled: false
      slaveCount: 1
  sessionStorage:
    type: redis
    redis:
      standalone:
        connectionUrl: "redis://my-env-redis-headless:6379"
```
