### ISSUE TITLE
OpenID Connect Client ID displayed as XXXXXXX

### ISSUE THREAD

**Issue by eokorieFA** [oauth2-proxy/oauth2-proxy#1819]
Hi,

Thanks for this package.  I have managed to successfully implemented large parts of this package into a project I am working on.  I am however coming across a bit of a weird issue.  When checking  the pod logs for oauth2-proxy on AKS, I am getting the following:

`[2022/10/07 11:10:39] [oauthproxy.go:156] OAuthProxy configured for OpenID Connect Client ID: XXXXXXX`

I would have assumed the above would display client id for the application I am trying tio authenticate with.

This is my current  config for oauth2-prioxy:
```
resource "helm_release" "oauth2-proxy" {
  name        = "${var.cluster_name}-oauth2-proxy"
  chart       = "oauth2-proxy"
  namespace   = kubernetes_namespace.oauth2-proxy.metadata.0.name
  repository  = "https://oauth2-proxy.github.io/manifests"

  values = [ <<EOF
extraArgs:
  provider: oidc
  oidc-issuer-url: "https://login.microsoftonline.com/${data.azurerm_client_config.current.tenant_id}/v2.0"
  redirect-url: https://manny-sandbox-aks-dev.devtheasylum.uk/oauth2/callback
  login-url: https://login.microsoftonline.com/${data.azurerm_client_config.current.tenant_id}/v2.0/oauth2/authorize
  redeem-url: https://login.microsoftonline.com/${data.azurerm_client_config.current.tenant_id}/v2.0/oauth2/token
  oidc-jwks-url: https://login.microsoftonline.com/common/discovery/keys
  profile-url: https://graph.microsoft.com/v1.0/me
  scope: 'openid email profile'
  set-xauthrequest: true
  whitelist-domain: ".domain.com"
  cookie-domain: ".domain.com"
  cookie-secret: cookie-secret
  cookie-secure: false
  cookie-refresh: 10m
  cookie-expire: 15m
  pass-access-token: true
  pass-host-header: true
  pass-user-headers: true
  upstream: https://domain.com
sessionStorage:
  type: redis
redis:
  enabled: true
config:
  email-domain: "email-domain.com"
  client-id: "${var.oauth2_proxy_client_id}"
  client-secret: "${var.oauth2_proxy_client_secret}"
authenticated-emails-file:
  enabled: true
  restricted_access: "me@domain.com"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
  hosts:
    - domain.com
  path: /oauth2
  tls:
  - secretName: domain-tls-secret
    hosts:
      - domain.com

EOF
  ]

}
```

On the app I want to protect, I have the following:
```
nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Access-Token, Authorization, X-Forwarded-User, X-Forwarded-Groups, X-Forwarded-Email, X-Forwarded-Preferred-Username"
nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$request_uri"
nginx.ingress.kubernetes.io/configuration-snippet: |
  auth_request_set $name_upstream_1 $upstream_cookie_name_1;

  access_by_lua_block {
    if ngx.var.name_upstream_1 ~= "" then
      ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
    end
  }
```

## Expected Behavior
I would expect to be redirected to authenticate myself. Does anyone know what I am missing? Or Have I misconfigured something?

## Current Behavior

<img width="595" alt="Screenshot 2022-10-07 at 12 31 07" src="https://user-images.githubusercontent.com/44394920/194543815-c67b165c-7695-47e0-87a2-ca861a990036.png">
<img width="582" alt="Screenshot 2022-10-07 at 12 31 35" src="https://user-images.githubusercontent.com/44394920/194543822-ab3a1659-9573-4e00-864d-514714ee5f1f.png">

## Your Environment

Cloud Provider: Azure
Kubernetes: 1.24

- Version used: 7.3.0

Any help would be appreciated.

Thanks,

Manny
