### ISSUE TITLE
AccessToken could not be validated due mismatch audience/issuer

### ISSUE THREAD

**Issue by ramonmedeiros** [oauth2-proxy/oauth2-proxy#1823]
## Expected Behavior

Token passed by oauth2-proxy would be the same as when I generate through my application

## Current Behavior

My application return an error while validating it:

```
"ID token has invalid 'aud' (audience) claim; expected \"OTHER\" but got \"CLIENT_ID\"; make sure the ID token comes from the same Firebase project as the credential used to authenticate this SDK; see https://firebase.google.com/docs/auth/admin/verify-id-tokens for details on how to retrieve a valid ID token"
```

## Steps to Reproduce (for bugs)

1) Have an oauth
2) docker compose:
```
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    ports:
      - 4180:4180
    command:
      - --cookie-secret=MY_SECRET
      - --client-id=CLIENT_ID
      - --client-secret=CLIENT_SECRET
      - --email-domain=*
      - --http-address=0.0.0.0:4180
      - --redirect-url=http://localhost:4180/oauth2/callback
      - --whitelist-domain=localhost:4180
      - --set-xauthrequest=true
      - --pass-access-token=true
      - --pass-basic-auth=true
      - --pass-user-headers=true
      - --pass-authorization-header=true
      - --cookie-secure=false
      - --cookie-samesite=lax
      - --upstream=http://host.docker.internal:4000
      - --oidc-issuer-url=https://securetoken.google.com/EXPECTED_AUD
      - --oidc-extra-audience=EXPECTED_AUD

```

1.  
2.  
3.  
4.  

## Context

We have an application that uses oauth and firebase. Now we want to deploy several instances of it, so proxy could help us not adding new authorized domains every time

## Your Environment

- Version used: quay.io/oauth2-proxy/oauth2-proxy:latest
