### ISSUE TITLE
Using proxy-prefix behind a rewrite ingress causes an endless redirect loop

### ISSUE THREAD

**Issue by gboor** [oauth2-proxy/oauth2-proxy#1843]
I have a service deployed on a specific URL with a rewrite directive like so;

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: some-api
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: api.domain.tld
      http:
        paths:
          - path: /service/v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: some-api
                port:
                  name: http
```

oauth2-proxy with prefix-path set to `/service/v1/oauth2` results in an endless redirect loop between the proxy and the OIDC provider (Keycloak in this case)

## Expected Behavior

1. User opens https://api.domain.tld/service/v1/docs in a browser
2. oauth2-proxy redirects to Keycloak
3. Keycloak redirects to https://api.domain.tld/service/v1/oauth2/callback
4. oauth2-proxy handles the login and redirects to https://api.domain.tld/service/v1/docs

## Current Behavior

1. User opens https://api.domain.tld/service/v1/docs in a browser
2. oauth2-proxy redirects to Keycloak
3. Keycloak redirects to https://api.domain.tld/service/v1/oauth2/callback
4. oauth2-proxy redirects back to Keycloak, but now with a much longer URL
5. Keycloak redirects back to the callback URL
6. oauth2-proxy redirects back to Keycloak, with yet a longer URL

and so on and so forth until the URL gets so long it results in some 5xx error somewhere.

## Possible Solution

Setting redirect_url instead of proxy_prefix makes the login work, but the final redirect goes to /docs instead of /service/v1/docs. However, if I then change the URL I am logged in.

Using redirect_url, the URL flow looks like this;

1. https://my.keycloak/auth/realms/my-realm/protocol/openid-connect/auth?approval_prompt=force&client_id=some-api&redirect_uri=https://api.domain.tld/service/v1/oauth2/callback&response_type=code&scope=openid email profile&state=xxxx:/docs
2. https://api.domain.tld/service/v1/oauth2/callback?state=xxxx:/docs&session_state=yyyyy&code=zzzz
3. https://api.domain.tld/docs

This results in a 404, but I AM properly logged in if I manually change the URL.

Using proxy_prefix, it looks like this;

1. https://my.keycloak/auth/realms/my-realm/protocol/openid-connect/auth?approval_prompt=force&client_id=some-api&redirect_uri=https://api.domain.tld/service/v1/oauth2/callback&response_type=code&scope=openid email profile&state=xxxx:/docs
2. https://api.domain.tld/service/v1/oauth2/callback?state=xxxx:/docs&session_state=yyyy&code=zzzz
3. https://my.keycloak/auth/realms/my-realm/protocol/openid-connect/auth?approval_prompt=force&client_id=some-api&redirect_uri=https%3A%2F%2Fapi.domain.tld%2Fservice%2Fv1%2Foauth2%2F%2Fcallback&response_type=code&scope=openid+email+profile&state=xxxx%3A%2Foauth2%2Fcallback%3Fstate%3Dxxxx%253A%252Fdocs%26session_state%3Dyyyy%26code%3Dzzzz
4. https://api.domain.tld/service/v1/oauth2/callback?state=xxxx:/oauth2/callback?state=xxxx%3A%2Fdocs&session_state=yyyy&code=zzzz&session_state=yyyy&code=zzzz
5. https://my.keycloak/auth/realms/my-realm/protocol/openid-connect/auth?approval_prompt=force&client_id=some-api&redirect_uri=https://api.domain.tld/service/v1/oauth2/callback&response_type=code&scope=openid email profile&state=xxxx:/oauth2/callback?state=xxxx%3A%2Foauth2%2Fcallback?state%3Dxxxx%253A%252Fdocs%26session_state%3Dyyyy%26code%3Dzzzz&session_state=yyyy&code=zzzz

And so on and so forth. It just keeps adding the state and other params to the URL infinitely until it craps out with a 5xx at some point when the URL gets too long.

The strange thing is that, up until step 2, it's all the same as the example above. There is no difference in the callback URL, but for some reason it's not  being handled and it goes straight back to Keycloak.

## Steps to Reproduce (for bugs)

1. Create a deployment and service that uses oauth2-proxy as a sidecar;

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: some-service
      app.kubernetes.io/name: some-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: some-service
        app.kubernetes.io/name: some-api
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
          args:
            - '--proxy-prefix=/service/v1/oauth2 --[whatever other stuff is needed for the test setup]'
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          imagePullPolicy: IfNotPresent
        - name: some-api
          image: nginxdemos/hello
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: some-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/instance: some-service
    app.kubernetes.io/name: some-api
  type: ClusterIP

```

2. Create the ingress as shown above
3. Visit the URL at `/service/v1/whatever-you-like`

## Context

I am trying to get oauth2-proxy to auth properly on a sub-URL. The authentication works with `--redirect-url` set, but then the redirect back to the service ends in the wrong place. `--proxy-prefix` seems to solve what it needs to from the docs, but either I misunderstand what it's meant to do, or it doesn't work properly.

## Your Environment

Running on GKE with ingress-nginx
