### ISSUE TITLE
Invalid Scopes with oidc provider and allowed-group option

### ISSUE THREAD

**Issue by romanGarvis** [oauth2-proxy/oauth2-proxy#1846]
## Expected Behavior
Login success with allowed-group option

## Current Behavior
Getting error 403 with message 
```
Invalid authentication via OAuth2: unauthorized
```

## Steps to Reproduce (for bugs)

1.  Auth0 application with connection to the Azure AD
2.  Installed Authorization Extension and created group mapping 
3.  Created claim "groups". Because Auth0 doesn't support it by default

**Deployment:**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: oauth2
    spec:
      containers:
      - args:
        - --email-domain=*
        - --provider=oidc
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --auth-logging=true
        - --pass-authorization-header=true
        - --set-authorization-header=true
        - --pass-access-token=true
        - --set-xauthrequest=true
        - --standard-logging=true
        - --skip-jwt-bearer-tokens=true
        - --extra-jwt-issuers=https://auth.example.com/=XXXXXXXXXXXXXX
        - --cookie-samesite=
        - --insecure-oidc-allow-unverified-email=true
        - --cookie-name=XXXXXXXXXXXXXXXXXXXX
        - --oidc-groups-claim=groups
        - --allowed-group=test_group
        env:
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: https://auth.example.com/
        - name: OAUTH2_PROXY_CLIENT_ID
          value: XXXXXXXXXXXXXXXXXXXXX
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: XXXXXXXXXXXXXXXXXXXX
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: 0.0.0.0:4180
        - name: OAUTH2_PROXY_SET_XAUTHREQUEST
          value: "true"
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
        imagePullPolicy: Always
        name: oauth2
        ports:
        - containerPort: 4180
          name: http
          protocol: TCP
```

**Ingress:**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: web
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization, X-Auth-Request-Email,
      X-Auth-Request-User, X-Forwarded-Access-Token
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: web
  name: web
  namespace: web
spec:
  ingressClassName: nginx
  rules:
  - host: subdomain.example.com
    http:
      paths:
      - backend:
          service:
            name: web
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - subdomain.example.com
    secretName: subdomain.example.com
```

## Context
Without allowed-group option it works as expected 

## Your Environment
- Kubernetes: AKS cluster  v1.22.11
- oauth2-proxy: v7.2.1
