### ISSUE TITLE
Machine to machine authentication not working as expected

### ISSUE THREAD

**Issue by benedikt-mue** [oauth2-proxy/oauth2-proxy#1854]
I currently run a frontend with a backend api pool in a kubernetes cluster. Both services are secured via an auth2-proxy, handling the SSO on user side. Additionally, though, an automated workflow must also be able to connect to the API. 

## Expected Behavior

Both, machine to machine and user auth should work with the config, provided to the oauth2-proxy (seen below)

## Current Behavior

When trying to curl the API, like:
```
curl --header 'Content-Type: application/x-www-form-urlencoded' --header 'Authorization: Basic <user:secret(base64encoded)>' --request POST https://sso.provider.com/as/token.oauth2\?'grant_type=client_credentials'
```
and handing over the token to:
```
curl --location --request GET 'https://example.net/api/get_queue' --header 'Authorization: Bearer <Token>' --header 'Content-Type: application/json; charset=utf-8'
```
the auth2-proxy logs:
```
[2022/10/25 11:58:27] [jwt_session.go:51] Error retrieving session from token in Authorization header: no valid bearer token found in authorization header
```

## Setup

api-ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sd-ingress
  annotations:
    # nginx.ingress.kubernetes.io/auth-signin: https://example.net/oauth2/start?rd=$scheme://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://example.net/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"    
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "false"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - example.com
  rules:
  - host: example.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: sd-svc
            port:
              number: 8080
```

oauth2-config.yaml (excerpt)
```
...
        args:
          - --skip-jwt-bearer-tokens=true
          - --show-debug-on-error=true
          - --http-address=0.0.0.0:4180
          - --provider=oidc
          - --oidc-issuer-url=https://sso.provider.com
          - --metrics-address=0.0.0.0:44180
          - --acr-values=gas:strong
          - --cookie-domain=example.net
          - --oidc-email-claim=sub
          - --whitelist-domain=.example.net
          - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name:  oauth2-secret
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth2-secret
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth2-secret
              key: cookie-secret
...
___
apiVersion: v1
kind: ConfigMap
data:
  oauth2_proxy.cfg: "email_domains = [ \"*\" ]\nupstreams = [ \"file:///dev/null\" ]\npass_access_token = true\nset_xauthrequest = true"
...
```

- SSO provider: Corporate AD
- Version used: v7.3.0
