### ISSUE TITLE
Support for Multi-Tenancy Environments

### ISSUE THREAD

**Issue by s14r** [oauth2-proxy/oauth2-proxy#1863]
# Purpose of this issue
OAuth2 Proxy is currently lacking support for multi-tenancy environments. If you want to secure an application which requires to use different IDP (configurations) based on "something", OAuth2 Proxy is not something which you can use easily.

Even though we have a strong opinion on what we need and how we would approach it, we would love to see additional thoughts and requirements we may able to cover :)

***Disclaimer**: We are not maintaining the project in any way, we just want to start a discussion on how we could include the feature (as we need it in our company) in the most helpful way for the project and the community.*

# Multi-Tenancy in general
There are many different ways on how "tenant identification" happens – we mostly use (sub-)domain based identification while others may use headers based, route based or cookie based identification (or even more?). We think OAuth2 Proxy should have an extensible matching system which can be combined in different ways.

As our use-case is domain driven identification, we would like to start with this in the first place while maintaining an easy-to-extend interface for additional "matchers".

## Thoughts
* Our investigation and plans are based on the [Alpha Config](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config) feature, not sure how stable this is but it looks more convenient to us
* CLI options may not be sufficient anymore to cover the additional config complexity
* Config Templates like mentioned in #739 may not be enough, specifically when it comes to different providers for different tenants
* Config structure should be open for pre-planned modifications to not force users to change their config from release to release (e.g. when new matchers are introduced, etc.)

## Config
Here is a very *rough* idea of how a configuration could look like in the future.
We would make use of the already existing [Alpha Config](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config) while we would spent time to harmonize configuration.
If we go this way, it would definitely lead to a breaking change release as configuration API would change entirely.

There is already a helper to create an alpha config out of the existing one and we think it would make sense to keep this approach to have a "one-shot" configuration migration.

```yaml

server:
  bindAddress: 0.0.0.0:4180
  emailDomains: "*"
  cookieSecure: true
  skipProviderButton: false
  redirectURL: "/oauth2/callback"
  skipAuthPreflight: true
  cookieRefresh: 15m
  defaultProvider: keycloak-tenant-1
  
  # ... more options ...
  
upstreamServers:
  - id: api
    flushInterval: 1s
    passHostHeader: true
    proxyWebSockets: true
    timeout: 30s
    uri: http://127.0.0.1
    path: /

providers:
  keycloak-tenant-1:
    provider: keycloak
    keycloakConfig:
      clientID: my-keycloak-client-id-1
      clientSecret: my-keycloak-client-secret-1
      loginURL: "https://<keycloak host>/auth/realms/<your realm>/protocol/openid-connect/auth"
      redeemURL: "http(s)://<keycloak host>/auth/realms/<your realm>/protocol/openid-connect/token"
      profileURL: "http(s)://<keycloak host>/auth/realms/<your realm>/protocol/openid-connect/userinfo"
      validateURL: "http(s)://<keycloak host>/auth/realms/<your realm>/protocol/openid-connect/userinfo"
      keycloakGroups: 
        - group1
        - group2
  
  keycloak-tenant-2:
    provider: keycloak
    keycloakConfig:
      clientID: my-keycloak-client-id-2
      clientSecret: my-keycloak-client-secret-2
      loginURL: "https://<keycloak host>/auth/realms/<your realm>/protocol/openid-connect/auth"
      redeemURL: "http(s)://<keycloak host>/auth/realms/<your realm>/protocol/openid-connect/token"
      profileURL: "http(s)://<keycloak host>/auth/realms/<your realm>/protocol/openid-connect/userinfo"
      validateURL: "http(s)://<keycloak host>/auth/realms/<your realm>/protocol/openid-connect/userinfo"
      keycloakGroups:
        - group1
        - group2

# Matching defines in which way the OAuth2 Proxy will determine which provider to use on each request
matcher:
  - provider: keycloak-tenant-1
    matchers:
      # if ONE of the matchers hit the given provider is used for the auth request  
      - type: domain
        domain: "tenant1.my-great.app"

      # so you can combine additional matching methods to support different scenarios 
      - type: header
        header: "X-TENANT-ID"
        value: "tenant-1"
        
    # grouping could potentially be used to support more specific use-cases
    - provider: keycloak-tenant-2
        type: group
        group:
          # both conditions need to fulfilled in order to match
          # this is basically an "AND" operation
          - type: domain
            domain: "tenant2.my-great.app"
          - type: header
            header: "X-TENANT-ID"
            value: "tenant-2"
```

I'm happy to have @beezerk23 here with me who already started working on this feature internally. 
Happy to hear your thoughts!

Hey @JoelSpeed, please jump in if we've overseen something :)

Looking forward and have a good one guys!
