### ISSUE TITLE
Document session "claims"

### ISSUE THREAD

**Issue by lmsurpre** [oauth2-proxy/oauth2-proxy#1877]
I am using oauth2-proxy against Azure AD with the nginx auth_request module.
Our application has some roles defined and I'd like to inject those into a header.

The standard config doesn't seem to support that and so I started looking into the alphaConfig, but the documentation seems either wrong or lacking (or both).

Specifically, the `injectResponseHeaders` doc says that the headers "may source values from either the authenticated user's session or from a static secret value."
Then, for the header value, it says

claim | string | Claim is the name of the claim in the session that the value should be loaded from.
-- | -- | --

Due to the word "claim", I originally thought we could map any claim from the id_token (or userinfo response) to any header, but after some trial and error I now understand that only values from the session can be injected.

## Expected Behavior

Given an alpha provider with the following:
```
    providers:
      - id: azure
        provider: oidc
        clientID: ***redacted***
        clientSecret: ***redacted***
        scope: openid profile email
        oidcConfig:
          issuerURL: https://login.microsoftonline.com/***redacted***/v2.0
          # The docs say "aud" is the default, but it wasn't working for me without this (as of v7.4.0)
          audienceClaims:
            - aud
          # I had to set an alternate emailClaim because it wasn't finding the "email" claim for some reason
          emailClaim: preferred_username
          groupsClaim: roles
          userIDClaim: sub
```

I expected documentation which indicates which session "claims" are available for me to map into headers (e.g.  via `injectResponseHeaders`).

## Current Behavior

Through trial and error, I found that the "groupsClaim" claim can be mapped to a header via a "claim: groups" entry
```
      - name: X-Auth-Request-Roles
        values:
          - claim: groups
```

Similarly, the emailClaim is available to map and takes the value of the preferred_username from my id token
```
      - name: X-Auth-Request-Preferred-Username
        values:
          - claim: email
```

However, the userIDClaim config doesn't seem to make any difference... there is no `userID` claim that I can map to a header.
Instead, there is a `user` "claim" in the session that I can map, but it always takes the value of the `sub` claim from my id token.
```
      - name: X-Auth-Request-User
        values:
          - claim: user
```

I also found an `id_token` that is available to map to a header.

But I couldn't find anywhere in the docs that indicates which "claims" are available from the session for mapping.  Are there any others?

## Possible Solution

If you expect users to map values from the session, document which attributes are available to map.

## Context

Ideally I'd be able to inject at least 5 different headers:
* user (sub)
* email (email)
* preferred_username (preferred_username)
* groups (groups)
* roles (roles)

However, with the current design, that doesn't seem to be supported; there's a fixed list of session attributes that I can map claims to.  So the closest I can get is to inject the entire id_token to a header.

Is there a more generic way to configure which claims get mapped to which session attributes?

## Your Environment

Deployed to kubernetes using https://artifacthub.io/packages/helm/oauth2-proxy/oauth2-proxy 6.3.0 but with the image set to v7.4.0.
