### ISSUE TITLE
Recommendations for running oauth2-proxy with externalRedis

### ISSUE THREAD

**Issue by mnsaybi** [oauth2-proxy/oauth2-proxy#1907]
## Expected Behavior

I'm trying to configure oauth2-proxy v7.4 (bitnami chart) with an externalRedis cluster already deployed in my AKS cluster

## Current Behavior

An exception raised when deploying oauth2-proxy with this configuration:

```
[2022/11/21 22:32:26] [main.go:54] invalid configuration:
 unable to set a redis initialization key: WRONGPASS invalid username-password pair or user is disabled.
 unable to delete the redis initialization key: WRONGPASS invalid username-password pair or user is disabled.

```

For redis password in oauth2-proxy configuration I'm using the same password used with external redis !

## current configuration

```
  containers:
    - args:
        - '--http-address=0.0.0.0:4180'
        - '--config=/bitnami/oauth2-proxy/conf/oauth2_proxy.cfg'
        - '--redirect-url=https://mydomain.com/oauth2/callback'
        - >-
          --oidc-issuer-url=https://login.microsoftonline.com/mytenantid/v2.0
        - '--whitelist-domain="[*]"'
      env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: <my-client-id>
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: <my-client-secret>
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie-secret
              name: <my-client-cookie>
        - name: OAUTH2_PROXY_SESSION_STORE_TYPE
          value: redis
        - name: OAUTH2_PROXY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: <my-redis-password>
        - name: OAUTH2_PROXY_REDIS_CONNECTION_URL
          value: 'redis://redis.mydomain.com:6379'
```

## Your Environment

- Version used:
- OAuth2-proxy v7.4
- Redis cluster v8.2.7
