### ISSUE TITLE
Provider behind proxy 

### ISSUE THREAD

**Issue by mmajewski-be** [oauth2-proxy/oauth2-proxy#1911]
Hey team,

I am trying to set up OAuth-proxy with the OIDC provider which is located behind a corporate proxy. 

I am getting
[2022/11/25 14:53:01] [oauthproxy.go:723] Error redeeming code during OAuth2 callback: token exchange failed: Post "https://<PROVIDER_URL>:443/auth/oauth2/access_token": Not Found

I was trying to set proxy as environment variable -> http_proxy and https_proxy but it looks like oauth2-Proxy is not using this value

Is there any option to set a proxy for the outgoing requests to the token endpoint?

Configuration:

```
 spec:
      serviceAccountName: oauth2-oauth2-proxy
      containers:
      - name: oauth2-proxy
        image: "oauth2-proxy:v7.2.1"
        imagePullPolicy: IfNotPresent
        args:
          - --http-address=0.0.0.0:4180
          - --metrics-address=0.0.0.0:44180
          - --upstream="static://200"
          - --provider=oidc
          - --provider-display-name="OIDC"
          - --client-id=Tools
          - --client-secret=***********************
          - --cookie-secure=false
          - --cookie-secret=**********************************
          - --email-domain=*
          - --http-address=0.0.0.0:4180
          - --skip-provider-button=false
          - --ssl-upstream-insecure-skip-verify=true 
          - --ssl-insecure-skip-verify=true          
          - --show-debug-on-error=true 
          - --silence-ping-logging=true 
          - --standard-logging=true 
          - --auth-logging=true 
          - --request-logging=true 
          - --scope=openid 
          - --insecure-oidc-skip-nonce 
          - --reverse-proxy 
          - --skip-oidc-discovery 
          - --profile-url=https://<URL>:443/auth/oauth2/userinfo
          - --validate-url=https://<URL>:443/auth/oauth2/userinfo
          - --oidc-issuer-url=https://<URL>/auth/oauth2/
          - --login-url=https://<URL>/auth/oauth2/authorize
          - --redeem-url=https://<URL>:443/auth/oauth2/access_token
          - --oidc-jwks-url=https://<URL>:443/auth/oauth2/connect/jwk_uri
          - --redirect-url=https://<URL>
          - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        env:
        - name: HTTP_PROXY
          value: http://<URL>:8080
        - name: HTTPS_PROXY
          value: http://<URL>:8080
```
