### ISSUE TITLE
Not getting the access token header when --pass-access-token=true

### ISSUE THREAD

**Issue by atrabulsi** [oauth2-proxy/oauth2-proxy#1912]
Hello,

I'm trying to get the authenticated user information, such as the username, but I'm not getting the right headers even when using `--pass-access-token=true`

Context:
I'm using auth0 with oauth2-proxy in K8s.

Here are the manifests of oauth2-proxy:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --pass-access-token=true
            - --pass-authorization-header=true

            - --provider=oidc
            - --oidc-issuer-url=XXXX
            - --client-id=XXXX
            - --client-secret=XXXX
            - --redirect-url=MY_APP_DOMAIN/oauth2/callback
            - --cookie-secret=XXXX
            - --email-domain=*
            - --http-address=0.0.0.0:4180
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: demo
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: demo
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - MY_APP_DOMAIN
      secretName: XXXX
  rules:
    - host: MY_APP_DOMAIN
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180
```

Here is the manifest of my app ignress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - MY_APP_DOMAIN
      secretName: XXX
  rules:
    - host: MY_APP_DOMAIN
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hello-world
                port:
                  number: 80
```

## Expected Behavior

I should get a header called `X-Forwarded-Access-Token` that includes the access token of the logged in user.

## Current Behavior

I don't get any oauth2-proxy specific headers

## Steps to Reproduce (for bugs)

1. Install the ingress controller helm package
2. Install oauth2-proxy using the manifest included above
3. Install my app and ingress resource and confiture it as included above
4. Access my domain. I will be redirected to auth0 to login
5. After logging in, I will be redirected to my app
6. The app is not receiving the headers I expect

After logging in, when I request the endpoint `/oauth2/userinfo` I get:
```
{
  "user": "XXXX",
  "email": "XXXX"
}
```

## Your Environment

K8s version v1.24.4
oauth2-proxy version: v7.4.0 (built with go1.19.2)
ingress controller image: docker.io/bitnami/nginx-ingress-controller:1.4.0-debian-11-r2

Thanks!
