### ISSUE TITLE
gcp_authn: Envoy as a Cloud Storage (GCS) proxy

### ISSUE THREAD

**Issue by bzurkowski** [oauth2-proxy/oauth2-proxy#1934]
I am experimenting with Envoy with the purpose of configuring it as a reverse proxy for a private bucket hosted in Google Cloud Storage (GCS). My use case is related to hosting Single-Page Application (SPA) assets in GCS.

For authenticating object requests I am using [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity#what_is) feature available in GKE.

The general flow for accessing bucket objects is as follows:

First, retrieve access token from the Metadata Server:

```
curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
```

Second, fetch objects by performing requests to the Google Storage API with the token set in request header:

```
curl -H "Authorization: Bearer <retrieved-token>" https://storage.googleapis.com/<my-bucket>/<some-object>
```

I am running a standalone Envoy instance in a Pod with a Kubernetes Service Account bound to the corresponding Service Account in Google IAM. That enables the proxy workload to impersonate as IAM SA and perform allowed actions on bucket contents.

So far, I have produced the following configuration:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: gcs
          route_config:
            name: route_config_0
            virtual_hosts:
            - name: gcs
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  prefix_rewrite: "/<my-bucket>/index.html"
                  cluster: cluster_0
          http_filters:
          - name: envoy.filters.http.gcp_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.gcp_authn.v3.GcpAuthnFilterConfig
              http_uri:
                uri: "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=[AUDIENCE]"
                cluster: "gcp_authn"
                timeout:
                  seconds: 10
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: cluster_0
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    connect_timeout: 5s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: cluster_0
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:z
              socket_address:
                address: storage.googleapis.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    metadata:
      typed_filter_metadata:
        envoy.filters.http.gcp_authn:
          "@type": type.googleapis.com/envoy.extensions.filters.http.gcp_authn.v3.Audience
          url: storage.googleapis.com
  - name: gcp_authn
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    connect_timeout: 5s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: "gcp_authn"
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "metadata.google.internal"
                port_value: 80

```

The above configuration enables Envoy to successfully retrieve a token from Metadata Server:

```
':status', '200'
'content-type', 'application/json'
'metadata-flavor', 'Google'
'server', 'GKE Metadata Server'
'date', 'Fri, 16 Dec 2022 17:01:19 GMT'
'content-length', '1083'
'x-envoy-upstream-service-time', '69'
```

... it correctly injects the retrieved token into the GCS request:

```
':authority', '<authority>'
':path', '/<my-bucket>/index.htmlindex.html'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.84.0'
'accept', '*/*'
'x-forwarded-proto', 'http'
'x-request-id', '9670191c-afae-4fec-bfc7-1f69e0477018'
'authorization', 'Bearer <retrieved-token></retrieved-token>>'
```

However, GCS responds with `401` HTTP error code:

```
< HTTP/1.1 401 Unauthorized
< x-guploader-uploadid: ADPycdvFlV0BzHs_XUHOlvNeMH4QI_uWJVMXGSrcrIK20hpcLgShr83A_hwV3x6W3R1mTH30-vYj54ThE9qm12SGlnZcgLXYhz4O
< content-type: application/xml; charset=UTF-8
< content-length: 131
< www-authenticate: Bearer realm="https://accounts.google.com/"
< date: Fri, 16 Dec 2022 17:15:22 GMT
< expires: Fri, 16 Dec 2022 17:15:22 GMT
< cache-control: private, max-age=0
< server: envoy
< x-envoy-upstream-service-time: 114
<
* Connection #0 to host localhost left intact
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AuthenticationRequired</Code><Message>Authentication required.</Message></Error>%
```

I suspect that the access issue is imposed by the fact that JWT Token (in the presented Envoy configuration) is used instead of [Access Token](https://cloud.google.com/docs/authentication/token-types#access) (in the original flow).

Note that, in the Envoy configuration, only JWT Token is supported (with the `AUDIENCE` field):

```
http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=[AUDIENCE]
```

... while Access Token is not possible:

```
http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
```

I tried to set the `http_uri` to the above URL and it ended up with token parsing error:

```
[error][filter] [source/extensions/filters/http/gcp_authn/gcp_authn_filter.cc:112] Failed to parse the token string, status : 4
```

## Expected Behavior

Envoy supports retrieving Access Token via URL:

```
http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
```

## Current Behavior

Currently, only JWT token retrieval is supported.

Setting, the token URL to:

```
http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
```

... ends up with the parsing error:

```
[error][filter] [source/extensions/filters/http/gcp_authn/gcp_authn_filter.cc:112] Failed to parse the token string, status : 4
```

Perhaps, there is another approach to leverage Workload Identity with Envoy or the use case is not valid?
