### ISSUE TITLE
[Alpha config] Default values are not set

### ISSUE THREAD

**Issue by Shunpoco** [oauth2-proxy/oauth2-proxy#1957]
## Expected Behavior
When I read [the doc](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/alpha-config/#oidcoptions) and tried to use `--alpha-config` option with my config file, I expected that OAuth2-proxy use the following default values:
- Providers[].oidcConfig.emailClaim: "email"
- Providers[].oidcConfig.groupsClaim: "groups"
- Providers[].oidcConfig.userIDClaim: "email"
- Providers[].oidcConfig.audienceClaims: ["aud"]

## Current Behavior
These variables are empty, thus I failed to authenticate users using my OIDC provider (currently, I'm using Keycloak)
I checked this behavior on both the master branch (build manually) and docker image v7.3.0.

## Possible Solution
In `loadAlphaOptions`, we create an empty AlphaOptions struct then load the config yaml file, and finally, overwrite the old style options using the AlphaOptions.
If we don't set such default variables in our config yaml file, the AlphaOptions does not contain default variables.
I think we should define `NewAlphaOptions` function in order to initialize an AlphaOptions with default variables [like an old style options](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/apis/options/options.go#L95)

If this solution is reasonable, I will work on this.

## Steps to Reproduce (for bugs)

1.  Clone this repository
2.  Add these lines after [this line](https://github.com/oauth2-proxy/oauth2-proxy/blob/master/main.go#L117) in order to check the options
```go
bs, _ = json.Marshal(opts)
fmt.Println(string(bs))
```

3.  Prepare alpha-config yaml file. Currently, I'm using this `alpha-config.yaml`:
```yaml
server:
  BindAddress: '0.0.0.0:4180'
metricsServer:
  BindAddress: '0.0.0.0:44180'
providers:
- clientID: testclient
  clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  id: keycloak
  oidcConfig:
    insecureAllowUnverifiedEmail: true
    insecureSkipIssuerVerification: true
    issuerURL: http://keycloak.keycloak.svc.cluster.local:8080/auth/realms/oauth2
  provider: keycloak-oidc
upstreamConfig:
  proxyRawPath: true
  upstreams:
  - id: upstream
    path: ^/oauth2/(.*)$
    rewriteTarget: /$1
    uri: http://upstream.upstream.svc.cluster.local:5001
```

4.  Build and run the binary with options:
```console
go build
./oauth2-proxy --alpha-config=alpha-config.yaml --email-domain="*" --cookie-secret="XXXXXXXXXXXXXXXX"
```
5.  Check the print log (I omitted unnecessary lines)
```json
{
  "ProxyPrefix": "/oauth2",
  ...
  "Providers": [
    {
      "clientID": "testclient",
      ...
      "oidcConfig": {
        "issuerURL": "http://keycloak.keycloak.svc.cluster.local:8080/auth/realms/oauth2",
        "insecureAllowUnverifiedEmail": true,
        "insecureSkipIssuerVerification": true
      },
      ...
    }
  ],
  ...
}
```
Ideally, `oidcConfig` should be like this:
```json
"oidcConfig": {
    "insecureSkipNonce": true,
    "emailClaim": "email",
    "groupsClaim": "groups",
    "userIDClaim": "email",
    "audienceClaims": [
      "aud"
    ]
},
```

## Context

We have to set these default variables explicitly in our config file. But it does not match the document.

## Your Environment

- Version used: master branch
