### ISSUE TITLE
[AlphaConfig] Some claims in OIDC token not accessible by ClaimSource

### ISSUE THREAD

**Issue by joraff** [oauth2-proxy/oauth2-proxy#1960]
When successfully getting a token from an OIDC provider that includes claims like `upn`, `given_name`, and `family_name`, those claims are not being read by ClaimSource data type in alphaConfig, such as for use in `injectRequestHeaders`.

## Expected Behavior

The following code should create a `X-Provider-User` user with the `upn` value from the ID token:

```yaml
injectRequestHeaders:
  - name: X-Provider-User
    values:
      - claim: upn
```
 Repeat with claims `family_name`, `given_name`, and `email`. All claim values are being provided by the IdP, but only the `email` claim results in a header being set.

## Current Behavior

The HTTP header `X-Provider-{claim}` is blank, other than {claim}=email.

## Possible Solution

Observations: if I intentionally leave off a config value, such as not setting `audienceClaims: ["aud"]`, I can see that the claim values are present:

```[azure.go:291] unable to verify ID token, fallback to access token: audience claims [] do not exist in claims: map[aio:AUQAu/8TAAAAwY8+3Lyb0XqRWZIwgzZLCRbPFeS58EnVnBs6yu84l5fPT2dA2kLU9WssrFopPZCZds6luxuHfJJQmbBVPhoBfA== aud:3ec49072-7365-4065-8494-df5d8eb67a58 email:jrafferty@tamu.edu exp:1.672879765e+09 family_name:Rafferty given_name:Joseph iat:1.672875865e+09 iss:https://login.microsoftonline.com/68f381e3-46da-47b9-ba57-6f322b8f0da1/v2.0 name:Rafferty, Joseph R nbf:1.672875865e+09 oid:fba7fc62-a397-4d14-b310-cd760f937278 preferred_username:jrafferty@tamu.edu rh:0.AUUA44HzaNpGuUe6V28yK48NoXKQxD5lc2VAhJTfXY62elhFAOw. sub:3v5IpE6N3MdLwjo7WjzaTKZLxXz49e7bn4LO5zO6Vwg tid:68f381e3-46da-47b9-ba57-6f322b8f0da1 upn:jrafferty@tamu.edu uti:IlvulaJSTUqJQ9UYKX4hAw ver:2.0]```

Successful token gives this log output:

```[AuthSuccess] Authenticated via OAuth2: Session{email:jrafferty@tamu.edu user:3v5IpE6N3MdLwjo7WjzaTKZLxXz49e7bn4LO5zO6Vwg PreferredUsername:jrafferty@tamu.edu token:true id_token:true created:2023-01-04 18:34:10.211261 -0600 CST m=+24.669597876 expires:2023-01-04 19:40:42.678696 -0600 CST m=+4017.137035709}```

## Steps to Reproduce (for bugs)

1.  Configure again Azure AD
2. Configure AlphaOptions with a claim HTTP header injection. v
3. Observe the log output the for claims
4. Observe the HTTP headers sent to the upstream
5. Observe the JWT set in the `cookie` header. 

## Your Environment

alphaConfig:

```yaml
upstreamConfig:
  upstreams:
    - id: echo
      path: /
      uri: http://127.0.0.1:8081
injectRequestHeaders:
  - name: X-Provider-User
    values:
      - claim: upn
  - name: X-Ready-Email
    values:
      - claim: email
 
providers:
  - id: azure
    name: Azure AD
    provider: "oidc"
    clientId: "{clientId}"
    clientSecret: "{secret}"
    azureConfig:
      tenant: "{tenant}"
    oidcConfig:
      issuerUrl: "https://sts.windows.net/{tenant}/"
      audienceClaims:
        - aud
      emailClaim: email
      userIDClaim: upn
    scope: "openid email profile"
server:
  bindAddress: 127.0.0.1:8080
```

The log output

- Version used:
v7.4.0

**Comment by miguelborges99** [comment]
@NickMeves Is the userIDClaim option deprecated?
At least it seems, looking at the code comment

https://github.com/oauth2-proxy/oauth2-proxy/blob/f753ec1ca5c42cd4c4e400afa1f76817638f3010/providers/providers.go#L148

I do not see any instruction to copy the userIDClaim in this method

`p.UserIDClaim = providerConfig.OIDCConfig.UserIDClaim`

should there be???


There are also some issues, when userIDClaim is not set. See [pull request](https://github.com/oauth2-proxy/oauth2-proxy/pull/1920)

**Comment by JoelSpeed** [comment]
Not yet resolved, never got around to adding the additional claims support that I had intended to

**Comment by gygabyte017** [comment]
This is still unsolved, jwt may contain any number of custom claims, and is very important to inject them all.

**Comment by SamuZad** [comment]
This is still unsolved, jwt may contain any number of custom claims, and is very important to inject them all.

**Comment by peterfarrell** [comment]
@SamuZad Starting in the [v7.15.0](https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.15.0) release:

> Session state can now be extend with arbitrary claims from ID Token and upstream IDP user profiles endpoint
> * This opens the door for multiple features like:
> * Additional arbitrary header values for any claims your IDP provides
> * Extended OAuth2 Proxy UserInfo endpoint with all additional claims
> * Read the docs [here](https://oauth2-proxy.github.io/oauth2-proxy/configuration/alpha-config#how-to-utilize-arbitrary-claims-provided-by-your-identity-provider)

You can set `injectRequestHeaders` for any claim value that you require as long as you define them in `additionalClaims`.  What specific claims do you **not** have access to? 

IMO, the feature on this issue has been implemented in  #2685 and this issue is now a duplicate.

This is an example:
```yaml
---
server:
  bindAddress: "0.0.0.0:4180"
upstreamConfig:
  upstreams:
    - id: static-forward-auth
      path: /
      static: true
      staticCode: 200

injectResponseHeaders:
  - name: X-Forwarded-User
    values:
      - claimSource:
          claim: user
  - name: X-Forwarded-Email
    values:
      - claimSource:
          claim: email
  - name: X-Forwarded-Spin
    values:
      - claimSource:
          claim: spin
  - name: X-Forwarded-Preferred-Username
    values:
      - claimSource:
          claim: preferred_username
  - name: X-Forwarded-First-Name
    values:
      - claimSource:
          claim: given_name
  - name: X-Forwarded-Middle-Name
    values:
      - claimSource:
          claim: middle_name
  - name: X-Forwarded-Last-Name
    values:
      - claimSource:
          claim: family_name
  - name: X-Forwarded-Phone-Number
    values:
      - claimSource:
          claim: phone_number
  - name: X-Auth-Iss
    values:
      - secretSource:
          value: "${ISSUER_URL}"
  - name: X-Auth-Iat
    values:
      - claimSource:
          claim: iat
  - name: X-Auth-Exp
    values:
      - claimSource:
          claim: exp

# Provider Configuration
providers:
  - id: commercial-idp
    name: Commercial IdP
    provider: oidc
    scope: "openid offline_access profile email phone"
    clientID: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    code_challenge_method: S256
    skipClaimsFromProfileURL: false
    additionalClaims:
      - spin
      - family_name
      - given_name
      - middle_name
      - name
      - phone_number
      - zoneinfo
      - iat
      - exp
    loginURLParameters:
      - name: approval_prompt
        default:
          - force
    oidcConfig:
      issuerURL: ${ISSUER_URL}
      emailClaim: email
```
