### ISSUE TITLE
Unable to find a valid CSRF token | kubernetes | nginx

### ISSUE THREAD

**Issue by rshiva777** [oauth2-proxy/oauth2-proxy#1962]
I have configured oauth2-proxy to used github as an idp, when i try to acces the URL, it is throwing "Unable to find a valid CSRF token" Error

## Expected Behavior

I should be able to access my URL after authenticating via oauth2 proxy

## Current Behavior

Getting "Unable to find a valid CSRF token" error after authenticating via github idp

## Steps to Reproduce (for bugs)

1. Install oauth2-proxy using helm chart
2. Integrate with github idp provider for authentication
    below are the args for oauth2-proxy deployment:

```
      containers:
      - args:
        - --http-address=0.0.0.0:4180
        - --https-address=0.0.0.0:4443
        - --metrics-address=0.0.0.0:44180
        - --provider=github
        - --redirect-url=http://oauth2.test.shiva.com/oauth2/callback
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        - --htpasswd-file=/etc/oauth2_proxy/htpasswd/users.txt
        - --reverse-proxy=true
        - --set-xauthrequest=true
        - --set-authorization-header=true
        - --cookie-csrf-per-request=true
        - --cookie-csrf-expire=5m
        - --cookie-samesite=lax
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --cookie-refresh=5m
        - --scope="user:email"
        - --skip-provider-button=false
        - --session-store-type=cookie
        - --cookie-samesite=lax
        - --skip-auth-preflight=false
        - --cookie-domain=.test.shiva.com
        - --whitelist-domain=.test.shiva.com
        - --client-id=*******************
        - --client-secret=*******************
        - --cookie-secret=*******************
        - --cookie-secure=true
        - --upstream=file:///dev/null
```
3. Deploy below ingress resource

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: oauth2
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: http://oauth2.test.shiva.com/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth-oauth2-proxy.oauth2.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: nginxnew.test.shiva.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx
            port:
              number: 80
```

4. Access the url from browser and authenticate with github provides the below error

![image](https://user-images.githubusercontent.com/42074614/211134163-51975836-bced-44df-a792-911fd4ea95f6.png)

nginx Log:
```
172.17.0.1 - - [07/Jan/2023:07:35:37 +0000] "GET / HTTP/1.1" 401 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0 0.002 [oauth2-nginx-80] [] 10.107.159.120:80 0 0.002 401 e85ff197337d6f6d88a5e5a326c77254
172.17.0.1 - - [07/Jan/2023:07:35:37 +0000] "GET / HTTP/1.1" 302 138 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 438 0.002 [oauth2-nginx-80] [] - - - - e85ff197337d6f6d88a5e5a326c77254
172.17.0.1 - - [07/Jan/2023:07:35:37 +0000] "GET /oauth2/start?rd=http://nginxnew.test.shiva.com%2F HTTP/1.1" 302 340 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 485 0.002 [oauth2-oauth-oauth2-proxy-80] [] 172.17.0.6:4180 340 0.002 302 5c4a2a1b252f91caaf335ac9fd750a87

172.17.0.1 - - [07/Jan/2023:07:36:10 +0000] "GET /oauth2/callback?code=5421ed81d3940b8d5586&state=YtnWrSNvV8XVCPalaKPRVbUNvf7zgL3fWSQ9zDfyXnA%3Ahttp%3A%2F%2Fnginxnew.test.shiva.com%2F HTTP/1.1" 403 2662 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 569 0.002 [oauth2-oauth-oauth2-proxy-80] [] 172.17.0.6:4180 2669 0.002 403 b4bb3edb86fc6e9fb074e259d52761df
172.17.0.1 - - [07/Jan/2023:07:36:10 +0000] "GET /favicon.ico HTTP/1.1" 403 9128 "http://oauth2.test.shiva.com/oauth2/callback?code=5421ed81d3940b8d5586&state=YtnWrSNvV8XVCPalaKPRVbUNvf7zgL3fWSQ9zDfyXnA%3Ahttp%3A%2F%2Fnginxnew.test.shiva.com%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 519 0.005 [oauth2-oauth-oauth2-proxy-80] [] 172.17.0.6:4180 9129 0.005 403 3597facd3bdd22da8e5d4681ebfe59e8
```

oauth2-proxy log:
```
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 401 13 0.000
172.17.0.1 - 5c4a2a1b252f91caaf335ac9fd750a87 - - [2023/01/07 07:35:37] oauth2.test.shiva.com GET - "/oauth2/start?rd=http://nginxnew.test.shiva.com%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 302 340 0.000
172.17.0.1 - f773bcb1-21ba-452c-a666-7b0bca717210 - - [2023/01/07 07:35:39] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
172.17.0.1 - b2e0cbcf-030c-4080-8c89-6a1980d690da - - [2023/01/07 07:35:39] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
172.17.0.1 - ee0947b8-45e9-4a73-9c57-e0c7daeda0ff - - [2023/01/07 07:35:49] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
172.17.0.1 - 00210422-7a6c-4700-9490-c3b1641c6adb - - [2023/01/07 07:35:49] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
172.17.0.1 - 04a6c04e-20f4-4e86-b881-230c3309e23b - - [2023/01/07 07:35:59] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
172.17.0.1 - 8a21e3f1-c175-43fb-84fb-85a9c43418a6 - - [2023/01/07 07:35:59] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
172.17.0.1 - 057c8a08-bd61-4975-8981-f4a52d2ceab2 - - [2023/01/07 07:36:09] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
172.17.0.1 - 7fac79ea-e809-45fc-afc2-3b12c691fb08 - - [2023/01/07 07:36:09] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
[2023/01/07 07:36:10] [oauthproxy.go:816] &{GET /oauth2/callback?code=5421ed81d3940b8d5586&state=YtnWrSNvV8XVCPalaKPRVbUNvf7zgL3fWSQ9zDfyXnA%3Ahttp%3A%2F%2Fnginxnew.test.shiva.com%2F HTTP/1.1 1 1 map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9] Accept-Encoding:[gzip, deflate] Accept-Language:[en-US,en;q=0.9] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36] X-Forwarded-For:[172.17.0.1] X-Forwarded-Host:[oauth2.test.shiva.com] X-Forwarded-Port:[80] X-Forwarded-Proto:[http] X-Forwarded-Scheme:[http] X-Real-Ip:[172.17.0.1] X-Request-Id:[b4bb3edb86fc6e9fb074e259d52761df] X-Scheme:[http]] {} <nil> 0 [] false oauth2.test.shiva.com map[code:[5421ed81d3940b8d5586] state:[YtnWrSNvV8XVCPalaKPRVbUNvf7zgL3fWSQ9zDfyXnA:http://nginxnew.test.shiva.com/]] map[] <nil> map[] 172.17.0.9:47942 /oauth2/callback?code=5421ed81d3940b8d5586&state=YtnWrSNvV8XVCPalaKPRVbUNvf7zgL3fWSQ9zDfyXnA%3Ahttp%3A%2F%2Fnginxnew.test.shiva.com%2F <nil> <nil> <nil> 0xc00028cd20} AuthFailure Invalid authentication via OAuth2: unable to obtain CSRF cookie

172.17.0.1 - b4bb3edb86fc6e9fb074e259d52761df - - [2023/01/07 07:36:10] oauth2.test.shiva.com GET - "/oauth2/callback?code=5421ed81d3940b8d5586&state=YtnWrSNvV8XVCPalaKPRVbUNvf7zgL3fWSQ9zDfyXnA%3Ahttp%3A%2F%2Fnginxnew.test.shiva.com%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 403 2650 0.001
[2023/01/07 07:36:10] [oauthproxy.go:959] No valid authentication in request. Initiating login.
172.17.0.1 - 3597facd3bdd22da8e5d4681ebfe59e8 - - [2023/01/07 07:36:10] oauth2.test.shiva.com GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 403 9102 0.003
172.17.0.1 - 32a5bda3-e5e4-4984-8617-7970bfb86617 - - [2023/01/07 07:36:19] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
```

## Your Environment

- Version used:
kuberentes version: v1.24.0
oauth2-proxy: v7.4.0
nginx ingress: v1.5.1

**Comment by miguelborges99** [comment]
Could you check in  your requests where the csrf cookie is lost or if it is present?

In your browser, open the developer tools and check what occurs with the csrf cookie. If you did not gave any name to your cookie, then it should be something like _oauth2_proxy_csrf_xxx.
The csrf cookie is created when you call /oauth2/start

**Comment by miguelborges99** [comment]
@rshiva777 Maybe your issue is related to https://github.com/oauth2-proxy/oauth2-proxy/issues/1724, see this https://github.com/oauth2-proxy/oauth2-proxy/issues/1724#issuecomment-1350894252.
You are using a config file,

- --config=/etc/oauth2_proxy/oauth2_proxy.cfg

I think you need to add this entry in the oauth2_proxy.cfg

scope = "user:email

If it is and it is solved, then please close this issue

**Comment by rshiva777** [comment]
@miguelborges99 , Thanks for the prompt update. 

I am facing same issue on keycloak IDP provider.

![image](https://user-images.githubusercontent.com/42074614/211165456-3aeb5c38-1d13-4550-9b36-0ffbe99389c4.png)

**oauth logs:**
```
172.17.0.1 - 81a7067ca465069d70f625ba28b78346 - - [2023/01/07 18:31:35] oauth2.test.shiva.com GET - "/oauth2/callback?state=-ZromjSoVpJ0n-CRPQc7u0nnAznuZ2b2Is4ZXxQCDkU%3Ahttp%3A%2F%2Fnginxtest.test.shiva.com&session_state=f58c7f52-1332-420e-82fa-66cece5f668c&code=4a040293-5320-4dbd-8ad2-812a99a3190a.f58c7f52-1332-420e-82fa-66cece5f668c.be5f5a13-999f-413c-ba5e-0d0e5de668c3" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76" 403 2650 0.001
172.17.0.1 - 4be99917-ff8c-488f-ba8f-6af0276b1287 - - [2023/01/07 18:31:43] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
172.17.0.1 - 6d95a7a9-0087-4f84-acd7-2f9a8354dfff - - [2023/01/07 18:31:43] 172.17.0.6:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.23" 200 2 0.000
[2023/01/07 18:31:45] [oauthproxy.go:816] &{GET /oauth2/callback?state=-ZromjSoVpJ0n-CRPQc7u0nnAznuZ2b2Is4ZXxQCDkU%3Ahttp%3A%2F%2Fnginxtest.test.shiva.com&session_state=f58c7f52-1332-420e-82fa-66cece5f668c&code=4a040293-5320-4dbd-8ad2-812a99a3190a.f58c7f52-1332-420e-82fa-66cece5f668c.be5f5a13-999f-413c-ba5e-0d0e5de668c3 HTTP/1.1 1 1 map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9] Accept-Encoding:[gzip, deflate] Accept-Language:[en-US,en;q=0.9] Cache-Control:[max-age=0] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76] X-Forwarded-For:[172.17.0.1] X-Forwarded-Host:[oauth2.test.shiva.com] X-Forwarded-Port:[80] X-Forwarded-Proto:[http] X-Forwarded-Scheme:[http] X-Real-Ip:[172.17.0.1] X-Request-Id:[bc3aabcc2ce07434e4b5a87d8e0cc973] X-Scheme:[http]] {} <nil> 0 [] false oauth2.test.shiva.com map[code:[4a040293-5320-4dbd-8ad2-812a99a3190a.f58c7f52-1332-420e-82fa-66cece5f668c.be5f5a13-999f-413c-ba5e-0d0e5de668c3] session_state:[f58c7f52-1332-420e-82fa-66cece5f668c] state:[-ZromjSoVpJ0n-CRPQc7u0nnAznuZ2b2Is4ZXxQCDkU:http://nginxtest.test.shiva.com]] map[] <nil> map[] 172.17.0.5:44274 /oauth2/callback?state=-ZromjSoVpJ0n-CRPQc7u0nnAznuZ2b2Is4ZXxQCDkU%3Ahttp%3A%2F%2Fnginxtest.test.shiva.com&session_state=f58c7f52-1332-420e-82fa-66cece5f668c&code=4a040293-5320-4dbd-8ad2-812a99a3190a.f58c7f52-1332-420e-82fa-66cece5f668c.be5f5a13-999f-413c-ba5e-0d0e5de668c3 <nil> <nil> <nil> 0xc00007f800} AuthFailure Invalid authentication via OAuth2: unable to obtain CSRF cookie

172.17.0.1 - bc3aabcc2ce07434e4b5a87d8e0cc973 - - [2023/01/07 18:31:45] oauth2.test.shiva.com GET - "/oauth2/callback?state=-ZromjSoVpJ0n-CRPQc7u0nnAznuZ2b2Is4ZXxQCDkU%3Ahttp%3A%2F%2Fnginxtest.test.shiva.com&session_state=f58c7f52-1332-420e-82fa-66cece5f668c&code=4a040293-5320-4dbd-8ad2-812a99a3190a.f58c7f52-1332-420e-82fa-66cece5f668c.be5f5a13-999f-413c-ba5e-0d0e5de668c3" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76" 403 2650 0.004
^C

```


args to oauth2:
```
        - args:
          - --http-address=0.0.0.0:4180
          - --https-address=0.0.0.0:4443
          - --metrics-address=0.0.0.0:44180
          - --provider=keycloak-oidc
          - --redirect-url=http://oauth2.test.shiva.com/oauth2/callback
          - --oidc-issuer-url=http://keycloak.test.shiva.com/realms/master
          - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
          - --htpasswd-file=/etc/oauth2_proxy/htpasswd/users.txt
          - --reverse-proxy=true
          - --set-xauthrequest=true
          - --set-authorization-header=true
          - --cookie-csrf-per-request=true
          - --cookie-csrf-expire=5m
          - --cookie-samesite=lax
          - --pass-access-token=true
          - --pass-authorization-header=true
          - --cookie-refresh=5m
          - --skip-provider-button=false
          - --session-store-type=cookie
          - --cookie-samesite=lax
          - --footer=-
          - --banner=-
          - --skip-auth-preflight=false
          - --cookie-domain=.test.shiva.com
          - --whitelist-domain=.test.shiva.com
          - --client-id=oauth2-proxy
          - --client-secret=kgSqcTAcgYgcUMdvwjjDHvUSKTMwKHHE
          - --cookie-secret=V4BrXfxVeMOclFeui9x2CQ==
          - --cookie-secure=true
          - --upstream=file:///dev/null
          - --insecure-oidc-allow-unverified-email=true
          - --skip-jwt-bearer-tokens=true
          env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: client-id
                name: oauth-oauth2-proxy
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: client-secret
                name: oauth-oauth2-proxy
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                key: cookie-secret
                name: oauth-oauth2-proxy
```
