### ISSUE TITLE
Add a flag to redirect users to OIDC logout page.

### ISSUE THREAD

**Issue by 5h4k4r** [oauth2-proxy/oauth2-proxy#1976]
We have an oidc provider and want the user to be redirected to the logout page of our oidc provider.

some of our employees forget to log out off the identity server, so when the other employee comes, they're working with the previous employee's account.

## Expected Behavior

A flag can fix our issue, something like redirectAfterLogout, based on this flag OAuth proxy can check if the provider is oidc and if this flag is true then it redirects users to oidc providers logout page to logout in to both oauth proxy and our identity server.

## Current Behavior

oauth proxy has two ways of fixing this but none of them works:

1. Using X-Auth-Request-Redirect header: we're using Kubernetes with ingress-nginx controller and we cannot set this auth request in our ingress as the ingress sets the header for every request it passes.
2. Using rd query parameter: this can fix our problem, but it causes us a headache as we have different identity servers for different environments (dev, production) , the problem is the rd parameter must come from the client, we cannot configure it on server side for each environment (dev, staging and production).

## Possible Solution

It would be much easier if we had a boolean flag (logoutFromOIDC) to redirect users to identity server after logging out from the oauth proxy. 

## Your Environment

```
  API_UPSTREAM: http://api-gateway-service
  CLIENT_ID: <client-id>
  CLIENT_UPSTREAM: http://pis-insight-client-service
  COOKIE_NAME: __Host-<cookie-name>
  COOKIE_SECURE: "true"
  EMAIL_DOMAINS: '*'
  ISSUER_URL: <identity-server>
  PORT: "4180"
  PROXY_PREFIX: /auth
  REDIRECT_URL: https://<client-url>/auth/callback
  REDIS_CONNECTION_URL: redis://redis-master:6379/6
  SCOPES: <scopes>
  SESSION_STORE_TYPE: redis

  CLIENT_SECRET: <client-secret>
  COOKIE_SECRET: <cookie-secret>
  REDIS_PASSWORD: <redis-password>

```
alpha config options:
 ```
upstreamConfig:
   upstream:
     - id: API
       path: /api/
       rewriteTarget: /$1
       uri: "http://api-gateway-service"

    - id: client
      path: /
      uri: "http://pis-insight-client-service"

 injectRequestHeaders:
   - name: Authorization
     preserveRequestValue: false
     values:
       - claim: access_token
         prefix: "Bearer "

 server:
   BindAddress: :4180

 providers:
   - id: <id>
     provider: oidc
     clientID: <client-id>
     clientSecret: <client-secret>
     code_challenge_method: S256
     profileUrl: https://<identity-server>/connect/userinfo
     scope: <scopes>
     redeemURL: https://<identity-server>/connect/token
     oidcConfig:
       issuerUrl: <identity-server>
       emailClaim: email
       userIDClaim: sub
       jwksURL: https://<identity-server>/.well-known/openid-configuration/jwks
       audienceClaims:
         - aud
       extraAudiences:
         - <audiences>

```
- Version used: v7.4.0
