### ISSUE TITLE
Can i disable authentication for specific subpath?

### ISSUE THREAD

**Issue by ghost** [oauth2-proxy/oauth2-proxy#1998]
I have a little struggle and need your help for the follwing problem:

We use the oauth2-proxy for every web applications with traefik. Everything runs fine but we have one challange with a backend. One application makes there oauth self and cant use the oauth2-proxy. Wenn the request send the cookie to the service, the service returns a http/400.

The setup:

* service1.site.mysite.com <- uses oauth2-proxy and everthing is fine (welcome page for alle subelements)
* service1.site.mysite.com/subelement1 <- must not pass any oauth credentials from proxy
* service1.site.mysite.com/subelement1 <- must not pass any oauth credentials from proxy 
* service1.site.mysite.com/subelement1 <- must not pass any oauth credentials from proxy
* service2.site.mysite.com/ <- uses oauth2-proxy correctly

Every service is with the same main domain.

## Configuration file for oauth2-proxy
```
client_id = "xxxxxx"
client_secret = "xxxxxx"
cookie_domains = ".site.mysite.com"
cookie_secret = "xxxxxx"
cookie_secure = "true"
email_domains = [
  "*"
]
http_address = "0.0.0.0:4180"
login_url = "https://login.microsoftonline.com/XXXXX/v2.0/oauth2/authorize"
metrics_address = "0.0.0.0:4181"
oidc_issuer_url = "https://login.microsoftonline.com/XXXXX/v2.0"
oidc_jwks_url = "https://login.microsoftonline.com/common/discovery/keys"
profile_url = "https://graph.microsoft.com/v1.0/me"
provider = "oidc"
redeem_url = "https://login.microsoftonline.com/XXXXX/v2.0/oauth2/token"
redirect_url = "https://oauth.site.mysite.com/oauth2/callback"
reverse_proxy = "true"
skip_provider_button = "true"
upstreams = "static://202"
whitelist_domains = ".site.mysite.com"
```

## Configuration oauth2-proxy for traefik
```yaml
http:
  routers:
    oauth2-proxy-route:
      rule: Host(`oauth.site.mysite.com`) && PathPrefix(`/`)
      middlewares:
      - secure-headers
      service: oauth-backend
  services:
    oauth-backend:
      loadBalancer:
        servers:
        - url: http://localhost:4180
  middlewares:
    rate-limit:
      rateLimit:
        average: 1000
        burst: 500
    secure-headers:
      headers:
        accessControlAllowMethods:
        - GET
        - OPTIONS
        - PUT
        - POST
        accessControlMaxAge: 100
        hostsProxyHeaders:
        - X-Forwarded-Host
        - X-Real-IP
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        frameDeny: true
        customFrameOptionsValue: allow-from https:mon.cloud.dvag
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: same-origin
        permissionsPolicy: camera 'none'; geolocation 'none'; microphone 'none'; payment
          'none'; usb 'none'; vr 'none';
        customResponseHeaders:
          X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex,nocache,nositelinkssearchbox,nopagereadaloud
          server: ''
    oauth-auth-redirect:
      forwardAuth:
        address: https://oauth.site.mysite.com/
        trustForwardHeader: true
        authResponseHeaders:
        - X-Auth-Request-Access-Token
        - Authorization
```

## Configuration for the problem route
```yaml
http:
  routers:
    service1-help-rtr: # welcome/landingpage
      rule: Host(`service1.site.mysite.com`) && !PathPrefix(`/.well-known/acme-challenge`)
      entryPoints:
      - https
      service: landingpage-service-svc
      priority: 1
      middlewares:
      - rate-limit
      - secure-headers
      - oauth-auth-redirect
      - addprefix-service1
    service1-rtr-ent: # backendserver service1 stage ent
      rule: Host(`service1.site.mysite.com`) && (PathPrefix(`/ent`) || PathPrefix(`/went`))
      entryPoints:
      - https
      service: service1-svc-ent
      priority: 2
      middlewares:
      - rate-limit
      - secure-headers
    service1-rtr-int: # backendserver service1 stage int
      rule: Host(`service1.site.mysite.com`) && (PathPrefix(`/int`) || PathPrefix(`/wint`))
      entryPoints:
      - https
      service: service1-svc-int
      priority: 3
      middlewares:
      - rate-limit
      - secure-headers
  middlewares:
    addprefix-log4u:
      addPrefix:
        prefix: /help
  services:
    landingpage-service-svc:
      loadBalancer:
        servers:
        - url: http://127.0.0.1:8085
    service1-svc-ent:
      loadBalancer:
        healthCheck:
          path: /HealthCheck
          interval: 10s
          timeout: 3s
        servers:
        - url: http://service1.ent.intern:8001
    service1-svc-int:
      loadBalancer:
        healthCheck:
          path: /HealthCheck
          interval: 10s
          timeout: 3s
        servers:
        - url: http://service1.int.intern:8001
```

And in all my other routes, i have configured the oauth-auth-redirect middleware.

- Version oauth2-proxy used: 7.4.0
- Version traefik used: 2.9.6

Booth application are running nativ on a linux server.
