### ISSUE TITLE
whitelist-domain does not work with alternative port

### ISSUE THREAD

**Issue by AurimasNav** [oauth2-proxy/oauth2-proxy#2000]
## Expected Behavior

I should get authenticated and be able to reach `myservice`.

## Current Behavior

After authentication getting 404 error.

## Possible Solution

Everything is working fine if I'm using default port, however there are situations when I need to use alternate port.

## Steps to Reproduce (for bugs)

1. oauth ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - login.example.com
    secretName: login-letsencrypt
  rules:
  - host: login.example.com
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
```

2. service ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myservice
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/auth-url: "https://login.example.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.example.com/oauth2/start?rd=$scheme://$best_http_host$escaped_request_uri"
spec:
  rules:
  - host: myservice.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myservice
            port:
              name: app

```

3. oauth2-proxy env:
```
  OAUTH2_PROXY_COOKIE_DOMAIN: ".example.com"
  OAUTH2_PROXY_WHITELIST_DOMAIN: "*.example.com:8443"
```

## Context

I've read very useful [thread](https://github.com/oauth2-proxy/oauth2-proxy/issues/109) which helped me to make this work with standard port, but I'm still bummed out about not being able to make it work with alternate port.

I could see in the ingress logs that redirect uri is constructed correctly however after signing in to google I would still end up with 404 error, because it seems I would get redirected to `[upstream-default-backend]` instead of `myservice`

<details>
  <summary>nginx ingress logs</summary>

```text

10.42.0.1 - - [04/Feb/2023:11:48:12 +0000] "GET /oauth2/auth HTTP/1.1" 401 13 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 686 0.001 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.158:4180 13 0.002 401 e715b29e589deb8a7bc6db0f372cb4c0
6
10.42.0.1 - - [04/Feb/2023:11:48:12 +0000] "GET / HTTP/2.0" 401 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 0 0.018 [myservice-myservice-app] [] <external_ip>:8443 0 0.013 401 e715b29e589deb8a7bc6db0f372cb4c0
5
10.42.0.1 - - [04/Feb/2023:11:48:12 +0000] "GET / HTTP/2.0" 302 138 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 279 0.018 [myservice-myservice-app] [] - - - - e715b29e589deb8a7bc6db0f372cb4c0
4
10.42.0.1 - - [04/Feb/2023:11:48:12 +0000] "GET /oauth2/start?rd=https://myservice.example.com:8443%2F HTTP/2.0" 302 383 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 1727 0.000 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.158:4180 383 0.001 302 4940a5bc8ec3e0aba6f23ba5b3db47b5
3
10.42.0.1 - - [04/Feb/2023:11:48:14 +0000] "GET /oauth2/callback?state=uRqI_Bku4e-Huu0rtN0AWNLhjvixyWSp5w-IazU-dhM%3A%2F&code=4%2F0AWtgzh7B-dtJNu_ABg_wqxXatys1jiPn3DpIVgXeckDWCqoYT1lEnpBfM7nUJlIinFYMYg&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=consent HTTP/2.0" 302 24 "https://accounts.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 448 0.197 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.158:4180 24 0.197 302 925069192927403431efe2df8144f5f2
2
10.42.0.1 - - [04/Feb/2023:11:48:14 +0000] "GET / HTTP/2.0" 404 146 "https://accounts.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 1429 0.000 [upstream-default-backend] [] 127.0.0.1:8181 146 0.001 404 9518d3b23dbe8b3d12090e3346083631
1
10.42.0.1 - - [04/Feb/2023:11:48:14 +0000] "GET /favicon.ico HTTP/2.0" 499 0 "https://login.example.com:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 191 0.000 [upstream-default-backend] [] 127.0.0.1:8181 0 0.000 - 9d0b6949db1ae40f7271c0a820693618
```

</details>

I've also seen a comment about cli flag `whitelist-domain` (singular) not corresponding to the config key of `whitelist-domains` (plural), so I've tried to set my env to 

```yaml
OAUTH2_PROXY_WHITELIST_DOMAINS: "*.example.com:8443"
```
which should be the [correct name](https://github.com/oauth2-proxy/oauth2-proxy/blob/10adb5c516b5a15756a7baa50aa2d8551a6655b8/options.go#L51) and this changed the behavior, but now it seems that it just can't get out of redirect loop, after clicking on google account to login with, I'm just back at google login page.

<details>
<summary>redirect loop logs</summary>

```text
10.42.0.1 - - [04/Feb/2023:12:19:44 +0000] "GET / HTTP/2.0" 401 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 0 0.014 [myservice-myservice-app] [] <external_ip>:8443 0 0.010 401 a61235911c42dd1ab87b934ec70c931c
12
10.42.0.1 - - [04/Feb/2023:12:19:44 +0000] "GET / HTTP/2.0" 302 138 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 279 0.014 [myservice-myservice-app] [] - - - - a61235911c42dd1ab87b934ec70c931c
11
10.42.0.1 - - [04/Feb/2023:12:19:44 +0000] "GET /oauth2/start?rd=https://myservice.example.com:8443%2F HTTP/2.0" 302 418 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 313 0.001 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.159:4180 418 0.001 302 fa45ae9637c5d6602aa8c22a0b74d60b
10
10.42.0.1 - - [04/Feb/2023:12:19:52 +0000] "GET /oauth2/callback?state=QlCPwnbixcnlaYJF_hnttW0Ty2FeHWajBdcEmhM7Mw0%3Ahttps%3A%2F%2Fmyservice.example.com%3A8443%2F&code=4%2F0AWtgzh4MeAGYEfLhLHy4qtm3HRqc29Ua1gNy7LnOOjxTYzC4KLOjA8mzA358rLts4CIJbg&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=consent HTTP/2.0" 302 51 "https://accounts.google.lt/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 471 0.182 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.159:4180 51 0.182 302 bac548487fb52ecf69c4374ffda2cd34
9
10.42.0.1 - - [04/Feb/2023:12:19:52 +0000] "GET /oauth2/auth HTTP/1.1" 401 13 "https://accounts.google.lt/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 710 0.001 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.159:4180 13 0.001 401 074aee524c7afafe26902dedaf64d3f2
8
10.42.0.1 - - [04/Feb/2023:12:19:52 +0000] "GET / HTTP/2.0" 401 0 "https://accounts.google.lt/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 0 0.016 [myservice-myservice-app] [] <external_ip>:8443 0 0.017 401 074aee524c7afafe26902dedaf64d3f2
7
10.42.0.1 - - [04/Feb/2023:12:19:52 +0000] "GET / HTTP/2.0" 302 138 "https://accounts.google.lt/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 45 0.016 [myservice-myservice-app] [] - - - - 074aee524c7afafe26902dedaf64d3f2
6
10.42.0.1 - - [04/Feb/2023:12:19:52 +0000] "GET /oauth2/start?rd=https://myservice.example.com:8443%2F HTTP/2.0" 302 418 "https://accounts.google.lt/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 1460 0.000 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.159:4180 418 0.000 302 492fd25feb7ee9ed3a9b597b6a43ada2
5
10.42.0.1 - - [04/Feb/2023:12:19:54 +0000] "GET /oauth2/callback?state=1GWP2RSev70DMGv1p74hd_wE107zX0D9V_G7AbFbHiA%3Ahttps%3A%2F%2Fmyservice.example.com%3A8443%2F&code=4%2F0AWtgzh68R9UEaQxeXMKr9_FsHqmpdP8arXDEZekOtw0Q0KzX_n5bkfPchkIgOMnX6WvATA&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=consent HTTP/2.0" 302 51 "https://accounts.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 468 0.132 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.159:4180 51 0.132 302 51432869ef7a371f26a61e630636ae9f
4
10.42.0.1 - - [04/Feb/2023:12:19:54 +0000] "GET /oauth2/auth HTTP/1.1" 401 13 "https://accounts.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 731 0.000 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.159:4180 13 0.000 401 935c8a52bb77c2ff7adb51ecf637b260
3
10.42.0.1 - - [04/Feb/2023:12:19:54 +0000] "GET / HTTP/2.0" 401 0 "https://accounts.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 0 0.013 [myservice-myservice-app] [] <external_ip>:8443 0 0.013 401 935c8a52bb77c2ff7adb51ecf637b260
2
10.42.0.1 - - [04/Feb/2023:12:19:54 +0000] "GET / HTTP/2.0" 302 138 "https://accounts.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 39 0.013 [myservice-myservice-app] [] - - - - 935c8a52bb77c2ff7adb51ecf637b260
1
10.42.0.1 - - [04/Feb/2023:12:19:54 +0000] "GET /oauth2/start?rd=https://myservice.example.com:8443%2F HTTP/2.0" 302 418 "https://accounts.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" 1563 0.001 [oauth2-proxy-oauth2-proxy-4180] [] 10.42.0.159:4180 418 0.001 302 a06635741674ea324b5a6058d6c064ac
```

</details>

## Your Environment

- Version used: 7.4.0
- Ingress-nginx controller 1.5.1

**Comment by AurimasNav** [comment]
So while compiling all the logs into the issue, I was actually able to figure this out, but still posted it for anyone who will stumble upon this.
It all comes down to [this statement](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#config-file) in the docs being not entirely true: 
> https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#config-file

it seems that there is no ENV equivalent for --cookie-domain, I can't write/read go, but quick repo search did not produce any results for OAUTH_PROXY_COOKIE_DOMAIN, so after adding argument to deployment manifest it all works now.

```yaml
    spec:
      containers:
      - name: oauth2-proxy
        args:
          - --cookie-domain=.example.com
```
