### ISSUE TITLE
Redirected you too many times

### ISSUE THREAD

**Issue by shinebayar-g** [oauth2-proxy/oauth2-proxy#2002]
Looks like I'm misconfiguring the application. Could someone take a look at my configuration? I'm trying to put oauth2-proxy in front of my ArgoCD application.

## Expected Behavior

Secure K8s Ingresses.

## Current Behavior

I'm getting "<url> redirected you too many times." error.

## Steps to Reproduce

1. Deploy Helm chart version: 6.8.0 (Oauth2 Proxy version: 7.4.0)
Helm values:
```yaml
config:
    clientID: GITHUB_OAUTH_APP_CLIENT_ID
    clientSecret: GITHUB_OAUTH_APP_CLIENT_SECRET
    cookieSecret: <"openssl rand -base64 32 | head -c 32 | base64"> value here
    cookieName: '_oauth2_proxy_1'
    configFile: |-
        provider = "github"
        github_org = "MyOrg"
        scope = "user:email read:org"
        email_domains = ["*"]
        reverse_proxy = "true"
        whitelist_domains = [".dev.myorg.app"]
        cookie_domains = [".dev.myorg.app"]
ingress:
    enabled: true
    className: nginx
    hosts:
        - auth.dev.myorg.app
```

ArgoCD Ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://auth.dev.myorg.app/oauth2/start?rd=https://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.dev.myorg.app/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
          if ngx.var.name_upstream_1 ~= "" then
              ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
          end
      }
  name: argocd-server
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.dev.myorg.app
    http:
      paths:
      - backend:
          service:
            name: argo-cd-argocd-server
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
```

Github Oauth App settings
**Homepage URL**: https://auth.dev.myorg.app
**Authorization callback URL**: https://auth.dev.myorg.app/oauth2/callback

I'm able to sign in to Oauth2-proxy's own endpoint at https://auth.dev.myorg.app . I see the `Sign in with Github` button and I'm able to sign in successfully. Once I'm signed in, it shows `404 page not found` response which I believe coming from oauth2-proxy pod.

However, when I go to `argocd.dev.myorg.app` I'm getting `redirected you too many times.` response. If I clear my cookies, this url successfully redirects me to Github Sign in page. But as soon as I'm signed in, I'm redirected back to `argocd.dev.myorg.app` where I stuck at too many redirect loop.

This is hosted on EKS. Traffic workflow looks like:

Browser -> AWS Network Load Balancer (TLS:443) -> Ingress Nginx Controller (HTTP:80) -> Ingress (HTTP:80).
I had very similar setup working on 6.x version with Google provider. Looking at docs, it should've work this time.. 🤔
