### ISSUE TITLE
Google provider allowed groups returning unauthorized for group with everyone

### ISSUE THREAD

**Issue by adrianwebb** [oauth2-proxy/oauth2-proxy#2012]
Hello, I am having a bit of an issue here.  I am setting up the oauth2-proxy behind the nginx ingress controller with the Google identity provider with the aim of authenticating via group email membership.

## Expected Behavior

The expected behavior according to all the documentation is that oauth2-proxy should be able to restrict access via Google workspace groups.  The documentation supports this, and there are clearly options and Go functionality for allowing this feature.

## Current Behavior

I have managed to get the Google provider working with allowed emails, and that authenticates alright but every time I try to switch to group membership checking I get unauthorized (even though my user is Google super admin and I am the owner of the group in question), and I am seeing strange redirect errors in the logs.  I have searched every issue I could find, looked at all tutorials, and spent a lot of time trying different combinations of configurations, and nothing seems to help.  So I am reaching out here in hopes that some enlightened google oauth2-proxy expert will know where to go, what to try, what could be wrong, really anything at this point.

I am getting the following log messages from the oauth2-proxy pod:

```
10.0.0.6 - 666...404 - - [2023/02/11 23:11:11] auth.${domain} GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0" 401 13 0.000
10.0.0.7 - 93b...115 - - [2023/02/11 23:11:11] auth.${domain} GET - "/oauth2/start?rd=https://subdomain.${domain}%2F" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0" 302 414 0.000
[2023/02/11 23:11:26] [internal_util.go:69] 200 GET https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=ya...Ku... {
  "issued_to": "xxxxxx.apps.googleusercontent.com",
  "audience": "xxxxxx.apps.googleusercontent.com",
  "user_id": "1...7",
  "scope": "openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile",
  "expires_in": 3599,
  "email": "user@${domain}",
  "verified_email": true,
  "access_type": "offline"
}

10.0.0.7 - bb9...647 - user@${domain} [2023/02/11 23:11:26] [AuthFailure] Invalid authentication via OAuth2: unauthorized
[2023/02/11 23:11:26] [validator.go:63] Rejecting invalid redirect "/oauth2/callback?state=1F...08:https://subdomain.${domain}/&code=4/0A...3A&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&authuser=0&hd=${domain}&prompt=consent": not an absolute or relative URL
[2023/02/11 23:11:26] [director.go:85] Invalid redirect generated from X-Forwarded-Uri header: /oauth2/callback?state=1F...08:https://subdomain.${domain}/&code=4/0A...3A&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&authuser=0&hd=${domain}&prompt=consent
10.0.0.7 - bb9...647 - - [2023/02/11 23:11:26] auth.${domain} GET - "/oauth2/callback?state=1F...08:https://subdomain.${domain}/&code=4/0A...3A&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&authuser=0&hd=${domain}&prompt=consent" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0" 403 2759 0.323
```

## Possible Solution

I have no clue what the problem is, much less a viable solution.  That's why I'm here :-)

## Steps to Reproduce (for bugs)

Below is a breakdown of the current configurations:

***Secrets:***
```
origin-cert:
  data:
    "server.key": "${certificate_key}"
    "server.crt": "${certificate_cert}"

google-auth-credential:
  data:
    "service-account.json": '${oauth_google_auth_credential}' # I have tested group access and attachment of this service account through Google in ArgoCD Dex and it works flawlessly

credentials:
  data:
    "cookie-secret": "${oauth_cookie_secret}"
    "client-id": "${oauth_ingress_google_client_id}"
    "client-secret": "${oauth_ingress_google_client_secret}"
```

***Oauth2 Proxy values:***
```
config:
  existingSecret: credentials

  google:
    useApplicationDefaultCredentials: false
    existingSecret: google-auth-credential

    adminEmail: "${oauth_google_admin_account}"
    groups:
      - everybody@${domain}

extraArgs:
  provider: google

  allowed-group: everybody@${domain}
  scope: "openid email profile"

  redirect-url: "https://auth.${domain}/oauth2/callback"
  set-xauthrequest: true
  cookie-secure: false
  pass-access-token: true
  pass-user-headers: true
  reverse-proxy: true

  whitelist-domain: ".${domain}"
  email-domain: ".${domain}"
  cookie-domain: ".${domain}"
  cookie-samesite: "lax"

  show-debug-on-error: true
  pass-authorization-header: true
  set-authorization-header: true
  standard-logging: true
  auth-logging: true
  request-logging: true
  skip-provider-button: false

ingress:
  enabled: true
  path: /
  hosts:
    - auth.${domain}
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - secretName: origin-cert
      hosts:
        - auth.${domain}
```

***Ingress annotations:***
```
nginx.ingress.kubernetes.io/auth-url: "https://auth.${domain}/oauth2/auth"
nginx.ingress.kubernetes.io/auth-signin: "https://auth.${domain}/oauth2/start"
nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Forwarded-Access-Token"
nginx.ingress.kuberentes.io/auth-request-redirect: "https://subdomain.${domain}/"
nginx.ingress.kubernetes.io/proxy-body-size: 100m
```

I know a lot of those options aren't necessary but I have been playing around with every possible combination that might help, all with the same log messages above.  I know the Google service account can grab the organization groups because it works with ArgoCD and Dex perfectly.

## Context

I can't allow access based on Google groups when my other apps that have Oauth integrated, such as ArgoCD, use groups to limit access internally just fine.  While I can certainly use individual emails this is not a viable strategy going forward as the organization grows, and this feature should work.  Either I'm doing something wrong, documentation is wrong, or there is a bug.  Thanks for your help!

## Your Environment

kubernetes: Managed DigitalOcean
repository: https://oauth2-proxy.github.io/manifests
chart: oauth2-proxy
version: 6.8.0
