### ISSUE TITLE
Help with OIDC and ORCID authentication error debugging

### ISSUE THREAD

**Issue by rukayaj** [oauth2-proxy/oauth2-proxy#2026]
We would like to use oauth2-proxy on kubernetes to allow users to log into a web application using their https://orcid.org credentials. 

## Current Behavior

The ingress for the web app looks like this: 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: label-extractor-ingress
  labels:
    name: label-extractor-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.svc.gbif.no/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.svc.gbif.no/oauth2/start?rd=https%3A%2F%2Fle.svc.gbif.no" 
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization,X-Auth-Request-User,X-Auth-Request-Email,X-Forwarded-Email,X-Forwarded-User,X-Roles,X-Forwarded-Proto,X-Forwarded-Host,X-Forwarded-Uri,X-Auth-Request-Redirect
spec:
  rules:
    - host: le.svc.gbif.no
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: label-extractor
                port:
                  number: 80
  tls:
    - hosts:
        - le.svc.gbif.no
      secretName: cert
```

I'm using the oauth2-proxy helm chart, like this: `helm upgrade oauth2-proxy --install oauth2-proxy/oauth2-proxy --reuse-values --values oauth2-proxy/oauth2-proxy-config.yaml`

And `oauth2-proxy/oauth2-proxy-config.yaml` looks like this:

```
config:
  existingSecret: oauth2-orcid
  configFile: |
    email_domains = [ "*" ]
    whitelist_domains = [ ".svc.gbif.no" ]
    oidc_email_claim = "id"
    set_xauthrequest = true
    set_authorization_header = true
    pass_authorization_header = true 
    pass_host_header = true
    pass_access_token = true
    scope = "openid"
    pass_user_headers = true
    cookie_refresh = "1m"
    cookie_expire = "30m"
    cookie_domains = [ ".svc.gbif.no" ]
    cookie_csrf_per_request = true
    cookie_csrf_expire = "1m"
    ssl_insecure_skip_verify = true

extraArgs:
  whitelist-domain: ".svc.gbif.no"
  cookie-domain: ".svc.gbif.no"
  provider: oidc
  oidc-issuer-url: "https://orcid.org"
  redirect-url: "https://auth.svc.gbif.no/oauth2/callback"
  skip-oidc-discovery: "true"
  login-url: "https://orcid.org/oauth/authorize"
  redeem-url: "https://orcid.org/oauth/token"
  validate-url: "https://orcid.org/oauth/userinfo"
  oidc-jwks-url: "https://orcid.org/oauth/jwks"
  cookie-secure: "true"
  user-id-claim: oid
  oidc-email-claim: "email"
  insecure-oidc-allow-unverified-email: "true"

authenticatedEmailsFile:
  enabled: false

ingress:
  enabled: true
  path: /
  hosts:
    - auth.svc.gbif.no
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Forwarded-Email,X-Forwarded-User,X-Roles,X-Forwarded-Proto,X-Forwarded-Host,X-Forwarded-Uri,X-Auth-Request-Redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
  tls:
    - hosts:
        - auth.svc.gbif.no
      secretName: oauth-cert
```

So now when I try to access le.svc.gbif.no I get the redirect to log with orcid:

`https://orcid.org/signin?approval_prompt=force&client_id=APP-BT57G03XTKA8Z9GY&redirect_uri=https:%2F%2Fauth.svc.gbif.no%2Foauth2%2Fcallback&response_type=code&scope=openid&state=X1y3h3B1cUG7dhA6V-RdLnO39c3oILHisQkRmZ2Iups:https:%2F%2Fle.svc.gbif.no` 

and thereafter I get two errors in the logs: 

```
[2023/02/23 19:02:23] [validator.go:63] Rejecting invalid redirect "/oauth2/callback?code=TW08di&state=FGODIzZV9PQG2ataTe2zXMbapO02RGwn1OopGhpnejc:https://le.svc.gbif.no": not an absolute or relative URL
10.244.3.111:59070 - dec8d3c766209dd36df96b39d5fca64c - - [2023/02/23 19:02:23] auth.svc.gbif.no GET - "/oauth2/callback?code=TW08di&state=FGODIzZV9PQG2ataTe2zXMbapO02RGwn1OopGhpnejc:https://le.svc.gbif.no" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 500 2837 0.228
[2023/02/23 19:02:23] [oauthproxy.go:830] Error creating session during OAuth2 callback: neither the id_token nor the profileURL set an email
[2023/02/23 19:02:23] [director.go:85] Invalid redirect generated from X-Forwarded-Uri header: /oauth2/callback?code=TW08di&state=FGODIzZV9PQG2ataTe2zXMbapO02RGwn1OopGhpnejc:https://le.svc.gbif.no
[2023/02/23 19:02:24] [oauthproxy.go:959] No valid authentication in request. Initiating login.
```

Trying to fix this, I have kind of just been throwing any remotely relevant sounding config variables into `oauth2-proxy/oauth2-proxy-config.yaml` that I found on google. Nothing seems to make any difference. I would really appreciate it if someone could point me in the right direction.
