### ISSUE TITLE
allowed_group for oidc provider with custom group claim does not work anymore with 7.3.0 and 7.40

### ISSUE THREAD

**Issue by lumoVWGS** [oauth2-proxy/oauth2-proxy#2032]
When setting allowed_groups with provider oidc and a custom group claim we get a "403 - forbidden" for all secured endpoints with image versions > 7.2.1

## Expected Behavior

allowed_group parameter should lead to listed idp group members are allowed to oauth2 protected sites even after version 7.2.1

## Current Behavior

with version 7.3.0 and higher everybody gets denied on oauth2 proxy proctected sites with a http 403

## Steps to Reproduce (for bugs)

installation via helmchart - we are using **chart version 6.9.0** as this is the only one that supports a list for command line arguments, which we need to define more than one allowed group.

this is the values.yaml with which it is working (anynomised):

```
config:
  existingSecret: oauth-client

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  tag: v7.2.1

extraArgs: 
- --http-address=0.0.0.0:4180
- --https-address=0.0.0.0:443
- --cookie-domain=.webapps.example.io
- --oidc-issuer-url=https://login.example.com/
- --pass-access-token=true
- --pass-authorization-header=true
- --pass-user-headers=true
- --provider=oidc
- --redirect-url=https://oauth2.sub-eu-dev.webapps.example.io/oauth2/callback
- --set-authorization-header=true
- --set-xauthrequest=true
- --skip-provider-button=true
- --upstream=file:///dev/null
- --whitelist-domain=.webapps.example.io
- --oidc-groups-claim=https://msi.example.com/groups
- --allowed-group=idp-group1
- --allowed-group=idp-group2
- --allowed-group=idp-group3

ingress:
  enabled: true
  className: nginx
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: 'true'
  hosts:
  - oauth2.cocos-${CLUSTER_REGION}-${CLUSTER_STAGE}${CLUSTER_NUMBER}.webapps.example.io
  path: /oauth2
  tls:
  - hosts:
    - oauth2.cocos-${CLUSTER_REGION}-${CLUSTER_STAGE}${CLUSTER_NUMBER}.webapps.example.io
    secretName: wildcard-certificate-tls
priorityClassName: "cocos-infra-pod-priority"

resources:
  limits:
    cpu: 20m
    memory: 30Mi
  requests:
    cpu: 2m
    memory: 10Mi
```

with an higher image version, we get all 403s:

```
config:
  existingSecret: oauth-client

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  tag: v7.4.0

extraArgs: 
- --http-address=0.0.0.0:4180
- --https-address=0.0.0.0:443
- --cookie-domain=.webapps.example.io
- --oidc-issuer-url=https://login.example.com/
- --pass-access-token=true
- --pass-authorization-header=true
- --pass-user-headers=true
- --provider=oidc
- --redirect-url=https://oauth2.sub-eu-dev.webapps.example.io/oauth2/callback
- --set-authorization-header=true
- --set-xauthrequest=true
- --skip-provider-button=true
- --upstream=file:///dev/null
- --whitelist-domain=.webapps.example.io
- --oidc-groups-claim=https://msi.example.com/groups
- --allowed-group=idp-group1
- --allowed-group=idp-group2
- --allowed-group=idp-group3

ingress:
  enabled: true
  className: nginx
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: 'true'
  hosts:
  - oauth2.sub-${CLUSTER_REGION}-${CLUSTER_STAGE}${CLUSTER_NUMBER}.webapps.example.io
  path: /oauth2
  tls:
  - hosts:
    - oauth2.sub-${CLUSTER_REGION}-${CLUSTER_STAGE}${CLUSTER_NUMBER}.webapps.example.io
    secretName: wildcard-certificate-tls
priorityClassName: "infra-pod-priority"

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 2m
    memory: 10Mi
```

## Context

All webapps in our kubernetes cluster that are secured with an according ingress annotation get a 403 with version 7.3.0 or higher

## Your Environment

See ingress configuration snippet of an affected application:

```
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://oauth2.sub-${CLUSTER_REGION}-${CLUSTER_STAGE}${CLUSTER_NUMBER}.webapps.example.io/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.sub-${CLUSTER_REGION}-${CLUSTER_STAGE}${CLUSTER_NUMBER}.webapps.example.io/oauth2/start?rd=https%3A%2F%2F$${q}host$${q}request_uri"
```

- Version used:

7.3.0, 7.4.0
