### ISSUE TITLE
oauth2-proxy in Docker getting nginx 502 with quay.io but working with bitnami

### ISSUE THREAD

**Issue by benni336** [oauth2-proxy/oauth2-proxy#2060]
Hi,
following online tutorials I ended up using the bitnami docker image  V.7.2.1 (because of github issues with latest)
#1802 pointed me to the "official" quay.io image, which I can't get running. I thought it would be just replacing the image resource in docker-compose, but obviously there is something more to do.

If I would know, I would like to offer updating the docs if wanted.

## Setup
Standard setup: ngninx does TLS termination and forwards request to oauth2 proxy if authentication fails or forwards to the application.
The nginx config follows [official recommendations](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/tls#terminate-tls-at-reverse-proxy-eg-nginx)

## Expected Behavior
Changing the image from bitnami to quay.io should not change the response of oauth2 proxy.

## Current Behavior
nginx shows 502 internal server error. Oauth2-proxy does not recieve any requests.
From the logs:
```
2023/03/22 17:41:42 [error] 23#23: *19036 connect() failed (111: Connection refused) while connecting to upstream, client: REQUESTIP, server: SUB.MYDOMAIN.COM, request: "GET / HTTP/1.1", subrequest: "/oauth2/auth", upstream: "http://172.27.0.4:4180/oauth2/auth", host: "SUB.MYDOMAIN.COM"
2023/03/22 17:41:42 [error] 23#23: *19036 auth request unexpected status: 502 while sending to client, client: REQUESTIP , server: SUB.MYDOMAIN.COM, request: "GET / HTTP/1.1", host: "SUB.MYDOMAIN.COM"
```
SUB.MYDOMAIN.COM and REQUESTIP have been replaced to mask my personal information.
This lead me to insight that OAuth2-Proxy might not recieve the request or something within docker is blocking it.
This is true so far. There is nothing in the logs for OAuth2-Proxy showing the request of nginx.

But just changing the image back to bitnami makes it work. So I guess I am just missing some config step or so.

Here is my docker network to proof configuration:
```
[
    {
        "Name": "default-net",
        "Id": "7b8e07ba8573a836929b2e34cc0e0d44b6e9b1ce17196fde2d67103dd3142572",
        "Created": "2023-03-17T01:21:46.296280953+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.27.0.0/16",
                    "Gateway": "172.27.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0bf2fbdc5a6e6f9a35d7fc9a49011bb39cb6385c642d0f5b4d3a749cbd3ee727": {
                "Name": "oauth2-proxy",
                "EndpointID": "d167455931bc0a178ed3e31eab1084f34790af968dd6961ecabba65006a9fc56",
                "MacAddress": "02:42:ac:1b:00:04",
                "IPv4Address": "172.27.0.4/16",
                "IPv6Address": ""
            },
            "1c7c75065b50ecadfdec928ce835b14b18eac6aede7c03c2a6b549e9dd79012a": {
                "Name": "proxy_server",
                "EndpointID": "12ca917d5267c768a0d0970410dd234d7b790f9574fa075ae7b9d2a0eda27211",
                "MacAddress": "02:42:ac:1b:00:03",
                "IPv4Address": "172.27.0.3/16",
                "IPv6Address": ""
            },
            "c88f5725ed61e5069e6099b10ccbff36555d112f56b9446a880cf77daca337fc": {
                "Name": "request-app",
                "EndpointID": "f31945e68528691fcd629fc84ea1f204532affd8aaaffdddf4c66d2577808803",
                "MacAddress": "02:42:ac:1b:00:02",
                "IPv4Address": "172.27.0.2/16",
                "IPv6Address": ""
            }
        }
    }
]
```

This is my docker-compose. As i said, I just change the image source to bitnami and it works
```
services:
  request-app:
    image: my-request-app
    container_name: request-app
    expose:
      - '8080'
  oauth2-proxy:
    # image: bitnami/oauth2-proxy:7.2.1
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    container_name: oauth2-proxy
    restart: always
    depends_on:
      - request-app
    expose:
      - '4180'
    networks:
       - default-net
    environment:
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_GITHUB_USERS=benni336
      - OAUTH2_PROXY_UPSTREAMS=http://request-app:8080
      - OAUTH2_PROXY_COOKIE_SECRET=xxx
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_CLIENT_ID=xxx
      - OAUTH2_PROXY_CLIENT_SECRET=xxx
      - OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR=true
      - OAUTH2_PROXY_REDIRECT_URL=https://SUB.MYDOMAIN.COM/oauth2/callback

networks:    [...]
```
request-app, is currently just a simple node app returning headers as json.

Even though this was running with bitnami, just staying at bitnami is not really a solution to me. I have problems recieving the user info via header and because of #1802 I just have doubts how the bitnami is preconfigured.

I hope that my problem might be obvious to one of you as I am literally smashing my head on this problem since three days.
May the stupidness only belong to me.

Best and thanks for this great project!
