### ISSUE TITLE
Authenticating inside iframe (same domain)

### ISSUE THREAD

**Issue by joeldeteves** [oauth2-proxy/oauth2-proxy#2062]
Hello, we have an nginx deployment serving static content for our WikiJS instance.

- NGINX is configured behind Traefik + oauth2-proxy
- WikiJS is behind Traefik and uses built-in Azure auth.
- Anything that gets passed to the `/static` path e.g. `wiki.domain.com/static` gets routed to NGINX/oauth2-proxy, whereas everything else goes to the WikiJS instance `wiki.domain.com`

What we are trying to do is serve static HTML content inside iframes (a workaround because WikiJS renders html with it's own formatting, which we do not want for this particular content).

I've tested this without oauth2-proxy and it works great - but we want to protect this content behind a transparent AAD login (hence using oauth2-proxy, which we already use on other services with great results in our AAD SSO environment).

The problem is when oauth2-proxy is enabled, the content doesn't load on first login - it throws `[AuthFailure] Invalid authentication via OAuth2: CSRF token mismatch, potential attack`

After refreshing the page, the content loads normally.

## Desired Behavior
If already authenticated to AAD, oauth2-proxy should allow loading of the content inside the iframes

## Current Behavior
Iframes fail to load with a 403 error until the page is refreshed

## Possible Solution
I tried the following:
- Setting `cookie-samesite` to 'none' and 'lax'
- Setting `cookie-csrf-per-request` to `true`

Neither of these worked.

I also tried the following Middleware in Traefik, however enabling trustForwardHeader cause all requests to redirect to `wiki.domain.com/oauth2/callback` as opposed to `login.mydomain.com/oauth2/callback`, resulting in a login loop

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
   name: forwardauth
   namespace: wikijs
spec:
  forwardAuth:
    address: "https://login.mydomain.com/"
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
```

## Steps to Reproduce (for bugs)
1. Authenticate to Azure
2. In the same browser session, try to access content in an iframe which is protected by oauth2-proxy

## Context
It would be very useful and helpful to us if we can have 'single sign on' pass into iframes as it does with our other oauth2-proxy protected services

## Your Environment
- Kubernetes 1.23.14
- oauth2-proxy 7.3.0
- NGINX 1.23

Thank you,
