### ISSUE TITLE
Oauth2-proxy & forwardAuth : after authentication, auth2-proxy redirect to forwardAuth's adress instead of upstream adress

### ISSUE THREAD

**Issue by RonanMorgan** [oauth2-proxy/oauth2-proxy#2084]
Hello,

I am using the trafik middleware in order to foward my calls to oauth2-proxy : 

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: forward-auth-to-keycloak
  namespace: arkhn
spec:
  forwardAuth:
    address: http://platform-oauth2-proxy.mycompany.svc.cluster.local/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
      - X-Auth-Request-Redirect
```

I can authenticate correctly (a cookie is created & populated) but when I do a second call to my application, I have the following error in traefik logs : 
 
> time="2023-04-14T15:58:11Z" level=debug msg="Remote error http://platform-oauth2-proxy.mycompany.svc.cluster.local/. StatusCode: 307" middlewareName=forward-auth-to-keycloak@kubernetescrd middlewareType=ForwardedAuthType

and the following log in oauth2-proxy logs : 

> 10.42.1.155:47254 - 3817fd29-4c92-4358-bac1-c90a1e28acf6 - name@mycompany.com [2023/04/14 15:58:11] platform-oauth2-proxy.mycompany.svc.cluster.local GET / "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0" 307 0 0.016

but the internal adresse "platform-oauth2-proxy.mycompany.svc.cluster.local" is not used in oauth2-proxy conf, I thought that it should forward to the upstream usl which is "http://platform-myapplication.mycompany.svc.cluster.local/"

Do you have any clues ?
Thanks,
Ronan Sy
