### ISSUE TITLE
Redirect to wrong url after login with github

### ISSUE THREAD

**Issue by c-dev-acc1** [oauth2-proxy/oauth2-proxy#2092]
## Expected Behavior

Redirect to my app at `https://app.example.com/myapp`

## Current Behavior

Redirect to `https://auth.example.com/`

## Your Environment

- Microk8s 1.26
- ingress-nginx: https://kubernetes.github.io/ingress-nginx
- Oauth2-proxy: https://quay.io/repository/oauth2-proxy/oauth2-proxy?tab=tags&tag=latest

### Oauth2-proxy:
```
http_address = "0.0.0.0:4180"
https_address = ":443"
upstreams = [
  "file:///dev/null"
]
email_domains = "*"
provider = "github"
client_id = "myid"
client_secret = "mysecret"
scope = "user:email read:user read:org"
cookie_secret = "aVYba9oi7Aqnl7QcbeMtLOFtQETwHDl5NTfVbI73d0E="
cookie-domains = "*.example.com"
whitelist_domains = "*.example.com"
```

Oauth2-proxy ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  ingressClassName: nginx
  rules:
  - host: auth.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
  tls:
  - hosts:
    - auth.example.com
    secretName: tls-example.com
```

### My app ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:  
  name: myapp
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://auth.example.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.example.com/oauth2/start?rd=$scheme://$host$request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
spec:
  ingressClassName: nginx
  rules:
  - host: app.example.com
    http:
      paths:
      - path: /myapp
        pathType: Exact   
        backend:
          service:
            name: myapp
            port:   
              number: 80
  tls:
  - hosts:
      - app.example.com
    secretName: tls-example.com
```
