### ISSUE TITLE
[oauthproxy.go:959] No valid authentication in request. Initiating login.

### ISSUE THREAD

**Issue by code-acc1** [oauth2-proxy/oauth2-proxy#2093]
## Expected Behavior

My hello-world app show this:
```
Hello, world!
Version: 1.0.0
Hostname: hello-6f69c4fd96-tw78b
```

## Current Behavior

Bad gateway Error code 502.

oauth2-proxy log
```
10.1.116.165:58000 - 726bf1be9fbe75f58c447d7516a64390 - - [2023/04/21 18:00:02] auth.mydomain.com GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48" 403 8508 0.021
10.1.116.165:47018 - c80535cea50769a883e5ea6c61baaadd - - [2023/04/21 18:09:02] auth.mydomain.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48" 401 13 0.000
10.1.116.165:47026 - 6d0825a04622ba48f90fb62f2752d9b2 - - [2023/04/21 18:09:02] auth.mydomain.com GET - "/oauth2/start?rd=https%3A%2F%2Ftest.mydomain.com/hello" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48" 302 386 0.000
10.1.116.165:47026 - 61fe845514cb51ffc928dd9fb998b321 - myemail@gmail.com [2023/04/21 18:09:27] [AuthSuccess] Authenticated via OAuth2: Session{email:myemail@gmail.com user: PreferredUsername:myusername token:true id_token:true created:2023-04-21 18:09:27.871049639 +0000 UTC m=+22227.730390829 expires:2023-04-21 18:14:27.869984114 +0000 UTC m=+22527.729325354 refresh_token:true groups:[cluster-admin cluster-view]}
10.1.116.165:47026 - 61fe845514cb51ffc928dd9fb998b321 - - [2023/04/21 18:09:27] auth.mydomain.com GET - "/oauth2/callback?state=fbucQRQWAD7aizB5mywnO6-WBlkIy_rr-XYfA88aLgw%3Ahttps%3A%2F%2Ftest.mydomain.com%2Fhello&session_state=5317ac4c-8a25-4f56-a116-463f81755559&code=fe688f00-6e3f-4231-81bf-ed77d940b0d0.5317ac4c-8a25-4f56-a116-463f81755559.8c8c8b4d-ea20-433f-bd10-e6faad679e53" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48" 302 52 0.366
[2023/04/21 18:09:28] [oauthproxy.go:959] No valid authentication in request. Initiating login.
10.1.116.165:59882 - 31007c5d9aeaab9b702675d0ba62856c - - [2023/04/21 18:09:28] auth.mydomain.com GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48" 403 8508 0.000
```

## My Environment

Microk8s 1.26
ingress-nginx: https://kubernetes.github.io/ingress-nginx
Oauth2-proxy: https://quay.io/repository/oauth2-proxy/oauth2-proxy?tab=tags&tag=latest
hello-world: gcr.io/google-samples/hello-app:1.0

## My config:

Oauth2-proxy:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy
data:
  oauth2-proxy.cfg: |
    http_address = "0.0.0.0:4180"
    https_address = ":443"
    upstreams = [
      "file:///dev/null"
    ]
    email_domains = "*"
    provider = "keycloak-oidc"
    client_id = "kube-api"
    client_secret = "TJ8pS3MOWQJw32wuWiLQKJvUTpFU76q8"
    oidc_issuer_url = "https://iam.mydomain.com/realms/mk8s"
    redirect_url = "https://auth.mydomain.com/oauth2/callback"
    scope = "openid"
    cookie_secret = "aVYba9oi7Aqnl7QcbeMtLOFtQETwHDl5NTfVbI73d0E="
    cookie_domains = ".mydomain.com"
    whitelist_domains = ".mydomain.com"
```

Oauth2-proxy ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  ingressClassName: nginx
  rules:
  - host: auth.mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
  tls:
  - hosts:
    - auth.mydomain.com
    secretName: tls-mydomain.com
```

Hello-world ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:  
  name: hello
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: "https://auth.mydomain.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.mydomain.com/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
spec:
  ingressClassName: nginx
  rules:
  - host: test.mydomain.com
    http:
      paths:
      - path: /hello
        pathType: Exact   
        backend:
          service:
            name: hello
            port:   
              number: 80
  tls:
  - hosts:
      - test.mydomain.com
    secretName: tls-mydomain.com
```
