### ISSUE TITLE
--extra-jwt-issuers not accepting token with other aud

### ISSUE THREAD

**Issue by rufreakde** [oauth2-proxy/oauth2-proxy#2106]
## Expected Behavior

m2m Request should be validated with JWKS and returned with OK:
```yaml
- --extra-jwt-issuers={{ .Values.ingress.ias.iss }}=aud1,{{ .Values.ingress.ias.iss }}=aud2
- --oidc-jwks-url=https://{{ .Values.ingress.ias.iss }}/oauth2/certs
- --skip-jwt-bearer-tokens=true
- --set-xauthrequest=true
- --pass-access-token=true
- --set-authorization-header=true
- --pass-authorization-header=true
```

Requests without valid JWT token in Authorization header should be redirected to SSO since those would be User based not m2m.

## Current Behavior

It always triggers an Authorization flow even if the Authorization Header is populated correctly with a valid JWT token. That was issued by the OIDC provider itself. (also no Log in proxy about a try to validate the token with JWKS or something hard to diagnose this could be an improvement)

## Possible Solution

This should not be needed as introspection is a special case but maybe it helps?
https://github.com/oauth2-proxy/oauth2-proxy/pull/1751

Other than that I think it is some kind of bug!

## Steps to Reproduce (for bugs)

1.  Setup Nginx Auth Redirect
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.ingress.dns }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.ingress.dns }}/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization $http_authorization;
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1==" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ template "template-chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.dns }}
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.externalPort }}


```
2. Setup OAuth2 Proxy
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: ingress-direct-proxy
    app: {{ .Values.service.name }}  # A metadata label that can be used to group / filter / search for deployments with that label.
    app.kubernetes.io/name: {{ template "template-chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: ingress-direct-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ingress-direct-proxy
  template:
    metadata:
      labels:
        k8s-app: ingress-direct-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --oidc-issuer-url=https://{{ .Values.ingress.ias.iss }}
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --set-xauthrequest=true
        - --pass-access-token=true
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --whitelist-domain={{ .Values.ingress.dns }}
        - --skip-jwt-bearer-tokens=true
        - --skip-oidc-discovery
        - --login-url=https://up.accounts.ondemand.com/oauth2/authorize
        - --redeem-url=https://up.accounts.ondemand.com/oauth2/token
        - --oidc-jwks-url=https://{{ .Values.ingress.ias.iss }}/oauth2/certs
        - --validate-url=https://{{ .Values.ingress.ias.iss }}/oauth2/userinfo
        - --extra-jwt-issuers={{ .Values.ingress.ias.iss }}={{ .Values.ingress.ias.auds.bom}},{{ .Values.ingress.ias.iss }}={{ .Values.ingress.ias.auds.dc}}
        - --skip-provider-button=true
        - --skip-auth-preflight=true
        - --pass-host-header=true
        - --pass-user-headers=true
        - --show-debug-on-error
        - --request-logging=true
        - --auth-logging=true
        - --standard-logging=true
        - --ssl-insecure-skip-verify=true
        envFrom:
          # OAUTH2_PROXY_CLIENT_ID
          # OAUTH2_PROXY_CLIENT_SECRET
          # OAUTH2_PROXY_COOKIE_SECRET
          - secretRef:
              name: ingress-direct-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: ingress-direct-proxy
    app: {{ .Values.service.name }}  # A metadata label that can be used to group / filter / search for deployments with that label.
    app.kubernetes.io/name: {{ template "template-chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: ingress-direct-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: ingress-direct-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-direct-proxy
  labels:
    app: {{ .Values.service.name }}  # A metadata label that can be used to group / filter / search for deployments with that label.
    app.kubernetes.io/name: {{ template "template-chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.dns }}
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: ingress-direct-proxy
                port:
                  number: 4180

```
3.  Curl endpoint with Authorization header set
```yaml

```
4.  Get SSO redirect instead of JWT validation only

## Context

This blocks our usage of the OAuth2 proxy just for simple JWT validation. Also it worked some weeks ago but stoped working all of a sudden so I am not sure why? The first configuration that worked was even much simpler than this one we try right now.
```yaml
        - --provider=oidc
        - --oidc-issuer-url={{ .Values.ingress.ias.iss }}
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --scope=openid
        - --set-xauthrequest=true
        - --pass-access-token=true
        - --pass-user-headers=true
        - --pass-host-header=true
        - --pass-authorization-header=true
        - --cookie-domain={{ .Values.ingress.dns }}
        - --whitelist-domain={{ .Values.ingress.dns }}
        - --request-logging=true
        - --auth-logging=true
        - --standard-logging=true
        - --skip-jwt-bearer-tokens=true
        - --extra-jwt-issuers={{ .Values.ingress.ias.iss }}={{ .Values.ingress.ias.auds.bom }}
```

## Your Environment
- Version used:
-         image: quay.io/oauth2-proxy/oauth2-proxy:latest

## References
https://github.com/oauth2-proxy/oauth2-proxy/issues/698
https://github.com/oauth2-proxy/oauth2-proxy/issues/773
https://github.com/oauth2-proxy/oauth2-proxy/issues/1034

**Comment by rufreakde** [comment]
Okay I played around with it more and see the following logs which means the JWT token from the header is deemed to not be valid right?
```bash
ingress-direct-proxy-68d875cdf-kd8k5 [2023/05/04 08:36:31] [jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, audience from claim aud with value [8c7d2ead-5379-495b-aad9-5fe1675c20dc] does not match with any of allowed audiences map[0558e865-245f-486b-bc04-a422fa387e25:{}], failed to verify token: oidc: id token issued by a different provider, expected IDP" got "https://IDP"]
ingress-direct-proxy-68d875cdf-kd8k5 127.0.0.1 - 4ccb9523c694b8ebb1e5ad5acc3a92a6 - - [2023/05/04 08:36:31] <domain> GET - "/oauth2/auth" HTTP/1.1 "PostmanRuntime/7.29.2" 401 13 0.051
ingress-direct-proxy-68d875cdf-kd8k5 127.0.0.1 - 6fafa1cf6e08b587c0dcda36000401a7 - - [2023/05/04 08:36:31] domain GET - "/oauth2/start?rd=%2Fapi%2Fv1%2FexecutionPlans" HTTP/1.1 "PostmanRuntime/7.29.2" 302 388 0.000
```

But when I test the token locally with the JWKS, that I can find in the discovery url of the IDP, it is validated correctly. Is it possible to get more detailed logs as to why there is a 401?

**Comment by rufreakde** [comment]
Okay I port forwarded the OAuth2 Proxy pod and accessed the the endpoint with curl with seems to work fine:

```bash
curl -ivL -POST http://localhost:4180/oauth2/auth -d -H "Content-Type: application/json" -H 'Authorization: Bearer <JWT_TOKEN>'
```
Resulted in
```
< HTTP/1.1 202 Accepted
HTTP/1.1 202 Accepted
< Gap-Auth: aud
Gap-Auth: aud
< X-Auth-Request-Access-Token: XXX
X-Auth-Request-Access-Token: XXXX
< X-Auth-Request-Email: aud
X-Auth-Request-Email: aud
< X-Auth-Request-User: aud
X-Auth-Request-User: aud
< Date: Thu, 04 May 2023 08:55:14 GMT
Date: Thu, 04 May 2023 08:55:14 GMT
< Content-Length: 0
Content-Length: 0
```
So it might be nginx related? Does the nginx somehow destroyes the Authorization token header on redirect? mhm 
( I will crossreference this issue on ingress-nginx)
https://github.com/kubernetes/ingress-nginx/issues/9910

**Comment by rufreakde** [comment]
how can I print out the full incoming request with headers and everything on the OAuth2 proxy side like as verbose as possible for debugging later on I can revert it again?

````
noop pause.c v3.2-4a45ae32366
linkerd-proxy [     0.002199s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
linkerd-proxy [     0.002785s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
linkerd-proxy [     0.002798s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
linkerd-proxy [     0.002801s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
linkerd-proxy [     0.002804s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190
linkerd-proxy [     0.002806s]  INFO ThreadId(01) linkerd2_proxy: Local identity is default.REDACTED.identity.linkerd.cluster.local
linkerd-proxy [     0.002809s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
linkerd-proxy [     0.002812s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
linkerd-proxy [     0.023430s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity id=default.REDACTED.identity.linkerd.cluster.local
oauth2-proxy [2023/05/04 09:15:43] [provider.go:55] Performing OIDC Discovery...
oauth2-proxy [2023/05/04 09:15:43] [provider.go:55] Performing OIDC Discovery...
oauth2-proxy [2023/05/04 09:15:43] [provider.go:55] Performing OIDC Discovery...
oauth2-proxy [2023/05/04 09:15:43] [providers.go:145] Warning: Your provider supports PKCE methods ["plain" "S256"], but you have not enabled one with --code-challenge-method
oauth2-proxy [2023/05/04 09:15:43] [proxy.go:83] mapping path "/dev/null" => file system "/dev/null"
oauth2-proxy [2023/05/04 09:15:43] [oauthproxy.go:152] Skipping JWT tokens from configured OIDC issuer: "https://IDP_REDACTED"
oauth2-proxy [2023/05/04 09:15:43] [oauthproxy.go:154] Skipping JWT tokens from extra JWT issuer: "IDP_REDACTED=REDACTED"
oauth2-proxy [2023/05/04 09:15:43] [oauthproxy.go:154] Skipping JWT tokens from extra JWT issuer: "IDP_REDACTED=REDACTED"
oauth2-proxy [2023/05/04 09:15:43] [oauthproxy.go:162] OAuthProxy configured for OpenID Connect Client ID: REDACTED
oauth2-proxy [2023/05/04 09:15:43] [oauthproxy.go:168] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains:bom-resolution.test-ms.spcnatprov.shoot.live.k8s-hana.ondemand.com path:/ samesite: refresh:disabled
Stream closed EOF for REDACTED/ingress-direct-proxy-84467f865c-pzk58 (noop)
oauth2-proxy 127.0.0.1 - 84c3855964ed640ced9adf37fe7eaca9 - - [2023/05/04 09:15:58] bom-resolution.test-ms.spcnatprov.shoot.live.k8s-hana.ondemand.com GET - "/oauth2/auth" HTTP/1.1 "curl/7.87.0" 401 13 0.000
oauth2-proxy 127.0.0.1 - 35e18bc892d9d35ad7945150f54a8013 - - [2023/05/04 09:15:58] bom-resolution.test-ms.spcnatprov.shoot.live.k8s-hana.ondemand.com GET - "/oauth2/start?rd=%2Fapi%2Fv1%2FexecutionPlans" HTTP/1.1 "curl/7.87.0" 302 388 0.000
oauth2-proxy 127.0.0.1 - b4aae848099f46307acc6e4605178d9d - - [2023/05/04 09:16:47] bom-resolution.test-ms.spcnatprov.shoot.live.k8s-hana.ondemand.com GET - "/oauth2/auth" HTTP/1.1 "curl/7.87.0" 401 13 0.000
oauth2-proxy 127.0.0.1 - 52939426ae475bb3f3282e8a2cb01663 - - [2023/05/04 09:16:47] bom-resolution.test-ms.spcnatprov.shoot.live.k8s-hana.ondemand.com GET - "/oauth2/start?rd=%2Fapi%2Fv1%2FexecutionPlans" HTTP/1.1 "curl/7.87.0" 302 388 0.000
```

**Comment by rufreakde** [comment]
Okay after a whole lot of troubleshooting I was finally able to get all the routing to work as expected it is exposing to much information but that I will fix later on. https://github.com/kubernetes/ingress-nginx/issues/9910

There is now a different issue and hence I would rename the Issue post to a more sensible one.

# Additional JWT issuers fails
```
--extra-jwt-issuers={{ .Values.ingress.ias.iss }}={{ .Values.ingress.ias.auds.bom }},{{ .Values.ingress.ias.iss }}={{ .Values.ingress.ias.auds.dc }}
```

is set but I always get 401 on my second JWT which has the aud set of the extra issuer.

**Comment by rufreakde** [comment]
Current Setup:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: ingress-direct-proxy
    app: {{ .Values.service.name }}  # A metadata label that can be used to group / filter / search for deployments with that label.
    app.kubernetes.io/name: {{ template "template-chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: ingress-direct-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ingress-direct-proxy
  template:
    metadata:
      labels:
        k8s-app: ingress-direct-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --set-xauthrequest=true
        - --pass-access-token=true
        - --pass-user-headers=true
        - --pass-host-header=true
        - --pass-authorization-header=true
        - --reverse-proxy=true
        - --cookie-domain={{ .Values.ingress.dns }}
        - --whitelist-domain={{ .Values.ingress.dns }}
        - --request-logging=true
        - --auth-logging=true
        - --standard-logging=true
        - --skip-jwt-bearer-tokens=true
        - --extra-jwt-issuers={{ .Values.ingress.ias.iss }}={{ .Values.ingress.ias.auds.bom }},{{ .Values.ingress.ias.iss }}={{ .Values.ingress.ias.auds.dc }}
        envFrom:
          # OAUTH2_PROXY_CLIENT_ID: 
          # OAUTH2_PROXY_CLIENT_SECRET: 
          # OAUTH2_PROXY_COOKIE_SECRET: 
          # OAUTH2_PROXY_OIDC_ISSUER_URL: 
          # OAUTH2_PROXY_SCOPE: 
          # OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 
          # OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: 
          - secretRef:
              name: ingress-direct-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
```
