### ISSUE TITLE
nginx auth request does not correctly redirect to configured oauth-2 proxy.

### ISSUE THREAD

**Issue by schrodit** [oauth2-proxy/oauth2-proxy#2111]
I deployed the ingress-nginx and configured an ingress as described in the [oauth-proxy nginx docs](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#configuring-for-use-with-the-nginx-auth_request-directive). (See the resource below).

When I try to access the endpoint nginx returns 500 and the log states:
```
2023/05/08 14:21:55 [error] 2915#2915: *18215608 auth request unexpected status: 404 while sending to client, client: 10.250.1.26, server: ts-test.example.com, request: "GET / HTTP/2.0", host: "ts-test.example.com"
10.250.1.26 - - [08/May/2023:14:21:56 +0000] "GET /favicon.ico HTTP/2.0" 404 0 "https://ts-test.example.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" 0 0.056 [upstream-default-backend] [] xxx:443 : xxx:8080 0 : 0 0.053 : 0.003 401 : 404 xxx
2023/05/08 14:21:56 [error] 2915#2915: *18215608 auth request unexpected status: 404 while sending to client, client: 10.250.1.26, server: ts-test.example.com, request: "GET /favicon.ico HTTP/2.0", host: "ts-test.exmaple.com", referrer: "https://ts-test.example.com/"
```

When I log in to another site that is protected by the same oauth2-proxy and the auth cookie is set, I can access the site without issues. So it seems just the redirect to login does not work.
The same configuration works on 2 different clusters.

```yaml
# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.example.com/oauth2/start?rd=$scheme://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth.example.com/oauth2/auth?allowed_groups=my_group@example.com
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_name_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
 
  name: ts-test
  namespace: default
spec:
  rules:
  - host: ts-test.example.com
    http:
      paths:
      - backend:
          service:
            name: ts-test
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ts-test.example.com
    secretName: tls-secret
```

What I already tested:
- different domain -> does not work
- different ingress-nginx versions -> does not work

## Expected Behavior

The request is correctly redirected to our oauth provider to do the login flow.

## Current Behavior

Nginx returns a 500 and does not redirect.

## Possible Solution

Don't know.

## Steps to Reproduce (for bugs)

Not sure. Throw at least that's the things I did:

1.  Deploy the latest ingress-nginx
2.  create a deployment and expose it via the ingress snippet above.
3.  access the page

## Your Environment

- Version used:
  - ingress nignx controller: v1.4.0
  - oauth2-proxy: 7.3.0

Any help how I can try to debug that issue would be appreciated:)
thanks already for your time and help.
