### ISSUE TITLE
Keycloak-OIDC shows Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by dicky1218** [oauth2-proxy/oauth2-proxy#2114]
## Expected Behavior

1.  jaeger (my ingress) redirects me to the oauth2-proxy service
2. Oauth flow happens, I get a callback from Keycloak
3. jaeger redirects the callback to oauth2-proxy
4. Oauth2-proxy lets me into my app

## Current Behavior

1. Jaeger ingress redirects me to the oauth2-proxy service
2. It returned 500 internal server error
---
1. If access to oauth2 ingress, it redirects me to keycloak page
2. keycloak page shows error message: "Invalid parameter: redirect_uri"

## Possible Solution
I don't know why.

## Steps to Reproduce (for bugs)
Jaeger ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    # nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
  name: jaeger-ingress
  namespace: devops
spec:
  rules:
  - host: opentracing-qa.fra1.internal
    http:
      paths:
      - backend:
          service:
            name: jaegertracing
            port:
              number: 16686
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - opentracing-qa.fra1.internal
    secretName: opentracing-secret
```
oauth2-proxy ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /oauth2
  name: oauth2-ingress
  namespace: devops
spec:
  rules:
  - host: opentracing-qa.fra1.internal
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              number: 80
        path: /oauth2
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - opentracing-qa.fra1.internal
    secretName: opentracing-secret
```
oauth2-proxy values file:
```
config:
  existingSecret: oauth2-secret
  configFile: |-
    provider="keycloak-oidc"
    provider_display_name="Keycloak"
    http_address="0.0.0.0:4180"
    email_domains=["*"]
    upstreams=["https://opentracing-qa.fra1.internal"]
    pass_access_token="true"
    pass_user_headers="true"
    pass_authorization_header="true"
    set_authorization_header="true"
    set_xauthrequest="true"
    redirect_url="https://opentracing-qa.fra1.internal/oauth2/callback"
    oidc_issuer_url="https://login-test.solvians.com/realms/devops"
    cookie_domains=["opentracing-qa.fra1.internal"]
    whitelist_domains=["opentracing-qa.fra1.internal"]
    standard_logging="true"
    auth_logging="true"
    cookie_refresh="1m"
    cookie_expire="168h"
    silence_ping_logging="true"
    show_debug_on_error="true"
    scope="email"
    reverse_proxy="true"
    skip_provider_button="true"
    code_challenge_method="S256"
```

## Your Environment

- Version used: 7.4 run through the helm chart

Environment is Kubernetes on Rancher, running nginx-ingress 0.4.3
