### ISSUE TITLE
No Redirect with Azure Auth 

### ISSUE THREAD

**Issue by etiennejournet** [oauth2-proxy/oauth2-proxy#2127]
Hello,

I'm trying to setup a unique oauth2-proxy to authenticate to multiple microservices on Kubernetes and Nginx Ingress Controller.

I'm stuck at the redirect.
After logging into Azure I can see microsoft is calling oauth2-proxy on oauth2/callback with a code, but it's not redirecting (I stay on azure login page) or even showing an error in the logs...
Having read pretty much all the internet on this subject and tested a lot of configurations, I'd be glad if someone could point me to the right direction :)

Here is my Oauth2-Proxy conf from helm values (they get properly provisionned):
```
extraArgs:
  provider: azure
  azure-tenant: ${tenantID}
  oidc-issuer-url: https://login.microsoftonline.com/${tenantID}/v2.0
  redirect-url: "https://service.${domain}"
  whitelist-domain: "${domain}"
  cookie-domain: "${domain}"
  pass-access-token: "true"
  pass-user-headers: "true"
  set-xauthrequest: "true"
  oidc-email-claim: sub
  azure-graph-group-field: "id"

config:
  clientID: ${clientID}
  clientSecret: ${clientSecret}
```

And the Ingresses I'm testing on:
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://auth.${domain}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.${domain}/oauth2/start?rd=https://$host$uri"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: monitoring
  namespace: grafana
spec:
  ingressClassName: nginx
  rules:
  - host: service.${domain}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service
            port:
              number: 80
  tls:
  - hosts:
    - service.${domain}
    secretName: service-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: auth.${domain}
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 80
  tls:
  - hosts:
    - auth.${domain}
    secretName: auth-tls
```

Thanks :)

**Comment by etiennejournet** [comment]
Ok I'm Answering to myself.

I was wrong in the redirect url configured in the service, I thought I had to redirect to my final service when I should have redirected to the auth service.
This `redirect_url` parameter is configuring the callback from the Login Provider to the oauth2-proxy (which in turn redirects to the final service).

```
extraArgs:
  provider: azure
  azure-tenant: ${tenantID}
  oidc-issuer-url: https://login.microsoftonline.com/${tenantID}/v2.0
  redirect-url: "https://auth.${domain}"       # this is the callback URL where i was mistaken
  whitelist-domain: "${domain}"
  cookie-domain: "${domain}"
  pass-access-token: "true"
  pass-user-headers: "true"
  set-xauthrequest: "true"
  oidc-email-claim: sub
  azure-graph-group-field: "id"

config:
  clientID: ${clientID}
  clientSecret: ${clientSecret}
```

Regards,
