### ISSUE TITLE
client jwt support

### ISSUE THREAD

**Issue by kfox1111** [oauth2-proxy/oauth2-proxy#2135]
## Expected Behavior

In the client spec:
https://datatracker.ietf.org/doc/html/rfc7523#section-2.2

Its mentioned you can use jwt's for client auth. Along with Kubernetes projected tokens, this could eliminate the need for handling any client secrets at all.

## Current Behavior

You must maintain client secrets.

## Possible Solution

Support reading the jwt periodically from a file, and use that in authentication with the oidc server.

**Comment by JoelSpeed** [comment]
What do you think it would take to implement this? Sounds like an interesting change to make

**Comment by kfox1111** [comment]
With something like keyloak, I think it can be configured like: https://www.youtube.com/watch?v=blv_nuONnTw except instead of generating a public/private key, I think just use the jwks endpoint of Kubernetes. To generate a projected token, something like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: basic-debian-pod-bound-token
  namespace: default
spec:
  serviceAccountName: default
  containers:
  - image: debian
    name: main
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: my-bound-token
      mountPath: /var/run/secrets/my-bound-token
  volumes:
  - name: my-bound-token
    projected:
      sources:
      - serviceAccountToken:
          path: token
          audience: foobar.com
          expirationSeconds: 3600
```
token readable out of /var/run/secrets/my-bound-token/token then.
