### ISSUE TITLE
Missing X-Auth-Request-Access-Token from Azure AD using correct flags

### ISSUE THREAD

**Issue by pievalentin** [oauth2-proxy/oauth2-proxy#2136]
I want to always receive a JWT token in my backend. So the `X-Auth-Request-Access-Token` is what I need. My understanding is that setting to true both `--pass-access-token` and `--set-xauthrequest` I should have the JWT token in my headers. Thing is, I don't receive any information about the user in my headers. So I opened this issue to know if my config might be missing something.
Context:
  Version: 7.4.0
  Env: Azure k8s (AKS)
  Maybe not relevant but my backend is using FastAPI

## Expected Behavior
Set `--pass-access-token` and `--set-xauthrequest` to true.
Receive the `X-Auth-Request-Access-Token` header with the OAuth JWT token.

## Current Behavior
It's missing the `X-Auth-Request-Access-Token` header 

## Steps to Reproduce (for bugs)
1. Deploy a proxy with this config
Here is my OAuth2 proxy pod config:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    application: myapp-oauth2-proxy
  name: myapp-oauth2-proxy-deployment
  namespace: dsi
spec:
  replicas: 1
  selector:
    matchLabels:
      application: myapp-oauth2-proxy
  template:
    metadata:
      labels:
        application: myapp-oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --azure-tenant="{tenant_id}"
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --oidc-issuer-url=https://login.microsoftonline.com/{tenant_id}/v2.0 
        - --reverse-proxy=true
        - --cookie-refresh=1h
        - --cookie-expire=3h
        - --cookie-secure=true
        # - --pass-user-headers=true
        # - --skip-jwt-bearer-tokens=true
        - --pass-access-token=true
        - --set-xauthrequest=true
        - --pass-authorization-header=true
        name: myapp-oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        imagePullPolicy: Always
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: "{client_id}" # Client ID
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: "{client_secret}" # Client Secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: "xxxxx"  # Cookie Secret
```

2.  Reach my pod and log the headers.
Here are the headers I receive:
```
Headers({'host': 'example.com', 'x-request-id': 'a5fc5c1b2aa8838139c62b3ff8deac66', 'x-real-ip': '10.41.1.77', 
'x-forwarded-for': '10.41.1.77', 'x-forwarded-host': 'example.com', 'x-forwarded-port': '80', 
'x-forwarded-proto': 'http', 'x-forwarded-scheme': 'http', 'x-scheme': 'http', 'x-original-forwarded-for': 'x.x.x.168:10400', 
'x-original-url': '/', 'x-appgw-trace-id': ' dd1175f75472af7b269b22d798236e3f', 
'x-original-host': 'example.com', 'cache-control': 'max-age=0', 
'upgrade-insecure-requests': '1', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Apple WebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36', 
'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8', 
'sec-gpc': '1', 'sec-fetch-site': 'cross-site' , 
'sec-fetch-mode': 'navigate', 
'sec-fetch-user': '?1', 
'sec-fetch-dest': 'document', 'sec-ch-ua': '"Brave";v="113", "Chromium";v="113", "Not-A.Brand";v="24"', 'sec-ch-ua-mobile': '?0', 
'sec-ch-ua-platform': '"Windows"',
 'accept-language': 'en-US,en;q=0.8',
 'referer': 'https://login.microsoftonline.com/', 
'accept-encoding': 'gzip, deflate, br', 'cookie': '_oauth2_proxy_0=xxxx; _oauth2_proxy_1=xxxxxxx'})  
```
Here is the oauth proxy logs:
```
│ x.x.x.77 - f98546ada547b867a2acb47f421d79a3 - PValentin@azureAD.com [2023/06/15 19:20:45] example.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.3 6 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" 202 0 0.000  
```
## Context
My provider is a single tenant app registration in Azure

## Your Environment

- Version used: 7.4.0

What is my config missing to receive the token? Or is it not supported in Azure?
