### ISSUE TITLE
Github Auth - Redirection Issues

### ISSUE THREAD

**Issue by mentlak0** [oauth2-proxy/oauth2-proxy#2137]
## Expected Behavior

I am following the setup for tekton dashboard (https://github.com/tektoncd/dashboard/blob/main/docs/walkthrough/walkthrough-oauth2-proxy.md#configuring-dashboard-logout-url) and can see that in the guide, upon authentication via Github it is re-directing them back to tekton-dashboard. They are using a lower version. However, I have tried same configuration on the version in the guide and latest release.

1. Call URL tekton-dashboard.example.com
2. redirect to tekton-auth.example.com
3. sign in and auth with Github
4. authorise login and redirect back to tekton-dashboard.example.com

## Current Behavior

Github auth working correctly, however, redirecting back to oauth2 ingress host which outputs a 404 page not found

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/93769720/a1d5400b-6022-4ac1-9fc8-81eaceeeb190)

1. Call URL tekton-dashboard.example.com
2. redirect to tekton-auth.example.com
3. sign in and auth with Github
4. authorise login and redirect to tekton-auth.example.com which persists with a 404

I am installing the charts with the below values. Therefore this shows my current config for oauth2-proxy

``` 
helm upgrade --install --wait --namespace tools oauth2-proxy oauth2-proxy/oauth2-proxy --version 6.13.1 --values - <<EOF
config:
 clientID: $CLIENT_ID
 clientSecret: $CLIENT_SECRET
extraArgs:
 provider: github
 whitelist-domain: .example.com
 cookie-domain: .example.com
 redirect-url: https://tekton-auth.example.com/oauth2/callback
 cookie-secure: 'false'
 scope: user:email
ingress:
 enabled: true
 path: /
 hosts:
   - tekton-auth.example.com
EOF

```
Current service ingress annotations for configuration

```
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: tekton-dashboard
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://tekton-auth.example.com/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.tools.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_name_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
```

## Context

This is currently a test environment and following the already created documentation (link above) I am struggling to redirect back to tekton dashboard. The authorisation side works perfect. 

It would be great if anyone can help try discover what the issue is. I have spent some time trying various different redirection parameters in the URL but nothing seems to work. 

## Your Environment

- Version used:

latest version of ingress and oauth2-proxy

**Comment by mentlak0** [comment]
fixed this. The issue was that I was dependent on the guide that I linked. I created my own values, with additional settings for a custom configuration to my use case. 

I am happy to assist anyone who requires help with issues for redirection as this took longer than expected.

**Comment by alokhom** [comment]
what would be the way to set the ingress in istio gateway config ?

**Comment by mentlak0** [comment]
@alokhom hello, I did not set up on isitio but with ingress annotations and deploying oauth2 on my cluster. I can help with the way I have set up, but may be different in your use case.

**Comment by alokhom** [comment]
ye we are struggling with istio

**Comment by patrickneubauer** [comment]
> fixed this. The issue was that I was dependent on the guide that I linked. I created my own values, with additional settings for a custom configuration to my use case.
> 
> I am happy to assist anyone who requires help with issues for redirection as this took longer than expected.

Hello, thank you for the detailed description. Could you please describe how you resolved this issue? We are facing the same issue. Cheers

**Comment by mentlak0** [comment]
@patrickneubauer Hello, so here is the set up I went with and works. Steps on how it works:

1. Service launched
2. redirection to github auth which requests authentication 
3. authentication is completed
4. redirected back to step 1 with authentication to the service via github

On my ingress I have added: 

```
nginx.ingress.kubernetes.io/auth-signin: https://your.domain/oauth2/start?rd=https://$host$uri
nginx.ingress.kubernetes.io/auth-url: https://your.domain.com/oauth2/auth
```

My arguments for oauth2-proxy are:

```
  extraArgs:
    provider: github
# scope user:email (fix for version 6.13.1 Github issues)
    scope: user:email
    github-org: your-org
    cookie-domain: .example.com
    whitelist-domain: .example.com
```
And this set up also needs a github auth0 application creating. 

This works fine for me and as expected. Hope this helps.
