### ISSUE TITLE
Adding Aws Cognito Provider

### ISSUE THREAD

**Issue by omeryesil** [oauth2-proxy/oauth2-proxy#214]
Can we add Aws Cognito provider, something like: https://github.com/mbartsch/oauth2_cognito_proxy/blob/cognito/providers/cognito.go

If it is ok I will be happy to create a PR for it.

**Comment by JoelSpeed** [comment]
I'm not against this, but before we go ahead, is there any reason Cognito can't be used with the generic OIDC provider?

**Comment by omeryesil** [comment]
I haven't tested it with OIDC provider, will give it a try. If it works, to be honest it doesnt provide that much value to have a separate provider for Cognito. On the other hand, I also think it would be nice to have a dedicated one, as oauth2_proxy has providers for Facebook, Azure AD, Gitlabl, etc..

**Comment by 8snit** [comment]
for us the OIDC provider of oauth2_proxy works out of the box with AWS Cognito - but the provider above includes a group membership check as additional functionality, something we would also need

this could be implemented in a generic way for OIDC as well by not just making group name (e.g. "admin") but also the claim name containing groups (here "cognito:groups") in id_token configurable

"cognito:groups": [
    "admin"
  ]

i.e. group membership part of id_token!

there are similar pull requests for other providers like google (#224 ), so would be great to have it everywhere

**Comment by steakunderscore** [comment]
If it does work it'd be great to see some docs on how to set it up. Even if it's straight forward, it'll help the next person.

**Comment by unfor19** [comment]
How do you set up AWS Cognito as an OIDC? I tried, but I always keep getting: `auth request unexpected status: 302 while sending to client, client`

In case you're skimming here - **THIS DOESN'T WORK**

### My Specs
- **Load Balancer**: AWS Network Load Balancer (NLB) routes traffic to [nginx-igress-controller](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/oauth-external-auth) and the cluster is AWS EKS (k8s v1.14)
- **SSL/TLS**: The NLB is terminating TLS using AWS's Certificate, and then routes HTTP traffic to ingresses

#### Domain name
<img src="https://i.ibb.co/c8C3fgv/cognito-domain-name.png" alt="cognito-domain-name" border="0">

#### App client settings
<img src="https://i.ibb.co/kDjGcnb/cognito-settings.png" alt="cognito-settings" border="0">

#### yaml files
`oauth2_proxy.yml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --provider-display-name=aws_cognito
        - --upstream=file:///dev/null
        - --client-id=MY_USER_POOL_DEVICE_ID
        - --client-secret=MYUSER_POOL_DEVICE_SECRET
        - --redirect-url=https://auth.example.com/oauth2/_callback
        - --login-url=https://auth.example.com/oauth2/login
        - --profile-url=https://auth.example.com/oauth2/userInfo
        - --redeem-url=https://auth.example.com/oauth2/token
        - --oidc-jwks-url=https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_MyUserPoolId/.well-known/jwks.json
        - --oidc-issuer-url=https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_MyUserPoolId
        - --skip-oidc-discovery
        - --scope=openid
        - --cookie-secure=false
        - --cookie-domain=localhost
        image: quay.io/pusher/oauth2_proxy:v5.0.0-amd64
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: whoami
spec:
  rules:
  - host: localhost
    http:
      paths:
        - path: /
          backend:
            serviceName: oauth2-proxy
            servicePort: 4180
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: whoami
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
```

`my_services.yml`
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: whoami
  labels:
    id: whoami
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 8000
      protocol: TCP
      name: private
  type: ClusterIP
  selector:
    id: whoami
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: whoami
spec:
  selector:
    matchLabels:
      id: whoami
  replicas: 1
  template:
    metadata:
      labels:
        id: whoami
    spec:
      containers:
        - name: whoami-container
          image: containous/whoami
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 100Mi
          ports:
            - containerPort: 80
              name: http
        - name: private-container
          image: jwilder/whoami
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 100Mi
          ports:
            - containerPort: 8000
              name: private                          
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami-ingress # public
  namespace: whoami
  labels:
    id: whoami
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: whoami.
    http:
      paths:
        - path: /
          backend:
            serviceName: whoami-service
            servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: private-ingress
  namespace: whoami
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://auth.example.com/oauth2/authorize"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.example.com/oauth2/_callback"
spec:
  rules:
  - host: private.example.com
    http:
      paths:
        - path: /
          backend:
            serviceName: whoami-service
            servicePort: 8000
```
