### ISSUE TITLE
PKCE verification failed after enabling cookie refresh with OKTA OIDC

### ISSUE THREAD

**Issue by marcellodesales** [oauth2-proxy/oauth2-proxy#2155]
## Expected Behavior

* The Single Page Application SPA web app should serve properly with HTTP 200 and load its experience after the OIDC exchange from OKTA is performed and returned to the App. 

Either refreshing the page manually or having the application intercept the lack of a valid Browser Cookie, the experience should be that the OKTA without any failure.

## Current Behavior

* When refreshing a Window Tab with the SPA app loaded for more than the cookie-expiration time, say `12hrs`, the OIDC exchange from OKTA is performed correctly 
  * Going through the UI and getting user's input for a new JWT token, etc
  * However, after confirming, the page is loaded with a 500 error 
* The potential problem is that the DNS may refuses calls sometimes
* The UI is redirected and it can't load from the `callback` URL
  * https://chat.gpt.company.com/oauth2/callback?code=ln1Q880CrhAfKi78F4AuXvSTB5PuVvLwrgCLG9Ob2Bo&state=znsW2OrtNUtnx07jVviif3FchqsiR3MJcpwqWF6zbRk%3A%2F

```json
 {
   "error":"invalid_grant",
    "error_description":"PKCE verification failed."
}
```

![Screenshot 2023-07-10 at 9 04 20 PM](https://github.com/oauth2-proxy/oauth2-proxy/assets/131457/87851062-b68d-4975-a340-28b20b7fe490)

### 🔊 Oauth2-proxy server logs

Meanwhile, the logs from oauth2-proxy server shows the following

```console
Jul 10, 2023 @ 14:58:45.418 | [2023/07/10 14:58:26] [oauthproxy.go:823] Error redeeming code 
during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 400 Bad Request | 
oauth2-proxy-gpt-com-prd
-- | -- | --

  | Jul 8, 2023 @ 03:32:32.356 | [2023/07/08 03:32:13] [main.go:60] ERROR: Failed to initialise OAuth2 
Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: 
could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC 
configuration: error performing request: 
Get "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/.well-known/openid-configuration": 
dial tcp 76.223.112.12:443: connect: connection refused | oauth2-proxy-gpt-com-prd

  | Jul 8, 2023 @ 03:32:32.255 | 2023-07-08T03:32:13.522753Z	warn	failed running ulimit command: | 
oauth2-proxy-gpt-com-prd

  | Jul 8, 2023 @ 03:31:42.371 | [2023/07/08 03:31:22] [main.go:60] ERROR: Failed to initialise OAuth2 
Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier:
 could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC
 configuration: error performing request: 
Get "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/.well-known/openid-configuration": 
dial tcp 76.223.112.12:443: connect: connection refused

Jul 8, 2023 @ 03:31:42.371 | 2023-07-08T03:31:22.354347Z	warn	failed running ulimit command: | 
oauth2-proxy-gpt-com-prd
-- | -- | --

  | Jul 8, 2023 @ 03:30:21.220 | [2023/07/08 03:30:01] [main.go:60] ERROR: Failed to initialise OAuth2 
Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: 
could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: 
error performing request:
 Get "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/.well-known/openid-configuration": 
dial tcp 13.248.245.245:443: connect: connection refused | oauth2-proxy-gpt-com-prd

  | Jul 8, 2023 @ 03:30:20.061 | 2023-07-08T03:30:01.850612Z	error	R
equest to probe app failed: Get "http://10.42.5.130:4180/ping": dial tcp 127.0.0.6:0->1
0.42.5.130:4180: connect: connection refused, original URL path = /app-health/oauth2-proxy/readyz
```

* The configuration was changed to the following:

```yaml
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.4.0"
        imagePullPolicy: IfNotPresent
        args:
          - --http-address=0.0.0.0:4180
          - --https-address=0.0.0.0:4443
          - --metrics-address=0.0.0.0:44180
          - --auth-logging=true
          - --code-challenge-method=S256
          - --cookie-domain=chat.gpt.company.com
          - --cookie-expire=12h
          - --cookie-name=_oauth2_proxy_gpt_prd_company_com
          - --cookie-refresh=1h
          # Someone reported that for OKTA we need to provide the offline_access https://github.com/oauth2-proxy/oauth2-proxy/issues/490#issuecomment-1576644398
          # The way to support scope https://github.com/oauth2-proxy/oauth2-proxy/issues/793#issuecomment-748952258
          # Our OKTA team suggests these 3 for offline_access 
          # https://developer.okta.com/docs/reference/api/oidc/#limits
          # My recommendation on how to set up OKTA https://github.com/oauth2-proxy/oauth2-proxy/issues/490#issuecomment-1626702589
          - --scope=openid profile email offline_access
          - --email-domain=*
          - --oidc-issuer-url=https://signin.company.com/oauth2/aus******696
          - --provider=oidc
          - --request-logging=true
          - --request-logging-format={ "client":"{{.Client}}", "method":"{{.RequestMethod}}", "username":"{{.Username}}", "timestamp":"{{.Timestamp}}", "host":"{{.Host}}", "upstream":"{{.Upstream}}", "url":{{.RequestURI}}, "protocol":"{{.Protocol}}", "user_agent":{{.UserAgent}}, "status":"{{.StatusCode}}", "length":"{{.ResponseSize}}", "response-time":"{{.RequestDuration}}" }
          - --set-authorization-header=true
          - --show-debug-on-error
          - --silence-ping-logging=true
          - --skip-provider-button=true
          - --standard-logging=true
          - --upstream=static://200
          - --whitelist-domain=chat.gpt.company.com
          - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
```

## Possible Solution

* If the `oidc-issuer-url` has intermittent failures, would that be the case of having an `Exponential Backoff` mechanism to try to guarantee this request is successful?
  * The reason why I ask is that the second attempt to login, after seeing the 500 ERROR on the UI, correctly logs the user back into the application
  * Add a configuration parameter to specify the max number of retries and the retries initial wait seconds
  * Potential HTTP client with code to make it more reliable https://github.com/oauth2-proxy/oauth2-proxy/blob/d9416c3630d4b888441425691b57f01dab64bda8/pkg/providers/oidc/provider.go#L59C1-L61
  * Sequence of methods on line `requests.New(requestURL).WithContext(ctx).Do().`

```go
	logger.Printf("Performing OIDC Discovery...")

	var p providerJSON
	requestURL := strings.TrimSuffix(issuerURL, "/") + "/.well-known/openid-configuration"
	if err := requests.New(requestURL).WithContext(ctx).Do().UnmarshalInto(&p); err != nil {
		return nil, fmt.Errorf("failed to discover OIDC configuration: %v", err)
	}
```

## Steps to Reproduce (for bugs)

1.  Let the app have its cookies expire for a period of time longer than `cookie-expire`
2.  Attempt to refresh the page
3. The OKTA OIDC process can be confirmed
4.  The user sees the 500 instead of the app that should be redirected by Istio

## Context

* SPA application can handle a browser tab refresh properly when an older Browser Cookie Expires
* The URL is responsible 99% of time but may result in an error
* Executing a curl pod in the same namespace, I could verify that there's DNS connectivity and it doesn't block connections from any POD egressing to the OKTA OIDC provider for the configs... 

```console
$  kubectl run curl-pod --namespace=oauth2-proxy-gpt-com-prd --rm -i --tty --image=curlimages/curl -- 
       curl -i https://signin.company.com/oauth2/aus8yhi850bHOdExX696/.well-known/openid-configuration

HTTP/1.1 200 OK
Date: Mon, 10 Jul 2023 20:34:59 GMT
Server: nginx
Content-Type: application/json
x-xss-protection: 0
p3p: CP="HONK"
content-security-policy-report-only: default-src 'self' company.okta.com signin.company.com *.oktacdn.com; connect-src 'self' company.okta.com company-admin.okta.com signin.company.com *.oktacdn.com *.mixpanel.com *.mapbox.com app.pendo.io data.pendo.io pendo-static-5634101834153984.storage.googleapis.com pendo-static-5391521872216064.storage.googleapis.com *.mtls.okta.com company.kerberos.okta.com *.authenticatorlocalprod.com:8769 http://localhost:8769 http://127.0.0.1:8769 *.authenticatorlocalprod.com:65111 http://localhost:65111 http://127.0.0.1:65111 *.authenticatorlocalprod.com:65121 http://localhost:65121 http://127.0.0.1:65121 *.authenticatorlocalprod.com:65131 http://localhost:65131 http://127.0.0.1:65131 *.authenticatorlocalprod.com:65141 http://localhost:65141 http://127.0.0.1:65141 *.authenticatorlocalprod.com:65151 http://localhost:65151 http://127.0.0.1:65151 https://oinmanager.okta.com data:; script-src 'unsafe-inline' 'unsafe-eval' 'self' company.okta.com signin.company.com *.oktacdn.com; style-src 'unsafe-inline' 'self' company.okta.com signin.company.com *.oktacdn.com app.pendo.io cdn.pendo.io pendo-static-5634101834153984.storage.googleapis.com pendo-static-5391521872216064.storage.googleapis.com; frame-src 'self' company.okta.com company-admin.okta.com signin.company.com login.okta.com com-okta-authenticator: api-b6e22032.duosecurity.com; img-src 'self' company.okta.com signin.company.com *.oktacdn.com *.tiles.mapbox.com *.mapbox.com app.pendo.io data.pendo.io cdn.pendo.io pendo-static-5634101834153984.storage.googleapis.com pendo-static-5391521872216064.storage.googleapis.com data: blob:; font-src 'self' company.okta.com signin.company.com data: *.oktacdn.com fonts.gstatic.com; frame-ancestors 'self'
content-security-policy: frame-ancestors 'self'
cache-control: max-age=86400, must-revalidate
expires: Tue, 11 Jul 2023 20:34:59 GMT
vary: Origin
x-content-type-options: nosniff
Strict-Transport-Security: max-age=315360000; includeSubDomains
X-Okta-Request-Id: ZKxrcwdyI5u1VZRbZWya4QAABmg
Transfer-Encoding: chunked
```
```json
{
  "issuer": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696",
  "authorization_endpoint": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/authorize",
  "token_endpoint": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/token",
  "userinfo_endpoint": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/userinfo",
  "registration_endpoint": "https://signin.company.com/oauth2/v1/clients",
  "jwks_uri": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/keys",
  "response_types_supported": [
    "code",
    "id_token",
    "code id_token",
    "code token",
    "id_token token",
    "code id_token token"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post",
    "okta_post_message"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "password",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "scopes_supported": [
    "locality",
    "okta.myAccount.email.manage",
    "okta.myAccount.email.read",
    "okta.myAccount.manage",
    "okta.myAccount.phone.manage",
    "okta.myAccount.phone.read",
    "okta.myAccount.profile.manage",
    "okta.myAccount.profile.read",
    "okta.myAccount.read",
    "openid",
    "profile",
    "email",
    "address",
    "phone",
    "offline_access",
    "device_sso"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt",
    "none"
  ],
  "claims_supported": [
    "iss",
    "ver",
    "sub",
    "aud",
    "iat",
    "exp",
    "jti",
    "auth_time",
    "amr",
    "idp",
    "nonce",
    "name",
    "nickname",
    "preferred_username",
    "given_name",
    "middle_name",
    "family_name",
    "email",
    "email_verified",
    "profile",
    "zoneinfo",
    "locale",
    "address",
    "phone_number",
    "picture",
    "website",
    "gender",
    "birthdate",
    "updated_at",
    "at_hash",
    "c_hash"
  ],
  "code_challenge_methods_supported": [
    "S256"
  ],
  "introspection_endpoint": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/introspect",
  "introspection_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt",
    "none"
  ],
  "revocation_endpoint": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/revoke",
  "revocation_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "client_secret_post",
    "client_secret_jwt",
    "private_key_jwt",
    "none"
  ],
  "end_session_endpoint": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/logout",
  "request_parameter_supported": true,
  "request_object_signing_alg_values_supported": [
    "HS256",
    "HS384",
    "HS512",
    "RS256",
    "RS384",
    "RS512",
    "ES256",
    "ES384",
    "ES512"
  ],
  "device_authorization_endpoint": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/device/authorize",
  "pushed_authorization_request_endpoint": "https://signin.company.com/oauth2/aus8yhi850bHOdExX696/v1/par"
}               
```

## Workaround

* Just refreshing the page doesn't work as it results in the same current code/state callback info
  * https://chat.gpt.company.com/oauth2/callback?code=ln1Q880CrhAfKi78F4AuXvSTB5PuVvLwrgCLG9Ob2Bo&state=znsW2OrtNUtnx07jVviif3FchqsiR3MJcpwqWF6zbRk%3A%2F
* Cleaning up the URL and removing the path entirely to go through the process again renewed to then properly

## Your Environment

- Kubernetes: 1.24
- Oauth2-Proxy: oauth2-proxy:v7.4.0
