### ISSUE TITLE
How to use custom sign_in.html & error.html in a air gripped environment

### ISSUE THREAD

**Issue by Mahesh-Gunda-Maersk** [oauth2-proxy/oauth2-proxy#2156]
## Expected Behavior 
the login page should show a custom sign_in.html or an error.html (upon error)

## Current Behavior
Custom templates dir is not being recognized.  oauth2-proxy is taking the default template.  Not sure what is going wrong, Please help, how can i use custom html pages in oauth2-proxy. 

## Steps to Reproduce (for bugs)
below snippet of the deployment file.  
```
spec:
  template:
    spec:
      serviceAccountName: xxxxxx
      containers:
      - name: oauth2
        args:
          - --http-address=0.0.0.0:4180
          - --metrics-address=0.0.0.0:44180
          - --proxy-prefix=/xxxxxxx
          - --request-logging=false
          - --custom-templates-dir=/mnt/html-templates
        volumeMounts:
        - name: custom-html-templates
          mountPath: /mnt/html-templates
        - name: custom-html-css
          mountPath: /mnt/html-templates/css
      volumes:
      - name: custom-html-templates
        configMap:
          name: custom-html-templates
          defaultMode: 0777
      - name: custom-html-css
        configMap:
          name: custom-html-css
          defaultMode: 0777
```
----
----
```
configMapGenerator:
- name: custom-html-templates
  files:
  - ./sign_in.html
  - ./error.html
  - ./robots.txt
- name: custom-html-css
  files:
  - ./bulma.min.css
  - ./all.min.css
generatorOptions:
  disableNameSuffixHash: true
```

HTML files are taken from --> https://github.com/oauth2-proxy/oauth2-proxy/tree/master/pkg/app/pagewriter

## Your Environment

K8s environment.
