### ISSUE TITLE
403 Forbidden - Login Failed: Unable to find a valid CSRF token. Please try again.

### ISSUE THREAD

**Issue by danksim** [oauth2-proxy/oauth2-proxy#2161]
## Expected Behavior
Redirect to my page

## Current Behavior
<img width="613" alt="image" src="https://github.com/oauth2-proxy/oauth2-proxy/assets/28274696/69c0acad-b5de-496e-b2ed-437f95e84b9e">

## Steps to Reproduce (for bugs)

1.  
```
# oauth2-proxy as a kubernetes sidecar
     - args:
        - --provider=oidc
        - --upstream="https://app.<MY_DOMAIN>"
        - --provider-display-name
        - <APP_NAME>
        - --client-id
        - $CLIENT_ID
        - --client-secret
        - $CLIENT_SECRET
        - --email-domain="*"
        - --oidc-issuer-url
        - https://$CLIENT_IDP_DOMAIN/
        - --cookie-secure=true
        - --cookie-secret=<REDACTED>
        - --cookie-domain="*"
        - --cookie-path="/"
        - --redirect-url="https://<APP_NAME>-<DOMAIN>"
        - --set-xauthrequest=true
        - --set-authorization-header=true
        - --pass-user-headers=true
        - --pass-authorization-header=true
        - --pass-access-token=true
        - --http-address="0.0.0.0:4180"
        command:
        - oauth2-proxy
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client_id
              name: <APP_NAME>-auth0-credentials
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client_secret
              name: <APP_NAME>-auth0-credentials
        - name: CLIENT_IDP_DOMAIN
          valueFrom:
            secretKeyRef:
              key: idp_domain
              name: <APP_NAME>-auth0-credentials
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
```
```
# nginx ingress annotations
annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: <APP_NAME>
    meta.helm.sh/release-namespace: <SOME_NAMESPACE>
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token,Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://<APP_NAME>.<DOMAIN>/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://<APP_NAME>.<DOMAIN>//oauth2/auth
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/server-snippet: |
      underscores_in_headers on;
      grpc_read_timeout 3600s;
      grpc_send_timeout 3600s;
      client_body_timeout 3600s;
```

## Context

I am trying to use oidc (okta) to log into a kubernetes service

## Your Environment

kubernetes helm helmfile nginx

- Version used: v7.4.0
