### ISSUE TITLE
Error redeeming code during OAuth2 callback

### ISSUE THREAD

**Issue by joseerlang** [oauth2-proxy/oauth2-proxy#2167]
I have oauth2-proxy inside kubernetes cluster and it is configured with both the oidc provider and keycloak-oidc and very occasionally I get a 500 error in the web interface right after logging into the keycloak portal.  The error I get is the following
`Error redeeming code during OAuth2 callback: token exchange failed: Post "https://<publicdns>/realms/<my_realm>/protocol/openid-connect/token": EOF`
## Expected Behavior
I would expect this call to give a somewhat more concrete message on the error. An EOF message doesn't add much meaning, really.

## Your Environment

```
- apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  releaseName: oauth2-proxy
  targetNamespace: oauth2-proxy
  interval: 10m
  chart:
    spec:
      chart: oauth2-proxy
      version: '6.12.0'
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  upgrade:
    force: true
  values:
    config:
      existingSecret: keycloak
      cookieName: "_oauth2_proxy"
      configFile: |-
        provider = "oidc"
        cookie_refresh = "5m"
        cookie_expire = "8h"
        email_domains = ["*"]
        set_xauthrequest = true    
        pass_access_token = true
        set_authorization_header = true
        skip_auth_preflight = true
        reverse_proxy = true
        ssl_insecure_skip_verify = true
        skip_provider_button = true
        upstreams = ["static://200"]
        whitelist_domains = ["<MyDomain>"]
        cookie_domains = ["<MyDomain>"]
        oidc_issuer_url = "https://<MyDomain>/realms/<my_realm>"
        silence_ping_logging = true
```
- keycloak version : 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  targetNamespace: keycloak
  interval: 10m
  chart:
    spec:
      chart: keycloak
      version: 13.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

```
