### ISSUE TITLE
Add Gitea as a provider

### ISSUE THREAD

**Issue by v7lin** [oauth2-proxy/oauth2-proxy#217]
[Gitea](https://gitea.io/) supports acting as an [OAuth2 provider](https://docs.gitea.io/en-us/oauth2-provider/) to allow third party applications to access its resources with the user’s consent. This feature is available since Gitea release 1.8.0.

- [ ] Check, can gitea used with the generic OIDC provider, if this is the case then please submit docs for this.

If the generic OIDC provider can't be used:
- [ ] Add new provider under `providers/`
- [ ] Add documentation
- [ ] Add changelog entry

**Comment by oliver006** [comment]
fwiw, not a sure a new provider implementation is needed, I managed to use Gitea by pretending to be Github, using these settings:
```
provider = "github"
redirect_url = "https://<< host running opauth2_proxy >>/oauth2/callback"
provider_display_name = "Gitea"
client_id = "<< client_id as generated by Gitea >>"
client_secret = "<< client_secret as generated by Gitea >>"
login_url="https://<< your gitea host >>/login/oauth/authorize"
redeem_url="https://<< your gitea host >>/login/oauth/access_token"
validate_url="https://<< your gitea host >>/api/v1"
```

**Comment by JoelSpeed** [comment]
If there is a working provider implementation using the GitHub provider, perhaps we could just add docs for doing that instead of adding a new provider?

**Comment by oliver006** [comment]
I think that makes sense. Let me see if I can find some time in the next few days and I'll open a PR to add this to the docs.

**Comment by v7lin** [comment]
> fwiw, not a sure a new provider implementation is needed, I managed to use Gitea by pretending to be Github, using these settings:
> 
> ```
> provider = "github"
> redirect_url = "https://<< host running opauth2_proxy >>/oauth2/callback"
> provider_display_name = "Gitea"
> client_id = "<< client_id as generated by Gitea >>"
> client_secret = "<< client_secret as generated by Gitea >>"
> login_url="https://<< your gitea host >>/login/oauth/authorize"
> redeem_url="https://<< your gitea host >>/login/oauth/access_token"
> validate_url="https://<< your gitea host >>/api/v1"
> ```

how to work with traefik docker swarm?

```yaml
# 版本
version: "3.7"

# 服务
services:

  # 暂不支持设置时区
  traefik:
    image: traefik:v2.1.1
    ports:
      - 22:22
      - 80:80
      - 443:443
#      - 8080
    networks:
      - net # traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../dev-ops-repo/traefik/acme:/etc/traefik/acme
#    environment:
#      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.ssh.address=:22"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
#      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-traefik@traefik.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-v2.json"
#      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-staging-v2.json"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager # 部署位置，只在管理节点部署
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.service=traefik"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
        - "traefik.http.routers.traefik.entrypoints=http"
        - "traefik.http.routers.traefik.middlewares=redirecttls"
        - "traefik.http.middlewares.redirecttls.redirectscheme.scheme=https"
        - "traefik.http.routers.traefiktls.service=traefik"
        - "traefik.http.routers.traefiktls.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
        - "traefik.http.routers.traefiktls.entrypoints=https"
        - "traefik.http.routers.traefiktls.tls.certresolver=letsencrypt"
        - "traefik.http.routers.traefiktls.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_BASIC}"

networks:
  # docker stack deploy -c <(docker-compose -f docker-swarm.yml config) traefik
  # Creating network traefik_net
  # 外部引用 "traefik_net"
  net:
    driver: overlay
    attachable: true
```

```yaml
# 版本
version: "3.7"

# 服务
services:

  # https://github.com/v7lin/traefik-oauth2-proxy/blob/master/docker-compose.yml
  oauth:
    image: pusher/oauth2_proxy:latest
#    ports:
#      - 4180
    networks:
      - traefik_net
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID?err}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET?err}
      - OAUTH2_PROXY_COOKIE_DOMAIN=.${SERVER_DOMAIN:-localhost}
      - OAUTH2_PROXY_COOKIE_REFRESH=1h
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET?err}
      - OAUTH2_PROXY_FOOTER=-
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_PASS_BASIC_AUTH=false
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_PROVIDER=${OAUTH2_PROXY_PROVIDER?err}
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_WHITELIST_DOMAIN=.${SERVER_DOMAIN:-localhost}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_net"
        - "traefik.docker.lbswarm=true"
        - "traefik.http.middlewares.oauth-verify.forwardAuth.address=http://oauth:4180/oauth2/auth"
        - "traefik.http.middlewares.oauth-verify.forwardAuth.trustForwardHeader=true"
        - "traefik.http.middlewares.oauth-verify.forwardAuth.authResponseHeaders=X-Auth-Request-User,Set-Cookie"
        - "traefik.http.middlewares.oauth-signin.errors.service=oauth@docker"
        - "traefik.http.middlewares.oauth-signin.errors.status=401"
        - "traefik.http.middlewares.oauth-signin.errors.query=/oauth2/sign_in"
        - "traefik.http.services.oauth.loadbalancer.server.port=4180"
        - "traefik.http.routers.oauthtls.service=oauth"
        - "traefik.http.routers.oauthtls.rule=Host(`oauth.${SERVER_DOMAIN:-localhost}`) || PathPrefix(`/oauth2`)"
        - "traefik.http.routers.oauthtls.entrypoints=https"
        - "traefik.http.routers.oauthtls.tls.certResolver=letsencrypt"

networks:
  traefik_net:
    external: true
```
