### ISSUE TITLE
Ouath2-proxy shouldn't pass both Basic and Bearer Authorizaiton token at the same time

### ISSUE THREAD

**Issue by YanFenGuo** [oauth2-proxy/oauth2-proxy#2187]
I oauth2-proxy configured with OCP Service Mesh and using IBM Identity Manager as OIDC provider, let's say request A request oauth authentication, request B request basic authentication, request C doesn't require authentication.

So I set `--skip-auth-route=B|C`. If I visit A B(require Basic authentication) C(require NO authentication)  in separately from different browsers, everything is perfect. But if I visit them in the same browser, I see below behavior:
For request A: Only bearer token passed, this is expected.
For request B: Both basic token and bearer token passed, I'm expecting only basic token passed.
For request C:  Only bearer token passed,  I'm expecting no token passed. But this is fine since no function impact.

## Expected Behavior

There should be an option to pass either Bearer token or Basic token, not both.

## Current Behavior

I'm seeing both token passed at the same time, requires application change to handle this situation.

## Possible Solution

Make it configurable to pass only one token.

## Steps to Reproduce (for bugs)

This is my oauth2-proxy configuration:
```
      containers:
        - name: oauth2-proxy
          image: 'quay.io/oauth2-proxy/oauth2-proxy:latest'
          args:
            - '--provider=oidc'
            - '--client-id=85e0cdf9f1f0dac7f0e026c38dfdac2d'
            - '--client-secret=a849f14a18f646809237ba404608fe3d'
            - >-
              --redirect-url=https://localhost:443/oauth2/callback
            - >-
              --oidc-jwks-url=https://MY-IDP-PROVIDER/jwk
            - >-
              --login-url=https://MY-IDP-PROVIDER/authorize
            - >-
              --redeem-url=https://MY-IDP-PROVIDER/token
            - >-
              --validate-url=https://MY-IDP-PROVIDER/introspect
            - >-
              --profile-url=https://MY-IDP-PROVIDER/userInfo
            - >-
              --oidc-issuer-url=https://MY-IDP-PROVIDER/.well-known/openid-configuration
            - '--request-logging=true'
            - '--show-debug-on-error=true'
            - '--skip-oidc-discovery=true'
            - '--email-domain=*'
            - '--cookie-secret=0dSBdCNa2k1oOPl3eviZ0g=='
            - '--cookie-domain=.apps.MY-IDP-PROVIDER-HOST'
            - '--skip-provider-button=true'
            - '--http-address=0.0.0.0:8081'
            - '--upstream=http://127.0.0.1:8080'
            - '--ssl-insecure-skip-verify=true'
            - '--cookie-expire=1h'
            - '--cookie-refresh=55m'
            - '--scope=openid'
            - '--pass-access-token=true'
            - '--pass-authorization-header=true'
            - '--pass-host-header=true'
            - '--pass-user-headers=true'
            - '--insecure-oidc-skip-issuer-verification=true'
            - '--oidc-email-claim=name'
            - '--insecure-oidc-allow-unverified-email=true'
            - '--whitelist-domain="*.MY-IDP-PROVIDER-HOST"'
            - '--skip-auth-route="FileNet/Engine|peengine/IOR/ping"'
            - '--skip-auth-strip-headers=false'
            - '--skip-jwt-bearer-tokens=true'
          ports:
            - name: oauth-http
              containerPort: 8081
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
```

## Context

Currently my application can only handle basic or bearer token, if there are both, it will report error.

## Your Environment

I followed https://cloud.redhat.com/blog/restricting-user-access-via-service-mesh-2.0-and-red-hat-single-sign-on to set up the configuration.

- Version used:
oauth2-proxy v7.4.0 (built with go1.19.2)
