### ISSUE TITLE
oauth2-proxy is passing duplicate Bearer token if I already provided bearer token in CLI

### ISSUE THREAD

**Issue by YanFenGuo** [oauth2-proxy/oauth2-proxy#2204]
I oauth2-proxy configured with OCP Service Mesh and using IBM Identity Manager as OIDC provider, everything work perfect from UI, but if I visit from CLI and pass Authorization header with  a bearer token, I see duplicated bearer token passed to my application.

## Expected Behavior

Don't pass duplicated bearer token.

## Current Behavior

I see `Authorization: Bearer token-abc,Bearer token-abc`.

## Possible Solution

If I remove `--pass-authorization-header=true` from oauth2-proxy, it can work from CLI, but from UI it can't pass bearer token, so no solution yet.

## Steps to Reproduce (for bugs)

1. Get a JWT token from IBM IM, confirmed the audience is the client ID of oauth2-proxy.
2. Visit application behind oauth2-proxy from CLI like this `curl -L  -vk -X POST -s -H "Authorization: Bearer $ACCESS_TOKEN" -H 'Content-Type: application/x-www-form-urlencoded' --cookie newcookies.txt https://$cpd/icn/navigator/jaxrs/logon`, `ACCESS_TOKEN` is a valid JWT token.
3. From My application I see Authorization header has duplicated bearer token.

This is my oauth2-proxy configuration:
```
      containers:
        - name: oauth2-proxy
          image: 'quay.io/oauth2-proxy/oauth2-proxy:latest'
          args:
            - '--provider=oidc'
            - '--client-id=85e0cdf9f1f0dac7f0e026c38dfdac2d'
            - '--client-secret=a849f14a18f646809237ba404608fe3d'
            - >-
              --redirect-url=https://localhost:443/oauth2/callback
            - >-
              --oidc-jwks-url=https://MY-IDP-PROVIDER/jwk
            - >-
              --login-url=https://MY-IDP-PROVIDER/authorize
            - >-
              --redeem-url=https://MY-IDP-PROVIDER/token
            - >-
              --validate-url=https://MY-IDP-PROVIDER/introspect
            - >-
              --profile-url=https://MY-IDP-PROVIDER/userInfo
            - >-
              --oidc-issuer-url=https://MY-IDP-PROVIDER/.well-known/openid-configuration
            - '--request-logging=true'
            - '--show-debug-on-error=true'
            - '--skip-oidc-discovery=true'
            - '--email-domain=*'
            - '--cookie-secret=0dSBdCNa2k1oOPl3eviZ0g=='
            - '--cookie-domain=.apps.MY-IDP-PROVIDER-HOST'
            - '--skip-provider-button=true'
            - '--http-address=0.0.0.0:8081'
            - '--upstream=http://127.0.0.1:8080'
            - '--ssl-insecure-skip-verify=true'
            - '--cookie-expire=1h'
            - '--cookie-refresh=55m'
            - '--scope=openid'
            - '--pass-access-token=true'
            - '--pass-authorization-header=true'
            - '--pass-host-header=true'
            - '--pass-user-headers=true'
            - '--insecure-oidc-skip-issuer-verification=true'
            - '--oidc-email-claim=name'
            - '--insecure-oidc-allow-unverified-email=true'
            - '--whitelist-domain="*.MY-IDP-PROVIDER-HOST"'
            - '--skip-auth-route="FileNet/Engine|peengine/IOR/ping"'
            - '--skip-auth-strip-headers=false'
            - '--skip-jwt-bearer-tokens=true'
          ports:
            - name: oauth-http
              containerPort: 8081
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
```

## Context

Can't make it work with both from UI and CLI.

## Your Environment

I followed https://cloud.redhat.com/blog/restricting-user-access-via-service-mesh-2.0-and-red-hat-single-sign-on to set up the configuration.

 Version used:
    oauth2-proxy v7.4.0 (built with go1.19.2)
