### ISSUE TITLE
No Authorization Header with BitBucket Provider

### ISSUE THREAD

**Issue by teceP** [oauth2-proxy/oauth2-proxy#2209]
Iam trying to authenticate with BitBucket provider but do not get any Authorization Header.

I want to use the OAuth2-Proxy as a centralized instance for several other applications like Kubernetes Dashboard, ArgoCD, Grafana and so on, which are all running in my cluster.

The OAuth2-Proxy is in namespace called "oauth2-proxy" and the Kubernetes Dashboard is in "kubernetes-dashboard" namespace.
Also the ingress-nginx is in another namespace called "ingress-nginx".

The Ingress for the Kubernetes Dashboard:
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: kubernetes-dashboard-7.0.0-alpha0
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubernetes-dashboard
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Email,Authorization,x-auth-request-access-token
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2.k8s.mydomain.de/oauth2/start?rd=http%3A%2F%2F$host
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: "auth_request_set $token $upstream_http_authorization;\nadd_header
      Authorization $token;        \n"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
  name: kubernetes-dashboard
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - dashboard.k8s.mydomain.de
      secretName: kubernetes-dashboard-certs
  rules:
    - host: dashboard.k8s.mydomain.de
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubernetes-dashboard-web
                port:
                  name: web
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: kubernetes-dashboard-api
                port:
                  name: api
```
As you can see, I have the annotations for my oauth2-proxy instance and also tried with some configuration snippets, but doesnt work either.

The oauth2-proxy.cfg has following content:

```yaml
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "http://dashboard.k8s.mydomain.de" ]

      provider="bitbucket"
      scope="email" 
      
      set_authorization_header="true"
      pass_access_token="true"
      pass_authorization_header="true"
      set_xauthrequest="true"

      whitelist_domains=".k8s.mydomain.de"
      cookie_domains=".k8s.mydomain.de"
      cookie_expire="2h"
      cookie_name="_oauth2_proxy"
```
Client ID, Client Secret and Cookie Secret is set by a Secret.

## Expected Behavior

1. Call Dashboard URL 
2. Get redirected to BitBucket via OAuth2-Proxy 
3. Authenticate successfully 
4. Get redirected to my Dashboard with Authorization Header
5. Dont get asked by the Kubernetes Dashboard to login via kubernetes token or kubeconfig, since it recognizes that I do have a Authorization token

## Current Behavior

When I access the dashboard URL, I get redirected to BitBucket via the OAuth2-Proxy and can successfully login.

Since I get successfully authenticated, I expect to get an Authorization Header when I
- call any Dashboard URL
- call https://oauth2.k8s.mydomain.de/oauth2/auth

When I Call https://oauth2.k8s.mydomain.de/oauth2/auth, I have some Headers like:
```
x-auth-request-access-token: EPxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxHOuT_ihca9WMDKB-K6nQz
x-auth-request-email: m.aemail@mydomain.de
```
But not my needed "Authorization: Bearer <token>".

When I Call my Dashboard URL (or get automatically redirected after successful authentication), I get none of those headers also also, of couse, no Authorization Header.

## Possible Solution

Is it possible that I need to add any configuration because I work with different URLs, since I want to use a centralized OAuth2 Proxy instance for all applications?

## Context

Trying to avoid login with Kubernetes Dashboard directly, but using BitBucket.

## Your Environment
- oauth2-proxy:6.16.1 from Helm Repository
- kubernetes-dashboard:7.0.0-alpha0 from Helm Repository
- ingress-nginx:4.7.1 from Helm Repository
- kuberntes:1.26.4-4 hosted on OVHCloud

Feeling dumb because there are so many other issues according this topic. Tried all suggested solutions, but I can't figure it out - sorry for that.
