### ISSUE TITLE
"[AuthFailure] Invalid authentication via OAuth2: unauthorized" error is occurring when combined with Keycloak

### ISSUE THREAD

**Issue by suzuryo97** [oauth2-proxy/oauth2-proxy#2215]
Hi.
I'm trying to combine Keycloak and OAuth2Proxy to issue authorization code and access token.

I launch both Keycloak and OAuth2Proxy using Docker. The configuration values are as follows.

OAuth2 configuration
```
sudo docker run -d  
-p 4180:4180 
-p 443:443 
-v /etc/pki/tls/private/server.key:/etc/pki/tls/private/server.key
-v /etc/pki/tls/certs/server.crt:/etc/pki/tls/certs/server.crt
-v /etc/pki/tls/cacert.pem:/etc/pki/tls/cacert.pem  
quay.io/oauth2-proxy/oauth2-proxy 
--cookie-secret [random character string]
--client-id OAuthTest 
--client-secret [OAuthTest's secret] 
--email-domain * 
--provider keycloak-oidc 
--redirect-url https://172.23.0.200/oauth2/callback 
--oidc-issuer-url https://172.23.0.132:8443/realms/OAuth   
--cookie-name test_cookie 
--skip-provider-button true  
--upstream https://172.23.0.111:8080 (Simple web page)
--tls-cert-file /etc/pki/tls/certs/server.crt  
--tls-key-file /etc/pki/tls/private/server.key 
--provider-ca-file /etc/pki/tls/cacert.pem 
--cookie-samesite lax 
--reverse-proxy true  
--code-challenge-method S256 
--cookie-secure false
```
172.23.0.200 is OAuth2Proxy server's address.
172.23.0.132 is Keycloak server's address.
172.23.0.111 is web application(nginx) server's address.

Keycloak configuration
```
 keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /etc/pki/tls/certs/server.crt:/etc/x509/https/tls.crt
      - /etc/pki/tls/private/server.key:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: mysecretpassword
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
    command:
      - start-dev
   ```

## Expected Behavior
1. Access Keycloak login page through OAuth2Proxy.
2. Login by any prepared user.
3. Keycloak returns authorization code  and start access token isuance via  optionally set  "redirect-url".
4. Keycloak returns access token and access optionally set "upstream" URL.

## Current Behavior
[Success] Access Keycloak login page through OAuth2Proxy.
[Success] Login by pre-prepared user.
[Success] Keycloak returns authorization code  and start to access optionally set "redirect-url".
[Fail] Browser returns "403 Forbidden  You do not have permission to access this resource." and OAuth2Proxy log shows the following log.  Because of this, the token issuance does not start.
```
[2023/09/05 05:13:52] [oauthproxy.go:959] No valid authentication in request. Initiating login.
172.23.0.43 - 10621335-2340-479d-a7f0-c4a558ff1268 - - [2023/09/05 05:13:52] 172.23.0.200 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0" 302 462 0.000
172.23.0.43 - 49a0de5e-c9a8-4085-b072-167e1de41e01 - sample@test.com [2023/09/05 05:13:56] [AuthFailure] Invalid authentication via OAuth2: unauthorized
172.23.0.43 - 49a0de5e-c9a8-4085-b072-167e1de41e01 - - [2023/09/05 05:13:56] 172.23.0.200 GET - "/oauth2/callback?state=H0HAwZonPf6jPSpq52LXpUNx6qdSpUiYWWq1EsqF3vk%3A%2F&session_state=0eedb952-1c6a-46b8-a199-d2749dc3d868&code=0294a24d-0333-4b1c-881e-f69ea9c3fe91.0eedb952-1c6a-46b8-a199-d2749dc3d868.e41fe4a2-3c9a-4340-888c-e3bbfa5fe601" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0" 403 2785 
```

## Your Environment
1. Docker 24.0.5
5. Keycloak 22.0.1(quay.io/keycloak/keycloak:22.0.1)
6. OAuth2Proxy 7.4.0  (quay.io/oauth2-proxy/oauth2-proxy)
