### ISSUE TITLE
7.5.0 breaks protected path /static, HTTP 404

### ISSUE THREAD

**Issue by StefanLobbenmeierObjego** [oauth2-proxy/oauth2-proxy#2223]
## Expected Behaviour

Protected resource can still host on /static, just like in 7.4.0

## Current Behaviour

404 page not found on resources hosted on /static
Caused by https://github.com/oauth2-proxy/oauth2-proxy/pull/2025

## Possible Solution

Rolling back to 7.4.0

## Steps to Reproduce (for bugs)

Host a resource that has content on /static, for example jupyter
login to the oauth proxy

the page does not fully load, requests to /static get a 404 response

calling the proxy on port 8080
```
kubectl debug -n tools -it jupyterlab-98c75c5c8-8qxq8  --image=curlimages/curl -- curl "http://localhost:8080/jupyter/static/lab/main.bcccfe17b7cd76ace990.js?v=bcccfe17b7cd76ace990"
Defaulting debug container name to debugger-rtpwv.
404 page not found
```

calling the underlying service on port 8888
```
kubectl debug -n tools -it jupyterlab-98c75c5c8-8qxq8  --image=curlimages/curl -- curl "http://localhost:8888/jupyter/static/lab/main.bcccfe17b7cd76ace990.js?v=bcccfe17b7cd76ace990"
Defaulting debug container name to debugger-rtpwv.
(()=>... (a valid response)
```

## Context

Will roll back for now

## Your Environment

```yml
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.0
          ports:
            - containerPort: 8080
          args:
            - "--upstream=http://localhost:8888"
            - "--banner=-"
            - "--footer=-"
            - "--custom-sign-in-logo=-"
            - "--cookie-secure=true"
            - "--cookie-expire=8h0m"
            - "--cookie-refresh=60m"
            - "--cookie-domain=censored.de"
            - "--http-address=0.0.0.0:8080"
            - "--proxy-prefix=/jupyter"
            - "--redirect-url=https://censored.de/jupyter/callback"
            - "--email-domain=censored.de"
            - "--provider=oidc"
            - "--client-id=123456"
            - "--oidc-issuer-url=https://login.microsoftonline.com/987645/v2.0"
```

- Version used: 7.5.0, 7.5.1

**Comment by Hadatko** [comment]
+1 Getting invalid scope. Currently i don't set any. If i add some it is not working anyway

**Comment by StefanLobbenmeierObjego** [comment]
@Hadatko where do you see invalid scope? For me the login completes but afterwards I get 404. But maybe I missed the invalid scope in some response?

**Comment by Hadatko** [comment]
Maybe i had different issue with similar behavior. I can simulate it on older version with setting scope. Then url and also keycloak console output is talking about wrong scope. Cannot confirm that this is exatcly same error i am getting with new version because i don't want to upgrade to non working version again, but it behaves like this:
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/13130700/2362b855-ed99-4f58-a6d0-3cdeaeeb2651)

**Comment by Hadatko** [comment]
Maybe i should create new issue.

**Comment by StefanLobbenmeierObjego** [comment]
Maybe yours is related to https://github.com/oauth2-proxy/oauth2-proxy/issues/2222

**Comment by tuunit** [comment]
For oidc and keycloak-odic you will have to set the scope manually with version v7.5.0
scope="openid groups"

We are working on getting a patch out ASAP.

**Comment by StefanLobbenmeierObjego** [comment]
@tuunit thanks for looking into this

I just tried manually adding this parameter:

            - "--scope=openid email profile"

And I could confirm that the authentication URL matches the url in 7.4.0:

https://login.microsoftonline.com/12345/oauth2/v2.0/authorize?approval_prompt=force&client_id=987654&redirect_uri=https%3A%2F%2Fcensored.de%2Fjupyter%2Fcallback&response_type=code&scope=openid+email+profile&state=censored-w%3A%2F

but after login I still get 404s. Anything else I can try?

**Comment by tuunit** [comment]
Hi @StefanLobbenmeierObjego,
which error message do you get? Can you provide the logs?

**Comment by StefanLobbenmeierObjego** [comment]
Logs from 7.5.0 after authentication, when I access censored.de/jupyter:

```
10.60.0.129:41692 - 5a47cefad4c24d00f6a52aec195898c9 - stefan.lobbenmeier@objego.de [2023/09/11 09:25:51] censored.de GET / "/jupyter" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" 302 0 0.002
10.60.0.129:41692 - 4ffa92743e9664af9b76ad84bbe26c5f - stefan.lobbenmeier@objego.de [2023/09/11 09:25:51] censored.de GET / "/jupyter/lab?" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" 200 3755 0.004
10.60.0.129:41692 - c51efe31fbada16c4cf79b2262ed0f76 - - [2023/09/11 09:25:51] censored.de GET - "/jupyter/static/lab/main.15e425005f20d2ec4ff6.js?v=15e425005f20d2ec4ff6" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" 404 19 0.000
```

Let me also grab from 7.4.0 to compare

**Comment by StefanLobbenmeierObjego** [comment]
It seems to mostly affect requests to /jupyter/static, maybe now subpaths are no longer allowed?

**Comment by StefanLobbenmeierObjego** [comment]
I wonder if I have to set something like

            - "--api-route=/jupyter/.*"

But I just tried that and it seems to disable the login page

**Comment by StefanLobbenmeierObjego** [comment]
Yeah but looks like that warning was already there. I guess the organisation is around 6.000 people.

The bigger part of the cookie seems to be _oauth2_proxy_0 with a length of 3900 characters

**Comment by StefanLobbenmeierObjego** [comment]
> @[tuunit](https://github.com/tuunit) tuunit (Jan Larwig) added this to the [v7.5.1](https://github.com/oauth2-proxy/oauth2-proxy/milestone/1) milestone [2 weeks ago](https://github.com/oauth2-proxy/oauth2-proxy/issues/2223#event-10356066501)

should I try again with the latest release or only when the ticket is closed?

**Comment by Hadatko** [comment]
New version works for me (fixed keycloak interaction).

**Comment by tuunit** [comment]
Issue has been fixed with release 7.5.1

**Comment by tuunit** [comment]
> > @[tuunit](https://github.com/tuunit) tuunit (Jan Larwig) added this to the [v7.5.1](https://github.com/oauth2-proxy/oauth2-proxy/milestone/1) milestone [2 weeks ago](https://github.com/oauth2-proxy/oauth2-proxy/issues/2223#event-10356066501)
> 
> should I try again with the latest release or only when the ticket is closed?

Please use the latest version.

**Comment by StefanLobbenmeierObjego** [comment]
I noticed in the logs that upstream is written as `-` instead of as `/` in the failing requests, so I think that means that the upstream is not recognized for the subpaths?

**Comment by anamnoid** [comment]
> Did not fix it for me unfortunately. I still have the same behaviour on 7.5.1 - base path works while subpaths return 404:
> 
> ![Screenshot 2023-09-26 at 12 36 56](https://private-user-images.githubusercontent.com/122794560/270628203-63a4806e-c1bd-4acb-87ae-ad15d28a613c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODczNDEsIm5iZiI6MTcwMjk4NzA0MSwicGF0aCI6Ii8xMjI3OTQ1NjAvMjcwNjI4MjAzLTYzYTQ4MDZlLWMxYmQtNGFjYi04N2FlLWFkMTVkMjhhNjEzYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMTU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDUzMjExNzBhYzA0YzE0ZGJjYzYwMzM2NWFjNzdlZWQ0ODJkMWQ5YjRmMzc1ZGI4YTJlNjhmMWMwMjZjZjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nJuJZsDiyHGIUqG_KlkUn3aBvNzp1j1_SPijvUHhHek)

I have the same problem.
It seems the problem in 7.5.1 is not the subpath by itself but the fragment "/static/" in the subpath.
It seems that if there is a  "/static/" in the subpath, oauth2-proxy send no request to the upstream at all, but just return 404.
May be it try to serve the request from the static file.

**Comment by StefanLobbenmeierObjego** [comment]
I see, that is a great insight. It is probably caused by https://github.com/oauth2-proxy/oauth2-proxy/pull/2025 then

**Comment by StefanLobbenmeierObjego** [comment]
Yeah I could confirm locally via git biect that this is the version where it breaks:

```
git bisect start
# status: waiting for both good and bad commits
# bad: [52ad31752d0d0b38673d419e56ddfc4cb2f56857] Feature: Add GitHub groups (orgs/teams) support  (#2196)
git bisect bad 52ad31752d0d0b38673d419e56ddfc4cb2f56857
# status: waiting for good commit(s), bad commit known
# good: [aafa96655048bc1ed26487e92410f5fe64968fa2] Merge pull request #1867 from oauth2-proxy/release-v7.4.0
git bisect good aafa96655048bc1ed26487e92410f5fe64968fa2
# bad: [738c09095bdd21d4816280e2480ec221a636d9b9] documented default for errors-to-info-log (#1990)
git bisect bad 738c09095bdd21d4816280e2480ec221a636d9b9
# good: [e079c60dfed1833c06872b20d540d979f61fbc5f] Issue 1929: Oauth2-proxy v7.4.0 is not using alpine:3.16 as it is wri… (#2013)
git bisect good e079c60dfed1833c06872b20d540d979f61fbc5f
# good: [a84e9f4d26df13d600c57ca2f5f12afb0a6b5a49] Update Dockerfile with qualified image names (#2138)
git bisect good a84e9f4d26df13d600c57ca2f5f12afb0a6b5a49
# good: [d9b9bcf9d46522aaf593e59ae34d3ef197fd36a7] Merge pull request #2192 from jawys/fix-use-x-forwarded-uri-for-pathregex-match
git bisect good d9b9bcf9d46522aaf593e59ae34d3ef197fd36a7
# bad: [bc4acd74347a0df01a6d4907d7a3f6ad3476d47d] Add docs entry to endpoints page for /oauth2/static/ path
git bisect bad bc4acd74347a0df01a6d4907d7a3f6ad3476d47d
# bad: [a02ab7c04e57c2895e4a83606f401599ca777c26] Embed static stylesheets and dependencies
git bisect bad a02ab7c04e57c2895e4a83606f401599ca777c26
# good: [bd867b5138a2152f411a00c822ef475740215ad1] Bugfix/check json path (#1921)
git bisect good bd867b5138a2152f411a00c822ef475740215ad1
# first bad commit: [a02ab7c04e57c2895e4a83606f401599ca777c26] Embed static stylesheets and dependencies
```

**Comment by StefanLobbenmeierObjego** [comment]
> I have the same problem. It seems the problem in 7.5.1 is not the subpath by itself but the fragment "/static/" in the subpath. It seems that if there is a "/static/" in the subpath, oauth2-proxy send no request to the upstream at all, but just return 404. May be it try to serve the request from the static file.

With that knowledge I pushed a fix for this, is it possible for you to verify the PR also fixes your issue?

**Comment by anamnoid** [comment]
> With that knowledge I pushed a fix for this, is it possible for you to verify the PR also fixes your issue?

Unfortunately I only can use images from https://hub.docker.com/r/bitnami/oauth2-proxy
I have no possibility for building and testing oauth2-proxy.

**Comment by StefanLobbenmeierObjego** [comment]
@tuunit can you reopen the issue since we now also know the cause and fix?

**Comment by tuunit** [comment]
You are welcome :) Thank you for your effort!

**Comment by StefanLobbenmeierObjego** [comment]
In my case I changed this in the deployment:

Before:
```yaml
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          args:
            - "--proxy-prefix=/jupyter"
            - "--redirect-url=https://hostname/jupyter/callback"
```

After
```yaml
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
          args:
            - "--proxy-prefix=/jupyter/oauth2"
            - "--redirect-url=https://hostname/jupyter/oauth2/callback"
```
