### ISSUE TITLE
oauth2-proxy should be able to set Content-Security-Policy (CSP) headers

### ISSUE THREAD

**Issue by julienlau** [oauth2-proxy/oauth2-proxy#2238]
Hi,

I use oauth2-proxy in a company that is requiring all URL to go through the script https://github.com/santoru/shcheck.
I managed to pass all checks except the Content-Security-Policy.

I cannot find any option to enable CSP headers on oauth2-proxy.
Would it be possible to implement this in the app ? I cannot use unsafe-* CSP.

Besides, when I activate the Content-Security-Policy-Report-Only header using a nginx proxy in front of oauth2-proxy I can see that there is stylesheet loaded from `https://cdn.jsdelivr.net/npm/bulma*` : this seems inappropriate. 
Would it be possible to embed the stylesheet in the application directly ?
For other resources, it may be necessary to define a nonce in the application but I am not familiar with CSP.

Regards
JL

**Comment by tuunit** [comment]
Hi @julienlau regarding the stylesheet. Please use release `v7.5.0`. We introduced embedded stylesheets and scripts with: https://github.com/oauth2-proxy/oauth2-proxy/pull/1492

**Comment by julienlau** [comment]
Ok, I am stil using 7.4.0 but will upgrade.
Still option to "set CSP" is needed I think.

**Comment by ianroberts** [comment]
> I cannot find any option to enable CSP headers on oauth2-proxy.

If you use the "alpha" config style you should be able to set a static CSP header using the `injectResponseHeaders` mechanism.  I'm not sure if that applies to the `/oauth2/*` pages generated by the proxy itself though, or just the responses it relays from an upstream.

**Comment by vyom-soft** [comment]
> > I cannot find any option to enable CSP headers on oauth2-proxy.
> 
> If you use the "alpha" config style you should be able to set a static CSP header using the `injectResponseHeaders` mechanism. I'm not sure if that applies to the `/oauth2/*` pages generated by the proxy itself though, or just the responses it relays from an upstream.

Hi, 
Can you please show some examples how to set injectRequestHeaders
Is this valid or how would it should be provided.
```
alphaConfig:
  enabled: true
  annotations: {}
  serverConfigData: {}
  metricsConfigData: {}
  configData:
    injectResponseHeaders:
    - name: X-Frame-Options
       values:
       - claim: SAMEORIGIN
    - name: X-XSS-Protection
       values:
       - claim: "1; mode=block" always
     - name: X-Content-Type-Option
        values:
        - claim: nosniff
     - name: Referrer-Policy
        values:
        - claim: no-referrer-when-downgrade
     - name: Content-Security-Policy
        values:
        - claim: default-src 'self' http: https: data: blob: 'unsafe-inline'" 
     - name: Strict-Transport-Security
        values:
        - claim: "max-age=31536000; includeSubDomains" always
```

**Comment by ianroberts** [comment]
It's a little bit more fiddly - the `claim` option is for taking values out of claims in the ID token and injecting them as response headers, if you want to set static values then you need to use the `value` option instead, but such values must be encoded in base64.  So for example:

```yaml
injectResponseHeaders:
  - name: Strict-Transport-Security
    values:
    # echo -n "max-age=3600; includeSubDomains" | base64
    - value: bWF4LWFnZT0zNjAwOyBpbmNsdWRlU3ViRG9tYWlucw==
```

**Comment by ianroberts** [comment]
Also note if you're not already on alpha config, when you enable it you will have to migrate a load of other options from your "legacy" configuration to the alpha style - with alpha config enabled any options that have an alpha equivalent are no longer accepted in the legacy style.  So you need to move at least the provider and upstream configuration into the alpha style as well as the `injectResponseHeaders`

```yaml
providers:
- provider: oidc
  id: AzureAD
  clientID: '....'
  clientSecret: '....'
  scope: 'openid email profile'
  oidcConfig:
    issuerURL: '.....'

upstreamConfig:
  upstreams:
  # The upstream tomcat containing the actual web app
  - id: /
    path: /
    uri: http://example.internal:8080/

injectResponseHeaders:
  - name: Strict-Transport-Security
    values: # as above
```

There may be others, you'll have to try it and see.
