### ISSUE TITLE
Regex path and rewriteTarget does not work for file:/// upstreams

### ISSUE THREAD

**Issue by ianroberts** [oauth2-proxy/oauth2-proxy#2242]
The `rewriteTarget` option for HTTP/HTTPS upstreams allows for arbitrary rewriting of the request URI path that is passed to the upstream.  There are use cases where it would be useful to be able to make the same sort of transformations on a `file:///` upstream that serves a static file tree, but `rewriteTarget` does not work correctly with `file:` upstreams - every request produces a 404.

Consider a case where oauth2-proxy is protecting a single page application.  The whole application is contained in one `index.html` file plus a set of static assets for the JS and CSS:

- /var/www/app/
  - index.html
  - assets/
    - main.{hash}.js
    - style.{hash}.css

In order to support deep links into the application, we want to serve the assets folder as `https://example.com/assets/`, but _any other URL_ should return the content of `index.html`, so the SPA can inspect the page URL and route appropriately.  This would require (alpha) configuration like this:

```yaml
upstreamConfig:
  upstreams:
  # Send API calls to the backend
  - id: api
    path: ^/api/(.*)$
    rewriteTarget: /$1
    uri: http://backend.internal:8080/
  # Serve static assets
  - id: assets
    path: /assets/
    uri: file:///var/www/app/assets
  # For any other URL, return the index page
  - id: spa
    path: ^/(.*)
    rewriteTarget: /
    uri: file:///var/www/app
```

## Expected Behavior

- A request for `https://example.com/assets/main.12345.js` should return that file from the assets folder
- A request for `https://example.com/` should return the index page
- A request for `https://example.com/myprofile` should _also_ return the index page

## Current Behavior

- A request for `https://example.com/assets/main.12345.js` does return that file from the assets folder
- A request for `https://example.com/` gives "404 page not found"
- A request for `https://example.com/myprofile` gives "404 page not found"

## Possible Solution

At present, when we register a `file:///` upstream we use

```go
http.StripPrefix(path, http.FileServer(http.Dir(filesystemPath)))
```

where `path` is the `path:` option for the upstream and `filesystemPath` is the path component of the upstream `file:` URI.  But the `http.StripPrefix` handler always returns 404 if it is asked to handle a URL that does not have the configured prefix.  When the upstream `path` option is a regex it will likely never be an exact prefix of any actual URL path (because it will include metacharacters like `^`, `()`, `*`), so the `StripPrefix` handler will always 404.

The solution would be to only use the `StripPrefix` handler if the upstream is _not_ configured with a `rewriteTarget` - if a `rewriteTarget` is provided then the regex rewrite is what is responsible for mapping the matched path to the correct relative path within the target file tree.

## Your Environment

- Version used: 7.5.0, on Mac arm64 but this isn't a platform-specific problem
