### ISSUE TITLE
[provider/google] Switch from serviceAccountJson to ApplicationDefaultCredentials gives 403

### ISSUE THREAD

**Issue by Pionerd** [oauth2-proxy/oauth2-proxy#2260]
## Expected Behavior

When retrieving groups from Google, we want to use Application Default Credentials (Workload Identity) on GKE instead of the serviceAccountJson. We expect this to work.

## Current Behavior

Using helm, disabling `.Values.config.google.serviceAccountJson` and enabling `.Values.config.google.useApplicationDefaultCredentials` leads to an error:

```
[2023/10/06 09:52:52] [google.go:298] error checking group membership: googleapi: Error 403: Not Authorized to access this resource/api, forbidden
[2023/10/06 09:52:52] [internal_util.go:73] 200 GET https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=<very long access token>... {
  "issued_to": "<oauth2_client_id>",
  "audience": "<oauth2_client_id>",
  "user_id": "<client_id_of_service_account>",
  "scope": "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email openid",
  "expires_in": 3598,
  "email": "<admin_email>",
  "verified_email": true,
  "access_type": "offline"
}

10.120.65.29:57588 - b7f494277bf389229b71041a12bdce75 - <admin_email> [2023/10/06 09:52:52] [AuthFailure] Invalid authentication via OAuth2: unauthorized
```

## Possible Solution

Ran out of ideas

## Steps to Reproduce (for bugs)

We configured our environment using helm, but for the sake of clarity I just post the commands and config below. 

Command: `/bin/oauth2-proxy --http-address=0.0.0.0:4180 --https-address=0.0.0.0:4443 --metrics-address=0.0.0.0:44180 --config=/etc/oauth2_proxy/oauth2_proxy.cfg --google-admin-email=<admin_email> --google-use-application-default-credentials=true --google-group=<group_email>`

/etc/oauth2_proxy/oauth2_proxy.cfg
```
email_domains = [ "*" ]
upstreams = [ "http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth" ]
whitelist_domains = [".<domain>"]
cookie_domains = ["<domain>"]
```

Service Account
```
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    # Correct annotation set
    iam.gke.io/gcp-service-account: <service_account_email_address>  
  labels:
    app: oauth2-proxy
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/version: 7.5.1
    argocd.argoproj.io/instance: oauth2-proxy
    helm.sh/chart: oauth2-proxy-6.17.1
  name: oauth2-proxy
  namespace: oauth2-proxy
[...]
```

We use workload identity for other apps, that is working fine. The role binding was created using:

```
gcloud iam service-accounts add-iam-policy-binding --project <project_id> <service_account_email_address> \
    --role roles/iam.workloadIdentityUser \
    --member "serviceAccount:<project_id>.svc.id.goog[oauth2-proxy/oauth2-proxy]"
```

## Context

Groups were loaded fine using the serviceAccountJson setting. To state the obvious: the service account used for Workload Identity and the serviceAccountJson are the same. We expect this to be a drop in replacement.

## Your Environment

- Version used: 7.5.1
- Helm chart: 6.17.1
- GKE 1.26.7

@kvanzuijlen forgive my tagging you here, but since I saw you did all the implementation, maybe you're interested. Dankjewel.
