### ISSUE TITLE
7.5.1 does not work with adfs

### ISSUE THREAD

**Issue by CodeGlitcher** [oauth2-proxy/oauth2-proxy#2261]
We upgraded oauth2 proxy from 7.5.0 to 7.5.1 but the application no longer works with adfs.

We use the following config:
  configFile: |-
    provider="adfs"
    email_domains = [ "{{ email suffix}}" ]
    upstreams = [ "{{ upstream}}" ]
    oidc_issuer_url="{{ endpoint_external_adfs }}"
    pass_authorization_header="true"
    ssl_upstream_insecure_skip_verify="false"
    tls_cert_file="/certs/tls.crt"
    tls_key_file="/certs/tls.key"
    ping_path="/ping"
    cookie_expire="0h10m0s"
    cookie_refresh="0h5m0s"
    client_secret_file="/secret/clientSecret"
    skip_provider_button="true"
    client_id="{{ proxy_client_id}}"

After the upgrade we see the following error in our log:
[2023/10/06 11:44:10] [oauthproxy.go:834] Error redeeming code during OAuth2 callback: could not get claim "groups": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "401":

We have tried diffent settings:
manually settings scopes to: email openid profile
our the adfs side we tried to enable more scopes for the oauth2 client but with no result.
It does not matter what are configure only after rolling back to 7.5.0 our users can login.

We didnt expect any breaking changes with a patch version. 
Any idea's what is causing this error?

**Comment by tuunit** [comment]
The only change that could possibly have effect this. Is the following https://github.com/oauth2-proxy/oauth2-proxy/pull/2229

Unfortunately, none of the maintainers currently has access to an active ADFS environment and we heavily rely on community feedback.

I will check the implications of the change mentioned above once more.

**Comment by CodeGlitcher** [comment]
That would be great.
If there is a way I can provide additional logging please let me known

**Comment by tuunit** [comment]
Hi @CodeGlitcher, is that your full configuration. You provided above? I'm wondering how the provider has been selected and which login url you are using.

**Comment by CodeGlitcher** [comment]
Yes that is de full config
This is the full helm chart values.yml:
Everything between {{ }} is repalced by an actual value during our deployment.
```
# Source: https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml
# Force the target Kubernetes version (it uses Helm `.Capabilities` if not set).
# This is especially useful for `helm template` as capabilities are always empty
# due to the fact that it doesn't query an actual cluster
kubeVersion:

{% set k8s_dashboard_proxy_cookie_encryption_key_name = "kubernetes-dashboard-proxy-cookie-encryption-key" %}
# Oauth client configuration specifics
config:
  # Add config annotations
  annotations: {}
  # variable are set in configfile manually.
  # This because in our setup the id does need to be a secret.
  # passwords are generated / loaded from vault
  clientID: "not_used"
  clientSecret: "not_used"
  cookieSecret: "not_used"
  cookieName: ""
  configFile: |-
    provider="adfs"
    email_domains = [ "{{ domain_suffix }}" ]
    upstreams = [ "{{ endpoint_internal_kubernetesdashboard }}" ]
    oidc_issuer_url="{{ endpoint_external_adfs }}"
    pass_authorization_header="true"
    ssl_upstream_insecure_skip_verify="false"
    tls_cert_file="/certs/tls.crt"
    tls_key_file="/certs/tls.key"
    ping_path="/ping"
    cookie_expire="0h10m0s"
    cookie_refresh="0h5m0s"
    client_secret_file="/secret/clientSecret"
    skip_provider_button="true"
    client_id="{{ kubernetes_dashboard_adfs_applicationname }}"

image:
  repository: "{{cluster_registry_hostname}}/{{containers_to_deploy.oauth2_proxy.image}}"
  tag: "{{containers_to_deploy.oauth2_proxy.tag}}"
  pullPolicy: "Always"

imagePullSecrets:
  - name: regcred

extraArgs: {}
extraEnv:
  - name: SSL_CERT_DIR
    value: /certs/ca
  - name: OAUTH2_PROXY_COOKIE_SECRET
    valueFrom:
      secretKeyRef:
        name: "{{ k8s_dashboard_proxy_cookie_encryption_key_name }}"
        key: password

# -- Custom labels to add into metadata
customLabels:

service:
  type: NodePort
  portNumber: 4443
  nodePort: 32001
  annotations: {}

## Create or use ServiceAccount
serviceAccount:
  ## Specifies whether a ServiceAccount should be created
  enabled: true
  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the fullname template
  name: k8s-dashboard-proxy
  automountServiceAccountToken: false
  annotations: {}

resources:
  requests:
    cpu: {{ouath2ProxyCpuRequest}}
  #   memory: 300Mi

extraVolumes: 
  - name: certs
    secret:
      secretName: certs
      items:
      - key: ca.crt
        path: ca/ca.crt
  - name: client-secret
    secret: 
      secretName: kubernetesdashboard-secret
  - name: ssl-certs
    emptyDir: {}
  - name: k8s-cert
    secret:
      secretName: k8s-cert
      items:
      - key: tls.crt
        path: tls.crt
      - key: tls.key
        path: tls.key
      - key: ca.crt
        path: ca/ca.crt
extraVolumeMounts:
  - name: ssl-certs
    mountPath: /etc/ssl/certs
  - name: k8s-cert
    mountPath: "/certs"
    readOnly: true
  - name: client-secret
    mountPath: "/secret"
    readOnly: true

priorityClassName: "lower"

# Host aliases, useful when working "on premise" where (public) DNS resolver does not know about my hosts.
hostAlias:
  enabled: false
  # ip: "10.xxx.xxx.xxx"
  # hostname: "auth.example.com"

# Whether to use secrets instead of environment values for setting up OAUTH2_PROXY variables
proxyVarsAsSecrets: false

# Configure Kubernetes liveness and readiness probes.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
# Disable both when deploying with Istio 1.0 mTLS. https://istio.io/help/faq/security/#k8s-health-checks
livenessProbe:
  enabled: true
  initialDelaySeconds: 0
  timeoutSeconds: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1

# Configure Kubernetes security context for container
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  enabled: false
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  runAsUser: 2000

deploymentAnnotations: {}
podAnnotations: {}
podLabels:
  egress-infrastructure-vault: ""
  egress-external-adfs: ""
  egress-kubernetes-dashboard-kubernetes-dashboard: ""
replicaCount: 1

## PodDisruptionBudget settings
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
podDisruptionBudget:
  enabled: false

# Configure Kubernetes security context for pod
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
podSecurityContext: {}

# whether to use http or https
httpScheme: https

# Configure the session storage type, between cookie and redis
sessionStorage:
  # Can be one of the supported session storage cookie|redis
  type: cookie

# Enables apiVersion deprecation checks
checkDeprecation: true

# Extra K8s manifests to deploy
extraObjects:
  - apiVersion: v1
    kind: Secret
    data:
      # create a random password for the encryption key
      password: "{{ pusher_kubernetes_dashboard_proxy_encryption_key | b64encode }}"
    metadata:
      labels:
        app.kubernetes.io/part-of: kubernetes-dashboard
      name: "{{ k8s_dashboard_proxy_cookie_encryption_key_name }}"
      namespace: kubernetes-dashboard
    type: Opaque
```
Our test env is not exposed public but It points to
https://ad-server/adfs

from the adfs/.well-known/openid-configuration
you get the normal openid configuration:

```
{
    "issuer": "https:\/\/ad-server\/adfs",
    "authorization_endpoint": "https:\/\/ad-server\/adfs\/oauth2\/authorize\/",
    "token_endpoint": "https:\/\/ad-server\/adfs\/oauth2\/token\/",
    "jwks_uri": "https:\/\/ad-server\/adfs\/discovery\/keys",
    "token_endpoint_auth_methods_supported": [
        "client_secret_post",
        "client_secret_basic",
        "private_key_jwt",
        "windows_client_authentication"
    ],
    "response_types_supported": [
        "code",
        "id_token",
        "code id_token",
        "id_token token",
        "code token",
        "code id_token token"
    ],
    "response_modes_supported": [
        "query",
        "fragment",
        "form_post"
    ],
    "grant_types_supported": [
        "authorization_code",
        "refresh_token",
        "client_credentials",
        "urn:ietf:params:oauth:grant-type:jwt-bearer",
        "implicit",
        "password",
        "srv_challenge",
        "urn:ietf:params:oauth:grant-type:device_code",
        "device_code"
    ],
    "subject_types_supported": [
        "pairwise"
    ],
    "scopes_supported": [
        "aza",
        "profile",
        "user_impersonation",
        "vpn_cert",
        "winhello_cert",
        "openid",
        "allatclaims",
        "logon_cert",
        "email"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "token_endpoint_auth_signing_alg_values_supported": [
        "RS256"
    ],
    "access_token_issuer": "http:\/\/ad-server\/adfs\/services\/trust",
    "claims_supported": [
        "aud",
        "iss",
        "iat",
        "exp",
        "auth_time",
        "nonce",
        "at_hash",
        "c_hash",
        "sub",
        "upn",
        "unique_name",
        "pwd_url",
        "pwd_exp",
        "mfa_auth_time",
        "sid",
        "nbf"
    ],
    "microsoft_multi_refresh_token": true,
    "userinfo_endpoint": "https:\/\/ad-server\/adfs\/userinfo",
    "capabilities": [
        "kdf_ver2"
    ],
    "end_session_endpoint": "https:\/\/ad-server\/adfs\/oauth2\/logout",
    "as_access_token_token_binding_supported": true,
    "as_refresh_token_token_binding_supported": true,
    "resource_access_token_token_binding_supported": true,
    "op_id_token_token_binding_supported": true,
    "rp_id_token_token_binding_supported": true,
    "frontchannel_logout_supported": true,
    "frontchannel_logout_session_supported": true,
    "device_authorization_endpoint": "https:\/\/ad-server\/adfs\/oauth2\/devicecode"
}
```
