### ISSUE TITLE
http oidc_issuer_url redirect to https

### ISSUE THREAD

**Issue by shywei** [oauth2-proxy/oauth2-proxy#2266]
I have a self-hosted gitlab instance and I want to use it as a oauth provider. 
I deploy nginx and oauth2-proxy by docker. 
The gitlab address is set by oidc_issuer_url in oauth2-proxy.cfg and cookie_secure is set to false.
However, the login page always automatically redirect to https, causing an error.
like this:
`https://193.160.63.190:8082/oauth/authorize?approval_prompt=force&client_id=clientid&nonce=Ss8LFUiB30_CzEFqMBuq44pPd_dteEwLuK5m_-CKJwc&redirect_uri=http%3A%2F%2F193.160.63.190%2Foauth2%2Fcallback&response_type=code&scope=openid+email&state=l38-DaEksqjKJ5OjQwk_TyQj3m6x6BZeOQI4HgjhVI4%3A%2F`

## Expected Behavior
redirect to the gitlab in http

## Current Behavior
redirect to https cause error

## Steps to Reproduce (for bugs)

1. docker-compose.yml of oauth2-proxy
```
version: "3.7"

services:
  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.5.1
    command: --config /etc/oauth2-proxy.cfg 
    ports:
      - 4180:4180
    volumes:
      - /home/cicd/oauth2-proxy/oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
    restart: always
``` 
2. oauth2-proxy.cfg
```
http_address="0.0.0.0:4180"
cookie_secret="secret"
provider="gitlab"
email_domains="*"
client_id="clientid"
client_secret="secret"
redirect_url="http://193.160.63.190/oauth2/callback"
set_xauthrequest="true"
upstreams=[
  "http://193.160.63.190/"
]
cookie_csrf_per_request="true"
cookie_csrf_expire="5m"
cookie_secure="false"
cookie_refresh="5m"
skip_auth_preflight="true"
skip_provider_button="true"
oidc_issuer_url="http://193.160.63.190:8082"
cookie_domains="193.160.63.190"
whitelist_domains="193.160.63.190"
```
3.docker-compose.yml of nginx
```
version: '3'

services:
  nginx:
    restart: always
    image: nginx:1.25.0
    container_name: cicd-nginx
    ports:
      - 80:80
      - 9003:9003
    volumes:
      - /home/cicd/nginx/nginx.conf:/etc/nginx/nginx.conf
```
4.nginx.conf
```
user nginx;
worker_processes auto;

events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name localhost;
    
    location /oauth2/ {
      proxy_pass       http://193.160.63.190:4180;
      proxy_set_header Host                    $host;
      proxy_set_header X-Real-IP               $remote_addr;
      proxy_set_header X-Scheme                $scheme;
      proxy_set_header X-Auth-Request-Redirect $request_uri;
    }

    location = /oauth2/auth {
      proxy_pass       http://193.160.63.190:4180;
      proxy_set_header Host             $host;
      proxy_set_header X-Real-IP        $remote_addr;
      proxy_set_header X-Scheme         $scheme;
      proxy_set_header Content-Length   "";
      proxy_pass_request_body           off;
    }

    location / {
      auth_request /oauth2/auth;
      error_page 401 = /oauth2/sign_in;

      auth_request_set $user   $upstream_http_x_auth_request_user;
      auth_request_set $email  $upstream_http_x_auth_request_email;
      proxy_set_header X-Auth-Request-User $user;
      proxy_set_header X-Email $email;
      auth_request_set $token  $upstream_http_x_auth_request_access_token;
      proxy_set_header X-Access-Token $token;
      auth_request_set $auth_cookie $upstream_http_set_cookie;
      add_header Set-Cookie $auth_cookie;
      auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;
      if ($auth_cookie ~* "(; .*)") {
        set $auth_cookie_name_0 $auth_cookie;
        set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
      }
      if ($auth_cookie_name_upstream_1) {
        add_header Set-Cookie $auth_cookie_name_0;
        add_header Set-Cookie $auth_cookie_name_1;
      }

      proxy_pass  http://193.160.63.190:8091/;
    } 
  }
}
```

## Your Environment

- Version used: 7.5.1
