### ISSUE TITLE
keycloak-oidc: failed to discover OIDC configuration: unexpected status "526"

### ISSUE THREAD

**Issue by avmp2208** [oauth2-proxy/oauth2-proxy#2276]
Hello.

I have been working with the chart to installs the oauth2 proxy and created a HelmRelease to do so, 

---
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: "4.1.6"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: oauth2-proxy
  interval: 10m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    args:
      - --provider=keycloak-oidc
      - --client-id=my-client
      - --client-secret=my-secret
      - --redirect-url=https://oauth2.domain.com/oauth2/callback
      - --oidc-issuer-url=https://keycloak.domain.com/realms/master
      - --email-domain=*
      - --code-challenge-method=S256 // PKCE
```

This is the error im getting when the pod in my kubernetes cluster tries to start

[2023/10/20 02:21:08] [provider.go:55] Performing OIDC Discovery...                                                                                                                                                                       [2023/10/20 02:21:08] [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error initialising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: unexpected status "526": 

Am I doing anything wrong in here?

- Version used: Latest

thank you in advance. 
Regards
