### ISSUE TITLE
Traefik keycloak group not being authorized after successful login

### ISSUE THREAD

**Issue by avmp2208** [oauth2-proxy/oauth2-proxy#2294]
Hello team
Im trying to use the configuration with Keycloak, Traefik and Kubernetes dashboard

## Expected Behavior

Go to the kubernetes dashboard if there is no valid sesion it will redirect to the oauth2 proxy url and this will send the keycloak url soi the user can authenticate and login successful if the user if in a certain keycloak group.

## Current Behavior

The user authenticates successfully but even he is in the correct group he cannot see anything in the kubernetes dashboard
With the correct ClusterRoleBinding and group he should be able to see everything 

## Steps to Reproduce (for bugs)

**This is my  OAuth2 Proxy release configuration**
```
values: 
    extraArgs:
      - --oidc-groups-claim="groups"
      - --allowed-group="role:k8s-admins" //I figured out when I use group membershipo mapper type the prefix  "role" comes in 
      - --set-xauthrequest=true
      - --set-authorization-header=true
      - --pass-access-token=true
      - --pass-authorization-header=true
      - --pass-user-headers=true
      - --pass-host-header=true
      - --scope=openid email profile groups
      - --skip-provider-button=true
      - --skip-jwt-bearer-tokens=true
      - --insecure-oidc-allow-unverified-email=false
      - --insecure-oidc-skip-issuer-verification=true
      - --ssl-insecure-skip-verify=true
      - --ssl-upstream-insecure-skip-verify=true
      - --reverse-proxy=true
      - --cookie-secure=true
      - --cookie-domain=.workhorse.com
      - --whitelist-domain=.workhorse.com
      - --cookie-samesite=lax
      - --cookie-csrf-per-request=true
      - --cookie-name=workhorse-oauth2-proxy
      - --provider=keycloak-oidc
      - --oidc-issuer-url=https://keycloak.company.com/realms/myrealm
      - --redirect-url=https://oauth2.company.com/oauth2/callback
      - --email-domain=*
      - --upstream="static://202"
    config:
      existingSecret: oauth2-proxy-secret
```

**Here are my ingressroutes** 
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`oauth2.company.com`)
      kind: Rule
      services:
        - name: oauth2-proxy
          port: 80
      middlewares:
      - name: auth-headers

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wildcard-auth
  namespace: oauth2-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`*.company.com`) && PathPrefix(`/oauth2/`)
      kind: Rule
      services:
        - name: oauth2-proxy
          port: 80
      middlewares:
      - name: auth-headers

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: oauth2-proxy
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: workhorse.com
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
```

### My keycloak configruation

**Client settings**

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/10584870/5226b7a8-d345-4d2b-8d88-cb2ab96e8c8b)

**Mapper config for Groups**

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/10584870/139f55a7-0f0f-4716-ad08-3c680177a0c1)

**Audience mapper config**

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/10584870/b2e97d94-3bbc-4beb-bf7a-04b73ade3ffa)

This is a log I get in the oauth2 pod after login success

`- username@company.com [2023/10/26 13:43:54] [AuthSuccess] Authenticated via OAuth2: Session{email:username@company.com user:8122404f-718b-4985-9406-a3d7da1e455b PreferredUsername:username@company.com token:true id_token:true created:2023-10-26 13:43:54.805875242 +0000 UTC m=+35088.969514054 expires:2023-10-28 13:43:54.761995367 +0000 UTC m=+207888.925634179 refresh_token:true groups:[role:k8s-admins]}`

This is a log for example if I refresh the kubernetes dashboard screen

`- username@company.com [2023/10/26 13:39:10] kubernetes-dashboard.company.com GET static://202 "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" 202 13 0.001`

Here is the role binnding I have for my cluster, I have ClusterRole  and ClusterroleBinding, also have Role and RoleBinding, but none of them sicne to work either

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-admins
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-admins
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: role:k8s-admins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-admins-role
  namespace: my-namespace
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-admins-role
  namespace: my-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-admins-role  
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: role:k8s-admins
    namespace: my-namespace
```

## Context

This is affecting to see the  kubernetes dashboard resources, for example if Im logged in successfuly kubernetes wont see the group and wont give authorization to do anything

## Your Environment

k3s latest version
Traefik v2.9.10
Keycloak latest version

- Version used:
app/version=7.5.1                                                                                                                                                                                         chart/version=oauth2-proxy-6.18.0

**Comment by avmp2208** [comment]
I even enabled redis because I was looking at the log and there were some issues with the cookie that was 4kb. so I fixed that issue but nothing change, I dont see any solution yet.
also I was looking into this documentation but I dont anything different and they say it is working with kubernetes dashboard

https://github.com/oauth2-proxy/oauth2-proxy/issues/1355#issuecomment-1257379627

**Comment by tuunit** [comment]
Hi @thatInfrastructureGuy,

as you wrote the comment / solution mentioned by @avmp2208. Might you have any input on this?

**Comment by avmp2208** [comment]
Adding more information.
I have noticed that maybe the problem is not the oauth2 proxy configuration at all, because when I go directly to the oauth2 proxy url and login to keycloak im able to see the headers in the response

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/10584870/241db68a-941c-43e3-ba13-eea999ff41ff)

but if I do that with the kubernetes dashboard, I mean go to the dashboard got redirected to oauth2 proxy and finally to keycloak authentication screen, after login successfully ( groups validation works, btw) Im getting the **unauthorized** issue

**![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/10584870/4f868ef7-774d-4dcf-be19-4b8ee2694d61)**

So, it looks like the issue is somewhere else, im stuck on this and it is frustrating haha
Appreciate any help

This is my updated oauth2 proxy config

```
      - --http-address=0.0.0.0:4180
      - --metrics-address=0.0.0.0:44180
      - --provider=keycloak-oidc
      - --oidc-issuer-url=https://keycloak.company.com/realms/myrealm
      - --redirect-url=https://oauth2.company.com/oauth2/callback
      - --cookie-secure=false
      - --cookie-domain=.company.com
      - --cookie-refresh=10m
      - --cookie-expire=1h
      - --session-store-type=redis
      - --redis-connection-url=redis://oauth2-proxy-redis-master:6379
      - --whitelist-domain=.company.com
      - --cookie-samesite=lax
      - --email-domain=*
      - --upstream="static://202"
      - --oidc-groups-claim=groups
      - --oidc-email-claim=email
      - --scope=openid email groups roles #depends on your provider
      - --pass-authorization-header=true
      - --set-authorization-header=true
      - --set-xauthrequest=true
      - --pass-access-token=true
      - --pass-host-header=true
      - --skip-provider-button=true
      - --skip-jwt-bearer-tokens=true
      - --insecure-oidc-allow-unverified-email=false
      - --insecure-oidc-skip-issuer-verification=true
      - --show-debug-on-error=true
      - --silence-ping-logging=true
      - --ssl-insecure-skip-verify=true
      - --ssl-upstream-insecure-skip-verify=true
      - --reverse-proxy=true
      - --force-https=false 
      - --cookie-csrf-per-request=true
      - --allowed-group="k8s-admins"
```

Thanks team

**Comment by JoelSpeed** [comment]
Looks to me like a middleware or ingressroute issue. As you've shown, OAuth2 Proxy is returning the authorization header correctly, but, I don't see any configuration that would tell Traefik how to copy it across to the request it then sends to the backend.

I'm not a Traefik user so not sure what that config would look like though, but I certainly think the issue is outside of OAuth2 Proxy given what you've described here

**Comment by avmp2208** [comment]
@JoelSpeed this is the kubernetes dashboard ingressroute

```
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`kubernetes-dashboard.company.com`)
    kind: Rule
    services:
    - name: kubernetes-dashboard
      port: 443
      serversTransport: kubernetes-dashboard-transport
    middlewares:
    - name: auth    
```

and this is the auth middleware 

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: kubernetes-dashboard
spec:
  forwardAuth:
    address: https://oauth2.company.com
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization  

```

if you see both are in the same namespace

my traefik config release is simple actually, I put everything as insecure to bypass security, I had this ad trustedip but the issue is the same.

```
    additionalArguments:
      - --entryPoints.websecure.forwardedHeaders.insecure=true
      - --entryPoints.websecure.proxyProtocol.insecure=true
```

something actually I noticed as well is, if I dont skip the oidc button for login I have 403 issue
So, I have to use this flag **- --skip-provider-button=true**  in order to login to keycloak

Thanks in advanced

**Comment by avmp2208** [comment]
**Adding more information**

Im actually using this official config now

https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#forwardauth-with-static-upstreams-configuration

Still having the issue.

**Comment by thatInfrastructureGuy** [comment]
As @tuunit mentioned,  OAuth2-Proxy was working for me with Traefik.

My Test Environment:
* OneLogin
* AWS NLB 
* Traefik
* OAuth2-Proxy v7.3.0
* Redis v7
* traefik/whoami as my test app

```yaml
        containers:
        - args:
          - --http-address=0.0.0.0:4180
          - --metrics-address=0.0.0.0:44180
          - --provider=oidc
          - --provider-display-name=OneLogin
          - --oidc-issuer-url=https://mySubdomain.onelogin.com/oidc/2
          - --redirect-url=https://oauth2-proxy.mydomain.com/oauth2/callback
          - --code-challenge-method=S256
          - --cookie-name=SESSION
          - --cookie-secure=true
          - --cookie-refresh=30m
          - --cookie-domain=.mydomain.com
          - --whitelist-domain=.mydomain.com
          - --cookie-samesite=lax
          - --session-store-type=redis
          - --redis-connection-url=redis://default:$(REDIS_PASS)@redis:6379
          - --email-domain=*
          - --upstream="static://202"
          - --oidc-groups-claim=groups
          - --oidc-email-claim=email
          - --scope=openid profile email groups
          - --pass-authorization-header=true
          - --set-authorization-header=true
          - --set-xauthrequest=true
          - --pass-access-token=true
          - --pass-host-header=true
          - --skip-provider-button=true
          - --skip-jwt-bearer-tokens=true
          - --banner=-
          - --footer=MyOrg
          - --insecure-oidc-allow-unverified-email=false
          - --insecure-oidc-skip-issuer-verification=false
          - --show-debug-on-error=false
          - --silence-ping-logging=true
          - --ssl-insecure-skip-verify=false
          - --ssl-upstream-insecure-skip-verify=false
          - --reverse-proxy=true
          - --force-https=false
```

IngressRoute for OAuth2-Proxy
```yaml
  apiVersion: traefik.containo.us/v1alpha1
  kind: IngressRoute
  metadata:
    name: oauth2-proxy
    namespace: oauth2-proxy
  spec:
    entryPoints:
    - websecure
    routes:
    - kind: Rule
      match: Host(`oauth2-proxy.mydomain.com`)
      services:
      - name: oauth2-proxy
        port: 80
```

where my `redis` container had the following args:
```yaml
       - args:
          - --save
          - ""
          - --appendonly
          - "no"
          - --requirepass
          - $(REDIS_PASS)
```

Target Application IngressRoute/Middleware
```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: whoami
spec:
  forwardAuth:
    address: https://oauth2-proxy.mydomain.com
    authResponseHeaders:
    - Authorization
    - Set-Cookie
    authResponseHeadersRegex: ^X-
    trustForwardHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: whoami
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`whoami.mydomain.com`) && PathPrefix(`/`)
    middlewares:
    - name: auth
    services:
    - kind: Service
      name: whoami
      port: 80
---
```

This test worked with kubernetes-dashboard as well.
