### ISSUE TITLE
Azure provider fails when scope is not Microsoft Graph

### ISSUE THREAD

**Issue by mvalenzisi** [oauth2-proxy/oauth2-proxy#2314]
My AAD application is configured for the following API permissions:
![Screenshot from 2023-11-08 16-15-02](https://github.com/oauth2-proxy/oauth2-proxy/assets/36044907/d1a951fe-1b4b-45ae-9a19-4bf01ea204a8)
to be able to authenticate against Azure Kubernetes.

The proxy is configured like follows:
```
provider: azure
oidc-issuer-url: https://login.microsoftonline.com/[REDACTED]/v2.0
scope: 6dae42f8-4368-4678-94ff-3960e28e3630/.default
```
and I get the error:
`The scope 6dae42f8-4368-4678-94ff-3960e28e3630/.default https://graph.microsoft.com/.default is not valid. static scope limit exceeded.`
because the proxy adds the scope `https://graph.microsoft.com/.default`, but in my case I don't need Microsoft Graph.

If I try to use `provider: oidc` instead, I get the error `Error redeeming code during OAuth2 callback: token response did not contain an id_token`.

One possible solution would be to allow passing custom scopes without adding `https://graph.microsoft.com/.default`.

**Comment by ianroberts** [comment]
I had a similar problem with the `oidc` provider logging in to Azure, in my case I tracked it down to the fact that the proxy was unable to fetch the groups from the userinfo endpoint without the Microsoft Graph scope.  In my case I don't actually care about group membership (I'm only using OIDC for authentication, I handle authorization directly in my own app) so I ended up with the following workaround (sorry, I use alpha config, and and `envsubst`-type transformation on my config file to insert the right values for the `@FOO@` placeholders):

```yaml
providers:
- provider: oidc
  id: AzureAD
  clientID: '@CLIENT_ID@'
  clientSecretFile: '@CLIENT_SECRET_FILE@'
  scope: '@OAUTH_SCOPE@'
  oidcConfig:
    emailClaim: email
    groupsClaim: groups
    audienceClaims: ["aud"]
    insecureSkipNonce: true
    # set next line to true when using the "common" issuer URL, since the actual
    # token issuer in this case has a specific tenant ID instead of "common"
    insecureSkipIssuerVerification: false
    issuerURL: https://login.microsoftonline.com/@OIDC_TENANT_ID@/v2.0
    userIDClaim: email
    # By default oauth2-proxy discovers the userinfo URL, and then fails to log
    # in as it can't fetch the groups list from there.  We don't care about AAD
    # group memberships, so instead we must disable discovery and manually
    # configure the other URLs that would normally be discovered but leave the
    # profileURL blank.  This way it doesn't attempt to fetch groups at all.
    skipDiscovery: true
    jwksURL: https://login.microsoftonline.com/@OIDC_TENANT_ID@/discovery/v2.0/keys
  loginURL: https://login.microsoftonline.com/@OIDC_TENANT_ID@/oauth2/v2.0/authorize
  redeemURL: https://login.microsoftonline.com/@OIDC_TENANT_ID@/oauth2/v2.0/token
```

essentially, skip discovery and instead configure the login, redeem and jwks URLs by hand.  If no profile URL is set then it will just use the ID token groups (if any) and not try to enrich the list by calling out to the userinfo endpoint.

**Comment by mvalenzisi** [comment]
@ianroberts what do you have as `scope`?
In my case, if I replicate your configuration with my `scope: 6dae42f8-4368-4678-94ff-3960e28e3630/.default` I still get `Error redeeming code during OAuth2 callback: token response did not contain an id_token`.

**Comment by ianroberts** [comment]
I'm just using the normal OIDC scope `openid email profile` plus a custom app-specific scope of my own.  According to the [Entra docs](https://learn.microsoft.com/en-gb/entra/identity-platform/scopes-oidc#openid) you _must_ request at least the `openid` scope when authenticating using OIDC, and you probably want to request the `email` and `profile` scopes too in order to get the user's email address and preferred username in the resulting ID token.

**Comment by mvalenzisi** [comment]
With this configuration:
```
provider: oidc
oidc-issuer-url: https://login.microsoftonline.com/[REDACTED]/v2.0
login-url: https://login.microsoftonline.com/[REDACTED]/v2.0/oauth2/authorize
redeem-url: https://login.microsoftonline.com/[REDACTED]/v2.0/oauth2/token
oidc-jwks-url: https://login.microsoftonline.com/[REDACTED]/v2.0/keys
user-id-claim: email
oidc-email-claim: email
oidc-audience-claim: aud
scope: openid email 6dae42f8-4368-4678-94ff-3960e28e3630/.default
```
I get: 
`[2023/11/09 12:47:16] [oauthproxy.go:834] Error redeeming code during OAuth2 callback: could not get claim "groups": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "401": {"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience.","innerError":{"date":"2023-11-09T12:47:16","request-id":"7db7caee-4d3c-43fd-902f-6d19157af20f","client-request-id":"7db7caee-4d3c-43fd-902f-6d19157af20f"}}}`

If I remove `email` from the scopes I get:
`[2023/11/09 12:49:04] [oauthproxy.go:834] Error redeeming code during OAuth2 callback: could not get claim "email": failed to fetch claims from profile URL: error making request to profile URL: unexpected status "401": {"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience.","innerError":{"date":"2023-11-09T12:49:04","request-id":"94bfcaca-6bf6-408a-ad9d-17613d3cf7f9","client-request-id":"94bfcaca-6bf6-408a-ad9d-17613d3cf7f9"}}}
`

**Comment by ianroberts** [comment]
If you don't need the groups then you must configure it to skip discovery to stop it from trying to fetch them.

Normally the discovery process is used to find the login, redeem, jwks _and profile_ URLs, to stop it trying to fetch the profile you must disable discovery, but then you need to provide the other three URLs yourself.

**Comment by mvalenzisi** [comment]
Right, I totally forgot to include `skipDiscovery`.
Thanks @ianroberts

**Comment by nilsgstrabo** [comment]
@JoelSpeed First of all, a **BIG** thanks to you and all the other contributors.

Regarding this issue, and the related #1666.
The problem is that the ClaimsProvider will call the ProfileURL (provided manually or by OIDC discovery) with the access token received from the OIDC token endpoint. When the scope defines an API, e.g. `scope: openid 6dae42f8-4368-4678-94ff-3960e28e3630/.default`, the `aud` claim is not valid for the ProfileURL, and the request will fails with status 401. This error will then make oauth2-proxy return a 500 Internal Server Error to the client.
https://github.com/oauth2-proxy/oauth2-proxy/blob/53cd0b83d3dc455488d24da029f03ee61afbf90c/pkg/providers/util/claim_extractor.go#L98-L105

I know I can use the work-around and set skipDiscovery: true and all the *URL properties manually, but I would be much better to use OIDC discovery, but skip loading claims from the ProfileURL,

My suggestion is to add a new flag to skip loading claims from the ProfileURL, e.g. `--skip-claims-from-profile-url` or something like that. I have implemented a working PoC here https://github.com/oauth2-proxy/oauth2-proxy/compare/master...nilsgstrabo:oauth2-proxy:feature/add-skip-claims-from-profile-url-flag

Obviously it is not production/PR ready. I was a bit confused where to put the new flag. The LegacyOptions sounded a bit like "don't change anything here", but thats where it ended up in the PoC. Hope it is enough to give you an understanding of what I'm trying to accomplish :)

I'll be happy to discuss the issue if you have any questions, or want me to test "things".

Regards,
Nils Gustav

**Comment by ianroberts** [comment]
Or alternatively some kind of option (or default behaviour?) whereby explicitly-configured values - including empty ones - for any of the URLs would override those found by discovery, so you could combine the default discovery with an explicit `profileURL: ""`

**Comment by tuunit** [comment]
> @JoelSpeed First of all, a **BIG** thanks to you and all the other contributors.
> 
> Regarding this issue, and the related #1666. The problem is that the ClaimsProvider will call the ProfileURL (provided manually or by OIDC discovery) with the access token received from the OIDC token endpoint. When the scope defines an API, e.g. `scope: openid 6dae42f8-4368-4678-94ff-3960e28e3630/.default`, the `aud` claim is not valid for the ProfileURL, and the request will fails with status 401. This error will then make oauth2-proxy return a 500 Internal Server Error to the client.
> 
> https://github.com/oauth2-proxy/oauth2-proxy/blob/53cd0b83d3dc455488d24da029f03ee61afbf90c/pkg/providers/util/claim_extractor.go#L98-L105
> 
> I know I can use the work-around and set skipDiscovery: true and all the *URL properties manually, but I would be much better to use OIDC discovery, but skip loading claims from the ProfileURL,
> 
> My suggestion is to add a new flag to skip loading claims from the ProfileURL, e.g. `--skip-claims-from-profile-url` or something like that. I have implemented a working PoC here [master...nilsgstrabo:oauth2-proxy:feature/add-skip-claims-from-profile-url-flag](https://github.com/oauth2-proxy/oauth2-proxy/compare/master...nilsgstrabo:oauth2-proxy:feature/add-skip-claims-from-profile-url-flag)
> 
> Obviously it is not production/PR ready. I was a bit confused where to put the new flag. The LegacyOptions sounded a bit like "don't change anything here", but thats where it ended up in the PoC. Hope it is enough to give you an understanding of what I'm trying to accomplish :)
> 
> I'll be happy to discuss the issue if you have any questions, or want me to test "things".
> 
> Regards, Nils Gustav

Hi @nilsgstrabo,

as the maintainers of the project currently don't have access to an Azure environment. We heavily rely on community support and feedback. Therefore feel free to create a PR with your suggested flag / changes and let's figure out together on how to enhance our Azure support.

**Comment by nilsgstrabo** [comment]
@tuunit 
I have created a PR https://github.com/oauth2-proxy/oauth2-proxy/pull/2329 with an example of a new new option that allows to skip resolving claims from profile URL. It is a very "naive" solution to the issue many are facing, but at least it works.

I have access to Azure, so I'll be happy to do more testing if you want me to.

Not sure where to add tests.

**Comment by andoks** [comment]
@nilsgstrabo: when using the skip_claims_from_profile_url = true configuration (in version v7.6.0) - oauth2-proxy still seems to add on the `https://graph.microsoft.com/.default` in scopes, did your PR #2329  do anything with that? Or what that not part of the change?

**Comment by MarkusDressel** [comment]
@nilsgstrabo  @andoks: I am having the same issue. changing the scope auto injects `https://graph.microsoft.com/.default` which then conflicts to my own scope api://<client-id>/user_impersonation with the error:
`AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope api://<client_id>/user_impersonation https://graph.microsoft.com/.default is not valid. static scope limit exceeded.` 

I have set `skip-claims-from-profile-url`  to true

A
Any recommendations on retrieving an access token with an audience other than Microsoft Graph and custom scopes ?

**Comment by andoks** [comment]
@MarkusDressel: It has been a while, but I think I switched to the OpenID Connect provider and made that work

**Comment by MarkusDressel** [comment]
@andoks are you able to share your OpenID config that worked with Azure ?

**Comment by andoks** [comment]
@MarkusDressel: here it is as docker-compose environment setup with a bunch of links, but you need to configure entra correctly too, which is a whole other story

<details>

<summary>Config</summary>

```yaml
  oauth2-proxy:
    secrets:
      - source: "oauth2-proxy_client_secret"
        target: "client_secret"
    environment:
      ## The OAuth Client ID, Secret
      # client_id = "123456.apps.googleusercontent.com"
      # client_secret = ""
      OAUTH2_PROXY_CLIENT_ID: "${OIDC_CLIENT_ID}"
      OAUTH2_PROXY_CLIENT_SECRET_FILE: "/run/secrets/client_secret"
      # docs also say that azure and azure ad does not support refresh tokens, only OIDC (and some other providers)
      # source: https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#footnote-label
      # offline_access: https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

      # Setup from https://github.com/oauth2-proxy/oauth2-proxy/issues/2314#issuecomment-1803684452
      # Work-around for access-token being for the proxied service, not the MS Graph
      # API, resulting in ms entra returning error as oauth2-proxy adds the
      # "https://graph.microsoft.com/.default" scope to the list of scope it
      # requests, which breaks when we request specific scopes already
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "<entra issuer url>"
      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: false
      OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION: false

      # MS Entra apparently does not set the email_verified claim, as it claims all
      # e-mails are valid by default. If insecure_oidc_allow_unverified_email is not
      # set to true, oauth2-proxy fails logging in the user with the error
      # `[oauthproxy.go:881] Error redeeming code during OAuth2 callback: could not
      # get claim "email_verified": failed to fetch claims from profile URL: error
      # making request to profile URL: unexpected status "401":
      # {"error":{"code":"InvalidAuthenticationToken","message":"Access token
      # validation failure. Invalid
      # audience.","innerError":{...}}}`
      #
      # https://github.com/oauth2-proxy/oauth2-proxy/issues/1680#issuecomment-1310020120
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: true

      # allow redirecting to single sign out
      OAUTH2_PROXY_WHITELIST_DOMAINS: "login.microsoftonline.com"

      ## the OAuth Redirect URL.
      # defaults to the "https://" + requested host header + "/oauth2/callback"
      OAUTH2_PROXY_REDIRECT_URL: "<your apps callback url>"

      ## Email Domains to allow authentication for (this authorizes any email on this domain)
      ## for more granular authorization use `authenticated_emails_file`
      ## To authorize any email addresses use "*"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"

      ## Scopes Added to the request
      ## It has the same behavior as the --scope flag
      ## NB: only need the roles scope if you want roles as part of AT and IdT
      OAUTH2_PROXY_SCOPE: "openid offline_access email profile <api://<your api id here>/roles"

      ## Cookie Settings
      ## Name     - the cookie name
      ## Secret   - the seed string for secure cookies; should be 16, 24, or 32 bytes
      ##            for use with an AES cipher when cookie_refresh or pass_access_token
      ##            is set
      ## Domain   - (optional) cookie domain to force cookies to (ie: .yourcompany.com)
      ## Expire   - (duration) expire timeframe for cookie
      ## Refresh  - (duration) refresh the cookie when duration has elapsed after cookie was initially set.
      ##            Should be less than cookie_expire; set to 0 to disable.
      ##            On refresh, OAuth token is re-validated.
      ##            (ie: 1h means tokens are refreshed on request 1hr+ after it was set)
      ## Secure   - secure cookies are only sent by the browser of a HTTPS connection (recommended)
      ## HttpOnly - httponly cookies are not readable by javascript (recommended)
      #cookie_name = "_oauth2_proxy"
      OAUTH2_PROXY_COOKIE_SECRET: "<cookie secret>"
      #cookie_domains = ""
      OAUTH2_PROXY_COOKIE_EXPIRE: "168h"
      OAUTH2_PROXY_COOKIE_REFRESH: "1h"
```

</details>
