### ISSUE TITLE
OAuth2Proxy token exchange failed x509: unhandled critical extension

### ISSUE THREAD

**Issue by JohnPadgettCivica** [oauth2-proxy/oauth2-proxy#2342]
## Expected Behavior
Use of Oauth2Proxy to initiate  and complete OpenID Authentication flow to access web resources within Kubernetes using NGINX Ingress Controller and custom certificate. 

## Current Behavior
Configure Oauth2proxy to use Keycloak as Open ID connect provider. During authentication flow user logs in but during the token exchange error in logs.

`[2023/12/05 16:01:35] [oauthproxy.go:823] Error redeeming code during OAuth2 callback: token exchange failed: Post "https://keycloak.domain/realms/Ludus_Preprod/protocol/openid-connect/token": x509: unhandled critical extension
`
And the following is observed in the browser.

![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/43237115/fe7c6608-1a10-4ad7-b018-e6e4b8b60062)

The same behaviour is exhibited when using OIDC discovery.
But the error in the log is 
`ERROR: Failed to initialise OAuth2 Proxy: error intiailising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: error performing request: Get "https://keycloak.domain/realms/Ludus_Prod/.well-known/openid-configuration": x509: unhandled critical extension`

The flow works with a self signed certificate that is added to Oauth2proxy during Docker build and placed into the /usr/local/share/ca-certificates/ directory and update-ca-certificates performed and the certificate can be viewed in 
/etc/ssl/certs. 

When updating the certificate to a certificate provided by the client this flow no longer works and errors as above.

## Steps to Reproduce (for bugs)

Using version OAuth2Proxy version v7.40 and Keycloak  22.0.1 my oauth2 deployment yaml configuration is as follows

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .OAUTH_NAME }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: {{ .OAUTH_NAME }}
      service: ludus-oauth2proxy
  template:
    metadata:
      labels:
        name: {{ .OAUTH_NAME }}
        service: ludus-oauth2proxy
    spec:
      containers:
        - name: oauth2-authentication
          image: {{ .OAUTH_IMAGE_URL }}
          imagePullPolicy: Always
          args:
            - "--http-address=0.0.0.0:8080"
            - "--provider-ca-file=/opt/bitnami/oauth2-proxy/certificate.pem"
            #- "--http-address=0.0.0.0:8080"
          env:
            - name: OAUTH2_PROXY_PROVIDER
              value: "oidc"
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: "true"
            - name: OAUTH2_PROXY_COOKIE_REFRESH
              value: "1m"
            - name: OAUTH2_PROXY_COOKIE_EXPIRE
              value: "30m"
            - name: OAUTH2_PROXY_SET_XAUTHREQUEST
              value: "true"
            - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
              value: "true"
            - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
              value: "true"
            - name: OAUTH2_PROXY_PASS_USER_HEADERS
              value: "true"
            - name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
              value: "true"
            - name: OAUTH2_PROXY_CLIENT_ID
              value: fboa-ui
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: oauth2_client_secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: oauth2_cookie_secret
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
            - name: OAUTH2_PROXY_COOKIE_DOMAINS
              value: "preprod.ludus.pnn.police.uk"
            - name: OAUTH2_PROXY_WHITELIST_DOMAINS
              value: "*.preprod.ludus.pnn.police.uk:*"
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: https://keycloak.domain/realms/Ludus_Preprod
            - name: OAUTH2_PROXY_LOGIN_URL
              value: https://keycloak.domain/realms/Ludus_Preprod/protocol/openid-connect/auth
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: https://oauth2.domain/oauth2/callback
            - name: OAUTH2_PROXY_OIDC_JWKS_URL
              value: https://keycloak.domain/realms/Ludus_Preprod/protocol/openid-connect/certs
            - name: OAUTH2_PROXY_REDEEM_URL
              value: https://keycloak.domain/realms/Ludus_Preprod/protocol/openid-connect/token
            #- name: OAUTH2_PROXY_SKIP_OIDC_DISCOVERY
            #  value: "true"
            - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
              value: "S256"
            # - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
            #   value: "true"
            - name: OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR
              value: "true"
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 8080
```

## Context

The flow works when setting OAUTH2_PROXY_SKIP_OIDC_DISCOVERY to true so seems to be some type of certificate issue, any information would be gratefully received. 

## Your Environment
Kubernetes
OAuth2proxy
Keycloak

- Version used:
Kubernetes v1.26
OAuth2Proxy v7.4.0
Keycloak v22.0.1
