### ISSUE TITLE
Dex +  OAuth2_Proxy + Github - Question, help needed

### ISSUE THREAD

**Issue by clickersmudge** [oauth2-proxy/oauth2-proxy#2347]
Hi,
We have a problem probalby with OAuth2_Proxy. 

## We configured Dex
```
dex:
  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: example
      clientSecret: example
      redirectURI: https://example.com/dex/callback
      orgs:
      - name: example-org
```

## We configured  OAuth2_Proxy
```
iap:
  oidc_issuer_url: https://example.com/dex
  replicas: 1
  deployments:
    alertmanager:
      name: alertmanager
      client_id: alertmanager
      client_secret: example
      encryption_key: example
      config:
        scope: "groups openid email"
        email_domains:
          - '*'
        github_org: example-org
        github_team: alertmanager
        skip_auth_regex:
          - '/-/healthy'
      upstream_service: alertmanager.monitoring.svc.cluster.local
      upstream_port: 9093
      ingress:
        host: "alertmanager.example.com"
```

## Problem
For example, when we log into Alertmanager using GitHub, it does not respect the parameters
```
github_org: example-org
github_team: master-alertmanager
```

```
 # see https://github.com/oauth2-proxy/oauth2-proxy/blob/master/docs/configuration/configuration.md
      # this example configures that only users belong to a special GitHub
      # organization can access the service behind the proxy (Prometheus in this case)
      config:
        scope: "groups openid email"
        github_org: mygithuborg
        github_team: mygroup
```

When we log in to GitHub, even though we are not assigned to a team in GitHub, it logs us correctly and we see a Alertmanager panel that we should not have access to.
Can you help?
