### ISSUE TITLE
SSO Issue with OAuth2 Proxy for Angular Frontend and API Gateway

### ISSUE THREAD

**Issue by antoninrichard** [oauth2-proxy/oauth2-proxy#2352]
## Expected Behavior

The authentication for the Angular frontend application should seamlessly apply to the API gateway, allowing authenticated users to fetch data without needing to authenticate again for the API gateway.

## Current Behavior

When a request is made from the Angular client without manually generating a token on the API gateway's URL, it fails to retrieve data. The API route redirects to the authentication form, indicating that the existing client authentication is not recognized by the API gateway.

## Possible Solution

I am looking for a solution where the SSO (Single Sign-On) mechanism can be implemented effectively, so the authentication on the client-side is also valid for API requests, eliminating the need for separate authentication for the API gateway.

## Steps to Reproduce (for bugs)

1. Authenticate on the Angular frontend client.
2. Make a request to the API gateway from the authenticated Angular client.
3. Notice the redirection to the authentication form instead of successful data retrieval.

## Context

This issue has been a significant blocker in achieving a seamless SSO experience for our users. I have been struggling with this for weeks and am close to giving up. My goal is to have a single authentication process that covers both the Angular frontend and the API gateway.

## Your Environment

oAuth2 Deployement file: 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: XXXXXX
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        args:
#Configuration OIDC Azure 
        - --provider=azure
        - --azure-tenant=XXXXXXXXXXXXXXXXXXXXXXXX
        - --email-domain=*
        - --oidc-issuer-url=https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXXXXX/v2.0
        - --skip-provider-button=true
#Configuration applicative  
        - --whitelist-domain="*.XXXXXXXX.fr" 
        - --http-address=0.0.0.0:4180
        - --upstream=file:///dev/null
#Configuration du cookie
        - --cookie-domain="XXXXXXXXX.fr"
        - --cookie-secure=true
        - --cookie-samesite=none
        - --cookie-refresh=5m
#Configuration des headers
        - --pass-basic-auth=true
        - --pass-user-headers=true
        - --set-authorization-header=true
        - --pass-authorization-header=true 
        - --set-xauthrequest=true
        - --pass-access-token=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secrets
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secrets
              key: OAUTH2_PROXY_CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secrets
              key: OAUTH2_PROXY_COOKIE_SECRET
        ports:
        - containerPort: 4180
          protocol: TCP
```

oAuth2 Ingress file:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-ingress
  namespace: XXXXXXXXX
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
spec:
  ingressClassName: nginx
  rules:
  - host: oauth-proxy.XXXXXXXX.fr
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 1200
  tls:
  - hosts:
    - oauth-proxy.XXXXXXXX.fr
    secretName: XXXXXXXXXXX
```

Angular app Ingress : 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: XXXXXXXXXX
  namespace: XXXXXXXXXXXXXX
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # cache > noflood
    nginx.ingress.kubernetes.io/auth-cache-key: "$cookie__oauth2_proxy"
    nginx.ingress.kubernetes.io/auth-cache-duration: '200 202 10m'
    #
    nginx.ingress.kubernetes.io/auth-url: "https://oauth-proxy.XXXXXX.fr/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth-proxy.XXXXXXXXXX.fr/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
    #
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - XXXXXXX.XXXXXXXXXXXX.fr
    secretName: XXXXXXXXXXXXX
  rules:
  - host: XXXXXXXXXXXXXXXX
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: XXXXXXXXXXXX
              port:
                number: 80

```

Api gateway ingress file : 
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: XXXXXXXXXXXXXXX
  namespace: XXXXXXXXXXXXXXXXXX
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # cache > noflood
    nginx.ingress.kubernetes.io/auth-cache-key: "$cookie__oauth2_proxy"
    nginx.ingress.kubernetes.io/auth-cache-duration: '200 202 10m'
    #
    nginx.ingress.kubernetes.io/auth-url: "https://oauth-proxy.XXXXXXXXXXX.fr/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth-proxy.XXXXXXXXXXX.fr/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
    #
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - XXXXXXXXXXX.XXXXXXXXXX.fr
    secretName: XXXXXXXXX
  rules:
  - host:XXXXXXXXXXXXXX.XXXXXXXXXXXXX.fr
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: XXXXXXXXXXX
              port:
                number: 80
```

I'm new to Kubernetes and microservice architecture. Thanks for your help and forgiveness if I've made any glaring mistakes.
