### ISSUE TITLE
Variabilize redirect URI

### ISSUE THREAD

**Issue by rgarrigue** [oauth2-proxy/oauth2-proxy#2361]
I'd like to provide OAuth2 for some websites in my org that doesn't have it. Let's say code generated documentations for the example. 

I got everything set up so I've doc1.company.tld and doc2.company.tld, opening them show me the OAuth2-Proxy login "Sign in with Google", I hit the button, and Google error

```
Error 400 : invalid_request
...
redirect_uri=https://$host/oauth2/callback 
```

Is there a way for $host to work, or anything that'll adjust the redirect-url depending on the website ?  

Here's my conf

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: oauth2-proxy
  name: nginx-config
data:
  nginx.conf: |-
    events {}
    http {
      server {
        listen 80;
        server_name _;
        server_tokens off;
        location / {
          proxy_pass http://oauth2-proxy;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources: {}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - configMap:
            name: nginx-config
          name: conf

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  name: nginx
  namespace: oauth2-proxy
spec:
  ingressClassName: contour
  rules:
  - host: doc1.website.tld
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
  - host: doc2.wesite.tld
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
  tls:
  - hosts:
    - doc1.website.tld
    - doc2.wesite.tld
    secretName: nginx-tls
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: oauth2-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          resources: {}
          args:
            - "--http-address=0.0.0.0:4180"
            - "--provider=google"
            - "--email-domain=company.com"
            - "--upstream=http://nginx"
            - "--redirect-url=https://$host/oauth2/callback"
          envFrom:
            - secretRef:
                name: oauth2-proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
# kubectl create secret generic -n oauth2-proxy oauth2-proxy --from-literal=OAUTH2_PROXY_CLIENT_ID='737XXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com' --from-literal=OAUTH2_PROXY_CLIENT_SECRET='GOCSPX-XXXXXXXXXXXXXXXXXXXXXXXXXXX' --from-literal=OAUTH2_PROXY_COOKIE_SECRET=$(openssl rand -base64 32 | tr -- '+/' '-_') --dry-run=client -o yaml | kubeseal -f /dev/stdin -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  encryptedData:
    OAUTH2_PROXY_CLIENT_ID: AgCsnUXXXXXXXXXXXXXXXXXXXXXXXXXXXDvLYVUe9kmqJz03ofDHFki5n6gb9cHSK5yqAsqZkz7eToL7MQCBJPjw=
    OAUTH2_PROXY_CLIENT_SECRET: AgB3BdFXXXXXXXXXXXXTDaM64XXXXXXXXgGLx008e9cIIl+laeEeg==
    OAUTH2_PROXY_COOKIE_SECRET: AgBQNrEMXXXXXXXXXXXXXXXXXXXXXXXXXXXxDuBWQMO30eLDKqTahQ3sLScIw==
  template:
    metadata:
      creationTimestamp: null
      name: oauth2-proxy
      namespace: oauth2-proxy

---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: 4180
  selector:
    app: oauth2-proxy
```
