### ISSUE TITLE
Problem running with Keycloak in docker-compose.yml

### ISSUE THREAD

**Issue by ianpurton** [oauth2-proxy/oauth2-proxy#2365]
I'm running the following `docker-compose.yml`

```yml

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy-keycloak.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    ports:
      - 4180:4180/tcp
    depends_on:
      - keycloak

  postgres:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword

  keycloak:
    build:
      context: ./keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: testpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    command:
      - "start-dev"
      - "--import-realm"
      - "--http-port=28080"
      - "--hostname=localhost"
    ports:
      - "28080:28080"
    depends_on:
      - postgres
```

The `oath2-proxy-keycloak.cfg` looks like

```
http_address="0.0.0.0:4180"
cookie_secret="OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
email_domains="example.com"
cookie_secure="false"
upstreams="http://upstream"
# keycloak provider
client_secret="69b26b08-12fe-48a2-85f0-6ab223f45777"
client_id="bionic-gpt"
redirect_url="http://localhost:4180/oauth2/callback"

# in this case oauth2-proxy is going to visit
# http://keycloak:8080/realms/bionic-gpt/.well-known/openid-configuration for configuration
oidc_issuer_url="http://keycloak:28080/realms/bionic-gpt"
insecure_oidc_skip_issuer_verification="true"
insecure_oidc_allow_unverified_email="true"
insecure_oidc_skip_nonce="true"
provider="oidc"
provider_display_name="Keycloak"
```

And the `realm.json` for keycloak

```
{
    "realm": "bionic-gpt",
    "registrationAllowed": true,
    "registrationEmailAsUsername": true,
    "enabled": "true",
    "sslRequired": "none",
    "clients": [
        {
            "clientId": "bionic-gpt",
            "clientAuthenticatorType": "client-secret",
            "secret": "69b26b08-12fe-48a2-85f0-6ab223f45777",
            "redirectUris": [
                "http://*"
            ],
            "protocol": "openid-connect"
        }
    ]
}
```

The logs look like the following after a failed login.

```
oauth2-proxy    | [2023/12/23 09:45:28] [providers.go:145] Warning: Your provider supports PKCE methods ["plain" "S256"], but you have not enabled one with --code-challenge-method
oauth2-proxy    | [2023/12/23 09:45:28] [proxy.go:89] mapping path "/" => upstream "http://upstream"
oauth2-proxy    | [2023/12/23 09:45:28] [oauthproxy.go:166] OAuthProxy configured for OpenID Connect Client ID: bionic-gpt
oauth2-proxy    | [2023/12/23 09:45:28] [oauthproxy.go:172] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
oauth2-proxy    | [2023/12/23 09:45:49] [oauthproxy.go:970] No valid authentication in request. Initiating login.
oauth2-proxy    | 172.30.0.1:55564 - 89584ddd-62f2-48cb-b6ab-773f619c70a7 - - [2023/12/23 09:45:49] localhost:4180 GET - "/" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" 403 8560 0.001
oauth2-proxy    | 172.30.0.1:55564 - 2522e036-75b6-4c67-b1e7-d67ec7475b8a - - [2023/12/23 09:45:49] localhost:4180 GET - "/oauth2/static/css/bulma.min.css" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" 200 207302 0.000
oauth2-proxy    | 172.30.0.1:55564 - df4013a4-0666-4993-a185-6754d0c0f8e7 - - [2023/12/23 09:45:53] localhost:4180 GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" 302 320 0.000
oauth2-proxy    | 172.30.0.1:55564 - 918a37db-6438-46a2-a6f5-161cb87c6261 - i[redacted]@gmail.com [2023/12/23 09:45:56] [AuthFailure] Invalid authentication via OAuth2: unauthorized
oauth2-proxy    | 172.30.0.1:55564 - 918a37db-6438-46a2-a6f5-161cb87c6261 - - [2023/12/23 09:45:56] localhost:4180 GET - "/oauth2/callback?state=CIiYNm2cqDggHa0nYB0rgjNxr44R9OFZGXopR0clu0A%3A%2F&session_state=c96ff13d-59a7-44e0-9d24-2ce2def8bed5&iss=http%3A%2F%2Flocalhost%3A28080%2Frealms%2Fbionic-gpt&code=0c96fee6-47e3-4a78-849d-f8be7cff995c.c96ff13d-59a7-44e0-9d24-2ce2def8bed5.6d02caea-e877-447f-aaa0-507634e0ab92" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" 403 2715 0.111
oauth2-proxy    | 172.30.0.1:55564 - f92f0daa-3b55-4157-87f9-ea55d5f6e8a5 - - [2023/12/23 09:45:56] localhost:4180 GET - "/oauth2/static/css/bulma.min.css" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" 200 207302 0.000
oauth2-proxy    | 172.30.0.1:49614 - ac642940-18d0-4c5a-882a-aa5fc8f1a1ea - - [2023/12/23 09:45:56] localhost:4180 GET - "/oauth2/static/css/all.min.css" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" 200 102025 0.000
oauth2-proxy    | 172.30.0.1:49614 - 30c4e699-edc3-4d8c-a6d7-4b0ea54014b4 - - [2023/12/23 09:45:56] localhost:4180 GET - "/oauth2/static/webfonts/fa-solid-900.woff2" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" 200 149908 0.000
```

I'm logging in from the browser with the URL `http://localhost:4180`

I get a 403 forbidden.

From the logs

```
oauth2-proxy    | 172.30.0.1:55564 - 918a37db-6438-46a2-a6f5-161cb87c6261 - i[redacted]@gmail.com [2023/12/23 09:45:56] [AuthFailure] Invalid authentication via OAuth2: unauthorized
```

I guess it's something to do with that I'm using localhost, but can't figure out what the issue is.
