### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by flashpaper12** [oauth2-proxy/oauth2-proxy#2379]
## Expected Behavior

When deploying oauth2proxy as a container inside kubernetes, it goes into a crashback loop

## Current Behavior

logs from container before crashing
```
[2024/01/09 05:12:50] [main.go:75] WARNING: You are using alpha configuration. The structure in this configuration file may change without notice. You MUST remove conflicting options from your existing configuration.
[2024/01/09 05:12:50] [main.go:43] ERROR: failed to load core options: failed to load config: error unmarshalling config: 1 error(s) decoding:

* '' has invalid keys: upstreams
```

## Possible Solution

Maybe something is wrong with my alpha config?

```
        server:
            BindAddress: '0.0.0.0:4180'
        metricsServer:
            BindAddress: '0.0.0.0:44180'
        providers:
          - clientID: **redacted**
            clientSecret: **redacted**
            id: oidc-auth0-istio
            provider: oidc
            scope: **redacted**
            code_challenge_method: S256
            oidcConfig:
                issuerURL: **redacted**
                jwksURL: **redacted**
                emailClaim: email
                groupsClaim: groups
                userIDClaim: email
                audienceClaims:
                    - aud
        injectResponseHeaders:
          - name: Authorization
            values:
              - claim: id_token
                prefix: "Bearer "
        upstreamConfig:
          upstreams:
            - id: static_200
              path: /
              static: true
              staticCode: 200
```

## Your Environment

- Version used: 7.5.0
