### ISSUE TITLE
Could someone help to configure Oauth2-proxy with Zitadel ? error "Unauthorized"

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [oauth2-proxy/oauth2-proxy#2380]
Trying to make Oauth2-proxy to work with Zitadel, can't find the right settings.

## Expected Behavior

Hi,
I am looking to get Oauth2-proxy to work with Zitadel, while trying to keep the configuration as simple as possible. I am using Caddy as my reverse proxy and I would like to use `forward_auth` from Caddy to delegate the auth to oauth2-proxy and zitadel, instead of proxying the whole traffic. I'm trying to secure Radarr under it, to begin with.

In Zitadel, I've created an app for Radarr, setting PKCE code challenge as Oauth2-proxy should support it.

My caddyfile is the following:
```
radarr.example.com {
        @except not path /api*
        reverse_proxy radarr:7878
        reverse_proxy /oauth2/* oauth2-radarr:4180
        forward_auth @except oauth2-radarr:4180 {
                copy_headers Authorization
                uri /oauth2/auth
        }
}
```

My Oauth2-proxy config is the following:
(I am using env variables)
```
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_REDIRECT_URL=https://radarr.${DOMAIN}/oauth2/callback
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://auth.${DOMAIN}
      - OAUTH2_PROXY_WHITELIST_DOMAIN=.${DOMAIN}
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_CLIENT_ID=${RADARR_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=sdgdhfd #For an unknown reason, Oauth2-proxy still wants a client_secret even when using PKCE where it won't be useful
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      - OAUTH2_PROXY_SCOPE="openid profile email groups"
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
```

With this setup, when trying to access Radarr, I have an error "Unauthorized". I don't know more about what the problem could be. 

I think the Caddy configuration is correct, because it is very close to what Authentik is doing to forward_auth to its own integrated proxy, confirmed by this post https://caddy.community/t/replicating-nginx-auth-request/22118/5

So I think it comes from the Oauth2-proxy configuration. But I couldn't find anyone using Oauth2-proxy with Zitadel, or Oauth2-proxy with forward_auth. So I'm looking for help to know what setting I could be missing.

Thanks in advance for any answer and have a great day.

## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by tuunit** [comment]
1. Which version are you using?
2. How do you deploy oauth2-proxy?
3. Please share your oauth2-proxy logs

**Comment by LeVraiRoiDHyrule** [comment]
> 1. Which version are you using?
> 
>     2. How do you deploy oauth2-proxy?
> 
>     3. Please share your oauth2-proxy logs

Hi, thanks a lot for your answer.

1. It is the version 7.5.1

2. I am deploying oauth2-proxy in docker-compose. My service is deployed this way:

```
  oauth2-radarr:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    platform: ${PLATFORM}
    container_name: oauth2-radarr
    networks:
      - services6
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_REDIRECT_URL=https://radarr.${DOMAIN}/oauth2/callback
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://auth.${DOMAIN}
      - OAUTH2_PROXY_WHITELIST_DOMAIN=.${DOMAIN}
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR=true
      - OAUTH2_PROXY_CLIENT_ID=${RADARR_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=dummy #${RADARR_CLIENT_SECRET}
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      #- OAUTH2_PROXY_OIDC_GROUPS_CLAIM=groups
      #- OAUTH2_PROXY_SCOPE="openid profile email groups"
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
 ```

3. My logs are the following:
```
[2024/01/10 21:56:17] [provider.go:55] Performing OIDC Discovery...

[2024/01/10 21:56:17] [oauthproxy.go:166] OAuthProxy configured for OpenID Connect Client ID: 248881322301390850@saladserver

[2024/01/10 21:56:17] [oauthproxy.go:172] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled

172.24.0.100 - 9bfdf543-d1d4-4a09-a207-08b603b72c43 - - [2024/01/10 21:59:33] radarr.saladcesar.fr GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0" 401 13 0.000

172.24.0.100 - ecc5e479-e490-49f9-8e25-5b25599a8458 - - [2024/01/10 22:20:43] radarr.saladcesar.fr GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0" 401 13 0.000

172.24.0.100 - 2b5d4046-d37e-4557-b997-63286cdc4ae0 - - [2024/01/10 22:20:43] radarr.saladcesar.fr GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0" 401 13 0.000
```
