### ISSUE TITLE
[Support]: Istio not receiving Auth headers from oauth2-proxy when running Alpha config

### ISSUE THREAD

**Issue by josh-thisisbud** [oauth2-proxy/oauth2-proxy#2463]
### OAuth2-Proxy Version

7.5.1

### Provider

oidc

### Current Behaviour of your Problem

- Oauth2 Proxy correctly authenticates with Keycloak
- Oauth2-proxy returns 302 redirect to / with the set-cookie headers
- No authentication header is returned and as response is not 200 or 202 istio can't seem to tell that auth was approved

### Configuration details or additional information

Intended authentication configuration diagram:
![image](https://github.com/oauth2-proxy/oauth2-proxy/assets/104507068/cb114617-394c-4eca-b21f-59e2c3c1aead)

Old Configuration Options:
```yaml
          configFile: |-
            cookie_httponly = true
            cookie_refresh = "1h"
            cookie_samesite = "lax"
            cookie_secure = true
            email_domains = [ "{{ .Values.configmap.email_domain }}" ]
            request_logging = true
            reverse_proxy = true
            show_debug_on_error = true
            errors_to_info_log = true
            silence_ping_logging = true
            skip_provider_button = true
            ssl_insecure_skip_verify = true
            auth_logging = true
            standard_logging = true
            cookie_domains = [ ".{{ $.Values.global.tld }}" ]
            whitelist_domains = [ ".{{ $.Values.global.tld }}" ]
```

Alpha Configuration Options:
```yaml
"injectResponseHeaders":
- "name": "Authorization"
  "values":
  - "claim": "access_token"
    "prefix": "Bearer "
- "name": "X-Auth-Request-Preferred-Username"
  "values":
  - "claim": "preferred_username"
- "name": "X-Auth-Request-Email"
  "values":
  - "claim": "email"
- "name": "kubeflow-groups"
  "values":
  - "claim": "groups"
- "name": "kubeflow-userid"
  "values":
  - "claim": "email"
"providers":
- "clientID": "oauth2-proxy"
  "clientSecret": "<redacted>"
  "id": "oidc"
  "loginURL": "https://keycloak.<redacted>/auth/realms/<redacted>/protocol/openid-connect/auth"
  "name": "oidc"
  "oidcConfig":
    "audienceClaims":
    - "aud"
    "emailClaim": "email"
    "groupsClaim": "groups"
    "insecureAllowUnverifiedEmail": true
    "issuerURL": "https://keycloak.<redacted>/auth/realms/<redacted>"
    "jwksURL": "https://keycloak.<redacted>/auth/realms/<redacted>/protocol/openid-connect/certs"
    "userIDClaim": "email"
  "profileURL": "https://keycloak.<redacted>/auth/realms/<redacted>/protocol/openid-connect/userinfo"
  "provider": "oidc"
  "redeemURL": "https://keycloak.<redacted>/auth/realms/<redacted>/protocol/openid-connect/token"
  "scope": "openid email profile groups"
  "validateURL": "https://keycloak.<redacted>/auth/realms/<redacted>/protocol/openid-connect/userinfo"
"server":
  "BindAddress": "0.0.0.0:4180"
"upstreamConfig":
  "upstreams":
  - "id": "static_200"
    "path": "^/auth"
    "static": true
    "staticCode": 200
```
