### ISSUE TITLE
[Support]: Unable to authorize applications with keycloak via oauth2 proxy using Bearer token

### ISSUE THREAD

**Issue by gargimehendale** [oauth2-proxy/oauth2-proxy#2484]
### OAuth2-Proxy Version

v7.5.1

### Provider

keycloak

### Current Behaviour of your Problem

I am trying to integrate keycloak with the kubernetes applications using oauth2 proxy. The use case is to authorize applications and API calls using keycloak with browser login/Bearer token. I have an example application, oauth2 proxy and keycloak running in the same namespace of kubernetes cluster. All the 3 applications are behind nginx-ingress. 

Currently I am able to authorize the application using the keycloak browser login, but facing issue while authenticating it using curl request or with postman.

### Endpoints:
- example-app: https://app.microservices.com/demo-service
- keycloak: https://keycloak.microservices.com
- oauth2 proxy: https://app.microservices.com/oauth2

### Current Behavior:
When I try to access "https://app.microservices.com/demo-service" endpoint, I am able to login with the browser using user credentials, but when I try to make a curl request from the CLI it gives me a "302" error.

### Expected behavior:
It should authorize the request using Bearer token and give me the output from example app.

### What I tried:
- Tried making curl request using `-H "Authorization Bearer TOKEN"`. It returns `302` redirect error
- Tried adding `-H 'Accept: application/json'`. Returns the same 302 error.
- Tried making request from postman but it returns `200 OK` with html code for keycloak sign in page. 
- I tried changing parameters in oauth2 configmap.

### Parameters in oauth2 config map:
```
oauth2-proxy.cfg: |-
    provider="keycloak"
    provider_display_name="Keycloak"
    login_url="https://<DOMAIN>/realms/test/protocol/openid-connect/auth"
    redeem_url="https://<DOMAIN>/realms/test/protocol/openid-connect/token"
    validate_url="https://<DOMAIN>/realms/test/protocol/openid-connect/userinfo"
    profile_url="https://<DOMAIN>/realms/test/protocol/openid-connect/userinfo"
    skip_jwt_bearer_tokens="true"
    pass_authorization_header = "true"
    pass_access_token = "true"
    pass_user_headers = "true"
    pass_basic_auth= "true"
    set_authorization_header = "true"
    set_xauthrequest = "true"
    cookie_refresh = "1m"
    cookie_expire = "30m"
    request_logging="true"
    auth_logging="true"
    standard_logging="true"
    client_id="CLIENT_ID"
    client_secret="xyz"
    cookie_secret="xyz"
    cookie_secure="true"
    # Upstream config
    http_address="0.0.0.0:4180"
    upstreams="file:///dev/null"
    email_domains=["*"]
    oidc_issuer_url="https://<DOMAIN>/realms/nginx-plus"
    cookie_domains=["*"]
    scope="openid"
    whitelist_domains=["*"]
```

### Logs from oauth2-proxy pod:
```
[jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, not implemented]                                                    
oauth-proxy.keycloak.svc.cluster.local GET - "/oauth2/auth" HTTP/1.1 "PostmanRuntime/7.28.4" 401 13 0.000
app.microservices.com GET - "/oauth2/start?rd=%2Fdemo-service" HTTP/1.1 "PostmanRuntime/7.28.4"
 ```

### example-app ingress annotations:

```
metadata:
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
        nginx.ingress.kubernetes.io/auth-signin: http://$host/oauth2/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-url: http://oauth-proxy.keycloak.svc.cluster.local:4180/oauth2/auth
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
```
