### ISSUE TITLE
[Bug]: Regression in alpha config upstreams with regex (+rewrite target)

### ISSUE THREAD

**Issue by roderik** [oauth2-proxy/oauth2-proxy#2508]
### OAuth2-Proxy Version

7.6.0

### Provider

google

### Expected Behaviour

In 7.5.1 we were running the following upstreamConfig

```
      upstreamConfig:
        upstreams:
          - id: app
            path: ^/(.*)$
            rewriteTarget: /$1
            proxyWebSockets: true
            uri: http://app:3000
          - id: api
            path: ^/api(/stripe/webhook|/graphql|/downloads)(.*)$
            rewriteTarget: /api$1$2
            proxyWebSockets: true
            uri: http://api:5555
```

Where all our requests went to the app except a few prefixed by /api/graphql for example.

### Current Behaviour

Upgrading to 7.6.0, this no longer works. All requests to the app end up returning the html served on / (in our example the base html from NextJS, but all js/css/etc also returns that base html) In a similar fashion, all things accessing the api component return the /api endpoint on the /api route.

I've tried with httpbin to see if is was on our side, but also here it can only serve / and not any other routes.

The output in the logs is the same as in 7.5.1

![CleanShot 2024-02-15 at 11 27 44@2x](https://github.com/oauth2-proxy/oauth2-proxy/assets/16780/c44778ee-80a5-4737-9e9a-05f66fff091f)

In this screenshot both / and /spec.js return the contents of /

I saw some more logger calls in the go code but i'm unsure on how to get these printed out.

- Changing the container version to 7.5.1 and all works again as it should
- the -alpine container of 7.6.0 has the same issue, so it is not the image itself
- I've scanned all commits that went into 7.6.0 but cannot find any change that is related, my guess is that it might have been one of the dependency updates

### Steps To Reproduce

1. helm install the 7.5.1 version
2. configure the upstreams like above
3. WORKS
4. upgrade the helm chart (image goes to 7.6.0
5. ERROR
6. change just the image version of the deployment to 7.5.1
7. WORKS

**Comment by sled** [comment]
having the same problem with:

```
          upstreams:
            - id: web
              path: ^/(.*)$
              rewriteTarget: /$1
              uri: http://kubernetes-dashboard-web:8000/
            - id: api
              path: ^/api/(.*)$
              rewriteTarget: /api/$1
              uri: http://kubernetes-dashboard-api:9000/
```

This works as expected in 7.5.1 but in 7.6.0 I get a 404 not found

**Comment by dashkan** [comment]
I encountered the same issue and discovered that it stems from the use of the envsubst package, which requires escaping the dollar sign $ with a double dollar sign $$.

For reference, you can see the relevant code here: [oauth2-proxy implementation](https://github.com/oauth2-proxy/oauth2-proxy/blob/e3dc927e570700ae598425344cf07073965bd19c/pkg/apis/options/load.go#L170).

It's important to clarify that the solution provided below is a workaround and not a permanent fix. The underlying issue with the envsubst package remains, and this approach simply allows us to bypass the problem temporarily.
To address this in the context mentioned by @sled, the workaround would involve modifying the configuration as follows:

```yaml
upstreams:
  - id: web
    path: ^/(.*)$$
    rewriteTarget: /$$1
    uri: http://kubernetes-dashboard-web:8000/
  - id: api
    path: ^/api/(.*)$$
    rewriteTarget: /api/$$1
    uri: http://kubernetes-dashboard-api:9000/
```

This ensures that the $ symbols are properly escaped, allowing for the correct interpretation of the YAML configuration.
