### ISSUE TITLE
[Support]: Return 401 if Bearer token is not valid

### ISSUE THREAD

**Issue by tasiorek27** [oauth2-proxy/oauth2-proxy#2512]
### OAuth2-Proxy Version

7.5.1

### Provider

oidc

### Current Behaviour of your Problem

Please find below my current oauth2-proxy and nginx ingress config:

```
oauth2-proxy:
  proxyVarsAsSecrets: false
  extraArgs:
    upstream: http://backend:3000/api/
    redirect-url: https://dev2.foobar.com/oauth2/callback
    oidc-issuer-url: https://idp.foobar.com/auth/realms/kums
    email-domain: '*'
    cookie-secure: 'true'
    cookie-httponly: 'true'
    skip-provider-button: true
    provider: oidc
    insecure-oidc-allow-unverified-email: true
    ssl-insecure-skip-verify: true
    show-debug-on-error: true
    set-xauthrequest: true
    cookie-refresh: '1h'
    silence-ping-logging: true
    pass-authorization-header: true
    set-authorization-header: true
    force-json-errors: true
    skip-jwt-bearer-tokens: true
    oidc-email-claim: sub
    whitelist-domain: dev2.foobar.com

  extraVolumeMounts:
    - name: oaut2-proxy-secret
      mountPath: "/mnt/secrets-store"
      readOnly: true
  extraVolumes:
    - name: oaut2-proxy-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: oaut2-proxy-secret-provider
```

- nginx
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-body-size: 8M
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1M
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization,X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Groups
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.ingressApp.prefix }}{{ .Values.ingressApp.domain }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.ingressApp.prefix }}{{ .Values.ingressApp.domain }}/oauth2/start"
    # >>> not sure if needed
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   auth_request_set $name_upstream_1 $upstream_cookie_cmt_auth;
    # <<<
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingressApp.prefix }}{{ .Values.ingressApp.domain }}
      secretName: {{ .Values.ingressApp.certificate }}
  rules:
    - host: {{ .Values.ingressApp.prefix }}{{ .Values.ingressApp.domain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
```

### Configuration details or additional information

Hello,

I'd like to implement two scenarios with oauth2-proxy and nginx ingress controller on AKS.
1. It should be possible to log in via a browser for users. It works fine.
2. It should be possible to hit API directly with `Bearer token` set in header. I can't make it quite working. See details below.

When I'm using the correct Bearer token I get successful response from API:
`10.20.0.4 - - [19/Feb/2024:08:22:55 +0000] "GET /oauth2/auth HTTP/1.1" 202 0 "-" "PostmanRuntime/7.36.3" 4000 0.001 [utils-oauth2-proxy-80] [] 10.20.0.73:4180 0 0.002 202 cea36f01cb744adb93e0dc8ce8e7afcb
89.64.111.10 - - [19/Feb/2024:08:22:55 +0000] "GET /api/foo/as?page=0 HTTP/1.1" 200 325 "-" "PostmanRuntime/7.36.3" 3724 0.030 [apps-backend-3000] [] 10.20.0.141:3000 325 0.018 400 cea36f01cb744adb93e0dc8ce8e7afcb`

However, when I remove the token or send invalid one, it always redirects the request to OIDC for normal sign in flow as when it comes to browser user.

`10.20.0.120 - - [19/Feb/2024:12:25:52 +0000] "GET /oauth2/auth HTTP/1.1" 401 13 "-" "PostmanRuntime/7.36.3" 741 0.002 [utils-oauth2-proxy-80] [] 10.20.0.73:4180 13 0.002 401 a1623ca5ef6b140a2e26b1374291ff02
89.64.111.10 - - [19/Feb/2024:12:25:52 +0000] "GET /api/foo/as?page=0 HTTP/1.1" 302 138 "-" "PostmanRuntime/7.36.3" 465 0.008 [apps-backend-3000] [] - - - - a1623ca5ef6b140a2e26b1374291ff02
89.64.111.10 - - [19/Feb/2024:12:25:52 +0000] "GET /oauth2/start?rd=https://dev2.foobar.com%2Fapi%2Ffoo%2Fas%3Fpage%3D0 HTTP/1.1" 302 436 "https://dev2.foobar.com/api/foo/as?page=0" "PostmanRuntime/7.36.3" 593 0.002 [utils-oauth2-proxy-80] [] 10.20.0.73:4180 436 0.002 302 d4876509d6514f1d5a9b0a8159d27ea8`

Question: Is is possible to tweak the configuration in the way it would return `401` to the user if the token is invalid?

Regads,
M
