### ISSUE TITLE
[Support]: injectRequestHeaders with nested claims

### ISSUE THREAD

**Issue by segaura** [oauth2-proxy/oauth2-proxy#2519]
### OAuth2-Proxy Version

v7.5.1

### Provider

oidc

### Current Behaviour of your Problem

I am using `injectRequestHeaders `with Alpha Config.
It works flawlessy like this

```
injectRequestHeaders:
- name: my-header
  values:
  - claim: my_first_level_claim
```

along with JWT where `my_first_level_claim `is in the first level along `iss`, aud, `etc`.

```
{
 "iss": https://loginid...,
  ...
 "exp": 1707411294,
 "my_first_level_claim": value_to_inject_in_header
}
```

but now I need to pick up the value from a nested claim

```
{
 "iss": https://loginid...,
  ...
 "exp": 1707411294,
 "additional_claims": [
   "my_nested_claim": value_to_inject_in_header
 ]
}
```

is this already possible with current oauth2-proxy version?
Can you help me with the syntax?
If not possible in current version, I am still interested in "defining" a feasible yaml syntax to represente nested claims, so I can open an issue/PR on github.

P.S. looking at `injectRequestHeaders `related tests in `oauthproxy_test.go` I understand none of them is using nested claims, currently

### Configuration details or additional information

I am using different Identity Providers but one of them forces us to have a nested claim in particular scenario and it is Novell Access Manager.

With my little knowledge of YAML my best guess is that this one is a possible syntax

```
injectRequestHeaders:
- name: my-header
  values:
  - claim:
    additional_claims:
    - my_nested_claim
```
