### ISSUE TITLE
[Bug]: No longer working on Kubernetes after upgrading from 7.5.1 to 7.6.0

### ISSUE THREAD

**Issue by David-Igou** [oauth2-proxy/oauth2-proxy#2522]
### OAuth2-Proxy Version

7.6.0

### Provider

github

### Expected Behaviour

In previous version (verified by a quick rollback) oauth2-proxy worked for kubernetes ingress auth

config:

```
  oauth2_proxy.cfg: |-
    email_domains = "*"
    provider = "github"
    github_org = "myorg"
    github_team = "k8s"
    scope = "user:email"
```

ingress annotations

```
annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.domain.io/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://oauth.domain.io/oauth2/auth
```

### Current Behaviour

Now oauth2-proxy throws a 500 error when I attempt to sign in, outputting the following in the pod logs:

```
[2024/02/22 21:37:49] [oauthproxy.go:888] Error creating session during OAuth2 callback: unexpected status "403": {"message":"You need at least read:org scope or user scope to list your organizations.","documentation_url":"https://docs.github.com/rest/orgs/orgs#list-organizations-for-the-authenticated-user"}
```

### Steps To Reproduce

deploy latest version of oauth2-proxy, configure github auth, attempt to signin

### Possible Solutions

I'm assuming the oauth2-proxy is attempting to do something it doesn't previously and the account doesn't have scoped permissions
