### ISSUE TITLE
[Support]: show login screen instead of automatically redirecting to oAuth provider

### ISSUE THREAD

**Issue by gangadharjannu** [oauth2-proxy/oauth2-proxy#2575]
### OAuth2-Proxy Version

7.6.0

### Provider

github

### Current Behaviour of your Problem

Current behavior is, application is directly redirecting to github auth page instead of showing sign in page where we will have an option to either login with Github (configured provider) or other authentication mechanisms like htpasswd file.

I configured oauth2 proxy with both GitHub and htpasswd file but oauth2 proxy is directly redirecting me to GitHub auth page instead of showing a sign in page which shows multiple configured options.

### Configuration details or additional information

Helm char version: oauth2-proxy-7.1.0

helm values.yaml configuration

```
config:
  clientID: __CLIENT_ID__
  clientSecret: __CLIENT_SECRET__
  cookieSecret: Jxq+gy/d/YUQhQGuhZ91UA==
  scope: "user:email read:org"
  configFile: |-
    email_domains = "*"
    provider = "github"
    upstreams = [ "file:///dev/null" ]
    http_address = "0.0.0.0:4180"

htpasswdFile:
  enabled: true
  entries:
    - user1:$2y$05$QWnusfnIVRVkRwIDKe9FnOjCsw/dB.lSm8lyg/xRL2Do2zf1bW9s6

ingress:
  enabled: true
  className: nginx
  path: /oauth2
  pathType: ImplementationSpecific
  hosts:
    - fe.localho.st

```

### Steps To Reproduce

I have helm, and local kubernetes cluster with rancher desktop.

Execute below commands to install oauth2 proxy

```
helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
helm upgrade --install -f kubernetes/oauth2-proxy/oauth2-proxy-values.yaml oauth2-proxy oauth2-proxy/oauth2-proxy
```

Then run below ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
  name: frontend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: fe.localho.st
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  name: fe-service-port
```

which exposes a normal angular/react nginx deployment
