### ISSUE TITLE
"403: You do not have permission to access this resource." but only for some users

### ISSUE THREAD

**Issue by theodotos** [oauth2-proxy/oauth2-proxy#2602]
### OAuth2-Proxy Version

7.6.0

### Provider

keycloak-oidc

### Current Behaviour of your Problem

Some users get "403: You do not have permission to access this resource."

### Configuration details or additional information

I have two users. auth.tester-ext and auth.tester2-ext. They are both new keycloak users (auth-tester-ext was deleted and re-created with different ID and different email). Both authenticate to the external realm but auth.tester2-ext gets a 403 from oauth2_proxy. I went through both users settings and I can't spot a difference between their profiles. They both are members the same group and roles.

### Steps To Reproduce

This is probably not the easiest issue to reproduce but here's the keycloak and oauth2_proxy settings:

docker-compose.yml (keycloak):

```
volumes:
  mysql_data:
      driver: local

services:
  mysql:
      image: mysql:5.7
      volumes:
        - /srv/keycloak.example.com/mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: NotTheRealDBRootPass
        MYSQL_DATABASE: keydb
        MYSQL_USER: keyuser
        MYSQL_PASSWORD: NotTheRealDBPass
  keycloak:
      image: quay.io/keycloak/keycloak:19.0.3-legacy
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keydb
        DB_USER: keyuser
        DB_PASSWORD: NotTheRealDBPass
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: NotTheRealKCPass
        PROXY_ADDRESS_FORWARDING: "true"
        REDIRECT_SOCKET: "proxy-https"
        KEYCLOAK_FRONTEND_URL: https://login.example.com/auth
        KC_HOSTNAME_ADMIN_URL: https://login.example.com/auth/admin

      volumes:
        - /srv/keycloak.example.com/deployments:/opt/jboss/keycloak/standalone/deployments
        - /srv/keycloak.example.com/themes/mytheme:/opt/jboss/keycloak/themes/mytheme

      ports:
        - 8090:8080
      depends_on:
        - mysql
```

docker-compose.yml (oath2_proxy)

```
version: '3'

services:
  oauth2-proxy:
    image: docker.io/bitnami/oauth2-proxy:7.6.0
    ports:
      - 127.0.0.1:5002:5002
    restart: always
    command: ' --config=/srv/oauth2-proxy.cfg '
    volumes:
      - ./srv/:/srv
```

/srv/oauth2-proxy.cfg:

```
 http_address = "0.0.0.0:5002"
 email_domains = [
     "example.com"
 ]
 cookie_name = "_oauth2_proxy"
 cookie_secret = "NotTheRealCookieSecret"
 cookie_expire = "24h"
 skip_provider_button = true
 insecure_oidc_allow_unverified_email = true
 set_authorization_header = true
 provider = "keycloak-oidc"
 client_id = "srv_client"
 client_secret = "NotTheRealClientSecret"
 redirect_url = "https://srv.example.com/oauth2/callback"
 oidc_issuer_url  = "https://login.example.com/auth/realms/external"
```
