### ISSUE TITLE
[Support]: <Keycloak-OIDC failed>

### ISSUE THREAD

**Issue by karnain1803** [oauth2-proxy/oauth2-proxy#2646]
### OAuth2-Proxy Version

7.6.0

### Provider

keycloak-oidc

### Current Behaviour of your Problem

`[2024/05/21 09:20:56] [provider.go:55] Performing OIDC Discovery...                                                     [2024/05/21 09:20:56] [providers.go:145] Warning: Your provider supports PKCE methods ["plain" "S256"], but you have not enabled one with --code-challenge-method                                                                               [2024/05/21 09:20:56] [proxy.go:89] mapping path "/" => upstream "http://10.2.1.20:80"                                  [2024/05/21 09:20:56] [oauthproxy.go:162] OAuthProxy configured for Keycloak OIDC Client ID: test                       [2024/05/21 09:20:56] [oauthproxy.go:168] Cookie settings: name:_oauth2_proxy secure(https):true httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled                                                                       10.2.3.27:51172 - 08a1226cb97db41c1c5c2f81f95086df - - [2024/05/21 09:21:15] dev.gomining.tech GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" 401 13 0.000                                                                                                             10.2.3.27:37778 - e6b610cb1a16cf01137a1ae375f7f772 - - [2024/05/21 09:21:18] dev.gomining.tech GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" 302 397 0.000                                                                                                    10.2.3.27:37778 - 0cf2b942773163382477de01c9838541 - - [2024/05/21 09:21:19] dev.gomining.tech GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" 401 13 0.000                                                                                                             10.2.3.27:37778 - 07f111f94e56810a7763d490085da2b2 - - [2024/05/21 09:21:19] dev.gomining.tech GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" 302 397 0.000                                                                                                    10.2.3.27:37778 - 3aa64a1d8c1783c88fcfdbe57da43637 - - [2024/05/21 09:21:39] dev.gomining.tech GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" 401 13 0.000                                                                                                             10.2.3.27:37778 - 31a2b8424bf0957be447e7301dccf615 - - [2024/05/21 09:21:39] dev.gomining.tech GET - "/oauth2/start?rd=%2Foauth2%2Fcallback%3Fstate%3Dg8Fd8Sqbwdv3Vy55Mku914HMefWcX60EsMwtrlVops4%253A%252F%26session_state%3D5996a0e2-f332-458e-8d90-8f08d12fc0aa%26code%3De903943d-705d-4651-9d75-d55a26a59df4.5996a0e2-f332-458e-8d90-8f08d12fc0aa.3bce793d-ce31-49cf-94ed-b860f5057344" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" 302 653 0.000`

```
### Configuration details or additional information

# oauth2-proxy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: bitnami/oauth2-proxy:7.6.0  
        imagePullPolicy: Always
        ports:
        - containerPort: 4180
          protocol: TCP
        args:
        - --provider=keycloak-oidc
        - --upstream=http://10.2.1.20:80
        - --http-address=0.0.0.0:4180
       # - --scope=openid email profile
        - --redirect-url=https://kibana.gomining.tech
        - --oidc-issuer-url=https://example/auth/realms/GMT-Test
        - --client-id=test
        - --client-secret=xxx
        - --cookie-secret=xxx
        #- --ssl-insecure-skip-verify=true
        #- --silence-ping-logging=true
        - --email-domain=*
        - --insecure-oidc-allow-unverified-email=true
        - --skip-provider-button=true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    app: oauth2-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-oauth2-proxy
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  rules:
    - host: dev.gomining.tech
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180
  ingressClassName: nginx
  
  
  ---
  **my service**
  
  apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.default.svc.cluster.local/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://dev.gomining.tech/oauth2/start"
  name: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: expamle.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80

```
