### ISSUE TITLE
[Support]: How to configure oauth2 with kubernetes

### ISSUE THREAD

**Issue by gaglimax** [oauth2-proxy/oauth2-proxy#2651]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Current Behaviour of your Problem

I try to configure OAuth2 Proxy to handle anthentication on my application hosted on a Kubernetes cluster.
The URL of the App is app.example.com.
When I connect on the URL app.example.com, I am redirected to the authentication page. When I log in, I end on a 404 page.

### Configuration details or additional information

I use this Helm chart for the OAuth2 Proxy deployment : https://github.com/oauth2-proxy/manifests/tree/main/helm/oauth2-proxy.
Here is my values.yml : 
```YAML
config:
  clientID: <REDACTED>
  clientSecret: <REDACTED>
  cookieSecret: <REDACTED>
  configFile: |
    provider = "oidc"
    provider_display_name = "OIDC"
    oidc_issuer_url = "https://oidc-url.com"
    scope = "openid"
    code_challenge_method = "S256"
    whitelist_domains = ["*"]
    email_domains = ["*"]
    oidc_email_claim = "sub"
    cookie_expire = "1h"
    cookie_samesite = "strict"
    session_cookie_minimal = "true"

ingress:
  enabled: true
  className: "nginx"
  hosts:
  - app.example.com
  tls:
  - hosts:
    - app.example.com
    secretName: app-tls-secret
```
And my ingress manifests : 
```YAML
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie_name_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "name_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
  name: app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: app.example.com
    http:
      paths:
      - backend:
          service:
            name: app-service
            port:
              name: app-http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - app.example.com
    secretName: app-tls-secret
```

### Steps To Reproduce

1. Deploy the App
2. Install the Helm Chart
3. Deploy the Ingress

If a add `upstreams = "static://200"` to the chart configuration, I end on a page with a message "Authenticated", but impossible to see my app.
