### ISSUE TITLE
Trying to implement simple Oauth2-proxy/nginx configuration

### ISSUE THREAD

**Issue by compgumby** [oauth2-proxy/oauth2-proxy#2653]
### OAuth2-Proxy Version

quay.io/oauth2-proxy/oauth2-proxy:latest

### Provider

azure

### Current Behaviour of your Problem

I have a working nginx reverse proxy. As soon as I try to inject oauth2-proxy, it fails - usually with a 502. I've tried a variety of tutorials... ChatGPT... the only thing I haven't done is pull the whole project, add a shell to the image, and rebuild. (BTW-a shell for the image would be good). I tried using a docker compose with a network. I tried without. This seems like it should be really straightforward.

### Configuration details or additional information

Here's the docker compose file:
```
version: '3'
services:
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    container_name: Auth
    volumes:
      - ./gateway-conf/oauth2_proxy.cfg:/etc/oauth2_proxy.cfg
    ports:
      - "4180:4180"
    command:
      - --config=/etc/oauth2_proxy.cfg

  nginx:
    image: containersdev.azurecr.io/servicesgateway:latest
    container_name: Services.Gateway
    volumes:
      - ./gateway-conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5012:80"
    depends_on:
      - proxy
```
Here's the docker config:
```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /oauth2/ {
        internal;
        proxy_pass http://localhost:4180/oauth2/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # staging_begin
    location /api-staging/test/ {
        auth_request /oauth2/;
        error_page 401 = /404.html;
        error_page 403 = /404.html;

        proxy_pass http://10.0.0.4:5003/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    # staging_end

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```
Here's the oauth config:
```
provider = "azure"
client_id = "7..."
client_secret = "k..."
redirect_url = "http://localhost/oauth2/callback"
oidc_issuer_url = "https://login.microsoftonline.com/a...c/v2.0"
cookie_secret = "1...="
email_domains = ["*"]
upstreams = ["http://localhost:80"]

# Enable setting the authorization header
set_authorization_header = true
# Pass the authorization header
pass_authorization_header = true
# Pass user headers like X-Forwarded-User
pass_user_headers = true
# Set the X-Forwarded-* headers
pass_host_header = true
```      
I have tried setting this: 
```
proxy_pass http://localhost:4180/oauth2/auth
```
to
```
proxy_pass http://127.0.0.1:4180/oauth2/auth
```
and
```
proxy_pass http://0.0.0.0:4180/oauth2/auth
```
and
```
proxy_pass http://actualIpAddress:4180/oauth2/auth
```
With most of them, I get:
```
Services.Gateway  | 2024/06/03 18:43:02 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XXX.XX.XXX, server: localhost, request: "GET /api-staging/test/getenvironment HTTP/1.1", subrequest: "/oauth2/", upstream: "http://127.0.0.1:4180/oauth2/auth", host: "XX.XX.XXX.XXX:5011"
Services.Gateway  | 2024/06/03 18:43:02 [warn] 23#23: *1 upstream server temporarily disabled while connecting to upstream, client: XX.XXX.XX.XXX, server: localhost, request: "GET /api-staging/test/getenvironment HTTP/1.1", subrequest: "/oauth2/", upstream: "http://127.0.0.1:4180/oauth2/auth", host: "XX.XX.XXX.XXX:5011"
Services.Gateway  | XX.XXX.XX.XXX - - [03/Jun/2024:18:43:02 +0000] "GET /api-staging/test/getenvironment HTTP/1.1" 500 177 "-" "PostmanRuntime/7.39.0" "-"
Services.Gateway  | 2024/06/03 18:43:02 [error] 23#23: *1 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XXX.XX.XXX, server: localhost, request: "GET /api-staging/test/getenvironment HTTP/1.1", subrequest: "/oauth2/", upstream: "http://127.0.0.1:4180/oauth2/auth", host: "XX.XX.XXX.XXX:5011"
Services.Gateway  | 2024/06/03 18:43:02 [warn] 23#23: *1 upstream server temporarily disabled while connecting to upstream, client: XX.XXX.XX.XXX, server: localhost, request: "GET /api-staging/test/getenvironment HTTP/1.1", subrequest: "/oauth2/", upstream: "http://127.0.0.1:4180/oauth2/auth", host: "XX.XX.XXX.XXX:5011"
Services.Gateway  | 2024/06/03 18:43:02 [error] 23#23: *1 auth request unexpected status: 502 while sending response to client, client: XX.XXX.XX.XXX, server: localhost, request: "GET /api-staging/test/getenvironment HTTP/1.1", host: "XX.XX.XXX.XXX:5011"
```
I have tried sticking them on the same Docker network with this config:
```
version: '3'
services:
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    container_name: Auth
    volumes:
      - ./gateway-conf/oauth2_proxy.cfg:/etc/oauth2_proxy.cfg
    networks:
      - oauth2-network
    ports:
      - "4180:4180"
    command:
      - --config=/etc/oauth2_proxy.cfg

  nginx:
    image: nginx:latest
    container_name: Services.Gateway
    volumes:
      - ./gateway-conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - oauth2-network
    ports:
      - "5011:80"
    depends_on:
      - proxy

networks:
  oauth2-network:
    driver: bridge
```
When doing that, I changed the network mapping to "proxy:4180" on the nginx default.conf. 

No matter what I do, I cannot get this to go. 
Any help is greatly appreciated.
