### ISSUE TITLE
[Support]: unable to verify bearer token, failed to verify token: oidc: id token issued by a different provider

### ISSUE THREAD

**Issue by gabriel-farache** [oauth2-proxy/oauth2-proxy#2668]
### OAuth2-Proxy Version

v7.6.0

### Provider

keycloak-oidc

### Expected Behaviour

Be able to access REST API located behind the oauth2-proxy sidecar with keycloak access token (Bearer header)

### Current Behaviour

When I send a request to an endpoint that is behind the oauth2-proxy sidecar, I see the following log in the proxy:
```
[jwt_session.go:51] Error retrieving session from token in Authorization header: [unable to verify bearer token, failed to verify token: oidc: id token issued by a different provider, expected "https://keycloak/auth/realms/<realm_name>" got "https://frontend/api/auth"]
```

And I get the following response:
```
{"error":{"name":"AuthenticationError","message":"No token specified"},"request":{"method":"POST","url":"/api/notifications/notifications"},"response":{"statusCode":401}}
```

I do not understand the error nor why or where is get the path `https://frontend/api/auth`.

When I decode the bearer token I got
```
{
  ...
  "iss": "https://keycloak/auth/realms/realm_name",
  ...
 "aud": [
    "client_name",
    ...
  ],
  "typ": "Bearer",
  "azp": "client_name",
  ...
  "scope": "openid email profile",
  "email_verified": false,
  "clientId": "client_name",
}
```

### Steps To Reproduce

1. send the request:
```
curl -v -X POST https://frontend/api/notifications/notifications -H "Authorization: Bearer ${access_token}"  -H "Content-type: application/json" -H "Accept: application/json" -d '{"title": "My message title", "message": "I have nothing to say", "origin": "my-origin", "topic":"my topic", "targetUsers": ["default/user1"], "actions": [{"title": "Thank you!", "url": "http://foo.bar"}, {"title": "another action", "url": "https://foo.foo.bar"}]}'
```

And the bearer was retrieved by:
```
export access_token=$(\
   curl -X POST 'https://keycloak/auth/realms/realm_name/protocol/openid-connect/token' \
   -H 'Content-Type: application/x-www-form-urlencoded' \
   -d 'client_id=client' -d 'client_secret=secret' -d 'grant_type=client_credentials' | jq --raw-output '.access_token' \
   )
```

### Possible Solutions

Missing configuration in keycloak?

### Configuration details or additional information
```
env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: <secret>
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: >-
                https://keycloak/auth/realms/realm_name
            - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
              value: 'true'
```

```
args:
            - '--provider=oidc'
            - '--email-domain=*'
            - '--upstream=http://localhost:7007'
            - '--http-address=0.0.0.0:4180'
            - '--skip-provider-button'
            - '--insecure-oidc-allow-unverified-email=true'
            - '--skip-auth-strip-headers=false'
            - '--skip-jwt-bearer-tokens=true'
            - '--pass-authorization-header=true'
```
