### ISSUE TITLE
[Support]: CSS not loading when using oauth2-proxy as external authorizer with Istio

### ISSUE THREAD

**Issue by wesbrownfavor** [oauth2-proxy/oauth2-proxy#2677]
### OAuth2-Proxy Version

7.6.0

### Provider

github

### Current Behaviour of your Problem

Since upgrading from 7.1.3 to 7.6.0 when I try to access a url protected by an Istio authorization policy with oauth2-proxy set as the custom authorizer I get an error about mismatched MIME types when trying to pull the bulma.min.css file.

Error:
```
The resource from “https://protected-app.mydomain.com/oauth2/static/css/bulma.min.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```

Content type shown in console for bulma.min.css
```
content-type: text/plain; charset=utf-8
```

The weird thing is in logs I see oauth2-proxy serving the file with a 200:
```
[2024/06/20 17:53:27] protected-app.mydomain.com GET - "/oauth2/static/css/bulma.min.css" HTTP/1.1 "" 200 207302 0.000
```

When I try to access oauth2-proxy directly via its own Virtual Service the css file is served correctly.

Commit where change was made to css path to serve it locally instead of pulling from CDN:
https://github.com/oauth2-proxy/oauth2-proxy/commit/a02ab7c04e57c2895e4a83606f401599ca777c26#diff-4c8eaf3172d4df29c6706fc0fe0093babf8630fb4364349056382897b9aacfdeR8

### Configuration details or additional information

Istio External Authorizer config:

```
 - envoyExtAuthzHttp:
   headersToDownstreamOnDeny:
   - content-type
   - set-cookie
   headersToUpstreamOnAllow:
   - authorization
   - path
   - cookie
   - x-auth-request-access-token
   - x-auth-request-user
   - x-auth-request-email
   includeHeadersInCheck:
   - authorization
   - cookie
   port: 80
   service: oauth2-proxy.oauth2-proxy.svc.cluster.local
   timeout: 5s
```

oauth2-proxy config
```
    provider      = "github"
    email_domains = [ "*" ]
    github_org    = "myorg"
    upstreams = "static://200"
    cookie_samesite = "lax"
    cookie_secure = true
    cookie_domains = [".mydomain.com"]
    set_xauthrequest=true
    set_authorization_header=true
    pass_authorization_header=true
    pass_host_header=true
    pass_access_token=true
    silence_ping_logging = true
    standard_logging = true
    auth_logging = true
    request_logging = true
    http_address = "http://0.0.0.0:4180"
    real_client_ip_header = "X-Forwarded-For"
    reverse_proxy = true
    whitelist_domains = [".mydomain.com",]
    redirect_url = "https://oauth2-proxy.mydomain.com/oauth2/callback"
```

oauth2-proxy pod arguments
```
- args:
        - '--http-address=0.0.0.0:4180'
        - '--https-address=0.0.0.0:4443'
        - '--metrics-address=0.0.0.0:44180'
        - '--cookie-name=_oauth2_cookie_yum'
        - '--config=/etc/oauth2_proxy/oauth2_proxy.cfg'
```

Istio Authorization Policy
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: protected-app-auth
  namespace: istio-system
spec:
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - protected-app.mydomain.com
  selector:
    matchLabels:
      app: istio-ingressgateway
```

### Steps To Reproduce

1. Setup oauth2-proxy in cluster with config above
2. Setup oauth2-proxy as external authorizer 
3. Add auth policy
4. Attempt to access protected domain.
