### ISSUE TITLE
[Support]: injectRequestHeaders are not visible in headers upstream

### ISSUE THREAD

**Issue by pbwur** [oauth2-proxy/oauth2-proxy#2693]
### OAuth2-Proxy Version

7.6.0

### Provider

adfs

### Current Behaviour of your Problem

Hi, I'm using the oauth2-proxy helmchart with the following configuration, but I cannot see the injected headers at the side of upstream. Could anybody help me out here?

```yml
image:
    repository: "containerinfra/oauth2-proxy"
    tag: 7.6.0
extraArgs:
  cookie-secure: "false"
  cookie-domain: "xxxxxx"    # Replace with your base domain
  cookie-samesite: lax
  cookie-expire: 12h               # How long our Cookie is valid
  auth-logging: true               # Enable / Disable auth logs
  request-logging: true            # Enable / Disable request logs
  standard-logging: true           # Enable / Disable the standart logs
  show-debug-on-error: true        # Disable in production setups
  skip-provider-button: true       # We only have one provider configured (Keycloak)
  silence-ping-logging: true       # Keeps our logs clean
  whitelist-domain: ".xxxx.xxxxx.xxxxx" # Replace with your base domain
  redirect-url: https://xxxx.xxxx.xxxx.xxx./oauth2/callback

config:
  clientID: APP-xxxxxxxxxxx
  clientSecret: xxxxxxxxx
  cookieSecret: xxxxxxxx
  configFile: |
    email_domains = ["*"]
alphaConfig:
  enabled: true
  configData:
    injectRequestHeaders:
    - name: X-Forwarded-User
      values:
      - claim: email
    - name: X-Forwarded-Email
      values:
      - claim: email
    - name: X-Forwarded-Access-Token
      values:
      - claim: access_token
    - name: Authorization
      values:
      - claim: id_token
        prefix: 'Bearer '
    injectResponseHeaders:
    - name: X-Auth-Request-User
      values:
      - claim: email
    - name: X-Auth-Request-Email
      values:
      - claim: email    
    - name: X-Auth-Request-Access-Token
      values:
      - claim: access_token
    - name: Authorization
      values:
      - claim: id_token
        prefix: 'Bearer '
    providers:
    - clientID: xxxxxxx
      clientSecret: xxxxxxxx
      id: oauth2
      name: oauth2
      provider: oidc
      scope: "openid profile email"
      oidcConfig:
        emailClaim: email
        groupsClaim: group
        insecureSkipNonce: true
        issuerURL: https://xxxxxx.xxxx.xxxxxx.xx
        userIDClaim: email
        audienceClaims: 
          - aud        
    
```

### Configuration details or additional information

.

### Steps To Reproduce

.
