### ISSUE TITLE
[Support]: authetication on certain path

### ISSUE THREAD

**Issue by SolidSnail727** [oauth2-proxy/oauth2-proxy#2726]
### OAuth2-Proxy Version

7.6.1

### Provider

keycloak-oidc

### Current Behaviour of your Problem

I have a pyroscope running on https://pyroscope.example and I want to implement authentication on the path https://pyroscope.example/admin while leaving the other paths unprotected. What should I change in my current configuration to achieve the desired result?

### Configuration details or additional information

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2proxy-configmap
data:
  oauth2-proxy.cfg: |
    provider="keycloak-oidc"
    provider_display_name="Keycloak"
    client_id="pyroscope.example"
    client_secret="***"
    oidc_issuer_url="https://keycloak.example/realms/example"
    cookie_secure="false"
    upstreams=["https://pyroscope.example/admin"]
    http_address="0.0.0.0:4180"
    reverse_proxy="true"
    ssl_insecure_skip_verify="true"
    scope="openid"
    insecure_oidc_allow_unverified_email="true"
    email_domains=["*"]
    cookie_secret="***"
    metrics_address="0.0.0.0:4181"
    cookie_expire="10m"
    pass_access_token="true"
    cookie_refresh="9m30s"
    proxy_prefix="/oauth2"
```
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2proxy
spec:
  ingressClassName: nginx
  rules:
  - host: pyroscope.example
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2proxy
            port:
              number: 4180
```
Helm chart ingress configuration for pyroscope:
```
ingress:
  enabled: true
  tls:
    - hosts:
        - pyroscope.example
      secretName: appSecret
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://oauth2proxy.pyroscope.svc.cluster.local:4180/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://pyroscope.example/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Email,X-Auth-Request-Preferred-,X-Auth-Request-Access-Token,X-Auth-Request-Roles,X-Auth-Request-User,X-Forwarded-Groups,X-Auth-Request-Groups,Authorization
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/large_client_header_buffers: 4 16k
    nginx.ingress.kubernetes.io/proxy_buffers: 4 16k
    nginx.ingress.kubernetes.io/proxy_busy_buffers_size: 128k
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;

      access_by_lua_block {
        if ngx.var.name_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
  hosts:
    - pyroscope.example
```
```
apiVersion: v1
kind: Service
metadata:
  name: oauth2proxy
spec:
  type: ClusterIP
  selector:
    app: oauth2proxy
  ports:
  - name: oauth2proxy
    port: 4180
    targetPort: 4180
```
