### ISSUE TITLE
[Bug]: Token exchange fails, no URL (or any hints) given

### ISSUE THREAD

**Issue by senpro-ingwersenk** [oauth2-proxy/oauth2-proxy#2727]
### OAuth2-Proxy Version

quay.io/oauth2-proxy/oauth2-proxy:latest-amd64

### Provider

keycloak-oidc

### Expected Behaviour

A successful token exchange

### Current Behaviour

Excerpt from the log after re-checking and restarting my container configuration:

```
root@senst-sv-ai:/srv/local-ai# docker-compose logs -f o2p
Attaching to oauth2-proxy
oauth2-proxy | [2024/08/01 06:34:32] [provider.go:55] Performing OIDC Discovery...
oauth2-proxy | [2024/08/01 06:34:32] [oauthproxy.go:171] OAuthProxy configured for Keycloak OIDC Client ID: oauth2-proxy
oauth2-proxy | [2024/08/01 06:34:32] [oauthproxy.go:177] Cookie settings: name:_oauth2_proxy secure(https):false httponly:false expiry:168h0m0s domains: path:/ samesite: refresh:disabled
oauth2-proxy | 192.168.30.180 - 1ac68395-4d26-4812-8e06-c9ad6604ed53 - - [2024/08/01 06:41:43] 192.168.28.137 GET - "/oauth2/sign_in?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 302 414 0.001
oauth2-proxy | [2024/08/01 06:41:43] [oauthproxy.go:881] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 403 Forbidden
oauth2-proxy | Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
oauth2-proxy | <html><head>
oauth2-proxy | <title>403 Forbidden</title>
oauth2-proxy | </head><body>
oauth2-proxy | <h1>Forbidden</h1>
oauth2-proxy | <p>You don't have permission to access this resource.</p>
oauth2-proxy | </body></html>
```

This is the service configuration:

```yaml
  o2p:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest-amd64
    restart: always
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:8080"
      OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
      OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
      OAUTH2_PROXY_CLIENT_SECRET: "<snip>"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://keycloak.thecompany.tld/realms/master"
      OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
      OAUTH2_PROXY_REDIRECT_URL: "http://192.168.28.137/oauth2/callback" # FIXME
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: "Keycloak"
      OAUTH2_PROXY_COOKIE_SECRET: "<snip>"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      #OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_COOKIE_HTTPONLY: "false"
      OAUTH2_PROXY_EMAIL_DOMAINS: "thecompany.tld"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_REAL_CLIENT_IP_HEADER: "X-Forwarded-For"
      OAUTH2_PROXY_UPSTREAM: "http://openwebui:8080/"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: "true"
```

This is behind a very plain and flat Caddy configuration and the purpose of it is to serve as a testbed. We have a kubernetes cluster at our company to which tis will be migrated to once it is fully done. Since OpenWebUI lacks OIDC itself, I wanted to use oauth2-proxy to work around that and provide the supported "foreign authentication headers" (basically, E-Mail containing headers sent downstream which it accepts and "logs in" to the provided account). Hence why it currently is HTTP only - for now, for the time being.

Further, it lives in a test network so it has to access our actual Keycloak deployment with a little roundtrip and is thus subject to the WAF. And, knowing that my collegues blocked a bunch of endpoints, I need to find out which one in particular it is that is being the issue. Thus, I need the URL of what returns the above error document. Because discovery clearly works, it just can not seem to properly reach one of the endpoints to redeem the code and aquire further information.

It would be very helpful to know what exactly the failing URL was or is.

### Steps To Reproduce

1. Deploy keycloak somewhere else; literally. Different network/server.
2. Point oauth2-proxy at it
3. Attempt to log in

### Possible Solutions

A few more debug information (failed URL for instance) would be very helpful. I had activated the errors being displayed on the page mainly in hopes of getting an URL this way - but no luck.

### Configuration details or additional information

Although this is but a temporary setup (since 3 months...) I would still love to set up authentication with our existing OIDC so I can save myself the user management stuff.

Thanks!
