### ISSUE TITLE
[Support]: oauth2-proxy with Keycloak and Kubernetes Dashboard configuration : logged but no permissions, no token in headers

### ISSUE THREAD

**Issue by mleneveut** [oauth2-proxy/oauth2-proxy#2750]
### OAuth2-Proxy Version

v7.6.0

### Provider

keycloak-oidc

### Current Behaviour of your Problem

I am logged in but I don't see the access_token in the headers and I have no permission in Kubernetes Dashboard

### Configuration details or additional information

Keycloak 25.0.1
I tried Kubernetes Dahboard v7.5 but with their default Kong gateway I can't make it pass the login page
kubernetesui/dashboard:v2.7.0 : works but I have no permissions 
Kubernetes 1.29.6 installed on RHEL 9.4 with kubeadm

Kubernetes Dashboard Ingress : 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: >-
      X-Auth-Request-Email,X-Auth-Request-Preferred-,X-Auth-Request-Access-Token,
      X-Auth-Request-Roles,X-Auth-Request-User,X-Auth-Request-Groups,X-Forwarded-Groups,
      Authorization
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $access_token $upstream_http_x_auth_request_access_token;
      proxy_set_header Authorization "Bearer $access_token";
spec:
  tls:
  - hosts:
    - kubernetes-dashboard.mycomp.com
    secretName: dashboard-tls-secret
  ingressClassName: nginx
  rules:
  - host: kubernetes-dashboard.mycomp.com
    http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
        path: /
        pathType: Prefix
```

I also tried the configuration-snippet from https://oauth2-proxy.github.io/oauth2-proxy/configuration/integration : 

```
nginx.ingress.kubernetes.io/configuration-snippet: |
  auth_request_set $name_upstream_1 $upstream_cookie__oauth2_proxy_1;
  access_by_lua_block {
    if ngx.var.name_upstream_1 ~= "" then
      ngx.header["Set-Cookie"] = "_oauth2_proxy_1=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
    end
  }
```

oauth2-proxy : 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=keycloak-oidc  //also tried "oidc"
        - --session-store-type=redis
        - --redis-connection-url=redis://redis-stack-0.redis-service.redis:6379/0
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --oidc-extra-audience=kubernetes
        - --skip-jwt-bearer-tokens=true
        - --reverse-proxy=true
        - --auth-logging=true
        - --request-logging=true
        - --standard-logging=true
        env:
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: https://authk8s.mycomp.com/realms/master
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: https://kubernetes-dashboard.mycomp.com/oauth2/callback
        - name: OAUTH2_PROXY_CLIENT_ID
          value: kubernetes
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: XXX
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: XXX
        - name: OAUTH2_PROXY_UPSTREAM
          value: https://kubernetes-dashboard.mycomp.com
        - name: OAUTH2_PROXY_PROVIDER_CA_FILE
          value: "/cert-secret/root.crt"
        - name: OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL
          value: "true"
        - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
          value: "true"
        - name: OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY
          value: "true"
        - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
          value: "true"
        - name: OAUTH2_PROXY_OIDC_EMAIL_CLAIM
          value: "preferred_username"
        - name: OAUTH2_PROXY_OIDC_GROUPS_CLAIM
          value: groups
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
        - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
          value: "true"
        - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
          value: "S256"
        - name: OAUTH2_PROXY_SCOPE
          value: "openid email profile"
        - name: OAUTH2_PROXY_COOKIE_DOMAIN
          value: ".mycomp.com"
        - name: OAUTH2_PROXY_COOKIE_REFRESH
          value: "9m"
        - name: OAUTH2_PROXY_COOKIE_EXPIRE
          value: "30m"
        - name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
          value: "true"
        - name: OAUTH2_PROXY_PASS_HOST_HEADER
          value: "true"
        - name: OAUTH2_PROXY_PASS_USER_HEADER
          value: "true"
        - name: OAUTH2_PROXY_SET_XAUTHREQUEST
          value: "true"
        - name: OAUTH2_PROXY_SILENCE_PING_LOGGING
          value: "true"
        image: oauth2-proxy/oauth2-proxy:v7.6.0
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        volumeMounts:
          - mountPath: /cert-secret
            name: cert-secret
            readOnly: true
      volumes:
        - name: cert-secret
          secret:
            defaultMode: 420
            secretName: cert-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-ingress
  namespace: kube-system
spec:
  tls:
  - hosts:
    - kubernetes-dashboard.mycomp.com
    secretName: dashboard-tls-secret
  ingressClassName: nginx
  rules:
  - host: kubernetes-dashboard.mycomp.com
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
        path: /oauth2
        pathType: Prefix
```

Our users are coming from an Active Directory, and some don't have any emails, so I set another attribute for OIDC_EMAIL_CLAIM

I changed the kube-apiserver args : 

```
    - --oidc-issuer-url=https://authk8s.mycomp.com/realms/master
    - --oidc-client-id=kubernetes
    - --oidc-username-claim=preferredUsername
    - --oidc-groups-claim=groups
    - --oidc-username-prefix=oidc:
    - --oidc-groups-prefix=oidc:
```

I created a clusterRoleBinding for the group of my AD user : 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-prd-admin-role-binding
subjects:
  - kind: Group
    name: "oidc:GL-APPLI-KUBE-PRD-ADMIN"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

I have a Keycloak client "kubernetes" with callback URL https://kubernetes-dashboard.mycomp.com/oauth2/callback  : 
![image](https://github.com/user-attachments/assets/2822db12-b231-49ee-b13e-6d50d1e447f6)
![image](https://github.com/user-attachments/assets/a6c6b103-fc06-4b02-bb84-303c00743b56)
![image](https://github.com/user-attachments/assets/9a415226-3cf5-41e2-968a-2744ab7dce8e)

### Steps To Reproduce

1. In a 1.29.6 Kubernetes
2. Deploy an oauth2-proxy 7.6.0, kubernetes-dashboard 2.7.0, Keycloak 25
3. Configure the Keycloak resources with https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/keycloak_oidc/
4. Configure the kube-apiserver to use OIDC
5. When accessing the Kuberbetes Dashboard, you are redirected to the Keycloak login page
6. Login with your AD user
7. You are redirected to the Dashboard home page, but you have no permissions
![image](https://github.com/user-attachments/assets/88e0e4af-bcc4-41bb-9b03-1b125c13d651)

9. You can see the _oauth_proxy cookie but no tokens in headers
![image](https://github.com/user-attachments/assets/9f0795c7-f311-4949-a57a-3fd75c9cf6ca)
10. You can see in the oauth2-proxy logs that you are logged and the token seemed to be there somewhere

```
11.120.0.80 - 129e7e08991a6e0084232c83a2c08f00 - - [2024/08/21 12:52:34] kubernetes-dashboard.mycomp.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 401 13 0.000
10.120.0.80 - 99e046585bb843e983239fdae33dad99 - - [2024/08/21 12:52:34] kubernetes-dashboard.mycomp.com GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 302 456 0.000
10.120.1.14 - 46820346a1d42d6ab673d28435d68aa2 - su-mleneveut [2024/08/21 12:52:46] [AuthSuccess] Authenticated via OAuth2: Session{email:su-mleneveut user:d8065ebe-ba4b-410e-92dd-f4463ae72dc2 PreferredUsername:su-mleneveut token:true id_token:true created:2024-08-21 12:52:46.980810239 +0000 UTC m=+15143.265333304 expires:2024-08-21 13:02:46.980258926 +0000 UTC m=+15743.264781955 refresh_token:true groups:[GL-APPLI-KUBE-PRD-ADMIN role:default-roles-master role:offline_access role:uma_authorization role:account:manage-account role:account:manage-account-links role:account:view-profile]}
10.120.1.14 - 46820346a1d42d6ab673d28435d68aa2 - - [2024/08/21 12:52:46] kubernetes-dashboard.mycomp.com GET - "/oauth2/callback?state=LV0IlDmOo1PRhDOsx9ZiupqcANUNvQSrVK2DTYwUHaM%3A%2F&session_state=fde92fba-25c3-45db-9aa2-10b4d20bc6c5&iss=https%3A%2F%2Fauthk8s.mycomp.com%2Frealms%2Fmaster&code=c5f710a7-67c1-46de-a9aa-dacaa5fafa1a.fde92fba-25c3-45db-9aa2-10b4d20bc6c5.b98612ed-b9a5-4a45-b50e-1dd0d07bd5ae" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 302 24 0.035
10.120.1.14 - f133aa50257ed58cb2a28604a7e4e0c8 - su-mleneveut [2024/08/21 12:52:47] kubernetes-dashboard.mycomp.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 202 0 0.001
```

10. When I evaluate the user access-token in Keycloak "client scopes" tab of the client "kubernetes", I get : 

```
{
  "exp": 1724252792,
  "iat": 1724252192,
  "jti": "716c01ed-f47d-44a1-bf1e-728f09cce7c0",
  "iss": "https://authk8s.mycomp.com/realms/master",
  "aud": [
    "kubernetes",
    "account"
  ],
  "sub": "d8065ebe-ba4b-410e-92dd-f4463ae72dc2",
  "typ": "Bearer",
  "azp": "kubernetes",
  "sid": "dfc22248-aa14-43d8-8df7-ddaa5308eade",
  "acr": "1",
  "allowed-origins": [
    "https://kubernetes-dashboard.mycomp.com"
  ],
  "realm_access": {
    "roles": [
      "default-roles-master",
      "offline_access",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "email_verified": true,
  "name": "LENEVEUT Michael",
  "groups": [
    "GL-APPLI-KUBE-PRD-ADMIN"
  ],
  "preferred_username": "su-mleneveut",
  "given_name": "LENEVEUT Michael",
  "family_name": "LENEVEUT"
}
```

11. The redis contains keys prefixed with _oauth2-proxy : 
![image](https://github.com/user-attachments/assets/5de96e7b-6646-4209-9df3-20c40ce14387)
