### ISSUE TITLE
[Support]: Pass Keycloak attribue as HTTP Header to upstream

### ISSUE THREAD

**Issue by Luth1ng** [oauth2-proxy/oauth2-proxy#2757]
### OAuth2-Proxy Version

v7.6.0

### Provider

keycloak-oidc

### Current Behaviour of your Problem

Hi,

I am using Alpha configuration to pass a Keycloak's user attribute to my upstream.

Keycloak is sending the attributes as a token's claim to OA2P : 
```
{
    "exp": 1724746642,
    "iat": 1724746582,
    "auth_time": 1724746582,
    "jti": "b25be509-e19f-4e10-98a3-679d7f9f5c8d",
    "iss": "http://10.0.0.1:8443/realms/master",
    "aud": "oauth2-proxy",
    "sub": "42752de2-1b53-4243-96dc-c4c5f32ec42f",
    "typ": "ID",
    "azp": "oauth2-proxy",
    "sid": "cbeecc85-7b5c-4f63-933b-99dab59a8771",
    "at_hash": "pKeQZ6Akp_bGlcOJZCVnFQ",
    "acr": "1",
    "address": {},
    "email_verified": true,
    "name": "John DOE",
    "fullname": "DOE John",
    "preferred_username": "john.doe",
    "given_name": "John",
    "family_name": "DOE",
    "email": "john.doe@example.com"
}
```

But OA2P cannot get this value and assign it to an existing header.

### Configuration details or additional information

Here's the configuration part :
```
injectRequestHeaders:
- name: X-Forwarded-Preferred-Username
  values:
  - claim: fullname
```

It seems OA2P cannot get this claim, as the header is not sent back to the upstream :  
```
X-Forwarded-Email: john.doe@example.com
X-Forwarded-For: 172.16.46.7
X-Forwarded-Groups: role:create-realm,role:default-roles-master,role:offline_access,role:admin,role:uma_authorization,role:master-realm:view-realm,role:master-realm:view-identity-providers,role:master-realm:manage-identity-providers,role:master-realm:impersonation,role:master-realm:create-client,role:master-realm:manage-users,role:master-realm:query-realms,role:master-realm:view-authorization,role:master-realm:query-clients,role:master-realm:query-users,role:master-realm:manage-events,role:master-realm:manage-realm,role:master-realm:view-events,role:master-realm:view-users,role:master-realm:view-clients,role:master-realm:manage-authorization,role:master-realm:manage-clients,role:master-realm:query-groups,role:account:manage-account,role:account:manage-account-links,role:account:view-profile
X-Forwarded-User: 42e52de2-1b53-4243-91dc-c4c1f32fc42f
```

When I try to specifiy a "test" base64 value to the header, it works as expected.

Some help would be much appreciated.
Cheers

**Comment by mleneveut** [comment]
Can you give us your full OA2P configuration ?

**Comment by Luth1ng** [comment]
> Can you give us your full OA2P configuration ?

Here's the last test I did : 
```
server:
  BindAddress: 0.0.0.0:4180
  SecureBindAddress: ""
  TLS: null
metricsServer:
  BindAddress: ""
  SecureBindAddress: ""
  TLS: null
upstreamConfig:
  upstreams:
  - id: upstream
    uri: http://upstream:8123
    passHostHeader: true
    path: /
    proxyWebSockets: true
    insecureSkipTLSVerify: true
    timeout: 30s
providers:
- provider: keycloak-oidc
  id: Keycloak OIDC
  clientID: oauth2-proxy
  clientSecret: Z2fX441dABHOmgPDFU0q5Stme22KRLek
  code_challenge_method: S256
  loginURLParameters:
  - name: approval_prompt
    default:
    - force
  name: Keycloak OIDC
  oidcConfig:
    audienceClaims:
    - aud
    emailClaim: email
    groupsClaim: groups
    insecureSkipNonce: true
    issuerURL: https://keycloak:8443/realms/master
    userIDClaim: email
  scope: openid profile email
injectRequestHeaders:
- name: X-Forwarded-Groups
  values:
  - claim: groups
- name: X-Forwarded-User
  values:
  - claim: user
- name: X-Forwarded-Email
  values:
  - claim: email
- name: X-Forwarded-Preferred-Username
  values:
  - claim: fullname
  preserveRequestValue: true
injectResponseHeaders:
- name: X-Forwarded-Preferred-Username
  values:
  - claim: fullname
```

It just wipes out the "X-Preferred-Username" for the upstream request.
