### ISSUE TITLE
[Bug]: Failed to verify TLS Certificate during OIDC discover

### ISSUE THREAD

**Issue by marjus45** [oauth2-proxy/oauth2-proxy#2760]
### OAuth2-Proxy Version

95cbd0cdfbe4

### Provider

None

### Expected Behaviour

I am using the following configuration to provide a custom CA to oauth2-proxy:
```
providers:
  - caFiles:
      - /etc/ssl/certs/ca-certificates.crt
      - ./ca.crt
[...]
```
With this CA I have signed the Certificate of the ingress controller which is before my OIDC provider [Keycloak instance].

I expect oauth2-proxy to successfully perform an OIDC discovery.

### Current Behaviour

Currently it fails with the following error:
```
[2024/08/30 14:04:19] [provider.go:55] Performing OIDC Discovery...
[2024/08/30 14:04:19] [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error initialising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: error performing request: Get "https:/<DOMAIN>/auth/realms/<REALM>/.well-known/openid-configuration": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### Steps To Reproduce

1. Build the latest master
2. Configure an OIDC provider with a Certificate signed by a custom CA
3. Provide the CA file in your alpha configuration
   ```
   providers:
     - caFiles:
         - /etc/ssl/certs/ca-certificates.crt
         - ./ca.crt
   [...]
   ```
4. Run `./oauth2-proxy --alpha-config alphaconfig.yaml --config oauth2-proxy.cfg`

### Possible Solutions

The issue seems related to https://github.com/oauth2-proxy/oauth2-proxy/pull/2570/files#diff-88d3656bbf6c31111a601f3d2e9935d0747da2b554cb9d6633e278ac2075ff6fR102. The patch introduced a breaking change on the client which makes the HTTP requests, as it didn't follow up the logic of the old client (http.DefaultClient) which was based on the following options https://github.com/oauth2-proxy/oauth2-proxy/blob/master/pkg/validation/options.go#L32-L50

### Configuration details or additional information

Complete Alpha configuration:
```
injectRequestHeaders:
  - name: X-Forwarded-Groups
    values:
      - claim: groups
  - name: X-Forwarded-User
    values:
      - claim: user
  - name: X-Forwarded-Email
    values:
      - claim: email
  - name: X-Forwarded-Preferred-Username
    values:
      - claim: preferred_username
injectResponseHeaders:
  - name: X-Auth-Request-User
    values:
      - claim: user
  - name: X-Auth-Request-Email
    values:
      - claim: email
  - name: X-Auth-Request-Preferred-Username
    values:
      - claim: preferred_username
  - name: X-Auth-Request-Groups
    values:
      - claim: groups
  - name: Authorization
    values:
      - claim: id_token
        prefix: 'Bearer '
metricsServer:
  BindAddress: '0.0.0.0:44180'
  SecureBindAddress: ""
  TLS: null
providers:
  - ADFSConfig: {}
    azureConfig:
      tenant: common
    bitbucketConfig: {}
    caFiles:
      - /etc/ssl/certs/ca-certificates.crt
      - ./ca.crt
    githubConfig: {}
    gitlabConfig: {}
    googleConfig: {}
    id: Keycloak
    keycloakConfig: {}
    loginGovConfig: {}
    loginURLParameters:
      - default:
          - force
        name: approval_prompt
    name: Keycloak
    oidcConfig:
      audienceClaims:
        - aud
      emailClaim: email
      groupsClaim: groups
      insecureAllowUnverifiedEmail: true
      insecureSkipNonce: true
      issuerURL: https://<DOMAIN>/auth/realms/<REALM>
      userIDClaim: email
    provider: oidc
    scope: openid profile email
    clientID: REDACTED
    clientSecret: REDACTED
server:
  BindAddress: 0.0.0.0:4180
  SecureBindAddress: ""
  TLS: null
upstreamConfig:
  upstreams:
    - id: static://200
      path: /
      static: true
      staticCode: 200
```
Complete `oauth2-proxy.cfg`:
```
whitelist_domains = [ "<DOMAIN>" ]
email_domains = [ "*" ]
redirect_url = "https://<DOMAIN>/oauth2/callback"
cookie_secure = true
cookie_refresh = "10m"
ssl_insecure_skip_verify = false
reverse_proxy = true
auth_logging = true
request_logging = true
skip_jwt_bearer_tokens = true
skip_provider_button = true
api_routes = ["^/api/"]
```
