### ISSUE TITLE
[Bug]: Unable to configure AWS Cognito for authentication using oauth2-proxy

### ISSUE THREAD

**Issue by adarsh-ks** [oauth2-proxy/oauth2-proxy#2762]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Expected Behaviour

Authentication successful through AWS Cognito

### Current Behaviour

Getting "401 Authorization Required" when invoking the url

### Steps To Reproduce

I have created a kubernetes Deployment and service for the oauth2-proxy image pulled from quay.io

```
-----oauth2-proxy-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "oauth2-proxy-deployment"
  namespace: <namespace>
spec:
  selector:
    matchLabels:
      app: "oauth2-proxy-app"
  replicas: 1
  template:
    metadata:
      labels:
        app: "oauth2-proxy-app"
    spec:
      serviceAccountName: {{ svc_acct }}
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: <COOKIE_SECRET>
            - name: OAUTH2_PROXY_CLIENT_ID
              value: <CLIENT_ID>
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: <CLIENT_SECRET>
            - name: OAUTH2_PROXY_PROVIDER
              value: "oidc"
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: <EMAIl_DOMAIN>
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: "https://cognito-idp.<AWS_REGION>.amazonaws.com/<user-pool-id>"
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: "true"
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: "0.0.0.0:4180"
          ports:
            - containerPort: 4180
              protocol: TCP
```
```
------oauth2-proxy-service.yml

apiVersion: v1
kind: Service
metadata:
  name: "oauth2-proxy-service"
  namespace: <namespace>
spec:
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
  type: NodePort
  selector:
    app: "oauth2-proxy-app"
```

From the application side, I have a docker image where nginx is installed which should internally invoke oauth2-proxy for authentication when the application is invoked.

The application has an ingress configured which will be used by the user to communicate from browser,
```
----app-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_deployment
  namespace: <namespace>
spec:
  selector:
    matchLabels:
      app: app_name
  replicas: 1
  template:
    metadata:
      labels:
        app: app_name
    spec:
      serviceAccountName: {{ svc_acct }}
      volumes:
        - name: ssl-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: <Secret_Provider_Name>
      containers:
        - name: app_name
          image: {{ image }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "128Mi"
          env:
            - name: AWS_REGION
              value: "{{ region }}"
          ports:
            - containerPort: 3050
              protocol: TCP
          volumeMounts:
            - name: ssl-secrets
              mountPath: "/mnt/secrets-store"
              readOnly: true
```

```
-----app-service.yml

apiVersion: v1
kind: Service
metadata:
  name: app_service
  namespace: <namespace>
spec:
  ports:
    - port: 3050
      targetPort: 3050
      protocol: TCP
  type: NodePort
  selector:
    app: app_name
```

```
------app-ingress.yml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app_ingress
  namespace: <namespace>
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: {{ securityGroup }}
    alb.ingress.kubernetes.io/group.name: <group_name>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:{{ region }}:{{ accountId }}:certificate/o<certificate_id>
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    app: app_ingress
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /app-test
          pathType: Prefix
          backend:
            service:
              name: app_service
              port: 
                number: 3050
```

```
-----nginx.conf

server {
    listen 3050 ssl;
    ssl_certificate <Certificate>;
    ssl_certificate_key <Certificate Key>;
    client_max_body_size 5m;
    keepalive_timeout 5;
    proxy_read_timeout 1200s;

    location /oauth2/ {
      proxy_pass       http://<IP Address of oauth2-proxy service>:4180;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host                    $host;
      proxy_set_header X-Real-IP               $remote_addr;
      proxy_set_header X-Auth-Request-Redirect $request_uri;
      # or, if you are handling multiple domains:
      # proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;
    }
    location = /oauth2/auth {
      proxy_pass       http://<IP Address of oauth2-proxy service>:4180;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host             $host;
      proxy_set_header X-Real-IP        $remote_addr;
      proxy_set_header X-Forwarded-Uri  $request_uri;
      # nginx auth_request includes headers but not body
      proxy_set_header Content-Length   "";
      proxy_pass_request_body           off;
    }

    location ~ ^/(app-test) {
      auth_request /oauth2/auth;
      error_page 401 =403 /app-test/oauth2/sign_in;

      #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;

      proxy_pass http://gunicorn;
      proxy_ssl_server_name on;
    }
```
