### ISSUE TITLE
Error redeeming code during OAuth2 callback: error performing request: Post "https://www.googleapis.com/oauth2/v3/token": net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by huynguyen-b3networks** [oauth2-proxy/oauth2-proxy#2773]
### OAuth2-Proxy Version

v7.6.0

### Provider

google

### Expected Behaviour

After login google gmail will be successfully

### Current Behaviour

After login google gmail it return 500

### Steps To Reproduce

I run docker compose:

```
services:
  webnettools:
    image: johannesschafer/webnettools:1.3.0
    container_name: webnettools
    restart: always
    ports:
      - "8080:8080"
    networks:
      - webnettools
    environment: 
      RATE_LIMIT: 5000
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 50M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_CLIENT_ID=xxx-xxxxx.apps.googleusercontent.com
      - OAUTH2_PROXY_CLIENT_SECRET=xxx-xxx
      - OAUTH2_PROXY_COOKIE_SECRET=xxxx
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_REDIRECT_URL=https://vm1.nettools.mycompany.com/oauth2/callback
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_UPSTREAMS=http://webnettools:8080
      - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.vm1.nettools.mycompany.com
    command:
      - --http-address=0.0.0.0:4180
      - --upstream=http://webnettools:8080
    networks:
      - webnettools
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
    webnettools:

```
