### ISSUE TITLE
[Bug]: Configuration in ConfigMap mounted to file in pod and using set_basic_auth leads to error

### ISSUE THREAD

**Issue by matthjes** [oauth2-proxy/oauth2-proxy#2787]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Expected Behaviour

Using set_basic_auth should set the authorization header to the basic auth.

### Current Behaviour

Using set_basic_auth, having the configuration stored as a ConfigMap and mounting this as a file to the pod which also gets secrets from Azure key vault and sets them as environment variables leads to the following error message: 

```
[2024/09/20 08:58:39] [main.go:52] invalid configuration:
  injectResponseHeaders: invalid header "Authorization": invalid values: invalid basicAuthPassword: multiple values specified for secret source: specify either value, fromEnv of fromFile
```

### Steps To Reproduce

1. Create ConfigMap with client_id, client_secret.
2. Mount ConfigMap into pod via deployment (see below)
3. Get secret values for client_id and client_secret from Azure Key vault and set them as environment variables.
4. Add set_basic_auth to proxy configuration.
5. Start pod.
6. Error message

### Configuration details or additional information

ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: {{ .Values.envspecific.general.namespace }}
data:
  oauth2-proxy.cfg: |
    provider = "oidc"
    scope = "<scopes>"
    redirect_url = "<uri>"
    client_id = "$(CLIENT_ID)"
    client_secret = "$(CLIENT_SECRET)"
    cookie_secret = "$(COOKIE_SECRET)"
    cookie_domains = "<domains>"
    cookie_secure = "true"
    oidc_issuer_url = "<uri>"
    whitelist_domains = [<domains>]
    http_address = "<ip>"
    metrics_address = "<ip>"
    email_domains = [ "*" ]
    reverse_proxy = "true"
    pass_access_token = "true"
    set_xauthrequest = "true"
    set_basic_auth = "true"
    acr_values = "<values>"
```

Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: <namespace>
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      terminationGracePeriodSeconds: 0
      securityContext:
        runAsNonRoot: true
      containers:
        - name: oauth2-proxy
          image: bitnami/oauth2-proxy:7.6.0
          ports:
            - containerPort: 4180
          volumeMounts:
            - name: config-volume
              mountPath: /etc/oauth2-proxy/oauth2-proxy.cfg
              subPath: oauth2-proxy.cfg
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: <name>
                  key: <key>
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: <name>
                  key: <key>
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: <name>
                  key: <key>
          args:
            - --config=/etc/oauth2-proxy/oauth2-proxy.cfg
      volumes:
        - name: config-volume
          configMap:
            name: oauth2-proxy-config
```
