### ISSUE TITLE
[Support]: Expiring oauth2-proxy access tokens when Keycloak session is manually expired

### ISSUE THREAD

**Issue by ndtreviv** [oauth2-proxy/oauth2-proxy#2795]
### OAuth2-Proxy Version

v7.6.0-alpine

### Provider

keycloak-oidc

### Current Behaviour of your Problem

It is possible, as an Admin in Keycloak, to navigate to a user's session and expire it via the Keycloak UI.
This has no effect on the oauth2-proxy cookie whatsoever - it'll continue allowing the user access to the application until the cookie expiration date has been reached.

One mitigation for this is to set the access token lifetime to a very small amount, and require very regular refreshes.

Is there a better way? Ideally I'd like to not have to refresh the token every minute, but rather somehow have the oauth2-proxy know when the session has been killed off in Keycloak.

### Configuration details or additional information

An example of our configuration running in docker-compose:

```
  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: "pg_isready -U postgres"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_HEALTH_ENABLED=true
    ports:
      - "22003:80"
    command: start-dev --log-level=DEBUG --http-port=80
    depends_on:
      postgres:
        condition: service_healthy

  oauth2-proxy-dev:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
    restart: unless-stopped
    environment:
      - OAUTH2_PROXY_BACKEND_LOGOUT_URL=http://keycloak/realms/MyOrg/protocol/openid-connect/logout?id_token_hint={id_token}
      - OAUTH2_PROXY_CLIENT_ID=my-client
      - OAUTH2_PROXY_CLIENT_SECRET_FILE=/shared/client_secret
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      - OAUTH2_PROXY_COOKIE_SECRET=...
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=:80
      - OAUTH2_PROXY_LOGIN_URL=http://localhost:22003/realms/MyOrg/protocol/openid-connect/auth
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://localhost:22003/realms/MyOrg
      - OAUTH2_PROXY_OIDC_JWKS_URL=http://keycloak/realms/MyOrg/protocol/openid-connect/certs
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=false
      - OAUTH2_PROXY_PROVIDER=keycloak-oidc
      - OAUTH2_PROXY_REDEEM_URL=http://keycloak/realms/MyOrg/protocol/openid-connect/token
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:22000/oauth2/callback
      - OAUTH2_PROXY_SKIP_OIDC_DISCOVERY=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_UPSTREAMS=http://authd-application
    volumes:
      - ./volumes/keycloak-shared/:/shared
    ports:
      - "22000:80"
```

### Steps To Reproduce

1. Setup oauth2-proxy with keycloak-oidc.
2. Authenticate a user against keycloak and confirm access to the upstream application is possible
3. As an admin in the Keycloak UI, find the user's session and kill it
4. Attempt application access as the originally authenticated user
