### ISSUE TITLE
[Support]: How to use single instance of oauth2-proxy with multiple SPAs 

### ISSUE THREAD

**Issue by koyadume** [oauth2-proxy/oauth2-proxy#2815]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Current Behaviour of your Problem

We wrote a [blog post](https://academy.mechcloud.io/universal-approach-to-integrate-oauthoidc-into-web-applications) to describe how using `oauth2-proxy` can help integrate `oauth2 / oidc` in different types of web applications universally.

I am not very sure if `oauth2-proxy` has out of the box support for the use case mentioned in the the title. I had to use a hack on cloudflare to overcome what seems to be a limitation at this moment.

I can see that the proxy supports `--redirect-url` and `--upstream` flags but it is not clear how these two can be used in different scenarios. Are these parameters really required if I trigger authentication flow by using `/start` endpoint passing the initial url of the SPA entered by the user in the browser against the `rd` parameter of this endpoint?

While the documentation does a good job of explaining how to configuring this proxy in an IdP as a client, I think we need more details around how to configured this proxy for a web application. Documentation is missing all the parameters and other things supported by the various endpoints of this proxy. Ideally OpenAPI specification for all the endpoints will be of great help to all the folks who are using this proxy.

### Configuration details or additional information

```
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4190
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_DISPLAY_NAME: Auth0
      OAUTH2_PROXY_CLIENT_ID: 
      OAUTH2_PROXY_CLIENT_SECRET: 
      OAUTH2_PROXY_COOKIE_SECRET: 
      OAUTH2_PROXY_REDIRECT_URL: https://sso.mechcloud.dev/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://tenant1.eu.auth0.com/
      OAUTH2_PROXY_LOGIN_URL: https://tenant1.eu.auth0.com/authorize
      OAUTH2_PROXY_REDEEM_URL: https://tenant1.eu.auth0.com/oauth/token
      OAUTH2_PROXY_VALIDATE_URL: https://tenant1.eu.auth0.com/userinfo
      OAUTH2_PROXY_PROFILE_URL: https://tenant1.eu.auth0.com/userinfo
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: 'true'
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: 'true'
    restart: always
```
