### ISSUE TITLE
[Bug]: Invalid callback request should be denied

### ISSUE THREAD

**Issue by chr1st1ank** [oauth2-proxy/oauth2-proxy#2822]
### OAuth2-Proxy Version

v7.7.1

### Provider

azure

### Expected Behaviour

When requesting an invalid callback url, the client should get 403 Forbidden. This was the case under version v7.7.0. There was no error log aside from the normal request log message.

### Current Behaviour

OAuth2-proxy returns 500 "Internal Server Error" and logs `[oauthproxy.go:875] Error while parsing OAuth2 state: invalid length`.

### Steps To Reproduce

We're running an oauth2-proxy as kubernetes deployment with the following config:

```yaml
     args:                                                                                                                                                                                                                                                                            
     - --email-domain=*                                                                                                                                                                                                                                                               
     - --http-address=0.0.0.0:8000                                                                                                                                                                                                                                                    
     - --upstream=file:///dev/null                                                                                                                                                                                                                                                    
     - --azure-tenant=$(AZURE_TENANT)                                                                                                                                                                                                                                                 
     - --provider=oidc                                                                                                                                                                                                                                                                
     - --oidc-issuer-url=https://login.microsoftonline.com/$(AZURE_TENANT)/v2.0                                                                                                                                                                                                       
     - --skip-provider-button                                                                                                                                                                                                                                                         
     - --session-store-type=redis                                                                                                                                                                                                                                                     
     - --redis-connection-url=redis://localhost:6379                                                                                                                                                                                                                                  
     - --set-xauthrequest                                                                                                                                                                                                                                                             
     - --cookie-expire=2h0m0s                                                                                                                                                                                                                                                         
     - --allowed-group=standard                                                                                                                                                                                                                                                       
     - --skip-jwt-bearer-tokens                                                                                                                                                                                                                                                       
     - --oidc-groups-claim=roles                                                                                                                                                                                                                                                      
     - --extra-jwt-issuers=https://login.microsoftonline.com/$(AZURE_TENANT)/v2.0=$(OAUTH2_PROXY_CLIENT_ID)                                                                                                                                                                           
     - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)                                                                                                                                                                                                                                  
     - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)                                                                                                                                                                                                                                  
     - --client-id=$(OAUTH2_PROXY_CLIENT_ID)                                                                                                                                                                                                                                          
     - --scope=openid profile email                                                                                                                                                                                                                                                   
     - --auth-logging=true                                                                                                                                                                                                                                                            
     - --request-logging=true                                                                                                                                                                                                                                                
     envFrom:                                                                                                                                                                                                                                                                         
     - secretRef:                                                                                                                                                                                                                                                                     
         name: oauth2-secret                                                                                                                                                                                                                                          
     image: bitnami/oauth2-proxy:7.7.1    
```

When it's running, I simply send a request like this (originally to test one step of the oauth2 flow):

```
curl --include --silent --show-error "https://$INGRESS_HOST/oauth2/callback?code=123&state=abc&session_state=def"
```

Depending on the version (7.7.0 versus 7.7.1), this returns with HTTP status 403 or 500.

### Possible Solutions

Permission should be denied and only minimal information leaked to a client who sends a malicious/unauthenticated request to the callback url.

### Configuration details or additional information

_No response_
