### ISSUE TITLE
[Support]: Need oauth2 Access Token to be passed and not ID token in Authorization Header 

### ISSUE THREAD

**Issue by umeshkaul** [oauth2-proxy/oauth2-proxy#2825]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Current Behaviour of your Problem

I have following use case and need help either addressing it using an existing configuration option or adding a specific configuration option for this particular use case (for which I am willing to create a PR ).

**Use Case : Overview** 

I need to be able to access an application which is running in a Kubernetes cluster using a browser. The application is exposed using Istio ingress/service-mesh and users are required to authenticate using an IDP.  After successful authentication the application requires that oauth2 access token (not id token) be passed to it as "Authorization": "Bearer xxx" since it uses that token for further authorization.  I am seeing ID token being passed. Below are more details of the test setup. 

**Use Case : Test Setup**

```
browser--->istio_ingress--->istio_virtual_service--->istio_ext_auth_oauth2_proxy--->IDP
                                            ---->web_app_requiring_oauth2_access_token
```
Behavior I see with below config is that after user authenticates oauth2-proxy and istio using below config passes the oauth2 ID token. I need it to pass oauth2 Access token i.e the http request which my application (in the test below i am using httpbin) gets 

```
    "Authorization": "Bearer THIS_IS_ID_TOKEN_BUT_I_NEED_ACCESS_TOKEN",
```

**Easy to get desired behavior with nginx but not istio**
- I understand it is easy to make it work with nginx but with istio it requires creating an `EnvoyFilter` which I want to avoid , hence this request. 
- As far as i can tell the behavior i am observing is the intended one as is obvious from the [code here](https://github.com/oauth2-proxy/oauth2-proxy/blob/e00c7a7eddc39a3f19c70d4cbed3bf2116cea368/pkg/apis/options/legacy_options.go#L372) but I feel that Access Token is more useful than ID token since ID token is usually with short validity.  
- I have done some testing using my local setup and feel that it would be very useful to be able to specify which token should be set in the Authorization response to the upstream service. 
- I am willing to create a PR if we agree on a solution/approach to this issue. This will be a very useful feature for istio in kubernetes. 

### Configuration details or additional information

- oauth2-proxy helm chart config

```
config:
  clientID: "example"
  clientSecret: "XXX"
  cookieSecret: "XXX"
  configFile: |-
    http_address = "0.0.0.0:4180"
    redirect_url = "https://apps.example.com/oauth2/callback"
    upstreams = [
        "http://getpods.getpods.svc.cluster.local/pods",
    ]
    oidc_issuer_url = "https://idp.example.com"
    oidc_jwks_url = "https://idp.example.com/ext/oauth2/jwks"
    provider_display_name = "Exmaple IDP"
    provider = "oidc"
    cookie_secure = true
    show_debug_on_error = true
    standard_logging = true
    request_logging = true
    auth_logging = true
    cookie_samesite = "lax"
    cookie_refresh = "1h"
    cookie_expire = "4h"
    cookie_name = "_oauth2_proxy_istio_ingressgateway"
    set_authorization_header = true
    skip_provider_button = true
    set_xauthrequest = true
    email_domains = [
        "*"
    ]
    client_id = "example"
    client_secret = "XXXXX"
    cookie_secret = "XXXXX"
    pass_host_header = true
    pass_user_headers = true
    pass_authorization_header = true
    pass_access_token = true
    skip_jwt_bearer_tokens = true
    silence_ping_logging = true

service:
  portNumber: 4180

serviceAccount:
  enabled: false
```

- istio configuration 

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: apps-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway 
  servers:
  - hosts:
    - "apps.example.com"
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "apps.example.com"
    port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: example-cert

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apps-vs
  namespace: istio-system
spec:
  hosts:
  - "apps.example.com"
  gateways:
  - apps-gw
  http:
  - match:
    - uri:
        exact: /headers
    route:
    - destination:
        host: "httpbin.httpbin.svc.cluster.local"
        port:
          number: 80
  - match:
    - uri:
        prefix: /oauth2
    route:
    - destination:
        host: oauth2-proxy.auth.svc.cluster.local
        port:
          number: 4180

---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: apps-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: "oauth2-proxy"
  rules:
  - to:
    - operation:
        paths: ["/headers"]

```

**Comment by vijayendrar** [comment]
yes whenever Authorization header pass with oauth2-proxy it sends ID token these thing need to control through envoyfilter then you will get access token instead of ID token

**Comment by WangYiDFO** [comment]
The request is pretty straight forward. Our solution also need Access Token in Authorization Bearer header. 
I simply fork and make extra config. [code here](https://github.com/WangYiDFO/oauth2-proxy).

add extra config setting for our usage. By able to pass access token to Upstream Authentication header under Bearer. example in config file: pass_access_token_to_bearer = true

flag: --pass-access-token-to-bearer
toml: pass_access_token_to_bearer

Well, since it's in Bearer, when use this config, should not use pass-authorization-header at the same time. that's all.

**Comment by iliuta** [comment]
Yes, I totally need this too. The ID token is not meant to give access to anything. It only contains user data. The access token is the one which gives the permissions.
Definitely the "Authorization: Bearer ..." should contain the access token.

**Comment by tuunit** [comment]
Already discussed in #843.

Please use the alpha config for this.

https://oauth2-proxy.github.io/oauth2-proxy/configuration/alpha-config/#alphaoptions

```
# Headers for upstream
injectRequestHeaders:
- name: Authorization
  values:
  - claim: access_token
    prefix: "Bearer "

# Headers for load balancer
injectResponseHeaders:
- name: Authorization
  values:
  - claim: access_token
    prefix: "Bearer "
```
