### ISSUE TITLE
[Support]: Oauth2-proxy as proper ExtAuth solution

### ISSUE THREAD

**Issue by zeisich** [oauth2-proxy/oauth2-proxy#2832]
### OAuth2-Proxy Version

7.7.1

### Provider

oidc

### Current Behaviour of your Problem

I'm configuring oauth2-proxy as ext_auth server for Envoy Gateway. Unauthenticated calls to my backend service should trigger the OAuth flow and authenticated calls should pass through.

Apparently Envoy (and others) expect a `200` response code with an empty body when using the ext_authz protocol, whereas oauth2-proxy returns `202` on the `/oauth2/auth` endpoint.

### Configuration details or additional information

I'm first asking here in case there is another way of making these components properly talk to each other. Could possibly be a feature request to allow customization of the `/oauth2/auth` endpoint.
**Oauth2_proxy.cfg**
```
    skip_provider_button = "false"
    skip_jwt_bearer_tokens = "true"
    email_domains = ["*"]
    reverse_proxy = "true"
    cookie_name = "__Host-oauth2-proxy"
    cookie_csrf_per_request = "true"
    show_debug_on_error = true
    silence_ping_logging = true
```
**Oauth2_config_alpha**
```
server:
  BindAddress: '0.0.0.0:4180'
metricsServer:
  BindAddress: '0.0.0.0:44180'

providers:
  - id: azure
    provider: oidc
    name: Azure
    clientSecret: ${OAUTH2_PROXY_CLIENT_SECRET}
    clientID: <REDACTED>
    scope: "openid email profile offline_access"
    loginURL: "https://login.microsoftonline.com/<REDACTED>/oauth2/v2.0/authorize"
    redeemURL: "https://login.microsoftonline.com/<REDACTED>/oauth2/v2.0/token"
    oidcConfig:
      issuerURL: "https://login.microsoftonline.com/<REDACTED>/v2.0"
      skipDiscovery: true
      jwksURL: "https://login.microsoftonline.com/<REDACTED>/discovery/v2.0/keys"
      emailClaim: sub
      groupsClaim: roles
      audienceClaims:
        - aud
```
**SecurityPolicy**
```  yaml
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
    - Cookie
    - X-Auth-Request-User
    - X-Auth-Request-Groups
    - X-Auth-Request-Email
    - X-Auth-Request-Preferred-Username
    - X-Forwarded-Proto
    - X-Forwarded-Host
    - X-Forwarded-Uri
    - X-Auth-Request-Access-Token
    http:
      backendRefs:
      - group: ""
        kind: Service
        name: oauth2-proxy
        port: 80
      path: /oauth2/auth
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway1
```

**Comment by jjlakis** [comment]
Did you try setting `upstreams="static://200"` ?

**Comment by Moulick** [comment]
Setting upstream to `static://200` in solves this

**Comment by zeisich** [comment]
Thank you - I'm sure that I also had tried this at the time and it didn't work - maybe for other reasons.

I came back to this after I saw the new Entra/Azure provider functionality and now it works like a charm :)

**Comment by andriktr** [comment]
@Moulick maybe you can show your final config of oauth2 and envoy gtw securitypolicy? Trying to achieve similar behaviuor use oauth-proxy as external auth for envoy gateway specific http route.

**Comment by SlackingVeteran** [comment]
@andriktr I used following for oauth2-proxy alpha config
```
upstreamConfig:
      upstreams:
      - id: static-auth
        path: "/"
        static: true
        staticCode: 200
```

I also have following in oauth2-proxy config:
```
# Skipping login button page so that envoy can hit up sso.${module_domain_name} url and
# if response is 403 redirect to identity provider login page directly
skip_provider_button = "true"
redirect_url = "https://sso.yourdomain.com/oauth2/callback"
real_client_ip_header = "X-Forwarded-For"
```
Maybe there is a way but with extAuth I was not able to use provider button thing..

Following for Envoy Gateway so that redirect url can be set from requested URL before sending request to Oauth2-Proxy:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: oauth2-proxy-traffic-policy
  namespace: envoy-gateway
spec:
  headers:
    earlyRequestHeaders:
      set:
        - name: X-Auth-Request-Redirect
          value: https://%REQ(Host)%%REQ(:PATH)%
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
```

And SecurityPolicy example:
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: someapp-security-policy
  namespace: prod
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - Cookie
      - X-Auth-Request-User
      - X-Auth-Request-Groups
      - X-Auth-Request-Email
      - X-Auth-Request-Preferred-Username
      - X-Auth-Request-Redirect
    http:
      backendRefs:
        - group: ''
          kind: Service
          name: oauth2-proxy
          namespace: prod
          port: 80
      headersToBackend:
        - X-Auth-Request-User
        - X-Auth-Request-Groups
        - X-Auth-Request-Email
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: someapp-https-httproute
```

`X-Auth-Request-Redirect` in ClientTrafficPolicy is important bit to be able to redirect user properly

**Comment by andriktr** [comment]
@SlackingVeteran Thanks for info can you please clarify the purpose of:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: oauth2-proxy-traffic-policy
  namespace: envoy-gateway
spec:
  headers:
    earlyRequestHeaders:
      set:
        - name: X-Auth-Request-Redirect
          value: https://%REQ(Host)%%REQ(:PATH)%
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
```

**Comment by SlackingVeteran** [comment]
> [@SlackingVeteran](https://github.com/SlackingVeteran) Thanks for info can you please clarify the purpose of:
> 
> apiVersion: gateway.envoyproxy.io/v1alpha1
> kind: ClientTrafficPolicy
> metadata:
>   name: oauth2-proxy-traffic-policy
>   namespace: envoy-gateway
> spec:
>   headers:
>     earlyRequestHeaders:
>       set:
>         - name: X-Auth-Request-Redirect
>           value: https://%REQ(Host)%%REQ(:PATH)%
>   targetRef:
>     group: gateway.networking.k8s.io
>     kind: Gateway
>     name: envoy-gateway

Oauth2-Proxy usually needs a rd parameter set so that user is returned to original url after successful auth `?rd=$scheme://$host$request_uri`

I was unable to set that up with extAuth method so instead I ended up creating a custom header in envoy through ClientTrafficPolicy `X-Auth-Request-Redirect` which is passed to oauth2-proxy and oauth2-proxy uses that to redirect user successfully back to original service that had the security policy setup for.

**Comment by andriktr** [comment]
Huh I'm but confused with this :) As far as I undestand `ClientTrafficPolicy` attaches to the Gateway only so doesn't this mean that all traffic will be affected? In our case only one app uses oauth2-proxy, but the gateway itself serves a lot more different apps.  This was easy to setup using nginx-ingress as it just a couple of annotations, but in gateway api this looks bit more complecated. 
As alternative it's possible to use oidc form envoy gtw but I cannot find a way how for example configure `--allowed-group`  to restrict access for the app only to specific entra id group. 
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc-example
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: myapp
  oidc:
    provider:
      issuer: "https://accounts.google.com"
    clientID: "${CLIENT_ID}"
    clientSecret:
      name: "my-app-client-secret"
    redirectURL: "https://www.example.com:8443/myapp/oauth2/callback"
    logoutPath: "/myapp/logout"
```

Any thoughts ?

Thanks.

**Comment by SlackingVeteran** [comment]
Thats off topic from the main subject of this issue (extAuth).
If you want to use OIDC in EnvoyGateway and include google client id and secret idk why you are trying to use oauth2-proxy, that just defeats the purpose. Whole point of using oauth2-proxy is so that you dont have to use idp oidc creds everywhere. Just a single config in oauth2-proxy side and it takes care of talking to idp. You just have to configure reverse proxy to sending requests to oauth2-proxy for authentication

Re: ClientTrafficPolicy
Its adding headers to request early on when request reaches envoy. It will add the said header to all requests, the specific header we are adding is harmless but is essential for oauth2-proxy to work with the setup i provided because the SecurityPolicy will pass that extra added header to oauth2-proxy when performing extAuth and oauth2 can redirect users back to original url after successful auth with oidc. If user has a active session with oauth2-proxy i believe envoyProxy will itself redirect the user to original requested url, because it gets a 200 response

**Comment by andriktr** [comment]
My case is basically simple. Currently we have one application where we use oauth-proxy for authentication using azure entra id. At this moment we use nignx ingress for exposure and as I said it simple to configure using ingresses and annotations. But as nginx-ingress is no longer supported we moving all ingresses to envoy gtw api. So I'm just looking for a proper way to achieve the same using gateway as we have now in with ingress config.  And as I see now there is two ways to achieve this is to use extauth and oauth-proxy or use oidc directly from envoy (but this approach don't support `allowed groups` or at least I have not found how to).

**Comment by SlackingVeteran** [comment]
Okay then why dont you setup /auth endpoint to return 200 using the same oauth2-proxy example provided above and in security policy use /auth?allowed_groups=your-group-name

Ie:
```
upstreamConfig:
      upstreams:
      - id: static-auth
        path: "/auth"
        static: true
        staticCode: 200
```

Give it a try and if you run into issue, reply here and I can try my best to help with it. I have this running in prod for our services. And like you I moved away from ingress-nginx to envoy-gateway as well. So i dealt with similar pain points like you are running into. It took me a solid week to understand envoy gateway properly.

I havent done the /auth endpoint setup myself, i use / endpoint instead mostly because we do not have any services gated by groups atm, but might in the future

**Comment by zeisich** [comment]
@andriktr It is possible, you just have to declare another section that takes care of evaluating the JWT. Have a look [here](https://gateway.envoyproxy.io/docs/tasks/security/oidc/#azure-entra)

But if you already have oauth2-proxy setup, envoy gateway with extauth is relatively straight-forward. If ClientTrafficPolicy can only target Gateways, it doesn't really introduce authentication to the whole Gateway, that comes from the SecurityPolicy. That one I know to be attachable to a single HTTPRoute.

**Comment by andriktr** [comment]
So here is that i have tried:

Oauth-proxy config:
```yaml
    - --provider=entra-id
    - --azure-tenant=<tennant id>
    - --pass-access-token=false
    - --cookie-name=_proxycookie
    - --upstream="static://200"
    - --skip-provider-button=true 
    - --redirect-url=https://myapp.domain.com/oauth2/callback
    - --cookie-csrf-per-request=true
    - --cookie-csrf-expire=5m
    - --email-domain=*
    - --http-address=0.0.0.0:4180
    - --oidc-issuer-url=https://login.microsoftonline.com/tennant_id/v2.0
    - --user-id-claim=oid
    - --allowed-group=f9202fb3-755d-45aa-a175-c4113b3e5d58
    - --allowed-group=a4afa3ff-b450-4943-a492-c9d2232ef95b
    - --allowed-group=3e9d3367-469f-429d-88a5-54ec872da6c2
    - --oidc-groups-claim=groups
    - --scope=openid profile email User.Read
    - --cookie-refresh=10m
    - --cookie-expire=1h
    - --auth-logging-format="{{.Client}} - {{.RequestID}} - {{.Username}} [{{.Timestamp}}] [{{.Status}}]" 
    - --entra-id-federated-token-auth=true
    - --client-id=<client id>
    - --reverse-proxy=true
    - --set-xauthrequest=false
```

Security policy:

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: myapp-ext-auth
  namespace: myapp
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: myapp
  extAuth:
    failOpen: false
    headersToExtAuth:
      - Cookie
      - X-Auth-Request-User
      - X-Auth-Request-Groups
      - X-Auth-Request-Email
      - X-Auth-Request-Preferred-Username
      - X-Auth-Request-Redirect
    http:
      backendRefs:
        - group: ''
          kind: Service
          name: oauth2-proxy
          namespace: myapp
          port: 4180
      path: /oauth2/auth
      headersToBackend:
        - X-Auth-Request-User
        - X-Auth-Request-Groups
        - X-Auth-Request-Email
```

httpRoute

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: myapp
  namespace: myapp
spec:
  hostnames:
  - myapp.domain.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: experimental-envoy-gateway
    namespace: envoy-gateway-api
    sectionName: https-balticit
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: myapp
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```

Here is what is see in the logs of oauth:

```
[2026/02/20 11:01:58] [provider.go:55] Performing OIDC Discovery...
[2026/02/20 11:01:58] [proxy.go:77] mapping path "/" => static response 200
[2026/02/20 11:01:58] [oauthproxy.go:176] OAuthProxy configured for Microsoft Entra ID Client ID: <redacted>
[2026/02/20 11:01:58] [oauthproxy.go:182] Cookie settings: name:_proxycookie secure(https):true httponly:true expiry:1h0m0s domains: path:/ samesite: refresh:after 10m0s
[2026/02/20 11:02:38] [oauthproxy.go:1034] No valid authentication in request. Initiating login.
10.72.64.53 - 80db0275-03c1-471d-b5ef-160d956c9047 - - [2026/02/20 11:02:38] myapp.domain.com GET - "/oauth2/auth/" HTTP/1.1 "" 302 409 0.000
[2026/02/20 11:02:43] [oauthproxy.go:1034] No valid authentication in request. Initiating login.
10.72.64.53 - b7222193-dd30-4ced-aae3-225325a8666d - - [2026/02/20 11:02:43] myapp.domain.com GET - "/oauth2/auth/" HTTP/1.1 "" 302 409 0.000
[2026/02/20 11:03:45] [oauthproxy.go:1034] No valid authentication in request. Initiating login.
10.72.64.32 - 7a87f126-ec1b-4924-883b-4a4d241b4c64 - - [2026/02/20 11:03:45] myapp.domain.com GET - "/oauth2/auth/" HTTP/1.1 "" 302 409 0.000
[2026/02/20 11:12:56] [oauthproxy.go:1034] No valid authentication in request. Initiating login.
10.72.64.32 - f9face97-d2da-4950-b41f-2b47d80a5efc - - [2026/02/20 11:12:56] myapp.domain.com GET - "/oauth2/auth/" HTTP/1.1 "" 302 409 0.000
```

and logs from envoy gtw:
```
envoy-envoy-gateway-api-experimental-envoy-gateway-6b76716v4qns:envoy {":authority":"myapp.domain.com ,"bytes_received":0,"bytes_sent":409,"connection_termination_details":null,"downstream_local_address":"10.72.64.53:10443","downstream_remote_address":"10.180.221.112:51526","duration":1,"method":"GET","protocol":"HTTP/2","requested_server_name":"myapp.domain.com ,"response_code":302,"response_code_details":"ext_authz_denied","response_flags":"UAEX","route_name":"httproute/myapp/myapp/rule/0/match/0/my_app_domain_com","start_time":"2026-02-20T11:02:43.448Z","upstream_cluster":"httproute/helm-release-viewer/helm-release-viewer/rule/0","upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36","x-envoy-origin-path":"/","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.180.221.112","x-request-id":"4137d2a2-c63f-4055-8c79-7a7140b9a935"}
```

Still missing something...

**Comment by SlackingVeteran** [comment]
```
[2026/02/20 11:01:58] [proxy.go:77] mapping path "/" => static response 200
```

You have / mapped to static response 200. You want /oauth2/auth configured with static response 200 since thats the path you are using in your extAuth

Idk how do change path in non-alpha config or if path is required.. but in alpha config you can setup with:
```
upstreamConfig:
      upstreams:
      - id: static-auth
        path: "/oauth2/auth"
        static: true
        staticCode: 200
```
