### ISSUE TITLE
HTTP upgrade not always working

### ISSUE THREAD

**Issue by deanm0000** [oauth2-proxy/oauth2-proxy#2838]
### OAuth2-Proxy Version

./oauth2-proxy --version = oauth2-proxy undefined (built with go1.22.8) I believe 7.7.1

### Provider

azure

### Current Behaviour of your Problem

I'm running pg_tileserv and some of its links are being promoted to https but some aren't

### Configuration details or additional information

```toml
provider="azure"
client_id=...
client_secret=...
azure_tenant=...
oidc_issuer_url=...
cookie_secret=.
email_domains=...
https_address=":443"
http_address=":80"
force_https=true
tls_cert_file="/opt/go/bin/fullchain.pem"
tls_key_file="/opt/go/bin/privkey.pem"
upstreams="http://localhost:7800/"
skip_provider_button=true
```

It gives me a link to "http://mysite.com/public.parcels.json" and when I click it I get 2 network requests...

The first one has https://mysite.com/public.parcels.json with the actual response data

The second one has http://mysite.com/public.parcels.json which doesn't have any of the request data but it does have all the request headers including the cookie auth.

I'm not sure if that second one means that I'm leaking auth info in the clear.

Additionally, if I go into the map then there are webworkers which are trying to call urls such as http://mysite.com/public.parcels/3/1/3.pbf? which is just blocked by Edge as insecure mixed content 

```
 The page at 'blob:https://mysite.com/2cb41e78-746a-4e0e-9f21-1ed5ea67a1b0' was loaded over HTTPS, but requested an insecure resource 'http://mysite.com/public.parcels/3/1/2.pbf?'. This request has been blocked; the content must be served over HTTPS.
```

If I just put 'https://mysite.com/public.parcels/3/1/2.pbf' into the address bar then it is able to download that just fine.

I'm not sure what the right question to ask is except is there a way to make this work as expected?
