### ISSUE TITLE
[Support]: I am trying to add authentication for my kubernetes dashboard using traefik as my ingress controller in my amazon EKS cluster

### ISSUE THREAD

**Issue by Kshitij-Katiyar** [oauth2-proxy/oauth2-proxy#2856]
### OAuth2-Proxy Version

7.7.28

### Provider

keycloak-oidc

### Current Behaviour of your Problem

I read the documentation of the k8s dashboard https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#authorization-header. I need to pass the authorization header with the Bearer Prefix. I tried everything but the authorization header is not being added.  I have tried both the --pass and --set configuration settings but nothing happened. Can anyone help me where I am going wrong? 

### Configuration details or additional information

Oauth2-proxy setting: 
- --provider=keycloak-oidc
- --client-id=XXX
- --client-secret=XXX
- --redirect-url=https://k8s-dashboard.calyxpod.com/oauth2/callback
- --oidc-issuer-url=https://auth2.jtg.tools/realms/Test
- --ssl-insecure-skip-verify=true
- --reverse-proxy=true
- --cookie-secure=false
- --set-authorization-header=true
- --set-xauthrequest=true
- --skip-auth-strip-headers=false

k8s cluster setting:

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors
  namespace: kubernetes-dashboard
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      port: 80
    query: "/oauth2/sign_in?rd={url}"      

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-middleware
  namespace: kubernetes-dashboard
spec:
  forwardAuth:
    address: https://k8s-dashboard.calyxpod.com/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Groups
      - X-Auth-Request-Email
      - X-Auth-Request-Preferred-Username
      - X-Auth-Request-Access-Token

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: kubernetes-dashboard
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: calyxpod.com
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: kubernetes-dashboard 
spec:
  routes:
    - match: "Host(`k8s-dashboard.calyxpod.com`) && PathPrefix(`/oauth2/`)"
      kind: Rule
      services:
        - name: oauth2-proxy
          namespace: kubernetes-dashboard
          port: 80
      middlewares:
        - name: auth-headers        
    - match: Host(`k8s-dashboard.calyxpod.com`)
      kind: Rule
      middlewares:
        - name: oauth-errors
        - name: oauth2-proxy-middleware
      services:
        - name: kubernetes-dashboard-kong-proxy
          port: 443
          serversTransport: no-verify-tls

**Comment by cnhsn** [comment]
In your OAuth2-Proxy configuration, add these additional flags:
```
--pass-authorization-header=true
--set-authorization-header=true
--pass-access-token=true
```


Modify your Traefik middleware configuration for oauth2-proxy-middleware to include the Authorization header:
```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-middleware
  namespace: kubernetes-dashboard
spec:
  forwardAuth:
    address: https://k8s-dashboard.calyxpod.com/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - Authorization
      - X-Auth-Request-User
      - X-Auth-Request-Groups
      - X-Auth-Request-Email
      - X-Auth-Request-Preferred-Username
      - X-Auth-Request-Access-Token
```


Make sure your IngressRoute is properly configured to use HTTPS and includes all necessary middlewares in the correct order:
```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: kubernetes-dashboard
spec:
  routes:
    - match: "Host(`k8s-dashboard.calyxpod.com`) && PathPrefix(`/oauth2/`)"
      kind: Rule
      services:
        - name: oauth2-proxy
          port: 80
      middlewares:
        - name: auth-headers
    - match: Host(`k8s-dashboard.calyxpod.com`)
      kind: Rule
      middlewares:
        - name: auth-headers
        - name: oauth2-proxy-middleware
        - name: oauth-errors
      services:
        - name: kubernetes-dashboard-kong-proxy
          port: 443
```

After making these changes, restart your oauth2-proxy and Traefik pods
