### ISSUE TITLE
[Support]: OAuth2-Proxy as ForwardAuth in a Docker Authentik+OAuth2-Proxy+Nginx stack

### ISSUE THREAD

**Issue by Nicba1010** [oauth2-proxy/oauth2-proxy#2858]
### OAuth2-Proxy Version

v7.7.1-alpine

### Provider

oidc

### Current Behaviour of your Problem

Whenever I access prowl.arr.BASE_DOMAIN i get a 401 unauthorized.

If I access prowl.arr.BASE_DOMAIN/oauth2/ I get properly redirected to Authentik, it logs me in, sets the cookie, and everything works fine from then on.

So the main issue is I'm not getting redirected to Authentik automatically and I have no idea why.

### Configuration details or additional information

compose.yml
```yaml
version: '3.8'

services:
  traefik:
    image: traefik:v2
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.default.acme.dnschallenge=true"
      - "--certificatesresolvers.default.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.default.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.default.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt_cert_storage:/letsencrypt
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - prowlarr_config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowl.arr.${BASE_DOMAIN}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls.certresolver=default"
      - "traefik.http.routers.prowlarr.middlewares=prowlarr-auth@docker,prowlarr-auth-errors@docker"

      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    restart: always

  prowlarr-oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest-alpine
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_DEBUG=true
      - OAUTH2_PROXY_OIDC_ISSUER_URL=${OIDC_ISSUER_URL}
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      - OAUTH2_PROXY_CLIENT_ID=${OIDC_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OIDC_COOKIE_SECRET}
      - OAUTH2_PROXY_REDIRECT_URL=https://prowl.arr.${BASE_DOMAIN}/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_SCOPE=openid email profile
      - OAUTH2_PROXY_SKIP_CLAIMS_FROM_PROFILE_URL=true
      - OAUTH2_PROXY_UPSTREAMS=https://prowl.arr.${BASE_DOMAIN}
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr-oauth2-proxy.rule=Host(`prowl.arr.${BASE_DOMAIN}`) && PathPrefix(`/oauth2/`)"
      - "traefik.http.routers.prowlarr-oauth2-proxy.entrypoints=websecure"
      - "traefik.http.routers.prowlarr-oauth2-proxy.tls.certresolver=default"

      - "traefik.http.services.prowlarr-oauth2-proxy.loadbalancer.server.port=4180"

      - "traefik.http.middlewares.prowlarr-auth.forwardauth.address=https://prowl.arr.${BASE_DOMAIN}/oauth2/auth"
      - "traefik.http.middlewares.prowlarr-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.prowlarr-auth.forwardauth.authResponseHeaders=X-Auth-Request-Access-Token,Authorization,X-Auth-Request-Email,X-Auth-Request-User,Set-Cookie,X-Auth-User,X-Secret,X-Forwarded-User,X-WebAuth-User"

      - "traefik.http.middlewares.prowlarr-auth-errors.errors.status=401-403"
      - "traefik.http.middlewares.prowlarr-auth-errors.errors.service=prowlarr-oauth2-proxy@docker"
      - "traefik.http.middlewares.prowlarr-auth-errors.errors.query=/oauth2/sign_in?rd={url}"
    restart: always

volumes:
  traefik_letsencrypt_cert_storage:
    driver: local
  prowlarr_config:
    driver: local
```

.env
```env
BASE_DOMAIN=example.com
LETSENCRYPT_EMAIL=domains@example.com

CLOUDFLARE_API_TOKEN=ABCD...

OIDC_ISSUER_URL=https://authentik.example2.com/application/o/prowlarr/
OIDC_CLIENT_ID=ABCD...
OIDC_CLIENT_SECRET=ABCD...
OIDC_COOKIE_SECRET=ABCD...
```

### Steps To Reproduce

1. Configure the .env with your domains, cd token, and oidc data
2. compose up
