### ISSUE TITLE
[Bug]: Connection refused while performing OIDC dicscovery when running oauth2-proxy as a sidecar on cloud run and using Okta as an identity provider

### ISSUE THREAD

**Issue by benoitgoujon** [oauth2-proxy/oauth2-proxy#2870]
### OAuth2-Proxy Version

v7.7.1

### Provider

oidc

### Expected Behaviour

Get the OIDC Configuration from the default endpoint: https://dev-99735729.okta.com/oauth2/default/.well-known/openid-configuration

### Current Behaviour

When running oauth2-proxy on cloud run, the OIDC Discovery step fails with this error:

```
[2024/11/06 21:25:39] [main.go:59] ERROR: Failed to initialise OAuth2 
Proxy: error initialising provider: could not create provider data: 
error building OIDC ProviderVerifier: could not get verifier builder: 
error while discovery OIDC configuration: failed to discover OIDC 
configuration: error performing request: Get 
"https://dev-99735729.okta.com/oauth2/default/.well-known/openid-configuration":
 dial tcp: lookup [dev-99735729.okta.com](http://dev-99735729.okta.com/) on [::1]:53: read udp 
[::1]:40751->[::1]:53: read: connection refused
```

When running locally, it's ok. It only fails on cloud run.

### Steps To Reproduce

The set-up is similar to the one described in [this article](https://medium.com/google-cloud/deploying-oauth2-proxy-as-a-cloud-run-sidecar-container-a06172d14e1f)

I used all default network settings of cloud run.

In terms of oauth2-proxy config, here is my config file:

```toml
http_address = "0.0.0.0:4180"
https_address = ":443"
provider = "oidc"
redirect_url = "https://cocktail-mixer-119304981870.europe-west1.run.app/oauth2/callback"
oidc_issuer_url = "https://dev-99735729.okta.com/oauth2/default" # authorization server issuer
upstreams = [
    "http://127.0.0.1:8080/"
]
email_domains = [
    "*"
]
client_id = ""
client_secret = ""
pass_access_token = true

cookie_name = "_oauth2_proxy"
cookie_secret = ""
cookie_expire = "168h"
cookie_secure = true
cookie_httponly = true
skip_provider_button = true
```

My config on cloud run is the one below:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: <image URI>
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["<urls>""]'
  labels:
    cloud.googleapis.com/location: europe-west1
  name: <name>
  namespace: '119304981870'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        client.knative.dev/user-image: <image URI>
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 412.0.0
        run.googleapis.com/sessionAffinity: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/container-dependencies: '{"hello":["oauth-proxy"]}'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 120
      volumes:
      - name: secret-1
        secret:
          secretName: oauth2_config
          items:
          - key: latest
            path: oauth2_config.cfg
      containers:
      - name: oauth-proxy
        image: europe-west1-docker.pkg.dev/.../oauth-proxy:latest-amd64
        command:
        - /bin/oauth2-proxy
        args:
        - --config=/etc/oauth2_config.cfg
        ports:
        - name: http1
          containerPort: 4180
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: secret-1
          mountPath: /etc
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 4180
      - name: hello
        image: <image URI>
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: <sa name>
      timeoutSeconds: 900
  traffic:
  - latestRevision: true
    percent: 100

```
