### ISSUE TITLE
[Feature]: allowed_groups as header

### ISSUE THREAD

**Issue by shotor** [oauth2-proxy/oauth2-proxy#2875]
### Motivation

I'm using `traefik` as my reverse proxy with its `forwardAuth` middleware to authenticate with `keycloak` through `oauth2-proxy`.

It works, but I have to define separate middleware configurations for each app/service:

```yml
http:
  middlewares:
    oauth:
        forwardAuth:
            address: "http://oauth2-proxy-external:4180/oauth2/auth"
    oauth-is-admin:
        forwardAuth:
            address: "http://oauth2-proxy-external:4180/oauth2/auth?allowed_groups=admin"
    oauth-has-access-to-x:
        forwardAuth:
            address: "http://oauth2-proxy-external:4180/oauth2/auth?allowed_groups=access-x"
# ...etc
```

Not great. And unfortunately `traefik` doesn't offer much parameterization options in this middleware. The out-of-the-box solution is to override the forward auth address in each container:

```yml
container1:
  - traefik.http.routers.app-1.middlewares.oauth.forwardAuth.address=http://oauth2-proxy-external:4180/oauth2/auth?allowed_groups=admin"
  - traefik.http.routers.app-1.middlewares=oauth@file

container2:
  - traefik.http.routers.app-2.middlewares.oauth.forwardAuth.address=http://oauth2-proxy-external:4180/oauth2/auth?allowed_groups=access-x"
  - traefik.http.routers.app-2.middlewares=oauth@file
```

Not great, because of the repetition for each container.

The only other solution I could come up with is to have a separate service or custom traefik plugin that allows me to set as a header (service) or variable (plugin) in each container which groups are allowed. It then matches with the header X-`Auth-Request-Groups` header provided by oauth2-proxy.

```yml
container1:
  - "traefik.http.routers.app-1.middlewares.headers.addAllowedGroups.X-Allowed-Groups=admin"
  -  traefik.http.routers.app-1.middlewares=addAllowedGroups,oauth@file,groups-check-service@file
container2: # plugin approach
  - "traefik.http.routers.app-2middlewares.oauth-plugin.groups=x-access"
  -  traefik.http.routers.app-2.middlewares=oauth@file,groups-check-plugin@file
```

Not great, requires custom code and between 1 and 2 new middlewares.

### Possible solution

My preferred solution would be to add an optional header parameter to `/auth`: `X-Allowed-Groups` and match on groups in `oauth2-proxy`. In the same way it's now being done with the query parameter `allowed_groups`.

Relevant code sections: 

- https://github.com/oauth2-proxy/oauth2-proxy/blob/ef8ba75987c8f4f441d8044a5853922929d3bd83/oauthproxy.go#L1208
- https://github.com/oauth2-proxy/oauth2-proxy/blob/ef8ba75987c8f4f441d8044a5853922929d3bd83/oauthproxy.go#L1166

It could be added as a separate function or `extractAllowedEntities` could be modified to also grab parameters from headers.

### Provider

None
