### ISSUE TITLE
[Bug]: Initial Redirect from IDP is to the main Oauth2 Proxy Ingress - Not the originating site

### ISSUE THREAD

**Issue by jseiser** [oauth2-proxy/oauth2-proxy#2883]
### OAuth2-Proxy Version

7.1.1

### Provider

oidc

### Expected Behaviour

1. https://am-01-dev-ops.my.tld/#/alerts
2. Redirect to Okta
3. Auth
4. Sent to https://am-01-dev-ops.my.tld/#/alerts

### Current Behaviour

1. https://am-01-dev-ops.my.tld/#/alerts
2. Redirect to Okta
3. Auth
4. Sent to the ingress of Oauth2 Proxy
5. It shows 403 Forbidden and Login Failed: Unable to find a valid CSRF token. Please try again.
6. If I click Sign In Im sent to https://gatekeeper-01-dev.my.tld/ with a 404 page not found
7. If I then re-enter the apps URL, im  redirected to my app

### Steps To Reproduce

1. EKS w/oauth2 proxy installed via helm

```
config:
  clientID: "${clientid}"
  clientSecret: "${clientsecret}"
  cookieSecret: "${cookiesecret}"
  cookieName: "tapps"
extraArgs:
  email-domain: "*"
  scope: "openid email profile offline_access"
  reverse-proxy: true
  cookie-domain: .${base_domain}
  whitelist-domain: .${base_domain}
  provider: oidc
  oidc-issuer-url: "https://auth.my.tld"
  pass-access-token: true
  pass-authorization-header: true
  set-authorization-header: true
  skip-provider-button: true
  set-xauthrequest: true
  cookie-samesite: lax
  standard-logging: true
  auth-logging: true
  request-logging: true
  silence-ping-logging: true
  cookie-expire: 5m
ingress:
  enabled: true
  className: "nginx-internal-trex"
  hosts:
    - gatekeeper-${cluster_number}-${env}.${base_domain}
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    cert-manager.io/cluster-issuer: cert-manager-r53-prod
  tls:
    - secretName: gatekeeper-${cluster_number}-${env}.${base_domain}-tls
      hosts:
        - gatekeeper-${cluster_number}-${env}.${base_domain}
sessionStorage:
  type: redis

redis:
  enabled: true

metrics:
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
```

### Configuration details or additional information

```
10.4.242.108 - dfca49bc4fc8c3068fc21a2bf35aa7d0 - justin@myemail.com [2024/12/10 18:19:02] [AuthSuccess] Authenticated via OAuth2: Session{email:justin@myemail.com user:00ufd5kaiKKPoH4yt4h6 PreferredUsername:justin@myemail.com token:true id_token:true created:2024-12-10 18:19:02.131808045 +0000 UTC m=+3310.438505309 expires:2024-12-10 19:19:01.76743931 +0000 UTC m=+6910.074136560}
10.4.242.108 - dfca49bc4fc8c3068fc21a2bf35aa7d0 - - [2024/12/10 18:19:01] gatekeeper-01-dev.my.tld GET - "/oauth2/callback?code=_Je6WKf0TX5GYpZ2I2Oi6v7OJZ3IUBj210jAAwzI2ds&state=Q7jYh3EfOL-1PScwg8fliM0Hp3XftA6r69KkMPhP4Yo%3A%2F" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0" 302 24 0.932
10.4.242.108 - 0a558018db749282645e13a67ad84357 - justin@myemail.com [2024/12/10 18:19:02] gatekeeper-01-dev.my.tld GET - "/" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0" 404 19 0.001
```

**Comment by jseiser** [comment]
The ingress for my app has this problem, either way I configure it.

Like this, 
```
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
      cert-manager.io/cluster-issuer: cert-manager-r53-qa
      nginx.ingress.kubernetes.io/auth-response-headers: Authorization
      nginx.ingress.kubernetes.io/auth-signin: https://gatekeeper-01-dev.my.tld/oauth2/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url: https://gatekeeper-01-dev.my.tld/oauth2/auth
```

or adding this
```
      nginx.ingress.kubernetes.io/configuration-snippet: |
        auth_request_set $name_upstream_1 $upstream_cookie_tapps;

        access_by_lua_block {
          if ngx.var.name_upstream_1 ~= "" then
            ngx.header["Set-Cookie"] = "tapps=" .. ngx.var.name_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
          end
        }
```
