### ISSUE TITLE
[Bug]: OIDC with Firebase (GCP Identity) and option --allowed-group

### ISSUE THREAD

**Issue by glb-cblin** [oauth2-proxy/oauth2-proxy#2891]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Expected Behaviour

Correctly validating the JWT groups claim

### Current Behaviour

[AuthFailure] Invalid authentication via OAuth2: unauthorized

### Steps To Reproduce

Given this k8s spec (with some values hidden for security reasons), I managed to access my underlying container (deployed at localhost:8888)

```
        - image: bitnami/oauth2-proxy:7.6.0
          # the image specifies upstream and http-adress params in the Dockerfile, we can not use env var to overide them :(
          # see https://github.com/bitnami/containers/blob/main/bitnami/oauth2-proxy/7/debian-11/Dockerfile
          command:
            - "oauth2-proxy"
            - "--upstream=http://localhost:8888/"
            - "--http-address=0.0.0.0:4180"
          ports:
            - name: http1
              containerPort: 4180
          env:
            - name: OAUTH2_PROXY_PROXY_PREFIX
              value: '/doc/oauth2'
            - name: OAUTH2_PROXY_PROVIDER_DISPLAY_NAME
              value: 'SSO'
            - name: OAUTH2_PROXY_PROVIDER
              value: 'oidc' 
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: 'https://accounts.google.com'
            - name: OAUTH2_PROXY_CLIENT_ID 
              value: 'xxxx'
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: doc-oauth-client-secret
            - name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
              value: 'false'
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: 'xxx.com'
            - name: OAUTH2_PROXY_SCOPE
              value: 'openid profile email'
            # - name: OAUTH2_PROXY_ALLOWED_GROUPS
            #   value: 'groupe-de-test'
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: https://dev.xxx.com/doc/oauth2/callback
            - name: OAUTH2_PROXY_COOKIE_SECRET 
              value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

If I uncomment the OAUTH2_PROXY_ALLOWED_GROUPS, I have the following error `[AuthFailure] Invalid authentication via OAuth2: unauthorized`

![image](https://github.com/user-attachments/assets/d5e86ad1-e822-437e-9d05-e6df7177d441)

Given that when I do the OAuth flow on my side I have these claims

![image](https://github.com/user-attachments/assets/b00bc412-35d7-47c8-86e1-c14d9873b2cf)

I'd expect that the 'groups' claims would work

### Possible Solutions

If the problem is due to the groups claims, please indicate in the log message what is the exact problem
