### ISSUE TITLE
[Support]: KeyCloak is bypassed on a fresh session

### ISSUE THREAD

**Issue by dimitrios-git** [oauth2-proxy/oauth2-proxy#2908]
### OAuth2-Proxy Version

latest

### Provider

keycloak-oidc

### Current Behaviour of your Problem

When I restrict a user from accessing a client in KeyCloak, the restriction is bypassed and the user can still access the client on a new private session, until they log in to KeyCloak in that session or they log in to another KeyCloak client. I am not entirely sure what's going on.

Example 1:
I open a new private session and visit my client at https://app.domain.com, I am redirected to OAuth2 Proxy, I log in and I can access the client where access is supposed to be denied.

Example 2:
I open a new private session and visit https://auth.domain.com/auth/realms/company/account to access my KeyCloak profile. Then I access my client at https://app.domain.com and access is denied as expected.

Example 3:
I open a new private session and visit https://app2.domain.com where app2 does not use OAuth2 Proxy and I log in. Then I visit https://app.domain.com and access is denied as expected.

Example 4:
I open a new private session, and I visit https://app.domain.com/oauth2/sign_in and access is denied as expected.

Why is this happening in example 1? I would expect it work just like example 4.

### Configuration details or additional information

OAuth2 Proxy runs in a container, here's the compose file:
```
secrets: {}
services:
    proxy:
        environment:
            OAUTH2_PROXY_ALLOWED_ROLE: ansible_project/app:restricted_access
            OAUTH2_PROXY_CLIENT_ID: ansible_project/app
            OAUTH2_PROXY_CLIENT_SECRET: Bx9emDn8dfadfadghh3Gwf5gsfgswGFSGM
            OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: 5m
            OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: 'true'
            OAUTH2_PROXY_COOKIE_EXPIRE: 2h0m0s
            OAUTH2_PROXY_COOKIE_HTTPONLY: 'true'
            OAUTH2_PROXY_COOKIE_NAME: __Host-oauth2_proxy
            OAUTH2_PROXY_COOKIE_REFRESH: '0'
            OAUTH2_PROXY_COOKIE_SAMESITE: lax
            OAUTH2_PROXY_COOKIE_SECRET: LO4rdfaf90mCfadfaghgkjhDDDDddKV
            OAUTH2_PROXY_COOKIE_SECURE: 'true'
            OAUTH2_PROXY_EMAIL_DOMAINS: '*'
            OAUTH2_PROXY_HTTP_ADDRESS: :8080
            OAUTH2_PROXY_OIDC_ISSUER_URL: https://auth.domain.com/auth/realms/company
            OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'false'
            OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: 'false'
            OAUTH2_PROXY_PASS_USER_HEADERS: 'true'
            OAUTH2_PROXY_PROVIDER: keycloak-oidc
            OAUTH2_PROXY_PROXY_PREFIX: /oauth2
            OAUTH2_PROXY_REDIRECT_URL: https://app.domain.com/oauth2/callback
            OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis
            OAUTH2_PROXY_REVERSE_PROXY: 'true'
            OAUTH2_PROXY_SESSION_STORE_TYPE: redis
            OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: 'true'
            OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
            OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: 'false'
            OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'
        image: quay.io/oauth2-proxy/oauth2-proxy
        ports:
        - 127.0.0.1:20001:8080/tcp
        restart: unless-stopped
    redis:
        image: redis
        restart: unless-stopped
```

My Nginx:
```
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name app.domain.com;

  # Fix upstream sent too big header while reading response header from upstream
  proxy_busy_buffers_size   512k;
  proxy_buffers   4 512k;
  proxy_buffer_size   256k;

  ssl_certificate /var/lib/dehydrated/certs/app.domain.com/fullchain.pem;
  ssl_certificate_key /var/lib/dehydrated/certs/app.domain.com/privkey.pem;
  #ssl_stapling_file /var/lib/dehydrated/certs/app.domain.com/ocsp.der;


  include /etc/nginx/snippets/https;
  include /etc/nginx/snippets/global;

  location /oauth2 {
    proxy_pass http://127.0.0.1:20001;
    proxy_read_timeout 600;
    proxy_connect_timeout 600;
    proxy_http_version 1.1;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Auth-Request-Redirect $request_uri;
    proxy_hide_header Strict-Transport-Security;
  }

  location / {
    # send request to oauth2 proxy to check for authentication
    auth_request /oauth2/auth;
    # redirect to login if authentication fails
    error_page 401 = /oauth2/start;
    # pass information about user via headers to backend
    auth_request_set $user $upstream_http_x_auth_request_user;
    proxy_set_header X-User $user;
    fastcgi_param X-User $user;
    auth_request_set $groups $upstream_http_x_auth_request_groups;
    proxy_set_header X-Groups $groups;
    fastcgi_param X-Groups $groups;
    auth_request_set $email $upstream_http_x_auth_request_email;
    proxy_set_header X-Email $email;
    fastcgi_param X-Email $email;
    auth_request_set $preferred_username $upstream_http_x_auth_request_preferred_username;
    proxy_set_header X-Preferred-Username $preferred_username;
    fastcgi_param X-Preferred-Username $preferred_username;

    proxy_pass http://localhost13004;
    proxy_read_timeout 600;
    proxy_connect_timeout 600;
    proxy_http_version 1.1;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_hide_header Strict-Transport-Security;
  }

}
```
