### ISSUE TITLE
[Support]: Allow login for multiple domains?

### ISSUE THREAD

**Issue by ImDevinC** [oauth2-proxy/oauth2-proxy#2926]
### OAuth2-Proxy Version

7.9.2

### Provider

oidc

### Current Behaviour of your Problem

I have two domains, one external (`*.mydomain.com`) and one internal (`*.myhouse.home`). The internal domain only serves http traffic, while the external one is covered by a certificate. I setup `https://oauth.mydomain.com` to serve as my proxy, which works great for other sites on `*.mydomain.com`.
However I can't seem to get it to cover `*.myhouse.home`. I've tried setting `whitelist_cookies` to share the cookie, but that doesn't seem to work. Is there any way to get this to work using a single instance of `oauth2-proxy` at the https domain?

### Configuration details or additional information

Using helm chart, here is my values.yaml
```yaml
oauth2-proxy:
  ingress:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/ingress-hostname-source: annotations-only
    enabled: true
    hosts:
      - oauth.mydomain.com
    tls:
      - hosts:
        - oauth.mydomain.com
        secretName: oauth2-proxy-tls
  proxyVarsAsSecrets: false
  extraVolumes:
    - name: config
      secret:
        defaultMode: 420
        secretName: oauth2-proxy-config
  extraVolumeMounts:
    - name: config
      mountPath: /opt/oauth2-proxy
      readOnly: true
  extraArgs:
    config: /opt/oauth2-proxy/config.cfg
  config:
    configFile:
      cookie_secret="secretvalue"
      cookie_domains=[".mydomain.com", ".myhouse.home"]
      whitelist_domains=[".mydomain.com", ".myhouse.home:*"]
      # only users with this domain will be let in
      email_domains=["*"]
      client_id="clientid"
      client_secret="clientsecret"
      cookie_secure="false"
      redirect_url="https://oauth.mydomain.com/oauth2/callback"
      upstreams = [ "file:///dev/null" ]
      set_xauthrequest = true
      provider="oidc"
      oidc_issuer_url="https://login.mydomain.com"
```
My OIDC issuer is pocket-id if that matters, but I don't think it does

**Comment by xakaitetoia** [comment]
So seems this isn't supported with 1 oauth2 instance but multiple as mentioned [here](https://github.com/oauth2-proxy/oauth2-proxy/issues/1944#issuecomment-1361049231). 
In our case (we have 2 external domains though) as we also have cert-manager, in order to resolve this issue (with 1 oauth2-proxy instance) we had to:

- keep the cookie-domains/whitelist-domains as you have them
- remove the redirect-url value from your oauth2-proxy `redirect_url="https://oauth.mydomain.com/oauth2/callback"` completely because of the next changes.
- Add an extra ingress object on helm chart to support the other domain, meaning you will have 2 ingresses pointing to same oauth2-proxy. 1 ingress per domain as we use different cluster issuer (which is needed to grab the correct certs). Example snippet below:
```yaml
    extraObjects:

      - apiVersion: onepassword.com/v1
        kind: OnePasswordItem
        metadata:
          name: myhouse-oauth2-secrets
          namespace: oauth2-proxy
        spec:
          itemPath: "vaults/test-vault/myhouse-oauth2-secrets"

      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          annotations:
            acme.cert-manager.io/http01-edit-in-place: "true"
            cert-manager.io/cluster-issuer: myhouse-clusterissuer
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          name: oauth2-proxy-myhouse
          namespace: oauth2-proxy
        spec:
          ingressClassName: nginx
          rules:
          - host: oauth.myhouse.home
            http:
              paths:
              - backend:
                  service:
                    name: oauth2-proxy
                    port:
                      number: 80
                path: /
                pathType: ImplementationSpecific
          tls:
          - hosts:
            - oauth.myhouse.home
            secretName: myhouse-tls
```
used 1password secret as an example, can be anything you have
- On the SP side (we are using jumpcloud) so in your case i guess `pocket-id`, configure and extra redirect URI so you should have 2 in total:
  -  https://oauth.mydomain.com/oauth2/callback
  - https://oauth.myhouse.home/oauth2/callback


Maybe something like that can work for you
