### ISSUE TITLE
[Documentation]: doc for the upstream config in the alpha configuration is incorrect

### ISSUE THREAD

**Issue by cjvirtucio87** [oauth2-proxy/oauth2-proxy#2962]
### OAuth2-Proxy Version

v7.8.0

### Provider

keycloak-oidc

### Expected Behaviour

[Doc](https://oauth2-proxy.github.io/oauth2-proxy/configuration/alpha-config/#upstream) currently says upstream paths can be configured like this:

```txt
^/foo/.*$
```

and that it would match:

```txt
http://subdomain.com/foo/bar/baz
```

### Current Behaviour

Config would result in a 404. Instead, config should actually be:

```txt
/foo/{path:.*}
```

### Steps To Reproduce

Configure your alpha config YAML to something like this:

```yaml
          upstreamConfig:
            upstreams:
              - id: media-server
                path: "^/files/.*$"
                uri: "http://localhost:8080"
```

Get an access token from your IdP and send a request:

```console
curl --header "Authorization: Bearer ${ACCESS_TOKEN}" 'http://127.0.0.1:8080/files/media/frigate/clips/livingroom_window-1739829746.571091-mmkry2-clean.png'
```

### Possible Solutions

Doc just needs an update to match actual usage of [gorilla/mux](https://github.com/gorilla/mux?tab=readme-ov-file#registered-urls), since that's what's being used as the [underlying router](https://github.com/oauth2-proxy/oauth2-proxy/blob/80189a99737c4576ed547d886557beb95301633b/pkg/upstream/proxy.go#L106-L110).
