### ISSUE TITLE
[Support]: JWT Token Validation Fails with Azure Bot Token Despite Correct Configuration

### ISSUE THREAD

**Issue by RafaMunoz** [oauth2-proxy/oauth2-proxy#2981]
### OAuth2-Proxy Version

latest

### Provider

oidc

### Current Behaviour of your Problem

I'm trying to validate a JWT token generated by Azure Bot using oauth2-proxy, but it keeps failing with the error no valid bearer token found in authorization header. I believe there might be a bug in the code or a misconfiguration on my end.

## Configuration
I'm running oauth2-proxy via Docker with the following configuration:

``` yaml
image: quay.io/oauth2-proxy/oauth2-proxy:latest
environment:
  OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
  OAUTH2_PROXY_ERRORS_TO_INFO_LOG: "true"
  OAUTH2_PROXY_PROVIDER: "oidc"
  OAUTH2_PROXY_OIDC_ISSUER_URL: "https://api.botframework.com"
  OAUTH2_PROXY_CLIENT_ID: "1b4d5f59-ab61-4300-b92b-8c7ca7bf294d"
  OAUTH2_PROXY_CLIENT_SECRET: "xxxxxxxxxxxxxxxxxxxxx"
  OAUTH2_PROXY_OIDC_JWKS_URL: "https://login.botframework.com/v1/.well-known/keys"
  OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: "true"
  OAUTH2_PROXY_OIDC_SCOPE: "openid profile"
  OAUTH2_PROXY_COOKIE_SECRET: "wJk2gY5L9W7TmCxpq8H3kVzXMVQeFsdP"
  OAUTH2_PROXY_COOKIE_SECURE: "false"
  OAUTH2_PROXY_UPSTREAMS: "http://http-echo:8888/"
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
```

## JWT Token
The JWT token I'm using is:

```
eyJhbGciOiJSUzI1NiIsImtpZCI6IlUzMGNQemxYVHpjS3M5aVc0emo4cHhXSXdtcyIsIng1dCI6IlUzMGNQemxYVHpjS3M5aVc0emo4cHhXSXdtcyIsInR5cCI6IkpXVCJ9.ew0KICAic2VydmljZXVybCI6ICJodHRwczovL3NtYmEudHJhZmZpY21hbmFnZXIubmV0L2VtZWEvNDBlZDBjYzUtYzkwNi00YjEyLTk5YmEtMDQ3YTZkMmExOWFiLyIsDQogICJuYmYiOiAxNzQxMzcxMzczLA0KICAiZXhwIjogMTc0MTM3NDk3MywNCiAgImlzcyI6ICJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwNCiAgImF1ZCI6ICIxYjRkNWY1OS1hYjYxLTQzMDAtYjkyYi04YzdjYTdiZjI5NGQiDQp9.TktY0v5DCyrIp07LL3A6Pns7_R-U21irSbt2altCSIqzusGsDYUKx6cKbt50_jOY62ztVBnqs16ANg-ISyHhQhbkNfBOIlSyhAiml3FNYtIFOD7sZ4XH955znDwGLBIbbcjflXlFdN98thV0Bsn0Ucq1u1SkdVXumP-gdNgYTZ5HkPppbcYY3eF8sXZZHj83Gvug0hKv6mWXhoubSTILVug73YV45DiUopwVRG2HdEyipe3cqhg_XqKpojbXAfA0X8mPnCFUSg5FKk2w3so0kR4TSjxRqA3Yy6VuGiPEKeQd5DmbPfFU8Wmaz5I4T1TFrnaxqIgL0aApzjPZlz4Oyg
```
## Error Logs:
The error returned in logs by **oauth2-proxy** is:
```
2025-03-07 20:13:32 [2025/03/07 19:13:32] [options.go:77] WARNING: no explicit redirect URL: redirects will default to insecure HTTP
2025-03-07 20:13:32 [2025/03/07 19:13:32] [proxy.go:89] mapping path "/" => upstream "http://downloads-http-echo-1:8888/"
2025-03-07 20:13:32 [2025/03/07 19:13:32] [oauthproxy.go:162] Skipping JWT tokens from configured OIDC issuer: "https://api.botframework.com"
2025-03-07 20:13:32 [2025/03/07 19:13:32] [oauthproxy.go:172] OAuthProxy configured for OpenID Connect Client ID: 1b4d5f59-ab61-4300-b92b-8c7ca7bf294d
2025-03-07 20:13:32 [2025/03/07 19:13:32] [oauthproxy.go:178] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite: refresh:disabled
2025-03-07 20:13:34 [2025/03/07 19:13:34] [jwt_session.go:51] Error retrieving session from token in Authorization header: no valid bearer token found in authorization header
2025-03-07 20:13:34 [2025/03/07 19:13:34] [oauthproxy.go:1026] No valid authentication in request. Initiating login.
2025-03-07 20:13:34 172.20.0.1:35298 - 091ae7d8-af97-4891-a53b-1e50f4f46797 - - [2025/03/07 19:13:34] localhost:4180 GET - "/" HTTP/1.1 "PostmanRuntime/7.43.0" 403 8493 0.000
```

## Manual Validation:
When I manually validate the token using the public keys from **https://login.botframework.com/v1/.well-known/keys**, the token is valid.

## Request
The request I'm making is:

``` bash
curl --location 'http://localhost:4180' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlUzMGNQe......
```

## Questions
1. Is there a way to enable debug logging in oauth2-proxy to see all the requests and validations it performs?

2. Could there be a bug in the JWT validation logic, or am I missing something in my configuration?

## Additional Context

- The iss in the JWT token is https://api.botframework.com, but the OIDC configuration is located at https://login.botframework.com/v1/.well-known/openid-configuration.
- I have already set OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: "true" to avoid automatic discovery.
- The OAUTH2_PROXY_OIDC_JWKS_URL is correctly set to https://login.botframework.com/v1/.well-known/keys.

### Configuration details or additional information

``` yaml
services:

  oauth2proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - '4180:4180'
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_ERRORS_TO_INFO_LOG: "true"
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://api.botframework.com"     
      OAUTH2_PROXY_CLIENT_ID: "1b4d5f59-ab61-4300-b92b-8c7ca7bf294d"
      OAUTH2_PROXY_CLIENT_SECRET: "xxxxxxxxxxxxxxxxxxxxx"
      OAUTH2_PROXY_OIDC_JWKS_URL: "https://login.botframework.com/v1/.well-known/keys"
      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: "true"
      OAUTH2_PROXY_OIDC_SCOPE: "openid profile"
      OAUTH2_PROXY_COOKIE_SECRET: "wJk2gY5L9W7TmCxpq8H3kVzXMVQeFsdP"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_UPSTREAMS: "http://http-echo:8888/"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
  
  http-echo:
    image: mendhak/http-https-echo:35
    ports:
      - '8888:8888'
    environment:
        - HTTP_PORT=8888
        - HTTPS_PORT=9999
        - PROMETHEUS_ENABLED=true
        - PROMETHEUS_METRICS_PATH=/metrics
        - PROMETHEUS_WITH_PATH=false
        - PROMETHEUS_WITH_METHOD=true
        - PROMETHEUS_WITH_STATUS=true
        - PROMETHEUS_METRIC_TYPE=summary
```

### Steps To Reproduce

1. Run a docker compose
2. Send a request to oauth2-proxy with the token in the Authorization header.
3. Observe the error logs.
