### ISSUE TITLE
[Bug]: Cipher Suite not applied

### ISSUE THREAD

**Issue by JonathanMbt** [oauth2-proxy/oauth2-proxy#2985]
### OAuth2-Proxy Version

7.8.0

### Provider

oidc

### Expected Behaviour

When the environment variable `OAUTH2_PROXY_TLS_CIPHER_SUITES` or the cli argument `--tls-cipher-suite` is specified with a cipher suite, only that cipher suite should be available. 

### Current Behaviour

When the environment variable `OAUTH2_PROXY_TLS_CIPHER_SUITES` or the cli argument `--tls-cipher-suite` is specified with a cipher suite, this cipher suite is not applied, and the default suite is used. 
We used the project https://github.com/testssl/testssl.sh to check which cipher suite were available to be used. 

### Steps To Reproduce

Start the following compose:
```
  oauth2-proxy-service:
    image: registrybc.gemalto.com:8000/bc/oauth2-proxy-v7.8.0-alpine:3.0-SNAPSHOT
    networks:
      - bms3cluster
    ports:
      - "8501:8501"
    command: --https-address 0.0.0.0:8501 --tls-min-version TLS1.2
    environment:
      - TZ=${DEFAULT_TIMEZONE:-Europe/Madrid}
      - OAUTH2_PROXY_FORCE_HTTPS=true
      - OAUTH2_PROXY_TLS_CERT_FILE=/etc/pki/tls/certs/oauth2-proxy-service.crt
      - OAUTH2_PROXY_TLS_KEY_FILE=/etc/pki/tls/certs/oauth2-proxy-service.key
      - OAUTH2_PROXY_TLS_CIPHER_SUITES=TLS_AES_256_GCM_SHA384
      - OAUTH2_PROXY_UPSTREAMS=REDACTED
      - OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=REDACTED
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_PROVIDER_CA_FILE=/etc/pki/tls/certs/ca.crt
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      - OAUTH2_PROXY_OIDC_ISSUER_URL=REDACTED
      - OAUTH2_PROXY_CLIENT_ID=REDACTED
      - OAUTH2_PROXY_CLIENT_SECRET=REDACTED
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_NAME=__Secure_oauth2_proxy
      - OAUTH2_PROXY_SESSION_COOKIE_MINIMAL=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_REDIRECT_URL=REDACTED
      - OAUTH2_PROXY_COOKIE_SECRET=REDACTED
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true
      - OAUTH2_PROXY_COOKIE_EXPIRE=1h0m0s
``` 

Check the cipher suites.
