### ISSUE TITLE
[Support]: How to configure to work with Haproxy Ingress?

### ISSUE THREAD

**Issue by sarg3nt** [oauth2-proxy/oauth2-proxy#2988]
### OAuth2-Proxy Version

7.12.5

### Provider

entra-id

### Current Behaviour of your Problem

We are looking at switching from nginx-ingress to [haproxy ingress controller community edition](https://www.haproxy.com/documentation/kubernetes-ingress/community/configuration-reference/ingress/).

There are no instructions on the oauth2-proxy website as to how to set this up.
We have oauth2-proxy working with nginx and I was hoping that by switching to `haproxy.org/auth-url` and `haproxy.org/auth-signin` in the ingress annotations it would make it work, but it does not (these values where provided by Github Copilot and since they don't appear in the docs or any google searches it probably hallucinated them).

Is this supported?  
Any other ideas?

BTW, I tried to get use the Slack channel but when trying to sign in the email I get says I'm not allowed and there are no instructions on the website about how to get permissions to the slack channel.

### Configuration details or additional information

None

**Comment by sarg3nt** [comment]
Hi team.  Any thoughts on this?

**Comment by sarg3nt** [comment]
@busyboy77 
I'm still not getting anywhere on this.  
We do redirect to an Azure login, so maybe that is the difference.
The strange thing is that the app we are trying to get to work never tries.  It's like the annotations aren't doing anything at all.
For example, I would think that this line
`haproxy.ingress.kubernetes.io/auth-url: https://oauth2.k8s.vault.ad.selinc.com/oauth2/auth`
Would at minimum cause it to try and use oath2proxy but is seems to do nothing.
Note that we have oath2proxy set to use a subdomain, so it is a bit different from what you are doing.

And as a reminder, this works with Nginx Reverse proxy just fine.

Here's what I'm trying with help from your above config.
The app:
```yaml
    haproxy.ingress.kubernetes.io/auth-response-headers: Authorization,X-Auth-Request-User,X-Auth-Request-Email
    haproxy.ingress.kubernetes.io/auth-signin: https://oauth2.k8s.vault.ad.selinc.com/oauth2//start?rd=https://$host$request_uri
    haproxy.ingress.kubernetes.io/auth-url: https://oauth2.k8s.vault.ad.selinc.com/oauth2/auth
```

oauth2proxy ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.ingress.kubernetes.io/auth-response-headers: Authorization,X-Auth-Request-User,X-Auth-Request-Email
    haproxy.ingress.kubernetes.io/auth-signin: https://oauth2.k8s.vault.ad.selinc.com/oauth2/start?rd=%2F$http_host$request_uri
    haproxy.ingress.kubernetes.io/auth-url: https://oauth2.k8s.vault.ad.selinc.com/oauth2/auth
    haproxy.ingress.kubernetes.io/limit-burst: "100"
    haproxy.ingress.kubernetes.io/limit-rps: "50"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: haproxy
    kubernetes.io/tls-acme: "true"
    meta.helm.sh/release-name: oauth2-proxy
    meta.helm.sh/release-namespace: oauth2-proxy
```

Any thoughts?
