### ISSUE TITLE
[Support]: [oauthproxy.go:897] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: "server_error"

### ISSUE THREAD

**Issue by azat431km** [oauth2-proxy/oauth2-proxy#3000]
### OAuth2-Proxy Version

v.7.8.1

### Provider

oidc

### **K8S Dashboard + dexidp + OAuth2-proxy**
I have a kubernetes cluster and I have deployed _K8S Dashboard_.
I wanted to be able authorize users in K8S Dashboard who have account in ldap server through dexidp.

Also I have existing ldap server: FreeIpa

For now, user opens _K8S Dashboard_ in browser and Ingress redirects user to _OAuth2-Proxy_.
_OAuth2-Proxy_ goes to dex and user gets to login/authorization page.
User enters his login and password.
_Dexidp_ writes in log: **login succeeded** and `**level=error msg="failed to get auth code: <nil>"**`
_OAuth2-proxy_: `**[oauthproxy.go:897] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: "server_error"**`

I tried various ways to configure it and have no success.
What am I doing wrong?

### Ingress-Controller Logs

```
10.98.0.146 - - [21/Mar/2025:04:51:55 +0000] "POST /auth/ldap/login?back=&state=fjyuvecalnynfvrtkznrrw5g7 HTTP/2.0" 303 0 "https://dex.k8s.host.lan/auth/ldap/login?back=&state=fjyuvecalnynfvrtkznrrw5g7" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 166 0.074 [dex-dex-5556] [] 10.233.65.215:5556 0 0.074 303 a3bd801ae5b754aa219b752353b7aba9
10.98.0.146 - - [21/Mar/2025:04:51:55 +0000] "GET /approval?req=fjyuvecalnynfvrtkznrrw5g7 HTTP/2.0" 303 166 "https://dex.k8s.host.lan/auth/ldap/login?back=&state=fjyuvecalnynfvrtkznrrw5g7" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 51 0.017 [dex-dex-5556] [] 10.233.113.134:5556 166 0.017 303 0e254ed70d8f24d65b2c5319758ead11
10.0.18.15 - kubernetes [21/Mar/2025:04:51:55 +0000] "POST /token HTTP/2.0" 500 24 "-" "oauth2-proxy/v7.8.1" 400 0.008 [dex-dex-5556] [] 10.233.92.78:5556 24 0.008 500 b57272535f216c73caaac6275320d427
10.0.18.15 - - [21/Mar/2025:04:51:55 +0000] "POST /token HTTP/2.0" 500 24 "-" "oauth2-proxy/v7.8.1" 347 0.009 [dex-dex-5556] [] 10.233.65.215:5556 24 0.009 500 3965d9a86e8567635d3a79974e2305c7
10.98.0.146 - - [21/Mar/2025:04:51:55 +0000] "GET /oauth2/callback?code=bkin7ggns67s563z2bi3fg2mu&state=L7N_TAB8YnPLP0gBENnlVc2ix1Re6Hq9zMrScSqGET0%3A%2F HTTP/2.0" 500 2767 "https://dex.k8s.host.lan/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 443 0.029 [kube-system-oauth2-proxy-4180] [] 10.233.113.135:4180 2786 0.029 500 6148d557b15d578f51c104881f2382f7
10.98.0.146 - - [21/Mar/2025:04:51:56 +0000] "GET /oauth2/static/css/bulma.min.css HTTP/2.0" 200 207302 "https://auth.k8s.host.lan/oauth2/callback?code=bkin7ggns67s563z2bi3fg2mu&state=L7N_TAB8YnPLP0gBENnlVc2ix1Re6Hq9zMrScSqGET0%3A%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 184 0.104 [kube-system-oauth2-proxy-4180] [] 10.233.113.135:4180 207302 0.104 200 1b0efe8aba9d18fbadabd6d1adabf629
10.98.0.146 - - [21/Mar/2025:04:51:56 +0000] "GET /oauth2/static/css/all.min.css HTTP/2.0" 200 102025 "https://auth.k8s.host.lan/oauth2/callback?code=bkin7ggns67s563z2bi3fg2mu&state=L7N_TAB8YnPLP0gBENnlVc2ix1Re6Hq9zMrScSqGET0%3A%2F" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 39 0.113 [kube-system-oauth2-proxy-4180] [] 10.233.113.135:4180 102025 0.113 200 8b4214f5b4f2c95ce7b2aadb9ca3c060
10.98.0.146 - - [21/Mar/2025:04:51:56 +0000] "GET /oauth2/static/webfonts/fa-solid-900.woff2 HTTP/2.0" 200 149908 "https://auth.k8s.host.lan/oauth2/static/css/all.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 136 0.003 [kube-system-oauth2-proxy-4180] [] 10.233.113.135:4180 149908 0.003 200 f9c5e91915ab6e982364584a40daa75d
```

### DexIdp Logs

```
root@m-01:~# kubectl get pods -n dex -o wide
NAME                   READY   STATUS    RESTARTS   AGE    IP               NODE        NOMINATED NODE   READINESS GATES
dex-84849b49d4-6j7pq   1/1     Running   0          7h3m   10.233.92.78     w-01   <none>           <none>
dex-84849b49d4-bpf8q   1/1     Running   0          7h3m   10.233.65.215    w-03   <none>           <none>
dex-84849b49d4-r8488   1/1     Running   0          7h3m   10.233.113.134   w-02   <none>           <none>
root@m-01:~# kubectl logs -n dex --tail 10 dex-84849b49d4-6j7pq
time="2025-03-20T21:51:34Z" level=info msg="listening (https) on 0.0.0.0:5556"
time="2025-03-20T21:52:16Z" level=error msg="failed to get auth code: <nil>"
time="2025-03-20T21:57:04Z" level=error msg="failed to get auth code: <nil>"
time="2025-03-21T04:15:15Z" level=info msg="performing ldap search cn=users,cn=accounts,dc=host,dc=lan sub (&(objectClass=posixaccount)(uid=aadiev))"
time="2025-03-21T04:15:15Z" level=info msg="username \"aadiev\" mapped to entry uid=aadiev,cn=users,cn=accounts,dc=host,dc=lan"
time="2025-03-21T04:15:15Z" level=info msg="login successful: connector \"ldap\", username=\"Name Name\", preferred_username=\"aadiev\", email=\"aadiev@email.com\", groups=[]"
time="2025-03-21T04:16:32Z" level=error msg="failed to get auth code: <nil>"
time="2025-03-21T04:40:16Z" level=error msg="failed to get auth code: <nil>"
time="2025-03-21T04:41:44Z" level=info msg="garbage collection run, delete auth requests=0, auth codes=1, device requests=0, device tokens=0"
time="2025-03-21T04:51:55Z" level=error msg="failed to get auth code: <nil>"
root@m-01:~# kubectl logs -n dex --tail 10 dex-84849b49d4-bpf8q
time="2025-03-20T21:57:04Z" level=info msg="login successful: connector \"ldap\", username=\"Name Name\", preferred_username=\"aadiev\", email=\"aadiev@email.com\", groups=[]"
time="2025-03-21T04:15:15Z" level=error msg="failed to get auth code: <nil>"
time="2025-03-21T04:16:32Z" level=error msg="failed to get auth code: <nil>"
time="2025-03-21T04:40:16Z" level=info msg="performing ldap search cn=users,cn=accounts,dc=host,dc=lan sub (&(objectClass=posixaccount)(uid=aadiev))"
time="2025-03-21T04:40:16Z" level=info msg="username \"aadiev\" mapped to entry uid=aadiev,cn=users,cn=accounts,dc=host,dc=lan"
time="2025-03-21T04:40:16Z" level=info msg="login successful: connector \"ldap\", username=\"Name Name\", preferred_username=\"aadiev\", email=\"aadiev@email.com\", groups=[]"
time="2025-03-21T04:51:55Z" level=info msg="performing ldap search cn=users,cn=accounts,dc=host,dc=lan sub (&(objectClass=posixaccount)(uid=aadiev))"
time="2025-03-21T04:51:55Z" level=info msg="username \"aadiev\" mapped to entry uid=aadiev,cn=users,cn=accounts,dc=host,dc=lan"
time="2025-03-21T04:51:55Z" level=info msg="login successful: connector \"ldap\", username=\"Name Name\", preferred_username=\"aadiev\", email=\"aadiev@email.com\", groups=[]"
time="2025-03-21T04:51:55Z" level=error msg="failed to get auth code: <nil>"
root@m-01:~# kubectl logs -n dex --tail 10 dex-84849b49d4-r8488
time="2025-03-20T21:57:04Z" level=error msg="failed to get auth code: <nil>"
time="2025-03-20T22:01:35Z" level=info msg="garbage collection run, delete auth requests=0, auth codes=1, device requests=0, device tokens=0"
time="2025-03-21T00:22:31Z" level=info msg="keys expired, rotating"
time="2025-03-21T00:22:31Z" level=info msg="keys rotated, next rotation: 2025-03-21 06:22:31.865312558 +0000 UTC"
time="2025-03-21T04:15:15Z" level=error msg="failed to get auth code: <nil>"
time="2025-03-21T04:16:31Z" level=info msg="performing ldap search cn=users,cn=accounts,dc=host,dc=lan sub (&(objectClass=posixaccount)(uid=aadiev))"
time="2025-03-21T04:16:31Z" level=info msg="username \"aadiev\" mapped to entry uid=aadiev,cn=users,cn=accounts,dc=host,dc=lan"
time="2025-03-21T04:16:31Z" level=info msg="login successful: connector \"ldap\", username=\"Name Name\", preferred_username=\"aadiev\", email=\"aadiev@email.com\", groups=[]"
time="2025-03-21T04:16:43Z" level=info msg="garbage collection run, delete auth requests=0, auth codes=2, device requests=0, device tokens=0"
time="2025-03-21T04:40:16Z" level=error msg="failed to get auth code: <nil>"
```

### OAuth2-Proxy Logs

```
10.233.92.64:47716 - 09dfb56e718a87c1d0dee13d38253470 - - [2025/03/21 04:59:54] auth.k8s.host.lan GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 401 13 0.000
10.233.92.64:44548 - 7bab70d6b66af77db13cae2b2197b5da - - [2025/03/21 04:59:55] auth.host.lan GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 302 390 0.000
[2025/03/21 05:00:08] [oauthproxy.go:897] Error redeeming code during OAuth2 callback: token exchange failed: oauth2: "server_error"
10.233.92.64:44548 - 731ed363fed9dcd0552f84dce00a8c82 - - [2025/03/21 05:00:08] auth.k8s.host.lan GET - "/oauth2/callback?code=zul5ucy5dxp45fjokf24ekhby&state=uYC5OsfAb3mEjJUPtvDdKgW_W02x8QyjVR_mYENnJJc%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 500 2767 0.026
10.233.92.64:44546 - d801d4781f2850f46692afa798c2edb4 - - [2025/03/21 05:00:08] auth.k8s.host.lan GET - "/oauth2/static/css/all.min.css" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 200 102025 0.000
10.233.92.64:44548 - 205f47a4ffa8bb1a9058d78b0b1725fc - - [2025/03/21 05:00:08] auth.k8s.host.lan GET - "/oauth2/static/css/bulma.min.css" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 200 207302 0.002
10.233.92.64:44548 - 2d78e2de9253811e7b669184695eb5cc - - [2025/03/21 05:00:09] auth.k8s.host.lan GET - "/oauth2/static/webfonts/fa-solid-900.woff2" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36" 200 149908 0.002
```

### K8S Dashboard Ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard-ingress
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://auth.k8s.host.lan/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.k8s.host.lan/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - "dashboard.k8s.host.lan"
    secretName: kubernetes-dashboard-secret-tls
  rules:
  - host: "dashboard.k8s.host.lan"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
```

### OAuth2-Proxy Ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: nginx
  rules:
    - host: auth.k8s.host.lan
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180
```

### DexIdp Ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex-ingress
  namespace: dex
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: dex.k8s.host.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dex
            port:
              number: 5556
  tls:
  - hosts:
    - dex.k8s.host.lan
    secretName: kubernetes-dex-secret
```

### DexIdp.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex # This is created below
      containers:
      - image: ghcr.io/dexidp/dex:v2.32.0
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]

        ports:
        - name: https
          containerPort: 5556

        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: tls
          mountPath: /etc/dex/tls

        readinessProbe:
          httpGet:
            path: /healthz
            port: 5556
            scheme: HTTPS
      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml
      - name: tls
        secret:
          secretName: kubernetes-dex-secret
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: dex
data:
  config.yaml: |
    issuer: https://dex.k8s.host.lan
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key

    logger:
      level: debug

    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: ipa.host.lan:389
        insecureNoSSL: true
        insecureSkipVerify: true
        bindDN: uid=log,cn=users,cn=accounts,dc=host,dc=lan
        bindPW: password

        userSearch:
          baseDN: "cn=users,cn=accounts,dc=host,dc=lan"
          filter: "(objectClass=posixaccount)"
          username: "uid"
          idAttr: "uid"
          emailAttr: "mail"
          nameAttr: "cn"
          preferredUsernameAttr: uid

        groupSearch:
          baseDN: "cn=groups,cn=accounts,dc=host,dc=lan"
          filter: "(objectClass=posixGroup)"
          userMatchers:
            - userAttr: "uid"
              groupAttr: "member"
          nameAttr: "cn"

    oauth2:
      skipApprovalScreen: true
      responseTypes: [ "code", "token", "id_token" ]

    staticClients:
    - id: kubernetes
      name: 'Kubernetes Dashboard'
      redirectURIs:
      - https://auth.k8s.host.lan/oauth2/callback
      secret: kubernetes-client-secret
```

### OAuth2-Proxy.yaml

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      restartPolicy: Always
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        ports:
        - containerPort: 4180
        args:
          - --http-address=0.0.0.0:4180
          - --email-domain=*
          - --ssl-insecure-skip-verify=true
          - --cookie-secure=true
          - --cookie-domain=.k8s.host.lan
          - --redirect-url=https://auth.k8s.host.lan/oauth2/callback
          - --whitelist-domain=.k8s.host.lan
          - --code-challenge-method=S256
          - --upstream=http://kubernetes-dashboard

          - --set-xauthrequest
          - --pass-authorization-header
          - --set-authorization-header=true
          - --pass-access-token
          - --cookie-csrf-expire=5m
          - --cookie-csrf-per-request=true
          - --request-logging=true
          - --auth-logging=true
          - --standard-logging=true

          - --client-id=kubernetes
          - --client-secret=kubernetes-client-secret
        env:
        - name: OAUTH2_PROXY_PROVIDER
          value: "oidc"
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: "https://dex.k8s.host.lan"
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secret
              key: cookie-secret
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  selector:
    app: oauth2-proxy
  ports:
    - name: http
      port: 4180
      targetPort: 4180
```

### FreeIpa

1. Deploying K8S Dashboard
2. Deploying DexIdp: https://github.com/dexidp/dex/tree/master/examples/k8s
3. Deploying OAuth2-Proxy I have pasted yaml config earlier
4. Deploying Ingresses: K8S Dashboard, DexIdp, OAuth2-Proxy
