### ISSUE TITLE
[Support]: Unable to authenticate service account with OAuth2 Proxy due to email claim requirement

### ISSUE THREAD

**Issue by ffma-glen-sampson** [oauth2-proxy/oauth2-proxy#3024]
### OAuth2-Proxy Version

oauth2-proxy:v7.7.1

### Provider

oidc

### Current Behaviour of your Problem

I'm encountering an issue authenticating a Microsoft Azure AD service account with OAuth2 Proxy (v7.7.1). Despite the service account having a UPN in email format, authentication fails with the error:

```bash
[oauthproxy.go:902] Error creating session during OAuth2 callback: neither the id_token nor the profileURL set an email
```

The service account successfully authenticates with Azure AD (confirmed in logs), but OAuth2 Proxy rejects the session creation.

## Current behavior
- Service account authentication succeeds at Microsoft Azure AD level (verified in audit logs)
- OAuth2 Proxy rejects the token with the above error
- Regular user accounts (with same UPN format) work correctly

## Expected behavior
- OAuth2 Proxy should accept the UPN claim as an email address since it follows email format
- Service account should authenticate successfully

## Token information
The token contains user principal name in email format:
```json
{
  "unique_name": "svc-dev-e2etesting@company.onmicrosoft.com",
  "upn": "svc-dev-e2etesting@company.onmicrosoft.com"
}
```

## Configuration
I'm using the following configuration locally (sensitive values redacted) in my docker-compose.yml which reflects my deployment in Kubernetes.

```yaml
`version: '3.8'

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    container_name: oauth2-proxy
    restart: always
    ports:
      - "3000:3000"
    networks:
      - auth-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      # Load secrets and dynamic values from this file
      - ./.env
    environment:
      # Provider Configuration
      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "https://login.microsoftonline.com/${TENANT_ID}/v2.0"
      OAUTH2_PROXY_LOGIN_URL: "https://login.microsoftonline.com/${TENANT_ID}/v2.0/oauth2/authorize"
      OAUTH2_PROXY_REDEEM_URL: "https://login.microsoftonline.com/${TENANT_ID}/v2.0/oauth2/token"
      OAUTH2_PROXY_OIDC_JWKS_URL: "https://login.microsoftonline.com/${TENANT_ID}/discovery/v2.0/keys"
      OAUTH2_PROXY_CLIENT_ID: ${CLIENT_ID} 
      OAUTH2_PROXY_CLIENT_SECRET: ${CLIENT_SECRET} # Loaded from .env file
      OAUTH2_PROXY_SCOPE: "openid"

      # Cookie Configuration
      OAUTH2_PROXY_COOKIE_SECRET: ${COOKIE_SECRET} # Loaded from .env file
      OAUTH2_PROXY_COOKIE_SECURE: "false" # Set to "true" in production
      OAUTH2_PROXY_SESSION_STORE_TYPE: "cookie"
      OAUTH2_PROXY_COOKIE_REFRESH: "1h"

      # Server Configuration
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:3000"
      OAUTH2_PROXY_UPSTREAMS: "http://${APP_HOST}:3001" # Constructed from .env file value
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:3000/myapp/oauth2/callback" # Make dynamic if needed via .env
      OAUTH2_PROXY_PROXY_PREFIX: "/myapp/oauth2"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_PROXY_WEBSOCKETS: "true"

      # Logging Configuration
      OAUTH2_PROXY_STANDARD_LOGGING: "true"
      OAUTH2_PROXY_REQUEST_LOGGING: "true"
      OAUTH2_PROXY_AUTH_LOGGING: "true"

      # Header/Auth Passing Configuration
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true"
      OAUTH2_PROXY_SKIP_AUTH_STRIP_HEADERS: "false"

      # Other Configuration
      OAUTH2_PROXY_FLUSH_INTERVAL: "200ms"

networks:
  auth-network:
    name: auth-network
    driver: bridge
    # Or external: true if managed outside compose`
```

## Attempted workarounds
I've tried:

Setting OAUTH2_PROXY_EMAIL_CLAIM: "upn"
Setting OAUTH2_PROXY_OIDC_EMAIL_CLAIM: "upn"
Extending scope to "openid email profile"
Specifying email domain in OAUTH2_PROXY_EMAIL_DOMAINS
