### ISSUE TITLE
[Support]: getting 500 internal error when using oauth2proxy behind nginx

### ISSUE THREAD

**Issue by thebigbone** [oauth2-proxy/oauth2-proxy#3033]
### OAuth2-Proxy Version

7.6.0

### Provider

oidc

### Current Behaviour of your Problem

I am trying to access oauth2proxy from behind nginx. Here's the oauth2proxy instance nginx config:
```NGINX
server {
        server_name oauth-user.example.xyz;
        set $oauthuser 127.0.0.1;

        location ~^/oauth2/.+$ {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Protocol $scheme;
                proxy_set_header X-Forwarded-Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_pass http://$oauthuser:4180;
        }

        access_log /var/log/nginx/oauth-user_access.log;
        error_log /var/log/nginx/oauth-user_err.log;
}
```

When I try to use the above oauth2proxy, for a service behind nginx with this config:

```NGINX
server {
	server_name uptime.example.xyz;
	set $uptime 127.0.0.1;
	
	location / {
		auth_request /oauth2/auth;
		error_page 401 = /oauth2/sign_in;
		proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;
        	proxy_set_header X-Forwarded-Protocol $scheme;
        	proxy_set_header X-Forwarded-Host $http_host;
        	proxy_set_header Upgrade $http_upgrade;
        	proxy_set_header Connection "upgrade";

		proxy_pass http://$uptime:3001;
	}

  	location /oauth2/ {
  	  	proxy_pass       https://oauth-user.example.xyz;
  	  	proxy_set_header Host                    $host;
  	  	proxy_set_header X-Real-IP               $remote_addr;
  	  	proxy_set_header X-Auth-Request-Redirect $request_uri;
  	}

  	location = /oauth2/auth {
  	  	proxy_pass       https://oauth-user.example.xyz;
  	  	proxy_set_header Host             $host;
  	  	proxy_set_header X-Real-IP        $remote_addr;
  	  	proxy_set_header X-Forwarded-Uri  $request_uri;
  	  	proxy_set_header Content-Length   "";
  	  	proxy_pass_request_body           off;
  	}

	access_log /var/log/nginx/uptime_access.log;
	error_log /var/log/nginx/uptime_err.log;

}
```

I get 500 internal server error. When I use oauth2proxy local IP (127.0.0.1), it works fine.

### Configuration details or additional information

```TOML
client_id="1234"
client_secret="1234"
oidc_issuer_url="https://id.example.xyz"

# Replace with a secure random string
cookie_secret="1234"

# Additional Configuration
provider="oidc"
scope = "openid email profile groups"

# If you are using a reverse proxy in front of OAuth2 Proxy
reverse_proxy = true

# Email domains allowed for authentication
email_domains = ["*"]

# If you are using HTTPS
cookie_secure="true"

# Listen on all interfaces
http_address="0.0.0.0:4180"
```

I am using pocket-id OIDC provider which also works fine when I use oauth2proxy locally instead of through nginx.
