### ISSUE TITLE
[Support]: Oauth2-proxy + Traefik + keycloak not working config

### ISSUE THREAD

**Issue by avmp2208** [oauth2-proxy/oauth2-proxy#3036]
### OAuth2-Proxy Version

7.8.2

### Provider

keycloak-oidc

### Current Behaviour of your Problem

```
extraArgs:
  http-address: 0.0.0.0:4180
  provider: keycloak-oidc
  oidc-issuer-url: https://identity.domain.com/secure/realms/master
  redirect-url: https://oauth.domain.com/oauth2/callback
  cookie-secure: true
  cookie-refresh: 30m
  cookie-expire: 1h
  cookie-domain: .domain.com
  whitelist-domain: .domain.com
  cookie-samesite: lax
  oidc-groups-claim: groups
  oidc-email-claim: email
  scope: openid email profile
  pass-authorization-header: true
  set-authorization-header: true
  set-xauthrequest: true
  pass-access-token: true
  pass-host-header: true
  pass-user-headers: true
  skip-provider-button: true
  skip-jwt-bearer-tokens: true
  show-debug-on-error: true
  silence-ping-logging: true
  reverse-proxy: true
  proxy-prefix: /oauth2
```

Traefik Ingresses and Middleware

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: **services-keycloak-auth**
  namespace: applications
spec:
  forwardAuth:
    address: https://oauth.domain.com
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
```

```
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: **clientservice**
  namespace: applications
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`services.doamin.com`) && PathPrefix(`/clientservice`)
      middlewares:
        - name: stripprefix
        - name: **services-keycloak-auth**
      services:
        - name: clientservice
          port: 80
  tls:
    secretName: applications-tls
```

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`oauth.domain.com`)
      kind: Rule
      services:
        - name: oauth-oauth2-proxy
          port: 80
  tls:
    secretName: oauth2-proxy-tls 

### Configuration details or additional information

I created a client in keycloak following this docs **https://oauth2-proxy.github.io/oauth2-proxy/configuration/providers/keycloak_oidc**
Everything is that way, callback url in place, scopes, etc 

The problem is that with this configuration it doesnt redirect to the original URL, for example the swagger 

### Steps To Reproduce

1. Go to **https://services.doamin.com/clientservice**
2. Im being redirected to keycloak url for authenticate
3. after authenticate I should be redirect to **https://services.doamin.com/clientservice** but instead its going to **https://oauth.pidelopo.cl**
