### ISSUE TITLE
[Support]: No authentication headers passed to upstream when using oauth2-proxy with Keycloak and Traefik

### ISSUE THREAD

**Issue by bo-unitysvc** [oauth2-proxy/oauth2-proxy#3043]
### Environment
- oauth2-proxy version: bitnami/oauth2-proxy:latest
- Keycloak version: 25.0
- Traefik version: 3.3.6

### Expected Behavior
oauth2-proxy should pass authentication headers (X-Forwarded-User, X-Auth-Request-User, X-Auth-Request-Email) to the upstream application after successful authentication.

### Actual Behavior
No authentication headers are passed to the upstream service. Only standard headers and cookies are present.

### Questions

Am I supposed to see some additional headers like    `X-Forwarded-User`, `X-Auth-Request-User`, and `X-Auth-Request-Email` from the last `GET` request? If so, what might have caused the missing headers?

### Configuration

**oauth2-proxy configuration:**
```yaml
oauth2-proxy:
  image: bitnami/oauth2-proxy:latest
  container_name: oauth2-proxy
  restart: unless-stopped
  command:
    - --provider=keycloak-oidc
    - --email-domain=mycompany.com
    - --redirect-url=https://oauth.mycompany.com/oauth2/callback
    - --http-address=0.0.0.0:4180
    - --cookie-secure=true
    - --cookie-httponly=false
    - --set-xauthrequest=true
    - --pass-access-token=true
    - --pass-basic-auth=true
    - --pass-user-headers=true
    - --pass-authorization-header=true
    - --pass-host-header=true
    - --skip-provider-button
    - --reverse-proxy=true
    - --scope=openid email profile
    - --upstream=http://website
    - --code-challenge-method=S256
    - --cookie-domain=.mycompany.com
    - --whitelist-domain=.mycompany.com
    - --standard-logging-format=text
    - --oidc-issuer-url=https://auth.mycompany.com/realms/mycompany
```

### Authentication Flow

1. User initiates login: `https://oauth.mycompany.com/oauth2/start?rd=https://mycompany.com`
2. Keycloak authentication successful
3. oauth2-proxy callback receives authorization code, with a request in the format of 
 
```
https://oauth.mycompany.com/oauth2/callback?state=r7buIXw%3Ahttps%3A%2F%2Fwww.mycompany.com&
session_state=9afba3a4&iss=https%3A%2F%2Fauth.mycompany.com%2Frealms%mycompany&
code=78cc1940-a49789430257
```
and yielded a 302 response with headers

```
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Content-Length: 47
Content-Type: text/html; charset=utf-8
Date: Sun, 27 Apr 2025 04:07:38 GMT
Expires: Thu, 01 Jan 1970 00:00:00 UTC
Location: https://www.mycompany.com
Set-Cookie: *oauth2*proxy_csrf=; Path=/; Domain=mycompany.com; Max-Age=0; Secure, *oauth2*proxy_0=vOtzPOnynCb1m-6AWtRUcZ6CxOWQXLqfOsQafaGrh90u1i0w2P3p; Path=/; Domain=mycompany.com; Max-Age=604800; Secure, *oauth2*proxy_1=h_Cb06QT1d_Vo=; Path=/; Domain=mycompany.com; Max-Age=604800; Secure
X-Accel-Expires: 0
```

5. Upstream receives request 

```
URL: https://www.mycompany.com/
Method: GET
Headers:
User-Agent: Mozilla/5.0 (Python Authentication Test Script)
Accept-Encoding: gzip, deflate, br, zstd
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection: keep-alive
Accept-Language: en-US,en;q=0.5
Cookie: oauth2_proxy_0=vOtzPOnynCb1C6MyXBJ=
```

### Steps To Reproduce

I can provide a test traefik configuration and docker-compose file if needed.
