### ISSUE TITLE
[Support]: injectResponseHeaders injects incorrect value for "email" claim

### ISSUE THREAD

**Issue by MartinRied** [oauth2-proxy/oauth2-proxy#3059]
### OAuth2-Proxy Version

v7.9.0

### Provider

oidc

### Current Behaviour of your Problem

I'm running oauth2-proxy together with Keycloak to authenticate users for the nginx ingress of a Kubernetes cluster.

Generally speaking this works just fine. However, all my attempts at injecting the email claim into the headers returned to nginx have failed. I've spent quite a bit of time over the last few weeks trying to figure this out, even looking at the source code of oauth2-proxy, but I couldn't find any explanation for the behaviour.

Here's the `injectResponseHeaders` config (full config see below):
```yaml
  injectResponseHeaders:
  - name: Remote-User
    values:
      - claim: preferred_username
  - name: X-Auth-Email
    values:
      - claim: email
  - name: X-Auth-Token
    values:
      - claim: id_token
```

And here's the response sent from oauth2-proxy to nginx I see when running tcpdump in the oauth2 pod/container:
```
HTTP/1.1 202 Accepted
Gap-Auth: user.name
Remote-User: user.name
X-Auth-Email: user.name
X-Auth-Token: [token]
```
⚠ Note that the `X-Auth-Email` header contains the username instead of the eMail ⚠ 
Needless to say that the application we're authenticating for also only receives the incorrect `X-Auth-Email` header, containing the username instead of the actual eMail.

Can anyone help me out here? 
Did I misunderstand something or provide incorrect configuration?
Is this maybe a known issue?
...?

### Token Contents

Token contents:
```json
{
  "sub": "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "email_verified": true,
  "name": "User Name",
  "groups": [
    "/group1",
    "/group2",
  ],
  "preferred_username": "user.name",
  "given_name": "User",
  "family_name": "Name",
  "email": "user@xxx.yyy"
}
```

### Ingress Annotations:

```yaml
ingress:
  enabled: false
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: Remote-User X-Auth-Email
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.xxx.yyy/oauth2/start?rd=$scheme://$best_http_host$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth.xxx.yyy/oauth2/auth
```

### Full oauth2-proxy Configuration (Helm values.yaml)

```yaml
config:
  # openssl rand -base64 32 | head -c 32 | base64
  cookieSecret: "[REDACTED]"
  configFile: |-
    cookie_domains = [ ".xxx.yyy", ".aaa.bbb" ]
    whitelist_domains = [ ".xxx.yyy", ".aaa.bbb" ]
    cookie_refresh = "15m"
    cookie_expire = "30m"
    email_domains = [ "*" ]

alphaConfig:
  enabled: true
  configFile: |-
    providers:
    - provider: oidc
      id: keycloak
      name: Keycloak
      clientID: "oauth2-proxy"
      clientSecret: [REDACTED]
      code_challenge_method: S256
      oidcConfig:
        issuerUrl: https://keycloak.xxx.yyy/realms/myrealm
      audienceClaims: [ "aud" ]
      emailClaim: email
      userIDClaim: preferred_username
      groupsClaim: groups
    scope: openid profile email
  injectResponseHeaders:
  - name: Remote-User
    values:
      - claim: preferred_username
  - name: X-Auth-Email
    values:
      - claim: email
  - name: X-Auth-Token
    values:
      - claim: id_token

sessionStorage:
  type: redis
redis:
  enabled: true
```

### Steps To Reproduce

1. Environment: Kubernetes cluster with Keycloak & nginx ingress
2. Setup oauth2-proxy as described above
3. Use annotations described above for an nginx ingress
4. Verify the `X-Auth-Email` header passed to the application behind the ingress.
