### ISSUE TITLE
[Bug]: insecureSkipNonce defaults to false with alpha configuration

### ISSUE THREAD

**Issue by pxnis** [oauth2-proxy/oauth2-proxy#3069]
### OAuth2-Proxy Version

2.9.0

### Provider

keycloak-oidc

### Expected Behaviour

Defaults to true, as per the documentation

### Current Behaviour

Defaults to false

### Steps To Reproduce

We are updating from RHSSO (Keycloak 18) to RHBK (Keycloak 26).
Therefore we ran into the issue described in #2876 which was confusing as we didn't define "insecureSkipNonce".
Was also the case with version 7.5.2.

1. Start oauth2-proxy with alpha config, which have undefined "insecureSkipNonce"
2. Nonce is still checked

### Configuration details or additional information

Our config with placeholders:
```
server:
  BindAddress: 0.0.0.0:OAUTH2_PROXY_PORT

upstreamConfig:
  upstreams:
    - id: routing
      path: /
      uri: http://CNAME_ROUTING_PLACERHOLDER:8080
      passHostHeader: true

providers:
  - id: keycloak
    provider: keycloak-oidc
    code_challenge_method: S256
    clientID: CLIENT_ID_PLACEHOLDER
    clientSecret: CLIENT_SECRET_PLACEHOLDER
    oidcConfig:
      issuerURL: OIDC_ISSUER_URL_PLACEHOLDER
      audienceClaims:
        - aud
      emailClaim: email
      userIDClaim: email
    loginURLParameters:
      - name: approval_prompt
        default:
          - force
      - name: login_hint
        allow:
          - pattern: '$'

injectRequestHeaders:
  - name: Authorization
    values:
      - claim: id_token
        prefix: 'Bearer '
```
