### ISSUE TITLE
[Feature]: configuration par fqdn/host

### ISSUE THREAD

**Issue by mcarbonneaux** [oauth2-proxy/oauth2-proxy#3076]
### Motivation

to be abel to mutualise one oauth2-proxy instance to serve multiple fqdn (to avoid to instanciate oauth-proxy for each fqdn), we need the posibility to have configuration per fqdn.

in that way we can configure multiple fqdn pointing to one oauth-proxy and the oauth proxy use the oidc idp asocciated to the fqdn and the upstream associated to the fqdn (virtual hosting).

**Comment by JoelSpeed** [comment]
In the long term, I think this is admirable as a goal, but I do question whether it's really that much of a burden to run multiple different OAuth2 Proxy instances? It's fairly lightweight and for most modern infrastructure (yes I appreciate that's not everyone) I'd expect templating out lots of instances of e.g. a helm chart not to be too burdensome

**Comment by mcarbonneaux** [comment]
Hi @JoelSpeed ,

Currently, deploying a dedicated `oauth2-proxy` instance for every single application/FQDN can become an operational burden when managing dozens of micro-frontends or independent domains, especially when we want to keep a centralized ingress architecture.

#### 🏢 My Use Case
I have a single ingress controller/reverse-proxy routing traffic for multiple independent domains. Each domain points to a different backend application and uses a different OIDC client (or even a different IdP provider), but I want a single `oauth2-proxy` deployment to handle the authentication routing based on the incoming `Host` header.

* `app1.company.com` -> Authenticates via Keycloak (Client A) -> Forwards to `service-a:80`
* `partner-portal.com` -> Authenticates via Google OIDC (Client B) -> Forwards to `service-b:80`

#### ⚙️ Suggested Configuration Syntax
To achieve this without breaking backward compatibility, we could introduce a `hosts` or `tenants` block in the configuration file. If a request matches a specific host, it overrides the global default settings.

```yaml
# Global / Default fallback configuration
provider: "oidc"
cookie_secure: true
cookie_refresh: "1h"

# Multi-FQDN / Virtual Hosting configuration
hosts:
  - match: "app1.company.com"
    client_id: "keycloak-client-a"
    client_secret: "secret-abc"
    oidc_issuer_url: "[https://keycloak.company.com/auth/realms/internal](https://keycloak.company.com/auth/realms/internal)"
    upstreams:
      - "[http://service-a.prod.svc.cluster.local:80](http://service-a.prod.svc.cluster.local:80)"

  - match: "partner-portal.com"
    client_id: "google-client-b"
    client_secret: "secret-xyz"
    oidc_issuer_url: "[https://accounts.google.com](https://accounts.google.com)"
    upstreams:
      - "[http://service-b.prod.svc.cluster.local:80](http://service-b.prod.svc.cluster.local:80)"

```

#### 🧠 Regarding the "lightweight / multiply instances" approach

@JoelSpeed's about simply templating many instances via Helm because the binary is lightweight:

While a single Go binary is fast and efficient, Go binaries are statically compiled and embed the entire Go runtime. An `oauth2-proxy` container easily takes ~30MB to ~50MB of RAM at baseline.

When you scale this across an enterprise infrastructure with hundreds of distinct FQDNs/applications—and replicate them for High Availability (at least 2 or 3 replicas per app)—we are no longer talking about a few megabytes. We end up wasting **several gigabytes of cluster memory** just to duplicate the same Go runtime over and over again, purely to handle different OIDC client secrets.

#### 🚀 Benefits of Multi-FQDN Support

1. **Resource Efficiency:** Significant memory savings on Kubernetes clusters by avoiding redundant Go runtime overhead for 50+ identical deployments.
2. **Centralized Management:** Easier to maintain, log, and update a single routing proxy layer while keeping GitOps repositories clean of repetitive Helm values.

This would make `oauth2-proxy` incredibly powerful and resource-friendly for multi-tenant and multi-domain infrastructures!
