### ISSUE TITLE
[Support]: Difficulty getting Oauth2-proxy to accept my redirect urls

### ISSUE THREAD

**Issue by mikeymop** [oauth2-proxy/oauth2-proxy#3079]
### OAuth2-Proxy Version

v7.9.0

### Provider

oidc

### Current Behaviour of your Problem

I am attempting to use oauth2-proxy to protect a service with authentication against Zitadel as an OIDC provider.

In my scenario, Zitadel is external, I would like to redirect requests to a service running on my docker host, to a Zitadel instance running on a different docker host.

In Zitadel, I have configured the following redirect urls:
 - https://music.example.com/app
 - https://music.example.com/
 - http://127.0.0.1:4180/   # oauth2-proxy, not sure if needed, but tried for debugging

I have also tried with
`whitelist_domains=[".example.com","music.example.com"]` with no luck.

No matter what I set for the whitelist_domain, oidc_issuer_url, or redirect_url, when I visit music.example.com I am redirected to the Oauth2 Proxy login page.

I see "Zitadel" as a provider, clicking it takes me to `oauth2/start?rd=%2F`. When I do this, oauth2-proxy logs the following error message:

```
[2025/05/26 20:29:08] [oauthproxy.go:1030] No valid authentication in request. Initiating login.

[2025/05/26 20:29:08] [director.go:85] Invalid redirect generated from X-Forwarded-* headers: https://music.example.com/

[2025/05/26 20:29:08] [validator.go:60] Rejecting invalid redirect "https://music.example.com/": domain / port not in whitelist

123.45.67.216 - 68cb562a-eb5d-4d5a-a1c7-2be2cb569475 - - [2025/05/26 20:29:08] music.example.com GET - "/oauth2" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0" 403 8571 0.000
```

It seems as if I am either entering an invalid `whitelist_domains` and it is being ignored, or that `whitelist_domains` is not the configuration I need.

I am also concerned that the `rd` query parameter is not "music.example.com" as my understanding is that this is the location oauth2-proxy will redirect me to once the authentication is successful with my OIDC provider.

Should `redirect_url` be the endpoint internal to oauth2-proxy? Should it be my downstream service? Or should it be the `redirect_url` specified within my OIDC provider?

What oauth2-proxy configuration dictates the result the of `rd` queryparam?

### Configuration details or additional information

```toml
http_address="0.0.0.0:4180"

provider="oidc"
provider_display_name="Zitadel"

client_id="REDACTED@example"
client_secret="<REDACTED>"

redirect_url="http://music.example.com/"
reverse_proxy="true"
set_xauthrequest="true"
real_client_ip_header="X-Forwarded-For"

# These are provided by Zitadel
oidc_issuer_url="https://auth.example.com/oauth/v2"
login_url="https://auth.example.com/oauth/v2/authorize"
redeem_url="https://auth.example.com/oauth/v2/token"
validate_url="https://auth.example.com/oauth/v2/userinfo"

email_domains=["example.com"]
whitelist_domains=".example.com"
cookie_secure="false"
cookie_secret="<REDACTED>"
```

### Steps To Reproduce

1. Visit the downstream service you want protected by oauth2-proxy
2. Attempt to login to the available provider
3. Notice you were redirected to `/start/?rd=%2F`
4. Observe the errors in the oauth2-proxy logs.
