### ISSUE TITLE
[Support]: skip-auth-strip-headers / skip_auth_strip_headers in Alpha

### ISSUE THREAD

**Issue by Smuger** [oauth2-proxy/oauth2-proxy#3086]
### OAuth2-Proxy Version

v7.9.0

### Provider

github

### Current Behaviour of your Problem

Current Behaviour of your Problem
https://oauth2-proxy.github.io/oauth2-proxy/configuration/alpha-config/#removed-options

**skip-auth-strip-headers** / **skip_auth_strip_headers** are removed in **Alpha** configuration

is there an equivalent for alpha?

I'm trying to use injectRequestHeaders to add Header with authorization Bearer so I can access my Kubernetes Dashboard and I just don't see the header passed upstream

### Configuration details or additional information

```
Configuration details or additional information
injectRequestHeaders:
  - name: Authorization
    values:
      - value: dGVzdA==
    preserveRequestValue: true
```
