### ISSUE TITLE
[Bug]: Passing empty list of Redis URLs causes nil pointer dereference

### ISSUE THREAD

**Issue by dgivens** [oauth2-proxy/oauth2-proxy#3100]
### OAuth2-Proxy Version

7.9.0

### Provider

keycloak-oidc

### Expected Behaviour

Passing an empty list of Redis URLs should return an error.

### Current Behaviour

You get a nil pointer dereference. 

```text
goroutine 1 [running]:
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/sessions/redis.buildSentinelClient({{0x0, 0x0}, {0x0, 0x0}, {0xc00003c01c, 0x1c}, 0x1, {0xc000038075, 0x1c}, {0x0, ...}, ...})
    /go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/sessions/redis/redis_store.go:104 +0xa4
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/sessions/redis.NewRedisClient({{0x0, 0x0}, {0x0, 0x0}, {0xc00003c01c, 0x1c}, 0x1, {0xc000038075, 0x1c}, {0x0, ...}, ...})
    /go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/sessions/redis/redis_store.go:86 +0x58
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/validation.validateRedisSessionStore(0xc000280f30)
    /go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/validation/sessions.go:49 +0xb8
github.com/oauth2-proxy/oauth2-proxy/v7/pkg/validation.Validate(0xc000280f30)
    /go/src/github.com/oauth2-proxy/oauth2-proxy/pkg/validation/options.go:25 +0x168
main.main()
    /go/src/github.com/oauth2-proxy/oauth2-proxy/main.go:52 +0x318
```

### Steps To Reproduce

1. Using the oauth2-proxy helm chart
1. Set the following in `values.yaml` - Note the absence of `sessionStorage.redis.sentinel`
    
    ```yaml
    sessionStorage:
      type: redis
      redis:
        existingSecret: oauth2-proxy-redis-password-secret
        passwordKey: redis-password
        clientType: sentinel
    ```
1. Install the helm chart
1. Check the logs from one of the oauth2-proxy pods
