### ISSUE TITLE
[Bug]: auth with htaccess impossible when `allowedGroups` is set

### ISSUE THREAD

**Issue by m-studer** [oauth2-proxy/oauth2-proxy#3102]
### OAuth2-Proxy Version

v7.9.0 dockerized

### Provider

oidc

### Expected Behaviour

if `--htpasswd-file` is set, any request with a `Authorization`-Header matching a line in the set htpasswd file should be passed on to the upstream, regardless of any oauth2-config, since this represents a separate auth mechanism.

### Current Behaviour

If `allowedGroups` is set in the alpha config, requests with a matching basic auth header get rejected due to them not being in the right group.

application log:
```
10.125.0.4 - d744e0a1-26cb-45c4-a129-2a10db7f1e07 - <basic_username> [2025/06/11 10:49:24] [AuthSuccess] Authenticated via basic auth and HTpasswd File
10.125.0.4 - d744e0a1-26cb-45c4-a129-2a10db7f1e07 - - [2025/06/11 10:49:24] [AuthFailure] Invalid authorization via session (unauthorized): removing session Session{email: user:<basic_username> PreferredUsername:}
10.125.0.4 - d744e0a1-26cb-45c4-a129-2a10db7f1e07 - <basic_username> [2025/06/11 10:49:24] <url> GET - "/" HTTP/1.1 "curl/7.81.0" 403 2715 0.003
```

the same request from curl's side:
```
curl -v 'https://<url>' --header 'Authorization: Basic <some_base64_string>' -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.100.42.13:443...
* Connected to <url> (10.100.42.13) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS header, Certificate Status (22):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.2 (IN), TLS header, Finished (20):
{ [5 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [10 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2759 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.2 (OUT), TLS header, Finished (20):
} [5 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.example.com
*  start date: May  4 04:03:58 2025 GMT
*  expire date: Aug  2 04:03:57 2025 GMT
*  subjectAltName: host "<url>" matched cert's "<url>"
*  issuer: C=US; O=Let's Encrypt; CN=R10
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
} [5 bytes data]
> GET / HTTP/1.1
> Host: <url>
> User-Agent: curl/7.81.0
> Accept: */*
> Authorization: Basic <some_base64_string>
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [233 bytes data]
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [233 bytes data]
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< date: Wed, 11 Jun 2025 10:49:24 GMT
< content-type: text/html; charset=utf-8
< transfer-encoding: chunked
< set-cookie: 1fe19e3a4f04bd6e36fe240b901b05dc=<some_hex_string>; path=/; HttpOnly; Secure; SameSite=None
< 
{ [2727 bytes data]
100  2715    0  2715    0     0  24285      0 --:--:-- --:--:-- --:--:-- 24459
* Connection #0 to host <url> left intact
```

when I do the same request but add the cookie i just got, i get the same response

### Steps To Reproduce

1. create a dockerized `v7.9.0` with an alphaConfig, in which you set a valid auth provider. also create a htaccess file, mount it into the container and activate it with `--htpasswd-file`.
2. observe how you can log in with both http basic auth and oauth2
3. now set `allowedGroups` in the alpha config to a group your user is a member of
4. observe how you can still log in with oauth2, but no longer with http basic auth

### Configuration details or additional information

# Works with both oauth2 and http basic

alpha config:
```yaml
upstreamConfig:
  upstreams:
    - id: "my_id"
      uri: "http://localhost:8000"
      path: "/"
server:
  BindAddress: "-" # Don't want to expose HTTP
  SecureBindAddress: "https://0.0.0.0:8443"
  TLS:
    Key:
      fromFile: "/etc/certificates/tls.key"
    Cert:
      fromFile: "/etc/certificates/tls.crt"
providers:
  - clientID: "my_client_id"
    clientSecretFile: "/secrets/oauth2_proxy_client_secret"
    oidcConfig:
      issuerURL: "https://sso.examlple.com/auth/realms/my_realm"
      emailClaim: "email"
      audienceClaims:
        - "aud"
      userIDClaim: "email"
      groupsClaim: "my_realm.roles"
    id: "pitc-sso"
    provider: "oidc"
    name: "Puzzle SSO"
    scope: "openid"
    allowedGroups:
      - "my_group"
    code_challenge_method: "S256"
```
environment variables:

```yaml
env:
  - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
    value: "true"
  - name: OAUTH2_PROXY_REVERSE_PROXY
    value: "true"
  - name: OAUTH2_PROXY_COOKIE_REFRESH
    value: "5m"
  - name: OAUTH2_PROXY_EMAIL_DOMAINS
    value: "example.com"
  - name: OAUTH2_PROXY_COOKIE_SECRET
    value: "****"
  - name: OAUTH2_PROXY_HTPASSWD_FILE
    value: "/secrets/application_password_htaccess"
  - name: OAUTH2_PROXY_SILENCE_PING_LOGGING
    value: "true"
```

# Works with both oauth2 and http basic

alpha config:
```yaml
upstreamConfig:
  upstreams:
    - id: "my_id"
      uri: "http://localhost:8000"
      path: "/"
server:
  BindAddress: "-" # Don't want to expose HTTP
  SecureBindAddress: "https://0.0.0.0:8443"
  TLS:
    Key:
      fromFile: "/etc/certificates/tls.key"
    Cert:
      fromFile: "/etc/certificates/tls.crt"
providers:
  - clientID: "my_client_id"
    clientSecretFile: "/secrets/oauth2_proxy_client_secret"
    oidcConfig:
      issuerURL: "https://sso.examlple.com/auth/realms/my_realm"
      emailClaim: "email"
      audienceClaims:
        - "aud"
      userIDClaim: "email"
      groupsClaim: "my_realm.roles"
    id: "pitc-sso"
    provider: "oidc"
    name: "Puzzle SSO"
    scope: "openid"
    code_challenge_method: "S256"
```
environment variables:

```yaml
env:
  - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
    value: "true"
  - name: OAUTH2_PROXY_REVERSE_PROXY
    value: "true"
  - name: OAUTH2_PROXY_COOKIE_REFRESH
    value: "5m"
  - name: OAUTH2_PROXY_EMAIL_DOMAINS
    value: "example.com"
  - name: OAUTH2_PROXY_COOKIE_SECRET
    value: "****"
  - name: OAUTH2_PROXY_HTPASSWD_FILE
    value: "/secrets/application_password_htaccess"
  - name: OAUTH2_PROXY_SILENCE_PING_LOGGING
    value: "true"
```
