### ISSUE TITLE
Option skip-provider-button provides white page with "Found." link

### ISSUE THREAD

**Issue by markuzzi** [oauth2-proxy/oauth2-proxy#334]
When I use the parameter -skip-provider-button, the login button is not shown anymore, but a white page with a single link named "Found" instead.

## Expected Behavior
I would have expected to be redirected to the login site of the provider directly. In addition, the Found link does not work, as it contains a redirect URI with 0.0.0.0 as host name.

## Current Behavior
Show white page with "Found" link instead of being redirected to provider.

## Steps to Reproduce (for bugs)

I have a docker container (swarm) with the following settings
```
oauth2:
  image: oauth2_proxy # build from repository (armv6)
  command:
    - -cookie-domain=xxx
    - -cookie-secure=true
    - -cookie-secret=xxx
    - -email-domain=*
    - -http-address=0.0.0.0:4180
    - -pass-access-token
    - -provider=gitlab
    - -gitlab-group=xxx
    - -client-id=xxx
    - -client-secret=xxx
    - -set-authorization-header
    - -set-xauthrequest
    - -whitelist-domain=.${DOMAIN}
    - -footer=-
    - -banner=xxx
    - -provider-display-name=me
    - -skip-provider-button=true
```

## Your Environment
- Version used: latest version (>4.1.0) from git (via git clone)
