### ISSUE TITLE
Get User Details from Azure AD

### ISSUE THREAD

**Issue by nicoschuck** [oauth2-proxy/oauth2-proxy#354]
I have an AKS cluster that runs with nginx-ingress in front. For authentification, I use Azure AD as IP.
Is it possible to forward the user details which Azure provides to the application? Or is there any other way to get the user details? I'm not able to send an http request directly to https://graph.windows.net/me?api-version=x.y because of my app stores only the oauth2_cookie and no auth token.

## Expected Behavior

I want to receive all the details from https://graph.windows.net/me.

## Current Behavior

The logs of the oauth2_proxy pod shows that all information is successfully received:

```
$ kubectl logs oauth2-proxy-7ddc97f9d5-ckm29

[oauthproxy.go:846] Error loading cookied session: Cookie "_oauth2_proxy" not present
...
[requests.go:25] 200 GET https://graph.windows.net/me?api-version=1.6 {
  "odata.metadata":"https://graph.windows.net/myorganization/$metadata#directoryObjects/@Element",
  "odata.type":"Microsoft.DirectoryServices.User",
  "objectType":"User", 
  ... ,
  "sipProxyAddress":"nico.schuck@example.com",
  "streetAddress":"my stree",
  "surname":"Schuck",
  "telephoneNumber":55512345,
  "usageLocation":"DE",
  "userType":"Member"
}
165.xxx.xxx.214 - nico.schuck@example.com [2020/01/17 11:22:02] [AuthSuccess] Authenticated via OAuth2: Session{email:nico.schuck@example.com user: token:true id_token:true created:2020-01-17 11:22:02.28839851 +0000 UTC m=+181.592452463 expires:2020-01-17 12:22:02 +0000 UTC refresh_token:true}
```

## Possible Solution

Provide all Details on /oauth2/userinfos.
Or is there any security reason why not doing that?

## Your Environment

ouath2-proxy.yaml:
```
containers:
      - args:
        - --provider=azure
        - --email-domain=*
        - --set-xauthrequest=true
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --azure-tenant=xxxx
        env:
          ...
        image: quay.io/pusher/oauth2_proxy
```

ingress.yaml:
```
annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/auth-url: "https://inside.eon.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://inside.eon.com/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
```

**Comment by JoelSpeed** [comment]
Have you tried using the `set-authorization-header` option? This would return the Azure ID Token to your application which may contain the information you require? 

There isn't presently a way to expose the auth token itself that you would require to access the profile URL (unless it would also accept the ID Token? I'm not familiar with Azure)

**Comment by nicoschuck** [comment]
Thank you for your answer. It looks like that set-authorization-header is what I'm looking for.
But is there any way to decode the information from the cookie?
I tried it by simple base64 -d (and it looks like that the auth and id token is passed) but most of the information are still encoded.

**Comment by JoelSpeed** [comment]
The cookie is encrypted by the proxy so it should only be readable with the proxy itself. If you wish to decrypt it within your app, you could potentially do so but it would require some work on your part to implement the decryption algorigthm

**Comment by nicoschuck** [comment]
I'm still struggling with that topic. I believe to encrypt the cookie is not the right way. What else I can do with the cookie?

**Comment by JoelSpeed** [comment]
The information in the cookie is meant to be used only by the proxy itself, we have alternative mechanisms for retrieving user info via headers.

The cookie is encrypted for security reasons, if it were not encrypted, the values within it could possibly be modified by users and this would break the security model of the proxy

**Comment by nicoschuck** [comment]
OK. If there are alternative mechanisms to retrieve user Infos, is there an option to provide user details to the app?

**Comment by nicoschuck** [comment]
Is there maybe any way to pass the JWT to the service, by which I can request the details by myself?

**Comment by johejo** [comment]
Hi, `pass-access-token` option might be helpful.

And setup ingress.
```
nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-forwarded-access-token"

```
You can use Azure AD Graph API using the access token.
(Caution: not Microsoft Graph API)
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api

**Comment by nicoschuck** [comment]
Hi. Actually I hoped there is an option to pass the groups of the user, too. But it doesn't looks like. Anyway. Unfortunately, I don't receive the access token.
My Ingress annotation:
`nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Forwarded-Access-Token"`

And I added following to the env of the ouath_proxy:
```
- --set-xauthrequest=true
- --pass-access-token=true
- --pass-authorization-header=true #for decode
- --set-authorization-header=true
```

But I only receive the Bearer Token, email and user account. Maybe because I added following configuration to my ingress:

nginx.ingress.kubernetes.io/configuration-snippet: proxy_set_header cookie "";

I did that because in other cases my header is too big and I get an Error 403.

**Comment by JoelSpeed** [comment]
If you remove the cookie this will cause issues. Try setting the `proxy_buffer_size` to `8k` and this may help your issue with the cookie header being too large

**Comment by nicoschuck** [comment]
I added:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  labels:
    k8s-app: nginx-ingress-controller-internal
data:
  proxy-buffer-size: "8k"
  http2-max-field-size: "8k"
```
and passed the configmap to my ingress-controller. Unfortunately, I still get an Error 431. Is there any other adjustment that I need to do?
