### ISSUE TITLE
Protected target URL returns HTTP 500 code instead of redirecting to sign in page

### ISSUE THREAD

**Issue by manning-ncsa** [oauth2-proxy/oauth2-proxy#356]
## Expected Behavior

I am following [this tutorial](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/oauth-external-auth) to use oauth2_proxy to enable basic authentication to a generic web app using GitHub as the third-party authenticator as in the tutorial. I expect to request the web app URL `example.com/app` and be redirected to `example.com/oauth2/sign_in` (when not authenticated). After authenticating via the GitHub oauth app page, I expect to be redirected to `example.com/app` where the HTTP request is now fulfilled by the app's corresponding Kubernetes service.

## Current Behavior

When I open `example.com/app` I get a "500 internal server error" in my browser. Kubernetes logs show that my app container is never involved. Instead the oauth2_proxy container logs show an error:
```
[2020/01/17 20:07:18] [oauthproxy.go:846] Error loading cookied session: Cookie "_oauth2_proxy" not present
127.0.0.1 - - [2020/01/17 20:07:18] example.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0" 401 21 0.000
```
If I manually enter the URL `example.com/oauth2/sign_in`, the correct authentication sequence occurs: I see a GitHub log in button, which takes me to the GitHub external app authorization page. Upon successful authorization, I am taken to `example.com` instead of `example.com/app`, which returns a 404 response, but if I then manually enter `example.com/app` I see my app page load properly. In other words, the session cookie is indeed being received by the browser and it is allowing me to access the app page when present and valid.

## Possible Solution

I thought that perhaps this was related to https://github.com/pusher/oauth2_proxy/pull/258 but I am not using Azure, and previous Docker image tags did not alter the outcome. I even tried NGINX ingress controller annotations to increase the [proxy_buffer_size](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#proxy-buffer-size) to no effect.

## Steps to Reproduce (for bugs)

The relevant Kubernetes resource definitions are below. The `auth-test` service is a simple `httpd` image serving a static HTML document.
```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth-test
  namespace: desdev2
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: auth-test
          servicePort: 80
        path: /app

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: desdev2
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - example.com
    secretName: example-com-tls

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: desdev2
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=github
        - --email-domain=*
        - --github-org=my-org-name
        - --upstream=http://$(AUTH_TEST_SERVICE_HOST):$(AUTH_TEST_SERVICE_PORT)
        - --http-address=0.0.0.0:4180
        - --pass-access-token=true
        - --pass-basic-auth=true
        - --pass-host-header=true
        - --pass-user-headers=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: secret
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: secret
        image: quay.io/pusher/oauth2_proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

```
## Context

This issue is preventing me from deploying a protected web app that can seamlessly authenticate users via GitHub to grant access to the site.

## Your Environment

Version info:
* oauth2_proxy:latest (should be v4.1.0)
* Kubernetes v1.16
* quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.21.0
