### ISSUE TITLE
redirect to '/' instead of requested URL after successful login in docker-compose with traefik

### ISSUE THREAD

**Issue by brucke** [oauth2-proxy/oauth2-proxy#397]
Hi, 

i like this project it solves a lot of my problems! :) But i have one big issue and i'm not able to fix it. I guess, there is a simple configuration bug in my docker-compose file or similar. The user is redirected to '/' after succesful login instead of requested page. 

Does somebody have a tipp or a solution for me? I read all issues related to this problem but i'm not able to adapt their proposal to my docker-compose with traefik. 

## Expected Behavior

1) go to https://api.${DOMAIN}/whoami 
2) redirect to login page
3) login with OICD provider
4) redirect to https://api.${DOMAIN}/whoami 

## Current Behavior

1) go to https://api.${DOMAIN}/whoami 
2) redirect to login page
3) login with OICD provider
4) redirect to https://api.${DOMAIN}

I guess, there is a simple configuration bug in my docker-compose file or similar. Does somebody have a tipp or a solution for me? I read all issues related to this problem but i'm not able to adapt their proposal to my docker-compose with traefik. 

## Steps to Reproduce (for bugs)

```yaml
version: "2"
services:
  traefik:
    image: "traefik:cantal"
    restart: always
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=postmaster@${DOMAIN}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"

    labels:
      traefik.enable: 'true'
      # traefik.http.middlewares.default-compress.compress: 'true'
      traefik.http.middlewares.redirect-web-secure.redirectscheme.scheme: 'https'
      traefik.http.middlewares.redirect-web-secure.redirectScheme.permanent: 'true'
      # traefik.http.middlewares.redirect-web-secure.chain.middlewares: default-compress
      traefik.http.routers.traefik.entrypoints: https
      # traefik.http.routers.traefik.middlewares: oauth-signin,oauth-verify,default-https
      traefik.http.routers.traefik.middlewares: redirect-web-secure
      traefik.http.routers.traefik.rule: "Host(`api.${DOMAIN}`) && PathPrefix(`/api`, `/dashboard`)"
      traefik.http.routers.traefik.tls.certResolver: 'mytlschallenge'
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: '80'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  oauth:
    image: quay.io/pusher/oauth2_proxy:v5.0.0
    restart: unless-stopped
    labels:
      ai.ix.expose: 'true'
      traefik.enable: 'true'
      traefik.http.middlewares.oauth-verify.forwardAuth.address: http://oauth:4180/oauth2/auth
      traefik.http.middlewares.oauth-verify.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.oauth-verify.forwardAuth.authResponseHeaders: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Redirect,Set-Cookie
      # traefik.http.middlewares.oauth-verify.forwardAuth.authResponseHeaders: X-Auth-Request-User,X-Auth-Request-Email,Set-Cookie
      traefik.http.middlewares.oauth-signin.errors.service: oauth@docker
      traefik.http.middlewares.oauth-signin.errors.status: '401'
      traefik.http.middlewares.oauth-signin.errors.query: /oauth2/sign_in # ?rd=https://api.${DOMAIN}/whoami
      # traefik.http.middlewares.oauth-signin.errors.query: /oauth2/start?rd=https://localhost/example
      traefik.http.routers.oauth-https.rule: Host(`api.${DOMAIN}`) && PathPrefix(`/oauth2`)
      traefik.http.routers.oauth-https.tls.certResolver: mytlschallenge
      traefik.http.routers.oauth-https.tls: 'true'
      traefik.http.routers.oauth-https.entrypoints: 'https'
      traefik.http.routers.oauth-https.service: oauth@docker
      traefik.http.routers.oauth-http.rule: Host(`api.${DOMAIN}`) && PathPrefix(`/oauth2`)
      traefik.http.routers.oauth-http.entrypoints: 'http'
      traefik.http.routers.oauth-http.middlewares: 'redirect-web-secure'
      traefik.http.services.oauth.loadbalancer.server.port: '4180'
    environment:
      OAUTH2_PROXY_CLIENT_ID: '${OAUTH2_PROXY_CLIENT_ID}'
      OAUTH2_PROXY_CLIENT_SECRET: '${OAUTH2_PROXY_CLIENT_SECRET}'
      OAUTH2_PROXY_COOKIE_DOMAIN: '${DOMAIN}'
      OAUTH2_PROXY_COOKIE_REFRESH: '1h'
      OAUTH2_PROXY_COOKIE_SECURE: 'true'
      OAUTH2_PROXY_COOKIE_SECRET: '${OAUTH2_PROXY_COOKIE_SECRET}'
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_FOOTER: '-my test footer-'
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      OAUTH2_PROXY_PASS_BASIC_AUTH: 'false'
      OAUTH2_PROXY_PASS_USER_HEADERS: 'true'
      OAUTH2_PROXY_PASS_HOST_HEADER: 'true'
      OAUTH2_PROXY_PROVIDER: 'OIDC'
      OAUTH2_PROXY_REVERSE_PROXY: 'true'
      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: 'true'
      OAUTH2_PROXY_SET_XAUTHREQUEST: 'true'
      # OAUTH2_PROXY_WHITELIST_DOMAIN: 'localhost'
      OAUTH2_PROXY_REDIRECT_URL: 'https://api.${DOMAIN}/oauth2/callback'
      OAUTH2_PROXY_LOGIN_URL: 'https://${OIDC_DOMAIN}/oauth2/authorize'
      OAUTH2_PROXY_PROFILE_URL: 'https://${OIDC_DOMAIN}/oauth2/userInfo'
      OAUTH2_PROXY_REDEEM_URL: 'https://${OIDC_DOMAIN}/oauth2/token'
      OAUTH2_PROXY_SCOPE: 'openid'
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: 'MyLogin'
      # OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: 'true'

  whoami:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami-https.middlewares=testheader,oauth-signin,oauth-verify,whoami-stripprefix"
      - "traefik.http.routers.whoami-https.rule=Host(`api.${DOMAIN}`)&& PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami-https.tls.certResolver=mytlschallenge"
      - "traefik.http.routers.whoami-https.tls=true"
      - "traefik.http.routers.whoami-https.entrypoints=https"  
      - "traefik.http.routers.whoami-http.middlewares=redirect-web-secure"
      - "traefik.http.routers.whoami-http.rule=Host(`api.${DOMAIN}`)&& PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami-http.entrypoints=http"
      - "traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes=/whoami"
      - "traefik.http.middlewares.testheader.headers.customrequestheaders.X-Script-Name=test"
```
