### ISSUE TITLE
 [oauthproxy.go:850] Error loading cookied session: Cookie "_oauth2_proxy" not present

### ISSUE THREAD

**Issue by paulpuvi06** [oauth2-proxy/oauth2-proxy#437]
I have implemented Oauth (Provider Azure AD) +  Nginx ingress for my application hosted in AKS. 

mapping path "/"
Authentication and authorization works fine for the root domain url , but when i try to browse child page (/api/build/graphql) i am getting Error loading cookied session: Cookie "_oauth2_proxy".

## Expected Behavior

Status Code: 200 

## Current Behavior

Status Code: 302 

 [oauthproxy.go:850] Error loading cookied session: Cookie "_oauth2_proxy" not present

 Oauth config:

```
    spec:
      containers:
        - args:
            - '--cookie-domain=.example.io'
            - '--cookie-secure=true'
            - '--email-domain=*'
            - '--http-address=0.0.0.0:4180'
            - '--provider=azure'
            - '--set-authorization-header=true'
            - '--upstream=http://example.svc.cluster.local:80'
          env:
            - name: OAUTH2_PROXY_AZURE_TENANT
              value: XXXXX
            - name: OAUTH2_PROXY_CLIENT_ID
              value: XXXXXX
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client_secret
                  name: oauth2-proxy-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  key: cookie_secret
                  name: oauth2-proxy-secret
          image: quay.io/pusher/oauth2_proxy
```

Ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: dns
    certmanager.k8s.io/cluster-issuer: letsencrypt-dns
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: 'https://$host/oauth2/start?rd=$request_uri'
    nginx.ingress.kubernetes.io/auth-url: 'https://$host/oauth2/auth'

```
