### ISSUE TITLE
Using OAuth2 Proxy to protect an entire domain

### ISSUE THREAD

**Issue by radical-edo** [oauth2-proxy/oauth2-proxy#439]
Hi,
I've run into a bit of a problem and can't seem to get over this hump. Trying to configure OAuth2 Proxy to provide basic authentication for my entire app. Goes without saying that it's all running on K8s. The app is composed of multiple microservices that together build the whole app. As an added difficulty I want to run this under a single domain. Don't want to obtain and register sub-domains. Don't think that it should be necessary. If I can force redirect from my main domain to a sub-domain and make the login then it should be possible to force the redirect to a path under one domain.

But, to be honest the "redirect" part is the problem I'm facing. Can't seem to make it work. If I go to my `/ouath2` path I can sign in via Google, but I'm not forced to sign in when I'm going to just `/`, which is crucial.

Here is the `Ingress` (Nginx Ingress Controller) configuration that I'm using

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/auth-url: "https://gcp-deployment.pl/oauth2/auth"
    kubernetes.io/auth-signin: "https://gcp-deployment.pl/oauth2/start?rd=https://$host$request_uri$is_args$args"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
  name: gcp-deployment-ingress
  namespace: default
spec:
  tls:
    - hosts:
        - gcp-deployment.pl
      secretName: gcp-deployment-tls
  rules:
  - host: gcp-deployment.pl
    http:
      paths:
        - backend:
            serviceName: gcp-deployment-nginx-service
            servicePort: 80
          path: /
        - backend:
            serviceName: oauth2-proxy
            servicePort: http
          path: /oauth2

```
Should you need some more info about the configuration YAMLs that I use please let me know.

#### Versions used:
- K8s cluster  `1.14.10-gke.17`
- OAuth2 Proxy chart - `2.2.2`
- OAuth2 Proxy app Version - `4.0.0`

Any help with this would be greatly appreciated.

**Comment by JoelSpeed** [comment]
Try adding the whitelist domain option with your domain as the value, this should allow you to redirect to any URI under the whitelisted domain

**Comment by radical-edo** [comment]
I'm assuming I should add this `whitelist-domain` as a container args? As it turns out I already have it specified: Here are my args:

```
spec:
      containers:
      - args:
        - --http-address=0.0.0.0:4180
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        - --whitelist-domain=gcp-deployment.pl
        - --cookie-domain=gcp-deployment.pl
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: oauth2-proxy
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: oauth2-proxy
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie-secret
              name: oauth2-proxy
        image: quay.io/pusher/oauth2_proxy:v4.0.0
```
I've added a bit more info in case it might come in handy.

But, the thing is, I've thought that the `whitelist-domain` is needed after the sign-in, not beforehand. And it's only needed if I have `OAuth2` flow under a different domain then the actual app, which I don't. I can't seem to force this Authorization flow for my users :/
