### ISSUE TITLE
Customizable scope(s) as query params

### ISSUE THREAD

**Issue by zuc** [oauth2-proxy/oauth2-proxy#452]
Hi all,
I have an hypothesis about a specific behavior not being currently covered by `oauth2_proxy`, so this issue is meant to:
1. make sure there's no actual solution as of `v5.0.0`
2. make sure my use case is not faulty somewhere
3. ask if you might accept a PR for this proposal

**Context:**
* Multiple Kubernetes clusters hosted on AWS EKS
* [`kube-oidc-proxy`](https://github.com/jetstack/kube-oidc-proxy) deployed in front of each Kubernetes API server in order to handle OIDC authentication for users (as EKS doesn't allow doing this the traditional way described [here](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server))
* [`gangway`](https://github.com/heptiolabs/gangway) deployed in each cluster to allow user self-provisioning of `kubeconfig` files
* One single instance of [`dex`](https://github.com/dexidp/dex) as OIDC connector in order for my users to leverage their Github identity to access clusters
* One single instance of `oauth2_proxy` to protect applications like [`kubernetes-dashboard`](https://github.com/kubernetes/dashboard) and others. These applications are specific for each cluster, therefore I have one instance of `kubernetes-dashboard` for cluster A, one for cluster B, and so on.

**Proposal:**
As I have only one `oauth2_proxy` for all my clusters (that's on purpose), I'd like to have a feature that allows me to add a custom scope to each auth request made by `oauth2_proxy` towards `dex`, in order to leverage [`dex`'s cross-client trust feature](https://github.com/dexidp/dex/blob/master/Documentation/custom-scopes-claims-clients.md#cross-client-trust-and-authorized-party), so that:
* `kubernetes-dashboard` on cluster A has an ingress definition similar to the following: 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-signin: https://sso.mydomain.com/oauth2/start?rd=https://$host$request_uri$is_args$args&additional_scopes=audience:server:client_id:oidc-proxy-cluster-a
    nginx.ingress.kubernetes.io/auth-url: https://sso.mydomain.com/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  rules:
  - host: dashboard.kube-cluster-a.mydomain.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /
  tls:
  - hosts:
    - dashboard.kube-cluster-a.mydomain.com
    secretName: dashboard-tls
```
*(please note the `additional_scopes` param attached to the `/start` endpoint querystring)*

* `oauth_proxy` takes the `additional_scopes` param, splits it by commas and push the resulting array to the provider's default scopes
* `dex` gets those `additional_scopes`, checks whether the current client is actually authorized to issue tokens on behalf of the audience referenced into the `additional_scopes` and then issues an `id_token` similar to the following:
```js
{
    "aud": "oidc-proxy-cluster-a",  // as per the additional_claims value
    "azp": "oauth2_proxy",          // original client_id
    "email": "foo@bar.com",
    // other claims...
}
```
* `oauth2_proxy` passes the `id_token` back to the ingress controller, which in turn adds an `Authorization` header to all the requests directed to `kubernetes-dashboard`, which in turn adds that header to each single request it sends to the cluster's `kube-oidc-proxy` that sits in front of the API server.
* `kube-oidc-proxy` will then see its own client ID (`oidc-proxy-cluster-a`) as one of the token audiences and will reverse-proxy the request back to the API Server. **This way, users can leverage their OIDC identity to access Kubernetes API Server either via `kubectl` (thanks to `gangway`) and via `kubernetes-dashboard`**
* This can be repeated to each different cluster, by simply changing the `additional_scopes` param on the `/start` endpoint querystring to match the `client_id` for that cluster's `kube-oidc-proxy`.

Sorry for the wall of text but I really wanted to make everything super-explicit.
Thanks!
