### ISSUE TITLE
Request for guidance to setup Bearer Token capability with Azure AD

### ISSUE THREAD

**Issue by Fez29** [oauth2-proxy/oauth2-proxy#502]
I am attempting to deploy Oauth2_proxy using Azure AD and require usage of Authorization: Bearer ... JWT tokens to communicate with API's, I would prefer to use Nginx-ingress but am open to possibilities. I have this working with cookies via a browser but the Bearer token use case is much bigger and more useful in real terms.

## Expected Behavior

I would like to have some clear documentation outlining how to achieve major use cases such as this. If this is OIDC 

## Current Behavior

Currently I cannot locate any useful documentation outlining how this is achieved with any ingress controller.

Currently When I try to use Bearer Tokens, oauth2_proxy complains about no cookie being present
````
Error loading cookied session: cookie "_oauth2_proxy" not present
`````
AND
````
Error retrieving session from token in Authorization header: unable to verify jwt token Bearer
````
Then redirects to the login page.

Arguments:

        - --email-domain=*
        - --cookie-secret=$COOKIE-SECRET
        - --provider=azure
        - --azure-tenant=$TENANT_ID
        - --http-address=0.0.0.0:4180
        - --client-id=$CLIENT_ID
        - --client-secret=$SECRET
        - --whitelist-domain=$DOMAIN
        - --set-authorization-header=true
        - --pass-access-token=true
        - --pass-authorization-header=true
        - --set-xauthrequest=true
        - --skip-provider-button=true
        - --pass-basic-auth=true
        - --skip-jwt-bearer-tokens=true
        - --pass-basic-auth=true
        - --pass-user-headers=true
        - --pass-host-header=true

**Comment by JoelSpeed** [comment]
It's unclear to me from your description, are you trying to login to Azure separately, then provide the JWT as a header to the OAuth2 Proxy to skip authentication, or are you trying to get OAuth2 Proxy to provide you a JWT once you've used OAuth2 Proxy to sign in to Azure?

> Currently I cannot locate any useful documentation outlining how this is achieved with any ingress controller.

We don't have that much documentation at the moment for ingress controllers as you describe, mainly due to the fact this project is used more than just with the Kubernetes ecosystem. Thought there is some for nginx-ingress at the bottom of this page https://oauth2-proxy.github.io/oauth2-proxy/configuration

**Comment by Fez29** [comment]
Hi @JoelSpeed 

I have been attempting to call the Azure token endpoint to get a bearer token and and then attempting to call my API to skip the Authentication, (Is this the correct way?) but I just keep getting redirected to the login page and as mentioned previously, Oauth2_proxy complains about no cookie being present.

I do understand that Oauth2_proxy is not just exclusive to Kubernetes.

I will definitely document this if I can get it to work. 100%. I guess I need clarification for the following:

Is the use case possible?
Is the flow I am executing correct?
Is the cookie error fatal or should it work without it and just the Bearer token?

Any chance of getting some assistance and then documenting it from yourself or the likes?

**Comment by ploxiln** [comment]
Yes, that feature was added by https://github.com/oauth2-proxy/oauth2-proxy/pull/65 - and it looks like you found the option `--skip-jwt-bearer-tokens`

The problem is that oauth2-proxy does not like your jwt for some reason:

> Error retrieving session from token in Authorization header: unable to verify jwt token Bearer

I have no idea why, sorry. The referenced pull request also adds the ability to configure additional permitted issuers ...

**Comment by Fez29** [comment]
Ok, Is it possible to get the bearer toekn from Oauth2 proxy instead of directly from Azure?

**Comment by JoelSpeed** [comment]
@Fez29 If you use the OIDC provider and configure it for Azure, you should be able to get the token using the `--set-authorization-header` flag

**Comment by Nojinverse** [comment]
I'm currently facing the same issue as Fez29. any updates on the matter? Thanks in advance.

**Comment by Nojinverse** [comment]
> Hey @Nojinverse, I did manage to resolve my issue, I haven't managed to get around to documenting it as yet but will try my best asap.
> 
> I can help you out if possible.
> What exact issue are you experiencing currently?
> 
> Are you using a personal Azure account or an Enterprize subscription?

Hey @Fez29, I'm using a enterprize subscription and have a very similar setup as you. I'm trying to authorize an event grid subscription validation to an azure function endpoint using the --skip-jwt-bearer-tokens with out luck. I getting the same error as you, cookie missing and unable verify jwt token.  I'm able to validate the azure function using cookies either with a browser or postman using oauth2.

**Comment by Fez29** [comment]
@Nojinverse Ok cool, so I would add the following to the oauth2_proxy config, to allow you to see more info in the logs.

request-logging=true
auth-logging=true
standard-logging=true 

Try with those settings and check if any more errors are shown?

What scope are you using to get your token?

Basically in short the changes I made to get mine to work are as follows:

Inside Azure AD:

In the manifest:

Changed accessTokenAcceptedVersion value from NULL to 2.

"accessTokenAcceptedVersion": 2,

to allow v2 bearer tokens.

Then 

I added the following to my oauth2_proxy config:

        - --provider=azure
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --client-id=${CLIENT_ID}
        - --client-secret=${CLIENT_SECRET}
        - --cookie-domain=${MACHINE_DOMAIN}
        - --cookie-refresh=1h
        - --cookie-secret=${COOKIE_SECRET}
        - --whitelist-domain=${MACHINE_DOMAIN}
        - --azure-tenant=${TENANT_ID}
        - --oidc-issuer-url=https://sts.windows.net/${TENANT_ID}/
        - --set-authorization-header=true
        - --skip-jwt-bearer-tokens=true
        - --pass-authorization-header=true
        - --set-xauthrequest=true
        - --pass-basic-auth=true
        - --request-logging=true
        - --auth-logging=true
        - --standard-logging=true
        - --extra-jwt-issuers=https://login.microsoftonline.com/${TENANT_ID}/v2.0=${APP_ID}

I suspect the 

Due to the fact that Oauth2_proxy calls the v1 url the **"oidc-issuer-url=https://sts.windows.net/${TENANT_ID}/"** is required to allow the browser interactions, then to make the bearer tokens work as well, the **"extra-jwt-issuers=https://login.microsoftonline.com/${TENANT_ID}/v2.0=${APP_ID}"** is required.

The rest is up to the Azure Config and scope being used but the logs should now reflect the actual error.

scope should be "api://${APP_ID}/.default" when getting your token

**Comment by Fez29** [comment]
I plan at some stage to upgrade the default URLS for the Azure Provider to the V2 URL's and test to see if it works to remove the need to have the entry:
`````
oidc-issuer-url=https://sts.windows.net/${TENANT_ID}/
`````

**Comment by Nojinverse** [comment]
@Fez29 It WORKS! Thank you. I was able to successfully validate Azure event subscription, using parts of the example you provided:```

    spec:
      containers:
      - args:
           - --provider=azure
          - --email-domain=*
          - --upstream=url.example.com
          - --http-address=0.0.0.0:4180
          - --cookie-domain=.example.com  
          - --whitelist-domain=.example.com
          - --azure-tenant=<INSERT_TENANT_ID>
          - --skip-jwt-bearer-tokens=true
          - --oidc-issuer-url=https://sts.windows.net/<INSERT_TENANT_ID>/
          - --extra-jwt-issuers=https://login.microsoftonline.com/<INSERT_TENANT_ID>/v2.0=<INSERT_APP_ID>
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            value: <INSERT_APP_ID>
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: <INSERT_APP_ID_SECRET>
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: <INSERT_GENERATED_CODE> (Planning to move these to a Azure keyvault using akv2k8s )

There was a few things that i needed to realize in order to validate subscription but the main issue was the format of --extra-jwt-issuers was wrong which was made clear by your example.  I was able to use "accessTokenAcceptedVersion": null in the manifest of the app registration so I changed it back.

**Comment by Fez29** [comment]
@Nojinverse glad you are sorted 👍

**Comment by zucaritask** [comment]
This comment helped me get my setup working. I extracted the IDToken from a user initiated session and I can pass it as an Authorization header on `curl` and I get access to the upstream.

But, if I want to automate that process from a non-user-initiated flow ("client_credentials" flow), why can't the Authorization header be an AccessToken instead as the one returned from:
`https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token` and described in [Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow).

Question: Can oauth2-proxy do authentication based on JWT Access tokens as in this scenario?

**Comment by ridhoq** [comment]
Hello @Fez29 and @Nojinverse! I have been studying this GitHub issue for a week or so, since I believe I'm trying to accomplish the same thing as what you both have working today. I'm using ingress-nginx (0.32.0) with oauth2-proxy (5.1.0) configured with the Azure provider. My ideal end state is that I should be able to pass a bearer token to an endpoint protected by the oauth2-proxy and bypass the Microsoft AD login workflow.

However, I am not able to get this working as you have described. Here is the script I'm using to retrieve and make a call to my protected endpoint:
```sh
TENANT_ID=TENANT_ID_GOES_HERE
URL=https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/token
APP_ID=APP_ID_GOES_HERE
APP_SECRET=APP_SECRET_GOES_HERE
SCOPE=$APP_ID/.default
PROTECTED_URL=PROTECTED_URL_GOES_HERE
TOKEN=`curl -s --request POST \
  --url $URL  \
  --header 'content-type: multipart/form-data;' \
  --form client_id=$APP_ID \
  --form client_secret=$APP_SECRET \
  --form scope=$SCOPE \
  --form grant_type=client_credentials \
| jq -r .access_token`

echo $TOKEN

curl -v -L \
-H "Authorization: Bearer $TOKEN" \
$PROTECTED_URL
```

I've set ```"accessTokenAcceptedVersion": 2,``` in my app registration manifest and set claims for email in both access and id tokens as seen here:
![image](https://user-images.githubusercontent.com/943533/87600121-6c831200-c6b9-11ea-8eea-33fd846c3c24.png)

My `deployment` config looks like this:

```yaml
    spec:
      containers:
      - name: oauth2-proxy-dev
        image: quay.io/oauth2-proxy/oauth2-proxy:v5.1.0
        imagePullPolicy: Always   
        args:
        - --provider=azure
        - --email-domain=mydomain.com
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --cookie-domain=.mydomain.com
        - --whitelist-domain=.mydomain.com
        - --skip-jwt-bearer-tokens
        - --extra-jwt-issuers=https://login.microsoftonline.com/TENANT_ID_GOES_HERE/v2.0=APP_ID_GOES_HERE
        - --oidc-issuer-url=https://sts.windows.net/TENANT_ID_GOES_HERE/
        - --request-logging=true
        - --auth-logging=true
        - --standard-logging=true
        env:  
        - name: OAUTH2_AZURE_TENANT
          value: TENANT_ID_GOES_HERE
        - name: OAUTH2_PROXY_CLIENT_ID
          value: APP_ID_GOES_HERE
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-secrets
              key: clientSecret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-cookie-secrets
              key: clientCookieSecret
```

With the above config, I see logs like this: 
```
failed to verify bearer token: oidc: id token issued by a different provider, expected "https://sts.windows.net/TENANT_ID_GOES_HERE/" got "https://login.microsoftonline.com/TENANT_ID_GOES_HERE/v2.0"
```

When I change to ```--oidc-issuer-url=https://login.microsoftonline.com/TENANT_ID_GOES_HERE/v2.0```, the browser workflow shows an 500 error.

My question for you, @Fez29 and @Nojinverse - is there something else that you all have configured that I'm missing? I'm pretty much near my wit's end trying to figure how this works, but you both have given me hope that what I'm trying to do is possible! Thanks in advance and hope to hear back from you soon :)

**Comment by pnoguera** [comment]
Hi,

we had a similar use case, basically verify an ID-Token provided by Azure ID. Since this token can have both [versions](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens) v1.0 and v2.0 and both have different issuers, we've managed to configure it by setting the `--extra-jwt-issuers` to both issuers separated by a comma without having to explicitly configure the application manifest for any of the versions as pointed above. 

This is our working example in kubernetes using variables to set the arguments and oatuh2-proxy version 6.0.0

```yaml
    spec: 
        containers:                                                                                                                                                                                                                          
          - name: oauth2-proxy                                                                                                                                                                                                               
            image: quay.io/oauth2-proxy/oauth2-proxy:v6.0.0-amd64                                                                                                                                                                            
            env:                                                                                                                                                                                                                             
              - name: OAUTH2_PROXY_EMAIL_DOMAINS                                                                                                                                                                                             
                value: "*"                                                                                                                                                                                                                   
              - name: OAUTH2_PROXY_PROVIDER                                                                                                                                                                                                  
                value: azure 
              - name: OAUTH2_PROXY_AZURE_TENANT                                                                                                                                                                                              
                value: <TENANT-ID>                                                                                                                                                                                                            
              - name: OAUTH2_PROXY_CLIENT_ID                                                                                                                                                                                                 
                valueFrom:                                                                                                                                                                                                                   
                  secretKeyRef:                                                                                                                                                                                                              
                    name: oauth-secrets                                                                                                                                                                                                      
                    key: clientid                                                                                                                                                                                                            
              - name: OAUTH2_PROXY_CLIENT_SECRET                                                                                                                                                                                             
                valueFrom:                                                                                                                                                                                                                   
                  secretKeyRef:                                                                                                                                                                                                              
                    name: oauth-secrets                                                                                                                                                                                                      
                    key: clientsecret                                                                                                                                                                                                        
              - name: OAUTH2_PROXY_COOKIE_SECRET                                                                                                                                                                                             
                valueFrom:                                                                                                                                                                                                                   
                  secretKeyRef:                                                                                                                                                                                                              
                    name: oauth-secrets                                                                                                                                                                                                      
                    key: cookiesecret                                                                                                                                                                                                        
              - name: OAUTH2_PROXY_COOKIE_EXPIRE                                                                                                                                                                                             
                value: 0h15m0s                                                                                                                                                                                                               
            [...]                                                                                                                                                             
              - name: OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS                                                                                                                                                                                    
                value: "true"                                                                                                                                                                                                                
              - name: OAUTH2_PROXY_EXTRA_JWT_ISSUERS                                                                                                                                                                                         
❯❯              value: https://login.microsoftonline.com/<TENANT-ID>/v2.0=<APP-ID>,https://sts.windows.net/<TENANT-ID>/=<APP-ID>   
              - name: OAUTH2_PROXY_HTTP_ADDRESS                                                                                                                                                                                              
                value: 0.0.0.0:8080                                                                                                                                                                                                          
              - name: OAUTH2_PROXY_UPSTREAMS                                                                                                                                                                                                 
                value: "http://localhost:8081"    
```
I hope this helps
