### ISSUE TITLE
403 - named cookie not present with keycloak provider 

### ISSUE THREAD

**Issue by pedrohjordao** [oauth2-proxy/oauth2-proxy#512]
First off, I'm totally new to the project and I am not an expert on the oauth workflow as a whole.

I have a sample project on kubernetes I've been playing around, the set up should be something like:

- Keycloak to handle user authentication
- Linkerd2 as a mesh
- kubernetes nginx ingress as an ingress controller
- A simple frontend application protected via login in all endpoints

(To reduce the number of the variables in play during this issue I've tried the same steps both with and without linkerd)

My setup is using minikube with the ingress addon enabled

oauth2-proxy setup:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --provider-display-name="Keycloak OIDC" 
        - --oidc-issuer-url=https://keycloak.192.168.39.37.nip.io/auth/realms/frontend
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --email-domain=*
        - --cookie-secret=XXX
        - --client-id=frontend
        - --client-secret=XXX
        - --cookie-name=frontend_id
        - --pass-authorization-header=true
        - --ssl-insecure-skip-verify=true
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
    name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  rules:
  - host: "frontend.example.com"
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2


```

The application Ingress setup looks like the following:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/auth-url: http://$host/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: http://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $frontend_id_upstream_1 $upstream_cookie_frontend_id_1;

      access_by_lua_block {
        if ngx.var.frontend_id_upstream_1 ~= "" then
          ngx.header["Set-Cookie"] = "frontend_id_1=" .. ngx.var.frontend_id_upstream_1 .. ngx.var.auth_cookie:match("(; .*)")
        end
      }
spec:
  rules:
  - host: "frontend.example.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: sa-frontend
          servicePort: 80

```

## Expected Behavior

Given the setup above I'd expect after the login to be able to access the frontend

## Current Behavior

After the login with keycloak I get 

403 Permission Denied
http: named cookie not present

The log for oauth2-proxy on kubernetes shows

```
|[2020/05/02 12:28:04] [oauthproxy.go:867] Error loading cookied session: Cookie "frontend_id" not present                                                                                 │
│ 127.0.0.1 - - [2020/05/02 12:28:04] frontend.example.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/5 │
│ 37.36" 401 21 0.000                                                                                                                                                                          │
│ 127.0.0.1 - - [2020/05/02 12:28:04] frontend.example.com GET - "/oauth2/start?rd=%2Ffavicon.ico" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81. │
│ 0.4044.129 Safari/537.36" 302 362 0.000                                                                                                                                                      │
│ 127.0.0.1 - xxx@gmail.com [2020/05/02 12:28:04] [AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie                                                      │
│ 127.0.0.1 - - [2020/05/02 12:28:04] frontend.example.com GET - "/oauth2/callback?state=e18d2fc657a5d7d473ded1082cf0b0c5%3A%2Ffavicon.ico&session_state=383e54a8-fc16-412f-b1ea-42a05fdde805& │
│ code=5469a241-9efc-458a-acf7-f1bb37faa0d7.383e54a8-fc16-412f-b1ea-42a05fdde805.702f6919-8c89-48ef-8aae-6676a5de39d0" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, li │
│ ke Gecko) Chrome/81.0.4044.129 Safari/537.36" 403 353 0.010 
```

While keycloak's log shows

```
|12:04:29,834 WARN  [org.keycloak.events] (default task-22) type=USER_INFO_REQUEST_ERROR, realmId=frontend, clientId=null, userId=null, ipAddress=172.17.0.1, error=invalid_token, auth_me │
│ thod=validate_access_token  
```

**EDIT**

In the end i was missing the argument `--cookie-secure=false`.

After that i started  having issues with 502s, which were related to the `proxy_buffer_size` of the nginx ingress controller. Changed it to 16k and it worked. It was necessary to change in the oauth2-proxy ingress and the frontend app Ingress (though in the end i changed it globally on the controller)

Hopefully this will help someone in the future. This issue can be closed.
