### ISSUE TITLE
Got ERR_TOO_MANY_REDIRECTS in the browser

### ISSUE THREAD

**Issue by yaakov-berkovitch** [oauth2-proxy/oauth2-proxy#565]
I configured an EnvoyFilter with the external authorization extension (envoy.ext_authz) to redirect traffic that is not authenticated to the oauth2-proxy, and then to the login age. The ID provider I use is Keycloak that is deployed locally on the same cluster where oauth2-poxy is deployed.
It looks that the problem raised because my ID provider is not external.

I followed the following paper https://homelab.blog/blog/devops/Istio-OIDC-Config/ to deploy the envoy filter and oauth2-proxy.

## Expected Behavior

Being redirected to the keycloak login page.

## Current Behavior

Got error in the browser : ERR_TOO_MANY_REDIRECTS. Also appear error in the ouath2-proxy log: 
[2020/05/19 17:18:23] [oauthproxy.go:871] Error loading cookied session: Cookie "_oauth2_proxy" not present

## Steps to Reproduce (for bugs)
Following is the EnvoyFilter.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 80
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        config:
          failure_mode_allow: false
          http_service:
            authorization_request:
              allowed_headers:
                patterns:
                - exact: cookie
            authorization_response:
              allowed_upstream_headers:
                patterns:
                - exact: authorization
                - exact: x-forwarded
            server_uri:
              uri: http://oauthproxy-service.default.svc.cluster.local:4180
              cluster: outbound|4180||oauthproxy-service.default.svc.cluster.local
              timeout: 5.000s

```

Deployment manifest of oauth2-proxy:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=keycloak
            - --provider-display-name="Keycloak"
            - --email-domain=yy.demo.com
            - --email-domain=demo.com
            - --pass-access-token=true
            - --pass-authorization-header=true
            - --set-authorization-header=true
            - --oidc-issuer-url=http://192.168.56.104/auth/realms/asms
            - --login-url=http://192.168.56.104/auth/realms/asms/protocol/openid-connect/auth
            - --redeem-url=http://192.168.56.104/auth/realms/asms/protocol/openid-connect/token
            - --validate-url=http://192.168.56.104/auth/realms/asms/protocol/openid-connect/userinfo
            - --http-address=0.0.0.0:4180
            - --cookie-expire=4h0m0s
            - --whitelist-domain=".demo.com"
            - --cookie-domain=192.168.56.104
            - --standard-logging=true
            - --auth-logging=true
            - --request-logging=true
            - --skip-provider-button=true
            - --upstream=static://200
            - --cookie-secret=KVgwiyRNt_deA_shUsVgoQ==
            - --client-secret=ad4630a2-510d-4c70-b924-64fee09748bb
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: asms
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: ad4630a2-510d-4c70-b924-64fee09748bb
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: KVgwiyRNt_deA_shUsVgoQ==
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              value: 192.168.56.104
          image: bitnami/oauth2-proxy:latest
          imagePullPolicy: IfNotPresent
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauthproxy-service
  namespace: default
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy

```

## Your Environment

Deploy oauth2-proxy on Kubernetes cluster v1.18 (standalone - one node for the moment), with istio 1.5.2 as ingress controller.
The oauth2-proxy version : bitnami/oauth2-proxy:latest (5.1.1) from docker hub .

- Version used:
5.1.1
