### ISSUE TITLE
Can't pass user data through request headers

### ISSUE THREAD

**Issue by josephElhajj** [oauth2-proxy/oauth2-proxy#585]
_Disclaimer; quite new to this setup so terminologies may be mixed up_

Currently, I have a k8s setup with an nginx controller processing all incoming requests, an OAuth-proxy2 running to authenticate all those requests. It is connected to an azure AD
My problem is; I can't seem to append the email even though I added all annotations needed.

## Expected Behavior

-email can be appended to the headers of a request through X-Auth-Request-Email

## Current Behavior
all data is retrieved correctly in the logs of the oauth2-proxy but
X-Auth-Request-User, X-Auth-Request-Email, and X-Auth-Request-Preferred-Username are not part of the request

## Possible Solution

fix the configuration to allow the headers to be passed

## Context

Since the cookie is current too big to manage, I have to switch to the redis method to handle the token. I have been trying to find a way to append the email in order to maintain the logging system as it is. as we have a lot of calls, having an extra request to get the user info from the endpoint is not practical.

## Your Environment
deployment.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "oauth2-proxy.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "oauth2-proxy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "oauth2-proxy.name" . }}
    spec:
      containers:
      - args:
        - --provider=azure
        - --email-domain=company.com
        - --email-domain=company.net
        - --cookie-domain=.company.net
        - --redis-connection-url=redis://redis-master.<namespace>.svc.cluster.local:6379
        - --session-store-type=redis
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --standard-logging=true
        - --auth-logging=true
        - --set-xauthrequest=true
        - --pass-access-token=true
        - --pass-authorization-header=true #for decode
        - --set-authorization-header=true
        - --set-basic-auth=false
        env:
          - name: OAUTH2_PROXY_AZURE_TENANT
            value: {{ .Values.oauth_tenant }}
          - name: OAUTH2_PROXY_CLIENT_ID
            value: {{ .Values.oauth_client }}
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: {{ .Values.oauth_key }}
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: {{ .Values.oauth_cookie_secret }}
        image: quay.io/pusher/oauth2_proxy:latest
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        imagePullPolicy: IfNotPresent
        name: {{ include "oauth2-proxy.name" . }}
        ports:
          - containerPort: {{ .Values.containerPort }}
            protocol: TCP
```
ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "oauth2-proxy.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-Email, X-Auth-Request-User, X-Forwarded-Access-Token"
spec:
  rules:
    - host: {{ .Values.baseUrl }}
      http:
        paths:
          - path: /oauth2
            backend:
              serviceName: {{ include "oauth2-proxy.name" . }}-svc
              servicePort: {{ .Values.containerPort }}
  tls:
  - hosts:
    - {{ .Values.baseUrl }}
    secretName: {{ .Values.certSecret }}
```
- Version used:
latest as of 28/05/2020

- Related Issues?
https://github.com/oauth2-proxy/oauth2-proxy/issues/354

Thank you in advance for your help
