### ISSUE TITLE
Azure AD: Invalid Account

### ISSUE THREAD

**Issue by kevin93w** [oauth2-proxy/oauth2-proxy#599]
## Expected Behavior
After logging in using our Azure AD provider and tenant, I would expect to be redirected back. It should set the cookie and show me the contents of the upstream container.

## Current Behavior
After successfully logging in, I get redirected to the callback URL. It does not set the cookie and returns "403 Permission Denied: Invalid Account".

## Possible Solution
I've been trying all sorts of different configurations in both Azure AD and the application config. Nothing seems to fix the problem, the tenant works as expected so I assume authentication goes well. Perhaps it has something to do with permissions.

## Steps to Reproduce (for bugs)

1. Use the below K8S specification to start the container, fill in the hidden variables (tenant id, etc.)
2. Go to localhost:30000
3. Try to login using your Azure AD tenant
4. You will get redirected and see the 403 message

## Context
Because I cannot get redirected properly, I'm currently unable to implement authentication and authorization as expected. I suspect making a mistake in the configuration, hopefully when that is resolved the authentication will complete and I'm able to offer the contents of the upstream container.

## Your Environment
My specification created by a Helm chart and used to run the containers:

```
- apiVersion: v1
  kind: Service
  metadata:
    name: proxy
  spec:
    clusterIP: None
    ports:
    - name: http
      port: 4180
    selector:
      app: proxy


- apiVersion: v1
  kind: Service
  metadata:
    name: proxy-nodeport
  spec:
    ports:
    - port: 4180
      targetPort: 4180
      nodePort: 30000
    selector:
      app: proxy
    type: NodePort

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: proxy
    name: proxy
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: proxy
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: proxy
      spec:
        containers:
        - image: quay.io/oauth2-proxy/oauth2-proxy:v5.1.0
          imagePullPolicy: Always
          name: proxy
          env:
          - name: NODE_ENVIRONMENT
            value: development
          - name: OAUTH2_PROXY_COOKIE_SECRET
            value: "<cookie-secret>"
          - name: OAUTH2_PROXY_EMAIL_DOMAINS
            value: "[*]"
          - name: OAUTH2_PROXY_HTTP_ADDRESS
            value: "0.0.0.0:4180"
          - name: OAUTH2_PROXY_UPSTREAM
            value: "<upstream-url:port>"
          - name: OAUTH2_PROXY_REDIRECT_URL
            value: "http://localhost:30000/oauth2/callback"
          - name: OAUTH2_PROXY_COOKIE_HTTPONLY
            value: "true"
          - name: OAUTH2_PROXY_COOKIE_SECURE
            value: "false"
          - name: OAUTH2_PROXY_PROVIDER
            value: "azure"
          - name: OAUTH2_PROXY_AZURE_TENANT
            value: "<tenant-id>"
          - name: OAUTH2_PROXY_CLIENT_ID
            value: "<client-id>"
          - name: OAUTH2_PROXY_CLIENT_SECRET
            value: "<client-secret>"
          - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
            value: "true"
          ports:
          - containerPort: 4180
          resources:
            requests:
              cpu: 0.1
              memory: 64M
            limits:
              cpu: 1
              memory: 64M
```

Output logging in the container:

```
[2020/06/02 14:19:17] [oauthproxy.go:261] OAuthProxy configured for Azure Client ID: <client-id>
[2020/06/02 14:19:17] [oauthproxy.go:267] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domain: path:/ samesite: refresh:disabled
[2020/06/02 14:19:17] [http.go:92] HTTP: listening on 0.0.0.0:4180
[2020/06/02 14:19:25] [oauthproxy.go:867] Error loading cookied session: Cookie "_oauth2_proxy" not present
192.168.65.3 - - [2020/06/02 14:19:25] localhost:30000 GET - "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" 302 356 0.000
[2020/06/02 14:19:26] [requests.go:25] 200 GET https://graph.windows.net/me?api-version=1.6 {"odata.metadata":"https://graph.windows.net/myorganization/$metadata#directoryObjects/@Element","odata.type":"Microsoft.DirectoryServices.User","objectType":"User", etc.}
<ip-address> - <email> [2020/06/02 14:19:26] [AuthFailure] Invalid authentication via OAuth2: unauthorized
```

- Version used: latest on K8S version 1.16.5
