### ISSUE TITLE
How to redirect my Kubernetes Dashboard to Oauth Proxy?

### ISSUE THREAD

**Issue by riupie** [oauth2-proxy/oauth2-proxy#609]
I want to use Dex as authentication for my Kubernetes Dashboard. This dex integrate with LDAP. It works successfully when I combine it with Gangway to generate my kubeconfig file. But it confused me when it comes to kubernetes dashboard.

By default, if I want to expose my dashboard I will expose it via Ingress controller:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.org/ssl-services: kubernetes-dashboard
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /
```

Then, when I want to use oauth2 so it will authenticate to my Dex, I will add this config to my dashboard ingress:

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.org/ssl-services: kubernetes-dashboard
    nginx.ingress.kubernetes.io/auth-url: "https://dashboard.example.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://dashboard.example.com/oauth2/start?rd=https://$host$request_uri$is_args$args"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /
```
And add 1 ingress for my oauth2-proxy:

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "tls-ca-issuer"
    ingress.kubernetes.io/force-ssl-redirect: "true"
  name: oauth-proxy
  namespace: auth-system
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 8080
        path: /oauth2
  tls:
  - hosts:
    - dashboard.example.com
    secretName: kubernetes-dashboard-external-tls
```

Is there any missconfig on my Ingress?
## Expected Behavior

When I access dashboard.example.com it will redirect to oauth/dex login form. After it get authenticate it will show my k8s dashboard.

## Current Behavior

When I access dashboard.example.com, it will show 404 not found.

## Your Environment

All inside VMs, each TLS certificate for website is self signed.
