### ISSUE TITLE
"Login session expired" when login to Kubernetes Dashboard

### ISSUE THREAD

**Issue by riupie** [oauth2-proxy/oauth2-proxy#621]
I combine dex + oauth-proxy + k8s-dashboard. I think there is no issue with my dex because I can authenticate it with another service (Gangway). But when I access my dashboard, after login to Dex it get error "Bad request: Login Session Expired".

Oauth2-proxy error logs:

```
[2020/06/15 15:04:12] [oauthproxy.go:871] Error loading cookied session: Cookie "_oauth2_proxy" not present
10.244.2.18 - - [2020/06/15 15:04:12] dashboard.example.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" 401 21 0.000
10.244.2.18 - - [2020/06/15 15:04:12] dashboard.example.com GET - "/oauth2/start?rd=https://dashboard.example.com/" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" 302 296 0.000
10.244.2.18 - johndoe@example.com [2020/06/15 15:04:25] [AuthSuccess] Authenticated via OAuth2: Session{email:johndoe@example.com user:CgRqb2huEgRsZGFw PreferredUsername: token:true id_token:true created:2020-06-15 15:04:25.028727079 +0000 UTC m=+211773.314942108 expires:2020-06-16 15:04:24.028444031 +0000 UTC m=+298172.314659074}
10.244.2.18 - - [2020/06/15 15:04:25] dashboard.example.com GET - "/oauth2/callback?code=bw3mjx6uplrb47xqe55dhggjt&state=14606b9082d5b0070e70f17f415004fc%3A%2F" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" 302 24 0.028
10.244.2.18 - johndoe@example.com [2020/06/15 15:04:26] dashboard.example.com GET - "/oauth2/auth" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" 202 0 0.000
```

Dex logs:
```
time="2020-06-15T15:04:23Z" level=info msg="performing ldap search OU=People,DC=rahmatawe,DC=com sub (&(objectClass=person)(mail=johndoe@example.com))" 
time="2020-06-15T15:04:23Z" level=info msg="username \"johndoe@example.com\" mapped to entry cn=john,ou=People,dc=rahmatawe,dc=com" 
time="2020-06-15T15:04:23Z" level=info msg="login successful: connector \"ldap\", username=\"john\", email=\"johndoe@example.com\", groups=[]" 
time="2020-06-15T15:04:38Z" level=error msg="Failed to get auth request: not found"
```
Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: auth-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --cookie-secure=false
        - --provider=oidc
        - --client-id=rahmatawe-app
        - --client-secret=XmT7EHo27skGchX0yLQNTYXibm3aNkx5
        - --oidc-issuer-url=https://dex.example.com
        - --email-domain=*
        - --set-authorization-header=true
        - --ssl-insecure-skip-verify
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: fOksHBeg7wH1E9OPThGh8g==
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
```
Ingress:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kubernetes-dashboard
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.org/ssl-services: kubernetes-dashboard
    nginx.ingress.kubernetes.io/auth-url: https://dashboard.example.com/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://dashboard.example.com/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 443
        path: /
```

Is there any parameter should be pass to dex from oauth config? Based on the dex log above, it wont claim group to authenticate and `Failed to get auth request: not found`.
