### ISSUE TITLE
Invalid Account - 403 Permission Denied 

### ISSUE THREAD

**Issue by rezagh2** [oauth2-proxy/oauth2-proxy#622]
Setting up oauth2-proxy 5.1.1 on Minikube and a locally installed Dex. I assume this should be the simplest use case for oauth2-proxy.

For the sake of completeness I should add that there is also an Envoy filter (istio 1.6) that intercepts traffic and forwards to the auth proxy. 

## Expected Behavior

Expect the callback to continue to the destination url after successful login.
The logs of Dex shows **login successful** but when the call back returns to oauth2-proxy it gives:

403 Permission Denied
Invalid Account

## Current Behavior

call back comes back with the code but the cookie is not set.

proxy logs

```
2020-06-17T02:11:56.012080927Z [2020/06/17 02:11:56] [oauthproxy.go:871] Error loading cookied session: Cookie "_oauth2_proxy" not present
2020-06-17T02:11:56.012120006Z 127.0.0.1 - - [2020/06/17 02:11:56] 10.106.39.73 GET - "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36" 302 286 0.000
2020-06-17T02:12:05.511330706Z 127.0.0.1 - admin@example.com [2020/06/17 02:12:05] [AuthFailure] Invalid authentication via OAuth2: unauthorized
2020-06-17T02:12:05.512923039Z 127.0.0.1 - - [2020/06/17 02:12:05] 10.106.39.73 GET - "/oauth2/callback?code=iozc276bsp7kt544iqmund5yd&state=38514b7df6860b925ece8160523c02ff%3A%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36" 403 338 0.006
2020-06-17T02:12:05.707892856Z [2020/06/17 02:12:05] [oauthproxy.go:871] Error loading cookied session: Cookie "_oauth2_proxy" not present
2020-06-17T02:12:05.707932747Z 127.0.0.1 - - [2020/06/17 02:12:05] 10.106.39.73 GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36" 302 297 0.000

```
![image](https://user-images.githubusercontent.com/57375907/84847189-e496f180-b093-11ea-8ec7-f9b5878fbaed.png)

## Steps to Reproduce
proxy config

```
    spec:
      containers:
        - args:
            - --cookie-secure=false
            - --upstream=file://dev/null
            - --http-address=0.0.0.0:4180
            - --cookie-secret=somerandomstring12341234567890AB
            - --client-id=example-app
            - --client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
            - --email-domain="example.com"
            - --provider=oidc
            - --provider-display-name="Dex oidc"
            - --redirect-url=http://10.106.39.73/oauth2/callback
            - --oidc-issuer-url=http://192.168.64.1:5556/dex
            - --pass-access-token=true
            - --pass-authorization-header=true
            - --set-authorization-header=true
            - --standard-logging=true
            - --auth-logging=true
            - --request-logging=true
            - --skip-provider-button=true
          image: quay.io/pusher/oauth2_proxy:v5.1.1
```
Dex config is the default only additions:

```
staticClients:
- id: example-app
  redirectURIs:
  - 'http://10.106.39.73/oauth2/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

```
Envoy filter that intercepts calls to forward to auth proxy:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  #namespace: istio-system
  namespace: foo
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      #context: GATEWAY
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        #name: envoy.filters.http.ext_authz
        name: envoy.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
          http_service:
            server_uri:
              uri: http://oauthproxy-service.default.svc.cluster.local:4180
              cluster: outbound|4180||oauthproxy-service.default.svc.cluster.local
              timeout: 3s

            authorizationRequest:
              allowedHeaders:
                patterns:
                 - exact: "cookie"
                 - exact: "x-forwarded-access-token"
                 - exact: "x-forwarded-user"
                 - exact: "x-forwarded-email"
                 - exact: "authorization"
                 - exact: "x-forwarded-proto"
                 - exact: "proxy-authorization"
                 - exact: "user-agent"
                 - exact: "x-forwarded-host"
                 - exact: "from"
                 - exact: "x-forwarded-for"
                 - exact: "accept"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"
            authorizationResponse:
               allowedClientHeaders:
                 patterns:
                 - exact: "location"
                 - exact: "proxy-authenticate"
                 - exact: "set-cookie"
                 - exact: "authorization"
                 - exact: "www-authenticate"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"
               allowedUpstreamHeaders:
                 patterns:
                 - exact: "location"
                 - exact: "proxy-authenticate"
                 - exact: "set-cookie"
                 - exact: "authorization"
                 - exact: "www-authenticate"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"              
```

- Version used: 
5.1.1
