### ISSUE TITLE
502 Bad Gateway after successful login

### ISSUE THREAD

**Issue by rezagh2** [oauth2-proxy/oauth2-proxy#646]
I had setup envoy filter -> oauth2 proxy -> Dex before in a local setting successfully [(here)](https://github.com/oauth2-proxy/oauth2-proxy/issues/622) but when moving it to a production environment with all the bell and whistles then the callback url doesn't return to the originating service url.

## Expected Behavior

I expect the call back url to send me to the originating url at httpbin.dex.com.au.

## Current Behavior

This is what I see in the logs... **successful auth** and failed redirect.

```

[2020/06/30 01:22:57] [oauthproxy.go:867] Error loading cookied session: Cookie "_oauth2_proxy" not present
10.42.12.74 - - [2020/06/30 01:22:57] httpbin.dev.com.au GET - "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" 302 319 0.000
10.203.104.11 - - [2020/06/30 01:22:57] 10.42.7.89:4180 GET - "/ping" HTTP/1.1 "kube-probe/1.15" 200 2 0.000
10.42.3.8 - reza@st.com.au [2020/06/30 01:22:59] [AuthSuccess] Authenticated via OAuth2: Session{email:reza@st.com.au user:CkZDTj1SZXphIEdoYWZhcmksT1U9VGVjaG5vbG9neSxPVT1EZXBhcnRtZW50cyxEQz1mb3hzcG9ydHMsREM9Y29tLERDPWF1EgRsZGFw PreferredUsername: token:true id_token:true created:2020-06-30 01:22:59.528646254 +0000 UTC m=+60.050483351 expires:2020-07-01 01:22:58.528381792 +0000 UTC m=+86459.050218735}
10.42.3.8 - - [2020/06/30 01:22:59] oauth.dev.com.au GET - "/oauth2/callback?code=anhwn6rpdytd4ytxjccajnjtr&state=da1eef2a72f6ddf85f5408760234cd21%3A%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" 302 24 0.023
[2020/06/30 01:22:59] [oauthproxy.go:867] Error loading cookied session: Cookie "_oauth2_proxy" not present
10.42.3.8 - - [2020/06/30 01:22:59] oauth.dev.com.au GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" 302 330 0.000

```
There is only a _oauth2_proxy_csrf cookie on .dev.com.au and no _oauth2_proxy cookie.

Oauth2 proxy config:

```
    helm:
      releaseName: oauth2-proxy
      valueFiles:
      - values.yaml
      values: |
        config:
          clientID: example-app
          clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0
          cookieSecret: somerandomstring12341234567890AB

        extraArgs:
          provider: "oidc"
          provider-display-name: "Dex Login"
          redirect-url: "https://oauth.dev.com.au/oauth2/callback"
          oidc-issuer-url: "https://dex.dev.com.au/dex"
          email-domain: "*"
          upstream: "static://200"
          cookie-secure: "false"
          http-address: "0.0.0.0:4180"
          cookie-domain: ".dev.com.au"
          session-store-type: "cookie"
          pass-basic-auth: "false"
          pass-access-token: "true"
          pass-authorization-header: "true"
          set-authorization-header: "true"
          ssl-insecure-skip-verify: "true"
          set-xauthrequest: "true"
          standard-logging: "true"
          auth-logging: "true"
          request-logging: "true"
          skip-provider-button: "true"
```
If i totally comment out cookie-domain the error changes to a 403, AuthFailure and each of dex.dex and oauth.dex will get a csurf cookie.

```
10.42.3.8 - reza@st.com.au [2020/06/30 02:17:15] [AuthFailure] Invalid authentication via OAuth2: unable too obtain CSRF cookie
10.42.3.8 - - [2020/06/30 02:17:15] oauth.dev.com.au GET - "/oauth2/callback?code=uli46shpbdze432insfply4ht&state=10c94a70586600384440a109c679425f%3A%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" 403 353 0.022
[2020/06/30 02:17:15] [oauthproxy.go:871] Error loading cookied session: Cookie "_oauth2_proxy" not present
10.42.3.8 - - [2020/06/30 02:17:15] oauth.dev.com.au GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" 302 330 0.000

```
Any ideas on this is appreciate.
Thanks

## Your Environment
- Version used:
oauth2 proxy: 6.0.0 via helm
kubernetes 1.15.11
istio (envoy filter): 1.6.1

**Comment by JoelSpeed** [comment]
Firstly, please update to the latest version, or at a minimum 5.1.1

Secondly, you may need to look at the whitelist domain option which specifies which redirects are allowed at the end of the authentication flow, `whitelist-domain: ".dev.com.au"` should probably work

Also please verify the the envoy filter is sending the `rd` parameter that specifies where the redirection should go

**Comment by rezagh2** [comment]
Thanks @JoelSpeed for your reply. Upgraded to 6.0.0. whitelist-domain added. Not much progress though.
EnvoyFilter below is crazily populated with headers. What exactly is the `rd` parameter?
```
            authorizationRequest:
              allowedHeaders:
                patterns:
                 - exact: "cookie"
                 - exact: "x-forwarded-access-token"
                 - exact: "x-forwarded-user"
                 - exact: "x-forwarded-email"
                 - exact: "authorization"
                 - exact: "x-forwarded-proto"
                 - exact: "proxy-authorization"
                 - exact: "user-agent"
                 - exact: "x-forwarded-host"
                 - exact: "from"
                 - exact: "x-forwarded-for"
                 - exact: "accept"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"
                 - prefix: _oauth2_proxy
                 - exact: cookie
            authorizationResponse:
               allowed_upstream_headers:
                 patterns:
                 - exact: authorization
                 - exact: Cookie
                 - exact: cookie
                 - prefix: x-forwarded
                 - prefix: x-auth-request
                 - prefix: _oauth2_proxy
               allowedClientHeaders:
                 patterns:
                 - exact: "location"
                 - exact: "proxy-authenticate"
                 - exact: "set-cookie"
                 - exact: "authorization"
                 - exact: "www-authenticate"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"
               allowedUpstreamHeaders:
                 patterns:
                 - exact: "location"
                 - exact: "proxy-authenticate"
                 - exact: "set-cookie"
                 - exact: "authorization"
                 - exact: "www-authenticate"
                 - exact: "x-forwarded"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"                     
```
I don't exactly see what the filter sends to oauth2 proxy but the request that lands in the login page looks like this:

```
Request URL: https://httpbin.dev.com.au/
Request Method: GET
Status Code: 302 
location: https://dex.dev.com.au/dex/auth?approval_prompt=force&client_id=example-app&redirect_uri=https%3A%2F%2Foauth.dev.com.au%2Foauth2%2Fcallback&response_type=code&scope=openid+email+profile&state=59169ba715334374cc309b502a356523%3A%2F
```
Latest oauth2 container args:
```
  containers:
    - args:
        - '--http-address=0.0.0.0:4180'
        - '--auth-logging=true'
        - '--cookie-domain=.dev.com.au'
        - '--cookie-secure=false'
        - '--email-domain=*'
        - '--http-address=0.0.0.0:4180'
        - '--oidc-issuer-url=https://dex.dev.com.au/dex'
        - '--pass-access-token=true'
        - '--pass-authorization-header=true'
        - '--pass-basic-auth=true'
        - '--provider=oidc'
        - '--provider-display-name=Dex Login'
        - '--redirect-url=https://oauth.dev.com.au/oauth2/callback'
        - '--request-logging=true'
        - '--reverse-proxy=false'
        - '--session-store-type=cookie'
        - '--set-authorization-header=true'
        - '--set-xauthrequest=true'
        - '--skip-provider-button=true'
        - '--ssl-insecure-skip-verify=true'
        - '--ssl-upstream-insecure-skip-verify=true'
        - '--standard-logging=true'
        - '--upstream=static://200'
        - '--whitelist-domain=.dev.com.au'
```

An interesting observation is that on Dex side when i replace the ldap integration with a static username/password the whole flow from envoy filter works; it gets a cookie but eventually lands on oauth2's url https://oauth.dev.com.au/ and says on the page "Authenticated" instead of originator url https://httpbin.dev.com.au/ ...

**Comment by sushiMix** [comment]
Hello, could you check the log at your ingress controller (I assume your are using kubernetes with helm).
You should have header too long issue :
It can be solved by tuning http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size (an annotation is available for each ingress in kubernetes).
The correct target value is not very clear as depending on the max header size.

**Comment by rezagh2** [comment]
@sushiMix this was gold mate thanks. This took me one step forward. Another issue I observe as explained above is that after success login it lands on the oauth proxy home page https://oauth.dev.com.au and only says "Authenticated" instead of the original url. Any idea on that one? Thanks.

**Comment by JoelSpeed** [comment]
You're getting the `Authenticated` because you set a static upstream, I imagine what you wanted to happen is that after you login, you are redirected back to the original path? To do this, you need to pass the original path to the initial request to OAuth2 Proxy `(eg `/oauth2/start?rd=http://foo.example/bar`), or set it via `X-Auth-Request-Redirect` as a header when making that call

I'm not familiar with Envoy so I can't tell you how to do that unfortunately

**Comment by camper42** [comment]
same problem after upgrade to v6.0.0 from v5.1.1

```
      containers:
      - args:
        - --provider=oidc
        - --redirect-url=https://oauth2.my-domain/oauth2/callback
        - --oidc-issuer-url=https://auth.my-domain
        - --email-domain=my-domain
        - --cookie-domain=.my-domain
        - --whitelist-domain=.my-domain
        - --set-authorization-header=true
        - --https-address=:4180
        - --scope=openid email profile groups offline_access
        - --tls-cert-file=/etc/oauth2_proxy/ssl/tls.crt
        - --tls-key-file=/etc/oauth2_proxy/ssl/tls.key
        - --silence-ping-logging
```

**Comment by camper42** [comment]
ingress nginx log
```
172.18.4.4 - - [07/Jul/2020:17:35:19 +0800] "GET /oauth2/callback?code=ewcbfjivn5eanrr4h7bngh2rt&state=51a73eda647fbe8768607ad7b4a8b343%3A%2F HTTP/2.0" 502 158 "https://auth.my-domain/auth/ldap?req=apwuyy6ssw2asyag3z4y42yj4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0" 174 0.041 [our-system-oauth2-proxy-443] [] 172.18.4.20:4180 0 0.044 502 a801247a2d14efdd241d6a5384bb2b12
```

oauth2-proxy log
```
172.18.5.188:33016 - - [2020/07/07 09:35:19] oauth2.capps.svc.douban GET - "/oauth2/callback?code=ewcbfjivn5eanrr4h7bngh2rt&state=51a73eda647fbe8768607ad7b4a8b343%3A%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0" 302 24 0.040
```

**Comment by rezagh2** [comment]
> You're getting the `Authenticated` because you set a static upstream, I imagine what you wanted to happen is that after you login, you are redirected back to the original path? To do this, you need to pass the original path to the initial request to OAuth2 Proxy `(eg `/oauth2/start?rd=[http://foo.example/bar`](http://foo.example/bar%60)), or set it via `X-Auth-Request-Redirect` as a header when making that call
> 
> I'm not familiar with Envoy so I can't tell you how to do that unfortunately

@JoelSpeed I cannot make sense of this. I expect the redirect to be done by oauth proxy as it's part of oauth dance. why should the initial request be aware of this rd?

**Comment by camper42** [comment]
thx @sushiMix 
I changed `proxy_buffer_size` to `8k(origin 4k)` , and 502 is gone.

with oauth2-proxy:v5.1.1, `proxy_buffer_size: 4k` is fine

**Comment by JoelSpeed** [comment]
@rezagh2 When you hit the URL you want to access and envory redirects you, where does it redirect you to? How do you configure this? If you can add an `rd` or a header to that redirection request, then that is what will trigger the redirect at the end of the flow, otherwise it will just route you to the root of the OAuth2 Proxy application

**Comment by rezagh2** [comment]
Added a redirect header to the envoy filter. I expect this behaviour should be default on the Envoy filter but that's a different discussion. Thanks for the tip.

```
   patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
          http_service:
            server_uri:
              uri: http://oauth2-proxy.istio-extensions.svc.cluster.local
              cluster: outbound|80||oauth2-proxy.istio-extensions.svc.cluster.local
            authorization_request:
              headers_to_add:
              - key: x-auth-request-redirect
                value: "https://the-original-url"
              allowed_headers:
                patterns:
                 - ...

```
