### ISSUE TITLE
Unable to redirect back to original site after grant access

### ISSUE THREAD

**Issue by NingPekin** [oauth2-proxy/oauth2-proxy#672]
## Expected Behavior

1. Access http://grafana.test:15031/login
2. Redirect to dex
https://dex.example.com:32000/auth?approval_prompt=force&client_id=grafana&redirect_uri=http%3A%2F%2Fgrafana.test%3A15031%2Flogin%2Fgeneric_oauth&response_type=code&scope=openid+email+profile&state=d392ba8c47961deca1f234ce72f871f1%3A%2Flogin
3. Choose one login method, for example email:
https://dex.example.com:32000/auth/local?req=w36q5wqgoay5iekel5kbuufbr
4. Fill in credentials, redirect to grant access page
https://dex.example.com:32000/approval?req=w36q5wqgoay5iekel5kbuufbr
5. Click grant access page
Should be redirect to original site, http://grafana.test:15031/login

## Current Behavior

1. Access http://grafana.test:15031/login
2. Redirect to dex
https://dex.example.com:32000/auth?approval_prompt=force&client_id=grafana&redirect_uri=http%3A%2F%2Fgrafana.test%3A15031%2Flogin%2Fgeneric_oauth&response_type=code&scope=openid+email+profile&state=d392ba8c47961deca1f234ce72f871f1%3A%2Flogin
3. Choose one login method, for example email:
https://dex.example.com:32000/auth/local?req=w36q5wqgoay5iekel5kbuufbr
4. Fill in credentials, redirect to grant access page
https://dex.example.com:32000/approval?req=w36q5wqgoay5iekel5kbuufbr
5. Click grant access page
Get redirect to http://grafana.test:15031/login/generic_oauth?code=bha5ffytppxdsublxkxttd53c&state=1d38214f346b4b7dba253a6359a1ab0a%3A%2Flogin

** oauth log **
```bash
/ # oauth2-proxy --provider=oidc --provider-display-name="Dex" --oidc-issuer-url=https://dex.example.com:32000 --login-ur
l=https://dex.example.com:32000/auth --redeem-url=https://dex.example.com:32000/token --ssl-insecure-skip-verify=true  --
email-domain=* --redirect-url=http://grafana.test:15031/login/generic_oauth  --validate-url=https://dex.example.com:32000
/user --pass-basic-auth=false --pass-access-token=true  --http-address=0.0.0.0:4180 --cookie-secret=**** --pass-authorization-header=true  --cookie-secure=false --cookie-samesite=lax --skip-provider-button=true
[2020/07/07 20:00:24] [oauthproxy.go:292] OAuthProxy configured for OpenID Connect Client ID: grafana
[2020/07/07 20:00:24] [oauthproxy.go:298] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains: path:/ samesite:lax refresh:disabled
[2020/07/07 20:00:24] [http.go:58] HTTP: listening on 0.0.0.0:4180
[2020/07/07 20:00:28] [oauthproxy.go:912] Error loading cookied session: cookie "_oauth2_proxy" not present
127.0.0.1:53532 - - [2020/07/07 20:00:28] grafana.test:15031 GET - "/login" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 302 284 0.000
[2020/07/07 20:01:06] [oauthproxy.go:912] Error loading cookied session: cookie "_oauth2_proxy" not present
127.0.0.1:53532 - - [2020/07/07 20:01:06] grafana.test:15031 GET - "/login" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 302 284 0.000
[2020/07/07 20:02:16] [oauthproxy.go:912] Error loading cookied session: cookie "_oauth2_proxy" not present
127.0.0.1:53532 - - [2020/07/07 20:02:16] grafana.test:15031 GET - "/login/generic_oauth?code=qbt7tchvsgj736aifxuw24cmk&state=24be61425010196d2ad18b1cfefa2493%3A%2Flogin" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" 302 300 0.000
```
** From the log, I don't know why I am not getting **Auth logs**?
** It keeps saying ` Error loading cookied session: cookie "_oauth2_proxy" not present`
** In my browser, I have  `set-cookie: _oauth2_proxy_csrf=******` instead
** I have also tried using redis, I got `Error loading cookied session: error loading session: http: named cookie not present`

## Your Environment
Use istio ingressgateway ()+ envoy_filter + oauth2-proxy + dex + grafana
oauth2-proxy config:
I ran it maunally since I have to hijack host entries in the pod,
```bash
oauth2-proxy --provider=oidc --provider-display-name="Dex" --oidc-issuer-url=https://dex.example.com:32000 --login-ur
l=https://dex.example.com:32000/auth --redeem-url=https://dex.example.com:32000/token --ssl-insecure-skip-verify=true  --
email-domain=* --redirect-url=http://grafana.test:15031/login/generic_oauth  --validate-url=https://dex.example.com:32000
/user --pass-basic-auth=false --pass-access-token=true  --http-address=0.0.0.0:4180 --cookie-secret=**** --pass-authorization-header=true  --cookie-secure=false --cookie-samesite=lax --skip-provider-button=true
```  

- Version used:
oauth2-proxy:v6.0.0
istio 1.5.6
grafana helm chart 5.0.0
dex 2.23.0

@JoelSpeed  Could you pls take a look at my issue? Many thanks

**Comment by JoelSpeed** [comment]
The redirect URL parameter should be the redirect path to the `/oauth2/callback` path on the OAuth2 Proxy http server. You currently have this set to grafana so you will need to update it. The expectation is that `/login` redirect to OAuth2 Proxy, then to dex, then after dex it goes back to the OAuth2 Proxy, and then redirects back to grafana

In your filter, you need to set there that if the OAuth2 Proxy is not authenticated, it should redirect to `/oauth2/start?rd=http://...`, the rd parameter here controls the final redirection after the authentication flow. You can also use `X-Auth-Request-Redirect` as a header to set this value.

**Comment by NingPekin** [comment]
@JoelSpeed 
I am new to this, do you know how can make istio envoy filter work?
Here is my envoyFilter, I am having a hard time to let it add a header `x-auth-request-redirect`, even though I put `headers_to_add`.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: public-ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        # name: envoy.filters.http.ext_authz
        name: envoy.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
          http_service:
            server_uri:
              uri: http://oauthproxy-service.core-system.svc.cluster.local:4180
              cluster: outbound|4180||oauthproxy-service.core-system.svc.cluster.local
              timeout: 3s
            authorizationRequest:
              headers_to_add:
              - key: x-auth-request-redirect
                value: "http://ip/"
              allowedHeaders:
                patterns:
                 - exact: "cookie"
                 - exact: "x-forwarded-access-token"
                 - exact: "x-forwarded-user"
                 - exact: "x-forwarded-email"
                 - exact: "authorization"
                 - exact: "x-forwarded-proto"
                 - exact: "proxy-authorization"
                 - exact: "user-agent"
                 - exact: "x-forwarded-host"
                 - exact: "from"
                 - exact: "x-forwarded-for"
                 - exact: "accept"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"
                 - prefix: _oauth2_proxy
                 - exact: cookie
            authorizationResponse:
               allowed_upstream_headers:
                 patterns:
                 - exact: authorization
                 - exact: Cookie
                 - exact: cookie
                 - prefix: x-forwarded
                 - prefix: x-auth-request
                 - prefix: _oauth2_proxy
               allowedClientHeaders:
                 patterns:
                 - exact: "location"
                 - exact: "proxy-authenticate"
                 - exact: "set-cookie"
                 - exact: "authorization"
                 - exact: "www-authenticate"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"
               allowedUpstreamHeaders:
                 patterns:
                 - exact: "location"
                 - exact: "proxy-authenticate"
                 - exact: "set-cookie"
                 - exact: "authorization"
                 - exact: "www-authenticate"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"


```

**Comment by JoelSpeed** [comment]
I'm not personally familiar with envoy, however we recently had an issue that was similar, you may find your answer there https://github.com/oauth2-proxy/oauth2-proxy/issues/646#issuecomment-655819364

**Comment by rezagh2** [comment]
This worked for me on istio 1.6. Pretty sure it will work on 1.5 too.

```
            authorization_request:
              headers_to_add:
              - key: x-auth-request-redirect
                value: "https://..."
              allowed_headers:
                patterns:
                 - exact: "authorization"
                 - exact: "x-forwarded-proto"
                 - exact: "proxy-authorization"
                 - exact: "user-agent"
                 - exact: "x-forwarded-host"
                 - exact: "x-forwarded-proto"
                 - exact: "from"
                 - exact: "accept"
                 - prefix: "x-forwarded"
                 - prefix: "x-auth-request"
                 - prefix: "_oauth2_proxy"
                 - exact: "cookie"
                 - exact: "referer"                
                 - exact: "location"
                 - exact: "set-cookie"
            authorization_response:
              allowed_upstream_headers:
                patterns:
                  - exact: "authorization"
                  - exact: "Cookie"
                  - exact: "cookie"
                  - prefix: "_oauth2_proxy"
                  - exact: "location"
                  - exact: "proxy-authenticate"
                  - exact: "set-cookie"
                  - exact: "www-authenticate"
                  - prefix: "x-forwarded"
                  - prefix: "x-auth-request"
                  - exact: "referer"                
              allowed_client_headers:
                patterns:
                  - exact: "location"
                  - exact: "proxy-authenticate"
                  - exact: "set-cookie"
                  - exact: "authorization"
                  - exact: "www-authenticate"
                  - prefix: "x-forwarded"
                  - prefix: "x-auth-request"                
                  - exact: "referer"
```

**Comment by NingPekin** [comment]
Thank you for your hint! @JoelSpeed  and @rezagh2 
I am able to have my `x-auth-request-redirect`
But it is still not redirecting to the original url, I have seen error logs in oauthproxy:
```bash
[2020/07/21 22:21:11] [oauthproxy.go:636] Rejecting invalid redirect "http://1.1.1.1/": domain / port not in whitelist
```

http://1.1.1.1/ is my org ip and also the ip I give to `x-auth-request-redirect`

**Comment by rezagh2** [comment]
Few things for you to test:
- That url in x-auth-request-redirect is the "original upstream" url you have to set
- if 1.1.1.1 is the origin url try removing / from the end
- oauth2 proxy has domain white list you can try if not already populated
- check if envoy has a constant you can use to indicate upstream so that you can set in x-auth-request-redirect to work for all upstreams ?

**Comment by NingPekin** [comment]
Hi @rezagh2 
The previous error has gone.
Unfortunately I am still blocked:

I am aiming to access `httpbin.example.com` and it directs me to dex, then after authentication and click GRANT button.
I am redirected back to the dex page.
1. Below shows  `cookie "_oauth2_proxy" not present`, but the cookie is set to 
`set-cookie: _oauth2_proxy_csrf=84fddb14bfdc352f07e4d50f390f001c; Path=/; Domain=example.com; Expires=Wed, 29 Jul 2020 21:43:47 GMT; HttpOnly; SameSite
` 
2. I got the state and code and state from my oauth.exmple.com:4180. And I am able to see the final redirect url got appended in the end 
`127.0.0.1:51196 - - [2020/07/22 21:39:28] oauth.example.com:4180 GET - "/oauth/callback?code=i5swhz3hnfnn7simrisx3rkxk&state=88348059ad62e179f37230c26d10f427%3Ahttp%3A%2F%2Fhttpbin.example.com%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 302 294 0.001`

Do you have more clue about this issue, I feel I am pretty close to and appreciate your help again.

The full log:
```bash
/ # oauth2-proxy --provider=oidc --provider-display-name="Dex" --oidc-issuer-url=https://dex.example.com:
32000  --ssl-insecure-skip-verify=true  --email-domain=* --redirect-url=http://oauth.example.com:4180/oau
th/callback   --skip-provider-button=true --pass-basic-auth=false --pass-access-token=true  --http-addres
s=0.0.0.0:4180 --cookie-secret=R3dQb1l6ckV1RXZUYmFJcnp1U2FLUT09 --pass-authorization-header=true --cookie
-secure=false --client-id=httpbin  --upstream="static://200" --cookie-domain=".example.com" --set-authori
zation-header=true --set-xauthrequest=true --whitelist-domain=".example.com"

[2020/07/22 21:38:24] [oauthproxy.go:292] OAuthProxy configured for OpenID Connect Client ID: httpbin
[2020/07/22 21:38:24] [oauthproxy.go:298] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains:.example.com path:/ samesite: refresh:disabled
[2020/07/22 21:38:24] [http.go:58] HTTP: listening on 0.0.0.0:4180
[2020/07/22 21:39:15] [oauthproxy.go:912] Error loading cookied session: cookie "_oauth2_proxy" not present
127.0.0.1:51196 - - [2020/07/22 21:39:15] httpbin.example.com GET - "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 302 310 0.000
[2020/07/22 21:39:28] [oauthproxy.go:912] Error loading cookied session: cookie "_oauth2_proxy" not present
127.0.0.1:51196 - - [2020/07/22 21:39:28] oauth.example.com:4180 GET - "/oauth/callback?code=i5swhz3hnfnn7simrisx3rkxk&state=88348059ad62e179f37230c26d10f427%3Ahttp%3A%2F%2Fhttpbin.example.com%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36" 302 294 0.001
```

**Comment by NingPekin** [comment]
I suspect this error is related to proxy_buffer_size issue. But I don't know how to manage it with Istio

**Comment by rezagh2** [comment]
also try setting cookie-domain.
i have set the buffer on the ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-extensions-ingress
  namespace: istio-extensions
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:

```
