### ISSUE TITLE
oidc authentication is being skipped but oauth2-proxy is still returning 200

### ISSUE THREAD

**Issue by robbertvdg** [oauth2-proxy/oauth2-proxy#711]
After upgrading oauth2-proxy from 5.1.1 to 6.0.0 we are experiencing issues with the keycloak oidc authentication. In the oauth2-proxy logs we see a 200 returned, however no authentication headers were provided (and no login redirect). Looking at the release notes we had to change our `--redis-sentinel-connection-urls` and the docker image.
## Expected Behavior

Keycloak should be queried when calling the oauth2-proxy endpoint

## Current Behavior

The keycloak authentication is skipped while immediately returning a 200

## Possible Solution
Maybe we missed something in the docs or release notes, otherwise investigation is needed

## Context

We are currently holding off on upgrading oauth2-proxy to 6.0.0 because our users cannot access our endpoints with it.

## Your Environment
Requests are routed via Istio and envoy to oauth2-proxy. Login is via keycloak.
oauth2-proxy config: 
```
containers:
  - name: {{ oauth2_proxy_name }}
    args:
      - --auth-logging=true
      - --email-domain=<domain>
      - --http-address=0.0.0.0:{{ oauth2_proxy_port }}
      - --login-url={{ oauth2_proxy_keycloak_issuer_url }}/protocol/openid-connect/auth
      - --oidc-issuer-url={{ oauth2_proxy_keycloak_issuer_url }}
      - --pass-access-token=true  # sets x-auth-request-access-token header
      - --provider-display-name="Keycloak"
      - --provider=oidc
      - --redeem-url={{ oauth2_proxy_keycloak_issuer_url }}/protocol/openid-connect/token
      - --redis-sentinel-connection-urls=redis://{{ oauth2_proxy_redis_sentinel_url }}:{{ oauth2_proxy_redis_sentinel_port }}
      - --redis-sentinel-master-name={{ oauth2_proxy_redis_sentinel_master_name }}
      - --redis-use-sentinel=true
      - --request-logging=true
      - --scope=openid
      - --session-store-type={{ oauth2_proxy_session_store_type }}
      - --set-authorization-header=true
      - --set-xauthrequest=true  # sets x-auth-request-(user|email|preferred-username) but not access-token, see above
      - --skip-provider-button=true
      - --standard-logging=true
      - --upstream=static://200
      - --validate-url={{ oauth2_proxy_keycloak_issuer_url }}/protocol/openid-connect/userinfo
    env:
      - name: OAUTH2_PROXY_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: keycloak-credentials
            key: CLIENT_ID
      - name: OAUTH2_PROXY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: keycloak-credentials
            key: CLIENT_SECRET
      - name: OAUTH2_PROXY_COOKIE_SECRET
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: key
```

- Version used: v6.0.0
