### ISSUE TITLE
Why I can't access Keycloak behind ingress?

### ISSUE THREAD

**Issue by PavelDemyanenko** [oauth2-proxy/oauth2-proxy#743]
I'm trying to follow up this example https://github.com/oauth2-proxy/oauth2-proxy/tree/master/contrib/local-environment/kubernetes but with Keycloak instead.

I want to deploy Keycloak in k8s cluster with kind and helm charts setup as in example. And having such config in my Values.yaml:

```
keycloak:
  basepath: auth
  username: admin
  password: password
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
  ingress:
    enabled: 	true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /auth/?(.*)
    hosts:
      - keycloak.localtest.me

oauth2-proxy:
  nameOverride: oauth2-proxy-sample
  ingress:
    enabled: true
    hosts:
      - oauth2-proxy.localtest.me
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        large_client_header_buffers 4 32k;
  # pick up client_id and client_secret from configFile as opposed to helm .Values.config.clientID and .Values.config.clientSecret
  proxyVarsAsSecrets: false
  config:
    configFile: |-
      cookie_secret="OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
      cookie_domain=".localtest.me"
      whitelist_domains=[".localtest.me"]
      # only users with this domain will be let in
      email_domains=["example.com"]

      client_id="oauth2-proxy"
      client_secret="b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK"
      cookie_secure="false"

      redirect_url="http://oauth2-proxy.localtest.me/oauth2/callback"

      # we don't want to proxy anything so pick a non-existent directory
      upstreams=["file:///dev/null"]

      # return authenticated user to nginx
      set_xauthrequest=true
      # using http://keycloak.localtest.me/auth/realms/master/.well-known/openid-configuration oauth2-proxy will populate
      # login_url, redeem_url, and oidc_jwks_url
      provider="oidc"
      oidc_issuer_url="http://keycloak.localtest.me/auth/realms/master"
```

Where keycloak.localtest.me is in my dns hosts. Accessing nginx I see that keycloack configuration is present with *.keycloak.example.com

And in nginx log I see this:
` Error getting SSL certificate "default/keycloak-tls": local SSL certificate default/keycloak-tls was not found`

So when I go to `keycloak.localtest.me` nothing happens. How can I access Keycloak? Example http://keycloak.localtest.me/auth/realms/master?

`$ kubectl get secret keycloak-tls -n ingress-nginx`
Gives me: `Error from server (NotFound): secrets "keycloak-tls" not found`

What can I do make this small example work with Keycloak? I need somehow to add this tls, or I'm missing some point? Thank you in advance

**Comment by PavelDemyanenko** [comment]
> Just FYI, you don't need to add it to your hosts, see http://readme.localtest.me/ for details

I just followed the example with Dex, cause there is also added host: https://github.com/oauth2-proxy/oauth2-proxy/blob/37026b60cebd89e2ae3aa489447e0038ca50895c/contrib/local-environment/kubernetes/custom-dns.yaml#L22

Does it needs to be removed from that example too?

> I haven't done this myself, but you should be able to disable the TLS I would imagine and run the whole thing over HTTP.

I'm also looking to find a way how to disable it, maybe I'll successed with within some short time. I need to find the correct place where to do this, I guess.

> We have a keycloak based example in https://github.com/oauth2-proxy/oauth2-proxy/tree/master/contrib/local-environment which you may be able to use to look at the settings that have been configured there

Also looking at this and trying to decompose with options and place it to k8s values of Keycloak

**Comment by JoelSpeed** [comment]
> Does it needs to be removed from that example too?

This example is for everything being deployed in Kubernetes, this custom dns is so that other pods within Kubernetes can find Dex. You don't yourself need to have it in your hosts, as the kind cluster should expose everything on localhost.

> I'm also looking to find a way how to disable it, maybe I'll successed with within some short time. I need to find the correct place where to do this, I guess.

Have you tried setting `sslRequired: "none"`?
https://github.com/oauth2-proxy/oauth2-proxy/blob/bd5fab478d88975ea5e5e6b7b22691fa716f08e4/contrib/local-environment/keycloak/master-realm.json#L26

**Comment by PavelDemyanenko** [comment]
> Have you tried setting `sslRequired: "none"`?

I have some updates from what I did from yesterday. I've added upon creating cluster:

` kubectl create secret generic realm-secret --from-file=./keycloak/master-realm.json`

Where `keycloak` is folder within where everything in located with `master-realm.json` configs, where I set `"sslRequired" : "NONE"`

Also I configured Helm Chart like this:
```
keycloak:
  basepath: auth/
  username: admin
  password: password
  route:
    tls:
      enabled: false
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_IMPORT
      value: /keycloak/master-realm.json
    - name: JAVA_OPTS
      value: >-
        -Djboss.socket.binding.port-offset=1000
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret
  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/keycloak/"
      readOnly: true
  extraArgs: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/keycloak -Dkeycloak.migration.strategy=IGNORE_EXISTING"
  ingress:
    enabled: 	true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /auth/?(.*)
    hosts:
      - keycloak.localtest.me
```
I believe I must be close to solve this configuration can't figure out for now and still having an issue. Could you please have a look at configs, maybe I just don't see obvious mistake?

That is what I see from ingress controller log with configs above:

```
W0829 09:02:50.933141       7 controller.go:1387] Error getting SSL certificate "default/keycloak-tls": local SSL certificate default/keycloak-tls was not found
I0829 09:02:58.993928       7 status.go:275] updating Ingress default/oauth2-proxy-example status from [] to [{ localhost}]
W0829 09:02:59.005323       7 backend_ssl.go:46] Error obtaining X.509 certificate: no object matching key "default/keycloak-tls" in local store
W0829 09:02:59.006033       7 controller.go:916] Service "default/oauth2-proxy-example-http" does not have any active Endpoint.
W0829 09:02:59.006630       7 controller.go:1387] Error getting SSL certificate "default/keycloak-tls": local SSL certificate default/keycloak-tls was not found
I0829 09:02:59.005939       7 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"oauth2-proxy-example", UID:"0f2e471e-927f-4384-863e-81d0ea863b85", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"2351", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/oauth2-proxy-example
```
