### ISSUE TITLE
External AUTH Not working

### ISSUE THREAD

**Issue by TheYkk** [oauth2-proxy/oauth2-proxy#766]
**NGINX Ingress controller version**:  2.15.0

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-26T20:32:49Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6+k3s1", GitCommit:"6f56fa1d68a5a48b8b6fdefa8eb7ead2015a4b3a", GitTreeState:"clean", BuildDate:"2020-07-16T20:46:15Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):  Ubuntu 16.04.7 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-186-generic
- **Install tools**:
- **Others**:

**What happened**:

### My Ingress
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://auth.theykk.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.theykk.com/oauth2/start?rd=https%3A%2F%2F$host$request_uri"

spec:
  tls:
    - hosts:
        - theykk.com
      secretName: theykk-com-tls-prod
  rules:
    - host: longhorn.theykk.com
      http:
        paths:
          - path: /
            backend:
              serviceName: longhorn-frontend
              servicePort: 8000
 ```
### My auth-proxy
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=github
        - --email-domain=*
        - --cookie-domain=*.theykk.com,*.theykk.net
        - --github-user=TheYkk
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --set-authorization-header=true
        # Register a new application
        # https://github.com/settings/applications/new
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: SECRET
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: SECRET
        image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: oauth2-proxy
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - theykk.com
      secretName: theykk-com-tls-prod
  rules:
    - host: auth.theykk.com
      http:
        paths:
          - path: /
            backend:
              serviceName: oauth2-proxy
              servicePort: http
```
### Auth Flow
![image](https://user-images.githubusercontent.com/21688838/92408130-458b0e80-f145-11ea-8992-2963ebd1c302.png)
![image](https://user-images.githubusercontent.com/21688838/92408149-53d92a80-f145-11ea-9a8c-f01940c77078.png)
![image](https://user-images.githubusercontent.com/21688838/92408183-68b5be00-f145-11ea-8819-d7ca5dbd2394.png)
![image](https://user-images.githubusercontent.com/21688838/92408210-766b4380-f145-11ea-9a4c-a9901f3d0219.png)
![image](https://user-images.githubusercontent.com/21688838/92408225-7d925180-f145-11ea-94a3-f7403f655182.png)

Auth proxy should redirect after successful login but it doesn't
