### ISSUE TITLE
cannot properly redirect when using dedicated host

### ISSUE THREAD

**Issue by aogier** [oauth2-proxy/oauth2-proxy#782]
## Expected Behavior

I'm currently authenticating a set of service against the same oauth2 proxy so in order not to pollute my cluster with too many ingresses/ingress backends I've decided to simply use another host. Authentication should go fine and I should see a redirection toward my `rd` uri

## Current Behavior

Authentication go fine, but at the end I got a redirection to the root of this dedicated host.

## Steps to Reproduce (for bugs)

1. using 6.1.1 with this very configuration:

```toml
provider = "oidc"
# Use Auth0 as identity provider
oidc_issuer_url = "https://redacted.eu.auth0.com/"
login_url = "https://redacted.eu.auth0.com/authorize"
redeem_url = "https://redacted.eu.auth0.com/oauth/token"
validate_url = "https://redacted.eu.auth0.com/userinfo"

# base config
email_domains = [ "*" ]
upstreams = [ "file:///dev/null" ]
```
2. couple super simply k8s ingress objects

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: main
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin:
      https://auth.labs/oauth2/start?rd=https://$host$request_uri
    nginx.ingress.kubernetes.io/auth-url:
      https://auth.labs/oauth2/auth
  name: one-2048
spec:
  rules:
  - host: one.labs
    http:
      paths:
      - backend:
          serviceName: myservice
          servicePort: 80
        path: /
  tls:
  - hosts:
    - one.labs
    secretName: one.labs-tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: main
  name: auth.labs
spec:
  rules:
    - host: auth.labs
      http:
        paths:
          - backend:
              serviceName: oauth2-proxy
              servicePort: 80
            path: /oauth2
  tls:
    - hosts:
        - auth.labs
      secretName: auth.labs-tls


```
3. observe pod's log files:
```
127.0.0.1:48294 - - [2020/09/17 12:06:12] auth.labs GET - "/oauth2/start?rd=https://one.labs/" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0" 302 320 0.000
```

## Your Environment

- Version used: 6.1.1

Thank you, regards!
