### ISSUE TITLE
Changing redirect url to include path causes redirect issues

### ISSUE THREAD

**Issue by lyndon160** [oauth2-proxy/oauth2-proxy#805]
I am trying to run multiple oauth2 proxies from the same domain: app.localhost:8080. I am trying to protect multiple backend services using the proxy, all of the services need to be accessible from the app.localhost:8080 domain. 

For example, I'm looking to configure endpoints like this:

app.localhost:8080/whoami/ --> routes to whoami backend service
app.localhost:8080/jaeger/ --> routers to jaeger backend service

Doing this in traefik is trivial, but configuring it for OAuth2-proxy causes a redirect issue.

## Proposed solution

I could change my configuration to be domain, or subdomain routed, but that does not fit my needs. I could also use one proxy and support multiple upstreams, but as the apps behind this have overlapping paths, this does not work. 

Supporting traefik forward auth would provide an alternative solution to this, as the redirect uri could be done at the root. This said, ideally both forward auth and what I am trying to do detailed in this issue would work.

## Expected Behavior

The user should be directed to the providers login page, and then should get returned to the app.localhost:8080 with correct path which is associated with the app.

## Current Behavior

When hitting app.localhost:8080/whoami/ and after signing in, I continually get redirected to the provider (keycloak) with an increasingly long redirect uri.

Inspecting the chrome network panel I can see that there are a bunch of redirects:
![Screenshot 2020-09-30 at 10 55 27](https://user-images.githubusercontent.com/5150703/94671353-adc7ad00-030b-11eb-92b5-b8e24e8a4263.png)

## Steps to Reproduce (for bugs)

Docker compose example:

```
x-iap: &iap_defaults
  image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
  environment: &iap_default_envs
    OAUTH2_PROXY_PROVIDER: oidc
    OAUTH2_PROXY_CLIENT_ID: test-cloud
    OAUTH2_PROXY_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
    OAUTH2_PROXY_COOKIE_SECRET: ${SESSION_KEY}
    OAUTH2_PROXY_COOKIE_SECURE: "false"
    OAUTH2_PROXY_COOKIE_SECURE_DOMAIN: "localhost"
    OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
    OAUTH2_PROXY_OIDC_ISSUER_URL: <removed>
    OAUTH2_PROXY_EMAIL_DOMAINS: "*"
    OAUTH2_PROXY_REVERSE_PROXY: "true"
    OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
    OAUTH2_PROXY_PASS_USER_HEADERS: "true"
    OAUTH2_PROXY_PREFER_EMAIL_TO_USER: "true"
    OAUTH2_PROXY_SESSION_STORE_TYPE: "redis"
    OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://cookie-monster:6379
    OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
  networks:
    - traefik



whoami-iap:
  <<: *iap_defaults
  environment:
    <<: *iap_default_envs
    OAUTH2_PROXY_UPSTREAMS: http://whoami:80/
    OAUTH2_PROXY_REDIRECT_URL: "http://app.localhost:8080/whoami/oauth2/callback"
  networks:
    - traefik
  labels:
    traefik.enable: "true"
    traefik.http.routers.whoami-iap.rule: "Host(`app.localhost`) && PathPrefix(`/whoami/`)"
    traefik.http.routers.whoami-iap.entrypoints: web
    traefik.http.services.whoami-iap.loadbalancer.server.port: 4180
  depends_on:
    - cookie-monster



traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--accesslog=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "8088:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
```

## Context

I am trying to run multiple services behind a single domain app.localhost:8080. I want to use paths to split the applications out. Some of these services have overlapping paths meaning that I cannot simply set them as part of the upstreams to OAuth2_proxy.

## Your Environment

- Version used: 6.1.1
