### ISSUE TITLE
cookies and different domains

### ISSUE THREAD

**Issue by Raboo** [oauth2-proxy/oauth2-proxy#818]
Hi,

This is more a question rather than a bug report.

## Context

I have different domains that I want to protect with one oauth2-proxy.
Since I saw that you can specify multiple `--whitelist-domain` and `--cookie-domain` I figured that you can use one proxy for multiple domains.

However I can't use one domains oauth2-proxy for another domains nginx backend/service.
nginx keeps redirecting me to the oauth2-proxy since it is not receiving the cookie set by

#### successful workflow 

I go to service.maindomain.net, it redirects to oauth2.maindomain.net, it runs a set-cookie.
```
set-cookie: _oauth2_proxy=xxx; Path=/; Domain=maindomain.net; Expires=xxx; HttpOnly; Secure; SameSite=lax
```

Then I get redirected back to service.maindomain.net, and it knows I'm authenticated cause my browser sends the `_oauth2_proxy` in the request.

Authentication is succeeded.

#### unsuccessful workflow

If I go to service.otherdomain.net, I get redirected to oauth2.maindomain.net and it runs the same set-cookie.
```
set-cookie: _oauth2_proxy=xxx; Path=/; Domain=maindomain.net; Expires=xxx; HttpOnly; Secure; SameSite=lax
```

Then I get redirected to service.otherdomain.net, and my browser does not send the cookie with the request, so it doesn't know I'm authenticated and I get redirected back to oauth2.maindomain.net. So I end up in a endless loop.

## Expected Behavior
Some documentation on how it works when using one oauth2-proxy for multiple domains.

## Current Behavior
Trial and Error, guess work and general googling about cookies.

## Possible Solution
So my question is, is there a way to work around this in a neat way or do I need to setup a virtual host for the oauth2 for every domain I intend to use in order to get the correct cookies set?

## Your Environment

- Version used: v6.1.1

Running oauth2-proxy with following flags (+ secrets)

```
--provider=oidc
--set-authorization-header=true
--set-xauthrequest=true
--cookie-samesite=lax
--cookie-name=_oauth2_proxy
--set-authorization-header=true
--set-xauthrequest=true
--email-domain=*
--http-address=0.0.0.0:4180
--upstream=static://200
--skip-provider-button=true
--whitelist-domain=.maindomain.com
--whitelist-domain=.otherdomain.com
--cookie-domain=.maindomain.com
--cookie-domain=.otherdomain.com
--redirect-url=https://oauth2.maindomain.net/oauth2/callback
--oidc-issuer-url=https://dex.maindomain.net
```

I'm running in kubernetes, with nginx ingress with following annotations.
```
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2.maindomain.net/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://oauth2.maindomain.net/oauth2/auth
```

**Comment by NickMeves** [comment]
I do this exact same architecture myself (I'm looking to make a blog post and add better documentation around it).

The trick is the cookie & redirect domain you want to use (especially cookie) has to match the structure your original app is hooking into this with subrequests via the ingress annotations.

OAuth2-Proxy hosted on `oauth2.maindomain.net` can't set a session cookie with `domain=otherdomain.com` if it is hosted on `maindomain.com`.

So you'll need to setup multiple K8s `ingress` domains for your central oauth2-proxy access gateway that match where you'll get redirect reqeusts from.

**Comment by NickMeves** [comment]
FYI - I'm also hoping to add this enhancement to this type of architecture: https://github.com/oauth2-proxy/oauth2-proxy/issues/831

**Comment by Raboo** [comment]
@NickMeves Ok, thanks for confirming that. 👍 

#831 is a very good feature indeed.

For anyone else that uses ingress-nginx, here is a example ingress for oauth2-proxy with multiple domains attached.

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  backend:
    serviceName: oauth2-proxy
    servicePort: 4180
  tls:
  - hosts:
    - oauth2.maindomain.com
    - oauth2.otherdomain.com
    secretName: oauth2-star-tls
  rules:
  - host: oauth2.maindomain.com
  - host: oauth2.otherdomain.com
```

Also I am now running oauth2-proxy without the `--redirect-url` argument or config.
Also you need to update your dex or keycloak or whatever you use, to have a redirect url for every domain you add for your oauth2-proxy.

So do I leave this issue open until there is some documentation or do I close this?
