### ISSUE TITLE
ingress-nginx and keycloak use case

### ISSUE THREAD

**Issue by Hokwang** [oauth2-proxy/oauth2-proxy#837]
Hi,

I am trying to use oauth2-proxy with keycloak and kubernetes-dashboard (and other tools) on the kubernetes cluster. ( I am using ingress-nginx. )

I am using helm chart for install oauth2-proxy.
Here's my values.yaml
```
config:
  clientID: "proxy"
  clientSecret: "secret"
  cookieSecret: "secret"

image:
  repository: "quay.io/pusher/oauth2_proxy"
  tag: "v6.1.1"

extraArgs:
  provider: "oidc"
  redirect-url: "https://my.company.net/oauth2/callback"
  oidc-issuer-url: "https://my.company.net/keycloak/realms/test"
  login-url: "https://my.company.net/keycloak/realms/test/protocol/openid-connect/auth"
  redeem-url: "https://my.company.net/keycloak/realms/test/protocol/openid-connect/token"
  validate-url: "https://my.company.net/keycloak/realms/test/protocol/openid-connect/userinfo"
  scope: "openid profile email"
  keycloak-group: user
  upstream: "file:///dev/null"
  insecure-oidc-allow-unverified-email: "true"
  insecure-oidc-skip-issuer-verification: "true"
  ssl-insecure-skip-verify: "true"
  ssl-upstream-insecure-skip-verify: "true"
  email-domain: "*"
  cookie-secure: "false"
  cookie-samesite: "lax"
  set-xauthrequest: "true"
  pass-user-headers: "true"
  pass-authorization-header: "true"
  set-basic-auth: "true"
  pass-basic-auth: "true"
  silence-ping-logging: "true"
  pass-access-token: "true"

ingress:
  enabled: true
  path: /oauth2
  hosts:
    - my.company.net
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
```
( lots of options I tested )

kubernetes dashboard ingress's annotaions
```
  annotations:
      kubernetes.io/ingress.class: nginx
      meta.helm.sh/release-name: dashboard-prod
      meta.helm.sh/release-namespace: dashboard-prod
      nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=https://$host$request_uri$is_args$args
      nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
      nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^(/dashboard)$ /dashboard/ permanent;
```

I can access kubernetes dashboard, but I can't find X-Auth-* header. Is there a bug in here?

when I use `provider: keycloak`, I can't get X-Auth-* header, too.
