### ISSUE TITLE
403 Permission Denied invalid_request error_description=Invalid+scopes OAUTH2 + Keycloak+ Docker

### ISSUE THREAD

**Issue by joaopalma5** [oauth2-proxy/oauth2-proxy#847]
I wan't pretect onde page with keycloak and I'm using the oauth2 for provide keycloak login but the proxy gives me 403 Invalid scopes when the proxy go to GET - "/oauth2/start?rd=%2F"

## Expected Behavior

Display Keycloak login page

## Current Behavior

Give me this page:
URL : http://docker.for.win.localhost:4180/oauth2/callback?error=invalid_request&error_description=Invalid+scopes%3A+api&state=7e1d5b2e88b115cc0860b3f69364b2d1%3A%2F
Text on page: 403 Permission Denied
invalid_request

## Steps to Reproduce (for bugs)
In docker compose with this configuration:
```

authproxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v5.1.0
    environment:
      OAUTH2_PROXY_PROVIDER: 'keycloak'
      OAUTH2_PROXY_COOKIE_SECRET: 'MjkyODUzMTA2Mw=='
      OAUTH2_PROXY_CLIENT_SECRET: 'ff ... 1104752e'
      OAUTH2_PROXY_CLIENT_ID: 'logs'
      OAUTH2_PROXY_EMAIL_DOMAINS: 'gmail.com'
      OAUTH2_PROXY_COOKIE_NAME: 'accessToken_logs'
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      OAUTH2_PROXY_UPSTREAM: 'http://nginx:8888/'
      OAUTH2_PROXY_LOGIN_URL: "http://docker.for.win.localhost:8081/auth/realms/logs/protocol/openid-connect/auth"
      OAUTH2_PROXY_REDEEM_URL: "http://docker.for.win.localhost:8081/auth/realms/logs/protocol/openid-connect/token"
      OAUTH2_PROXY_VALIDATE_URL: "http://docker.for.win.localhost:8081/auth/realms/logs/protocol/openid-connect/userinfo"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
```

## Context

```
authproxy_1            | 172.21.0.1 - - [2020/10/16 13:46:05] docker.for.win.localhost:4180 GET - "/oauth2/sign_in" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 200 2657 0.000
authproxy_1            | [2020/10/16 13:46:05] [oauthproxy.go:867] Error loading cookied session: Cookie "accessToken_elk" not present
authproxy_1            | 172.21.0.1 - - [2020/10/16 13:46:05] docker.for.win.localhost:4180 GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 403 2668 0.000
authproxy_1            | 172.21.0.1 - - [2020/10/16 13:46:07] docker.for.win.localhost:4180 GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 302 336 0.000
authproxy_1            | [2020/10/16 13:46:07] [oauthproxy.go:746] Error while parsing OAuth2 callback: invalid_request
authproxy_1            | 172.21.0.1 - - [2020/10/16 13:46:07] docker.for.win.localhost:4180 GET - "/oauth2/callback?error=invalid_request&error_description=Invalid+scopes%3A+api&state=7e1d5b2e88b115cc0860b3f69364b2d1%3A%2F" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 403 338 0.006
authproxy_1            | [2020/10/16 13:46:07] [oauthproxy.go:867] Error loading cookied session: Cookie "accessToken_elk" not present
authproxy_1            | 172.21.0.1 - - [2020/10/16 13:46:07] docker.for.win.localhost:4180 GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 403 2668 0.000
```

## Your Environment

Docker-compose 
Image: https://quay.io/repository/oauth2-proxy/oauth2-proxy?tag=latest&tab=tags with versions v6.1.1 and v5.1.0
