### ISSUE TITLE
Gitlab Auth stopped working after upgrade from v3 to v6

### ISSUE THREAD

**Issue by jeff1985** [oauth2-proxy/oauth2-proxy#860]
Trying to upgrade oauth2-proxy from v3.2.0 to the "latest" (also tried v6.1.1) version. 

## Expected Behavior

oauth2-proxy should be able to authenticate via gitlab. With the old version I was able to use gitlab authentication with our company's custom hosted gitlab. 

## Current Behavior

With the new version, after redirecting back from gitlab to /oauth2/callback, I'm getting a http 500 internal error page and I see in the logs:

    [2020/10/21 08:10:56] [logger.go:508] Error redeeming code during OAuth2 callback: token response did not contain an id_token
    [2020/10/21 08:10:56] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session

## Steps to Reproduce (for bugs)

I'm using the following command:
```
/bin/oauth2-proxy
--provider=gitlab
--cookie-secure=false
--oidc-issuer-url=https://git.xxxxxxxxx.com
--profile-url=https://git.xxxxxxxxx.com/oauth/userinfo
--pass-basic-auth=false
--validate-url=https://git.xxxxxxxxx.com/api/v4/user
--footer=xxxxxxxxx.com
--cookie-secret=xxxx
--upstream=http://myupstream/
--http-address=0.0.0.0:4180
--pass-user-headers
--scope=openid
--scope=read_user
--scope=email
--redirect-url=https://xxxxxxxxx.com/oauth2/callback
--email-domain=xxxxxxxxx.com

```

OAUTH2_PROXY_CLIENT_ID and OAUTH2_PROXY_CLIENT_SECRET are provided as env variable. 

I also tried to set provider=oidc with the same result. 

## Your Environment

- Version used: docker quay.io/pusher/oauth2_proxy:latest
- GitLab Community Edition 13.4.2
- Running in a Kubernetes Cluster (AKS) v1.17.11

**Comment by JoelSpeed** [comment]
I don't think scope can be specified multiple times like that, try `--scope="openid read_user email"`

**Comment by jeff1985** [comment]
Hi @JoelSpeed 

Thank you for that idea!

I tried that, but it seems that in that case the quotes will be passed as part of scope parameter when running gitlab redirect. I'm getting "The requested scope is invalid, unknown, or malformed." from gitlab. I.e. I see following in the URL:
`&scope="openid read_user email"`

If I manually remove the quotes inside the link and reload it, the auth works and can use my service as expected. However this is bad user experience :(

So I tried:
`--scope="openid read_user email"`
`--scope='openid read_user email'`
`--scope=openid+read_user+email`
skip scope param => results in `&scope=openid+email+profile` which is also invalid for gitlab

What worked was actually 
`--scope=openid read_user email`

I must say, this is not very intuitive... Maybe you could add this to the docs?

**Comment by JoelSpeed** [comment]
We should make sure this is documented, glad you found a solution!

**Comment by ieugen** [comment]
I've also encountered this issue and spent ~ 3-4h until I found this post.

**Comment by JoelSpeed** [comment]
I've just tried this out locally and verified what I'm seeing. If I try `--scope="openid profile email"` with the OIDC provider, the state ends up with `scope=openid+profile+email` which is expected. If I try `--scope=openid profile email`, I end up with `scope=openid` which is not intended. Perhaps there is some issue in the gitlab provider that's not liking the scope setting 🤔 

Could you verify that your scope is being set correctly by checking the redirect to the provider? And perhaps provide what it gets set to when you try the other options

**Comment by ieugen** [comment]
For me it's working with `--scope=openid email profile groups`.

This is part of the spec for the k8s deployment taken from live system:
```
 spec:
      containers:
      - args:
        - --http-address=0.0.0.0:4180
        - --email-domain=*
        - --oidc-issuer-url=https://REDACTED
        - --pass-authorization-header=true
        - --pass-basic-auth
        - --provider=oidc
        - --scope=openid email profile groups
        - --skip-jwt-bearer-tokens=true
        - --skip-provider-button=true
        - --ssl-upstream-insecure-skip-verify=true
        - --upstream=https://REDACTED
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
```

**Comment by jeff1985** [comment]
For me its set like this:

```
containers:
        - name: oauth2
          image: 'quay.io/pusher/oauth2_proxy:v6.1.1'
          command:
            - /bin/oauth2-proxy
            - '--provider=gitlab'
            - '--cookie-secure=true'
            - '--oidc-issuer-url=https://git.REDACTED'
            - '--profile-url=https://git.REDACTED/oauth/userinfo'
            - '--pass-basic-auth=false'
            - '--validate-url=https://git.REDACTED/api/v4/user'
            - '--upstream=http://REDACTED/'
            - '--http-address=0.0.0.0:4180'
            - '--pass-user-headers'
            - '--scope=openid read_user email'
```

and I see `&scope=openid+read_user+email&` in the URL used to redirect to gitlab for auth. Also gitlab is showing the 3 permissions that have been requested when user first time logs in with this app.
