### ISSUE TITLE
Trouble updating from v4 to v6

### ISSUE THREAD

**Issue by Jleagle** [oauth2-proxy/oauth2-proxy#865]
Going from oauth2_proxy:v4.0.0 to oauth2_proxy:v6.1.1
I checked any breaking changes in the changelog but didn't see anything related

Mainly the error i get to is:

```
403 Permission Denied
http: named cookie not present
```

My config is docker-compose is:

```
auth:
  container_name: auth
  hostname: auth
  image: quay.io/pusher/oauth2_proxy:v6.1.1
  restart: "unless-stopped"
  volumes:
    - ${MYSITE_INFRASTRUCTURE_PATH}/auth/authenticated-emails.txt:/authenticated-emails.txt
  environment:
    - OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE=/authenticated-emails.txt
    - OAUTH2_PROXY_CLIENT_ID=${MYSITE_OAUTH2_PROXY_CLIENT_ID}
    - OAUTH2_PROXY_CLIENT_SECRET=${MYSITE_OAUTH2_PROXY_CLIENT_SECRET}
    - OAUTH2_PROXY_COOKIE_DOMAIN=mysite.com
    - OAUTH2_PROXY_COOKIE_SECRET=${MYSITE_OAUTH2_PROXY_COOKIE_SECRET}
    - OAUTH2_PROXY_COOKIE_SECURE=true
    - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
    - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
    - OAUTH2_PROXY_REDIRECT_URL=https://auth.mysite.com/oauth2/callback
    - OAUTH2_PROXY_REVERSE_PROXY=true
    - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=true
    - OAUTH2_PROXY_SET_XAUTHREQUEST=true
    - OAUTH2_PROXY_UPSTREAM=http://nginx:80
```

I am using a reverse proxy with nginx, everything is using https and terminates at nginx.
nginx is setup using the config in the docs (doesn't looks like it's changed from 4 -> 6)

I am using oauth2-proxy to secure access to:

```
https://sub1.mysite.com
https://sub2.mysite.com
https://mysite.com/path1
https://mysite.com/path2
```

Should COOKIE_SECURE be true if you use https? I have tried with false too.
The redirect back form the provider seems to work but maybe an issue with the cookie details it's creating?

Any ideas? Thanks.
