### ISSUE TITLE
Error loading cookied session: cookie "_oauth2_proxy" not present, removing session

### ISSUE THREAD

**Issue by karlschriek** [oauth2-proxy/oauth2-proxy#866]
oauth2-proxy gives this error after user logs in via Azure Active Directory:
`2020-10-23T14:01:46.595308318Z [2020/10/23 14:01:46] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy" not present, removing session`

It also gives the following warning:
```
020-10-23T13:45:26.542883106Z [2020/10/23 13:45:26] [logger.go:508] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.
2
```

I would expect after authentication, that the user is redicted to the application, but instead, nginx throws a "502 Bad Gateway".

I am using this in combination with nginx on EKS.

Below are the full Kubernetes specs I am using (based on https://msazure.club/protect-kubernetes-webapps-with-azure-active-directory-aad-authentication/)

```
apiVersion: v1
kind: Namespace
metadata:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/instance: my-app
---
# my-app Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-app-app
      labels:
        app: my-app
    spec:
      containers:
        - image: hashicorp/http-echo
          args:
            - "-text=my-app"
            - "-listen=:80"
---
# my-app Service
kind: Service
apiVersion: v1
metadata:
  name: my-app-service
  namespace: my-app
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - port: 80
---
# my-app Ingress
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: my-app-ingress
  namespace: my-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
spec:
  rules:
    - host: my-app.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: my-app-service
              servicePort: 80
  tls:
    - hosts:
        - my-app.mydomain.com
      secretName: my-app-tls
---
# oauth2_proxy Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  namespace: my-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: my-app.mydomain.com
      http:
        paths:
          - path: /oauth2
            backend:
              serviceName: oauth2-proxy
              servicePort: 4180
  tls:
    - hosts:
        - my-app.mydomain.com
      secretName: my-app-tls
---
# oauth2_proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - env: #TODO encode this in a K8S secret
            - name: OAUTH2_PROXY_PROVIDER
              value: azure
            - name: OAUTH2_PROXY_AZURE_TENANT
              value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            - name: OAUTH2_PROXY_CLIENT_ID
              value: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: aaaaaaaaaaaaaaaaaaaaaaaaaaaaa
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: "0.0.0.0:4180"
            - name: OAUTH2_PROXY_UPSTREAM
              value: http://172.20.176.91:80 #This is the ClusterIP of "my-app-service". I believe that is what should be set here but cannot be certain
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: mydomain.com
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: IfNotPresent
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: my-app
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    app: oauth2-proxy
```
