### ISSUE TITLE
Okta authorization_code flow not working 

### ISSUE THREAD

**Issue by andreyprezotto** [oauth2-proxy/oauth2-proxy#867]
## Expected Behavior

I have oauth2_proxy v6.1.1 configured in my kubernetes cluster and I'm trying to make the authorization code flow to work.
But looks like the /token endpoint (redeem) is not being requested

## Current Behavior

- When I request the gateway address, I get redirected to the proxy 
- Then the proxy redirects me to the Okta login page.
- Once logged in, I'm redirected back to the proxy with the `&code=<authz_code>` appended to the URL.
- Then the proxy redirects to the upstream service. **At this point I expect it to make a request to Okta to exchange the authz code for and Access Token.**

## Possible Solution

Maybe I am missing some configuration

## Steps to Reproduce (for bugs)

Here is the args I'm currently using
```yaml
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
        args:
        - --provider=oidc
        - --cookie-secure=true
        - --cookie-samesite=lax
        - --cookie-refresh=1h
        - --cookie-expire=4h
        - --cookie-name=_oauth2_proxy_istio_ingressgateway
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --pass-access-token=true
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --upstream=static://200
        - --skip-provider-button=true
        - --whitelist-domain=envoy-local.com
        - --oidc-issuer-url=https://test.okta.com/oauth2/<id>
        - --request-logging=true
```

And here are the logs from the proxy. After the /callback request I think it would have to request /token in okta (between lines 4 and 5 in the log)

```bash
1. oauth2-proxy-757cd4c66c-4zxr2 oauth2-proxy [2020/10/23 17:12:14] [logger.go:508] Error loading cookied session: cookie "_oauth2_proxy_istio_ingressgateway" not present, removing session
2. oauth2-proxy-757cd4c66c-4zxr2 oauth2-proxy 127.0.0.1:60480 - - [2020/10/23 17:12:14] envoy-local.com:31061 GET - "/swagger-ui.html" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 302 342 0.000
3. oauth2-proxy-757cd4c66c-4zxr2 oauth2-proxy 127.0.0.1:60480 - AndreyPrezotto@company.com [2020/10/23 17:13:00] [AuthSuccess] Authenticated via OAuth2: Session{email:AndreyPrezotto@company.com user:CLIENTID PreferredUsername:1122857@usadev.ihmdev.com token:true id_token:true created:2020-10-23 17:13:00.217662165 +0000 UTC m=+381.176734793 expires:2020-10-23 18:13:00.216377993 +0000 UTC m=+3981.175450678}
4. oauth2-proxy-757cd4c66c-4zxr2 oauth2-proxy 127.0.0.1:60480 - - [2020/10/23 17:12:59] envoy-local.com:31061 GET - "/oauth2/callback?code=0n6RhT_0OfQyGOVHJUUJubcAr2CxyNDNLIRPelUGAmk&state=fe55cf0e184bbee3274f223e1d6382fe%3A%2Fswagger-ui.html" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 302 39 0.712
5. oauth2-proxy-757cd4c66c-4zxr2 oauth2-proxy 127.0.0.1:60480 - AndreyPrezotto@company.com [2020/10/23 17:13:00] envoy-local.com:31061 GET static://200 "/swagger-ui.html" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 200 13 0.001

```
## Context

I want to get an access token from okta and forward it to the upstream service in the auth header/cookie

## Your Environment

- Version used: v6.1.1
