### ISSUE TITLE
[v6.1.1] Http 404 with Outh2 -> Keycloak 

### ISSUE THREAD

**Issue by dicolasi** [oauth2-proxy/oauth2-proxy#948]
404 outh2->keycloak 

## Expected Behavior

When I click on authenticate with Keycloak button (line above is Authenticate using @property.xyz) I got redirected to this uri:

`https://auth.stage.data.property.xyz/realms/xyz-engs/protocol/openid-connect/auth?approval_prompt=force&client_id=monitor-client&redirect_uri=https%3A%2F%2Falertmanager.stage.data.property.xyz%2Foauth2%2Fcallback&response_type=code&scope=api&state=57334a86ab94366d0ae2770eaecd5018%3A%2F`

and an authentication prompt with keycloak appears. Please note that I got SAML configured for that domain. 

## Current Behavior
Redirected here:

`https://auth.stage.data.property.xyz/realms/xyz-engs/protocol/openid-connect/auth?approval_prompt=force&client_id=monitor-client&redirect_uri=https%3A%2F%2Falertmanager.stage.data.property.xyz%2Foauth2%2Fcallback&response_type=code&scope=api&state=57334a86ab94366d0ae2770eaecd5018%3A%2F`

followed by a page with body: 

404 - Not Found.

[no details in logs]

## Steps to Reproduce (for bugs)

Here the link to the service -> https://alertmanager.stage.data.property.xyz/

## Context

I am trying to authenticate users to access alertmanager. 

## Your Environment

outh2-proxy runs a sidecar for alertmanager:

```
alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        cpu: "100m"
        memory: "100M"
      requests:
        cpu: "10m"
        memory: "30M"
    externalUrl: https://alertmanager.stage.data.property.xyz
    containers:
      - image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
        name: oauth2-proxy
        ports:
          - containerPort: 4180
        env:
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-monitor-client-secret
                key: secret
        args:
        - --provider=keycloak
        - --client-id=monitor-client
        - --client-secret=$(KEYCLOAK_CLIENT_SECRET)
        - --login-url=https://auth.stage.data.property.xyz/realms/xyz-engs/protocol/openid-connect/auth
        - --redeem-url=https://auth.stage.data.property.xyz/realms/xyz-engs/protocol/openid-connect/token
        - --validate-url=https://auth.stage.data.property.xyz/realms/xyz-engs/protocol/openid-connect/userinfo
        - --keycloak-group=/admin
        - --email-domain=property.xyz
        - --cookie-secret=SECRET
        - --logging-compress=true
        - --http-address=http://:4180
        - --upstream=http://127.0.0.1:9093
```
`
here the keycloak client config:

```
 apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: monitor-client
  labels:
    app: keycloak-client
spec:
  realmSelector:
    matchLabels:
      app: engs-realm
  client:
    clientId: monitor-client
    clientType: confidential
    directAccessGrantsEnabled: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    redirectUris:
      - https://prometheus.stage.data.property.xyz
      - https://prometheus.stage.data.property.xyz/*
      - https://alertmanager.stage.data.property.xyz
      - https://alertmanager.stage.data.property.xyz/*
    protocolMappers:
      - name: admin
        protocolMapper: oidc-group-membership-mapper
        config:
          token.claim.name: "groups"
          jsonType.label: String
          access.token.claim: "true"
```

- Version used:
 6.1.1

**Comment by skuethe** [comment]
Try to modify the URI from `/realms/...` to `/auth/realms/...`
So:

```yaml
        - --login-url=https://auth.stage.data.property.xyz/auth/realms/xyz-engs/protocol/openid-connect/auth
        - --redeem-url=https://auth.stage.data.property.xyz/auth/realms/xyz-engs/protocol/openid-connect/token
        - --validate-url=https://auth.stage.data.property.xyz/auth/realms/xyz-engs/protocol/openid-connect/userinfo
```

instead of

```yaml
        - --login-url=https://auth.stage.data.property.xyz/realms/xyz-engs/protocol/openid-connect/auth
        - --redeem-url=https://auth.stage.data.property.xyz/realms/xyz-engs/protocol/openid-connect/token
        - --validate-url=https://auth.stage.data.property.xyz/realms/xyz-engs/protocol/openid-connect/userinfo
```

**Comment by dicolasi** [comment]
Thanks. May I ask you why should I change that?

**Comment by skuethe** [comment]
I think it's a problem from the documentation side. Both on oauth2-proxy and keycloak side.

Authenticate against Keycloak and then open the following URL, which displays all the available endpoints:
https://auth.stage.data.property.xyz/auth/realms/xyz-engs/.well-known/openid-configuration

**Comment by dicolasi** [comment]
Thanks. Got past that error. Nw got this: 

403 - Permission denied 

https://alertmanager.stage.data.property.xyz/oauth2/callback?error=invalid_request&error_description=Invalid+scopes%3A+api&state=e6ac62477e31a978268a125acf370135%3A%2F

**Comment by dicolasi** [comment]
docs only talk about creating a mapper. I left everything as default. Any clue @skuethe?

**Comment by dicolasi** [comment]
Found this -> https://github.com/oauth2-proxy/oauth2-proxy/issues/847

**Comment by skuethe** [comment]
Well yes, looking at your config, you don't have a scope defined. Try something like
```
 - --scope="openid profile email groups"
````

As it seems you are working with group access. This assumes you have created a `groups` client scope.

**Comment by dicolasi** [comment]
let me try. Can't say I am grateful of your help!

**Comment by skuethe** [comment]
The argo projects otherwise has a good documentation on how to use keycloak groups for authorization:
https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/#configuring-the-groups-claim

**Comment by dicolasi** [comment]
https://alertmanager.stage.data.property.xyz/oauth2/callback?error=invalid_request&error_description=Invalid+scopes%3A+%22openid+profile+email+groups%22&state=22f6bf613b6841598fd51bde63ce9752%3A%2F

**Comment by dicolasi** [comment]
quick update: 

- removed group authentication and add saml identity provider. Now I got this:
https://alertmanager.stage.data.property.xyz/oauth2/callback?state=dc0bad1f1d3c83de74b0f622dfffba84%3A%2F&session_state=1a61eaee-5ae7-4793-9878-34457870d64c&code=d8378d78-d8c9-4dd0-a1e8-04724c53cd54.1a61eaee-5ae7-4793-9878-34457870d64c.24e48af0-29e4-48ff-a462-f3adfb544c66

No error, but got 403....

**Comment by dicolasi** [comment]
Got it working!!! :)

**Comment by dicolasi** [comment]
I leave here what I have done so other won't struggle like myself. I am using keycloak-operator in Kubernetes 1.17 [https://github.com/keycloak/keycloak-operator]. Here the client [of course replace with something meaningful for yourself]:

```
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: monitor-client
  labels:
    app: keycloak-client
spec:
  realmSelector:
    matchLabels:
      app: engs-realm
  client:
    clientId: monitor-client
    clientType: confidential
    directAccessGrantsEnabled: true
    standardFlowEnabled: true
    implicitFlowEnabled: false
    redirectUris:
      - https://prometheus.stage.data.property.xyz
      - https://prometheus.stage.data.property.xyz/*
      - https://alertmanager.stage.data.property.xyz
      - https://alertmanager.stage.data.property.xyz/*
    protocolMappers:
      - name: audience
        protocolMapper: oidc-audience-mapper
        protocol: openid-connect
        config:
          claim.name: audience
          access.token.claim: "true"
          included.client.audience: client-test
      - name: username
        protocolMapper: oidc-usermodel-property-mapper
        protocol: openid-connect
        config:
          access.token.claim: "true"
          claim.name: username
          jsonType.label: String
          user.attribute: username
      - name: roles
        protocolMapper: oidc-usermodel-client-role-mapper
        protocol: openid-connect
        config:
          access.token.claim: "true"
          claim.name: roles
          jsonType.label: String
          multivalued: "true"

```

Here the container configuration: 

```
    containers:
      - image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
        name: oauth2-proxy
        ports:
          - containerPort: 4180
        env:
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: keycloak-monitor-client-secret
                key: secret
        args:
        - --provider=keycloak
        - --client-id=monitor-client
        - --client-secret=$(KEYCLOAK_CLIENT_SECRET)
        - --login-url=https://auth.stage.data.property.xyz/auth/realms/xyz-engs/protocol/openid-connect/auth
        - --redeem-url=https://auth.stage.data.property.xyz/auth/realms/xyz-engs/protocol/openid-connect/token
        - --validate-url=https://auth.stage.data.property.xyz/auth/realms/xyz-engs/protocol/openid-connect/userinfo
        - --email-domain=*
        - --cookie-secure=true
        - --cookie-secret=SECRET
        - --logging-compress=true
        - --http-address=http://:4180
        - --upstream=http://127.0.0.1:9093
        - --scope=profile email roles
```

[notice that I am not using groups!]
