### ISSUE TITLE
Support for docker secrets

### ISSUE THREAD

**Issue by jmigual** [oauth2-proxy/oauth2-proxy#973]
It would be nice if all (or most) of the variables have a `_FILE` variant to support loading the values from a file instead of directly. This will allow us to use docker secrets to store values like the client secret or the cookie secret. I know that `OAUTH2_PROXY_CLIENT_SECRET_FILE` exists and works well but I would like to also have a `OAUTH2_PROXY_COOKIE_SECRET_FILE` to do the same and properly work with docker secrets. In an ideal solution I would like for all the variables to have a `_FILE` variant so if the user wants, it can define everything as a docker secret 

## Expected Behavior

Then I could define a `docker-compose.yml` file as such:

```yaml
version: "3.8"

services:
    oauth2-proxy:
        image: "bitnami/oauth2-proxy:latest"
        environment:
            - "OAUTH2_PROXY_CLIENT_SECRET_FILE=/run/secrets/client-secret"
            - "OAUTH2_PROXY_COOKIE_SECRET_FILE=/run/secrets/cookie-secret"

            # Other provider specific options here
        secrets:
            - client-secret
            - cookie-secret
secrets:
    client-secret:
        file: "./secrets/client-secret.txt"
    cookie-secret:
        file: "./secrets/cookie-secret.txt
```

## Current Behavior

Currently only the `OAUTH2_PROXY_CLIENT_SECRET_FILE` is supported so the cookie secret cannot be defined as a docker secret file.

## Context

Currently I have to define the `OAUTH2_PROXY_COOKIE_SECRET` environment variable either directly on the `docker-compose.yml` file or as an environment variable given to docker compose.

## Your Environment

- Version used: 6.1.1
