### ISSUE TITLE
CORS Problem with Azure

### ISSUE THREAD

**Issue by Christoph-Raab** [oauth2-proxy/oauth2-proxy#987]
I have a problem refreshing the session using oauth2-proxy with redis in kubernetes with istio. My main question is, if this can be because of a misconfiguration in oauth2-proxy or if this can be ruled out.

## Expected Behavior

Session Refresh works as expected.

## Current Behavior

Note: For testing purpose, session refresh is configured to 1 minute.

After the configured session refresh period the browser get a 302 redirect response to login.microsoft.com. 
The next request to that page failes and the console prints:

```
Access to XMLHttpRequest at 'https://login.microsoftonline.com/common/oauth2/authorize?...' (redirected from 'https://sub.sub.domain.com/Client?...') from origin 'https://sub.sub.domain.com/Client' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

OAuth2 Proxy logs:
```
[2021/01/12 13:47:42] [logger.go:490] Refreshing 1m6.246263874s old session cookie for Session{email:user@domain.com user: PreferredUsername: token:true id_token:true created:2021-01-12 13:46:35.753736126 +0000 UTC expires:2021-01-12 14:46:35 +0000 UTC refresh_token:true} (refresh after 1m0s)
[2021/01/12 13:47:42] [logger.go:508] Error loading cookied session: error refreshing access token for session (Session{email:user@domain.com user: PreferredUsername: token:true id_token:true created:2021-01-12 13:46:35.753736126 +0000 UTC expires:2021-01-12 14:46:35 +0000 UTC refresh_token:true}): session is invalid, removing session
127.0.0.1:57536 - - [2021/01/12 13:47:42] sub.sub.domain.com GET - "/WebClient;jsessionid=..." HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 302 437 0.002
```

If I click some link, OAuth2 Proxy logs:
```
[2021/01/12 14:31:27] [logger.go:508] Error loading cookied session: http: named cookie not present, removing session
127.0.0.1:41056 - - [2021/01/12 14:31:27] sub.sub.domain.com GET - "/WebClient;jsessionid=." HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 302 526 0.000
```

## Possible Solution

unknown

## Steps to Reproduce (for bugs)

```
            - --provider=azure
            - --provider-display-name="Azure AD"
            - --set-authorization-header=true
            - --pass-access-token=true
            - --pass-authorization-header=true
            - --pass-user-headers=true
            - --standard-logging=true
            - --skip-jwt-bearer-tokens=true
            - --skip-provider-button=true
            - --session-store-type=redis
            - --http-address=0.0.0.0:4180
            - --upstream=static://
            - --silence-ping-logging
            - --cookie-refresh=1h
            - --cookie-expire=168h
            - --skip-auth-regex=/rest/*
            - --skip-auth-preflight=true
```

```
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: ...
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: ...
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: ...
            - name: OAUTH2_PROXY_REDIS_CONNECTION_URL
              value: ...
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: domain.com
            - name: OAUTH2_PROXY_WHITELIST_DOMAINS
              value: .sub.domain.com
            - name: OAUTH2_PROXY_COOKIE_DOMAINS
              value: sub.domain.com
```

## Context

Since AzureAD standard session timeout uccures after 1 hour, the system can't be used after that period of time.

- Version used:
   - oauth2: v6.1.1
   - kubernetes: 1.19.3
   - istio: 1.7.3
